from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,sys
N=Path(__file__).resolve().parent;MON=N.parents[2];M=N.parents[4]
read=lambda p:json.loads(p.read_text('utf8'))
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n','utf8')
now=datetime.now(timezone.utc).isoformat()
sys.path.insert(0,str(MON));import monitor
ed=read(MON/'public-progress-editorial.json')
ed['current_work']=[{'short_label':'Sommer et al. (2020)','title':'Atomic Scale Design of Spinel ZnAl2O4 Nanocrystal Synthesis','stage':'Source, data and illustration audits passed; website integration in progress','summary':'The complete supplied main article has passed separate source, structured-data, molecular, apparatus and phase-context audits. The contribution preserves three laboratory routes, nine supporting procedures, seven observations, 31 illustrated stages and 20 selected original crops. Integrated website and publication checks remain.','stages':[{'label':'Supplied-main scientific review','status':'complete','detail':'All 11 supplied pages and 222 table cells reviewed. SI remains locally unlocated and unverified.'},{'label':'Data and illustration audits','status':'complete','detail':'19 records; 28 chemical identities; seven stocks; 31 apparatus scenes; 77 symbolic phase-component mappings with explicit sample evidence.'},{'label':'Website integration and publication','status':'in_progress','detail':'Independent metadata review passed; local integration, browser inspection and anonymous deployment verification remain.'}],'gaps':['Declared supporting information remains locally unlocated/unverified.','Source discrepancies and unresolved sample composition remain explicit. No exact atomic structure–recipe pair.']},{'short_label':'Matuhina et al. (2023)','title':'Role of CsMnCl3 Nanocrystal Structure on Its Luminescence Properties','stage':'Complete main/SI extraction and independent source reading','summary':'The next evidence-ranked paper has been admitted from the fixed collection. Its 13-page main article and 13-page SI have matching titles/bylines and verified file hashes. Two distinct readers are working in parallel on hot-injection synthesis, phase outcomes and luminescence.','stages':[{'label':'Main/SI pairing','status':'complete','detail':'Two unique documents; duplicate copies verified across both local collections.'},{'label':'Extraction and independent audit','status':'in_progress','detail':'All supplied pages, synthesis conditions, figures and sample assignments are being read. No completed review or public contribution is claimed yet.'}],'gaps':['Source review is ongoing; no public records or training eligibility approved.']}]
p=read(MON/'deadline-20260920/admission-20260920T111852Z/scope-partition.json');save(N/'latest-cutoff-counts.json',p['counts'])
ed['estimate']['current_batch']='Sommer source/data/illustration audits passed and website integration is underway. Matuhina CsMnCl3 main/SI extraction and a distinct independent review continue in parallel. Whole-corpus throughput and finish date remain unvalidated.'
save(MON/'public-progress-editorial.json',ed)
monitor.checkpoint(MON/'ledger.json','mattersyn-primary',group_id='10.1021_acs.cgd.9b01519',note='Complete supplied-main source/data/visual audits passed. SI remains unverified; independent metadata promotion passed, website integration/publication pending.',data={'current_step':'Integrating audited Sommer contribution','source_audit':str(N/'source-independent-audit/independent-audit-v2.json'),'canonical_audit':str(N/'canonical-reader-independent-audit/independent-audit-v2.json'),'promotion_audit':str(N/'site-integration-independent-audit/promotion-delta-audit.json')})
monitor.checkpoint(MON/'ledger.json','mattersyn-primary',group_id='10.1021_acsanm.2c04342',note='Main/SI content pairing and all duplicate hashes verified by author and distinct reviewer. Complete source extraction and independent reading underway.',data={'current_step':'Parallel source extraction and independent reading','title':'Role of CsMnCl3 Nanocrystal Structure on Its Luminescence Properties','main_pages':13,'si_pages':13,'review_folder':str(N.parent/'acsanm.2c04342')})
text=f'''## 2026-09-20 — Sommer scientific audits passed; Matuhina admitted

Saved {now}. Sommer source revision 2, canonical/reader revision 2, molecular overlay, 31 apparatus scenes and 77 explicit phase-component mappings passed separate independent audits. Promotion v1 freeze 05ac8e9e770d888613223b755d19e26552d35d8e84183d32f6f7ce833cebdd3d passed distinct audit 6802ccbe253a1e134469d2e67d51e6184e493b3baabff60b58b68e3c00447fee. There are 19 records (3 routes, 9 procedures, 7 observations), 532 measurement/context entries, 20 selected crops, 28 chemical identities and seven stocks. SI remains unlocated/unverified. Website integration, actual browser review and anonymous publication remain separate. The public dataset is still 0.28.0 / 567 records; do not claim Sommer public until verification.

Next fixed-cutoff claim: Matuhina et al. (2023), DOI10.1021/acsanm.2c04342, “Role of CsMnCl3 Nanocrystal Structure on Its Luminescence Properties.” Main13pages and SI13pages, two unique documents/four verified copies. Backlog authors complete extraction; Norberg reads and audits independently at batches/20260920-rolling-pipeline/acsanm.2c04342. Root/Peng finish Sommer integration in parallel. Intake: intake-20260920T111852Z; bundle1f4a99d36e2d6921df540a3b34f0ad2b6cf1fdc87ddf5766504c29b098953681. Do not restart closed Ghosh/Lian work or alter downloader files.

The reusable skill now explicitly separates nominal targets from observed phase components and unknown whole-specimen composition, and groups alternative schedules without pooling conditions. Project and installed skill references synchronized. The existing heartbeat, public filtered repositories, independent audits, fixed cutoff, no paper downloads and deferred paid API decision persist. Original PDFs/SI/raw full text/full pages remain local.
'''
f=M/'MEMORY.md';f.write_text(text+'\n'+f.read_text('utf8'),'utf8')
print('Memory, editorial and two existing claims checkpointed; no public claim made.')
