"""Manually read main-source facts. No SI, canonical or model approval is implied."""
FACTS=[]
def F(i,p,l,title,claim,scope,qs=(),flags=(),kind='reported'):
 FACTS.append((i,p,l,title,claim,scope,list(qs),list(flags),kind))
def Q(n,r,u):return(n,str(r),u)
F('identity',1,'Title, byline, abstract','Article identity','Sanna Sommer, Espen D. Bojesen, Hazel Reardon and Bo B. Iversen report atomic-scale guidance for ZnAl2O4 nanocrystal synthesis. The main article supplies microwave, supercritical-flow and autoclave experiments plus distinct in situ and precursor-solution measurements.','article')
F('scope',7,'Conclusions paragraph 1','Limits of cross-reactor transfer','Different reactors, concentrations and heating rates mean the in situ results give qualitative guidelines for laboratory syntheses. They do not establish identical reaction trajectories or exact sample joins across reactors.','all-samples',flags=['G2'])
F('reagents',7,'Experimental: Laboratory Synthesis','Starting reagents','Zn(NO3)2·6H2O and Al(NO3)3·9H2O are Sigma-Aldrich nitrate hydrates; NaOH and Al(OH)3 are also from Sigma-Aldrich. Nanosized ZnO is from Inframat Advanced Materials. Al(OH)3 purity is not stated.','all-methods',[Q('zinc nitrate hexahydrate purity','>=99','%'),Q('aluminum nitrate nonahydrate purity','>=98','%'),Q('NaOH purity','>=97','%'),Q('ZnO nominal particle size','~30','nm')])
F('workup',7,'Experimental: Laboratory Synthesis','Common laboratory powder workup','Separate as-synthesized powders from supernatant by centrifugation until the solution appears colorless. Wash the retained powders three times with demineralized water and once with 96% ethanol, then dry in a Thermo Scientific Heraeus vacuum oven. Centrifuge settings, solvent quantities, vacuum pressure and yields are absent. This workup is not automatically assigned to D-series solutions or in situ capillary observations.','M1-M9/S1-S2/A1-A6',[Q('water washes','3','count'),Q('ethanol washes','1','count'),Q('wash ethanol grade','96','%'),Q('drying temperature','50','degC'),Q('drying duration','4','h')],['G3'])
F('mw-stock',7,'Experimental: Microwave Synthesis','Microwave mixed-nitrate stock','Dissolve the two nitrate hydrates in demineralized water to obtain Zn:Al 1:2. The stated 20 mL is water charged, not an independently measured final solution volume.','MW-stock',[Q('Zn(NO3)2·6H2O mass','1.425','g'),Q('Al(NO3)3·9H2O mass','3.596','g'),Q('demineralized water charge','20','mL'),Q('Zn:Al molar ratio','1:2','ratio_parts')])
F('mw-base',7,'Experimental: Microwave Synthesis','Three base-adjusted formulations','Dissolve NaOH in separate aqueous Zn-Al mixtures to give the three stated final NaOH concentrations. Table 1 records their specimen-specific Zn:Al:OH ratios; exact NaOH masses and final mixture volumes are not supplied.','M1-M9/A1-A6',[Q('low final NaOH','1.5','M'),Q('middle final NaOH','1.7','M'),Q('high final NaOH','2.0','M')],['G3'])
F('mw-vessel',7,'Experimental: Microwave Synthesis','Microwave reactor loading','Transfer a 10 mL aliquot into a thick-walled 80 mL quartz reaction vessel in an Anton Paar Multiwave 3000 multisample multimode microwave digestion system. Pressure and temperature are sensed in a sapphire immersion tube. The vessel geometry is not an atomistic structure.','M1-M9',[Q('reaction aliquot','10','mL'),Q('quartz vessel capacity','80','mL')],['G3'])
F('mw-profile-1',8,'Equation 1 and following paragraph','Microwave heating profile 1','The printed sequence is RT to 130 °C in 1.45 min, then to 210 °C in 7.85 min, then to 240 °C in 15 min, then at 1 °C/min to the Table 1 target. It applies to M1-M3 and M7-M9. Table 1 total times remain independently reported and are not arithmetically reconciled with this sequence.','M1-M3/M7-M9',[Q('first set point','130','degC'),Q('first ramp duration','1.45','min'),Q('second set point','210','degC'),Q('second ramp duration','7.85','min'),Q('third set point','240','degC'),Q('third ramp duration','15','min'),Q('final ramp rate','1','degC/min')],['C1'])
F('mw-profile-2',8,'Equation 2 and following paragraph','Microwave heating profile 2','For M4-M6 the printed sequence is RT to 130 °C in 1.45 min and then to 250 °C in 7.45 min. The source separately reports total reaction and dwell times in Table 1.','M4-M6',[Q('first set point','130','degC'),Q('first ramp duration','1.45','min'),Q('second set point','250','degC'),Q('second ramp duration','7.45','min')],['C1'])
F('mw-pressure',8,'Microwave methods continuation','Microwave pressure and ramp rationale','The final slow ramp of profile 1 avoids sudden pressure spikes above manufacturer recommendations. Reaction pressure varied approximately over the reported interval; SI Figure S30 contains further settings and is unavailable locally.','M1-M9',[Q('reported approximate pressure interval','~40-60','bar')],['G1'])
F('scf-settings',8,'Supercritical Flow Synthesis','Supercritical-flow settings','An in-house SCF reactor cited to Hellstern et al. and Hald et al. is used with the stated pressure and two flow rates. This methods paragraph says 450 °C for each synthesis, but Table 1 and Results explicitly give S2 as 380 °C. The upstream reactor papers have not been read.','S1/S2',[Q('pressure','250','bar'),Q('methods temperature each synthesis','450','degC'),Q('solvent flow rate','14.5','mL/min'),Q('precursor flow rate','5','mL/min'),Q('OH concentration','0.18','M'),Q('Zn:Al:OH molar ratio','1:2:7','ratio_parts')],['C2','G4'])
F('acs-settings',8,'Autoclave Synthesis','Autoclave loading and durations','Use 20.0 mL Teflon-lined stainless-steel autoclaves filled with 10 mL of the precursor solutions described for microwave synthesis. Heat at 220 °C for either 1 day or 2.5 weeks in the methods. The long Table 1 entries instead say 17 days.','A1-A6',[Q('vessel capacity','20.0','mL'),Q('precursor fill','10','mL'),Q('set point','220','degC'),Q('short duration','1','day'),Q('methods long duration','2.5','week')],['C3','G3'])
F('acs-ramp-assumption',8,'Autoclave Synthesis','Assumed autoclave heating lag','Based on previous studies, the authors assume that the solution reaches 220 °C after approximately 45-60 min. This is not an observed temperature trace for every current sample.','A1-A6',[Q('assumed time to set point','~45-60','min'),Q('set point','220','degC')],kind='author_assumption')
F('insitu-nitrate-stock',8,'In Situ XRD: Zn(NO3)2 Based Solutions','Concentrated in situ nitrate stock','Prepare a 30.0 mL water-based solution containing the specified nitrate-hydrate masses, giving Zn:Al 1:2. This is a different stock from the microwave/autoclave feed.','I1-I14-stock',[Q('Zn(NO3)2·6H2O mass','8.552','g'),Q('Al(NO3)3·9H2O mass','21.572','g'),Q('solution volume','30.0','mL'),Q('Zn:Al ratio','1:2','ratio_parts')],['G5'])
F('insitu-mix',8,'In Situ XRD: Zn(NO3)2 Based Solutions','Equal-volume in situ mixing','Add 1.00 mL NaOH(aq) of varying concentration to 1.00 mL Zn-Al precursor solution. Final metal concentrations are 0.480 M Zn and 0.960 M Al. Table 1 gives the M/OH conditions. The basis of the table NaOH concentration is not explicitly harmonized with the laboratory final concentration; the zero-NaOH rows do not specify the corresponding diluent.','I1-I14',[Q('NaOH solution aliquot','1.00','mL'),Q('nitrate stock aliquot','1.00','mL'),Q('final Zn concentration','0.480','M'),Q('final Al concentration','0.960','M')],['G5'])
F('insitu-load',8,'In Situ XRD: Zn(NO3)2 Based Solutions','Stirring and capillary loading','After vigorous stirring for ca. 5 min, inject the resultant white slurry into a single-crystal sapphire capillary. The cited setup/uncertainty papers are not treated as newly read source evidence.','I1-I14',[Q('vigorous stirring duration','~5','min'),Q('capillary inner diameter','0.6','mm'),Q('capillary outer diameter','1.1','mm')],['G4'])
F('insitu-oxide-stock',8,'In Situ XRD: ZnO Based Solutions','Solid-oxide/hydroxide alternative','Mix dry nanosized ZnO and Al(OH)3 in a 1:2 molar ratio in Millipore water, giving the reported final metal concentrations. Stir for 4 h and inject into the sapphire capillary. This branch applies only to I15 and I16; the total water volume is not reported.','I15/I16',[Q('ZnO mass','0.8141','g'),Q('Al(OH)3 mass','1.561','g'),Q('ZnO nominal size','~30','nm'),Q('Zn:Al molar ratio','1:2','ratio_parts'),Q('final Zn concentration','0.5','M'),Q('final Al concentration','1','M'),Q('stirring duration','4','h')],['G5'])
F('insitu-acquisition',8,'In Situ XRD Experiments','In situ facilities and sequential fits','Experiments use beamline I711 at MAXlab and ID11 at ESRF; the article does not map each table row to a specific facility. Fullprof sequentially refines the in situ data. Pressure, exposure schedule and full apparatus specification remain in cited work/SI.','I1-I16',flags=['G1','G4'])
F('insitu-defects',8,'In situ refinement paragraph','Constrained defect model','Isotropic ADPs vary independently and become high; the authors attribute this to limited q-range, background, signal-to-noise and temperature. Antisite defects and interstitial Zn at (0,0,0) are refined under Zn/Al stoichiometry constraints. The complete refined values are in unavailable Table S7. This formula/site reference is not a complete coordinate set or a qualified measured CIF.','I1-I16-model',[Q('q-range endpoint','4.2','angstrom^-1')],['G1','G6'],kind='reported_model')
F('insitu-minor-phase',8,'In situ refinement paragraph','Minor-phase fitting restriction','When impurity amounts are minuscule, all impurity parameters except scale factor are fixed. Absence of a reported fitted amount must not be converted into zero impurity.','I1-I16-model',flags=['G6'])
F('lab-xrd',8,'Ex Situ XRD Analysis','Laboratory XRD acquisition','All laboratory samples are measured using Rigaku SmartLab Cu Kalpha1 radiation with Bragg-Brentano optics; Fullprof performs Rietveld refinement. Initial structural models are literature ICSD entries ZnAl2O4 39473, ZnO 26170 and AlOOH 59608, not new source-provided coordinate files.','M1-M9/S1-S2/A1-A6',flags=['G6'])
F('lab-fit',8,'Ex Situ XRD Analysis','Laboratory profile and size model','LaB6 NIST 660A determines instrumental resolution. A five-coefficient Chebyshev background and TCH pseudo-Voigt profiles are used; up to four spherical-harmonic functions describe anisotropic size/morphology.','laboratory-XRD',[Q('Chebyshev coefficient count','5','count'),Q('maximum spherical-harmonic functions','<=4','count')],['G6'],kind='reported_model')
F('synchrotron-xrd',8,'Ex Situ XRD Analysis','Selected-sample synchrotron acquisition','Selected M1-M3, M7, S1 and A1-A2 powders are packed in rotating 0.3 mm glass capillaries at SPring-8 BL44B2. Debye-Scherrer geometry and an image plate are used. The reported wavelength includes parenthetic uncertainty; CeO2 supplies resolution and wavelength calibration.','M1/M2/M3/M7/S1/A1/A2',[Q('glass capillary diameter','0.3','mm'),Q('wavelength','0.50054(6)','angstrom')],['G6'])
F('synchrotron-fit',8,'Ex Situ XRD Analysis','Synchrotron refinement','MAUD models a background combining four polynomial functions and two features for small-angle scattering/glass. Three spherical-harmonic functions represent anisotropic size broadening. For all laboratory-sample data, positions and occupancies are fixed to literature values; atom-type ADPs are refined as defect/disorder proxies and microstrain is not modeled.','laboratory-XRD',[Q('polynomial functions','4','count'),Q('additional background features','2','count'),Q('size spherical harmonics','3','count')],['G6'],kind='reported_model')
F('pdf-acquisition',8,'PDF Analysis','Total-scattering acquisition','P02.1 PETRA III total scattering uses a 2D detector, Fit2D integration and PDFgetX3 reduction. Measurements of deionized water in the same capillary type and at the same temperatures supply background. DiffPy CMI is used; PDFgui with LaB6 NIST 660b determines Qdamp.','D1-D4',flags=['G1','G5'])
F('pdf-fit',8,'PDF Analysis','Precursor PDF/reciprocal-space fits','D3 Zn clusters use the Debye approach with only scale fitted and literature-fixed ADPs. Crystalline D2 ZnO fits unit cell, scale and spheroid polar/equatorial size. Fullprof reciprocal refinement uses 16 variable-height background points, cell/zero/scale and Y00/Y40 size harmonics; other parameters are fixed. Values are in unavailable Tables S1-S2.','D2/D3',[Q('reciprocal background points','16','count'),Q('reciprocal size harmonics','2','count')],['G1','G6'],kind='reported_model')
F('tem-prep',8,'TEM','Electron microscopy specimen preparation','Sonicate dried powders dispersed in 99% ethanol, deposit individual drops on 200 mesh copper grids with Formvar/carbon support, and dry in ambient atmosphere. Sonication settings, deposited quantity and per-grid batch IDs are absent.','microscopy',[Q('dispersion ethanol grade','99','%'),Q('grid mesh','200','mesh')],['G3','G2'])
F('tem-acquire',8,'TEM','Electron microscopy acquisition','Bright-field TEM uses TALOS F200A, TWIN lens, X-FEG and Ceta 16M camera. HAADF-STEM and Super-X EDS maps are collected with Bruker Esprit and plotted using Hyperspy. The model name does not itself establish an explicit operating voltage. Element maps and their detailed results are in unavailable SI.','microscopy',flags=['G1','G6'])
F('uvvis-acquire',8,'UV-vis Spectroscopy','Diffuse-reflectance acquisition','Acquire at room temperature with a BaSO4 reference using Shimadzu UV-3101 PC over the stated wavelength interval. A2, M2 and S1 are the displayed optical contexts, without a new independently specified optical preparation recipe.','A2/M2/S1',[Q('measurement spectral interval','200-2500','nm')],['G2'])
F('uvvis-transform',8,'UV-vis Spectroscopy continued p9','Optical transformation as printed','The printed transformation and exponent are retained literally, with C called absorbance and S the scattering coefficient. The authors assign a direct transition at Gamma and use a straight-line Tauc fit shown in unavailable Figure S31. No precise M2/A2/S1 band-gap number is printed in the main text or on inset bars.','A2/M2/S1',[Q('source exponent x','1/2','ratio_parts')],['G1','G7'],kind='reported_model')
F('structures-background',2,'Introduction and Figure 1','Literature structural context','Normal spinel ZnAl2O4 has Fd-3m symmetry with oxygen 32e, tetrahedral Zn 8a and octahedral Al 16d. Figure 1 contrasts tetrahedral ZnO in P63mc and octahedral AlOOH in Cmcm. These are literature structural depictions, not measured new source coordinates.','literature-structures',flags=['G6'],kind='cited_context')
F('inversion-background',2,'Introduction','Cited inversion context','Prior work describes direct spinel or a maximum reported 33% inversion. This is cited background, not the measured inversion fraction of every present sample.','literature-structures',[Q('cited maximum inversion','33','%')],kind='cited_context')
F('d3-peaks',2,'Precursor structure and Figure 2','Zn-only precursor PDF','The Zn-only solution shows four strong short-range peaks below 3 angstrom; nitrate N-O is assigned at 1.2 angstrom and Zn-O near 2.0 angstrom. The source compares tetrahedral and octahedral reference distances and favors octahedral Zn-aquo monomers. The background reference to octahedral Zn in ZnAl2O4 is not silently substituted for the normal-spinel description.','D3',[Q('short-range peak count','4','count'),Q('short-range region','<3','angstrom'),Q('N-O assignment','1.2','angstrom'),Q('Zn-O assignment','~2.0','angstrom'),Q('cited tetrahedral Zn-O reference','1.8','angstrom')],['C10'],kind='reported_interpretation')
F('d3-fit',2,'Precursor structure continued p3','Octahedral Zn interpretation','The octahedral cluster describes the short-range PDF well; a combined tetrahedral/octahedral refinement gives 0 wt% tetrahedral. Broad correlations around 4.5 and 6 angstrom may involve dimers or solvent interactions but are not assigned as proven unique species.','D3',[Q('fitted tetrahedral cluster fraction','0','wt%'),Q('weak broad feature 1','~4.5','angstrom'),Q('weak broad feature 2','~6','angstrom')],['G6'],kind='reported_model')
F('d3-solution',2,'Precursor chemistry','Zn-only solution and protonation uncertainty','The Zn-only solution is 1 M with measured pH 5.5. The authors propose a general partially hydrolyzed octahedral zinc-aquo expression with unknown protonation parameter delta; X-rays are weakly sensitive to H. Exact protonation/solvation is not identified.','D3',[Q('Zn concentration','1','M'),Q('pH','5.5','pH')],['G6'],kind='reported_interpretation')
F('d4-solution',2,'Figure 4 and preceding discussion','Al-only and mixed precursor interpretations','The 1 M Al-only solution is associated with octahedral Al dimers as in previously cited work. D1’s mixed solution PDF is well represented by the sum of D3 and D4, with features out to about 8 angstrom. The native Figure 4b legend says 1:0:0 although the caption/prose identify the Al-only 0:2:0 solution.','D1/D4',[Q('Al-only concentration','1','M'),Q('mixed-solution correlation extent','~8','angstrom')],['C5','G5','G6'],kind='reported_interpretation')
F('d2-pdf',3,'Figure 3 and Figure 4','Base-added precursor','For D2 (Zn:Al:OH 1:2:8), adding NaOH yields strong ZnO correlations out to 70 angstrom; residual low-r intensity is attributed to Al-dimer correlations, while nitrate remains evident near 1.2 angstrom. This precursor ZnO is distinct from synthesized spinel product.','D2',[Q('correlation extent','70','angstrom'),Q('nitrate correlation','1.2','angstrom'),Q('Zn:Al:OH','1:2:8','ratio_parts')],['G6'],kind='reported_interpretation')
F('d2-size',3,'Figure 3 discussion','Precursor ZnO dimensions','Rietveld analysis of the base-added precursor is reported to give ZnO width 15.8(1) nm and length 26 nm along [001]. The source refers to unavailable SI refinements; the two dimensions are not isotropic spinel sizes.','D2',[Q('ZnO width','15.8(1)','nm'),Q('ZnO length along [001]','26','nm')],['G1','G6'])
F('formation-model',3,'Figure 5 and discussion continued p4','Proposed nucleation pathways','High M/OH (lower pH) favors octahedral Zn monomers; their recoordination may limit tetrahedral-Zn spinel nucleation and permit AlOOH formation. Low M/OH (higher pH) favors ZnO as a tetrahedral-Zn reservoir, with dissolution feeding spinel and residual ZnO as impurity. This is an author mechanism, not directly measured rates or resolved molecular intermediates.','formation-model',flags=['C7','G6'],kind='author_interpretation')
F('insitu-middle',4,'In Situ Synthesis','Middle-base in situ outcome','I4-I6 (Zn:Al:OH 1:2:7.3) yield phase-pure ZnAl2O4 under their Table 1 conditions. These row-specific temperatures are 350, 400 and 430 °C, not a universal 350 °C schedule.','I4/I5/I6',[Q('Zn:Al:OH ratio','1:2:7.3','ratio_parts')])
F('insitu-lowbase',4,'In Situ Synthesis and Figure 6','Low-base impurity consumption','I1/I2 initially contain AlOOH and ZnAl2O4; raising temperature to 430 °C after about 34 min consumes remaining AlOOH within a few minutes. The Figure 6 axes instead say Time(s). Direct 430 °C I3 shows only ZnAl2O4, but capillary turbulence prevents quantitative refinement.','I1/I2/I3',[Q('temperature after increase','430','degC'),Q('reported time before increase','~34','min')],['C4','G6'])
F('insitu-highbase',4,'In Situ Synthesis continued p5','High-base ZnO impurity','I9-I11 initially contain ZnO at 350, 400 and 430 °C; its consumption accelerates with temperature. Do not replace phase-consumption observations with exact completion times read from curves.','I9/I10/I11')
F('insitu-nobase',4,'In Situ Synthesis','No-base nitrate experiments','The text calls I12-I14 two experiments although Table 1 has three. The 450 and 475 °C experiments give phase-pure ZnAl2O4 at low crystallinity/yield and are difficult to refine. The 400 °C I14 row must not inherit those higher-temperature outcomes.','I12/I13/I14',[Q('higher temperature 1','450','degC'),Q('higher temperature 2','475','degC')],['C11','G2'])
F('insitu-oxide-outcome',4,'In Situ Synthesis','Oxide-feed conversion','With solid ZnO/Al(OH)3 feed, I15 at 425 °C reaches phase-pure ZnAl2O4 after extended reaction; I16 at 400 °C retains some ZnO. Exact completion time and yield are not printed.','I15/I16',[Q('I15 temperature','425','degC'),Q('I16 temperature','400','degC')],['G3'])
F('insitu-sizes',5,'Figure 7 and crystallite-size discussion','In situ crystallite-size trajectories','Spherical-domain refinements generally start at 2.5-3.5 nm and reach 3.5-7 nm; I12/I13 are around 15 nm. Higher temperature increases size without impurities, while impurity-mediated cases show complex trends. The author nucleation/depletion interpretation is not an independently measured growth law.','I1-I16',[Q('general initial size interval','2.5-3.5','nm'),Q('general final size interval','3.5-7','nm'),Q('I12/I13 approximate size','~15','nm')],['G6'])
F('mw-lowbase-outcome',5,'Laboratory Synthesis and Figure 8','Low-base M1 outcome','M1 contains approximately 51.4(4) wt% AlOOH and 48.6(4) wt% ZnAl2O4; no ZnO is detected. These are phase fractions, not synthetic yields.','M1',[Q('AlOOH fraction','~51.4(4)','wt%'),Q('ZnAl2O4 fraction','48.6(4)','wt%')])
F('mw-highbase-outcome',5,'Laboratory Synthesis and Figure 8','High-base M3 outcome','M3 contains 13(2) wt% ZnO and 0.4(1) wt% AlOOH, alongside the target spinel.','M3',[Q('ZnO fraction','13(2)','wt%'),Q('AlOOH fraction','0.4(1)','wt%')])
F('mw-middle-outcome',5,'Laboratory Synthesis and Figure 8','M2 phase-purity qualification','M2 is described as almost phase-pure or phase-pure, but a small AlOOH peak at 4.7 degrees is present below reliable quantification. A poorly modeled peak near 15 degrees is discussed in terms of defects. Neither observation is equivalent to confirmed zero impurity.','M2',[Q('small AlOOH peak position','4.7','deg2theta'),Q('poorly modeled peak position','15','deg2theta')],['C9','G6'])
F('mw-time-outcome',6,'Figure 10 and discussion','Microwave time comparison','At 250 °C M4-M6 contain AlOOH, decreasing from 12.5(3) wt% in M4 to 2.93(5) wt% in M6. M5 is plotted but has no exact printed fraction. M7, with no dwell at 280 °C, contains 1.53(3) wt% AlOOH.','M4/M5/M6/M7',[Q('M4 AlOOH fraction','12.5(3)','wt%'),Q('M6 AlOOH fraction','2.93(5)','wt%'),Q('M7 AlOOH fraction','1.53(3)','wt%')],['G7'])
F('mw-heating-outcome',6,'Figure 10 and discussion','Heating-path comparison','Figure 10 compares M4-M6 at 250 °C with M2 and M7 at 280 °C, plotting AlOOH fraction against dwell time. The numerical impurity trend is displayed graphically without a complete printed data table; preserve sample-linked curves and Table 1 conditions without digitizing invented exact outcomes.','M2/M4/M5/M6/M7',flags=['G7'])
F('scf-outcome',6,'Supercritical flow results','SCF temperature dependence','S1 at 450 °C is phase-pure; S2 at 380 °C contains 49(3) wt% ZnO. The method paragraph says 450 °C for each synthesis, retained as a conflict.','S1/S2',[Q('S1 temperature','450','degC'),Q('S2 temperature','380','degC'),Q('S2 ZnO fraction','49(3)','wt%')],['C2'])
F('acs-outcome',6,'Figure 11 and autoclave discussion','Autoclave phase outcomes','A2 after 17 days is phase-pure; A5 after one day contains 31.25(2) wt% AlOOH. A3 and A6 contain 5.5(1) and 7.7(1) wt% ZnO, respectively. A4 is AlOOH without detected spinel and A1 is almost phase-pure ZnAl2O4 with AlOOH below the quantification limit. The Figure 11 caption color labels disagree with the plotted sample colors and prose.','A1-A6',[Q('A5 AlOOH fraction','31.25(2)','wt%'),Q('A3 ZnO fraction','5.5(1)','wt%'),Q('A6 ZnO fraction','7.7(1)','wt%')],['C3','C6'])
F('phasepure-size',6,'Crystallite sizes and Figure 12','Selected phase-pure sample sizes','Reported refined crystallite sizes are 2.4(1) nm for M2, 17.0(1) nm for S1 and 52.4(6) nm for the larger A2 population. These are diffraction model results, not direct exact TEM diameters.','M2/S1/A2',[Q('M2 refined size','2.4(1)','nm'),Q('S1 refined size','17.0(1)','nm'),Q('A2 larger refined size','52.4(6)','nm')],['C8','G6'])
F('acs-bimodal-size',6,'Crystallite sizes discussion','Autoclave bimodal size models','A1 is modeled with two size populations of 40.6(5) and 90.4(1) nm; A2 with 7.42(6) and 52.4(6) nm. These values must retain their individual sample and model-population assignments, rather than become one common product size range.','A1/A2',[Q('A1 smaller population','40.6(5)','nm'),Q('A1 larger population','90.4(1)','nm'),Q('A2 smaller population','7.42(6)','nm'),Q('A2 larger population','52.4(6)','nm')],['C8','G6'])
F('tem-morphology',6,'Figure 12 and discussion','Morphology and size distributions','TEM images of S1, M2 and A2 show broadly octahedral nanocrystals: microwave products are comparatively narrow, SCF broader and autoclave polymodal. Figure 12d is the refined shape of S1 based on spherical harmonics, not an experimentally solved atomic model.','S1/M2/A2',[Q('Figure 12a S1 scale bar','10','nm'),Q('Figure 12b M2 scale bar','30','nm'),Q('Figure 12c A2 scale bar','0.25','um')],['G6'])
F('optical-outcome',7,'Figure 13 and preceding discussion','Method-dependent optical comparison','The Kubelka-Munk/Tauc presentation compares M2, A2 and S1 and shows different apparent band gaps. Exact bar values are not printed. The authors associate differences with defects/disorder while acknowledging that disentangling size and inversion requires further study. Do not infer exact band-gap labels by reading bar heights.','M2/A2/S1',flags=['G7'],kind='reported_interpretation')
F('optical-literature',7,'Paragraph before Conclusions','Cited band-gap ranges','The theory range 3.4-4.5 eV and earlier experimental range 3.7-4.9 eV are literature context, not current sample-specific measurement rows.','literature-band-gap',[Q('cited theory range','3.4-4.5','eV'),Q('cited experiment range','3.7-4.9','eV')],kind='cited_context')
F('conclusion-range',7,'Conclusions','Literal conclusion range','The conclusion says crystallite size can be tailored from 2 to 42 nm and microwave crystallites are about 2 nm. This summary conflicts with larger explicit A1/A2 values; retain it as a source claim without replacing the measured/model-derived result entries.','article-summary',[Q('conclusion size range','2-42','nm'),Q('conclusion microwave size','2','nm')],['C8'])
F('conclusion-coordination',7,'Conclusions final paragraph','Coordination inconsistency in conclusion','The final conclusion paragraph says low M/OH gives octahedral Zn monomers, whereas the earlier discussion and preceding conclusion paragraph identify high M/OH as the octahedral-monomer regime. No silent choice resolves this contradiction.','formation-model',flags=['C7'],kind='author_interpretation')
F('si-availability',9,'Associated Content','Declared but unlocated SI','The main declares a Supporting Information PDF with precursor PDF, in situ/laboratory XRD, electron microscopy, microwave power/rate and UV-vis/Rietveld details. Bounded local filename and existing-cache searches have not located a matched SI. Main citations to Tables S1-S7 and Figures S1-S31 are pointers, not read SI content.','source-availability',flags=['G1'])

TABLE='''M1 1.5 280 1:2:6.25 124.5 30
M2 1.7 280 1:2:7.09 124.5 30
M3 2.0 280 1:2:8.34 124.5 30
M4 1.7 250 1:2:7.09 39.5 30
M5 1.7 250 1:2:7.09 99.5 90
M6 1.7 250 1:2:7.09 189.5 180
M7 1.7 280 1:2:7.09 94.5 0
M8 1.7 260 1:2:7.09 124.5 50
M9 1.7 270 1:2:7.09 124.5 40
S1 0.18 450 1:2:7 ~1 0
S2 0.18 380 1:2:7 ~1 0
A1 1.5 220 1:2:6.25 17day 17day
A2 1.7 220 1:2:7.09 17day 17day
A3 2.0 220 1:2:8.34 17day 17day
A4 1.5 220 1:2:6.25 1day 1day
A5 1.7 220 1:2:7.09 1day 1day
A6 2.0 220 1:2:8.34 1day 1day
I1 6.0 350 1:2:6.25 0-40 0-40
I2 6.0 400 1:2:6.25 0-40 0-40
I3 6.0 430 1:2:6.25 0-40 0-40
I4 7.0 350 1:2:7.30 0-40 0-40
I5 7.0 400 1:2:7.30 0-40 0-40
I6 7.0 430 1:2:7.30 0-40 0-40
I7 7.5 350 1:2:7.81 0-40 0-40
I8 7.5 400 1:2:7.81 0-40 0-40
I9 8.0 350 1:2:8.34 0-40 0-40
I10 8.0 400 1:2:8.34 0-40 0-40
I11 8.0 430 1:2:8.34 0-40 0-40
I12 0 450 1:2:0 0-40 0-40
I13 0 475 1:2:0 0-40 0-40
I14 0 400 1:2:0 0-40 0-40
I15 0 425 1:2:0 0-40 0-40
I16 0 400 1:2:0 0-40 0-40
D1 0 RT 1:2:0 3.3 3.3
D2 8.0 RT 1:2:8 3.3 3.3
D3 0 RT 1:0:0 3.3 3.3
D4 0 RT 0:2:0 3.3 3.3'''

CONFLICTS=[
('C1','Printed microwave profiles versus total times','Equations 1-2 ramp durations do not directly sum to Table 1 total-minus-dwell values. Both are literal source observations; do not invent a missing hold/ramp.',[4,8]),
('C2','SCF temperature conflict','Methods say 450 °C for each synthesis; S2 is 380 °C in Table 1 and Results.',[4,6,8]),
('C3','Long autoclave duration','Methods say 2.5 weeks; Table 1/Results use 17 days. Retain both without equating exact durations.',[4,6,8]),
('C4','Figure 6 time units','Figure 6 axes print Time(s), while caption/prose describe an increase after about 34 min and Table 1 gives minutes.',[4]),
('C5','Figure 4b precursor legend','Native legend says 1:0:0; caption/prose identify Al-only 0:2:0 (D4).',[3]),
('C6','Figure 11 impurity-color caption','Caption says green AlOOH/orange ZnO; plotted sample assignments and text identify green A3/A6 as ZnO and orange A4/A5 as AlOOH.',[6]),
('C7','Conclusion coordination regime','Final conclusion says low M/OH gives octahedral monomers; earlier discussion and same-page preceding conclusion say high M/OH.',[3,7]),
('C8','Conclusion size range','Summary 2-42 nm conflicts with explicit A2 52.4(6) nm and A1 90.4(1) nm populations.',[6,7]),
('C9','Qualified M2 phase purity','M2 is called phase-pure but a tiny AlOOH peak is reported below reliable quantification. Preserve detection versus quantification limits.',[5,6]),
('C10','Zn coordination reference wording','The short-range PDF discussion calls the 2.0 angstrom Zn reference octahedral in ZnAl2O4; the normal-spinel structural description places Zn tetrahedrally. Keep source context; no new coordination determination.',[2]),
('C11','No-base experiment count','The text says two experiments (I12-I14), while Table 1 has three rows at 450, 475 and 400 °C. Do not assign high-temperature outcomes to I14 by range shorthand.',[4])]
GAPS=[
('G1','Supporting information unlocated','Only one unique main PDF is locally verified. Declared SI tables/figures, detailed refinements and settings remain unread/unverified; this package completes supplied main scope only.'),
('G2','Cross-context sample identity','Named Table 1 samples link their stated main figures and results, but no unique physical aliquot/batch identifiers prove universal cross-technique or cross-reactor identity.'),
('G3','Incomplete operational fields','NaOH masses, several final volumes, centrifuge speed/time, wash quantities, vacuum pressure and product yields are not reported; unknowns are not zero or default protocol settings.'),
('G4','Upstream apparatus/source limits','Cited reactor/setup/uncertainty papers have not been read. SCF feed formulation and complete in situ pressure/exposure/heating details are not reproduced in the main.'),
('G5','Solution concentration and preparation scope','Keep charged water versus final solution volume, NaOH-column basis, I12-I14 zero-base mixing and D1/D2 absolute metal concentrations unresolved where not explicit.'),
('G6','Structure/model limits','Main gives no complete atomic coordinates/lattice/refinement table for qualified product CIF. Literature-fixed structural parameters, partial site/formula expressions, phase fractions and refined sizes remain correctly separated.'),
('G7','Graph-only outcomes','Exact optical gap values, several impurity fractions and trajectory coordinates are not printed. Original graphics are retained; no new numeric labels from visual estimates.')]

FIGURES=[
('graphical-abstract',1,'Graphical abstract','Conceptual precursor/route-to-spinel overview',['formation-model'],[],(.552,.274,.911,.451)),
('figure-1',2,'Figure 1','Literature ZnAl2O4, ZnO and AlOOH structures',['literature-structures'],['G6'],(.09,.076,.489,.439)),
('figure-2',2,'Figure 2','D3 Zn-only short-range PDF and cluster comparisons',['D3'],['G6','C10'],(.512,.209,.911,.449)),
('figure-3',3,'Figure 3','D1 mixed-precursor PDF versus the sum of D3 Zn and D4 Al PDFs',['D1','D3','D4'],['G6'],(.09,.073,.489,.347)),
('figure-4',3,'Figure 4','D2 ZnO PDF fit and residual comparison with D4 Al solution',['D2','D4'],['C5','G6'],(.09,.480,.489,.744)),
('figure-5',3,'Figure 5','Author-proposed high/low M/OH formation pathways',['formation-model'],['C7','G6'],(.512,.219,.911,.532)),
('figure-6',4,'Figure 6','I1/I2 phase evolution after temperature increase',['I1','I2','I9','I10','I11'],['C4'],(.512,.068,.911,.317)),
('figure-7',5,'Figure 7','Selected in situ crystallite-size trajectories',['I4','I5','I6','I9','I10','I11'],['G6','G7'],(.09,.350,.489,.583)),
('figure-8',5,'Figure 8','M1-M3 diffraction comparison and marked impurities',['M1','M2','M3'],['C9'],(.512,.151,.911,.383)),
('figure-9',5,'Figure 9','M2 Rietveld refinement and trace AlOOH inset',['M2'],['C9'],(.512,.472,.911,.746)),
('figure-10',6,'Figure 10','AlOOH fraction versus dwell time at 250 and 280 °C',['M4','M5','M6','M2','M7'],['G7'],(.09,.073,.489,.376)),
('figure-11',6,'Figure 11','Autoclave phase fractions and diffraction',['A1','A2','A3','A4','A5','A6'],['C6'],(.512,.073,.911,.354)),
('figure-12',6,'Figure 12','S1/M2/A2 TEM and model-refined S1 morphology',['S1','M2','A2'],['G6'],(.512,.355,.911,.72)),
('figure-13',7,'Figure 13','Optical comparison and unlabeled band-gap bars',['M2','A2','S1'],['G7'],(.09,.072,.489,.313))]

PAGE_NOTES=[
'Title/byline/abstract, graphical abstract and Introduction; distinguish cited spinel uses/claims from new synthesis data.',
'Introduction and literature crystal structures, complete Figure 1 and Figure 2; Zn-only PDF peak/model discussion.',
'Precursor protonation and mixed/alkaline solution discussion; Figures 3-5 and their captions/model limitations; Figure 4b legend conflict.',
'All 37 Table 1 rows, all five data columns and nomenclature footnote; in situ outcomes; Figure 6 and seconds/minutes conflict.',
'In situ phase/size discussion and Figure 7; laboratory microwave outcomes and Figures 8-9, all phase-fraction ESDs.',
'Microwave/SCF/autoclave comparisons, Figures 10-12, all quantitative fractions/bimodal sizes and color/sample conflicts.',
'Figure 13, literature band-gap ranges, conclusions with conflicting size and M/OH claims; reagents/workup/microwave stock and vessels.',
'Both literal heating profiles; SCF/ACS/in situ recipes, defect formula, all XRD/PDF/TEM/optical acquisition/refinement methods.',
'Optical-method ending; Supporting Information declaration, author/acknowledgment notes and references 1-20.',
'References continued, 21-54; cited studies retained as references only, not read source evidence.',
'References 55-65 and footer. Complete supplied-main scope; no local SI file was read or inferred.']
