from pathlib import Path

root=Path(__file__).parent
source=(root/'refine_proposal.py').read_text(encoding='utf-8')
changes={
0: 'MatterSyn for Predicting Nanocrystal Synthesis',
2: 'Nanocrystals are nanometre-sized particles with an ordered arrangement of atoms. Their size, shape, and composition influence their optical and electronic properties, making them useful in technologies ranging from quantum-dot displays [1] to emerging research on diamond-based quantum sensing and computing [2]. A major scientific challenge is to produce particles with the required characteristics reproducibly. This is particularly difficult for materials such as diamond, whose atoms form a strongly bonded network. Predictive synthesis methods could broaden the range of accessible materials and support advances in semiconductor, optoelectronic, and quantum technologies.',
3: 'We are developing MatterSyn, a materials synthesis data platform that combines a curated database with an interactive website [3]. The database organizes synthesis recipes: reported instructions specifying the starting chemicals, their quantities, reaction conditions, and purification steps. It connects these instructions to measurements of the resulting particles, such as their size, atomic arrangement, and light emission. Each record retains links to the source paper and available supporting information, allowing users to examine the evidence. MatterSyn therefore provides both a resource for experimental researchers and structured data for training predictive models.',
5: 'The public MatterSyn pilot [3] contains 675 structured records from 41 source contributions, including 123 synthesis routes or variants across 39 material systems. Other records describe supporting procedures or measurements, so the total is not a count of independent synthesis experiments. This pilot establishes a working data format and a process for checking records against published evidence. Our longer-term target is approximately 13,500 structured records, about twenty times the current collection; the number suitable for model training will depend on their completeness and review.',
10: 'Dataset construction. We will identify papers that report usable synthesis procedures, remove duplicates, and match each main article to its supporting information. Extraction will capture the starting chemicals, quantities, order of operations, temperature, reaction atmosphere, purification steps, and measurements of the resulting particles. Language and vision models will assist with reading text, tables, and figures. A separate audit will check each record against the source, with human review of ambiguous cases. A manually checked benchmark of 200 paper groups will measure extraction accuracy, including numerical values, units, and links between recipes and measured samples. Missing information will remain explicit, and only audited records will enter training and public release.',
11: 'Recipe prediction and evaluation. We will compare three approaches: retrieving similar published recipes, generating recipes from retrieved text, and fine-tuning open-weight models with 1–8 billion parameters. Fine-tuning will update a small set of model parameters rather than train a language model from scratch. All approaches will use the same literature collection. Evaluation papers, their supporting information, and closely related recipes will be withheld from both training and retrieval. We will assess the proposed chemicals and conditions, support from cited sources, and whether the instructions are complete enough to execute. Experiments will determine whether a recipe produces the desired particles. The initial models will target composition and measured particle characteristics; prediction from complete atomic structures requires matched structure–recipe data that the current collection does not yet contain.',
12: 'Experimental feedback. We plan to test predictions in Professor Paul Alivisatos\'s laboratory alongside model development. Targets and success criteria, such as particle size, internal atomic arrangement, or light emission, will be selected before inspecting model outputs. We will compare model proposals with published starting recipes, record unsuccessful outcomes, and repeat promising conditions to assess reproducibility. The results will inform subsequent model updates. A separate set of targets will evaluate the updated model, so experiments used for fine-tuning do not also serve as its final test.',
14: 'Months 1–2 will focus on screening and dataset construction. During the first two weeks, papers of different lengths and formats, including scanned documents and extensive supplementary files, will establish runtimes, memory use, and charged SUs. Papers will run independently through Slurm job arrays. We will reuse extracted text, batch inference by input length, and checkpoint completed work. The first release will prioritize complete synthesis procedures with measurements clearly linked to the particles produced; its size will depend on audit capacity.',
}
lines=source.splitlines()
for index,newtext in changes.items():
    matches=[i for i,line in enumerate(lines) if line.startswith(str(index)+': ')]
    assert len(matches)==1,index
    lines[matches[0]]=str(index)+': '+repr(newtext)+','
source='\n'.join(lines)+'\n'
source=source.replace('MatterSyn_RCC_Research_II_Proposal_Refined.docx','MatterSyn_RCC_Research_II_Proposal_Revised.docx')
aims='The proposed research will use MatterSyn to train and validate models that recommend synthesis recipes for specified particle characteristics. We will test whether learning from structured records improves predictions compared with literature retrieval and generation from unstructured text. Our initial focus is colloidal semiconductor nanocrystals: small crystals of semiconductor materials prepared in liquids. Selected predictions will be evaluated in Professor Paul Alivisatos\'s laboratory. The expected outcomes are a curated dataset, reproducible model comparisons, and experimentally evaluated recipes.'
anchor='scope = original[6].insert_paragraph_before('
assert source.count(anchor)==1
source=source.replace(anchor,'original[4].insert_paragraph_before('+repr(aims)+')\n\n'+anchor)
source=source.replace('the characterization methods available in the Alivisatos lab','the methods available to measure particle size, structure, and optical properties in the Alivisatos lab')
target=root/'refine_proposal_accessible.py'
target.write_text(source,encoding='utf-8')
print('Prepared',target)
