"""Adapt established read-only checks; does not execute against an unready Site."""
from pathlib import Path
B=Path(__file__).resolve().parents[1];old=B.parent/'nl015685v';O=B/'public-review-proposal'
text=(old/'public-review-proposal/validate_proposal.py').read_text(encoding='utf8').replace('besson2002','dantas2002').replace("source['main_page_count'],6","source['main_page_count'],5").replace('list(range(1,44))','list(range(1,22))').replace('range(1,5)))','range(1,8)))')
start=text.index('for num,target in [(2,');end=text.index("result={'status'",start)
text=text[:start]+"ck('Figure 3 remains pure theory',assets['figure-3']['sample_links'],['dantas-2002-parabolic-model','dantas-2002-four-band-model'])\nck('Figure 4 remains AFM cohorts',assets['figure-4']['sample_links'],['dantas-2002-afm1','dantas-2002-afm2','dantas-2002-afm-analysis'])\nck('Figure 6 remains SG1',assets['figure-6']['sample_links'],['dantas-2002-sg1','dantas-2002-power-response','dantas-2002-mechanisms'])\n"+text[end:]
(O/'validate_proposal.py').write_text(text,encoding='utf8')
text=(old/'reader-assets/check_reader_runtime.mjs').read_text(encoding='utf8').replace('besson2002','dantas2002').replace('Besson2002','Dantas2002').replace('130','101').replace('===10','===11').replace('All 10 original','All 11 original').replace('Four original figure cards','Seven original figure cards').replace('figureCards.length===4','figureCards.length===7').replace('Six-page','Five-page').replace("includes('6 pages')","includes('5 pages')").replace('===36','===48').replace('All 36','All 48').replace('===44','===67').replace('All 44','All 67').replace("input.value='copolymer'","input.value='AFM1'")
start=text.index("check('SI search limitation explicit'");end=text.index('const input=',start)
text=text[:start]+"check('SI search limitation explicit',/no local SI was matched/.test(cardMap.get('coverage')?.textContent||''));\ncheck('Size versus radius ambiguity explicit',cardMap.get('size-radius-boundary')?.textContent.includes('radius'));\ncheck('Crucible source anomaly explicit',cardMap.get('crucible')?.textContent.includes('aluminum'));\ncheck('No invented Raman acquisition',cardMap.get('raman-boundary')?.textContent.includes('Raman-shift'));\n"+text[end:]
(B/'reader-assets/check_reader_runtime.mjs').write_text(text,encoding='utf8')
text=(old/'reader-assets/check_integrated_presentation.py').read_text(encoding='utf8').replace('besson2002','dantas2002').replace('Besson 2001','Dantas 2002').replace('12 records / 36 operations / 98 measurements','16 records / 48 operations / 110 measurements').replace('len(records)==12','len(records)==16').replace("for r in records.values())==36","for r in records.values())==48").replace("for r in records.values())==98","for r in records.values())==110").replace('2 literature protocols / 1 protocol variant / 7 procedures / 2 observations','6 literature protocols / 8 procedures / 2 observations').replace('Counter(literature_protocol=2,protocol_variant=1,procedure=7,observation=2)','Counter(literature_protocol=6,procedure=8,observation=2)').replace('130 reader','101 reader').replace('len(items)==130','len(items)==101').replace('173 source','147 source').replace("len(source['units'])==173","len(source['units'])==147").replace('10 original assets','11 original assets').replace('len(assets)==10','len(assets)==11').replace('==[4,0,0,6]','==[7,0,0,4]').replace("runtime['reader_items']==130","runtime['reader_items']==101").replace("runtime['unique_original_assets']==10","runtime['unique_original_assets']==11").replace("runtime['operation_count']==36","runtime['operation_count']==48").replace('10 originals','11 originals').replace('36 operation scenes','48 operation scenes').replace("'records':12,'operations':36,'measurements':98,'reader_items':130,'source_units':173,'original_assets':10","'records':16,'operations':48,'measurements':110,'reader_items':101,'source_units':147,'original_assets':11")
start=text.index(' expected_structure={');end=text.index(' def structural(',start)
text=text[:start]+" expected_structure={'source_reported_optically_inferred_qd_size','source_reported_afm_qd_size','figure_reported_afm_grain_height','figure_reported_afm_substrate_depth','reported_afm_size_distribution','figure4a_panel_scope','figure4b_panel_scope','figure4_histogram_displayed_depth_range','figure4_histogram_axis_labels','author_afm_growth_observation','author_optical_afm_comparison'}\n"+text[end:]
text=text.replace("'Optical confinement threshold stays under Properties',not structural('author_weak_confinement_size_threshold')","'Electronic model threshold stays under Properties',not structural('source_strong_confinement_size_upper_bound')")
text=text.replace("m['property']=='author_weak_confinement_size_threshold'","m['property']=='source_strong_confinement_size_upper_bound'")
start=text.index(' for num,target in [(2,');end=text.index(" ck('Missing SI",start)
text=text[:start]+" ck('Figure 3 pure model association',assets['figure-3']['sample_links']==['dantas-2002-parabolic-model','dantas-2002-four-band-model'])\n ck('Figure 4 AFM cohort association',assets['figure-4']['sample_links']==['dantas-2002-afm1','dantas-2002-afm2','dantas-2002-afm-analysis'])\n ck('Figure 6 SG1 association',assets['figure-6']['sample_links']==['dantas-2002-sg1','dantas-2002-power-response','dantas-2002-mechanisms'])\n"+text[end:]
(B/'reader-assets/check_integrated_presentation.py').write_text(text,encoding='utf8')
print('Prepared read-only candidate and actual-build checker helpers. Actual-build checks not run.')
