from pathlib import Path
import json
B=Path(__file__).resolve().parents[1];O=B/'public-review-proposal';read=lambda p:json.loads(p.read_text(encoding='utf8'))
mapping={}
def group(target,ids):
 for s in ids.split():mapping['schwartz2003-'+s]=target.split()
group('identity','identity-title identity-journal')
group('identity affiliation','identity-authors identity-dates identity-administrative')
group('sample-boundaries','context-scope context-spectroscopy-scope')
group('motivation','context-spintronics context-controversy')
group('nucleation-threshold solubility-model giant-zeeman aggregation-interpretation','context-summary')
group('colloid-rationale dmso','context-solution-motivation')
group('dopant-problem','context-surface-risk')
group('zinc-stock','precursor-zinc')
group('base-stock stock-conflict','precursor-base')
group('cobalt-source','precursor-cobalt')
group('nickel-source','precursor-nickel')
group('dopant-substitution','precursor-fixed-metal protocol-doped-feed')
group('antisolvents workup','precursor-antisolvent protocol-initial-isolation')
group('dmso ethanol toluene workup','precursor-redispersion')
group('dodecylamine','precursor-dodecylamine')
group('topo','precursor-topo')
group('analysis-materials','precursor-supports')
group('zinc-stock base-stock','protocol-typical-stocks')
group('alkaline-growth','protocol-addition')
group('clarity clarity-reagent','protocol-clarity')
group('aggregation','protocol-aggregation aggregate-preparation')
group('remove-zinc','protocol-remove-zinc')
group('amine-workup','protocol-amine-isolation protocol-amine-cycles')
group('topo-heating','protocol-topo-heat')
group('topo-cooling','protocol-topo-cool')
group('topo-redispersion','protocol-topo-redispersion protocol-colloid-stability')
group('colloid-rationale','protocol-open-air')
group('xrd-method','method-xrd')
group('microscopy-method','method-electron method-sem')
group('icp-method','method-icp')
group('absorption-method','method-absorption-rt method-size-estimate')
group('lowtemp-absorption','method-absorption-lowt postprocess-films')
group('mcd-method','method-mcd')
group('mcd-definition','method-mcd-definition')
group('zeeman-method','method-zeeman')
group('magnetometry-method','method-squid')
group('pure-kinetics stock-conflict','kinetics-small-charge')
group('pure-kinetics pure-formation','kinetics-sampling kinetics-focusing')
group('pure-titration stock-conflict','kinetics-titration')
group('pure-base-response','kinetics-nucleation')
group('pure-base-response pure-intensity','kinetics-metastable-size nucleation-model-size-ceiling')
group('thermal-ripening thermal-response','kinetics-heated-ripening')
group('pure-tem room-aging','pure-structure-aged pure-structure-diameter')
group('pure-diffraction pure-tem','pure-structure-phase')
group('co-titration','cobalt-titration-feed')
group('co-color','cobalt-titration-colors cobalt-titration-starting cobalt-titration-bandgap')
group('co-intermediate','cobalt-titration-intermediate')
group('co-intermediate co-isosbestic','cobalt-titration-internal')
group('dopant-series nickel-source','cobalt-titration-series-method')
group('dopant-energy','cobalt-titration-series-co cobalt-titration-series-ni')
group('co-tem microscopy-method','cobalt-structure-cohort cobalt-structure-size')
group('co-diffraction','cobalt-structure-phase')
group('co-spectra','optical-co-cohort optical-co-lf')
group('co-ct-band','optical-co-ct optical-co-chromophore ct-model-co-bound')
group('mcd-relative','optical-co-ratio optical-ni-weak')
group('ni-spectra','optical-ni-cohort optical-ni-regions')
group('fine-structure ni-fine','optical-fine-width')
group('field-co','magneto-co-saturation magneto-co-energy-conflict')
group('field-ni','magneto-ni-saturation')
group('zeeman-results','magneto-zeeman-data')
group('aggregate-morphology','magneto-aggregate-cohort')
group('magnetic-loop','magneto-hysteresis')
group('curie-bound','magneto-curie')
group('basic-acetate','nucleation-model-clusters')
group('lf-localization','nucleation-model-lf-assignment-conflict')
group('co-isosbestic','nucleation-model-deconvolution nucleation-model-base-use')
group('nucleation-threshold','nucleation-model-exclusion')
group('intermediate-model co-isosbestic','nucleation-model-intermediate-speciation')
group('intermediate-model','nucleation-model-sequence scheme-1')
group('dopant-number','nucleation-model-suppression nucleation-model-base-control')
group('geometry-barrier solubility-model','nucleation-model-barriers')
group('solubility-model equation3','nucleation-model-gibbs-thompson')
group('solubility-model','nucleation-model-critical-radius')
group('cleaning-rationale','postprocess-ics postprocess-surface-clean postprocess-homogeneity')
group('cleaning-structure ni-tem si-bandgap-comparison','postprocess-ripening')
group('lf-localization fine-structure','ligandfield-co-match')
group('sum-rule','ligandfield-co-sum ligandfield-ni-sum')
group('ni-fine','ligandfield-ni-origins')
group('fano','ligandfield-fano')
group('quenching','ligandfield-emission')
group('no-lf-emission','ligandfield-emission-limit')
group('ni-ct equation4','ct-model-ni-lmct')
group('co-ct-assignment','ct-model-co-assignment')
group('electronegativity-parameters','ct-model-halide-comparison ct-model-electronegativity')
group('ct-parameters','ct-model-nickel-parameters ct-model-cobalt-parameters')
group('ct-prediction','ct-model-prediction')
group('oxide-electronegativity','ct-model-oxide-electronegativity')
group('confinement-electronegativity','ct-model-confinement')
group('equation7 ct-intensity','ct-model-covalency')
group('ct-intensity ct-wording-conflict','ct-model-weak-mlct')
group('giant-zeeman equation8','ct-model-exchange')
group('equation8','ct-model-fixed-alpha')
group('valence-model','ct-model-zero-field')
group('co-exchange','exchange-co-fit exchange-anisotropy')
group('volume-scaling table2-comparators','exchange-scaling-comparator')
group('lattice-context','exchange-lattice-reference')
group('ni-exchange','exchange-ni-estimate')
group('co-ground-state','exchange-co-spin')
group('ni-ground-state','exchange-ni-spin')
group('ni-ground-state bterm-wording','exchange-ni-second-order')
group('aggregate-phase','aggregate-structure')
group('aggregation-interpretation','aggregate-ordering')
group('magnetic-fractions','aggregate-moment')
group('equation10','aggregate-anisotropy-model')
group('domain-estimate','aggregate-domain-spin aggregate-domain-size')
group('interface-hypothesis','aggregate-interface-hypothesis')
group('outlook','conclusion-outlook')
group('funding','conclusion-funding')
group('si-identity','conclusion-si-declaration si-identity')
group('pure-kinetics pure-formation','figure-1a')
group('pure-titration pure-base-response','figure-1b')
group('thermal-ripening thermal-response','figure-1c')
group('pure-tem room-aging','figure-2a figure-2b')
group('pure-diffraction','figure-2c figure-2d')
group('co-color','figure-3-photos')
group('co-titration co-intermediate co-isosbestic','figure-3-spectra')
group('dopant-series dopant-energy','figure-4a')
group('dopant-series dopant-number nickel-source','figure-4b')
group('co-tem','figure-5a figure-5b')
group('co-diffraction','figure-5c figure-5d')
group('co-spectra co-ct-band','figure-6a')
group('ni-spectra mcd-relative','figure-6b')
group('fine-structure','figure-7a')
group('fine-structure ni-fine','figure-7b')
group('field-co co-ground-state','figure-8a')
group('field-ni ni-ground-state','figure-8b')
group('valence-model','figure-9a')
group('zeeman-results co-exchange','figure-9b')
group('magnetic-loop aggregate-morphology','figure-10a')
group('curie-bound aggregate-morphology','figure-10b')
group('co-isosbestic nucleation-threshold','figure-11a')
group('co-isosbestic intermediate-model','figure-11b')
for x in ['lf','ct','bg']:
 group('table1-co','table1-co-'+x);group('table1-ni','table1-ni-'+x)
for x in ['cdte-co','cdte-mn','cdse-co','cdse-mn','znte-co','znte-mn','zno-mn','blank']:group('table2-comparators','table2-'+x)
group('co-exchange','table2-zno-co');group('ni-exchange','table2-zno-ni')
for n in range(1,11):
 for s in ['a','b'] if n in [6,7,8] else ['']:group('equation'+str(n),'equation-'+str(n)+s)
group('si-kinetics si-kinetic-results','si-s1-cohorts si-s1-kinetics')
group('surface-control si-cleaning-results','si-s2')
group('ni-tem','si-s3')
group('luminescence-method quenching','si-s4')
group('si-lf-comparison','si-s5')
group('si-bandgap-comparison','si-s6 si-s6-axis')
for n in range(1,52):group(f'reference-{n:02}',f'reference-{n:02}')
units={u['id'] for u in read(B/'source-audit.json')['units']};print('Missing',sorted(units-set(mapping)));print('Extra',sorted(set(mapping)-units));assert set(mapping)==units
(O/'source-item-mapping.json').write_text(json.dumps(mapping,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print('Mapped',len(mapping),'units')
