contexts={1:'Diluted magnetic semiconductor background.',2:'Spintronics motivation; three separate cited works.',3:'Spin-polarized light-emitting diodes; three separate cited works.',4:'Predicted ferromagnetism in doped semiconductors; two cited works.',5:'High-temperature magnetic-semiconductor predictions and exchange scaling.',6:'Reported thin-film ferromagnetism and conflicting preparation dependence.',7:'Thin-film reports and defect hypotheses; two cited works.',8:'Thin-film magnetic context.',9:'Contrasting thin-film magnetic and optical behavior.',10:'Bulk-film charge-transfer assignment used as a comparison.',11:'Carrier/defect-mediated ordering and sample dependence; two works.',12:'Phase-segregation alternative in magnetic ZnO.',13:'Earlier ethanol synthesis and isocrystalline-core/shell processing; source of the SI S5 comparator, not a complete new recipe here.',14:'Dopant exclusion and isocrystalline shell-processing context.',15:'Dopant-incorporation challenge.',16:'Technical-grade TOPO composition and possible phosphonic-acid ligation.',17:'Empirical ZnO optical sizing.',18:'Optical bandgap–size relations and ZnO trap emission.',19:'Bulk Co/Ni ligand-field spectra and parameter context.',20:'Co fine structure, zero-field splitting and earlier dip assignment.',21:'MCD intensity and group-theory conventions.',22:'Basic zinc-acetate clusters and ZnO formation; three cited works.',23:'Critical nucleation and impurity effects.',24:'Strain/solubility interpretation; two cited works.',25:'Source note on the Co MCD antiresonance.',26:'Fine-structure assignments.',27:'Ligand-field MCD and sum-rule comparisons.',28:'Bulk low-temperature ligand-field emission.',29:'Source note delimiting bulk low-temperature emission.',30:'Ni charge-transfer assignment in ZnO.',31:'Ni:ZnS charge-transfer comparison.',32:'Covalency and charge-transfer intensity analysis.',33:'Optical electronegativity and molecular-oxide reference range.',34:'Optical electronegativity and ligand-field spectroscopy.',35:'Tetrahalide electronegativity comparison.',36:'Effective oxide electronegativity; two cited works.',37:'Diluted magnetic semiconductor exchange and Zeeman theory.',38:'Hybridization and magnetic-exchange theory.',39:'Co exchange constants for bulk II–VI comparison materials.',40:'Mn exchange constants and theoretical comparison.',41:'ZnO valence-level splitting.',42:'ZnO Zeeman anisotropy.',43:'Optical selection rules and anisotropy.',44:'Co magnetic-susceptibility anisotropy.',45:'Exchange-volume scaling and ZnO overlap.',46:'Confinement effects beyond volume scaling.',47:'Configuration-interaction exchange model.',48:'Co zero-field-splitting context.',49:'Bulk Ni magnetic-level estimates and uncertainty.',50:'Related aggregation work cited as in press; external results not imported.',51:'Magnetic anisotropy and domain-size context.'}
referenced=[]
for a in read(B/'reference-candidates.json'):
 n=a['number'];page=a['page'];bib=a['text'].replace('ReV.','Rev.').replace('Flatte´','Flatté').replace('- 12214','-12214').replace('- 1137','-1137').replace('- 3521','-3521').replace('- 314','-314').replace('- 1569','-1569')
 if n==16:bib='Source note: technical-grade TOPO (Aldrich) contains phosphonic acids, with an analogous ZnO ligating role proposed. Cited comparison: Peng, Z. A.; Peng, X. J. Am. Chem. Soc. 2002, 124, 3343–3353.'
 if n==25:bib='Source note: a Co:ZnO MCD Fano antiresonance occurs at 17 700 cm⁻¹; a weaker absorption dip at that energy was previously assigned to ²A₁(G) in reference 20.'
 if n==29:bib='Source note: cited bulk Co:ZnO ⁴T₁(P) emission is confined to cryogenic temperatures, reported below 5 K, with low quantum yields (reference 28).'
 if n==33:bib='Jørgensen, C. K. Prog. Inorg. Chem. 1970, 12, 101–158. The source note gives χ_opt(O²⁻) between 3.0 and 3.9, typically 3.2.'
 item('sources',f'reference-{n:02}',f'Reference {n}',bib+' '+contexts[n],page,f'References, entry {n}',scope='cited_context',kind='source_reference',notes=['Entry inspected in the supplied article. External full text not independently inspected in this source review.'])
 referenced.append({'id':f'reference-{n}','reference_number':n,'bibliography':[bib],'context':contexts[n],'cited_work_independently_reviewed_in_this_task':False,'import_experimental_evidence':False,'source_locators':[ev(page,f'References, entry {n}')['locator']]})
