from pathlib import Path
import json,hashlib,datetime
V=Path(__file__).resolve().parent;B=V.parent
def load(p):return json.loads(p.read_text(encoding='utf8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
refs={};samples={};excluded=[];hashes={}
for p in sorted((B/'canonical-drafts').glob('*.json')):
 r=load(p);rid=r['record_id'];hashes[rid]=sha(p)
 if rid.endswith(('-calibration','growth-model','pl-size-analysis')):
  excluded.append({'record_id':rid,'sample_count':len(r['products']),'reason':'Calibration/analysis/model context without a defined synthesized physical specimen; no product geometry is assigned.'});continue
 refs[rid]='identity-peng-incl3-top' if rid.endswith('incl3-top-stock') else 'identity-peng-cdse' if '-cdse-' in rid else 'identity-peng-inas'
 samples[rid]={s['sample_id']:{'entry_id':refs[rid],'reference_type':'chemical/material identity card only','source_sample_label':s.get('source_sample_label'),'composition':s.get('composition'),'phase':s.get('phase'),'scope_notes':s.get('notes',[]),'is_measured_geometry':False,'eligible_training':False} for s in r['products']}
save(V/'product-reference-proposal.json',{'scope':'Illustrative product identity references only; never measured sample coordinates or training labels. Calibration rows and model/analysis contexts deliberately receive no product geometry.','recordBindings':refs,'sampleBindings':samples,'excluded_contexts':excluded,'sourceRecordSha256':hashes,'record_count':len(refs),'sample_context_count':sum(map(len,samples.values()))})
save(V/'creator-visual-review.json',{'status':'passed','review_type':'Creator source/visual review; independent audit still required','source_visuals_reviewed':['main-01.png','main-02.png'],'asset_visuals_reviewed':['review/molecular-contact.png']+[f'review/scenes-{i:02}.png' for i in range(1,6)],'operation_count':28,'module_sha256':sha(V/'peng1998-protocol.mjs'),'registry_proposal_sha256':sha(V/'registry-additions.json'),'checks':['All 28 canonical stages rendered and visually inspected.','CdSe stock uses TBP rather than TOP; no Se-only injection.','TOPO4g/360°C/Ar and cold2.4mL under0.1s are primary run, with post-injection300°C.','CdSe300°C nominal growth explicitly inferred, maintained hold not asserted.','InAsTOP2g/300°C, cold1mL under0.1s→250°C initially→260°C growth.','Only stock-preparation Ar is explicit for InAs; no gas tube added to InAs growth.','Feed elapsed times23/158min and190min are separate from feed duration.','CdSe aliquot0.2mL→methanol2mL followed by unspecified purification; no centrifuge, drying or powder process invented.','InAs aliquot workup uses toluene only; no imported methanol/OD.','InCl3·TOP cool→drybox no imported−35°C.','TMS3As two-dimensional atom indices, formula, bonds and highlight groups checked; no invented organometallic3D.','Separate PL-calibration inputs, distribution assumptions and no third moment.','CdSe TEM8.5nm remains separate from kinetic series; no InAs diffraction/CIF invented.','All colors/vessels/flow arrows labeled illustrative; diagrams contain no generated experimental traces.']})
manifest={'status':'ready_for_independent_audit_and_root_integration','source_id':'peng1998','source_doi':'10.1021/ja9805425','source_main_sha256':'9ab487d6125bd30631b0acf02803e59b0a5bfc4524ae1b3f25d4e40e5e8ff98d','canonical_record_hashes':hashes,'apparatus':{'module':'peng1998-protocol.mjs','module_sha256':sha(V/'peng1998-protocol.mjs'),'operation_count':28,'manifest':'scene-manifest.json','validation':'scene-validation.json'},'molecules':{'registry':'registry-additions.json','bindings':'bindings-additions.json','reuse':'reused-references.json','assets':'asset-manifest.json','validation':'molecular-validation.json',**load(V/'molecular-validation.json')['summary']},'products':{'proposal':'product-reference-proposal.json','record_count':len(refs),'sample_context_count':sum(map(len,samples.values()))},'creator_review':'creator-visual-review.json','integration':['Root copies peng1998-protocol.mjs to dist and adds createPeng1998Art dispatch before generic scene rendering.','Root merges registry-additions.entries by id and copies only listed svg/models assets to dist/assets/chemical-registry.','Root merges bindings-additions.recordBindings by exact record id, preserving other sources.','Root merges product-reference-proposal.recordBindings only; sampleBindings/exclusions document scope, not invented specimen coordinates.','No CIF/3D product reference association is proposed. Existing CdSe reference cells belong to independent sources and must not become this paper’s measured phase.','Do not rerun finalize_scenes.py: it is a one-time development migration already applied. render_scenes.mjs and build_molecules.py may be rerun after canonical source changes.']}
save(V/'handoff.json',manifest)
(V/'HANDOFF.md').write_text('''# Peng 1998 molecular and apparatus assets

All work is private in this directory. Site-owning root performs integration.

- `peng1998-protocol.mjs`: 28 source-specific scenes; exports `buildPeng1998Scene` and `createPeng1998Art`.
- `registry-additions.json`, `bindings-additions.json`: five new identity/connectivity references, nine unchanged references reused, all 20 current material slots bound. TMS₃As has a valid colored two-dimensional drawing; no unsupported computed metal geometry.
- `product-reference-proposal.json`: eight record-level identity cards and scoped physical/context bindings. Calibration rows and model/analysis-only records excluded. No product CIF or measured phase invented.
- `asset-manifest.json`: exact SVG/model asset filenames and SHA256 values.
- `scene-validation.json`: 104 checks passed against the final 28 canonical operations, including exclusive injection-duration bounds and absent InAs Ar conditions.
- `molecular-validation.json`: identity, graph, formula, finite-coordinate and reused-byte validation.
- `creator-visual-review.json`: all five apparatus contact sheets and molecular contact sheet visually inspected. This is the creator review, not an independent audit.

Root imports the module into the existing source-specific apparatus dispatch, copies the registry assets, and merges exact record bindings. The current CdSe and InAs kinetic records remain two methods within the existing atlas. Upstream stock, aliquot workup, and optical conversion stay distinct procedures. No Site checkout files were edited by this agent.
''',encoding='utf8')
print(json.dumps({'molecule_checks':len(load(V/'molecular-validation.json')['checks']),'product_records':len(refs),'physical_contexts':sum(map(len,samples.values())),'module_sha256':manifest['apparatus']['module_sha256']}))
