"""Record the authorized immutable scope reference; does not activate monitor policy."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
O=Path(__file__).resolve().parent;C=O/'cutoff-20260920T033439542641Z'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_bytes())
manifest=read(C/'cutoff-snapshot-manifest.json');partition=read(O/'deadline-scope-partition.json');validation=read(C/'capture-validation.json')
assert sha(C/'cutoff-snapshot-manifest.json')==partition['cutoff_manifest_sha256']=='8822a771eef5b01d52748a0c6882256de4a0a9a9e92675f3608b2e76fb15a519'
assert validation['status']=='passed' and not validation['failed']
cut=datetime.fromisoformat(manifest['cutoff_at']);target=cut.replace(month=11)
def reference(p):return {'path':str(p.resolve()),'sha256':sha(p)}
obj={'schema':'mattersyn-active-cutoff-reference/1','recorded_at':datetime.now(timezone.utc).isoformat(),'author':'/root/backlog_eta','status':'active_scope_reference_monitor_filter_integration_pending','cutoff_id':C.name,'cutoff_at':manifest['cutoff_at'],'scope':'Existing collection represented by immutable explicit file membership in both local source folders. Genuinely new post-cutoff papers are separate.','target_calendar_months':2,'target_at_utc':target.isoformat(),'target_basis':'Two calendar months after the actual inventory cutoff; project target, not a validated throughput forecast or completion promise.','cutoff_manifest':reference(C/'cutoff-snapshot-manifest.json'),'file_inventory':reference(C/'file-inventory.json'),'last_authoritative_group_mapping':reference(C/'last-authoritative-group-mapping.json'),'initial_scope_partition':reference(O/'deadline-scope-partition.json'),'capture_validation':reference(C/'capture-validation.json'),'partition_generator':reference(O/'partition_deadline_scope.py'),'partition_tests':reference(O/'test_partition.py'),'counts':partition['counts'],'later_new_papers_separate':True,'included_source_updates_reopen_review':True,'monitor_selection_filter_activated':False,'shared_ledger_changed':False,'source_files_written':False,'integration_owner':'root work owner'}
p=O/'active-cutoff.json';assert not p.exists();p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
report={'schema':'mattersyn-cutoff-operational-author-check/1','author':'/root/backlog_eta','independent_audit':False,'at':datetime.now(timezone.utc).isoformat(),'status':'passed_scope_reference_ready_for_root_integration','tests':{'command':'python -B -X utf8 -m unittest -v test_partition.py','passed':7,'failed':0,'coverage':['terminal included scopes remain complete','new paper stays separate','late SI flags generation/reopen check','newly mapped cutoff member included','alias merge and missing member retained','changed signature requires check','same DOI candidate does not join; input ledger unchanged']},'snapshot_validation_checks':validation['check_count'],'bound_files':{str(x.resolve()):sha(x) for x in [p,C/'cutoff-snapshot-manifest.json',C/'file-inventory.json',C/'capture-validation.json',O/'deadline-scope-partition.json',O/'partition_deadline_scope.py',O/'test_partition.py',Path(__file__)]},'integration_limit':'Partition is a read-only proposal. Root must integrate the included_pending_group_ids filter with current monitor priority, active-batch and source-generation gates; no scientific closure is conferred.'}
(O/'operational-author-check.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'active_cutoff':str(p),'active_cutoff_sha256':sha(p),'partition_sha256':sha(O/'deadline-scope-partition.json'),'operational_check_sha256':sha(O/'operational-author-check.json'),'manifest_sha256':sha(C/'cutoff-snapshot-manifest.json'),'target_at_utc':obj['target_at_utc'],'counts':partition['counts']}))
