from pathlib import Path
from datetime import datetime,timezone
import json
B=Path(__file__).resolve().parent;MON=B.parent.parent
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
g=read(MON/'ledger.json')['groups']['10.1021_nl015685v'];m=read(B/'source-manifest.json');m['fingerprint']=g['fingerprint'];m['documents']=[{'filename':k,'sha256':h,'role_candidate':'main','page_count':6}for k,h in g['fingerprint']['files'].items()];write(B/'source-manifest.json',m)
proof={'at':datetime.now(timezone.utc).isoformat(),'main_pages_text_read':[1,2,3,4,5,6],'main_pages_visually_inspected':[1,2,3,4,5,6],'scope':'All supplied six main pages including four figures, all experimental paragraphs and43references/notes. Cited outside papers are not independently read.','source_sha256':m['sha256'],'identity':'Besson et al., 3D Quantum Dot Lattice Inside Mesoporous Silica Films, Nano Letters2002,2(4),409–414; DOI10.1021/nl015685v','key_boundaries':['Mesoscopic P63/mmc pore ordering differs from atomic CdS blende-type111 fringes. Figure3d is an image Fourier power spectrum, not SAED.','Figure4 caption stage assignments conflict with body text and visible upper/lower intensity; no silent relabeling.','Host preparation, repeated loading and distinct silicon-wafer PL branch retain separate states. Copolymer template and preparation remain unspecified.','Matching SI not located or verified; source does not declare SI.','Optical estimated pore filling differs from qualitative total-filling language and visible unfilled pores.']};write(B/'root-reading.json',proof)
notes={'read':'All6supplied main pages read and visually inspected; two identical copies reconciled; matching SI not located or verified.','extract':'Canonical records, full reader and original assets in preparation.','audit':'Independent full-source reading complete; detailed extraction/asset audits underway.','integrate':'Source remains privately staged until audits pass.','publish':'Current public site remains version22; this contribution not yet published.'}
ms={k:{'status':'complete'if k=='read'else 'partial'if k in ['extract','audit']else'pending','evidence':[str(B/'root-reading.json'),str(B/'source-manifest.json')]if k=='read'else[],'note':v}for k,v in notes.items()};write(B/'milestones.json',ms)
c={'paper':'10.1021/nl015685v','title':'3D Quantum Dot Lattice Inside Mesoporous Silica Films','source_id':'besson2002','source_generation':2,'review_scope':'supplied_main_only_si_unverified','main_pages_text_reviewed':[1,2,3,4,5,6],'main_pages_visually_reviewed':[1,2,3,4,5,6],'si_status':'Matching SI not located or verified; no SI declaration observed.','website_published':False,'checkpoint_at':proof['at'],'current_work_items':[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in ms.items()],'next_action':'Complete canonical/reader/molecular/apparatus artifacts and independent audits, integrate same Site, validate and publish before next paper.'};write(B/'checkpoint.json',c)
print('Six supplied main pages reviewed; extraction and audit ongoing.')
