from pathlib import Path
import json,hashlib,datetime
A=Path(__file__).resolve().parent;P=A.parent
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text('utf8'))
c=read(A/'mechanical-checks-v1.json');r=read(A/'independent-reading-v1.json')
manual=[
('Pairing and attachment scope','Exact title/byline/DOI match across main8/SI26. Original two PDF hashes independently verified; local identifier filename search finds no declared ZIP/MP4. This is a local completeness limitation.'),
('Bulk A/B preparation','2:1 versus1:1 salt feed;800uLDMF;4day room-temperature evaporation. B explicitly inherits other procedure conditions. No unspecified temperature, yield, wash or vessel invented.'),
('NC precursor stock and aliquot','1mmol/0.5mmol in2000uLDMF stock; only500uL aliquot enters5mLtoluene+500uLOA. Stock solution final volume and aliquot reagent mmol are not invented.'),
('NC formation/recovery','Rapid injection/vigorous stirring qualitative; no unsupported RT/gas/duration.7000rpm3min and retained powder preserved; noRCFconversion or drying/wash invention.'),
('Five composite controls','Blue/yellow weight parts1/0,1/3,1/2,2/3,0/1 retained as a series, not five independently replicated NC syntheses.20minmix/dropcast/slowhood evaporation/peeling; absolute amounts absent.'),
('Precursor spin-coated film','Independent2/1mmol in1000uLDMF stock,200uLaliquot,2000rpm40s,80C30min; noPS/OA imported.'),
('Specimen association','14 sample contexts preserve bulkA/B,NCfamily,drypowder,colloid,spinfilm,blendseries,beta-film and relaxedDFT structures. Composition lineage does not prove same physical batch.'),
('Negative and stability outcomes','B non-detection atRT/77K notPLQEzero; bulk3months distinct from colloid5min deposition and drypowder severalmonths.'),
('Bulk optical measurements','612/459nm band scopes and392/310nm PLE;96.8%bulkPLQE;CIE pairs;all biexponential lifetimes including0.89ns bluefast component; reportedStokes221nm discrepancy retained.'),
('Temperature/model distinction','77–337K range/20Ksteps;197/297Ktrendcrossovers;S9fits197/237/277K. Ea205.26meV,S28.74,phonon19.44meV andS10R=.99 are model/fitted results, not recipe conditions.'),
('DFT and parity','PBE3.40/3.47eV,HSE4.40/4.46eV, orbital andTDMEclaims theoretical. No false claim P-1 lacks inversion; original paper narrative qualified.400eVcutoff;B2x4x4/A4x4x4;<.01eV/angstrom forces.'),
('NC characterization','PXRD phase consistency;diameter6.43±.17nm with unknown uncertainty type;3.4angstrom(224)assignment;TEM20nm/HRTEM5nm bars.614/465nm PL and decay values retain scopes;89.3%PLQE belongs driedpowder.'),
('Film optics/scintillation','Spinfilm611nm/123nm separate from composite. Beta resultbulkA/NCfilm;0.4MeV,16kW,400Gy/s. No exactblend membership,integrated dose,light yield or detection limit invented.'),
('Chemicals and utilities','Commercial purities/bounds and vendor roles retained. PSaverageMwapprox280000 without printed unit. N2 explicitly TGA-only; liquidN2 cooling utility.'),
('Table S1','Both composition columns;all72 expanded cells including66numeric values; precise uncertainties,latticeangles,2theta strict bounds,hkl inclusive limits,reflection andrefinement subsets retained.'),
('Tables S2–S5','All139 bond/angle numericrows compared with independent source tokens and actualnative table images. Exactatomlabels preserved.'),
('Tables S6–S7','68non-Hsites/272numeric values. xyz1e-4,Ueq1e-3 scales anduncertainties correct; unwrappedoutofcell/negative coordinates retained. NoH/occupancy/CIF qualification implied.'),
('Tables S8–S9','68sites/408Uij entries;sourcecolumnorder,negativeoffdiagonals,zero0(2) and1e-3scale preserved. Originalexponent/headings retained insourcecrops.'),
('Figures/equations/references','21figures includinggraphicalabstract,1scheme,6explicit equations and30referenceentries checked. Figure3B/A order,splitSIcaptions andsource-onlyreference context retained. Otherpapers notclaimed read.'),
('Source crops','All53selected originalcrops viewed through9contact sheets, with originalfullpage reading separately completed. No truncateddata/caption found. All53freshPDFiumpixel comparisons match; selectedcrops are not wholepageimages.'),
('Source-unit and export boundaries','167inventoryentries/sourcepointers resolve, but3sameIDs occuracrossmaterial/samplecontexts. Unique-unit transport fix required beforecanonical work; no task/exactpair/publication gate approved.')]
findings=[
{'id':'LIAN-SOURCE-01','status':'resolved_before_first_freeze','scope':'lian2021-chemicals PS average Mw unit','finding':'Pre-freeze draft labeled g/mol as reported though source prints no unit.','resolution':'First immutable freeze has unit:null, approximate:true,value280000; independently checked.','source':'main p6,§4.1'},
{'id':'LIAN-SOURCE-02','status':'open','scope':'protocols bulk-characterization / bulk-xps-tga / action','finding':'Acquire XPS and TGA under N2 can incorrectly attach N2 to XPS.','required_change':'Acquire XPS; acquire TGA under N2. Preserve all other scientific content.','source':'main p7,§4.5'},
{'id':'LIAN-SOURCE-03','status':'open','scope':'source-inventory.json inventory_units IDs','finding':'bulk-a,bulk-b,nc-a occur both as material and sample-context unit IDs.','required_change':'Give inventory units unique namespaced IDs with unchanged source_object_id/JSON pointers. Do not rename scientific objects.'}]
bound=dict(c['bound_files'])
for name in ['independent-reading-v1.json','independent-reading-v1.md','independent-reading-addendum.md','independent-table-tokens-v1.json','mechanical-checks-v1.json','check_extraction.py']:
 bound[str(A/name)]=sha(A/name)
d={'schema':'mattersyn.independent_source_scientific_audit.v1','source_id':'lian2021','doi':'10.1021/acsami.1c18038','auditor':'/root/norberg2004_extract','extraction_author':'/root/backlog_eta','created_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'open_findings','proposal_revision':1,'proposal_freeze_sha256':c['proposal_freeze_sha256'],'independence':'All34 source pages read/viewed and independent notes/tokens frozen before opening author typed extraction. No author files modified.','actual_manual_page_coverage':r['actual_page_coverage'],'manual_scopes':[{'id':f'L{n:02}','topic':t,'assessment':v} for n,(t,v) in enumerate(manual,1)],'counts':{'main_pages':8,'si_pages':26,'facts':57,'fact_quantities':134,'materials':15,'stocks':5,'protocols':9,'operations':21,'sample_contexts':14,'inventory_units':167,'tables':9,'table_rows':311,'table_cells':891,'numeric_table_cells':885,'figures_including_graphical_abstract':21,'schemes':1,'equations':6,'reference_entries':30,'original_crops_viewed':53,'contact_sheets_viewed':9,'manual_scientific_scopes':len(manual),'mechanical_checks':c['counts']['checks'],'mechanical_failures':c['counts']['failed']},'findings':findings,'source_conflicts_retained':['C1 B two-Sb geometry/main average scope','C2 reported bulk221nm Stokes vs612-392','C3 source symmetry/parity interpretation','C4 undefined diameter uncertainty'],'restrictions':['Supplied PDF source extraction only; missing ZIP/MP4 not reviewed','No original coordinate model,CIF or exact nanocrystal synthesis–structure pairing qualified','No canonical,molecule,apparatus,reader,browser,integration,training or publication approval'],'auditor_corrections':['Independent reading-v1 notes wrote1.89ns incorrectly; source Figure2c reopened and correct0.89ns accepted. Frozen note retained with addendum.','Initial helper usedMuPDF tocompare PDFiumcrops; all53false pixel failures were auditor renderer mismatch. Corrected helper usesPDFium andall53replayspass; original diagnostic retained.'],'bound_files':bound}
out=A/'independent-audit-v1.json';assert not out.exists();out.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n','utf8')
(A/'independent-audit-v1.md').write_text('# Lian 2021 independent extraction audit: revision1\n\nStatus: two bounded findings remain. The scientific reading covers all8 main and26SIpages,57facts/134quantities,9tables/891cells(885numeric),21operations and53selectedsourcecrops. All891tablecells and all53original crop pixel replays pass.\n\nRequired changes: clarify N2 is only the TGA atmosphere; give source inventory units unique IDs across material/sample namespaces. The earlier unreported PS Mw unit is already corrected in the first freeze.\n\nAll four declared source conflicts and missing attachment/sample-identity limits remain. This audit does not qualify a coordinate model, exact structure–recipe pair, downstream canonical/visual package or publication.\n\nExact input bindings, actual page coverage and21manual scopes are in independent-audit-v1.json. Original author files were not modified.\n',encoding='utf8')
print(json.dumps({'path':str(out),'sha256':sha(out),'freeze':d['proposal_freeze_sha256'],'bound_files':len(bound)}))
