"""Author a complete private supplied-source packet; no canonical or publication admission."""
from pathlib import Path
from datetime import datetime,timezone
from decimal import Decimal
import json,hashlib,re,copy
import pypdfium2 as pdfium
from PIL import Image,ImageOps,ImageDraw
import source_author_data as A
P=Path(__file__).resolve().parent;SID='pati2009';DOI='10.1021/la8031286';AUTHOR='/root/peng1998_reader_assets'
assert not(P/'package-freeze.json').exists()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):return json.loads(Path(p).read_text(encoding='utf-8-sig'))
def save(n,x):(P/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
prep=read(P/'source-preparation.json');docs={x['role']:x for x in prep['documents']}
for d in docs.values():assert sha(d['source_path'])==d['sha256'] and d['page_count']==4
def ev(role,page,loc):return {'source_id':SID+'-'+role,'document_role':role,'source_sha256':docs[role]['sha256'],'pdf_page':page,'printed_page':66+page if role=='main'else None,'locator':loc}
def q(raw,unit,meaning,evidence,flags=()):
 raw=str(raw);t=raw.replace('−','-').replace('–','-');ap=t.startswith('~');t=t.lstrip('~');value=ran=com=None
 if t.startswith(('<','>')):com=t[0];t=t[1:]
 if re.fullmatch(r'[+-]?\d+(\.\d+)?',t):value=float(Decimal(t))
 elif re.fullmatch(r'\d+(\.\d+)?-\d+(\.\d+)?',t):a,b=t.split('-');ran={'min':float(a),'max':float(b)}
 return {'raw_text':raw,'value':value,'unit':unit,'uncertainty':None,'range':ran,'comparison':com,'approximate':ap,'status':'reported'if value is not None or ran else'reported_text','meaning':meaning,'evidence':evidence,'conflict_ids':[x for x in flags if x.startswith('C')],'gap_ids':[x for x in flags if x.startswith('G')]}
facts=[]
for fid,role,p,loc,title,claim,scope,qs,flags,kind in A.FACTS:
 flags=flags.split();e=[ev(role,p,loc)]
 if fid in ['precipitation']:e.append(ev('main',2,'Experimental continuation: receiving volume, flask and stirring'))
 if fid=='dls-values':e.append(ev('main',4,'Conclusions: the same values called hydrodynamic diameters'))
 if fid=='hydroxo-conflict':e.append(ev('main',4,'Discussion continuation: simultaneous hydroxo and TEA complexes'))
 if fid=='si-peak-labels':e.append(ev('si',2,'Continuation of the literal spin-orbit and peak assignment'))
 if fid=='si-exposure':e.append(ev('si',1,'FigureS1 caption and four panels'))
 if fid=='calcined-xrd':e.append(ev('main',2,'Results final paragraph: calcination temperature and duration'))
 facts.append({'id':SID+'-'+fid,'title':title,'claim':claim,'sample_scope':scope,'claim_class':kind,'evidence':e,'quantities':[q(raw,u,m,e,flags)for m,raw,u in qs],'conflict_ids':[x for x in flags if x.startswith('C')],'gap_ids':[x for x in flags if x.startswith('G')],'independent_audit_status':'pending'})
fb={x['id'].removeprefix(SID+'-'):x for x in facts}
materials=[{'id':mid,'name':name,'source_formula_or_abbreviation':formula,'role':role,'scope_note':note,'source_fact_ids':[SID+'-'+fid],'evidence':fb[fid]['evidence'],'identity_qualification':'source-name/formula transcription only; no molecular model approved'}for mid,name,formula,role,note,fid in A.MATERIALS]
stocks=[]
for solvent in ['ethanol','propanol','butanol']:
 for solute,short,conc in [('cerium-nitrate','nitrate','0.1'),('tea','tea','0.4')]:
  stocks.append({'id':solvent+'-'+short+'-stock','name':f'{solute} stock in {solvent}','components':[{'material_id':solute,'role':'solute','amount':None},{'material_id':solvent,'role':'solvent','amount':None}],'quantities':[q(conc,'M','final stock concentration',fb['stocks']['evidence'])],'preparation':'Dissolve solute in the selected alcohol; source gives concentration, not preparation masses or total stock volume.','final_volume':None,'storage':None,'subsequent_transfer_volume':q('100','mL','volume transferred in one described precipitation',fb['precipitation']['evidence']),'source_fact_ids':[SID+'-stocks',SID+'-precipitation'],'evidence':fb['stocks']['evidence'],'scope_note':'One solvent-specific formulation. The100mL use is a transferred volume, not an asserted complete stock-preparation volume.'})
samples=[]
for solvent in ['ethanol','propanol','butanol']:
 for state in ['as-prepared','calcined','solution-dls']:
  samples.append({'id':solvent+'-'+state,'label':solvent+' '+state,'solvent':solvent,'state':state,'recipe_link':'precipitation-family','lineage_note':'Common reported protocol in a separate selected solvent; not a newly inferred replicate. Calcination is a post-treatment. DLS solution preparation/reconstitution is unspecified.','reported_whole_composition':None if state!='calcined'else'CeO2 (source phase-purity claim)','evidence':fb['dls-values'if state=='solution-dls'else'calcined-xrd'if state=='calcined'else'tem-size']['evidence'],'cross_technique_physical_batch_join':'unknown'})
for sid,state,fid in [('xrd-as-prepared','as-prepared bulk diffraction; solvent unspecified','asprep-xrd'),('xrd-calcined','calcined diffraction; solvent unspecified','calcined-xrd'),('butanol-tga','as-prepared1-butanol TGA in air','tga-steps'),('butanol-dsc','as-prepared1-butanol DSC','dsc-results'),('dsc-calcined','calcined DSC comparison; exact physical batch unspecified','dsc-results'),('packing-powder','room-temperature-dried porous powder; solvent unspecified','packing-result'),('xps-as-short','as-prepared short-exposure XPS; solvent unspecified','xps-short-main'),('xps-calcined-short','calcined short-exposure XPS; solvent unspecified','xps-short-main'),('xps-as-long','as-prepared long-exposure XPS; solvent unspecified','si-long-results'),('xps-calcined-long','calcined long-exposure XPS; solvent unspecified','si-long-results'),('xps-fit-context','shared source fitting parameters with printed specimen/figure inconsistencies','si-fitting'),('author-mechanism','interpretive species; not measured isolated products','hydroxo-conflict'),('literature-reference','cited prior systems; not current samples','prior-diethylamine')]:samples.append({'id':sid,'label':state,'state':state,'recipe_link':None,'reported_whole_composition':None,'evidence':fb[fid]['evidence'],'cross_technique_physical_batch_join':'unknown or not applicable; no batch match inferred'})
def op(i,action,fids,inputs,outputs,missing,retained=None):
 fs=[fb[x]for x in fids];return {'id':i,'action':action,'inputs':inputs,'outputs':outputs,'source_fact_ids':[f['id']for f in fs],'quantities':copy.deepcopy([qq for f in fs for qq in f['quantities']]),'context_fact_ids':[f['id']for f in fs],'evidence':[e for f in fs for e in f['evidence']],'missing_fields':missing,'retained_fraction':retained,'quantity_scope_note':'Only explicitly applicable source-context quantities are conditions; diagnostic and reference values remain separate.'}
prepops=[op('prepare-nitrate','Prepare selected alcohol cerium-nitrate stock',['stocks'],['cerium-nitrate','selected-alcohol'],['selected-nitrate-stock'],['solute mass','preparation volume','mixing conditions','storage']),op('prepare-tea','Prepare separate selected alcohol TEA stock',['stocks'],['tea','selected-alcohol'],['selected-tea-stock'],['solute mass','preparation volume','mixing conditions','storage']),op('drip','Drip nitrate stock into TEA stock at room temperature',['precipitation'],['selected-nitrate-stock','selected-tea-stock','burette','erlenmeyer'],['precipitating-mixture'],['numeric room temperature','stirring speed']),op('poststir','Continue mild stirring after precipitation',['poststir'],['precipitating-mixture'],['stirred-mixture'],['stirring speed','completion endpoint criterion']),op('filter','Suction-filter precipitate',['filtration'],['stirred-mixture','filter-paper'],['precipitate','filtrate'],['vacuum setting'],'precipitate for synthesis; filtrate aliquot for diagnostic'),op('diagnostic','Test separate filtrate aliquot with ammonium hydroxide',['filtrate-control'],['filtrate','ammonium-hydroxide'],['diagnostic-mixture'],['NH4OH amount/concentration','explicit positive/negative criterion'],'diagnostic only; not returned to precipitate'),op('alcohol-wash','Wash precipitate with the same solvent alcohol',['alcohol-wash-dry'],['precipitate','selected-alcohol'],['washed-precipitate'],['wash amount','wash cycles'],'solid precipitate'),op('ambient-dry','Dry washed precipitate at room temperature',['alcohol-wash-dry'],['washed-precipitate'],['ambient-dried-powder'],['numeric temperature','atmosphere']),op('acetone-wash','Wash dried powder with acetone',['acetone-wash'],['ambient-dried-powder','acetone'],['as-prepared-powder'],['acetone amount/cycles','subsequent drying'],'washed powder')]
# Narrow each stock preparation to its own concentration; prevent a second solute concentration becoming a stock parameter.
prepops[0]['quantities']=[copy.deepcopy(fb['stocks']['quantities'][0])];prepops[1]['quantities']=[copy.deepcopy(fb['stocks']['quantities'][1])]
prepops[6]['quantities']=[];prepops[7]['quantities']=copy.deepcopy(fb['alcohol-wash-dry']['quantities'])
protocols=[{'id':'precipitation-family','title':'Room-temperature alcohol/TEA precipitation','kind':'synthesis_variant_family','sample_ids':[x+'-as-prepared'for x in ['ethanol','propanol','butanol']],'alternatives':[{'id':x,'solvent_material_id':x,'nitrate_stock_id':x+'-nitrate-stock','tea_stock_id':x+'-tea-stock','scope':'Separately reported solvent substitution in the same described procedure; no independent replicate count inferred.'}for x in ['ethanol','propanol','butanol']],'operations':prepops,'source_fact_ids':[SID+'-'+x for x in ['stocks','precipitation','poststir','filtration','filtrate-control','alcohol-wash-dry','acetone-wash']]}, {'id':'calcination','title':'Calcination of as-prepared powder','kind':'post_treatment','sample_ids':[x+'-calcined'for x in ['ethanol','propanol','butanol']],'operations':[op('calcine','Ramp and hold as-prepared powder',['calcination'],['as-prepared-powder'],['calcined-powder'],['atmosphere','furnace/loading','cooling'])]}]
for i,title,fid,ss in [('xrd','Powder XRD and source Scherrer analysis','xrd-acquisition',['xrd-as-prepared','xrd-calcined']),('bet','BET surface-area analysis','bet-acquisition',[x+'-calcined'for x in ['ethanol','propanol','butanol']]),('tem','HRTEM and SAED','tem-acquisition',[x+'-as-prepared'for x in ['ethanol','propanol','butanol']]+['butanol-calcined']),('tga','Thermogravimetry','tga-acquisition',['butanol-tga']),('dsc','Differential scanning calorimetry','dsc-acquisition',['butanol-dsc','dsc-calcined']),('xps','XPS acquisition','xps-acquisition',['xps-as-short','xps-calcined-short','xps-as-long','xps-calcined-long']),('dls','Dynamic light scattering','dls-acquisition',[x+'-solution-dls'for x in ['ethanol','propanol','butanol']]),('packing','Rough packing-density measurement','packing-acquisition',['packing-powder']),('xps-fit','Peak fitting and surface-valence calculation','si-fitting',['xps-fit-context'])]:protocols.append({'id':i,'title':title,'kind':'measurement_or_analysis','sample_ids':ss,'operations':[op(i+'-acquire'if i!='xps-fit'else'xps-fit-analyze',title,[fid],ss,[i+'-data'],['See source acquisition facts and missingness G4'])]})
# Preserve fitting exposures and formulas as analysis context rather than solvent synthesis parameters.
protocols[-1]['context_fact_ids']=[SID+'-'+x for x in ['si-exposure','si-fit-four','si-fit-ten','si-short-results','si-long-results']]
table_rows=[]
for group,labels,states,be,width in [('Ce3d7/2',['v0','v','v′','v″','v‴'],['Ce3+','Ce4+','Ce3+','Ce4+','Ce4+'],['880.3','881.9','884.8','888.3','897.8'],['3.0','2.2','3.9','3.8','2.3']),('Ce3d5/2',['u0','u','u′','u″','u‴'],['Ce3+','Ce4+','Ce3+','Ce4+','Ce4+'],['898.8','900.4','902.9','906.8','916.1'],['3.2','1.5','4.5','2.9','2.3'])]:
 for j,(label,state,b,w)in enumerate(zip(labels,states,be,width)):
  table_rows.append({'id':'table-s1-'+label,'source_group_header':group,'peak_label':label,'oxidation_assignment_as_printed':state,'source_column_in_group':j+1,'cells':[{'column':'binding_energy',**q(b,'eV','source fitted peak binding energy',[ev('si',3,'TableS1 '+group+', '+label+' binding-energy cell')],['C6','C7','C10']if label=='v′'else['C6','C7'])},{'column':'fwhm',**q(w,'eV','source fitted peak FWHM',[ev('si',3,'TableS1 '+group+', '+label+' FWHM cell')],['C6','C7'])}]})
table={'id':'table-s1','title':'The binding energy positions and FWHM values obtained from the fitting of spectrum3(c)','raw_grid':[['Ce3d7/2','v0 Ce3+','v Ce4+','v′ Ce3+','v″ Ce4+','v‴ Ce4+'],['Binding Energy(eV)','880.3','881.9','884.8','888.3','897.8'],['FWHM(eV)','3.0','2.2','3.9','3.8','2.3'],['Ce3d5/2','u0 Ce3+','u Ce4+','u′ Ce3+','u″ Ce4+','u‴ Ce4+'],['Binding Energy(eV)','898.8','900.4','902.9','906.8','916.1'],['FWHM(eV)','3.2','1.5','4.5','2.9','2.3']],'rows':table_rows,'numeric_cell_count':20,'raw_grid_cell_count':36,'evidence':[ev('si',3,'Complete TableS1 and caption')],'conflict_ids':['C6','C7','C10'],'footnotes':[],'sample_scope':'XPS fitting context; literal3(c) label unresolved, shared fits across4source spectra; no exact physical batch join'}
save('source-tables.json',{'schema':'mattersyn-source-tables/1','source_id':SID,'author':AUTHOR,'tables':[table],'independent_numerical_audit':'pending'})
figures=[
 {'id':'figure-1','role':'main','page':2,'title':'HRTEM images and SAED','panels':[{'label':a,'sample_id':s,'annotations':{'scale_bar':q('5','nm','source bar',[ev('main',2,'Figure1'+a)]),'saed_hkl':h}}for a,s,h in [('a','ethanol-as-prepared',['200','220','311']),('b','propanol-as-prepared',['200','220','311']),('c','butanol-as-prepared',['200','220','311']),('d','butanol-calcined',['111','200','220','311'])]],'scope_note':'Local microscopy crystallites; bulk as-prepared mixture uncertainty retained.'},
 {'id':'figure-2','role':'main','page':3,'title':'X-ray diffraction','panels':[{'label':'a','sample_id':'xrd-as-prepared'},{'label':'b','sample_id':'xrd-calcined'}],'annotations':{'x_label':'2Theta(degree)','x_ticks_raw':['20','30','40','50','60','70','80','90'],'y_label':'Relative intensity(a.u.)','legend':'* CeO2; source assigns calcined cubic peaks','curves_digitized':False},'scope_note':'Solvent for these XRD specimens not explicit. Calcined200°C/3h; as-prepared phase unresolved.'},
 {'id':'figure-3','role':'main','page':3,'title':'TGA and DSC','panels':[{'label':'a','sample_id':'butanol-tga','x_label':'Temperature(°C)','x_ticks_raw':['0','200','400','600','800'],'y_label':'Weight%','y_ticks_raw':['0','50','100','150']},{'label':'b','sample_id':'butanol-dsc','x_label':'Temperature(°C)','x_ticks_raw':['0','50','100','150','200','250'],'y_label':'Heat flow(W/g)','y_ticks_raw':['-5','-4','-3','-2','-1','0','1','2']},{'label':'c','sample_id':'dsc-calcined','x_label':'Temperature(°C)','x_ticks_raw':['0','50','100','150','200','250'],'y_label':'Heat flow(W/g)','y_ticks_raw':['-0.3','-0.1','0.1','0.3','0.5','0.7']}],'scope_note':'Axes preserved; no raw thermal curve digitization. TGA air does not determine calcination atmosphere.'},
 {'id':'figure-s1','role':'si','page':1,'title':'Ce3d XPS and peak fits','panels':[{'label':a,'sample_id':s}for a,s in [('a','xps-as-long'),('b','xps-as-short'),('c','xps-calcined-long'),('d','xps-calcined-short')]],'annotations':{'x_label':'Binding Energy(eV)','x_ticks_raw':['930','920','910','900','890','880','870'],'x_direction':'descending left to right','y_label':'Intensity(arb.units)','peak_label_legend':'u/v components retained in original and TableS1','curves_digitized':False},'scope_note':'Mappings follow SI first paragraph and plotted4/10peak context; conflicting caption/fitting prose explicitly preserved. No extra FigureS2 exists.'},
]
for f in figures:f['evidence']=[ev(f['role'],f['page'],f['id']+' complete original and caption')]
equations=[{'id':eid,'raw_expression':expr,'title':loc,'note':note,'evidence':[ev(role,p,loc)],'conflict_ids':flags,'numerical_recalculation_performed':False}for eid,role,p,loc,expr,note,flags in A.EQUATIONS]
refs=[{'id':f'{role}-reference-{n}','number':n,'raw_citation':txt,'evidence':[ev(role,p,f'Printed reference{n}')],'access_level':'citation in supplied source only; cited work not read'}for role,p,n,txt in A.REFERENCES]
conflicts=[{'id':i,'title':t,'description':d,'status':'unresolved_source_discrepancy','source_fact_ids':[x['id']for x in facts if i in x['conflict_ids']]}for i,t,d in A.CONFLICTS]
gaps=[{'id':i,'title':t,'description':d,'status':'unreported_or_unverified','source_fact_ids':[x['id']for x in facts if i in x['gap_ids']]}for i,t,d in A.GAPS]
for collection in [conflicts,gaps]:
 for entry in collection:
  entry['evidence']=list({json.dumps(e,sort_keys=True):e for f in facts if f['id'] in entry['source_fact_ids'] for e in f['evidence']}.values())
sf={'schema':'mattersyn-source-facts/1','source_id':SID,'doi':DOI,'title':A.TITLE,'authors':A.AUTHORS,'year':2009,'author':AUTHOR,'created_at':datetime.now(timezone.utc).isoformat(),'source_generation':1,'bundle_sha256':prep['bundle_sha256'],'source_scope':'Complete supplied4main+4matchedSI pages, author extraction; independent scientific audit pending.','facts':facts,'materials':materials,'stocks':stocks,'protocols':protocols,'sample_contexts':samples,'figures':figures,'equations':equations,'conflicts':conflicts,'missingness':gaps,'references':refs,'independent_audit_status':'pending','canonical_status':'not authored','training_eligibility':False,'atomic_model_status':'not supplied/not admitted'}
save('source-facts.json',sf)
pair={'schema':'mattersyn-intake-identity/1','author':AUTHOR,'doi':DOI,'source_id':SID,'title':A.TITLE,'authors':A.AUTHORS,'year':2009,'journal':'Langmuir','volume':'25','pages':'67–70','online_publication_date':'2008-12-05','source_generation':1,'bundle_sha256':prep['bundle_sha256'],'file_copies':[{k:v for k,v in d.items()if k!='pages'}for d in docs.values()],'pairing_status':'matched_by_source_content_and_publisher_document_locator','evidence':[ev('main',1,'Exact article title/authors/DOI/journal identity'),ev('main',4,'SI declaration: XPS spectra and detailed peak-fitting procedures'),ev('si',1,'Supporting Information, FigureS1 Ce3d spectra; printed publisher watermark contains la8031286_si_001'),ev('si',3,'Same as-prepared81/19 and calcined33/67 percent states as mainp3')],'identity_caveat':'SI does not repeat article title/authors; its generic word-processing metadata is not identity evidence. Main declaration, exact analytical results and publisher DOI-bearing document locator support the pairing.','recipe_present':True,'recipe_evidence':[ev('main',1,'Experimental stock concentrations and feed rate'),ev('main',2,'Experimental continuation: volumes, stirring, filtration, washing, drying and calcination')],'no_source_downloads':True}
save('intake-identity.json',pair)
# Original assets rendered from the unchanged PDF at220dpi. Fractions are crop boxes in a full-page rendered image.
crop_specs=[('figure-1','main',2,[.516,.048,.936,.484],'Figure1 full image and caption'),('figure-1a','main',2,[.525,.052,.729,.239],'Figure1a ethanol as-prepared'),('figure-1b','main',2,[.730,.052,.928,.239],'Figure1b propanol as-prepared'),('figure-1c','main',2,[.525,.239,.729,.429],'Figure1c butanol as-prepared'),('figure-1d','main',2,[.730,.239,.928,.429],'Figure1d butanol calcined'),('figure-2','main',3,[.070,.046,.487,.273],'Figure2 diffraction and caption'),('figure-3','main',3,[.517,.048,.936,.444],'Figure3 thermal plots and complete caption'),('figure-s1','si',1,[.140,.119,.894,.665],'FigureS1 four XPS spectra and caption'),('table-s1','si',3,[.132,.119,.891,.305],'TableS1 complete cells and caption'),('reaction','main',4,[.068,.385,.485,.433],'Literal proposed reaction'),('xps-equations','si',3,[.139,.449,.886,.579],'Literal CeIII/CeIV area sums and percentage expression'),('materials-stocks','main',1,[.519,.683,.934,.858],'Experimental materials stocks and start of addition'),('workup-calcination','main',2,[.069,.050,.484,.207],'Experimental continuation through calcination'),('xps-fitting','si',2,[.143,.383,.887,.897],'Complete fitting paragraph including source conflicts'),('xps-results','si',3,[.142,.589,.889,.801],'Complete short/long-exposure result paragraph'),('asprep-phase','main',2,[.519,.705,.934,.912],'XRD as-prepared mixture discussion, continues on main page3'),('mechanism-conflict','main',3,[.519,.897,.934,.941],'Hydroxo-complex discussion first part; continues main page4'),('asprep-phase-continuation','main',3,[.069,.283,.485,.565],'Continuation of XRD and BET paragraph from main page2'),('mechanism-conflict-continuation','main',4,[.069,.050,.485,.109],'Continuation of hydroxo-complex paragraph from main page3'),('si-reference-list','si',4,[.142,.089,.890,.320],'All4SI references')]
(P/'reader-assets').mkdir(exist_ok=True);pdfs={role:pdfium.PdfDocument(d['source_path'])for role,d in docs.items()};assets=[]
for aid,role,page,fr,loc in crop_specs:
 pg=pdfs[role][page-1];im=pg.render(scale=220/72).to_pil();w,h=im.size;box=[round(fr[0]*w),round(fr[1]*h),round(fr[2]*w),round(fr[3]*h)];path=P/'reader-assets'/f'{aid}.png';im.crop(box).save(path)
 assets.append({'id':aid,'path':str(path),'sha256':sha(path),'source_path':docs[role]['source_path'],'source_sha256':docs[role]['sha256'],'document_role':role,'pdf_page':page,'locator':loc,'renderer':'pypdfium2 '+pdfium.PYPDFIUM_INFO.version+' / PDFium '+pdfium.PDFIUM_INFO.version,'dpi':220,'full_render_dimensions':[w,h],'crop_box_pixels':box,'crop_fraction':fr,'dimensions':[box[2]-box[0],box[3]-box[1]],'contains_complete_source_page':False,'scientific_image_pixels_modified':False,'actual_author_preview_review':False});pg.close()
for pdf in pdfs.values():pdf.close()
save('original-assets-manifest.json',{'schema':'mattersyn-original-crops/1','source_id':SID,'author':AUTHOR,'assets':assets,'status':'author_crops_pending_actual_preview_check','public_admission':False})
for start in range(0,len(assets),3):
 subset=assets[start:start+3];thumbs=[]
 for x in subset:
  im=Image.open(x['path']).convert('RGB');im.thumbnail((950,1200));canvas=Image.new('RGB',(980,im.height+45),'white');ImageDraw.Draw(canvas).text((10,8),x['id'],fill='black');canvas.paste(im,(10,35));thumbs.append(canvas)
 canvas=Image.new('RGB',(max(x.width for x in thumbs),sum(x.height for x in thumbs)),'#e7edf2');y=0
 for t in thumbs:canvas.paste(t,(0,y));y+=t.height
 canvas.save(P/'reader-assets'/f'contact-{start//3+1:02}.png')
units=[]
def unit(uid,kind,ptr,label,evidence):units.append({'id':SID+'-'+uid,'kind':kind,'payload_path':'source-facts.json','json_pointer':ptr,'title':label,'evidence':evidence,'disposition':'retained_source_linked','independent_audit_status':'pending'})
for field in ['facts','materials','stocks','protocols','sample_contexts','figures','equations','references','conflicts','missingness']:
 for i,x in enumerate(sf[field]):
  unit(field+'-'+x['id'],field,'/'+field+'/'+str(i),x.get('title',x.get('name',x.get('label',x.get('raw_citation',x['id'])))),x.get('evidence',[]))
  if field=='protocols':
   for j,opx in enumerate(x['operations']):unit('operation-'+opx['id'],'operation',f'/{field}/{i}/operations/{j}',opx['action'],opx['evidence'])
  if field=='figures':
   for j,pan in enumerate(x['panels']):unit(x['id']+'-'+pan['label'],'figure_panel',f'/{field}/{i}/panels/{j}',x['title']+' '+pan['label'],x['evidence'])
units.append({'id':SID+'-table-s1','kind':'table','payload_path':'source-tables.json','json_pointer':'/tables/0','title':table['title'],'evidence':table['evidence'],'disposition':'all20numeric cells and36raw grid cells retained'})
for i,row in enumerate(table_rows):units.append({'id':SID+'-'+row['id'],'kind':'table_row','payload_path':'source-tables.json','json_pointer':f'/tables/0/rows/{i}','title':row['source_group_header']+' '+row['peak_label'],'evidence':row['cells'][0]['evidence'],'disposition':'two numeric cells retained'})
units.append({'id':SID+'-missing-reference-27','kind':'reference_gap','payload_path':'source-facts.json','json_pointer':'/conflicts/8','title':'Main reference27 absent','evidence':[ev('main',4,'Reaction citation27 and bibliography ending28')],'disposition':'explicit gap; not reconstructed'})
counts={'facts':len(facts),'fact_quantities':sum(len(x['quantities'])for x in facts),'materials':len(materials),'stocks':len(stocks),'protocol_families':len(protocols),'operations':sum(len(x['operations'])for x in protocols),'sample_contexts':len(samples),'figures':4,'figure_panels':sum(len(x['panels'])for x in figures),'tables':1,'table_numeric_cells':20,'table_raw_grid_cells':36,'equations':4,'printed_reference_entries':31,'conflicts':len(conflicts),'missingness':len(gaps),'inventory_units':len(units),'selected_crops':len(assets)}
save('source-inventory.json',{'schema':'mattersyn-source-inventory/1','source_id':SID,'author':AUTHOR,'created_at':datetime.now(timezone.utc).isoformat(),'counts':counts,'inventory_units':units,'supporting_information_status':'matched4pages by declaration/contents and source DOI locator; generic metadata caveat retained','complete_supplied_main_inventory':True,'complete_main_plus_si_inventory':True,'source_table_scope':'All TableS1 values transcribed; curves not digitized.','main_page_count':4,'si_page_count':4,'si_expected':True,'independent_audit_status':'pending'})
pages=[]
for role,d in docs.items():
 for row in d['pages']:pages.append({**row,'document_role':role,'source_sha256':d['sha256'],'text_read':True,'visual_review':True,'reviewer':AUTHOR,'coverage_note':'Full retained page text read and PDFium page image actually viewed; scientific glyphs compared to pixels.','source_unit_ids':[u['id']for u in units if any(e.get('document_role')==role and e.get('pdf_page')==row['pdf_page']for e in u.get('evidence',[]))]})
save('page-coverage.json',{'schema':'mattersyn-page-coverage/1','author':AUTHOR,'created_at':datetime.now(timezone.utc).isoformat(),'pages':pages,'main_read_pages':[1,2,3,4],'main_visually_inspected_pages':[1,2,3,4],'si_read_pages':[1,2,3,4],'si_visually_inspected_pages':[1,2,3,4],'si_status':'matched_and_read_with_identity_metadata_caveat','complete_supplied_page_coverage':True,'complete_main_plus_si_coverage':True,'independent_audit_status':'pending'})
(P/'extraction-notes.md').write_text('''# Pati2009 private source extraction

The supplied four main and four supporting-information pages were read and visually inspected. Original PDFs were rehashed against generation1 intake and remain unchanged. The study contains a usable common room-temperature precipitation method with three explicitly named alcohol variants and a subsequent calcination step. Six stock formulations are kept separate;100mL is a transferred volume, not a claimed stock-preparation volume. Diagnostic filtrate is separate from retained precipitate. TGA air is not inherited as calcination atmosphere.

As-prepared local CeO2 crystallites coexist with unresolved bulk diffraction and a proposed complex/hydroxide/hydrated-ceria mixture. No pure as-prepared whole composition is assigned. TEM, DLS, BET, XRD, thermal and XPS contexts retain their treatment and measurement-state boundaries. The DLS radius/diameter inconsistency and all XPS formula/label/exposure/calibration conflicts remain explicit. No atomic coordinates, additional synthesis runs, inferred phase fractions or training eligibility are introduced.

SI contains FigureS1, TableS1 and XPS fitting equations, not FigureS2. All20 numeric table cells and36 raw grid cells are preserved; spectral curves remain original images rather than invented numeric traces. Main has references1–26 and28; reference27 is absent. Four SI citations remain literal, including source typography. Cited articles have not been downloaded or read.

Full-page renders and raw page text are private source-reading aids under source-render. Selected original crops are author candidates pending actual crop review and independent audit. This source packet does not constitute canonical, model, browser or publication approval.
''',encoding='utf8')
print(json.dumps(counts))
