"""Save the exact verified release boundary and unfinished next source."""
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
P=Path(__file__).resolve().parent;M=P.parents[4];MON=P.parents[2];F=P.parent/'acs.inorgchem.8b02945'
read=lambda p:json.loads(p.read_text('utf8'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
release=read(MON/'latest-publication.json');assert release['dataset_version']=='0.31.0'
proof=read(M/'research-assets/github-public-delivery-verification.json');assert proof['status']=='passed' and release['commit_sha']==proof['site_commit']
independent=F/'source-independent-audit/independent-reading-checkpoint.json';assert independent.exists()
source_freeze=F/'package-freeze.json';source_audit=F/'source-independent-audit/independent-audit.json'
out={'saved_at':datetime.now(timezone.utc).isoformat(),'author':'/root','live_dataset':'0.31.0','science_commit':release['scientific_dataset_commit'],'current_site_commit':release['commit_sha'],'anonymous_endpoint_count':324,'README_citations_each':39,'records':626,'routes_or_variants':118,'hubs':49,'direct_hubs':38,'component_hubs':11,'source_groups':39,'formal_readers':34,'exact_structure_recipe_pairs':0,'pati_status':'complete within supplied main4+SI4 scope, independently audited and anonymously published','next_source':{'group_id':'legacy::10.1021_acs.inorgchem.8b02945','doi':'10.1021/acs.inorgchem.8b02945','pages':33,'independent_reading_sha256':sha(independent),'author_freeze_present':source_freeze.exists(),'author_freeze_sha256':sha(source_freeze) if source_freeze.exists() else None,'final_source_audit_present':source_audit.exists(),'final_source_audit_status':read(source_audit).get('status') if source_audit.exists() else 'pending','site_integrated':False},'resume':'Use current immutable Friedfeld source package and distinct audit; resolve findings before canonical freeze, then molecule/apparatus/product, root integration/browser and verified publication. Do not restart reviewed sources or re-import Pati.','cutoff_counts':read(MON/'deadline-20260920/active-cutoff.json')['counts'],'source_documents_uploaded':False,'paid_API_started':False,'ongoing_mechanism':'Existing single mattersyn-sequential-paper-review heartbeat; do not duplicate.'}
p=P/'site-integration-proposal/final-handoff.json';p.write_text(json.dumps(out,indent=2)+'\n','utf8')
skills=[M/'skills/mattersyn-paper-to-site/references/delivery-and-memory.md',Path('[local path redacted]')];assert sha(skills[0])==sha(skills[1])
note=f'''## 2026-09-20 — Verified CeO2 release and current InP work

Saved {out['saved_at']}. Live dataset0.31.0 contains626records,118routes/variants,49hubs(38direct+11component),39sourcegroups and34formalreaders. Pati science commit {out['science_commit']}; latest progress-only commit {out['current_site_commit']};324anonymous endpoints and both39-citation READMEs passed. The actual public CeO2 hub lists all three equal solvent routes: https://cuiyist.github.io/mattersyn-site/material.html?id=ceo2-625501 . The public queue is https://cuiyist.github.io/mattersyn-site/progress.html . Prior607canonicalrecord bytes and all six training-export files unchanged; exact atomic pairs0.

Pati main4+SI4 complete, separate source/canonical/molecule/apparatus/product/transport/browser audits and exact publication verified.19records,35operation scenes,167condition rows,20original crops and39symbolic contexts retained. The frozen molecular annotation correction removes three incorrect nitrate amine labels; no atomic structure, missing solvent link, complementary XPS fraction or corrected DLS metric was invented. Root actually exercised35stagecontrols,ninefiguremodals,fourstockselectors/fourXPScontexts,molecularcontrols and mobile layout; rotation was not separately retested.

Next Friedfeld2019 InP DOI10.1021/acs.inorgchem.8b02945 has a separate claim,8main+25SIpages and immutable independent reading checkpoint {out['next_source']['independent_reading_sha256']}. Extractor and auditor read all33pages; final source comparison/canonical preparation remain governed by actual packages at rolling-pipeline/acs.inorgchem.8b02945. Do not infer scientific approval from draft files. Snapshot flags: authorfreeze={out['next_source']['author_freeze_present']}; finalaudit={out['next_source']['final_source_audit_status']}. No Friedfeld Site import. Peng owns source authoring; Backlog independent source comparison; Norberg canonical planning. Root owns shared Site and ledger. Resume from final-handoff.json and current agent messages.

Fixed cutoff has9502pending provisional scopes and three held nested identity cases;418latergroups/429files are separate in the latest partition. Screening is not complete reading or no-recipe exclusion. Current screen-first/evidence-priority parallel workflow, individual audits, reusable reviewed illustrations and batched completed releases are in force. The two-month target remains unvalidated capacity. No download or paid API run. SourcePDFs/SI/fulltext/fullpages remain local; source-excluding public project/site projections preserve code,memory,skills,history and citations.

Installed and project skill delivery reference match SHA{sha(skills[0])}; skill validation passed. New lesson: every hash-bound input, including reading notes, stays immutable; later observations go in addenda. Pati's accidental ancillary-note edit was restored from an exact hash-matched historical copy with the expanded reading preserved separately and an explicit receipt. Do not repeat the restoration or rewrite passed freezes. Existing single five-minute heartbeat continues; no new automation created.
'''
p=M/'MEMORY.md';p.write_text(note+'\n'+p.read_text('utf8'),'utf8')
print(json.dumps({'handoff':str(P/'site-integration-proposal/final-handoff.json'),'live_site':out['current_site_commit'],'next_source':out['next_source']}))
