"""Private Pati apparatus authoring from exact frozen canonical v1."""
from pathlib import Path
from copy import deepcopy
import json,hashlib,shutil
A=Path(__file__).resolve().parent;P=A.parents[1];C=P/'canonical-proposal/v1';M=P.parents[3]
T=P.parent/'acsanm.2c04342/visuals/apparatus'
def read(p):return json.loads(p.read_bytes())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(A/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert not(A/'package-freeze.json').exists()
assert sha(C/'package-manifest.json')=='5986df83c2313f8e5418d0c46c049d86e2ef62dbd049359c7a53a5010e312281'
records=[]
for row in read(C/'record-manifest.json')['records']:
 assert sha(Path(row['path']))==row['sha256']
 r=read(Path(row['path']))
 if r['operations']:records.append(r)
base={}
def scene(oid,title,art,prose,notes=(),**extra):base[oid]=dict(title=title,art=art,prose=prose,notes=[{'label':k,'value':v}for k,v in notes],**extra)
scene('prepare-nitrate','Nitrate stock preparation','stock','Dissolve cerium nitrate hexahydrate in the selected alcohol to the reported final stock concentration.', [('Volume basis','0.1 M is the final stock concentration; stock preparation volume and solute mass are unreported.'),('Water scope','The six waters belong to the precursor hydrate; no separate water charge is reported.'),('Unreported','Stock preparation vessel, mixing conditions and storage.')],reagent='Cerium nitrate hexahydrate',stock='Nitrate stock · 0.1 M')
scene('prepare-tea','TEA stock preparation','stock','Prepare a separate triethanolamine solution in the same selected alcohol as the nitrate stock.', [('Volume basis','0.4 M is the final stock concentration; the subsequent 100 mL use is not a complete stock preparation volume.'),('Identity','Triethanolamine is the named reagent. Its inconsistent printed formula remains a source issue; this scene assigns no molecular graph.'),('Unreported','Solute mass, stock volume, preparation apparatus and storage.')],reagent='Triethanolamine',stock='TEA stock · 0.4 M')
scene('drip','Burette addition into an Erlenmeyer flask','burette','Drip 100 mL of the selected-alcohol nitrate stock into 100 mL of the same-alcohol TEA stock at room temperature with mild stirring.', [('Reported apparatus','Burette feeding an Erlenmeyer flask; vessel capacities are not supplied.'),('Separate intervals','The later 1 h post-precipitation hold is separate. A total feeding duration is not calculated or substituted.'),('Unreported','Numerical room temperature and stirring rate.')])
scene('poststir','Post-precipitation stirring','stir','Continue mild stirring for 1 h after completion of precipitation.', [('Time origin','This hold follows completion of precipitation; it does not specify the total burette-addition time.'),('Unreported','Numerical room temperature and stirring speed.')])
scene('filter','Suction filtration and fraction split','filter','Suction-filter the stirred mixture using Whatman 42 paper. Retain the precipitate for the powder workup and keep filtrate available for a separate diagnostic aliquot.', [('Retained synthesis fraction','Solid precipitate; the filtrate is not recombined with it.'),('Filter specification','Printed pore diameter 2.5 µm.'),('Unreported','Vacuum pressure, filtration duration and filter assembly dimensions.')])
scene('alcohol-wash','Wash retained precipitate','wash','Wash the retained precipitate using the same alcohol used for both stock preparations.', [('Retained fraction','Washed solid precipitate.'),('Separate routes','Each solvent route remains separate; no alcohol mixture is implied.'),('Unreported','Wash volume, cycle count and wash-separation details.')],wash='route')
scene('ambient-dry','Room-temperature drying','dry','Dry the alcohol-washed precipitate at room temperature for 24 h before the acetone wash.', [('Order','Alcohol wash → 24 h ambient drying → acetone wash.'),('Unreported','Numerical temperature, atmosphere and drying apparatus. A vacuum oven is not asserted.')])
scene('acetone-wash','Acetone wash of dried powder','wash','Wash the room-temperature-dried powder with acetone to remove residual alcohol, unreacted TEA and other byproduct.', [('Retained fraction','Washed as-prepared powder.'),('Unreported','Acetone volume, number of washes and separation method.'),('Missing subsequent step','No further drying operation or its conditions are supplied.')],wash='Acetone')
scene('diagnostic','Separate filtrate completeness test','diagnostic','Take a 10 mL filtrate aliquot and add ammonium hydroxide solution for the reported completeness check.', [('Branch boundary','Diagnostic mixture is not returned to the retained precipitate; NH4OH is not the main synthesis precipitant.'),('Unreported','NH4OH volume/concentration, exact addition rate and explicit visual pass criterion.'),('Sample scope','The diagnostic applies to separate solvent preparations; filtrates are not pooled.')])
scene('calcine','Calcination of separate powder preparations','calcine','Apply the reported 10 °C/min ramp and 200 °C, 3 h hold to each as-prepared powder separately.', [('Atmosphere','Unreported for synthesis calcination. Do not inherit the air condition of TGA.'),('Specimen boundary','Separate ethanol-, 1-propanol- and 1-butanol-derived powders; no pooled mixture.'),('Unreported','Furnace type, sample loading and cooling schedule.')])
scene('xrd-acquire','Powder diffraction and Scherrer context','xrd','Measure as-prepared and calcined powders using a Bruker AXS D8 Advance with Cu Kα radiation.', [('Specimen boundary','XRD solvent provenance and exact physical-batch links are not explicit.'),('Analysis','The source cites Scherrer analysis but supplies no explicit equation or shape factor.'),('Structure limit','As-prepared bulk phase is unidentified; calcined cubic-CeO2 assignment is not a supplied atomic model.'),('Unreported','Full scan settings and exact instrument geometry.')])
scene('bet-acquire','Gas-sorption surface-area analysis','bet','Measure the separate calcined solvent-derived powders using Micromeritics ASAP 2010C.', [('Gas context','Nitrogen is named in the source interpretation; gas grade and pressure schedule are unreported.'),('Metric distinction','Reported surface areas and source-calculated equivalent spherical diameters are separate from TEM crystallite diameters.'),('Unreported','Degassing conditions and numeric isotherm data.')])
scene('tem-acquire','HRTEM and selected-area diffraction','tem','Use JEOL 2100 HRTEM for the separately assigned Figure 1 specimens and retain the original SAED panels.', [('Samples','Ethanol, 1-propanol and 1-butanol as-prepared specimens; calcined 1-butanol comparison.'),('Local versus bulk','Local CeO2 fringes/SAED do not establish pure whole as-prepared composition.'),('Unreported','Grid preparation, accelerating voltage and dose/exposure.')])
scene('tga-acquire','Thermogravimetry in air','tga','Measure as-prepared 1-butanol-derived material using Perkin-Elmer TGA-7 in air at 10 °C/min.', [('Atmosphere scope','Air applies to this TGA measurement only.'),('Observation scope','Thermal loss intervals and the high-temperature residue are analytical observations, not the 200 °C synthesis product specification.'),('Unreported','Sample loading and gas flow.')])
scene('dsc-acquire','Differential scanning calorimetry','dsc','Use the TA Instruments 2920 Modulated DSC for the as-prepared and calcined comparison contexts.', [('Samples','Figure 3b is as-prepared 1-butanol material; the exact calcined physical batch is not uniquely identified.'),('Unreported','DSC atmosphere, heating rate and modulation settings.'),('Boundary','The source endotherm and inferred transition interval are not additional synthesis setpoints.')])
scene('xps-acquire','Exposure-dependent surface spectroscopy','xps','Use Kratos AXIS 165 with Al Kα in hybrid mode, preserving separate survey and high-resolution pass energies.', [('Four contexts','As-prepared and calcined surfaces each have short- and long-exposure observations.'),('Exposure wording','Main: <15 min; SI: approximately 15 min or 15 min. Long exposure: >5 h. These are acquisition contexts, not synthesis durations.'),('Boundary','XPS surface valence fractions are not whole-powder composition; exact solvent provenance is unreported.')])
scene('dls-acquire','Solution dynamic light scattering','dls','Measure the three separately prepared solvent dispersions with the He–Ne laser 05-LHP-121 and FEU-79 photon counter.', [('Preparation gap','Dispersion concentration, preparation/reconstitution, viscosity model and temperature are unreported.'),('Source conflict','The Results call the values hydrodynamic radii; Conclusions call them diameters. No factor-of-two correction is applied.'),('Geometry','The optical layout is explanatory; no cuvette dimensions or scattering angle are supplied.')])
scene('packing-acquire','Rough hand-packed powder density','packing','Hand-pack room-temperature-dried precipitate in a preweighed 1 mL pipet, then weigh the pipet plus powder.', [('Metric','Rough bulk packing density; it is not a measured crystal density.'),('Unreported','Exact packing force, replicate count and balance specification.')])
scene('xps-fit-analyze','Source XPS peak-fitting analysis','fit','Apply the reported Shirley background and 50% Gaussian/50% Lorentzian shape to the source XPS data.', [('Calibration conflict','Printed calibration is 884.5 eV; Table S1 v′ binding energy is 884.8 eV. Neither is silently replaced.'),('Model scope','Long-exposure fits supply positions/widths for lower-SNR short-exposure spectra; four- and ten-peak contexts remain distinct.'),('Printed labels','Unusual spin labels, conflicting spectrum references and the unprimed I_v area term remain explicit.'),('Boundary','No synthetic spectrum or recomputed surface fraction is generated.')])
facts={f['id']:f for f in read(P/'source-facts.json')['facts']}
SCOPE_FACTS={'prepare-nitrate':['cerium-material','stocks'],'prepare-tea':['tea-material','stocks'],'drip':['precipitation','poststir'],'poststir':['poststir'],'filter':['filtration','filtrate-control'],'alcohol-wash':['alcohol-wash-dry'],'ambient-dry':['alcohol-wash-dry','acetone-wash'],'acetone-wash':['acetone-wash'],'diagnostic':['filtrate-control'],'calcine':['calcination','tga-acquisition'],'xrd-acquire':['xrd-acquisition','asprep-xrd','calcined-xrd'],'bet-acquire':['bet-acquisition','bet-diameters'],'tem-acquire':['tem-acquisition','figure1-bars','asprep-xrd'],'tga-acquire':['tga-acquisition','tga-steps'],'dsc-acquire':['dsc-acquisition','dsc-results'],'xps-acquire':['xps-acquisition','si-exposure','xps-short-main','si-long-results'],'dls-acquire':['dls-acquisition','dls-values','conclusion-dls'],'packing-acquire':['packing-acquisition','packing-result'],'xps-fit-analyze':['si-fitting','si-fit-four','si-fit-ten','si-peak-labels','si-short-results']}
cfg={};bindings=[]
for r in records:
 for j,o in enumerate(r['operations']):
  c=deepcopy(base[o['id']]);c.update(record_id=r['record_id'],operation_id=o['id'],operation_pointer=f'/operations/{j}',option_pointers=[])
  sol=r['record_id'].removeprefix('pati-2009-').removesuffix('-route')if r['record_id'].endswith('-route')else None
  c['solvent']={'ethanol':'Anhydrous ethanol','propanol':'1-Propanol','butanol':'1-Butanol'}.get(sol,'Separate source specimens')
  if sol:c['title']=c['solvent']+' · '+c['title'];c['notes'].insert(0,{'label':'Selected solvent','value':c['solvent']+' only. Both stock solutions and the alcohol wash use this same solvent.'})
  c['source_context_fact_ids']=['pati2009-'+f for f in SCOPE_FACTS[o['id']]]
  ev=list({json.dumps(e,sort_keys=True):e for f in c['source_context_fact_ids']for e in facts[f]['evidence']}.values())
  for note in c['notes']:note['source_fact_ids']=c['source_context_fact_ids'];note['evidence']=ev
  k=r['record_id']+'--'+o['id'];cfg[k]=c
  bindings.append({'scene_id':k,'record_id':r['record_id'],'record_path':str(C/(r['record_id']+'.json')),'record_sha256':sha(C/(r['record_id']+'.json')),'operation_id':o['id'],'operation_pointer':c['operation_pointer'],'inputs':o['inputs'],'outputs':o['outputs'],'retained_fraction':o['retained_fraction'],'source_evidence':o['evidence'],'supplemental_source_fact_ids':c['source_context_fact_ids'],'supplemental_source_evidence':ev,'canonical_description':o['description'],'human_prose':c['prose'],'art':c['art'],'option_pointers':[]})
assert len(cfg)==len(bindings)==35 and len({b['operation_id']for b in bindings})==19
data={'source_group':'pati2009','configs':cfg,'parameter_labels':{k:k.replace('_',' ').capitalize()for r in records for o in r['operations']for k in o['parameters']}}
data['parameter_labels'].update({'nitrate_stock_transferred_volume':'Nitrate stock transfer','tea_receiving_volume':'TEA stock already in receiving flask','post_precipitation_stirring_duration':'Hold after precipitation','ambient_drying_duration':'Room-temperature drying before acetone','filtrate_aliquot':'Separate diagnostic filtrate aliquot','printed_calibration_energy':'Printed calibration energy (source conflict retained)'})
save('scene-config.json',data);save('records.json',records);save('canonical-bindings.json',{'author':'/root/backlog_eta','status':'private_author_proposal','record_manifest_sha256':sha(C/'record-manifest.json'),'canonical_package_sha256':sha(C/'package-manifest.json'),'source_freeze_sha256':sha(P/'package-freeze.json'),'bindings':bindings})
template=(T/'protocol-template.mjs').read_text(encoding='utf-8');template=template[:template.index('function draw(c)')]+(A/'draw-scenes.mjs').read_text(encoding='utf-8')+'\n'+template[template.index('function quantity(q)'):]
template=template.replace('Matuhina2023','Pati2009').replace('matuhina2023','pati2009').replace('Matuhina et al. 2023','Pati et al. 2009').replace('matuhina-','pati-')
template=template.replace('DATA.configs[o?.id]','DATA.configs[r.record_id+\'--\'+o?.id]')
template=template.replace('.map(([k])=>k)', '.map(([,c])=>c.operation_id)')
(A/'protocol-template.mjs').write_text(template,encoding='utf-8');(A/'pati2009-protocol.mjs').write_text(template.replace('__CONFIG__',json.dumps(data,ensure_ascii=False,separators=(',',':'))),encoding='utf-8')
shutil.copyfile(T/'quantity-value.mjs',A/'quantity-value.mjs')
save('helper-provenance.json',{'templates':[{'path':str(T/'protocol-template.mjs'),'sha256':sha(T/'protocol-template.mjs'),'reuse':'Drawing primitives, quantity formatter and responsive condition layout; source-specific draw cases replaced.'},{'path':str(T/'quantity-value.mjs'),'sha256':sha(T/'quantity-value.mjs'),'reuse':'Unmodified formatter copy.'}],'new_model_or_data':False})
print(json.dumps({'records':len(records),'scenes':len(cfg),'distinct_operations':19,'parameters':sum(len(o['parameters'])for r in records for o in r['operations'])}))
