"""Freeze independent projection/code/editorial review; all shared inputs read-only."""
from pathlib import Path
from datetime import datetime,timezone
from collections import Counter
import ast,hashlib,json,re,subprocess
O=Path(__file__).resolve().parent;B=O.parent;M=O.parents[4];A=M/'research-assets';Q=A/'incoming-paper-monitor';D=M/'recipe-atlas/dist';C=M.parent/'mattersyn-github-public-clean/mattersyn-site';OLD=M.parent/'mattersyn-github-public/mattersyn-site'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def load(p):return json.loads(Path(p).read_bytes())
bound={};checks=[]
def bind(p):p=Path(p).resolve();bound[str(p)]=sha(p);return p
def ck(scope,statement,ok,detail=None):checks.append({'scope':scope,'statement':statement,'passed':bool(ok),'detail':detail})
comparison=load(bind(O/'projection-comparison.json'))
roots={'site':D,'clean':C,'old_working':OLD}
for name,h in comparison['full_file_sha256'].items():
    label,rel=name.split('/',1);p=roots[label]/rel
    ck('frozen comparison bytes',name,p.is_file() and sha(p)==h)
    bound[str(p.resolve())]=h
ck('projection inventory','6,548 projected files plus empty .nojekyll',comparison['source_file_count']==6564 and comparison['clean_file_count']==6549 and (C/'.nojekyll').read_bytes()==b'')
ck('projection inventory','Only 16 Norberg whole-page PNGs omitted',len(comparison['missing_from_clean'])==16 and all(p.startswith('assets/figures/norberg2004/pages/') and p.endswith('.png') for p in comparison['missing_from_clean']))
ck('projection inventory','No unreviewed additions except .nojekyll',comparison['added_to_clean']==['.nojekyll'])
ck('canonical science','470 canonical JSON records byte-identical to S/dist and published baseline',comparison['record_count']==470 and comparison['records_byte_identical_source_and_baseline'])
ck('reader science','26 formal readers and exactly one changed reader',comparison['readers_count']==26 and len(comparison['reader_changes'])==1 and comparison['reader_changes'][0]['path']=='data/paper-reviews/norberg2004.json')
delta=comparison['reader_changes'][0]['json_differences']
ck('reader science','Exactly 34 public_asset whole-page URL fields removed; no facts/values/objects changed',len(delta)==34 and all(x['kind']=='removed' and x['pointer'].endswith('/public_asset') and isinstance(x['before'],str) and '/norberg2004/pages/' in x['before'] for x in delta),delta)
ck('original figures','All 24 selected Norberg crops retained byte-identical',len(comparison['norberg_selected_crops'])==24 and comparison['all_selected_crops_retained_byte_identical'])
htmlchanges=[x for x in comparison['differences'] if x['path'].endswith('.html')]
ck('URL transport','Four HTML deltas from S/dist are only former-host replacement',len(htmlchanges)==4 and all(x['old_site_host_replacement_only'] for x in htmlchanges))
baseline=comparison['baseline_comparison']
ck('published baseline','Original commit matches recorded publication',comparison['old_baseline_commit']==load(bind(Q/'latest-publication.json'))['commit_sha']=='6e9c97b961fa0d5db2463cc017f483e406908389')
ck('published baseline','Committed baseline changed only progress presentation and page-attachment projection',set(baseline['changed'])=={'README.md','data/paper-reviews/norberg2004.json','dataset.html','index.html','inventory.html','library.html'} and set(baseline['new'])=={'REFERENCES.md','data/review-progress.json','progress.css','progress.html','progress.mjs'} and baseline['omitted']==comparison['missing_from_clean'])
oldstatus=comparison['old_working_status'].splitlines()
ck('published baseline','Old working copy has documented ten progress changes, not used as immutable baseline',len(oldstatus)==10 and not any('data/records/' in s for s in oldstatus))

codepaths=[A/'sync_github_public.py',A/'github_public_delivery.py',A/'sync_github_private.py',A/'public_projection_policy.py',A/'build_reference_readmes.py',A/'update_deadline_delivery.py',Q/'build_public_progress.py',Q/'public-progress-editorial.json',A/'github-public-site-sync.json',B/'public-repository-exclusion-proposal-20260920.json',B/'public-repository-exclusion-proposal-20260920.md',Q/'deadline-20260920/active-cutoff.json',O/'test_delivery_guards.py',O/'inspect_projection.py',Path(__file__)]
for p in codepaths:bind(p)
sync=(A/'sync_github_public.py').read_text(encoding='utf-8');api=(A/'github_public_delivery.py').read_text(encoding='utf-8');oldsync=(A/'sync_github_private.py').read_text(encoding='utf-8');policy=(A/'public_projection_policy.py').read_text(encoding='utf-8')
for name,src in [('sync',sync),('delivery',api),('policy',policy)]:ast.parse(src);ck('code syntax',name+' parses',True)
oldtree=ast.parse(oldsync);ck('superseded script','Historical private synchronizer stops before imports/work',isinstance(oldtree.body[1],ast.Raise) and 'sync_github_public.py' in ast.unparse(oldtree.body[1]))
ck('sync boundary','Project/site destinations are fixed isolated checkouts',"'project':ROOT.parent/'mattersyn-github-project'" in sync and "'site':ROOT.parent/'mattersyn-github-public-clean'/'mattersyn-site'" in sync)
ck('sync boundary','Origin URL is checked before synchronization when configured',"remote','get-url','origin'" in sync and 'Unexpected destination remote; stopped.' in sync)
ck('sync boundary','Source writes absent; updates and removals target isolated copy only','target=dest/rel' in sync and 'target.write_bytes(clean)' in sync and 'dest.resolve() not in target.parents' in sync and 'target.unlink()' in sync)
ck('sync boundary','Sync performs no commit/push or remote API actions',"'git_commit_or_push_performed':False" in sync and "git(dest,'push'" not in sync and "git(dest,'commit'" not in sync and 'urllib' not in sync)
ck('projection policy','Exclusion proposal hash and count match reviewed policy',sha(B/'public-repository-exclusion-proposal-20260920.json')=='572ae70749f8fac09451154a565e8ede9ac486ba5f39d595bfa903d94334ae82' and 'EXPECTED_EXCLUDED_PATHS = 12556' in policy)
ck('projection policy','Recursive private-field and scoped whole-page attachments removed','firstPagePreviewPrivate' in policy and "key=='public_asset' and is_withheld_page_url(value)" in policy)
ck('projection policy','Original source formats and PDF magic rejected',"('.pdf','.doc','.docx','.ppt','.pptx','.zip','.xls','.xlsx')" in policy and "raw.lstrip().startswith(b'%PDF-')" in policy)
ck('projection policy','Credentials omitted from logged data; pattern detector is not blanket guarantee','No general PII guarantee' in policy and 'no credential' in api.lower() and 'no credential details logged' in api.lower())
ck('API scope','Exact account login and numeric ID gate precedes repository work',"OWNER='cuiyist'" in api and "user.get('id')!=147659097" in api and "NAMES={'mattersyn','mattersyn-site'}" in api)
ck('API scope','Exact original repository ID and unused preservation name required','old.get(\'id\')!=args.expected_old_id' in api and 'Preservation name already exists; inspect before retry.' in api)
ck('API preservation','Original repository renamed privately before fresh public creation',api.index("{'name':archive,'private':True}")<api.index("'/user/repos','POST'") and "saved.get('private') is not True" in api and "new.get('private') is not False" in api)
ck('API preservation','No repository deletion or force-push operation',not re.search(r"['\"]DELETE['\"]|--force|force_push",api))
ck('API preservation','Fresh public repo is not auto initialized; Pages fixed main/root',"'auto_init':False" in api and "{'branch':'main','path':'/'}" in api)
test=subprocess.run(['[local path redacted]','-B','-X','utf8','-m','unittest','-v','test_delivery_guards.py'],cwd=O,capture_output=True,text=True)
ck('offline guard simulations','Eight mocked account/ID/archive/visibility/scope checks passed',test.returncode==0 and 'Ran 8 tests' in test.stderr and 'OK' in test.stderr,test.stderr)

progress=load(C/'data/review-progress.json');editorial=load(Q/'public-progress-editorial.json');cutoff=load(Q/'deadline-20260920/active-cutoff.json');release=load(Q/'latest-publication.json')
ck('final editorial','Exact current public progress hash matches source and committed clean projection',sha(C/'data/review-progress.json')==sha(D/'data/review-progress.json')=='d2737a4f6033b6c469c68abebe5bce2c9d17629d77cb42374dc9cfae7eada011')
for k in ('batch','current_work','recent_milestones','estimate'):ck('editorial transport',k+' matches source',progress[k]==editorial[k])
ck('published counts','470 records, 97 routes, 42 collections, zero exact pairs',all(progress['published'][k]==release[k] for k in progress['published']) and [progress['published'][k] for k in ('record_count','synthesis_route_count','material_hub_count','exact_structure_recipe_count')]==[470,97,42,0])
ck('current paper','Heo remains unpublished with downstream stages pending',not progress['batch']['papers'][-1]['published'] and progress['current_work'][0]['stages'][3]['status']=='in_progress' and progress['current_work'][0]['stages'][-1]['status']=='pending')
estimate=progress['estimate'];summary=estimate['summary'];notes=' '.join(estimate['notes'])
ck('deadline scope','Two-month target is expressly unsupported by demonstrated capacity','two-month target for the existing collection' in summary and 'not yet supported by demonstrated processing capacity' in summary)
ck('deadline arithmetic','158 per 60 days and 190 per 50 production days are rounded required rates',round(9470/60)==158 and 189<=9470/50<=190 and '158 closed scopes per day over 60 days' in summary and '190 per production day if 10 days are reserved' in summary)
ck('deadline scope','Cutoff files and unresolved grouping remain separate from known pending scopes',all(t in notes for t in ('13,831','9,470','45 files','three nested document candidates','not a verified unique-paper total')) and cutoff['counts']['unmapped_cutoff_files']==45 and cutoff['counts']['nested_cutoff_candidates_held']==3)
ck('deadline scope','Later new papers separated, included-paper SI still updates evidence','Later new papers are queued separately' in notes and 'late or changed SI for an included paper remains an evidence update' in notes)
ck('capacity limits','No paid API or achieved speedup claim','No paid API processing has started' in notes and 'finish remain unverified' in notes and 'do not guarantee a proportional speedup' in notes)
ck('timestamp semantics','Snapshot-generated label used with separate scan timestamp','Snapshot generated ${date(data.updated_at)}' in (C/'progress.mjs').read_text(encoding='utf-8') and progress['corpus_scanned_at']!='' and progress['corpus_scanned_at']!=progress['updated_at'])
ck('citation cosmetics','Doubled terminal period removed without source-record edits','Quantum Dots..' not in (C/'REFERENCES.md').read_text(encoding='utf-8'))
refs=(C/'REFERENCES.md').read_text(encoding='utf-8');dois=re.findall(r'^- .*?\]\(https://doi\.org/([^\)]+)\)',refs,re.M)
records=[load(p) for p in (M/'recipe-atlas/data/records').glob('*.json')];primary={s['doi'].lower() for r in records for s in r['sources'] if s['id']==r['lineage']['source_group']}
ck('citation scope','All 31 primary DOIs from published canonical records, no Heo addition',len(dois)==len(set(dois))==31 and set(x.lower() for x in dois)==primary and '10.1021/jp0219348' not in primary)
ck('citation scope','Root and clean bibliography contents agree',(M/'REFERENCES.md').read_bytes()==(D/'REFERENCES.md').read_bytes()==(C/'REFERENCES.md').read_bytes())
old_audit=load(bind(B/'public-progress-review/independent-audit.json'))
for cite in old_audit['citation_mapping']:
    line=next(line for line in refs.splitlines() if line.startswith('- ') and 'https://doi.org/'+cite['doi'] in line)
    authors=cite['authors'];authors='; '.join(authors) if isinstance(authors,list) else authors
    ck('citation metadata',cite['doi']+' authors/title/year/scope retained',authors in line and cite['title'].rstrip('.') in line and f"({cite['year']})." in line and ('SI unverified' in line if 'si_unverified' in cite['scope'] else ('matched SI reviewed' in line if cite['scope']=='supplied_main_and_matched_si' else 'does not imply full main/SI review' in line)))
for p in (C/'data/review-progress.json',C/'progress.html',C/'progress.mjs',C/'README.md',C/'REFERENCES.md'):
    t=p.read_text(encoding='utf-8');ck('public private-path scope',p.name+' contains no raw private absolute paths',not re.search(r'(?<![A-Za-z0-9])[A-Za-z]:[[local path redacted]
for p in (M/'README.md',M/'REFERENCES.md',D/'README.md',D/'REFERENCES.md'):bind(p)
git=subprocess.run(['C:/Program Files/Git/cmd/git.exe','-c','safe.directory='+C.as_posix(),'-C',str(C),'rev-parse','HEAD'],capture_output=True,text=True,check=True)
cleanhead=git.stdout.strip();ck('clean commit','Clean projection commit matches root freeze',cleanhead=='3289675fe54374d5619f932e16b8a8d2842c4c37')
committed_progress=subprocess.run(['C:/Program Files/Git/cmd/git.exe','-c','safe.directory='+C.as_posix(),'-C',str(C),'show',cleanhead+':data/review-progress.json'],capture_output=True,check=True).stdout
ck('final editorial','Current progress bytes equal final clean commit blob',hashlib.sha256(committed_progress).hexdigest()==sha(C/'data/review-progress.json'))
for p in (O/'pre-final-hash-audit.json',O/'pre-final-hash-audit.md'):bind(p)
fail=[x for x in checks if not x['passed']]
report={'schema':'mattersyn-public-projection-delivery-independent-audit/1','author':'/root','auditor':'/root/backlog_eta','reviewer':'/root/backlog_eta','at':datetime.now(timezone.utc).isoformat(),'status':'passed' if not fail else 'findings_require_resolution','scope':'Independent local projection, reader/canonical transport, final deadline/citation metadata and static/offline API guard audit. No actual API, credential, browser, push or external-write operation performed.','counts':{'checks':len(checks),'failed':len(fail),'clean_files_including_nojekyll':6549,'unchanged_canonical_records':470,'reader_files':26,'removed_whole_page_url_fields':34,'excluded_whole_page_images':16,'retained_norberg_selected_crops':24,'primary_doi_citations':31,'offline_guard_tests':8},'required_findings':fail,'resolved_findings':[{'id':'API-1','initial_finding':'Fresh repository visibility check accepted missing private field as verified public.','root_correction':'Fresh private must be exactly False; preserved archive private must be exactly True.','verification':'Corrected code bound; missing-visibility and wrong-preservation-state offline tests pass.'}],'checks':checks,'bound_files':bound,'old_public_baseline_commit':comparison['old_baseline_commit'],'clean_projection_commit':cleanhead,'preservation_plan_review':'Original repository identity must match caller-reviewed numeric ID; preserve it under the fixed private archive name before creating a fresh public repository for filtered reachable objects. This audit verifies the code gates, not remote execution or remote visibility.','deadline_interpretation':'158/day and 190/production-day are explicitly required-rate arithmetic for a stated 60-day planning approximation and 10 reserved days. The recorded two-calendar-month cutoff target is a project objective, not an achieved capacity or promise; exact calendar window differs from that planning approximation.','scope_limits':['Root browser QA and anonymous delivery verification remain separate; no browser action was performed here.','Complete project-history filtering and commit metadata preservation are another reviewer’s scope; this report binds the current website projection and corrected delivery code.','Scientific audits continue to refer to unchanged local source/canonical artifacts. Removing public attachments does not independently re-audit scientific statements or confer redistribution rights.','Synchronizer implementation permits a missing origin for a freshly initialized isolated destination; the later delivery/push workflow must retain the exact reviewed repository target. No remote action was taken by this audit.'],'mutations':'Only private public-projection-review reports and test/check scripts written.'}
report['final_binding_note']={'superseded_announced_progress_sha256':'dd6feb89addacc7e4d6066798d4fee0ce8447ab2101aa9e53ba7c79c48c3def0','current_progress_sha256':sha(C/'data/review-progress.json'),'basis':'Root confirmed the earlier announcement hashed LF text in memory, while Windows write_text produced CRLF file bytes. The generator now prints the SHA256 of read_bytes; this output-only code correction is bound. Source site, clean working file and final committed Git blob have identical current bytes. The preliminary mismatch report is preserved.'}
(O/'independent-audit.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
md=['# Public projection and delivery audit','',f"**{report['status']}** — author `/root`; independent auditor `/root/backlog_eta`. {len(checks):,} checks; {len(fail)} unresolved findings.",'','All 470 canonical record JSON files remain byte-identical to both the source site and original public commit `6e9c97b961fa0d5db2463cc017f483e406908389`. All 26 source readers retain their content; Norberg has exactly 34 `public_asset` whole-page URL fields removed, with the surrounding objects, scientific facts and locators preserved. Exactly 16 whole-page PNGs are omitted; all 24 selected Norberg crops remain byte-identical. Four HTML differences from the local source site only replace the former hosting URL and already match the original public baseline.','','The final clean projection has 6,549 files including `.nojekyll`, committed as `3289675fe54374d5619f932e16b8a8d2842c4c37`. The old working checkout’s ten progress edits were distinguished from its committed baseline. No hidden scientific edits were found.','','The final 31 DOI citations preserve stored author/title/year and source-review scope. The doubled citation period is corrected. Snapshot generation time is labeled accurately and distinguished from the corpus scan and scientific publication. Heo remains unpublished. The two-month target is explicitly unsupported by demonstrated capacity: the stated 158/day and 190/production-day are required arithmetic under a 60-day planning approximation, not achieved rates. The fixed 13,831-file document inventory is distinguished from 9,470 known pending scopes, 45 unmapped files and three nested candidates. No paid API processing is claimed.','','The account, original-ID and archive-name checks precede preservation. One required narrow code correction was applied by root: created repository visibility must be exactly `False`, while preserved archive visibility must be exactly `True`. All eight offline guard simulations now pass, including missing visibility, wrong account, wrong original ID and occupied archive name. Credential lookup and API functions were replaced with local test doubles before branch execution; no actual API or credential call was made.','','The historical private-only synchronizer stops before work. The new synchronizer targets fixed isolated checkouts, applies the reviewed projection policy and bounds tracked-file deletions to those checkouts. It does not commit or push. Remote preservation/creation, actual Pages delivery, browser QA and full project-history filtering remain separate root/other-reviewer gates.','','Exact code, editorial, projection and evidence hashes are in `independent-audit.json`; exhaustive file comparison is retained in `projection-comparison.json`.','']
md += ['The progress JSON is bound to current hash `d2737a4f6033b6c469c68abebe5bce2c9d17629d77cb42374dc9cfae7eada011`, identical in the source site, clean working copy and final committed Git blob. Root confirmed that the earlier `dd6feb…` announcement hashed LF text in memory while Windows wrote CRLF file bytes. The generator now prints the hash of actual file bytes; this output-only correction is bound. The preliminary mismatch report is preserved separately.','']
for x in fail:md += [f"Required: {x['scope']} — {x['statement']}.",'']
(O/'independent-audit.md').write_text('\n'.join(md),encoding='utf-8')
print(json.dumps({'status':report['status'],'checks':len(checks),'failed':fail,'audit_sha256':sha(O/'independent-audit.json'),'markdown_sha256':sha(O/'independent-audit.md'),'helper_sha256':sha(A/'github_public_delivery.py'),'progress_sha256':sha(C/'data/review-progress.json'),'clean_commit':cleanhead}))
