assets={a['id']:a for a in manifest['assets']}
groups={'figures':[],'tables':[],'schemes':[],'equations':[],'source_notes':[]}
def asset(key,group,caption,scope,records,classification,notes=(),panels=(),rows=None,axes=()):
 a=assets[key];e=ev(a['source_pdf_page'],a['label'])
 d={'id':key,'label':a['label'],'document_role':'main','page':a['source_pdf_page'],'printed_page':e['printed_page'],'source_locators':[e['locator']],'caption_paraphrase':caption,'sample_scope':scope,'sample_links':[P+r for r in records],'sample_linkage':'Explicit source cohort association only; shared host chemistry does not identify a physical specimen across substrates or techniques.','evidence_class':classification,'public_asset':a['public_asset'],'public_asset_sha256':a['sha256'],'asset_provenance':{'source_file':a['source_filename'],'source_sha256':a['source_sha256'],'source_pdf_page':a['source_pdf_page'],'crop_bbox_pdf_points_top_left':a['crop_bbox_pdf_points_top_left'],'crop_normalized':a['crop_normalized'],'render_dpi':a['render_dpi'],'pixel_dimensions':a['pixel_dimensions'],'renderer':'PDFium 300 dpi original-source crop','transformation':a['transformation']},'quantitative_context':list(notes),'panels':list(panels),'notes':list(notes),'axes':list(axes),'text_reviewed':True,'visual_reviewed':True,'reviewed':False,'reader_render_verified':False,'training_eligible':False,'source_asset_type':a['source_asset_type']}
 if rows is not None:d['structured_rows']=rows
 groups[group].append(d)
asset('figure-1','figures','Original UV–visible spectra and optically inferred CdS size progression in CTAB and copolymer hosts.','Panels a/b: CTAB host; c/d: distinct larger-pore copolymer host. Cycle labels are process states, not physical batch identifiers.',['ctab-cds-loading','copolymer-cds-loading','uv-visible'],'experimental_and_optically_derived',['Absorbance curves retain the calcined-film baseline and original selected cycle labels.','Text endpoints: CTAB 2.2 to 3.6 nm; copolymer 3.3 to 5.8 nm. Sizes derive from cited gap–size correlations, not TEM diameter histograms.','CTAB saturation is stated after nine cycles; copolymer six-cycle endpoint is read from the graph.','The zero-cycle origin is a graphical baseline, not a measured zero-diameter crystallite.','Intermediate point heights are not converted into invented exact numerical values.'],['a: CTAB absorption, cycles 1, 2, 3, 4, 5, 7, 9','b: CTAB inferred size','c: copolymer absorption, cycles 1, 2, 3, 4, 6','d: copolymer inferred size'],axes=['a/c: wavelength (nm), 300–600; absorbance, 0–0.5','b: particle size (nm), 0–4; number of impregnations through 9','d: particle size (nm), 0–6; number of impregnations through 6'])
asset('figure-2','figures','Original evolution of the mesostructure 0002 X-ray peak during cadmium adsorption and CdS filling.','Calcined, Cd²⁺-impregnated and filled CTAB-film contexts; not atomic CdS powder diffraction.',['xrd'],'experimental',['Calcined-film trace is scaled by 0.5 and first-cycle trace by 5.','Later labeled filling states include 2, 3, 4, 5, 7 and 9.','Source c values: 6.9 nm calcined, 6.8 nm Cd-adsorbed and 7.2 nm saturated.','Peak intensity changes are interpreted through changing electron-density contrast; no raw integrated intensities are supplied.'],axes=['2θ (degrees), approximately 2.2–2.9','Intensity (a.u.), uncalibrated numerical ordinate'])
asset('figure-3','figures','Original filled/empty cross-sectional HRTEM comparison, enlarged particle array and Fourier power spectrum.','a/c/d: source saturated-film image and its derived views; b: separate empty calcined host control.',['hrtem'],'experimental_image_and_fourier_analysis',['Scale bars: a/b 30 nm; c 20 nm.','Panel d is |Fourier transform|² of the image, not SAED.','Mesostructure labels: (0 0 0 2), (0 1 −1 1), (0 1 −1 0).','Some particles show atomic CdS blende 111 fringes; this is distinct from the hexagonal host/particle array.','A few bright points near the substrate are assigned to empty pores. No 100% pore occupancy is inferred.'],['a: saturated cross section','b: empty calcined cross section','c: enlargement of a','d: power spectrum of a'],axes=['Real-space scale bars retained; no calibrated reciprocal-length scale in d'])
asset('figure-4','figures','Original room-temperature excitation and luminescence spectra of a silicon-supported CdS-loaded film.','Silicon-supported optical specimen; body and caption disagree on process-state assignment of upper/lower curves.',['pl-silicon'],'experimental_with_source_assignment_conflict',['Dashed curves: excitation; solid curves: luminescence.','Caption: upper curves after first H₂S, lower curves after the next Cd impregnation.','Body: weak broad 640 nm emission after first H₂S; stronger 640 nm plus sharp 450 nm emission after subsequent Cd impregnation. The visibly stronger upper curve contains the sharp band.','Both source statements and original curve order are preserved; no silently relabeled curve is promoted as an exact training label.','Room temperature is specified for these spectra, not automatically for the loading synthesis.'],axes=['Wavelength (nm), 300–700','Intensity (a.u.), no numerical ordinate calibration'])
asset('matrix-preparation-start','source_notes','Original matrix-sol composition, aging, CTAB ratio and ethanol-dilution paragraph.','Explicit CTAB-host preparation, continued in the next crop.',['ctab-silica-host'],'direct_source_method',['TEOS:H₂O:ethanol = 1:5:3.8 molar; acidic water pH 1.25; 1 h at 60 °C; CTAB/TEOS = 0.1 molar.','Ethanol dilution is 1:1 without a stated ratio basis. The paragraph continues with Pyrex deposition.'])
asset('matrix-preparation-continuation','source_notes','Original spin-coating, air-calcination and host-thickness/texture statements.','Continuation of the explicit CTAB-host preparation.',['ctab-silica-host'],'direct_source_method',['3,000 rpm spin coating on Pyrex; air calcination at 450 °C.','Approximately 300 nm film; 3D hexagonal structure and c-axis perpendicular to substrate.','Coating and calcination durations are not stated.'])
asset('impregnation-precipitation','source_notes','Original cadmium complex-stock, water rinse, evacuation and H₂S filling procedure.','Common filling strategy; the larger-pore host preparation is separately incomplete.',['cadmium-stock','ctab-cds-loading','copolymer-cds-loading'],'direct_source_method',['0.1 M aqueous cadmium nitrate; one equivalent each ammonia and sodium citrate, the latter a 1 M aqueous stock; further ammonia to pH 9.5.','Deionized-water rinse; vacuum; slow gas admission until P(H₂S) = P(atmosphere).','No numerical vacuum level, gas flow or gas hold time supplied.'])
asset('note-36','source_notes','Original internal note estimating a 3.5 nm mean pore diameter.','Model-dependent host geometry; not a CdS crystallite measurement.',['ctab-silica-host'],'direct_source_analysis_note',['Assumes spherical pores and combines porosity measurements with XRD-derived hexagonal unit-cell volume.'])
asset('note-38','source_notes','Original internal note identifying the reverse-micelle CdS comparator.','Colloidal optical loading reference; not a complete additional synthesis recipe.',['loading-fraction'],'direct_source_analysis_note',['Reference 42 is cited for the reverse-micelle technique; that external preparation was not independently inspected here.'])
asset('power-spectrum-definition','source_notes','Original Fourier-power definition and mesostructure symmetry/parameter paragraph.','Image analysis of the particle/pore superlattice; no atomic CdS structure solution.',['hrtem'],'direct_source_analysis_note',['Power spectrum = |Fourier transform|².','P6₃/mmc, approximately a = 6.0 nm, c = 6.8 nm, c/a = 1.13.','Keep separate from XRD saturated c = 7.2 nm and atomic 111 CdS fringes.'])
