"""Explicit semantic mapping from the independently inventoried source units."""
from pathlib import Path
import json
O=Path(__file__).resolve().parent;B=O.parent;M={}
def bind(target,*units):
 for u in units:
  key='besson2002-'+u;M.setdefault(key,[])
  for t in target.split():
   if t not in M[key]:M[key].append(t)
bind('identity','identity-title','identity-journal','identity-dates')
bind('identity source-context','identity-authors')
bind('source-context','identity-administrative')
bind('historical-scope generalization','abstract-claim')
bind('historical-scope pore-size-control','abstract-evidence')
bind('nanoscale-context','context-size-effects')
bind('array-motivation','context-control','context-applications')
bind('template-rationale','context-template','context-pore-range')
bind('film-motivation','context-powders','context-nanowires','context-films')
bind('teos','chemical-teos')
bind('water','chemical-acid-water','chemical-rinse-water')
bind('ethanol','chemical-ethanol')
bind('ctab','chemical-ctab')
bind('cadmium-nitrate stock-composition','chemical-cd-nitrate')
bind('ammonia','chemical-ammonia')
bind('citrate','chemical-citrate')
bind('hydrogen-sulfide','chemical-h2s')
bind('substrates','chemical-substrates')
bind('copolymer','chemical-copolymer')
bind('host-vs-crystal','chemical-matrix-product')
bind('method-dependencies','matrix-dependency')
bind('sol-mixing','matrix-sol-ratio')
bind('sol-aging','matrix-age')
bind('template-addition','matrix-ctab-add')
bind('ethanol-dilution','matrix-dilute')
bind('spin-coating','matrix-coat')
bind('calcination','matrix-calcine')
bind('host-order host-thickness','matrix-film')
bind('connected-porosity','matrix-open-porosity')
bind('cadmium-stock-preparation cadmium-nitrate','stock-cd-start')
bind('ammonia stock-composition','stock-ammonia-first')
bind('citrate','stock-citrate')
bind('cadmium-stock-preparation ammonia','stock-ph')
bind('complexation','stock-complex','stock-hydroxides')
bind('ph-window','stock-ph-window')
bind('impregnation','loading-impregnate')
bind('rinsing','loading-rinse')
bind('surface-retention','loading-retention')
bind('evacuation','loading-evacuate')
bind('gas-precipitation','loading-gas')
bind('ctab-cycles copolymer-cycles','loading-repeat')
bind('gas-diffusion','loading-gas-rationale')
bind('silanol-regeneration','loading-silanol-regeneration')
bind('unreported-fields gas-precipitation','loading-missing')
bind('color-sequence','ctab-colors')
bind('ctab-cycles','ctab-saturation')
bind('ctab-size','ctab-size-first','ctab-size-final')
bind('ctab-absorption','ctab-exciton')
bind('pore-size-control','ctab-size-control','copolymer-generalization')
bind('copolymer copolymer-size','copolymer-scope')
bind('copolymer-gap','copolymer-recipe-gap')
bind('copolymer-absorption','copolymer-redshift','copolymer-exciton-loss')
bind('copolymer-size','copolymer-size-first')
bind('copolymer-size copolymer-cycles','copolymer-size-final')
bind('uv-acquisition','uv-acquisition','uv-size-model')
bind('sims-acquisition','sims-method')
bind('depth-uniformity','sims-result')
bind('xrd-acquisition','xrd-instrument','xrd-texture')
bind('xrd-before-growth','xrd-initial-change','xrd-initial-c')
bind('host-deformation','xrd-condensation','xrd-deformation')
bind('xrd-contrast','xrd-h2s-first','xrd-contrast-adsorb','xrd-contrast-cds')
bind('xrd-width','xrd-width')
bind('xrd-filling','xrd-final-c')
bind('xrd-width pore-size-control','xrd-combined')
bind('loading-analysis','filling-comparator')
bind('volume-fractions','filling-cds-fraction','filling-pore-fraction','filling-occupancy')
bind('ctab-size loading-analysis pore-estimate','filling-diameter-scope')
bind('hrtem-acquisition','tem-instrument','tem-focus')
bind('hrtem-filled-empty','tem-filled','tem-empty')
bind('tem-contrast','tem-contrast')
bind('hrtem-empty-pores','tem-residual-pores')
bind('figure3-panels cds-fringes','tem-enlargement')
bind('cds-fringes','tem-cds-lattice')
bind('tem-orientation','tem-orientations','tem-projection')
bind('image-power','tem-power-spectrum','tem-mesosymmetry','tem-mesoparameters')
bind('mesostructure-comparison','tem-c-conflict')
bind('hrtem-empty-pores hrtem-filled-empty connected-porosity','tem-conclusion')
bind('pl-acquisition','pl-instrument','pl-substrate','pl-temperature','pl-excitation-limits')
bind('pl-first','pl-first-h2s')
bind('pl-reimpregnation pl-passivation','pl-next-cd','pl-bound-exciton')
bind('pl-passivation','pl-passivation')
bind('pl-later','pl-later-cycles')
bind('pl-quenching','pl-wall-rationale')
bind('pl-figure-conflict','pl-caption-conflict')
bind('figure1-spectra figure1-sizes','figure-1','figure-1-ctab-series')
bind('figure1-spectra figure1-sizes copolymer-cycles','figure-1-copolymer-series')
bind('figure2-axes','figure-2','figure-2-rescaling','figure-2-series')
bind('figure3-panels hrtem-filled-empty image-power','figure-3')
bind('figure3-panels','figure-3-scales','figure-3-indices')
bind('figure4-axes pl-figure-conflict','figure-4')
bind('host-thickness historical-scope','conclusion-control')
bind('connected-porosity','conclusion-connectivity')
bind('silanol-regeneration','conclusion-repeat-necessity')
bind('generalization','conclusion-extension')
bind('acknowledgment','acknowledgment')
bind('pore-estimate reference-36','note-36')
bind('loading-analysis reference-38','note-38')
bind('coverage unreported-fields structure-limit copolymer-gap','source-missing')
for n in range(1,44):bind(f'reference-{n:02}',f'reference-{n:02}')
audit=json.loads((B/'source-audit.json').read_text(encoding='utf8'));ids={u['id'] for u in audit['units']}
assert set(M)==ids,(ids-set(M),set(M)-ids)
(O/'source-item-mapping.json').write_text(json.dumps(M,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(len(M),'source units mapped')
