from pathlib import Path
import hashlib,json,datetime
O=Path(__file__).resolve().parent;F=O.parent;B=F/'visuals/molecular-bindings'
def read(p):return json.loads(Path(p).read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
a=read(O/'binding-checks.json');b=read(O/'consumer-independent-checks.json');assert a['status']==b['status']=='passed';bound=a['bound_files']
for p in [O/'check_bindings.py',O/'binding-checks.json',O/'check_consumer_independent.mjs',O/'consumer-independent-checks.json',B/'previews/msc-injection-varied.png',Path(b['module_path'])]:bound[str(p)]=sha(p)
out={'schema':'mattersyn-independent-molecular-binding-audit/1','status':'passed','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'author':'root','auditor':'peng1998_reader_assets','proposal_freeze_sha256':sha(B/'package-freeze.json'),'review_scope':'Exact source/material/stock bindings and consumer data dispatch; molecular identity/geometry qualification relies on the distinct passed backlog_eta audit. This audit does not certify browser integration or own product cards.','canonical_boundary':'draft-v2, 30 records. Pending reader-only v3 may use an explicit unchanged-record receipt; any record-byte change requires a new binding review.','molecular_chemistry_audit_sha256':sha(F/'molecular-independent-audit/independent-audit.json'),'open_findings':[],'check_counts':{'binding_and_dependency':a['check_count'],'independent_current_consumer':b['check_count']},'counts':{'material_slots':77,'stock_instances':8,'stock_components':16,'qualified_identities':39,'actual_slot_popup_executions':77,'stock_transitions':16,'context_transitions':16},'manual_scope':['Read all 39 source-specific identity captions/limitations and their source material roles; all 77 exact slot snapshots match frozen canonical records.','Read all eight stock summaries and source scoping. Final reaction volume is not stock volume; unknown concentrations stay unknown, commercial solution and transfer amounts remain separate.','The varied-concentration MSC stock excludes representative 20 mg and 0.00121 mmol. Its 1 mL solvent is explicitly inherited and condition concentrations remain reaction options.','Actually viewed the full 1100-pixel varied-stock preview; all five scope statements are readable and match the new SVG. Other stock/chemical assets are exact qualified reuse already visually reviewed by the distinct molecular auditor.','Checked N2 atmosphere versus liquid coolant, reactive labeled CO2 versus dry ice, carbonyl-label specificity, Grignard and indium formula fragments, unknown sodium-sulfate hydration, GPC medium, support and symbolic phase scopes.','Executed actual current chemicalEntry/openChemical/mountStockComponents/mountReagentComponents with an independently written minimal DOM. Exact geometry arrays, captions, private flags, override whitelist, keyboard rotation, controls and exclusions passed. No browser or WebGL rasterization claim.'],'bound_files':bound,'training_approved':False,'browser_verified':False,'publication_approved':False}
(O/'independent-audit.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(O/'independent-audit.md').write_text('# Friedfeld exact molecular bindings\n\nPassed. No open finding.\n\n77 material slots, eight stock instances and 16 components match the frozen canonical proposal. 928 independent binding checks and 941 actual-consumer checks passed.\n\n'+ '\n\n'.join(out['manual_scope'])+'\n\n'+out['canonical_boundary']+'\n',encoding='utf8')
print(sha(O/'independent-audit.json'),len(bound))
