"""Source-specific Heath1996 drafts; existing schema, no publication or training promotion."""
from pathlib import Path
import sys,json,hashlib
from copy import deepcopy
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas'
sys.path.insert(0,str(S/'scripts'))
from record_helpers import record,source,ev,fact,qty,material,operation,state,product,measurement
from dataset_lib import validate_record,eligibility,build_groups
OUT=B/'canonical-drafts';OUT.mkdir(exist_ok=True)
SID='heath1996'
SRC=source(SID,'10.1021/jp951903v','Spatially Confined Chemistry: Fabrication of Ge Quantum Dot Arrays','J. R. Heath; R. S. Williams; J. J. Shiang; S. J. Wind; J. Chu; C. D’Emic; W. Chen; C. L. Stanis; J. J. Bucchignano',1996)
SRC['main_status']='All six supplied main pages read and visually inspected; independent source audit in progress'
def E(page,section):return ev(SID,f'Main PDF p. {page}, printed p. {3143+page}, {section}')
P1=E(1,'Process Methodology');P2=E(2,'Process Methodology continuation');AN=E(2,'Analysis of the Ge Quantum Dots');W100=E(5,'100 nm Wells and Figure 6');W150=E(3,'150 nm Wells and Figure 3');KIN=E(4,'150 nm Wells and Figure 4');PILOT=E(2,'Results and Discussion, unpatterned growth trials')
def Q(value=None,unit='',e=P1,**kw):return qty(value,unit,e,**kw)
def F(value=None,e=P1,**kw):return fact(value,e,**kw)
def M(id,name,formula,role,stage,e=P1,notes=None):return material(id,name,formula,role,stage,e,notes=notes or [])
COMMON_GAPS=['Matching SI not located or verified.','Initial wafer cleaning reagents/conditions, oxidation temperature/time/atmosphere and wafer doping/resistivity are unreported.','PMMA molecular weight, solvent, solution concentration, coating method and spinning conditions are not reported; no spin-coating step is invented.','Developer ratio basis, bath temperature and development duration are unstated.','CF4/CHF3 flow ratio, etch pressure/power/time and endpoint parameters are unreported; no endpoint detection was used.','10% HF concentration basis, solvent, exact dip duration, rinse/dry and transfer conditions are unreported.','Gas stock fraction and sccm reference basis are unstated; gas purity/supplier, temperature ramp, cool-down and final storage are unreported.','Both well sizes occur on the same substrate/exposure; individual wafer or specimen identifiers are not supplied.','No measured atomic coordinates, XRD/SAED figure, Raman spectrum or near-IR spectrum is supplied.']
COMMON_CONFLICTS=['Figure 1 caption gives approximately 60–150 nm photoresist openings, whereas process prose gives approximately 60 and 100 nm; final etched openings are 100 and 150 nm.','Figure 2 body identifies 100 nm wells and a 25 square-micrometre field, whereas its caption identifies 150 nm wells. Keep the image unassigned to either template variant.','Title page prints Received July 6, 1995 and In Final Form November 6, 1994. This internally inconsistent chronology is preserved.']
def base(rid,title,kind='protocol_variant'):
    r=record(rid,'Heath et al. (1996) · '+title,'Ge/Si','Supported group-IV quantum-dot arrays','Template-confined UHV chemical vapor deposition',SRC,'Main PDF pp. 1–2, printed pp. 3144–3145, Process Methodology',kind)
    r['collection']='reviewed_literature';r['material'].update(elements=['Ge','Si'],components=['Ge','Si'],architecture='heterostructure')
    r['lineage']['recipe_family']='heath1996-patterned-wafer-cvd'
    r['intended_target']['composition']=F('Ge islands on Si(100) exposed through a patterned SiO2 mask')
    r['intended_target']['phase']=F(None,e=AN,note='No exact atomic target structure supplied.')
    r['intended_target']['morphology']=F('Spatially positioned quantum-dot arrays',e=P1)
    r['quality'].update(review_status='imported_unreviewed',requested_tasks=[],experimental_outcome='not_established',review_scope='Private structured draft from all six supplied main pages; canonical audit and reader integration remain pending. SI not located or verified. Shared template variants are not independent growth runs. No experimental atomic-structure or exact-size label is asserted.',missing_fields=COMMON_GAPS[:],conflicts=COMMON_CONFLICTS[:])
    r['context_links']=[{'label':'Source review','url':'../paper-review.html?id=heath1996','relation':'Supplied-main review; SI not located or verified.'}]
    return r

def template(width):
    r=base(f'heath-1996-ge-{width}nm-wells',f'Ge islands in {width} nm silicon wells')
    r['materials']=[M('si-wafer','Silicon (100) wafer','Si','substrate','precursor_preparation',notes=['Both 100 and 150 nm arrays are patterned on the same wafer. Cleaning is reported without reagents or conditions.']),M('silica-mask','Thermally grown silicon dioxide','SiO2','lithographic mask','precursor_preparation',notes=['About 20 nm oxide; grown in situ. Oxidant and oxidation conditions are not stated.']),M('pmma','Poly(methyl methacrylate)','(C5H8O2)n','electron-beam resist','precursor_preparation',notes=['Polymer identity; degree of polymerization, molecular weight, tacticity and resist formulation are not specified.']),M('ipa','Isopropyl alcohol','C3H8O','developer component','precursor_preparation'),M('mibk','Methyl isobutyl ketone','C6H12O','developer component','precursor_preparation'),M('cf4','Carbon tetrafluoride','CF4','reactive ion etchant','precursor_preparation'),M('chf3','Trifluoromethane','CHF3','reactive ion etchant','precursor_preparation'),M('acetone','Acetone','C3H6O','resist removal solvent','precursor_preparation',P2),M('hf','Hydrogen fluoride in 10% solution','HF','native oxide etchant','precursor_preparation',P2,notes=['Solution basis and solvent are not named; no exact aqueous formulation is inferred.']),M('geh4','Germane','GeH4','metalloid_precursor','synthesis',P2),M('he','Helium','He','carrier gas','synthesis',P2)]
    r['stocks']=[{'id':'developer','name':'Isopropyl alcohol / methyl isobutyl ketone developer','components':[{'material_id':'ipa','quantities':{}},{'material_id':'mibk','quantities':{}}],'concentrations':{'ipa_per_mibk':Q(3,'',raw_text='3:1',basis='Isopropyl alcohol:methyl isobutyl ketone; mass/volume/mole basis unstated')},'preparation_operation_ids':[],'scope':'Reported developer mixture; quantities and mixing procedure not supplied.','evidence':P1},{'id':'germane-stock','name':'10% GeH4 in He','components':[{'material_id':'geh4','quantities':{}},{'material_id':'he','quantities':{}}],'concentrations':{'germane_fraction':Q(10,'%',P2,basis='Reported gas-mixture fraction; concentration reference basis not stated')},'preparation_operation_ids':[],'scope':'90 sccm refers to this mixture, not pure germane.','evidence':P2},{'id':'hf-solution','name':'10% HF solution','components':[{'material_id':'hf','quantities':{}}],'concentrations':{'hf_fraction':Q(10,'%',P2,basis='Unspecified percent denominator and solvent')},'preparation_operation_ids':[],'scope':'Solvent identity and preparation recipe unreported.','evidence':P2}]
    specifications=[
      ('clean','wafer_cleaning','Clean silicon wafer',['si-wafer'],'clean-si','Reported cleaning; no reagents or conditions stated.',{},P1),
      ('oxidize','thermal_oxidation','Thermally oxidize silicon',['clean-si'],'oxide-si','Grow approximately 20 nm SiO2. Oxidation temperature, duration and oxidant are not reported.',{},P1),
      ('coat','resist_coating','Apply PMMA resist',['oxide-si','pmma'],'coated-si','Apply a 70 nm PMMA layer. Coating technique and formulation are not stated.',{'resist_thickness':Q(70,'nm')},P1),
      ('bake','resist_bake','Bake the resist',['coated-si'],'baked-si','Bake at the reported temperature and time; pressure and atmosphere are unspecified.',{'temperature':Q(80,'degC'),'duration':Q(1,'h')},P1),
      ('expose','electron_beam_lithography','Pattern point-exposure arrays',['baked-si'],'exposed-si','IBM Vector Scan electron-beam lithography; dwell time controls dose. The 200/400 nm pitch choices and 1 mm2–1 cm2 patterned-area range are not assigned to particular template regions. Both template diameters share the wafer.',{'beam_energy':Q(25,'keV'),'dose':Q(unit='uC/cm2',minimum=50,maximum=75),'pitch_option_1':Q(200,'nm'),'pitch_option_2':Q(400,'nm'),'area_lower_endpoint':Q(1,'mm2'),'area_upper_endpoint':Q(1,'cm2'),'dwell_time':Q(unit='s')},P1),
      ('develop','resist_development','Develop the resist pattern',['exposed-si','developer'],'developed-si','Use the reported 3:1 isopropyl alcohol/MIBK developer. Main prose reports approximately 60 and 100 nm openings; Figure1 caption instead gives approximately 60–150 nm. Individual doses are not mapped to opening sizes.',{'temperature':Q(unit='degC'),'duration':Q(unit='min')},P1),
      ('etch','reactive_ion_etching','Transfer the pattern into SiO2',['developed-si','cf4','chf3'],'etched-si','CF4/CHF3 reactive ion etching enlarges the oxide openings. RIE lag makes smaller openings etch more slowly; no endpoint detection. '+('The 150 nm region is over-etched by about 10 nm and has approximately 30 nm well depth.' if width==150 else 'The 100 nm region is close to the oxide thickness; approximately 17 nm well depth is measured by AFM. Later text attributes final exposure of Si bases to the HF dip.'),{'etch_time':Q(unit='min'),'etch_pressure':Q(unit='Torr'),'etch_power':Q(unit='W'),'cf4_to_chf3_ratio':Q()},P1+P2),
      ('strip','resist_removal','Remove the PMMA',['etched-si','acetone'],'stripped-si','Remove resist using an acetone rinse; volume, temperature and duration are unspecified.',{},P2),
      ('hf-dip','native_oxide_removal','Remove native oxide at exposed sites',['stripped-si','hf-solution'],'hf-cleaned-si','Briefly dip the wafer in 10% HF; exact time, solvent/basis, rinse and drying are not reported.',{'dip_duration':Q(unit='s',e=P2,raw_text='briefly')},P2),
      ('load','vacuum_loading','Load the UHV/CVD chamber',['hf-cleaned-si'],'loaded-si','Introduce the wafer into the load lock of the UHV/CVD chamber. Base pressure is separate from deposition pressure.',{'base_pressure':Q(5e-6,'Torr',P2,qualifier='less_than',raw_text='below 5 × 10^-6 Torr',basis='Reported chamber base pressure; threshold, not an exact operating pressure')},P2),
      ('grow','selective_cvd','Grow Ge islands in both template regions',['loaded-si','germane-stock'],'grown-si','Expose the wafer to 10% GeH4/He. Both template sizes receive the same deposition; the duration includes the incubation period and is not five minutes of post-nucleation growth. Gas purity, temperature ramp and cooling are not reported.',{'stock_gas_flow':Q(90,'sccm',P2,basis='10% GeH4/He mixture; standard flow reference temperature/pressure unstated'),'deposition_pressure':Q(unit='mTorr',e=P2,minimum=1,maximum=2),'growth_temperature':Q(600,'degC',P2),'exposure_duration':Q(5.0,'min',P2)},P2),
      ('dice','wafer_dicing','Divide wafer for analysis',['grown-si'],'pieces','Dice into several pieces for analysis; piece count/dimensions, dicing method and cross-technique specimen assignment are not stated.',{},P2)]
    prev=None
    for oid,action,label,inputs,out,description,parameters,e in specifications:
        r['material_states'].append(state(out,label+' output',inputs,'product' if oid=='dice' else 'mixture'))
        r['operations'].append(operation(oid,action,label,e,inputs,[out],depends=[prev] if prev else [],parameters=parameters,stage='synthesis' if oid=='grow' else 'workup' if oid=='dice' else 'precursor_preparation',description=description,environment=F('10% germane in He under reported deposition pressure',P2) if oid=='grow' else F(None,e)))
        prev=oid
    templ=product('template', 'Si with SiO2 mask',P1+P2,link='explicit',state='stripped-si',notes=['Template geometry before the common CVD exposure; not a Ge particle size. Figure2 geometry assignment is disputed.']);templ['source_sample_label']=f'{width} nm template region';templ['morphology']=F('Circular wells',P1)
    dots=product('ge-islands','Ge on Si',W150 if width==150 else W100,link='explicit',state='pieces',notes=['Template-level linkage is explicit, but physical wafer piece, individual well and cross-technique identity are not fully assigned.','The 100 and150 nm templates share the wafer and CVD exposure; not independent synthesized batches.']);dots['source_sample_label']=f'Ge islands in {width} nm wells'
    dots['phase']=F('Crystalline Ge epitaxially aligned with Si',W150,note='Moire fringes in 150 nm plan-view TEM; no experimental atomic coordinates.') if width==150 else F(None,AN+W100,note='Ge composition is assigned from the shared patterned-wafer characterization. No usable plan-view TEM of the 100 nm regions; AFM alone does not establish their individual core crystallinity.')
    dots['morphology']=F('Islands predominantly around well perimeter',W150) if width==150 else F('A central island in three of four imaged wells; one had no apparent island',W100)
    r['products']=[templ,dots]
    def measure(id,sample,prop,value,tech,e,conditions=''):r['measurements'].append(measurement(id,sample,prop,value,tech,e,conditions))
    measure('template-opening','template','well_diameter',Q(width,'nm',P1,basis='Reported final etched opening designation; not quantum-dot diameter'),'Lithographic and etching process description',P1)
    measure('template-depth','template','well_depth',Q(30 if width==150 else 17,'nm',P1 if width==150 else P2,approximate=True),'AFM',P1 if width==150 else P2,'Reported template depth; individual scan and HF-dip timing of this measurement are not independently specified.')
    measure('oxide-thickness','template','oxide_mask_thickness',Q(20,'nm',P1,approximate=True),'Thermal oxidation description',P1,'Initial oxide thickness, before RIE and HF removal.')
    if width==150:
        measure('islands-per-well','ge-islands','islands_per_well',Q(unit='count',e=E(1,'Abstract and Introduction'),minimum=2,maximum=4),'TEM',E(1,'Abstract and Introduction'),'Reported count range for 150 nm wells, not total wafer yield.')
        measure('distance-well-count','ge-islands','wells_in_distance_analysis',Q(50,'count',KIN),'TEM image analysis',KIN,'Figure4: 50 separate wells; nucleation order inferred from relative island size under stated kinetic assumptions.')
        measure('close-distances','ge-islands','nearest_neighbor_distances_below_100nm_count',Q(3,'count',KIN),'TEM image analysis',KIN+AN,'Only three distances below100nm; distances are center-to-center, using well-to-well centers as length standard. Not an absolute nucleation time measurement.')
    else:
        measure('imaged-wells','ge-islands','afm_wells_imaged',Q(4,'count',W100),'Supertip contact-mode AFM',W100)
        measure('single-dot-wells','ge-islands','afm_single_dot_wells',Q(3,'count',W100),'Supertip contact-mode AFM',W100,'Three of four selected images contain one central structure. This is not a75% fabrication success rate.')
        measure('empty-imaged-well','ge-islands','afm_wells_without_apparent_dot',Q(1,'count',W100),'Supertip contact-mode AFM',W100,'No apparent island in one selected well; detection limit and representativeness unstated.')
        for sid,label in [('fig6-dot','Figure6 imaged dot'),('second-dot','Second detailed AFM well')]:
            p=product(sid,'Ge on Si',W100,link='general_context',notes=['Same template class; no cross-technique physical-specimen identity established.']);p['source_sample_label']=label;r['products'].append(p)
        measure('fig6-height','fig6-dot','apparent_afm_height',Q(1.4,'nm',E(5,'Figure6 caption'),basis='Measured height interpreted by authors as lower bound on radius under similar-island morphology assumption'),'Supertip contact-mode AFM',E(5,'Figure6 caption'),'Tip-sample convolution can reduce apparent height and broaden width; not an exact radius.')
        measure('fig6-width','fig6-dot','apparent_afm_width',Q(33,'nm',E(5,'Figure6 caption'),basis='Measured width interpreted as upper bound on diameter'),'Supertip contact-mode AFM',E(5,'Figure6 caption'),'Figure6 caption; body gives separate diameter bounds3.0–34nm.')
        measure('first-bounds','fig6-dot','author_bounded_particle_diameter',Q(unit='nm',e=W100,minimum=3,maximum=34,status='author_derived',basis='Body-text lower/upper bounds using approximately hemispherical similar islands; not a size distribution'),'AFM with similar-island TEM morphology assumption',W100)
        measure('second-bounds','second-dot','author_bounded_particle_diameter',Q(unit='nm',e=W100,minimum=3,maximum=35,status='author_derived',basis='Second detailed well, distinct bounded diameter'),'AFM with similar-island TEM morphology assumption',W100)
        r['quality']['conflicts'].append('Figure6 caption measured height1.4nm/width33nm; body bounds3.0–34nm and second well3.0–35nm; Summary says3–30nm. These are distinct source descriptions, not a corrected exact diameter.')
    if width==100:
        next(op for op in r['operations'] if op['id']=='etch')['evidence']+=W100
    r['quality']['experimental_outcome']='reported_product'
    return r

records=[template(100),template(150)]
r=base('heath-1996-ge-characterization','Shared structural and spectroscopic characterization','procedure')
r['materials']=[M('carbon-tip','Carbon whisker','C','AFM probe modification','characterization',AN,notes=['Supertip geometry and fabrication recipe unreported.']),M('silicon-nitride-tip','Silicon nitride AFM tip',None,'AFM probe support','characterization',AN,notes=['Source identifies silicon nitride but does not specify exact stoichiometry; do not impose Si3N4 sample composition.'])]
r['material_states']=[state('diced-wafer','Diced patterned Ge/Si wafer pieces',kind='product')]
r['products']=[product('patterned-cohort','Ge on patterned Si',AN,link='general_context',state='diced-wafer',notes=['Raman and near-IR are reported for the patterned material collectively; no separation by100/150nm region or physical piece.'])]
r['products'][0]['source_sample_label']='Patterned-wafer characterization cohort'
for oid,action,label,parameters,description in [('raman','raman_spectroscopy','Micro-Raman spectroscopy',{},'LO phonon observed only in patterned regions. Excitation wavelength, power, resolution and spectrum are not supplied.'),('nir','near_ir_absorption','Near-infrared absorption',{},'Reported Ge surface-state peak; no displayed spectrum or acquisition settings. This peak is not a bandgap.'),('tem','plan_view_tem','Plan-view transmission electron microscopy',{'accelerating_voltage':Q(400,'kV',AN)},'JEOL4000; 150nm wells show Moire fringes, epitaxial registry and defects in some larger islands. Preparation destroyed or insufficiently thinned100nm regions. Image calibration uses well-to-well centers; no fabricated scale bar.'),('afm','contact_mode_afm','Supertip atomic force microscopy',{},'TopometrixTMX2010 MultiView, contact mode, carbon whisker on silicon nitride tip. High aspect ratio improves narrow-valley access; tip convolution still broadens widths and reduces heights.')]:
    context=AN+W150+W100 if oid=='tem' else AN+W100 if oid=='afm' else AN
    r['operations'].append(operation(oid,action,label,context,['diced-wafer'],[],parameters=parameters,stage='characterization',branch='independent_measurement',description=description))
r['measurements']=[measurement('raman-ge-lo','patterned-cohort','raman_mode_wavenumber',Q(301,'cm^-1',AN,basis='Ge LO phonon, patterned portion only'),'Micro-Raman spectroscopy',AN,'No spectrum, laser wavelength, power, temperature or measurement-region split supplied.'),measurement('nir-ge-surface','patterned-cohort','surface_state_absorption_wavenumber',Q(5890,'cm^-1',AN,basis='Author-assigned characteristic Ge surface-state absorption; not a bandgap'),'Near-IR absorption spectroscopy',AN,'No spectrum or detailed acquisition conditions supplied; template-class assignment unresolved.')]
r['quality']['missing_fields'].append('AFM tip dimensions/force/scan settings, TEM thinning procedure, Raman settings and near-IR setup unreported.');records.append(r)
r=base('heath-1996-ge-unpatterned-growth-context','Unpatterned silicon growth trials','observation')
r['method']='Unpatterned germanium chemical vapor deposition trials'
r['intended_target']['composition']=F('Ge islands on unpatterned Si(100)',PILOT)
r['intended_target']['morphology']=F('Island distributions used to select later growth conditions',PILOT)
r['intended_target']['phase']=F(None,PILOT,note='No atomic target structure or pilot-specific phase characterization supplied.')
r['intended_target']['size']=Q(unit='nm',e=PILOT)
r['quality']['review_scope']='Private contextual observation of unpatterned pilot trials from the supplied main. Full run matrix, conditions and specimen links are unreported. No patterned-mask process, shared-wafer identity, exact-size label or complete recipe is inferred. SI not located or verified.'
r['quality']['missing_fields']=['Matching SI not located or verified.','Full pilot temperature/time matrix, run count and individual specimen identifiers are unreported.','Pilot gas composition, flow, deposition pressure, wafer preparation, ramp and cooling are not independently specified; patterned-wafer settings are not inherited.','Particle size definition and per-run size distributions are not supplied.','No pilot-specific atomic coordinates or raw quantitative data are supplied.']
r['quality']['conflicts']=[COMMON_CONFLICTS[2]]
r['lineage']['recipe_family']='heath1996-unpatterned-pilot-context';r['products']=[product('pilot-cohort','Ge on unpatterned Si(100)',PILOT,link='unresolved',notes=['A series of times/temperatures was used to select the patterned-wafer conditions; the full experimental matrix and sample identities are absent. Gas flow/pressure are not inherited from the patterned recipe.'])];r['products'][0]['source_sample_label']='Unpatterned pilot-growth cohort'
r['measurements']=[measurement('uniform-temperature','pilot-cohort','reported_uniform_island_growth_temperature',Q(unit='degC',e=PILOT,minimum=560,maximum=600,basis='Reported most uniform distribution window, not enumerated independent runs'),'Pilot CVD and cross-sectional TEM',PILOT,'Full matrix, per-run conditions and statistical definition of uniformity are not given.'),measurement('incubation','pilot-cohort','reported_incubation_time',Q(5,'min',PILOT,qualifier='just_under',raw_text='just under5min',basis='Near600degC, before any island growth; source threshold, not exact duration'),'Pilot CVD and TEM',PILOT),measurement('late-exposure','pilot-cohort','reported_late_exposure_interval',Q(unit='min',e=PILOT,minimum=8,maximum=9,raw_text='8 or9min',basis='Reported late-exposure context; not a continuous sweep'),'Pilot CVD and TEM',PILOT),measurement('late-size','pilot-cohort','reported_late_island_size',Q(.1,'um',PILOT,approximate=True,basis='Source calls particles large; radius/diameter definition not explicitly specified'),'Cross-sectional TEM',PILOT,'After8or9min exposure; do not turn this into a measured diameter at one exact time.'),measurement('late-coverage','pilot-cohort','substrate_coverage',Q(unit='%',e=PILOT,minimum=70,maximum=90,basis='Approximate late-growth surface coverage range; not synthesis yield'),'Cross-sectional TEM',PILOT,'Unpatterned surface after8or9min; not the5min patterned-wafer endpoint.')]
records.append(r)
errors=[]
for r in records:
    errors+=validate_record(r)
    assert not any(x['eligible'] for x in eligibility(r).values())
    (OUT/(r['record_id']+'.json')).write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert len(set(build_groups(records).values()))==1
report={'status':'passed' if not errors else 'failed','scope':'Schema/graph, single-source split grouping and disabled training; independent scientific audit pending','records':[{ 'record_id':r['record_id'],'type':r['record_type'],'measurement_count':len(r['measurements']),'sha256':hashlib.sha256((OUT/(r['record_id']+'.json')).read_bytes()).hexdigest()} for r in records],'errors':errors,'published':False}
(B/'records-validation.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':report['status'],'records':len(records),'measurements':sum(len(r['measurements']) for r in records),'errors':errors}))
if errors:raise SystemExit(1)
