"""Private independent audit of the six supplied main pages; no Site writes."""
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
manifest = json.loads((HERE / 'source-manifest.json').read_text(encoding='utf-8'))
def loc(page, section):
    return {'source_id': 'heath1996-main', 'pdf_page': page, 'printed_page': str(3143 + page), 'locator': section}
def item(id, text, page, section, **extra):
    return {'id': id, 'text': text, 'evidence': [loc(page, section)], **extra}

protocol = [
 item('substrate', 'Clean Si wafers oriented <100>, then thermally oxidize to approximately 20 nm SiO2. Cleaning reagents, oxidation atmosphere, temperature and duration are unreported.', 1, 'Process Methodology', parameters={'substrate_orientation':'<100>','oxide_thickness':{'value':20,'unit':'nm','approximate':True}}, role='substrate_preparation'),
 item('resist', 'Coat with 70 nm PMMA and bake at 80 °C for 1 h. The PMMA formulation, solvent, molecular weight, coating method and speed are not supplied.', 1, 'Process Methodology', parameters={'PMMA_thickness':{'value':70,'unit':'nm'},'bake_temperature':{'value':80,'unit':'degC'},'bake_duration':{'value':1,'unit':'h'}}, role='mask_preparation'),
 item('lithography', 'Pattern point-exposure arrays with an IBM Vector Scan electron-beam system at 25 keV. Pitches were 200 or 400 nm; array areas ranged from 1 mm² to 1 cm². Exposure dose of 50–75 µC/cm² was controlled by beam dwell time; actual dwell times are absent. No exact dose-to-size or pitch-to-well-size assignment is given.', 1, 'Process Methodology', parameters={'beam_energy':{'value':25,'unit':'keV'},'pitch_options':{'values':[200,400],'unit':'nm'},'array_area':{'minimum':1,'minimum_unit':'mm^2','maximum':1,'maximum_unit':'cm^2'},'dose_range':{'minimum':50,'maximum':75,'unit':'uC/cm^2'}}, role='lithography'),
 item('development', 'Develop in isopropyl alcohol:methyl isobutyl ketone (3:1), giving approximate PMMA hole diameters of 60 and 100 nm. The ratio basis and developer duration/temperature are not stated. Figure 1 caption instead summarizes photoresist wells as approximately 60–150 nm.', 1, 'Process Methodology; contrast p2 Figure 1 caption', parameters={'IPA_to_MIBK_ratio':'3:1','ratio_basis':'not_reported','PMMA_hole_diameter_options':{'values':[60,100],'unit':'nm','approximate':True}}, role='development'),
 item('oxide_etch', 'Transfer the mask through the oxide by CF4/CHF3 reactive-ion etching. Partial loss of anisotropy enlarged openings to 100 and 150 nm. RIE lag slowed etching in the smaller features; no endpoint detection was used. Gas ratio, flow, pressure, RF power, bias and duration are not supplied.', 1, 'Process Methodology', parameters={'final_well_diameters':{'values':[100,150],'unit':'nm'},'RIE_gases':['CF4','CHF3'],'endpoint_detection':False}, role='reactive_ion_etching'),
 item('resist_strip', 'Remove PMMA by an acetone rinse. No amount, number of rinses, temperature or duration is given.', 2, 'Process Methodology continuation', parameters={'reagent':'acetone'}, role='mask_removal'),
 item('HF_clean', 'Both well-size arrays were on the same substrate. Briefly dip the wafer in 10% HF to remove native oxide from exposed silicon, then introduce it into the UHV/CVD load lock. Percentage basis, exact duration, rinse/drying procedure and transfer delay are not reported.', 2, 'Process Methodology continuation', parameters={'HF_concentration':{'value':10,'unit':'%','basis':'not_reported'},'duration':'briefly'}, role='native_oxide_removal'),
 item('UHV_CVD', 'Use a chamber with base pressure below 5×10^-6 Torr; expose the patterned wafer to a 10% GeH4-in-He mixture flowing at 90 sccm, at a deposition pressure of 1–2 mTorr and growth temperature of 600 °C for 5.0 min. Mixture percentage basis, gas purity, temperature sensor/heater configuration, stabilization/ramp, exhaust and cooling sequence are not supplied. The 90 sccm is mixture flow, not pure-GeH4 flow.', 2, 'Process Methodology continuation, left column to right-column top', parameters={'base_pressure':{'value':5e-6,'unit':'Torr','qualifier':'less_than'},'gas_mixture':{'solute':'GeH4','carrier':'He','concentration':10,'unit':'%','basis':'not_reported'},'mixture_flow':{'value':90,'unit':'sccm'},'deposition_pressure':{'minimum':1,'maximum':2,'unit':'mTorr'},'growth_temperature':{'value':600,'unit':'degC'},'exposure_duration':{'value':5.0,'unit':'min'}}, role='selective_heteroepitaxial_CVD'),
 item('dicing', 'Dice the wafer into several pieces after CVD for analysis. The number of pieces, particular measurement assignments and cutting/cleaning details are not specified.', 2, 'Process Methodology continuation', role='analysis_specimen_preparation')
]
variants = [
 item('wells_150nm', 'Template variant: nominal 150 nm diameter wells, approximately 30 nm deep by AFM, including about 10 nm over-etch beyond the initial oxide. Majority of Ge islands occurred near the perimeter, attributed to radial defects from over-etching. The reported population was 2–4 Ge islands per well. This is one template population on the shared patterned wafer, not an independent recipe run.', 1, 'Abstract; Process Methodology; p3 150 nm Wells and Figure 3', parameters={'well_diameter':{'value':150,'unit':'nm'},'well_depth':{'value':30,'unit':'nm','approximate':True,'technique':'AFM'},'overetch_depth':{'value':10,'unit':'nm','approximate':True},'islands_per_well':{'minimum':2,'maximum':4}}, direct_figure_links=['figure_3','figure_4','figure_5'], ambiguous_figure_links=['figure_2']),
 item('wells_100nm', 'Template variant: nominal 100 nm diameter wells, approximately 17 nm deep by AFM. Authors infer that RIE stopped just above Si and the final HF treatment exposed the base while removing some oxide; no perimeter ring of defects is inferred. Three of four AFM-imaged wells contained one approximately central island and the fourth appeared empty. Insufficient TEM preparation prevented comparable plan-view TEM analysis of this population.', 2, 'Process Methodology continuation; p5–6 100 nm Wells', parameters={'well_diameter':{'value':100,'unit':'nm'},'well_depth':{'value':17,'unit':'nm','approximate':True,'technique':'AFM'},'imaged_well_count':4,'one_island_well_count':3,'apparently_empty_well_count':1}, direct_figure_links=['figure_6'], ambiguous_figure_links=['figure_2'])
]
control = item('unpatterned_optimization', 'Separate planar, unpatterned Si(100) films were grown over a time/temperature series and studied with cross-sectional TEM to select the patterned-wafer conditions. 560–600 °C gave the most uniform island distributions. Near 600 °C, an incubation period just under 5 min preceded island growth. After 8 or 9 min exposure, particles were approximately 0.1 µm and coverage 70–90%. Larger islands showed narrower size distributions with longer growth. Full matrix, growth gas conditions for each trial, repetitions and individual source images are not supplied; do not instantiate discrete complete recipes or transfer these outcomes to the 5-min patterned samples.', 2, 'Results and Discussion; p3 kinetic discussion', parameters={'uniformity_temperature_range':{'minimum':560,'maximum':600,'unit':'degC'},'incubation':{'value':5,'unit':'min','qualifier':'just_under','temperature_context':'near 600 degC'},'longer_exposure_times':{'values':[8,9],'unit':'min'},'longer_exposure_particle_size':{'value':0.1,'unit':'um','approximate':True},'longer_exposure_coverage':{'minimum':70,'maximum':90,'unit':'%'}}, claim_type='reported_optimization_context', recipe_link='incomplete_series')
characterization = [
 item('raman', 'Micro-Raman spectroscopy detected the Ge LO mode at 301 cm^-1 only on the patterned part of the substrate. No plotted Raman spectrum, excitation wavelength, power, temperature or well-size-specific measurement assignment is supplied.', 2, 'Analysis of the Ge Quantum Dots', claim_type='reported_measurement', sample_scope='patterned-wafer ensemble; well-size population unresolved', quantity={'value':301,'unit':'cm^-1','property':'LO_phonon_wavenumber'}),
 item('TEM_instrument', 'Plan-view TEM used a JEOL 4000 at 400 kV. Moiré fringes support crystalline Ge islands epitaxially aligned with Si; larger particles show fringe discontinuities interpreted as defects/misfit dislocations. Figure 3 explicitly concerns 150 nm wells. This does not provide an XRD pattern, acquired SAED pattern, refined lattice parameter or atomic coordinates.', 2, 'Analysis of the Ge Quantum Dots; p3 150 nm Wells/Figure 3', claim_type='reported_measurement_and_author_interpretation', sample_scope='plan-view TEM; explicit Figure 3 join to 150 nm wells', quantity={'value':400,'unit':'kV','property':'TEM_accelerating_voltage'}),
 item('near_IR', 'Near-IR absorption identified the characteristic Ge surface-state absorption at 5890 cm^-1. It is not reported as a bandgap or photoluminescence peak. No spectrum or optical acquisition details are provided.', 2, 'Analysis of the Ge Quantum Dots', claim_type='reported_measurement', sample_scope='patterned-wafer characterization; well size unresolved', quantity={'value':5890,'unit':'cm^-1','property':'surface_state_absorption_wavenumber'}),
 item('AFM_instrument', 'AFM used a Topometrix TMX 2010 MultiView in contact mode with a high-aspect-ratio supertip: a carbon whisker on a standard silicon nitride tip. Probe geometry, force/setpoint and scan speed are missing. Tip convolution biases the apparent in-well particle toward larger width and smaller height.', 2, 'Analysis of the Ge Quantum Dots; p5 100 nm Wells', claim_type='reported_measurement_method', sample_scope='AFM arrays and individual wells'),
 item('TEM_length_calibration', 'Relatively low-resolution TEM supplied particle sizes and nearest-neighbor separations for 150 nm wells, using well-to-well center spacings as the length standard. Interparticle distances were measured center-to-center. No resolution-error distribution or exact pitch assignment to the plotted data is given.', 2, 'Analysis of the Ge Quantum Dots; p3 150 nm Wells', claim_type='reported_measurement_method', sample_scope='150 nm wells'),
 item('150nm_neighbor_statistics', 'Figure 4 uses 50 separate wells. Only three measured first-to-second-island separations were below 100 nm. Geometry and minimum island sizes restrict possible center separations to about 15–135 nm, with maxima nearer 125 nm for most wells. These are geometric limits, not the measured minimum/maximum of a raw dataset. The plotted dependence on r2/r1 shows no correlation; error-bar definitions and individual 50-well data are not given.', 4, 'Figure 4 and Results continuation from p3', claim_type='reported_statistics_and_author_inference', sample_scope='50 wells of nominal 150 nm diameter', quantities={'well_count':50,'distances_below_100nm':3,'possible_separation_minimum_nm':15,'possible_separation_maximum_nm':135,'typical_geometric_maximum_nm':125}),
 item('Fig6_AFM_dimensions', 'For the depicted 100 nm well, Figure 6 gives a measured dot height of 1.4 nm as a lower bound on radius and width of 33 nm as an upper bound on diameter. Those dimensions are apparent AFM values, not exact dimensions. The authors invoke approximately hemispherical, faceted similar Ge islands seen in side-view TEM to motivate converting twice-height to a lower diameter bound; that morphology evidence is from similar islands, not direct shape reconstruction of this well.', 5, 'Figure 6 caption and 100 nm Wells', claim_type='reported_measurement_with_model_dependent_bounds', sample_scope='Figure 6 single 100 nm well', quantities={'apparent_height_nm':1.4,'apparent_width_nm':33}, optional_derived_bound={'minimum_diameter_nm':2.8,'status':'derived','basis':'2 × caption height, using the author morphology assumption; body rounds lower bound to 3.0 nm'}),
 item('100nm_body_diameter_bounds', 'The body gives diameter bounds of 3.0–34 nm for one detailed AFM measurement and 3.0–35 nm for a second well. These are resolution/convolution bounds for individual dots, not population size distributions, and should coexist with caption values.', 5, '100 nm Wells, final paragraph continuing p6', claim_type='author_derived_bounds', sample_scope='two AFM-imaged 100 nm wells, one apparently Figure 6 and a second explicitly separate', quantities=[{'minimum':3.0,'maximum':34,'unit':'nm','specimen':'first detailed well; contextual Figure 6 join'},{'minimum':3.0,'maximum':35,'unit':'nm','specimen':'second detailed well'}]),
 item('four_well_AFM_sample', 'Three out of four scanned 100 nm wells displayed an approximately central single island; one appeared empty. The three-of-four observation is a small imaging sample, not a measured 75% process yield. No broadening of well-wall edges was seen in these four images; perimeter islands in 150 nm wells flatten the apparent AFM wall slopes.', 5, '100 nm Wells', claim_type='reported_observation', sample_scope='four AFM-imaged 100 nm wells, qualitative comparison with 150 nm wells'),
 item('paper_size_summaries', 'Introduction first summarizes single-crystal arrays as approximately 6–30 nm, then states selective growth to 6–25 nm. The conclusion summarizes 100 nm-well islands as 3–30 nm. These broad statements do not override sample-specific AFM bounds or the ambiguous 40 nm maximum used in the kinetic argument.', 1, 'Introduction; contrast p5 Figure 5 discussion and p6 Summary', claim_type='reported_study_summary_with_unresolved_scope', sample_scope='multiple summary scopes; not a single measured distribution')
]
models = [
 item('growthlaw', 'Authors interpret post-nucleation growth with R^n − R0^n = k(t − t0) (Equation 1), considering n=2,3,4 from prior literature and selecting n=3 as most plausible for this experiment. R0 denotes a critical growth size, not a measured seed diameter. No fitted k, n uncertainty or physical elapsed time for individual islands is supplied.', 3, 'Equation 1 and kinetic discussion', claim_type='author_model_with_citation_context', formula='R^n - R0^n = k(t - t0)', sample_scope='interpretive model, principally 150 nm wells'),
 item('growth_assumptions', 'Two explicit assumptions underlie later modeling: growth kinetics do not change with island size; GeH4 incident on the oxide does not contribute to growth within wells. Authors argue 600 °C can overcome strain-related defect barriers, but neither assumption is directly measured here.', 3, 'Two modeling assumptions', claim_type='author_assumptions', sample_scope='patterned arrays'),
 item('selectivity', 'Cited work places Ge selectivity for Si over SiO2 below 0.1 Torr; authors say their GeH4 partial pressure is a factor of 1000 below that limit. The directly reported total growth pressure is 1–2 mTorr with a 10% mixture. A nominal arithmetic estimate gives 0.1–0.2 mTorr and a factor of 500–1000 only if the gas fraction is interpreted as a pressure fraction; do not silently turn the factor-of-1000 prose into an independently measured pressure.', 3, 'Second modeling assumption and reference 15', claim_type='author_rationale_and_citation_context', sample_scope='growth selectivity, not another recipe'),
 item('nucleation_order', 'Within each well, authors use relative island size to infer relative nucleation order: larger islands are taken to have nucleated earlier. First/second labels therefore derive from a growth model; the nucleation events were not imaged in real time.', 3, 'Kinetic discussion preceding two assumptions', claim_type='author_model_derived_identity', sample_scope='150 nm wells'),
 item('screening_equations', 'For an unconfined 2-D surface, the authors discuss ξ=(D/k)^(1/2) and ∂C/∂t − D∇²C = S − kC (Equation 2), with steady state, C(a)=0 and C(large r)=Cb. Equation 3 is C(r)=Cb[1−K0(r/ξ)/K0(a/ξ)], where K0 is the modified Bessel function of the second kind. D, k, flux/sticking product S, a and Cb are symbolic; no numerical diffusion coefficient or rate constant is measured here. Equation 2 cites a private communication (reference 16).', 4, 'Equations 2–3 and adjacent discussion', claim_type='author_model_and_private_communication_context', sample_scope='unconfined-surface comparison model'),
 item('reflective_boundaries', 'Typical unconfined diffusion fields are discussed as extending 2–4 island radii from the perimeter. The effective field in 150 nm wells appears to span the well, independent of island size; the authors attribute amplification to reflection at the oxide boundary rather than a measured change in intrinsic diffusivity. The statement that adatoms can diffuse several microns at 600 °C is cited to reference 17. The paper calls the upper effective-field radius limit the well diameter (150 nm); preserve that specific author meaning and do not convert it to a measured 75 nm radial distance.', 4, 'Figure 4 interpretation and diffusion discussion', claim_type='author_interpretation_with_cited_comparison', sample_scope='150 nm wells versus unconfined reference'),
 item('incubation_alternatives', 'The approximately 5-min incubation may reflect a critical adatom coverage, slow GeH4 removal of residual oxide at the well bases, or both. These are alternative explanations, not an instructed etch step or established mechanism.', 4, 'Nucleation discussion', claim_type='author_hypotheses', sample_scope='onset of CVD growth'),
 item('nucleation_models', 'Authors distinguish defect sites that completely remove the barrier (pure heterogeneous nucleation; critical nucleus of one atom; no further incubation once active) from sites that reduce the barrier but still require fluctuations and buildup (their assisted homogeneous nucleation). The initial event-rate shapes are described as convex-up and concave-up, respectively. These are definitions/model expectations, not measured critical-nucleus sizes.', 4, 'Nucleation mechanisms', claim_type='author_model', sample_scope='interpretive nucleation alternatives'),
 item('Fig5_reconstruction', 'Figure 5 reconstructs the first nucleation-event distribution from largest-island sizes in individual 150 nm wells, assuming dr/dt=k r^-2 (n=3). The plotted x coordinate is RL^3−Ri^3, labeled time without physical time units; RL is an arbitrary hypothetical island a few nanometers larger than the largest observed island, described as 40 nm. Radii/sizes were measured with approximately 5 nm resolution. A nonlinear curve is fitted only to illustrate the rising edge; functional form and fit parameters are absent. This is not time-resolved growth data. Authors infer assisted homogeneous nucleation and Stranski–Krastanov rather than Volmer–Weber growth.', 5, 'Figure 5 caption, plot axes and Results continuation', claim_type='author_model_derived_statistical_plot', sample_scope='150 nm wells; number of Figure 5 wells not explicitly stated', quantities={'size_resolution_nm':5,'largest_observed_size_nm':40,'largest_size_definition':'radius discussion calls it island size; unresolved radius/diameter meaning'}, x_axis='RL^3 - Ri^3 (time)', y_axis='number of islands'),
 item('100nm_interpretation', 'Authors suggest the lower defect density in 100 nm wells could change kinetics and help explain mostly single central islands, but explicitly state that AFM alone does not establish detailed kinetics.', 6, '100 nm Wells continuation', claim_type='author_hypothesis_with_limit', sample_scope='100 nm wells'),
 item('device_outlook', 'Precisely positioned, electrically contacted, size-confined dots and ambient-operation Coulomb-blockade devices are the motivation and outlook. No electrical-contact resistance, conductance, Coulomb-blockade trace or room-temperature quantum-device performance is measured in this paper.', 1, 'Introduction; p6 Summary and Conclusions', claim_type='author_motivation_and_outlook', sample_scope='prospective device application')
]
figures = [
 item('figure_1', 'Three-stage fabrication schematic: resist lithography, oxide etch to Si, selective Ge nucleation/growth. It is an explanatory schematic, not an apparatus measurement. Preserve printed Si <100>, 20 nm oxide and PMMA labels.', 2, 'Figure 1', figure_number=1, evidence_kind='author_schematic', sample_scope='shared fabrication framework', links=['wells_100nm','wells_150nm'], caveat='Caption photoresist hole range ~60–150 nm differs from main-method 60 and 100 nm.'),
 item('figure_2', 'AFM overview of a patterned well array with a 600 nm scale bar. Body calls it a 25 µm² region of 100 nm wells; caption says 150 nm wells. Preserve both labels and keep the well-size join unresolved.', 2, 'Figure 2; Process Methodology continuation', figure_number=2, evidence_kind='experimental_AFM', sample_scope='template-array overview; 100 versus 150 nm identity conflict', links=[], caveat='Do not infer pre/post-growth state more precisely than the template-overview context allows.'),
 item('figure_3', 'Dark-field plan-view TEM of 150 nm wells. Contrast emphasizes Ge versus Si; oxide boundaries are weak. Most islands appear near the perimeter, with Moiré fringes supporting epitaxial registry. No explicit scale bar is visible in the supplied figure.', 3, 'Figure 3', figure_number=3, evidence_kind='experimental_TEM', sample_scope='150 nm well Ge/Si islands', links=['wells_150nm']),
 item('figure_4', 'Center-to-center first/second island separation versus r2/r1, built from 50 nominal 150 nm wells. Axes are distance n1→n2 (nm) and size ratio; plotted distance axis spans 15–135 nm. Error bars are shown but their statistical definition is not supplied. Original figure retained; no raw points digitized.', 4, 'Figure 4', figure_number=4, evidence_kind='experimental_statistics_with_model_based_nucleation_order', sample_scope='50 nominal 150 nm wells', links=['wells_150nm']),
 item('figure_5', 'Number of first-nucleated islands versus RL^3−Ri^3, labeled time. Points originate in measured particle sizes; the time relation and zero are assumed, and the rising-edge curve is model illustration/fitting. This is not a direct time trace or additional growth recipe.', 5, 'Figure 5', figure_number=5, evidence_kind='author_model_derived_statistics', sample_scope='largest islands in 150 nm wells; exact count not supplied', links=['wells_150nm']),
 item('figure_6', 'AFM topography of one approximately 100 nm well plus height-versus-distance cross section and scan inset. A single central island is shown; height 1.4 nm and width 33 nm are apparent dimensions/bounds, not exact crystal dimensions. Include both the topographic and line-profile panels.', 5, 'Figure 6', figure_number=6, evidence_kind='experimental_AFM', sample_scope='one 100 nm well with a central island', links=['wells_100nm'])
]
conflicts = [
 item('dates', 'The printed source gives Received July 6, 1995 and In Final Form November 6, 1994, so the final-form date precedes receipt. This inconsistency is visually present in the PDF and must not be silently corrected. The article is published as 1996; advance abstract January 15, 1996.', 1, 'Title block and author footnote', severity='metadata_conflict'),
 item('figure2_identity', '100 nm in body versus 150 nm in Figure 2 caption; this prevents an unqualified image-to-template-variant join.', 2, 'Process Methodology continuation and Figure 2 caption', severity='sample_join_conflict'),
 item('photoresist_diameter', 'Main process reports approximate 60 and 100 nm PMMA openings; Figure 1 caption says approximately 60–150 nm photoresist wells. Final etched oxide openings are separately 100 and 150 nm.', 1, 'Process Methodology; p2 Figure 1 caption', severity='stage_specific_dimension_conflict'),
 item('AFM_bound_values', 'Caption: 1.4 nm height / 33 nm width. Body first well: diameter 3.0–34 nm; second well: 3.0–35 nm. Conclusion: 3–30 nm. Retain each with specimen/summary scope; do not collapse to one exact size or population distribution.', 5, 'Figure 6 and 100 nm Wells; p6 Summary', severity='dimension_bound_and_summary_conflict'),
 item('intro_size_ranges', 'Introduction summarizes approximately 6–30 nm arrays and later 6–25 nm growth; relationship to the later AFM bounds and 40 nm kinetic maximum is unresolved.', 1, 'Introduction; p5 Figure 5 discussion', severity='summary_scope_ambiguity'),
 item('40nm_definition', 'The Figure 5 discussion refers to island radii but calls the largest observed island 40 nm without an explicit radius/diameter label. Keep the number as source-reported size with unresolved dimensional definition. RL is stated to be a few nm larger, not equal to 40 nm.', 5, 'Figure 5 discussion', severity='dimensional_definition_ambiguity'),
 item('partial_pressure_factor', 'A 10% mixture at 1–2 mTorr implies a nominal 0.1–0.2 mTorr partial-pressure range only under a stated ideal fraction assumption. Author statement factor 1000 below 0.1 Torr corresponds to its low-pressure end. Preserve the stated range and narrative separately.', 3, 'Selectivity assumption; p2 Methodology', severity='source_precision_and_derived_value_scope'),
 item('growth_constant_notation', 'Equation 1 with n=3 and Figure 5 dr/dt=k r^-2 use k symbolically; their integrated constants differ by a factor of three under the same k definition. No numerical k is supplied. Do not combine these forms to calculate absolute time or a fitted rate constant.', 3, 'Equation 1; p5 Figure 5 caption', severity='model_notation_caution')
]
references = [
 (1,'Yang and Herron, J. Phys. Chem. 1991,95,525','Review of wet-chemical quantum structures; citation-only background.'),
 (2,'Hayashi et al. 1987; Jasinski and Legoues 1991; Littau et al. J. Phys. Chem. 1993,97,1224','Gas-phase nanocrystal background; no cited full protocol is imported into this Ge wafer process.'),
 (3,'Murray, Norris and Bawendi, JACS 1993,115,8706','Background size control ±0.2 nm and colloidal organization; not current Ge size precision.'),
 (4,'Ohara, Leff, Heath and Gelbart, Phys. Rev. Lett., in press','Langmuir–Blodgett dot-array background; full bibliographic identity and method unverified here.'),
 (5,'Leonard et al., J. Vac. Sci. Technol. B 1994,12,1063','30 nm InAs islands on GaAs background; not a Ge product or process.'),
 (6,'Bauer, Z. Kristallogr. 1958,110,372','F-vdM, V-W and S-K growth-mode framework.'),
 (7,'Mercer and Chou, Phys. Rev. B 1993,48,5374','Calculated Ge(100) surface free energy about 30% below Si(100); not measured here. Related 4% Ge/Si mismatch is background.'),
 (8,'Cunnigham, Chu and Akbar, J. Appl. Phys. 1991,59,3574, as printed','UHV/CVD Ge/Si growth-mode transition near 350 °C; citation-only, not current process temperature.'),
 (9,'Ngo and Williams, J. Appl. Phys. 1995,66,1906, as printed','Growth exponent n=2,3,4 framework; bibliographic year/volume not externally checked.'),
 (10,'Zinke-Allmang, Feldman and Nakahara, Appl. Phys. Lett. 1991,51,975, as printed','Prior experimental n=3 behavior; not a fitted current-sample exponent.'),
 (11,'Steyer, Guenoun and Beysens, Phys. Rev. A 1991,44,8271','Diffusion field/size scaling background.'),
 (12,'Reiss, J. Chem. Phys. 1951,19,482','Size-distribution narrowing after nucleation saturation.'),
 (13,'Leonard et al., Appl. Phys. Lett. 1993,63,3203','Strain/defect activation-barrier caveat.'),
 (14,'Grider et al., Mater. Res. Soc. Symp. Proc. 1990,158,147','Argument about high-temperature kinetic growth; not current activation-energy measurement.'),
 (15,'Ishii, Takahashi and Murota, Appl. Phys. Lett. 1985,47,863','Selective Ge deposition on Si versus SiO2 below 0.1 Torr.'),
 (16,'Koch, private communication','Modified diffusion-equation context; no accessible paper identity or independently reviewed derivation.'),
 (17,'Krishnamurthy, Drucker and Venables, J. Appl. Phys. 1991,69,6561','Ge adatom diffusion over several microns at 600 °C; citation-only reference system.')
]
gaps = [
 'Only the six supplied main pages were inspected. Matching supporting information was not searched for or verified by this bounded audit; no assertion that SI does not exist.',
 'No complete unpatterned optimization matrix or distinct wafer-run count is reported. Shared 100/150 nm template regions are not independent experimental replicates.',
 'Substrate doping, cleaning, oxidation conditions, resist formulation and coating parameters are absent.',
 'Exposure dwell times, development duration/basis, and variant-specific pitch/dose mappings are absent.',
 'RIE gas proportions, gas flows, power/bias, chamber pressure, duration and endpoint criterion are absent; no endpoint detection was used.',
 'HF percentage basis, treatment duration, rinse/dry details and air/transfer delay are absent.',
 'GeH4/He percentage basis and purity, actual partial pressure, temperature measurement, thermal history, and cooling/storage details are absent.',
 'TEM specimen-preparation details and dicing-to-measurement specimen identities are incomplete; the 100 nm regions could not be adequately prepared for plan-view TEM.',
 'AFM exact probe shape and acquisition settings are absent, so particle dimensions remain bounds; 4 wells cannot establish full-array yield.',
 'No raw numerical point tables, Figure 4 error-bar definition, Figure 5 fit function/parameters, physical time axis, or exact Figure 5 well count are supplied.',
 'No shown Raman/near-IR spectra, excitation/optical geometry details, electrical device data, XRD, SAED, PL, unit-cell coordinates or CIF are supplied in the inspected main article.',
 'Cited references were inventoried only from this article; no external reference text was retrieved or used to fill missing historical conditions.'
]
ocr = [
 'The source visually prints the inconsistent 1995 received / 1994 final dates; this is not an extraction error.',
 'Degree-Celsius glyphs sometimes render/extract as a damaged composite such as )C or )C-like text. Temperature meanings were confirmed visually.',
 'Extracted ) in equations is equality =; ú in screening expressions is Greek ξ; dn1fn2 is d(n1→n2). Figure 5 x-axis is RL^3−Ri^3, not directly measured minutes.',
 'Small caps/ligatures generate AdVance, selectiVely, No Vember, Moire´, +/- and artifacts; normalize only typography, not scientific meaning.',
 'Superscripts matter: doses µC/cm², patterned area 25 µm², base pressure 10^-6 Torr, spectroscopic cm^-1, Equation 1 powers n and Figure 5 cube. The 25 keV electron-beam exposure is distinct from 400 kV TEM.',
 'The Figure 2 scale bar reads 600 nm; it does not resolve its contradictory 100/150 nm identity captions.',
 'Figure 5 island-radius/size wording and 40 nm definition remain ambiguous even after visual reading; do not repair through OCR normalization.'
]
report = {
 'audit_version':'1.0','audited_at_utc':datetime.now(timezone.utc).isoformat(),
 'status':'independent_supplied_main_text_and_visual_review_complete',
 'source':{'source_id':'heath1996-main','basename':Path(manifest['source']).name,'sha256':manifest['sha256'],'title':'Spatially Confined Chemistry: Fabrication of Ge Quantum Dot Arrays','authors':['J. R. Heath','R. S. Williams','J. J. Shiang','S. J. Wind','J. Chu','C. D’Emic','W. Chen','C. L. Stanis','J. J. Bucchignano'],'doi':'10.1021/jp951903v','journal':'Journal of Physical Chemistry','year':1996,'volume':100,'issue':8,'pages':'3144–3149','page_count':6},
 'review_scope':'supplied_main_only_si_unverified',
 'scope_limit':'Independent source reading and compact extraction/audit. Not a canonical-record audit, figure crop audit, source-to-view audit, training eligibility review or publication approval.',
 'page_review':[{'pdf_page':i,'printed_page':str(3143+i),'text_file':f'plain-page-{i}.txt','text_sha256':hashlib.sha256((HERE/f'plain-page-{i}.txt').read_bytes()).hexdigest(),'text_reviewed':True,'image_file':f'main-{i}.png','image_sha256':hashlib.sha256((HERE/f'main-{i}.png').read_bytes()).hexdigest(),'visual_reviewed':True} for i in range(1,7)],
 'relevance':{'useful_synthesis':True,'useful_structure':True,'useful_property':True,'system':'Ge islands/quantum-dot arrays on Si(100) patterned through SiO2','method':'selective UHV/CVD with electron-beam lithography and reactive-ion-etched nanosurface templates','not_colloidal':True,'properties_scope':'Raman and near-IR peak positions plus model-derived kinetic interpretation; no measured electrical quantum-device performance'},
 'chemical_inventory':[{'name':a,'formula_or_repeat_unit':b,'role':c,'reported_amount':d} for a,b,c,d in [('silicon','Si','single-crystal <100> substrate','wafer dimensions, count and doping not reported'),('silicon dioxide','SiO2','thermal oxide mask and confinement walls','approximately 20 nm layer'),('poly(methyl methacrylate)','(C5H8O2)n','electron-beam resist','70 nm coating; repeat-unit formula is chemical-identity normalization, not printed by paper'),('isopropyl alcohol','C3H8O','developer component','IPA:MIBK 3:1; basis and amount unreported'),('methyl isobutyl ketone','C6H12O','developer component','IPA:MIBK 3:1; basis and amount unreported'),('tetrafluoromethane','CF4','RIE process gas','unreported fraction/flow'),('trifluoromethane','CHF3','RIE process gas','unreported fraction/flow'),('acetone','C3H6O','resist-removal rinse','unreported'),('hydrofluoric acid','HF','native-oxide dip','10%; basis/solution balance unreported'),('germane','GeH4','Ge CVD precursor','10% in He; mixture flow 90 sccm'),('helium','He','CVD carrier','balance/composition not separately quantified'),('silicon nitride','Si3N4','standard AFM tip supporting carbon whisker','instrument component, not synthesis reagent; formula normalization'),('carbon','C','AFM supertip whisker','instrument component, not synthesis reagent')]],
 'shared_protocol':protocol,'template_variants':variants,'optimization_context':control,
 'characterization':characterization,'author_models_and_intuition':models,'figure_inventory':figures,
 'table_inventory':[],'conflicts_and_semantic_hazards':conflicts,
 'reference_contexts':[{'reference_number':n,'citation_as_printed_or_compact':c,'scope':s,'access':'citation_in_current_main_only','evidence':[loc(6,f'Reference {n}')]} for n,c,s in references],
 'missing_information':gaps,'OCR_and_typography_hazards':ocr,
 'new_parameter_concepts':['substrate crystallographic orientation','oxide/resist film thickness','electron-beam energy, area dose, beam dwell and pitch','template dimensions versus product dimensions','reactive-ion etching with lag, over-etch and endpoint status','native-oxide removal and transfer history','base pressure versus deposition pressure versus precursor partial pressure','gas-mixture flow versus pure precursor flow','common-wafer regions versus independent runs','AFM tip-convolution upper/lower geometric bounds','well occupancy sample size rather than process yield','model-inferred nucleation order and model-derived pseudo-time','substrate-supported epitaxial morphology versus free colloidal particles'],
 'handoff_priority':['Preserve dates, Figure 2 identity and stage-diameter conflicts.','Keep two template variants under shared wafer/CVD scope; do not create two independent runs.','Make all source-reported peak/geometry/model data visible with correct specimen and evidence type.','Retain original figures with full axes/captions; do not generate missing experimental Raman/IR traces.','Do not convert model assumptions, critical-nucleus hypotheses, 40 nm ambiguous size or application outlook into training targets.']
}
(HERE/'source-audit.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines=['# Independent source audit: Heath et al. (1996)','',report['scope_limit'],'',f"Source: {report['source']['title']} · DOI 10.1021/jp951903v · six main pages, all read and visually checked. SHA-256: `{manifest['sha256']}`.",'','Main-only scope: matching SI was not searched for or verified in this bounded audit. No Site changes, external papers or downloads.','', '## Critical issues','']
lines += ['- '+x['text'] for x in conflicts]
for title,items in [('Shared fabrication protocol',protocol),('Template variants',variants),('Characterization and specimen boundaries',characterization),('Author models and chemical interpretation',models),('Figures',figures)]:
    lines += ['', '## '+title,'']
    lines += ['- **'+x['id']+'** — '+x['text']+' [PDF p'+str(x['evidence'][0]['pdf_page'])+', '+x['evidence'][0]['locator']+']' for x in items]
lines += ['', '## Separate optimization series','',control['text'],'','## Missing details','']+['- '+x for x in gaps]
lines += ['', '## Citation-only context','']+['- **Reference '+str(n)+'** — '+c+'. '+s for n,c,s in references]
lines += ['', '## OCR and symbol checks','']+['- '+x for x in ocr]
lines += ['', '## Recommended disposition','','Two template-based fabrication variants are supportable from the shared procedure; the unpatterned optimization remains incomplete context. The 100 nm AFM, 150 nm TEM/statistics and study-wide spectroscopic checks need separate specimen scope. All six figures should be included; there are no tables. Canonical and reader integration need a subsequent independent join audit.']
(HERE/'source-audit.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'status':report['status'],'pages':6,'protocol_operations':len(protocol),'template_variants':len(variants),'characterization_items':len(characterization),'model_items':len(models),'figures':len(figures),'conflicts':len(conflicts),'citation_contexts':len(references),'source_audit_sha256':hashlib.sha256((HERE/'source-audit.json').read_bytes()).hexdigest()},indent=2))
