"""Sashchiuk et al. 2004: complete seven-page local main-paper extraction."""
from pathlib import Path
from copy import deepcopy
import sys,json,hashlib
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas';sys.path.insert(0,str(S/'scripts'));sys.dont_write_bytecode=True
from record_helpers import record,source,ev,fact,qty,material,operation,state,product,measurement
from dataset_lib import validate_record
SID='sashchiuk2004';PRE='sashchiuk-2004-'
SRC=source(SID,'10.1021/nl0345116','PbSe Nanocrystal Assemblies: Synthesis and Structural, Optical, and Electrical Characterization','A. Sashchiuk; L. Amirav; M. Bashouti; M. Krueger; U. Sivan; E. Lifshitz',2004,si='No matching SI is present in the supplied local bundle; SI existence/absence is not independently established. No SI used.')
SRC['main_status']='All seven main pages text-read and visually inspected, including Figures 1–5, unnumbered model equations and references 1–67. Independent audit pending.'
def E(p,s):return ev(SID,f'Main PDF p. {p}, printed p. {158+p}, {s}')
SYN=E(2,'Section 2 Experimental Section');RES=E(2,'Section 3')+E(3,'Section 3 continuation');MIC=E(2,'Microscopy methods');DEV=E(2,'Electrical-device preparation');ELEC=E(4,'Electrical measurements')+E(5,'Figure 5')
def Q(v=None,u='',e=SYN,**kw):return qty(v,u,deepcopy(e),**kw)
def F(v=None,e=SYN,**kw):return fact(v,deepcopy(e),**kw)
CHEM={
 'lead-chxbu':('Lead-cyclohexanebutirate, as printed (Pb-cHxBu); exact molecular identity unresolved',None,SYN),
 'selenium':('Selenium precursor; source prints Se, allotrope and stock speciation unreported','Se',SYN),
 'tbp':('Tri-n-butylphosphine (TBP)','C12H27P',SYN),
 'topo-reagent':('Aldrich TOPO reagent, 90% or 99% purity; minor components not quantified',None,SYN+E(5,'TOPO impurities')),
 'topo-component':('Trioctylphosphine oxide, named component of the reagent','C24H51OP',SYN),
 'argon':('Argon','Ar',SYN),'methanol':('Methanol','CH4O',SYN),'butanol':('Butanol; isomer unspecified','C4H10O',SYN),
 'pbse-individual':('Individual TOPO/TBP-capped PbSe nanocrystals','PbSe',RES),
 'pbse-spheres':('Spherical polycrystalline assemblies of PbSe nanocrystals','PbSe',E(3,'Figure 1')),
 'pbse-wires':('Ordered wire-like assemblies of PbSe nanocrystals','PbSe',E(3,'Figure 2')+E(4,'Figure 3')),
 'formvar-grid':('300-mesh copper TEM grid with amorphous Formvar and evaporated carbon film',None,MIC),
 'silicon-substrate':('p-doped silicon substrate; dopant identity and concentration unspecified','Si',DEV),
 'silica-layer':('Silicon oxide layer on silicon substrate','SiO2',DEV),
 'trimethylsilane':('Trimethylsilane, source-printed surface-treatment reagent','C3H10Si',DEV),
 'pmma':('Poly(methyl methacrylate) resist; molecular weight and formulation unspecified',None,DEV),
 'titanium':('Titanium contact layer','Ti',DEV),'gold':('Gold contact layer','Au',DEV)
}
def C(i,role,stage='synthesis',quantities=None,notes=None,e=None):
 n,f,d=CHEM[i];return material(i,n,f,role,stage,deepcopy(e or d),quantities=quantities,notes=notes or[])
def base(k,title,kind='observation',method='Source-scoped structural, optical or electrical observation'):
 r=record(PRE+k,'Sashchiuk et al. (2004) · '+title,'PbSe','Lead selenide nanocrystals and their assemblies',method,deepcopy(SRC),'Complete seven-page main article',kind)
 r['schema_version']='1.3.0';r['material'].update(elements=['Pb','Se'],components=['PbSe'],architecture='single_material')
 r['lineage'].update(source_group=SID,recipe_family='sashchiuk2004-pbse-assembly')
 r['quality'].update(review_status='imported_unreviewed',review_scope='All seven supplied main pages text-read and visually inspected; no SI or cited full text used. Independent audits and publication pending.',missing_fields=['Absolute precursor charges, injected stock amount, stock aging/speciation and quantitative Pb-cHxBu molecular identity are not established.','Several heating rates, withdrawal volumes, separation settings, purification solvent ratios and final storage conditions are unreported.','No measured atomic-coordinate file or raw electronic transport/spectral array is supplied.'],conflicts=[],requested_tasks=['precursor_selection','partial_protocol']if kind=='literature_protocol'else[],experimental_outcome='reported_product'if kind=='literature_protocol'else'not_established')
 r['context_links']=[{'label':'Complete source review','url':'../paper-review.html?id='+SID,'relation':'Original figures, methods, source conflicts, theory and references.'}];return r
def add(r,i,action,label,inputs,out,e,pars=None,stage='synthesis',desc='',env=None,kind='reaction_batch',depends=None,retain=False,parents=None):
 if out:r['material_states'].append(state(out,label+' output',inputs if parents is None else parents,kind))
 r['operations'].append(operation(i,action,label,deepcopy(e),inputs,[out]if out else[],depends=depends if depends is not None else([r['operations'][-1]['id']]if r['operations']else[]),parameters=pars or{},stage=stage,description=desc,environment=F(env,e),retained_fraction=out if retain else None))
def P(r,i,label,e,st=None,explicit=False,notes=None):
 p=product(i,'PbSe',deepcopy(e),link='explicit'if explicit else'general_context',state=st,notes=notes or[]);p['source_sample_label']=label;r['products'].append(p);return p
def M(r,i,s,pr,v,u,e,tech='Source-reported observation',conditions='',**kw):r['measurements'].append(measurement(i,s,pr,Q(v,u,e,**kw),tech,deepcopy(e),conditions))
def T(r,i,s,pr,v,e,tech='Source-reported observation',conditions='',**kw):r['measurements'].append(measurement(i,s,pr,F(v,e,**kw),tech,deepcopy(e),conditions))
def link(r,k,label,rel='Source-scoped related evidence; no unproven physical-batch join.'):
 r['context_links'].append({'label':label,'url':'../records/'+PRE+k+'.html','relation':rel})
records=[]

routes=[('individual-low','Individual nanocrystals at 118 °C',(0.25,0.6,50),15,'individual'),('sphere-intermediate','Spherical assemblies at intermediate precursor concentration',(0.5,1.2,50),None,'spheres'),('wire-intermediate','Wire assemblies after 90 min at intermediate concentration',(0.5,1.2,50),90,'wires'),('wire-high','Wire assemblies after 40 min at high concentration',(1,2.5,50),40,'wires')]
for k,title,ratio,time,morph in routes:
 r=base(k,title,'literature_protocol','Hot injection and temperature-controlled colloidal assembly')
 r['materials']=[C('lead-chxbu','metal_precursor',notes=['The printed spelling and abbreviation do not establish a unique structure, stoichiometry or CAS identity. No guessed salt formula.']),C('selenium','chalcogen_precursor',notes=['Source selenium identity is retained; no stock molecular structure or selenium allotrope is inferred.']),C('tbp','solvent'),C('topo-reagent','reaction_medium',quantities={'mass':Q(6,'g')}),C('topo-component','named_reagent_component',notes=['Molecular reference for TOPO only, not an independently dosed material or pure composition claim.']),C('argon','process_gas')]
 r['stocks']=[{'id':'feed-stock','name':'Se/Pb-cHxBu/TBP precursor stock','components':[{'material_id':i,'quantities':{'relative_mass':Q(v,'mass parts',basis='Se:Pb-cHxBu:TBP mass ratio; not grams or molar equivalents')}}for i,v in zip(['selenium','lead-chxbu','tbp'],ratio)],'concentrations':{'absolute_concentration':Q(u='mol/L',qualifier='Mass parts do not establish a stock molarity. Pb-cHxBu identity and total volume are unresolved.')},'preparation_operation_ids':['prepare-stock'],'scope':'Route stock ratio from Methods/body. Alternative conflicting figure-caption ratios are preserved separately, not silently substituted.','evidence':deepcopy(SYN)}]
 add(r,'prepare-stock','inert_stock_preparation','Dissolve selenium and Pb-cHxBu in TBP under inert glovebox conditions',['selenium','lead-chxbu','tbp'],'stock',SYN,{'temperature':Q(u='°C',qualifier='Room temperature, numeric value not reported.'),'selenium_mass_part':Q(ratio[0],'mass parts'),'lead_precursor_mass_part':Q(ratio[1],'mass parts'),'tbp_mass_part':Q(ratio[2],'mass parts')},stage='precursor_preparation',env='Inert glovebox atmosphere; gas identity not specified',desc='Precursors are STREM or Aldrich technical grade. Absolute masses, dissolution duration, selenium chemical speciation and storage are unreported.')
 add(r,'heat-topo','surfactant_heating','Heat 6.0 g TOPO in a three-neck flask under argon',['topo-reagent'],'hot-topo',SYN,{'temperature':Q(150,'°C'),'topo_mass':Q(6,'g')},depends=[],env='Argon flow',desc='Aldrich TOPO is given as 90% or 99% purity. Flow rate, flask capacity, degassing schedule and heating ramp are absent. The two purities are alternative reagent grades, not co-added masses.')
 add(r,'injection','rapid_precursor_injection','Rapidly inject the precursor stock; temperature drops to 118 °C',['stock','hot-topo'],'injected-mixture',SYN,{'post_injection_temperature':Q(118,'°C'),'stock_injection_volume':Q(u='mL'),'injection_duration':Q(u='s',qualifier='Rapid injection, no numerical duration.')},depends=['prepare-stock','heat-topo'],desc='The cooling to 118 °C is the immediate injection response, not a separately quantified cooling-bath program. The source does not repeat a selected-operation gas setting.')
 if k=='individual-low':
  add(r,'grow','isothermal_growth','Maintain the reaction at 118 °C for 15 min',['injected-mixture'],'grown',SYN,{'temperature':Q(118,'°C'),'duration':Q(15,'min')},desc='The 15 min endpoint is the Experimental branch. Figure 1A is a distinct approximately 5 min aliquot and does not characterize this exact final batch.')
  add(r,'cool','rapid_cooling','Terminate the low-concentration branch by rapid cooling to 70 °C',['grown'],'cooled',SYN,{'target_temperature':Q(70,'°C'),'cooling_duration':Q(u='s')},desc='Cooling method and elapsed time are not reported.')
  st='cooled'
 else:
  add(r,'ramp','gradual_heating','Gradually heat the injected reaction from 118 °C to 150 °C',['injected-mixture'],'growth-temperature',SYN,{'initial_temperature':Q(118,'°C'),'target_temperature':Q(150,'°C'),'ramp_rate':Q(u='°C/min')},desc='Methods says gradual heating; Discussion describes fast heating. No quantified ramp or time-zero definition reconciles those descriptions.')
  hold=Q(time,'min',E(3,'Assembly growth'))if time is not None else Q(u='min',e=E(1,'Abstract')+E(5,'Assembly discussion'),minimum=10,maximum=60,qualifier='Source spherical-assembly regime; a trajectory window, not one independently timed batch.')
  add(r,'grow','assembly_growth','Grow '+('spherical assemblies in the reported 10–60 min regime'if time is None else f'wire-like assemblies for the reported {time} min'),['growth-temperature'],'assembled',RES+E(5,'Assembly discussion'),{'temperature':Q(150,'°C',RES),'duration':hold},desc='Methods allows extended growth up to 150 min. Individual specimen times and caption-ratio discrepancies remain separately scoped; no unreported endpoint quench or isolated whole-batch yield is assumed.')
  st='assembled'
 p=P(r,'route-product',title,SYN+RES,st=st,explicit=True);p['morphology']=F({'individual':'Separate nanocrystals; source uses both spherical and cubic shape descriptions','spheres':'Spherical polycrystalline nanocrystal assemblies','wires':'Ordered wire-like nanocrystal assemblies'}[morph],RES)
 p['phase']=F('Rock-salt cubic PbSe',E(2,'Individual nanocrystal phase')+E(3,'Wire SAED'),note='Phase evidence from separately described representative specimens, not a sample-specific atomic coordinate file.');p['surface']=F('TOPO/TBP-capped',E(2,'Results'))
 r['condition_options']=[{'id':'topo90','label':'TOPO, Aldrich 90% purity; alternative to 99% grade.','parameters':{'purity':Q(90,'%',SYN,basis='Source purity basis unspecified')},'evidence':deepcopy(SYN)},{'id':'topo99','label':'TOPO, Aldrich 99% purity; alternative to 90% grade.','parameters':{'purity':Q(99,'%',SYN,basis='Source purity basis unspecified')},'evidence':deepcopy(SYN)}]
 if k=='individual-low':r['quality']['conflicts'].append('Methods/body stock ratio is 0.25:0.6:50, but Summary prints 0.25:0.6:0.5. Figure 1A ~5 min differs from the 15 min terminal protocol.')
 if k in ['sphere-intermediate','wire-intermediate']:r['quality']['conflicts'].append('Methods/body intermediate stock is 0.5:1.2:50; Figures 1 and 4 captions print 0.5:1:50. Figure 2 caption instead identifies high stock 1:2.5:50 while body associates its 90 min wires with intermediate stock. Figure-specific sample links remain unresolved.')
 if k=='wire-high':r['quality']['conflicts'].append('Body explicitly reports high-stock wire formation at 40 min as not shown. Figure 2 high-stock caption gives 90 min for its junction panel, conflicting with the body attribution to intermediate stock. Do not identify the 40 min product with a particular displayed micrograph.')
 T(r,'framework','route-product','recipe_framework_scope','Shared stock preparation and injection framework reconstructed from Methods; exact stock amount, per-image batch identity and purification yield are missing. This record denotes a literature route, not independent replicated experiments.',SYN+RES)
 link(r,'aliquot-workup','Aliquot quenching and purification','Common sampling procedure applies to removed aliquots; not asserted for the entire mother batch.');link(r,{'individual':'individual-structure','spheres':'sphere-structure','wires':'wire-structure'}[morph],'Source-specific structural observations');link(r,'assembly-model','Assembly interpretation and source conflicts');records.append(r)

r=base('aliquot-workup','Reaction aliquot quenching and purification','procedure','Aliquot quench and repeated precipitation')
r['materials']=[C('pbse-individual','possible_specimen','characterization'),C('pbse-spheres','possible_specimen','characterization'),C('pbse-wires','possible_specimen','characterization'),C('methanol','quench_antisolvent','workup'),C('butanol','solvent','workup')]
add(r,'withdraw','aliquot_withdrawal','Withdraw a reaction aliquot with a syringe',[],'aliquot',SYN,{'sampling_interval':Q(u='min',qualifier='Every few minutes; no numerical complete schedule.'),'aliquot_volume':Q(u='mL')},stage='characterization',desc='The selected route and elapsed time define each aliquot. Individual, spherical and wire specimens are alternative source populations, not mixed inputs.')
add(r,'quench','methanol_quench','Inject the removed aliquot into 1 mL methanol',['aliquot','methanol'],'quenched-aliquot',SYN,{'methanol_volume':Q(1,'mL')},stage='workup',desc='Source states that methanol quenches further nanocrystal growth. This is a removed aliquot treatment, not a claim that 1 mL quenched the whole mother solution.')
add(r,'centrifuge','centrifugal_separation','Separate products from the quenched solution by centrifugation',['quenched-aliquot'],'isolated-product',SYN,{'speed':Q(u='rpm'),'duration':Q(u='min')},stage='workup',retain=True,desc='Product fraction retained; exact centrifugal force/speed, duration and solvent removal procedure are unreported.')
add(r,'redisperse','redissolution','Redissolve the separated product in methanol–butanol solution',['isolated-product','methanol','butanol'],'redissolved-product',SYN,{'solvent_ratio':Q(u='volume ratio'),'solvent_volume':Q(u='mL')},stage='workup',desc='The paper calls this redissolving; butanol isomer, mixture ratio and degree of particle dissolution versus redispersion are unspecified.')
add(r,'repeat','repeated_redissolution_centrifugation','Repeat redissolving–centrifuging cycles for purification',['redissolved-product'],'purified-aliquot',SYN,{'cycle_count':Q(u='cycles',qualifier='Several; no exact count.')},stage='workup',retain=True,desc='Authors associate these cycles with purification and improved monodispersity. No numerical recovered mass or narrowing is given.')
P(r,'aliquot','Generic removed reaction aliquot; route/time assigned only when stated',SYN,st='purified-aliquot');T(r,'scope','aliquot','aliquot_workup_scope','The sequence immediately follows syringe withdrawal into methanol. Its application to the full mother batch and any final dry-powder isolation are not specified.',SYN);records.append(r)

r=base('microscopy','TEM, HR-TEM, HR-SEM, SAED and EDAX acquisition','procedure','Electron microscopy and diffraction')
r['materials']=[C('pbse-individual','possible_specimen','characterization'),C('pbse-spheres','possible_specimen','characterization'),C('pbse-wires','possible_specimen','characterization'),C('formvar-grid','sample_support','characterization')]
add(r,'deposit','tem_grid_deposition','Place small solution droplets on a Formvar/carbon-coated copper grid',['formvar-grid'],'grid-specimen',MIC,{'grid_mesh':Q(300,'mesh',MIC),'droplet_volume':Q(u='µL',e=MIC)},stage='characterization',parents=[],desc='A selected TEM specimen is placed on the grid. The three morphology inputs are possible separate populations, not one mixed specimen; grid is support, not product composition.')
add(r,'dry','grid_drying','Dry the TEM specimen at room temperature',['grid-specimen'],'dry-grid',MIC,{'temperature':Q(u='°C',e=MIC,qualifier='Room temperature; numerical value not stated.'),'duration':Q(u='min',e=MIC)},stage='characterization')
add(r,'tem','transmission_electron_microscopy','Image the selected specimen with JEOL 2000FX TEM',['dry-grid'],'tem-data',MIC,{'accelerating_voltage':Q(200,'kV',MIC)},stage='characterization',kind='analysis_data')
add(r,'hrtem','high_resolution_tem','Acquire high-resolution images with JEOL 3010',['dry-grid'],'hrtem-data',MIC,{'accelerating_voltage':Q(300,'kV',MIC)},stage='characterization',kind='analysis_data',depends=['dry'])
add(r,'sem','high_resolution_sem','Examine separate assembly specimens with Zeiss Leo 982 HR-SEM',[],'sem-data',MIC,{'accelerating_voltage_methods':Q(4,'kV',MIC),'accelerating_voltage_figure5_label':Q(10,'kV',E(5,'Figure 5B micrograph label'),status='inferred',qualifier='Read from original SEM image annotation; distinct from Methods.')},stage='characterization',kind='analysis_data',depends=[],desc='SEM sample deposition is not specified as identical to TEM grid preparation. The electrical-device SEM annotation prints 10.0 kV, in contrast to the general 4 kV method.')
add(r,'saed','selected_area_electron_diffraction','Acquire selected-area electron diffraction for separate specimens',['dry-grid'],'saed-data',MIC,{'accelerating_voltage':Q(200,'kV',MIC)},stage='characterization',kind='analysis_data',depends=['dry'],desc='JEOL 2000FX is the named TEM/EDAX/SAED instrument. Figure 1E spherical and Figure 2C wire patterns are actual distinct measured images.')
add(r,'edax','energy_dispersive_xray_analysis','Perform EDAX coupled to the JEOL 2000FX TEM',['dry-grid'],'edax-data',MIC,{'accelerating_voltage':Q(200,'kV',MIC)},stage='characterization',kind='analysis_data',depends=['dry'],desc='Technique is listed, but no EDAX spectrum, composition result or quantitative stoichiometry is reproduced in the inspected article.')
add(r,'microdiffraction','electron_microdiffraction','Examine wire microdiffraction as reported',[],'microdiffraction-data',E(3,'Wire diffraction discussion'),stage='characterization',kind='analysis_data',depends=[],desc='Authors state additional microdiffraction confirmed single-crystalline behavior, but the pattern and its exact instrument/settings are not shown.')
P(r,'acquisition','Shared instrument context; morphology-specific results remain separate',MIC)
T(r,'edax-limit','acquisition','edax_result_availability','EDAX is named as a method but no measured composition table or spectrum is supplied. Cu/Formvar/carbon grid materials cannot be treated as PbSe composition.',MIC)
r['quality']['conflicts'].append('General HR-SEM method is 4 kV, but Figure 5B image annotation reads 10.0 kV.');records.append(r)

r=base('absorption','Absorption during spherical-assembly growth','procedure','UV–visible–near-infrared absorption')
r['materials']=[C('pbse-spheres','specimen','characterization')]
add(r,'prepare','optical_aliquot_selection','Select separate assembly aliquots after 30, 35 and 40 min',['pbse-spheres'],'optical-specimens',E(3,'Figure 4 discussion')+E(4,'Figure 4'),stage='characterization',kind='sample_set',desc='Body associates these aliquots with 0.5:1.2:50 stock at 150 °C; caption prints 0.5:1:50. No cuvette path length, final dispersion solvent or concentration is supplied.')
add(r,'measure','absorption_spectroscopy','Record UV–visible and UV–visible–NIR absorption spectra',['optical-specimens'],'absorption-data',MIC+E(4,'Figure 4'),stage='characterization',kind='analysis_data',desc='Shimadzu UV–vis spectrometer and JASCO V-570 UV–vis–NIR spectrometer are named. Acquisition temperature, resolution and per-curve normalization are not stated.')
for t in [30,35,40]:
 P(r,'time-'+str(t),'Figure 4 spherical-assembly aliquot at '+str(t)+' min',E(3,'Absorption discussion')+E(4,'Figure 4'),explicit=True)
 M(r,'time-'+str(t),'time-'+str(t),'source_aliquot_growth_time',t,'min',E(3,'Absorption discussion')+E(4,'Figure 4 labels'))
P(r,'series','Figure 4 optical series; exact caption/body stock assignment unresolved',E(4,'Figure 4'))
M(r,'bands','series','pronounced_exciton_band_count',2,'bands',E(3,'Absorption discussion'))
M(r,'wavelengths','series','reported_exciton_wavelength_window',None,'nm',E(3,'Absorption discussion'),minimum=1000,maximum=1600,conditions='Window spanning two source-reported bands; not two exact fitted peak wavelengths.')
M(r,'energies','series','reported_exciton_energy_window',None,'eV',E(3,'Absorption discussion'),minimum=.775,maximum=1.240,conditions='Author-reported energy window, not a new conversion or exact peak pair.')
M(r,'redshift','series','growth_series_absorption_redshift',.04,'eV',E(4,'Section 4 optical discussion'),status='author_derived',conditions='Series-level interpretation; no exact two-curve endpoint assignment is supplied.')
M(r,'blueshift','series','assembly_absorption_blueshift_from_bulk',.5,'eV',E(5,'Optical discussion'),status='author_derived',conditions='Author summary of retained quantum confinement; no independently extracted peak position.')
T(r,'evolution','series','optical_assembly_interpretation','Excitonic features remain distinct and blue-shifted from bulk; slight broadening versus individual nanocrystals and redshift during heating may reflect individual growth and added interparticle coupling. Spectra alone do not resolve those contributions.',E(3,'Absorption discussion')+E(4,'Section 4')+E(5,'Continuation'),status='author_derived')
r['quality']['conflicts'].append('Figure 4 caption prints 0.5:1:50, whereas body optical paragraph identifies 0.5:1.2:50.');records.append(r)

r=base('device-fabrication','Contacting a single PbSe nanocrystal wire assembly','procedure','Lithographic electrical-device preparation')
r['materials']=[C('pbse-wires','specimen','characterization'),C('silicon-substrate','substrate','characterization'),C('silica-layer','substrate_layer','characterization',quantities={'thickness':Q(200,'nm',DEV)}),C('trimethylsilane','surface_treatment','characterization',notes=['The paper prints trimethylsilane. A bound Si(CH3)3 group in Figure 5A does not establish chlorotrimethylsilane or another precursor. Reagent verification remains unresolved.']),C('pmma','resist','characterization'),C('titanium','contact_material','characterization'),C('gold','contact_material','characterization')]
add(r,'hydrophobize','substrate_surface_treatment','Treat p-doped Si with 200 nm oxide using the printed trimethylsilane',['silicon-substrate','silica-layer','trimethylsilane'],'hydrophobic-substrate',DEV,{'oxide_thickness':Q(200,'nm',DEV),'reagent_dose':Q(u='mL',e=DEV),'treatment_duration':Q(u='min',e=DEV)},stage='characterization',desc='Purpose is a hydrophobic surface. Treatment chemistry/solvent, surface cleaning and exact silane identity are not resolved beyond the printed name; no chloride reagent is silently substituted.')
add(r,'mark','optical_lithography','Draw positional markers by optical lithography',['hydrophobic-substrate'],'marked-substrate',DEV,stage='characterization',desc='Marker material, resist formulation, exposure and development settings are not reported.')
add(r,'spin-wire','wire_spin_coating','Spin-coat the PbSe wire-assembly dispersion on the substrate',['marked-substrate','pbse-wires'],'wire-coated-substrate',DEV,{'spin_speed':Q(u='rpm',e=DEV),'spin_duration':Q(u='s',e=DEV)},stage='characterization',desc='Dispersion solvent, concentration and deposited volume are not specified. Substrate/device components do not change the PbSe synthesis target.')
add(r,'locate','sem_wire_selection','Select a single wire and locate it relative to the markers',['wire-coated-substrate'],'located-wire',DEV,stage='characterization',desc='SEM inspection is used; no electron-beam voltage is independently stated for this alignment step.')
add(r,'coat-resist','pmma_spin_coating','Spin-coat PMMA resist over the selected wire',['located-wire','pmma'],'resist-coated-device',DEV,{'spin_speed':Q(u='rpm',e=DEV)},stage='characterization',desc='PMMA molecular weight, solvent, solids fraction and thickness are not given.')
add(r,'anneal','resist_annealing','Anneal the resist-coated device',['resist-coated-device'],'annealed-device',DEV,{'temperature':Q(u='°C',e=DEV),'duration':Q(u='min',e=DEV)},stage='characterization',desc='Annealing conditions were explored, but the numerical optimal temperature/time is not published. This device treatment is not the 150 °C synthesis growth step.')
add(r,'write-develop','electron_beam_lithography','Write and develop the electrode pattern by EBL',['annealed-device'],'patterned-device',DEV,stage='characterization',desc='Beam dose, energy, developer identity and development time are unreported.')
add(r,'evaporate-contacts','contact_metal_evaporation','Evaporate Ti/Au electrical contact leads',['patterned-device','titanium','gold'],'contacted-device',DEV,{'titanium_thickness':Q(u='nm',e=DEV),'gold_thickness':Q(u='nm',e=DEV)},stage='characterization',desc='The source names Ti/Au contacts; layer thickness, evaporation rates and chamber pressure are missing.')
add(r,'remove-resist','photoresist_removal','Remove the photoresist to expose the contacted wire',['contacted-device'],'completed-device',DEV,stage='characterization',desc='Dissolving solvents and conditions were examined but not reported. The source flags stripping the organic NC coating at contact points and avoiding unintended wire-surface modification; no distinct fully specified ligand-removal process is supplied.')
add(r,'inspect','final_sem_inspection','Examine the resulting circuit by SEM',['completed-device'],'device-inspection-data',DEV+E(5,'Figure 5B'),stage='characterization',kind='analysis_data',desc='Figure 5B is an actual contacted-wire image; its 10.0 kV annotation differs from the general 4 kV HR-SEM method.')
P(r,'device','Figure 5 contacted single PbSe wire assembly',ELEC,st='completed-device',explicit=True,notes=['Figure 5 caption names 1:2.5:50 high stock, but no precise growth time identifies each electrical wire.'])
T(r,'contact','device','contact_processing_limit','The contact protocol was optimized to remove organic coating locally while avoiding wire damage during photoresist stripping. The final annealing/solvent choices are absent, so the sequence is incomplete as a fabrication SOP.',DEV)
T(r,'gate','device','gate_geometry_scope','A silicon back gate appears in the circuit schematic. No gate sweep, field-effect transfer curve, gate bias or mobility result is reported; gated measurements are future work.',E(5,'Figure 5C')+E(6,'Summary'))
link(r,'electrical','Reported single-wire I–V measurements');records.append(r)

r=base('electrical','Room-temperature transport through three PbSe wire assemblies','procedure','Two-contact current–voltage measurement')
r['materials']=[C('pbse-wires','specimen','characterization')]
add(r,'measure','current_voltage_measurement','Measure separate contacted wires at room temperature',['pbse-wires'],'iv-data',ELEC,{'temperature':Q(u='°C',e=ELEC,qualifier='Room temperature; numerical value not stated.'),'applied_electric_field':Q(3.5e4,'V/m',E(4,'Electrical measurements'))},stage='characterization',kind='analysis_data',desc='Three wires have separate I–V curves. Source gives an applied-field value but does not tabulate complete source-meter settings or per-wire voltage grids.')
add(r,'normalize','geometry_normalized_conductivity','Normalize I–V slopes by the wire dimensions',['iv-data'],'conductivity-data',E(4,'Electrical measurements'),stage='characterization',kind='analysis_data',desc='Source reports a representative resistivity/conductivity after dimension normalization, not separately tabulated uncertainty-bearing values for all three wires. Cross-section model and contact-resistance de-embedding are not fully specified.')
for k,w,l,label in [('square',110,700,'squares'),('circle',60,1000,'circles'),('triangle',150,1200,'triangles')]:
 P(r,k,'Figure 5D '+label+' wire',E(4,'Dimensions and curve assignment'),explicit=True)
 M(r,k+'-width',k,'wire_width',w,'nm',E(4,'Dimensions and curve assignment'))
 M(r,k+'-length',k,'wire_length',l,'nm',E(4,'Dimensions and curve assignment'))
P(r,'transport-context','Source-wide interpretation of the three contacted wire curves',ELEC)
M(r,'building-block','transport-context','electrical_wire_building_block_edge',10,'nm',E(4,'Electrical measurements'),conditions='Cubic nanocrystal building blocks; not the complete wire width.')
M(r,'resistivity','transport-context','reported_specific_resistivity',.15,'Ω cm',E(4,'Electrical measurements'),status='author_derived')
M(r,'conductivity','transport-context','reported_conductivity',7,'Ω^-1 cm^-1',E(4,'Electrical measurements')+E(6,'Transport discussion'),approximate=True,status='author_derived')
T(r,'linear','transport-context','current_voltage_behavior','Source curves are approximately linear at room temperature. Authors take this as excluding a Schottky barrier at the contacts; this is their interpretation, not an independent contact-potential measurement.',E(4,'Electrical measurements'),status='author_derived')
M(r,'sem-scale','transport-context','device_sem_scale_bar',3,'µm',E(5,'Figure 5B scale bar'),status='inferred',qualifier='Original image annotation.')
T(r,'transport-limit','transport-context','transport_mechanism_status','Resonant tunneling, thermally activated transport and variable-range hopping are discussed. Temperature-dependent, higher-field and gated measurements remain future work; the mechanism is not established.',E(5,'Transport discussion')+E(6,'Discussion and Summary'),status='author_derived');records.append(r)

r=base('individual-structure','Individual PbSe nanocrystal morphology and lattice evidence')
P(r,'individual-series','Low-stock individual nanocrystals at 118 °C; variable reaction duration',RES)
M(r,'size-range','individual-series','individual_nanocrystal_size_range',None,'nm',E(2,'Results'),minimum=3.5,maximum=10,conditions='General time-dependent individual-NC range, not the 15 min endpoint or one monodisperse population.')
M(r,'distribution','individual-series','reported_relative_size_distribution',None,'%',E(2,'Results'),maximum=10,maximum_exclusive=True,conditions='Source does not define this as standard deviation, full width or another specific statistic.')
T(r,'shape','individual-series','individual_shape_language','Results first describes monodispersed spherical NCs and then cubic-shaped individual PbSe NCs. Figure 1A is a cubic-shaped representative; retain the source language without converting shape labels into separate experiments.',E(2,'Results')+E(3,'Figure 1A'))
p=P(r,'figure1a','Figure 1A: low-stock approximately 5 min individual NC',E(3,'Figure 1A caption'),explicit=True);p['phase']=F('Rock-salt cubic PbSe',E(2,'Results'));p['morphology']=F('Cubic-shaped individual nanocrystal',E(3,'Figure 1A'))
M(r,'f1-time','figure1a','source_aliquot_growth_time',5,'min',E(3,'Figure 1A caption'),approximate=True)
M(r,'f1-temperature','figure1a','source_growth_temperature',118,'°C',E(3,'Figure 1A caption'))
M(r,'f1-size','figure1a','representative_individual_nc_size',5,'nm',E(2,'Results'),conditions='Source calls it a single 5 nm nanocrystal; no uncertainty or explicit edge/diameter convention supplied.')
M(r,'f1-spacing','figure1a','interplanar_spacing',3.05,'Å',E(2,'Results'),tech='HR-TEM')
M(r,'f1-scale','figure1a','micrograph_scale_bar',5,'nm',E(3,'Figure 1A scale'),status='inferred',qualifier='Read from original scale annotation.')
T(r,'f1-zone','figure1a','hrtem_zone_axis','[100] rock-salt cubic projection',E(2,'Results'),tech='HR-TEM')
T(r,'endpoint-link','figure1a','sample_link_limit','Figure 1A is about 5 min; the preparative branch continues 15 min before cooling to 70 °C. No exact final size is assigned to the 15 min route.',SYN+E(3,'Figure 1A'));records.append(r)

r=base('sphere-structure','Spherical assembly size evolution and polycrystalline SAED')
for t,panel in [(10,'B'),(25,'C'),(40,'D')]:
 P(r,'figure1'+panel.lower(),'Figure 1'+panel+': spherical assembly aliquot',E(3,'Figure 1 caption'),explicit=True)
 M(r,'f1'+panel+'-time','figure1'+panel.lower(),'source_aliquot_growth_time',t,'min',E(3,'Figure 1 caption'))
 M(r,'f1'+panel+'-scale','figure1'+panel.lower(),'micrograph_scale_bar',200,'nm',E(3,'Figure 1'+panel+' image scale'),status='inferred',qualifier='Original scale-bar label.')
P(r,'sphere-series','Spherical assembly trajectory; caption/body precursor-ratio conflict',E(3,'Figure 1 and text'))
M(r,'body-range','sphere-series','spherical_assembly_diameter_range_body',None,'nm',E(3,'Results'),minimum=50,maximum=450)
M(r,'abstract-range','sphere-series','spherical_assembly_diameter_range_abstract',None,'nm',E(1,'Abstract'),minimum=50,maximum=500)
M(r,'onset','sphere-series','assembly_growth_threshold_time',5,'min',E(3,'Figure 1F discussion'),status='author_derived')
M(r,'plateau','sphere-series','assembly_plateau_after_time',None,'min',E(3,'Figure 1F discussion'),minimum=50,minimum_exclusive=True,status='author_derived')
T(r,'polycrystal','sphere-series','spherical_assembly_diffraction','Figure 1E selected-area diffraction indicates polycrystalline assembly with randomly oriented constituent NCs. Figure 1F plots assembly diameter versus reaction time; raw values and statistical uncertainties are not tabulated.',E(3,'Figure 1E–F')+E(4,'Discussion'),tech='SAED / HR-SEM',status='author_derived')
T(r,'size-scope','sphere-series','assembly_vs_primary_size','The 50–450 or 50–500 nm dimensions describe complete spherical assemblies, not constituent PbSe nanocrystals. Monodispersity is described for each time-selected population without a numerical distribution width.',E(1,'Abstract')+E(3,'Results'))
r['quality']['conflicts']=['Figure 1 caption ratio 0.5:1:50 differs from Methods/body 0.5:1.2:50. Abstract diameter span ends at 500 nm, while Results ends at 450 nm.'];records.append(r)

r=base('wire-structure','Straight, junction and bent wire assembly structure')
P(r,'wire-context','Source-wide ordered-wire morphology context',E(1,'Abstract')+E(3,'Results'))
M(r,'width-typical','wire-context','typical_wire_width_range',None,'nm',E(1,'Abstract'),minimum=60,maximum=150)
M(r,'length-typical','wire-context','typical_wire_length_range',None,'µm',E(1,'Abstract'),minimum=1,maximum=5)
M(r,'junction-fraction','wire-context','reported_junction_fraction',5,'%',E(3,'Results'),approximate=True,conditions='Source intermediate-stock 90 min description; denominator/sample count not supplied.')
M(r,'width-growth','wire-context','growth_stage_wire_width_range',None,'nm',E(3,'Wire growth discussion'),minimum=20,maximum=150,conditions='Intermediate-stage wires, distinct from the abstract typical-width span.')
M(r,'orientation','wire-context','accumulated_orientation_change',None,'degree',E(3,'Bright-field discussion'),minimum=1,maximum=2,approximate=True,conditions='Accumulated over tens of nanometers; nearest neighbors differ only by a fraction of a degree.')
T(r,'helix','wire-context','wire_orientation_interpretation','Dark bright-field HR-TEM regions move continuously as the wire is rotated. Authors describe helix-like orientational variation and suggest increasing width reflects coagulation toward a full cylindrical assembly.',E(3,'Figure 2A discussion'),status='author_derived')
for i,label in [('figure2a','Figure 2A bright-field wire'),('figure2b','Figure 2B junction wire'),('figure2c','Figure 2C wire SAED'),('figure3','Figure 3 bent wire, junction and edge')]:P(r,i,label,E(3,'Figure 2')if i!='figure3'else E(4,'Figure 3'),explicit=True)
M(r,'f2a-scale','figure2a','micrograph_scale_bar',40,'nm',E(3,'Figure 2A scale'),status='inferred',qualifier='Original image label.')
M(r,'f2b-scale','figure2b','micrograph_scale_bar',500,'nm',E(3,'Figure 2B scale'),status='inferred',qualifier='Original image label.')
M(r,'f2b-time','figure2b','caption_reaction_duration',90,'min',E(3,'Figure 2 caption'),conditions='Caption high-stock context, conflicting with body medium-stock attribution.')
M(r,'f2-cell','figure2c','source_cubic_lattice_constant',6.1,'Å',E(3,'Figure 2C caption and discussion'),tech='SAED')
T(r,'f2-zone','figure2c','wire_diffraction_assignment','Ordered rock-salt cubic PbSe, [100] zone axis. Spot pattern resembles a single crystal; authors use this as evidence for coherent orientation across an NC assembly, not proof of a uniform fused single-grain wire.',E(3,'Figure 2C'),tech='SAED',status='author_derived')
M(r,'f3-cell','figure3','source_cubic_lattice_constant',6.1,'Å',E(4,'Figure 3 caption'),tech='HR-TEM')
M(r,'f3-fringe','figure3','interplanar_spacing',3.05,'Å',E(3,'Bent wire discussion')+E(4,'Figure 3A/C labels'),tech='HR-TEM',conditions='Figure labels assign (200) fringes in [100] projection.')
M(r,'f3-block','figure3','bent_wire_building_block_edge',10,'nm',E(3,'Bent wire discussion')+E(4,'Figure 3 caption'),approximate=True)
M(r,'f3-scale','figure3','micrograph_scale_bar',10,'nm',E(4,'Figure 3B scale'),status='inferred',qualifier='Original image label.')
T(r,'f3-scope','figure3','bent_wire_sample_scope','Figure 3 caption identifies high-stock 1:2.5:50 but no growth time. This cannot be assigned automatically to the explicitly reported 40 min high-stock product.',E(4,'Figure 3 caption')+E(3,'High-stock 40 min statement'))
r['quality']['conflicts']=['Figure 2 caption assigns high stock 1:2.5:50 (90 min for B), whereas body cites intermediate stock 0.5:1.2:50 for 90 min and those panels. Preserve both statements without repairing the batch assignment.'];records.append(r)

r=base('assembly-model','Interparticle separation, permanent dipoles and assembly interpretation')
P(r,'assembly-model','Author model for adjacent capped PbSe nanocrystals',E(4,'Section 4')+E(5,'Discussion'))
P(r,'literature-context','Cited interparticle-coupling context, not a measurement of this specimen',E(4,'Section 4'))
M(r,'general-separation','literature-context','cited_interparticle_separation_range',None,'nm',E(4,'Section 4'),minimum=0,maximum=5,status='author_derived',conditions='General range from intimate contact to about 5 nm, dependent on ligands. Zero denotes prose intimate-contact limit, not a measured spacing here.',approximate=True)
M(r,'present-separation','assembly-model','estimated_ligand_separated_surface_gap',1.1,'nm',E(4,'Section 4'),approximate=True,status='author_derived')
M(r,'exchange-threshold','literature-context','cited_exchange_coupling_gap_threshold',None,'nm',E(4,'References 58 discussion'),maximum=.5,maximum_exclusive=True,status='author_derived')
M(r,'dipolar-threshold','literature-context','cited_dipolar_coupling_gap_threshold',None,'nm',E(4,'Section 4'),minimum=.5,minimum_exclusive=True,status='author_derived')
M(r,'heated-gap','assembly-model','proposed_heated_interparticle_gap',.6,'nm',E(5,'Optical discussion and references 45,61'),status='author_derived',conditions='Suggested partial ligand loss during heating, not a directly measured gap for a specified aliquot.')
T(r,'distance-effects','assembly-model','interparticle_coupling_hypothesis','TOPO/TBP separates neighboring NCs. Ligand interdigitation or dilute coating may reduce the gap; shorter separation may promote wave-function overlap, whereas the authors favor permanent dipolar coupling for these assemblies because confinement remains evident.',E(4,'Section 4')+E(5,'Optical discussion'),status='author_derived')
T(r,'dipole-origins','assembly-model','proposed_permanent_dipole_origins','Possible origins are deviations of cube corners and localization of carriers at surface defects/strain. Mutual polarization of nearby particles could increase their permanent dipoles; these mechanisms are hypotheses rather than measured charge maps.',E(5,'Permanent-dipole discussion and references 30,62'),status='author_derived')
T(r,'dipole-equation','assembly-model','printed_dipole_equation','μ = 6 e r ε₂∞ / (ε₂∞ + 2 ε₁∞). The source calls r the individual nanocrystal diameter; ε₂∞ refers to PbSe and ε₁∞ to the external medium.',E(5,'Unnumbered permanent-dipole equation'),status='author_derived')
M(r,'pbse-dielectric','assembly-model','model_pbse_dielectric_constant',24,'dimensionless',E(5,'Dipole-model inputs'),status='author_derived')
M(r,'topo-dielectric','assembly-model','model_topo_dielectric_constant',2.1,'dimensionless',E(5,'Dipole-model inputs'),status='author_derived')
M(r,'model-diameter','assembly-model','model_particle_diameter',10,'nm',E(5,'Dipole estimate'),status='author_derived')
M(r,'dipole','assembly-model','author_estimated_permanent_dipole',500,'D',E(5,'Dipole estimate'),status='author_derived')
T(r,'interaction-equation','assembly-model','printed_dipole_interaction_equation','ΔH = −μ / [2π ε₀ r (r² − D²)], transcribed as printed with μ rather than a silently inserted μ². D is identified as surface-to-surface NC distance. The dimensional/formula ambiguity is unresolved; no corrected recomputation is supplied.',E(5,'Unnumbered interaction-energy equation'),status='author_derived')
M(r,'epsilon0','assembly-model','printed_vacuum_permittivity',8.9e-12,'C² J^-1 m^-1',E(5,'Interaction-energy inputs'),status='author_derived')
M(r,'enthalpy','assembly-model','author_estimated_interparticle_interaction_energy',-28,'kJ/mol',E(1,'Abstract')+E(5,'Interaction-energy estimate')+E(6,'Summary'),status='author_derived',conditions='Reported model output for 10 nm PbSe NCs; formula/diameter conventions are not repaired or independently validated.')
T(r,'free-energy','assembly-model','author_assembly_free_energy_argument','The authors describe ΔS as negative when disordered NCs enter an ordered assembly and conclude ΔG = ΔH − TΔS < 0. They provide no numerical entropy or full free-energy balance; ΔS < 0 alone does not establish that conclusion.',E(5,'Entropy/free-energy discussion'),status='author_derived')
M(r,'sphere-time','assembly-model','author_spherical_assembly_time_regime',None,'min',E(5,'Assembly mechanism'),minimum=10,maximum=60,status='author_derived')
M(r,'ordered-time','assembly-model','author_ordered_assembly_time_threshold',None,'min',E(5,'Assembly mechanism'),minimum=60,minimum_exclusive=True,status='author_derived',conditions='Higher concentration can also produce wires earlier; not a universal lower bound on all wire synthesis.')
T(r,'order','assembly-model','author_assembly_ordering_mechanism','Faster heating and intermediate times permit diffusion into randomly oriented spheres. Longer time or higher concentration is proposed to allow equilibration and orientational order along a polarization axis, generating wires. The mechanism is inferred from morphology, not measured individual-particle trajectories.',E(4,'Section 4')+E(5,'Assembly mechanism'),status='author_derived')
M(r,'impurity-effect','assembly-model','reported_wire_formation_increase_with_technical_topo',15,'%',E(5,'TOPO impurity discussion'),approximate=True,status='author_derived',conditions='Source says wire assembly formation increased by about 15%; whether relative percent or percentage points and denominator are unspecified. No fully quantified paired purity-control recipe or yield table.')
T(r,'impurity','assembly-model','technical_topo_facet_stabilization_hypothesis','The authors attribute increased wire formation with 90% TOPO to impurities such as phosphonic acid selectively stabilizing facets and favoring prolonged particles, citing reference 12. Impurity identities/amounts and direct facet-specific measurements are absent.',E(5,'TOPO impurity discussion'),status='author_derived')
r['quality']['conflicts']=['The printed interaction formula uses μ, with unresolved dimensional convention; r is called diameter and later enters radius-like expressions. No formula correction or rederived energy is substituted.','Methods describes gradual heating; Discussion uses fast heating. Neither provides a numerical ramp.'];records.append(r)

r=base('transport-model','Author estimates for fields, charging, transfer energy and conductivity')
P(r,'model','Representative capped 10 nm PbSe NC within a wire; author model',E(6,'Discussion calculations a–e'))
P(r,'comparison','Cited PbSe thin-film and quantum-well comparisons',E(6,'Discussion e and references 66–67'))
T(r,'field-equation','model','printed_internal_field_equation','E ≈ V/(εₘ L), where V is applied wire voltage and L wire length.',E(6,'Calculation a'),status='author_derived')
T(r,'dielectric-equation','model','printed_effective_dielectric_expression','εₘ = ε₁∞ + 4√2π/(ε₂∞ − ε₁∞) [1/2r/(r + D)]³, retaining the literal printed 1/2r sequence and unusual denominator. The source describes this as volume-weighted dielectric averaging. The grouping, equation and radius/diameter convention are unresolved; no corrected calculation is substituted.',E(6,'Calculation a, original displayed inline expression'),status='author_derived')
for i,pr,v,u in [('diameter','model_particle_size_parameter_r',10,'nm'),('gap','model_surface_gap_D',1.1,'nm'),('voltage','model_applied_voltage',35,'mV'),('field','author_estimated_internal_field',7e3,'V/m'),('resistance','author_estimated_single_capped_nc_resistance',18,'kΩ'),('capacitance','author_estimated_single_nc_capacitance',1.5e-18,'F'),('time','author_estimated_rc_time',2.7e-14,'s'),('transfer','author_estimated_transfer_energy',76,'meV'),('spacing','cited_conduction_intraband_spacing',100,'meV'),('drop','author_estimated_interparticle_energy_drop',7,'µeV'),('barrier','cited_topo_potential_barrier',20,'µeV')]:
 M(r,i,'model',pr,v,u,E(6,'Calculations a–d'),status='author_derived',approximate=i in ['field','resistance','spacing'],conditions='As-printed estimate/reference in the source model; not an independent experimental fit or synthesis condition.')
T(r,'capacitance-equation','model','printed_self_capacitance_equation','C = 4π ε₀ εₘ (r + D). The source labels r as a particle diameter elsewhere; this convention remains unresolved.',E(6,'Calculation b'),status='author_derived')
T(r,'lifetime-equation','model','printed_residence_time_equation','τ = RC; source interprets this as the lifetime of an electron localized on a given nanocrystal.',E(6,'Calculations b–c'),status='author_derived')
T(r,'transfer-equation','model','printed_transfer_energy_equation','E_T = πℏ/τ. The printed result is 76 meV, compared with an approximately 100 meV conduction intraband spacing to argue for sensitivity to discrete electronic states.',E(6,'Calculation c'),status='author_derived')
T(r,'drop-equation','model','printed_interparticle_energy_drop_expression','eED = 7.0 µeV, compared with a cited 20 µeV TOPO barrier. Preserve these source estimates and units; no unreported barrier measurement is inferred.',E(6,'Calculation d'),status='author_derived')
M(r,'film-conductivity','comparison','cited_polycrystalline_film_conductivity',55e-3,'Ω^-1 cm^-1',E(6,'Calculation e, reference 66'),status='author_derived',conditions='External PbSe thin film with microsized grains, not a specimen synthesized here.')
M(r,'well-conductivity','comparison','cited_quantum_well_conductivity',None,'Ω^-1 cm^-1',E(6,'Calculation e, reference 67'),minimum=10,maximum=20,approximate=True,status='author_derived',conditions='External two-dimensional PbSe quantum-well comparison; not another current-paper recipe.')
T(r,'candidates','model','proposed_transport_mechanisms','Possible transport paths are resonant tunneling among discrete states, thermal activation to a mobility edge or variable-range hopping. Source argues that dipolar coupling links NCs while their ligand coating supplies a barrier; no complete temperature-dependent discrimination is reported.',E(5,'Transport discussion')+E(6,'Continuation'),status='author_derived')
T(r,'summary-units','model','summary_field_wording_conflict','Summary calls 7.0 × 10³ V/m an applied voltage per NC although the units and earlier calculation identify an electric field. Keep the terminology discrepancy explicit.',E(6,'Summary'))
r['quality']['conflicts']=['Model expressions use r with a diameter definition but radius-like geometric roles; dielectric-average typography is unusual. All outputs are author estimates, not corrected derived labels.','Summary calls a V/m quantity voltage per NC, unlike the earlier field definition.'];records.append(r)

r=base('source-context','Source coverage, background comparisons and unresolved information')
P(r,'source','Complete local main-paper source bundle',E(1,'Title and abstract')+E(7,'References'))
P(r,'bulk','Cited bulk-PbSe reference properties',E(1,'Introduction'))
P(r,'prior','Prior PbSe quantum dots and related nanostructures',E(1,'Introduction')+E(2,'Introduction'))
T(r,'scope','source','inspected_document_scope','All seven main pages, Figures 1–5 and their panels, every unnumbered equation and numbered references 1–67 were text-read and visually inspected. The incoming and legacy main PDFs are byte-identical. No matching SI was supplied or used; SI existence is unverified.',E(1,'Front matter')+E(7,'End of article'))
T(r,'date','source','publication_date_scope','Journal citation is Nano Letters 2004, 4(1), 159–165. Published online November 26, 2003; received July 14, 2003 and revised November 10, 2003. The source group uses the journal year 2004.',E(1,'Front matter'))
T(r,'conflicts','source','source_conflict_register','Preserve intermediate mass ratio 0.5:1.2:50 in Methods/body versus 0.5:1:50 in Figures 1/4; Figure 2 high-stock caption versus intermediate-stock 90 min body; Summary low-stock 0.25:0.6:0.5 versus 0.25:0.6:50 elsewhere; 4 kV general SEM versus 10 kV Figure 5B; gradual versus fast heating language; assembly-size spans 50–450 versus 50–500 nm; printed model equations and field/voltage terminology.',SYN+E(3,'Figures 1–2')+E(4,'Figure 4')+E(5,'Figure 5 and models')+E(6,'Summary'))
M(r,'maximum-extended-duration','source','maximum_reported_extended_reaction_duration',None,'min',SYN,maximum=150,conditions='General extended branch limit from Methods, not a separately characterized 150 min synthesis or the endpoint of every route.')
for context,parts,e in [('caption-intermediate',[.5,1,50],E(3,'Figure 1 caption')+E(4,'Figure 4 caption')),('summary-low',[.25,.6,.5],E(6,'Summary'))]:
 for component,value in zip(['selenium','lead_precursor','tbp'],parts):M(r,context+'-'+component,'source',context.replace('-','_')+'_'+component+'_mass_part',value,'mass parts',e,conditions='Conflicting printed ratio preserved as source context; not silently substituted into the Methods-based synthesis stock.')
T(r,'structures','source','structure_and_characterization_availability','Original SAED panels 1E and 2C and lattice-resolved Figures 1A/3 are available. Rock-salt structure and a 6.1 Å cubic lattice constant are reported for wires, but no atom coordinates or measured CIF are supplied. EDAX is named without a displayed composition result; no XRD, Raman or photoluminescence data for the current assemblies are presented.',MIC+E(3,'Figures 1–2')+E(4,'Figure 3'))
T(r,'future','source','author_future_work','Authors plan temperature-dependent I–V, stronger electric fields and gate-dependent studies to test the transport mechanism. Device and optical applications remain motivation, not measured performance beyond the displayed absorption and I–V data.',E(6,'Discussion and Summary'),status='author_derived')
for i,pr,v,u in [('gap','bulk_direct_band_gap',.28,'eV'),('temperature','bulk_reference_temperature',300,'K'),('dielectric','bulk_high_frequency_dielectric_constant',24,'dimensionless'),('bohr','bulk_effective_exciton_bohr_radius',46,'nm'),('ratio','bohr_radius_relative_to_cdse',8,'dimensionless')]:M(r,i,'bulk',pr,v,u,E(1,'PbSe background'),status='author_derived',conditions='Cited bulk reference context, not current nanocrystal measurement.')
M(r,'mass','bulk','bulk_electron_hole_effective_mass_upper_bound',None,'m*',E(1,'Reference 49 context'),maximum=.1,maximum_exclusive=True,status='author_derived',conditions='Source prints <0.1 m* for small electron and hole effective mass; preserve its notation.')
T(r,'bulk-phase','bulk','bulk_phase_and_gap_location','Bulk PbSe is rock-salt cubic with a direct gap at L. These bulk properties motivate strong quantum confinement; they are not sample-specific refined coordinates.',E(1,'Introduction'))
M(r,'prior-gap','prior','cited_individual_pbse_transition_energy_range',None,'eV',E(1,'Prior optical studies')+E(2,'Reference 54 context'),minimum=.5,maximum=1.1,status='author_derived')
M(r,'prior-core-shell','prior','cited_pbse_pbs_core_shell_size_range',None,'nm',E(2,'Reference 55 context'),minimum=2.5,maximum=7,status='author_derived',conditions='Prior synthesis and enhanced PL statement; no reproduced current core-shell recipe.')
for i,pr,v,u in [('wire-width','cited_individual_wire_width',20,'nm'),('wire-length','cited_individual_wire_length',1,'µm'),('rod-width','cited_individual_rod_width',20,'nm'),('rod-length','cited_individual_rod_length',100,'nm'),('cube','cited_individual_cube_size',100,'nm')]:M(r,i,'prior',pr,v,u,E(2,'Reference 56 context'),status='author_derived',conditions='Prior alkyl-diamine-templated individual nanostructures, not current assembled wires or new fully quantified routes.')
T(r,'prior-properties','prior','cited_optical_and_transport_background','Prior PbSe dots show small Stokes shifts, sub-microsecond interband lifetimes and fast 1S–1P / 1P–1D intraband relaxation; earlier thermoelectric work reports a Seebeck increase. These cited claims are not new lifetime, quantum-yield or thermoelectric measurements for this paper’s assemblies.',E(1,'Introduction')+E(2,'References 50–56 context'))
T(r,'references','source','reference_scope','References 1–29 motivate nanocrystal photophysics, shapes and applications; 30–48 concern assemblies and interactions; 49–56 PbSe properties and earlier syntheses; 57–62 structure/coupling/dipole/ligand arguments; 63–67 transport mechanisms and external conductivity comparisons. Citation reading is not full-text verification of those papers.',E(6,'References 1–30')+E(7,'References 31–67'))
records.append(r)

if __name__=='__main__':
 out=B/'canonical-drafts';out.mkdir(exist_ok=True);errors=[]
 for r in records:
  errors+=validate_record(r);(out/(r['record_id']+'.json')).write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 report={'status':'failed'if errors else'passed','record_count':len(records),'operation_count':sum(len(r['operations'])for r in records),'measurement_count':sum(len(r['measurements'])for r in records),'material_slots':sum(len(r['materials'])for r in records),'source_read_pages':7,'source_visual_pages':7,'main_pages':7,'si_pages':0,'errors':errors}
 (B/'records-validation.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 (B/'canonical-material-identities.json').write_text(json.dumps({'source_id':SID,'source_group':SID,'materials':[{'id':i,'name':n,'formula':f}for i,(n,f,e)in CHEM.items()],'record_material_ids':{r['record_id']:[m['id']for m in r['materials']]for r in records}},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 raw=json.loads((B/'source-manifest.json').read_text(encoding='utf-8-sig'))
 (B/'canonical-record-manifest.json').write_text(json.dumps({'source_id':SID,'source_group':SID,'source_fingerprint':raw.get('fingerprint'),'main_pages_read_and_visually_inspected':7,'si_pages_read_and_visually_inspected':0,'supporting_information':'Not supplied or used; existence/absence unverified.','records':[{'id':r['record_id'],'record_type':r['record_type'],'sha256':hashlib.sha256((out/(r['record_id']+'.json')).read_bytes()).hexdigest(),'operation_ids':[o['id']for o in r['operations']],'sample_ids':[p['sample_id']for p in r['products']],'measurements':len(r['measurements'])}for r in records]},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 print(json.dumps(report))
 if errors:raise SystemExit(1)
