from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
B=Path(__file__).resolve().parent;MON=B.parent.parent;M=B.parents[3];S=M/'recipe-atlas'
def read(p):return json.loads(p.read_text(encoding='utf8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
n=read(B/'native-publication.json');saved=n['saved_version'];d=n['deployment'];assert d['status']=='succeeded' and saved['id']==d['version_id']
assert saved['source']['commit_sha']==read(B/'publication-source.json')['commit_sha']
ledger=read(MON/'ledger.json');assert ledger['current_paper']['group_id']=='10.1021_nl0345116';g=ledger['groups']['10.1021_nl0345116'];fp=g['fingerprint']
assert fp['generation']==g['generation']==2 and fp['bundle_sha256']=='8064ad5271eeefd0c71131b70a6f1701157a4641a031632addd04fd02e7d77a9'
assert set(fp['files'].values())=={'72684e3bf22a2ef173ea1d6d6e31648a1222b2b15bc069bb8fe6cef8d1876a33'}
write(B/'final-source-fingerprint.json',{'group_id':'10.1021_nl0345116',**fp})
inv=read(S/'data/inventory-summary.json');row=next(x for x in inv['per_paper']if x['source_group']=='sashchiuk2004');index=read(S/'dist/data/materials-index.json');hubs=[x for x in index['materials']if x['formula']=='PbSe'];assert len(hubs)==1
reader=read(S/'data/paper-reviews/sashchiuk2004.json');audit=read(B/'source-audit.json');records=[read(S/'data/records'/(k+'.json'))for k in row['record_ids']]
archive=S/'.sites-runtime/site-sashchiuk2004.tar.gz';assert sha(archive)==read(B/'archive-validation.json')['sha256']
p=dict(status='published',source_commit=saved['source']['commit_sha'],site_project_id=saved['project_id'],public_live_version=saved['version_number'],dataset_version=read(S/'dist/data/dataset-manifest.json')['dataset_version'],source_pushed=True,archive=str(archive.relative_to(M)),archive_sha256=sha(archive),archive_storage=saved['archive_storage'],version_id=saved['id'],deployment_id=d['id'],deployment_status=d['status'],public_url=d['url'],published_at=d['updated_at'],review_scope='supplied_main_only_si_unverified',source_id='sashchiuk2004',doi='10.1021/nl0345116',records=len(records),synthesis_routes=row['synthesis_route_variant_count'],supporting_procedures=row['procedure_count'],contextual_observations=row['contextual_observation_count'],measurement_entries=sum(len(r['measurements'])for r in records),operations=sum(len(r['operations'])for r in records),reader_evidence_items=sum(len(s['items'])for s in reader['reader_sections']),source_audit_units=audit['unit_count'],typed_facts=sum(reader['counts'][k]for k in ['typed_characterization_rows','operation_parameter_facts','reagent_quantity_facts','stock_quantity_facts']),source_typed_anchors=audit['typed_anchor_count'],original_assets=len(read(B/'reader-assets/crop-manifest.json')['assets']),original_main_figures=5,original_si_figures=0,canonical_records_total=inv['summary']['canonical_records'],material_hubs_total=len(index['materials']),source_groups_total=inv['summary']['total_canonical_source_groups'],source_documents_unchanged=True,source_generation=2,bundle_sha256=fp['bundle_sha256'],material_urls={h['formula']:d['url'].rstrip('/')+'/'+h['url']for h in hubs},paper_url=d['url'].rstrip('/')+'/paper-review.html?id=sashchiuk2004',si_status='Not located or verified; no SI used. Later SI reopens review.',native_publication_evidence='native-publication.json',browser_checks='browser-qa.json',build_checks='build-validation.json',independent_audit=['source-audit.json','canonical-records-audit.json','reader-source-audit.json','molecular-source-audit.json','crystal-source-audit.json','bindings-source-audit.json','visual-source-audit.json'])
assert p['records']==15 and p['synthesis_routes']==4 and p['dataset_version']=='0.21.0';write(B/'publication-checkpoint.json',p)
ms=read(B/'milestones.json');ms['publish']={'status':'complete','evidence':[str(B/f)for f in ['publication-checkpoint.json','native-publication.json','final-source-fingerprint.json']],'note':'Same existing public MatterSyn Site successfully published. Seven-page supplied main review closed; SI not located/verified. Later changed evidence reopens scope.'};assert all(x['status']=='complete'and x['evidence']for x in ms.values());write(B/'milestones.json',ms)
c=read(B/'checkpoint.json');c.update(website_published=True,checkpoint_at=datetime.now(timezone.utc).isoformat(),public_live_version=p['public_live_version'],dataset_version=p['dataset_version'],publication_evidence=str(B/'publication-checkpoint.json'),current_work_items=[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in ms.items()],next_action='Supplied-main contribution published and closed. Existing heartbeat continues oldest eligible arrival; new or changed evidence reopens this source.');write(B/'checkpoint.json',c)
print(json.dumps({'publication':'succeeded','material_urls':p['material_urls'],'records':p['records'],'milestones':'complete'}))
