from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,subprocess
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas';N='[local path redacted]'
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
checks=['Existing periodic table with Pb + Se selected shows PbSe and four reviewed routes.','Material hub has four equal method cards and method selector.','Heated TOPO operation renders pure liquid, three-neck flask, heat support, argon and150°C/6.0g/90%OR99% labels.','Finite model opens with explicit4.88nm-envelope/4.575nm-atom-span caption; rotation and zoom change view.','Browser revealed an old cached finite renderer; versioned import fixed it and actual screenshot shows distinct Pb/Se colors.','2×2×2 reference lattice switches successfully and retains6.1Å/P1-expanded prototype disclosure.','Figure1 modal opens, zoom/reset/zoomout work, and original SAED panelE is visible.','Selecting90min wire changes active protocol; all-source gallery exposes originalFigures1–5.','Device trimethylsilane molecular modal shows literal-name disclosure,3Dstructure; functional-group toggle and zoom work.','Source-reader TOPO search returns relevant evidence.','No browser console errors observed during material-hub checks.']
write(B/'browser-qa.json',{'status':'passed','at':datetime.now(timezone.utc).isoformat(),'method':'Actual CUA browser interactions and visual screenshots on localhost; no Playwright substitute or inferred UI success.','scope':'Representative desktop discovery, protocol, crystal, original figure, molecule and reader controls. No mobile/200%-text test or deployment-access fetch claimed.','tab_id':'22','checks':checks,'main_url':'http://127.0.0.1:5187/material.html?id=pbse-752487','file_hashes':{n:hashlib.sha256((S/'dist'/n).read_bytes()).hexdigest()for n in ['crystal-viewer.mjs','finite-crystal-reference.mjs','sashchiuk2004-protocol.mjs']}})
r=subprocess.run([N,'--check',str(S/'dist/crystal-viewer.mjs')],capture_output=True,text=True);assert r.returncode==0,r.stderr
p=B/'build-validation.json';d=json.loads(p.read_text(encoding='utf8'));d['results'].append({'command':['node','--check','dist/crystal-viewer.mjs'],'returncode':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'scope':'Final finite-renderer versioned import; no generated data changed.'});write(p,d)
print('Saved actual browser evidence and final changed-module syntax check.')
