from pathlib import Path
from datetime import datetime,timezone
import json
B=Path(__file__).resolve().parent;MON=B.parent.parent
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
reading={'status':'supplied_main_text_and_visual_review_complete','at':datetime.now(timezone.utc).isoformat(),'main_pages_text_read':list(range(1,8)),'main_pages_visually_inspected':list(range(1,8)),'si_pages_text_read':[],'si_pages_visually_inspected':[],'si_status':'SI not located or verified in bounded local search; no SI used. Later SI reopens review.','main_figures':5,'references':67,'original_crops_visually_inspected':13,'critical_boundaries':['Mass ratios are not absolute charges or stock molarity. Caption/body ratios conflict.','Pb-cHxBu exact molecular identity unresolved; butanol isomer unknown; literal trimethylsilane not silently substituted.','Aliquot quench/workup separate from full-batch isolation; microscope/device conditions not synthesis conditions.','Individual particle, spherical assembly and ordered wire specimens retain separate sizes/times and diffraction scope.','Rock-salt ideal model using reported rounded 6.1 Å is not measured coordinates or a training target.','Printed model equations and microeV energy scales preserved with dimensional concerns; transport mechanism unresolved.','No external full cited papers read; references retained as citations.']}
write(B/'root-reading.json',reading)
stages={'read':{'status':'complete','evidence':[str(B/'root-reading.json'),str(B/'source-manifest.json'),str(B/'source-identity.json')],'note':'All seven supplied main pages text-read and visually inspected; duplicate copies reconciled. SI not located/verified.'},'extract':{'status':'partial','evidence':[str(B/'canonical-record-manifest.json')],'note':'15 canonical drafts, four routes, reader and faithful original crops prepared; independent corrections pending.'},'audit':{'status':'partial','evidence':[str(B/'source-audit.json')],'note':'Independent full-page source inventory complete; canonical, reader, molecular, crystal, binding and apparatus audits underway.'},'integrate':{'status':'pending','evidence':[],'note':'Private staging; same existing Site will receive reviewed PbSe hub.'},'publish':{'status':'pending','evidence':[],'note':'Existing MatterSyn version 27 remains live.'}}
write(B/'milestones.json',stages)
write(B/'checkpoint.json',{'paper':'10.1021/nl0345116','title':'PbSe Nanocrystal Assemblies: Synthesis and Structural, Optical, and Electrical Characterization','source_id':'sashchiuk2004','source_generation':2,'review_scope':'supplied_main_only','main_pages_text_reviewed':list(range(1,8)),'main_pages_visually_reviewed':list(range(1,8)),'si_pages_text_reviewed':[],'si_pages_visually_reviewed':[],'si_status':reading['si_status'],'website_published':False,'checkpoint_at':datetime.now(timezone.utc).isoformat(),'current_work_items':[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in stages.items()],'next_action':'Finish independent audits, integrate into existing MatterSyn, validate and publish this paper before starting another.'})
print('Seven-page reading checkpoint saved; SI gap explicit.')
