from pathlib import Path
from datetime import datetime,timezone
import json
B=Path(__file__).resolve().parent;M=B.parents[3]
plan={'saved_at':datetime.now(timezone.utc).isoformat(),'status':'recommendations_saved_not_yet_implemented','user_request':'Consider speeding up the process and explain what the user can do; keep saving memory.','agent_owned_improvements':['Parameterize common extraction/reader/asset/integration validators rather than copy and rename per-paper helper scripts.','Traverse all typed quantities by schema/JSON pointers, including condition options, to generate both reader displays and machine exports.','Keep complete extraction plus independent complete source audit; presentation owner consumes evidence inventory with targeted source/crop inspection instead of a third/fourth redundant full extraction.','Cache rendered pages/crops by source hash, renderer and crop geometry; reuse verified chemistry/structure references with source applicability checks.','Instrument stage elapsed times and recalibrate after a representative20-paper pilot; publication intervals are not isolated active-work durations.'],'user_enablers':['A manifest alongside existing stable files: DOI,parent-paper ID,main/SI role,completion indicator,optional source link and checksum. Preserve original files and arrival order.','Authorize a small three-paper concurrency pilot if desired; this would explicitly supersede prior one-paper-at-a-time scheduling. No such authorization yet.','Choose public batch publication if desired while retaining separate read/extract/audit/integrate/publish states; do not mark pending publications complete.','Keep computer and app/runtime available during desired processing windows; no new software purchases recommended.'],'unchanged_requirements':['Complete supplied-source coverage and main/SI identity checks','Independent scientific audit','Explicit missing values, conflicts and sample provenance','Original figure verification and CdSe-quality presentation','No additional downloads or downloader changes','No unverified exact-coordinate labels'],'throughput_limit':'Three-paper concurrency or batching is not a measured speedup and cannot be promised to handle1000fullyreviewedpapers/day. Need measured optimization before revising ETA.'}
(B/'speed-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
heading='## 2026-09-19 — Speed improvements requested; quality standard retained'
entry=f'''{heading}

User asks what they can do to speed progress. Recommendations saved in research-assets/incoming-paper-monitor/reviews/nl0345116/speed-plan.json. Avoidable agent overhead: per-paper helper recreation, duplicate manual quantitative display mapping, and full extraction-style readings by four roles. Recommended improvement is a shared parameterized toolkit, schema-derived quantitative displays, source-hash caches and a complete extractor+independent auditor workflow with targeted presentation/root review. These changes are proposed, not yet implemented or benchmarked; no speedup factor claimed. Timing estimates reflect the present workflow, not a fixed unavoidable project duration.

User can help through a sidecar intake manifest identifyingDOI/main/SI/parent association/completed downloads while keeping existing files and arrival order stable; computer/app availability; and, if desired, explicit authorization for a three-paper parallel pilot and batched publication. Prior one-paper-at-a-time scheduling remains in force until the user changes it. A20-paper measured pilot should recalibrate stage-level throughput and ETA. Extra tokens already authorized; do not ask for that again or suggest that tokens alone solve the growing backlog. No downloader modifications, extra downloads or purchases authorized by this discussion. CdSe presentation quality, full-source coverage, independent audit and honest missingness stay unchanged.

'''
p=M/'MEMORY.md';t=p.read_text(encoding='utf8');assert heading not in t;p.write_text(entry+t,encoding='utf8')
print('Saved speed recommendations, proposed pilot and unchanged quality/scheduling constraints in memory.')
