from pathlib import Path
from datetime import datetime,timezone
import json
B=Path(__file__).resolve().parent;M=B.parents[3]
data={'saved_at':datetime.now(timezone.utc).isoformat(),'scope':'Existing frozen queue; provisional review scopes are not verified unique papers. New arrivals excluded from completion arithmetic.','snapshot_scan_at':'2026-09-19T18:39:53Z','document_copies_both_folders':13430,'document_copies_incoming':6057,'waiting_scopes_incoming':4972,'waiting_scopes_legacy':4158,'waiting_scopes_both':9130,'recent_publication_intervals_minutes':[64.87,49.07,46.06,39.78,40.06,44.60,57.56],'recent_sample_mean_minutes':48.86,'recent_sample_scope':'Seven consecutive native publication intervals v20 to27; elapsed cadence, not measured uninterrupted active processing time.','conditional_minutes_per_scope':[40,65],'incoming_hours':[3315,5386],'both_hours':[6087,9891],'incoming_continuous_days':[138,224],'both_continuous_days':[254,412],'limitations':['Dedupe and relevance disposition can reduce work; unknown SI and complexity can increase it.','Requires computer/app/runtime availability; do not promise uninterrupted execution.','At1000genuinelynewrelevantpapers/day versus hypothetical22–36deepreviews/day, queue grows964–978/day; no finite catch-up date.'],'phase_linked_route_candidates':19,'phase_somewhere_routes':29,'morphology_linked_route_candidates':30,'measured_coordinate_assets':0,'training_plan_status':'Proposed and saved; new descriptor/prototype-conditioned exports not implemented or validated yet.'}
(B/'training-plan-and-eta.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
heading='## 2026-09-19 — Whole-folder estimate and structure-conditioned training plan'
entry=f'''{heading}

User clarified that completion estimate concerns ALL papers in the folder, and reiterated always saving memory. Standing curation includes both incoming data_Tanjin/papers/50k_all_papers and legacy mattersyn/downloaded_papers; distinguish incoming-only from combined estimates rather than asking another clarification.

Snapshot scanned18:39:53UTC: incoming6,057document copies/4,972waiting provisional review scopes; legacy7,373copies/4,158waiting scopes. Combined13,430copies/9,130waiting scopes plus current paper; unconfirmed duplicates mean these are NOT verified unique-paper counts. Recent seven native publication gaps v20→27 averaged48.86min, range39.78–64.87min. Conditional40–65min/full-review scope gives incoming3,315–5,386hours (~138–224continuous days/~4.5–7.5months), both6,087–9,891hours (~254–412continuous days/~8–14months). These are rough elapsed-cadence scenarios, not validated throughput or calendar promises; downtime increases calendar duration, screening/dedup may decrease scope, complex/missingSI may increase work. At userreported1,000 genuinely new relevant papers/day, hypothetical22–36deepreviews/day cannot catch up. Previous5–8h/paper blanket estimate should not be reused. Evidence saved in research-assets/incoming-paper-monitor/reviews/nl0345116/training-plan-and-eta.json and native publication timestamps of prior reviews.

User asked why dashboard says PbS and zero exact structure–recipe pairs. The100PbSrows are a separately imported benchmark from Voznyy2019 DOI10.1021/acsnano.9b03864 (95optical outcomes +5flagged failures), not the scope of MatterSyn or100reviewed papers. Updated dashboard wording to Imported benchmark experiment rows and Verified sample-coordinate–recipe pairs, with nearby definitions. Current0 is correct under the strict gate: no measured-sample coordinate assets; references/constructedCIFs are not measured samples. Gate also excludes anylistedmissingfield/not_reported precursor-stock-operation value, which is stricter than a task-specific completeness rule.

Proposed training development, NOT yet implemented: (1) composition + audited product phase/morphology/dimensions/architecture → partial recipe, marking conditioning_origin=observed_outcome rather than rewriting author intent; (2) evidence-supported reference prototype + descriptors → recipe with explicit reference_prototype provenance; (3) measured coordinates + experimentally linked recipe when actual source files exist. Separate recipe completeness and uncertainty using task-specific required fields. Among92reviewed routes,29have productphase somewhere and19have it on anexplicitlylinkedproduct;43have morphology/architecture somewhere and30explicitlylinked. These are field availability candidates requiring sample/phase audit, not already verified new training pairs. No measured full nanocrystal geometry, ligand arrangement or defectstructure is implied by bulkCIF. Preserve source/lineage-group splits and avoid mixing samples. Prioritize this as a future dataset improvement alongside the ongoing source-review pipeline; do not silently claim these exports exist.

'''
p=M/'MEMORY.md';t=p.read_text(encoding='utf8');assert heading not in t;p.write_text(entry+t,encoding='utf8')
print('Saved whole-folder timing assumptions, benchmark explanation and proposed training tiers in project memory.')
