import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
A=Path(__file__).resolve().parent;P=A.parent
def load(p):return json.loads(Path(p).read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def save(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
freeze=load(P/'package-freeze.json');checks=load(A/'mechanical-checks-v1.json')
assert sha(P/'package-freeze.json')=='e57825801f343b57b48ff66722a686b9fda045a04baeb71c5d1fc946f75c0151'
assert checks['checks_run']==checks['checks_passed']==4034
addendum={'reviewer':'/root/norberg2004_extract','created_at':datetime.now(timezone.utc).isoformat(),'preserved_original_notes_sha256':sha(A/'independent-reading-notes.json'),'correction_to_reviewer_notes_only':{'main-12':'Bibliography continues through reference47; reference14 also continues from page11.','main-13':'References48–55 occupy the upper part of page13, followed by publisher advertisement/footer. These bibliographic entries have now been reopened and compared to all retained reference entries; the original note incorrectly summarized this page as only advertisement/footer. No extraction error: all55 author references and their source pages are correct.'},'fresh_viewed_paths':[str(A/'audit-pages'/n) for n in ['main-13.png','si-08.png','si-12.png']],'source_files_changed':False,'author_files_changed':False}
save(A/'reading-notes-addendum.json',addendum)
manual=[
 {'scope':'identity-and-pairing','result':'All four copies match generation2 source hashes. 13 main +13 SI pages, topic/byline/title/DOI-context pairing consistent; SI title has an additional The. Source bibliography is cited-only, not a claim to have read its55 articles.'},
 {'scope':'precursor-stock','result':'Cs carbonate407mg/ODE18mL/50mL vessel,120°C1h,OA1.74mL,additional15min and150°C retained. Vacuumstorage and ≥30min preheating separate; final stock volume/concentration not invented.'},
 {'scope':'five-primary-variants','result':'MnCl2 156mg,ODE10mL,OA2mL,OlAm2mL,25mL vessel,120°C1.5h vacuum then Ar injection,2/3/4mL loading alternatives and five explicitly demonstrated sample labels retained. No full3×3factorial or independently known batches asserted.'},
 {'scope':'quench-and-workup','result':'5s growth/external icewater quench,8550rpm5min,discard supernatant and keep precipitate,overnight vacuum drying and unknown hexane volume agree. No unsupported pressure, overnight hour count or centrifuge radius added.'},
 {'scope':'failed-and-alternative-controls','result':'Unisolated air1hdegradation,2mLhexane8600–14000rpm no pellet,IPA OR EtOAc1:2 nonvisiblePL precipitates,MeOAc1:1 and12000rpm successful reported wash are separate contexts. Below150°C formation failure has no invented individual temperatures.'},
 {'scope':'materials','result':'28 materials/5 stocks preserve commercial purity/technical grade, methylacetate conventional distillation and dry-reagent gaps. Chemical reference formulas remain a later separately qualified identity-view task.'},
 {'scope':'xrd-and-tem','result':'Dropcast glass-film XRD settings, native source structure/refinement claims, TEM grid200kV/20µL and absorption2at280nm match. TEM size/scale-bar/SAED contexts remain explicit; no image-scale converted into a particle diameter.'},
 {'scope':'tables','result':'All55rows/321typedfields matched independent pre-author transcription, comprising301printed body cells and20 repeated S2 group metadata fields. Empty TA components and S4 dashes remain null; uncertain S3 values and S5 dimensionless ratio vs printed header remain qualified.'},
 {'scope':'refined-coordinates','result':'SI S1/S2 source values preserved including printed zero Mn/Cl occupancies for150, unusual180//0.7 Wyckoff assignments, .5/.35 shared coordinate values and exchangedCl labels, no200 coordinate block. No validated atomic model/CIF or exact structure-recipe pairing approved.'},
 {'scope':'optical-and-transient-acquisition','result':'Solution spectra/integrating-sphere data,300nm main TA (~150fs;80µW Figure6), distinct445/550nm probes and SI.7 300/370/420nm/600nm context retained. Shared protocol groupings do not establish common physical sample identity or simultaneous settings.'},
 {'scope':'low-temperature-and-width','result':'LTPL silica-film380nm/30–293K20Ksteps,warming sequence distinct from narrative cooling;655/~680/673nm shifts,100±18meV fitted binding,69→52meV293→50K prose values retained. Fact-levelC13 links the source plot≈70K disagreement; quantities must inherit that conflict downstream.'},
 {'scope':'interpretation-and-equations','result':'Eight expressions retained including source lifetime formula inconsistency, modelled HSE06/ZORA/grids/exchange, ligand-field/STE proposals. Model/cited/calculated values are not independent measurements. Only required revision is precise left/right scope in the printed Tauc-axis description.'},
 {'scope':'stability-and-lsc','result':'FilmXRD,hexanePL,agedTEM and LSCglassfilm separate. Main5%55d versus plot endpoint≈.15 remains conflict; source agedcubic phasefit88.1/4.5/7.4% retained as authorfit. LSC geometry/illumination/bias and11week age match; no unreported film thickness/variant or digitized curve points.'},
 {'scope':'figures-and-crops','result':'All30 selected crops actually inspected on8contacts plus native Figure5; source figures/pages read separately. All30 crops are pixel-identical to fresh original-PDF render/crop replay. Eighteen numbered figures +graphical abstract +S2captioncontinuation are distinguished from tables.'},
 {'scope':'inventory-and-missingness','result':'353 unique resolvable inventory units,62facts/186quantities,14scopes/39ops,41contexts,13sourceconflicts/6missingness entries accounted for. Source-only audit does not certify downstream canonical, illustrations, task admission or publication.'}
]
finding={'id':'MATUHINA-SOURCE-01','severity':'bounded_scope_wording','status':'open','source':'SI PDFpage8,FigureS4b','path':'source-facts.json#/equations/7 (resolve by id tauc-axes)','current_text':'(alpha*h*nu)^2; units printed with exponent1/2','source_evidence':'Both ordinates print (αhν)^2. Left unit is (eV cm−1)^2; right unit is (eV cm−1)^(1/2).','requested_change':'Preserve v1 and distinguish both source axes explicitly; keep the right-axis inconsistency as printed. No numerical quantities, formulas from other equations, table cells, models, source or crop changes.'}
bound=dict(freeze['bound_files']);bound[str(P/'package-freeze.json')]=sha(P/'package-freeze.json')
for name in ['check_extraction.py','mechanical-checks-v1.json','independent-reading-notes.json','independent-reading-notes.md','independent-table-transcription.json','lifetime-equation-crosscheck.json','reading-inputs.json','reading-notes-addendum.json',Path(__file__).name]:bound[str(A/name)]=sha(A/name)
for folder in ['audit-pages','audit-text-normal']:
 for f in sorted((A/folder).glob('*')):
  if f.is_file():bound[str(f)]=sha(f)
report={'schema':'mattersyn-independent-source-audit/1','reviewer':'/root/norberg2004_extract','author':'/root/backlog_eta','source_id':'matuhina2023','doi':'10.1021/acsanm.2c04342','created_at':datetime.now(timezone.utc).isoformat(),'status':'open_findings','source_package_freeze_sha256':sha(P/'package-freeze.json'),'source_revision':1,'counts':freeze['counts'],'manual_reading_scope':{'main_pages':13,'si_pages':13,'all_supplied_pages_actually_read_and_viewed':True,'independent_table_transcription_before_author_package_opened':True,'selected_crops_actually_viewed':30,'crop_pixel_replays':30,'manual_scopes':len(manual)},'manual_scopes':manual,'mechanical_checks':{'path':str(A/'mechanical-checks-v1.json'),'sha256':sha(A/'mechanical-checks-v1.json'),'run':4034,'passed':4034,'author_checks_not_counted':True},'findings':[finding],'open_findings':[finding['id']],'numeric_or_sample_corrections_required':False,'bound_files':bound,'scope_exclusions':['No source modification','No external cited-paper reading asserted','No canonical/reader/illustration/browser approval','No verified atomic-model, exact structure-recipe pair or training eligibility','No Site integration or publication approval']}
save(A/'independent-audit-v1.json',report)
(A/'independent-audit-v1.md').write_text('# Matuhina2023 independent source audit — revision1\n\nStatus: one bounded wording finding; all numerical, sample, table and crop checks passed.\n\nRead and viewed all13main+13SI pages independently, compared all321typed table fields (301printed bodycells+20groupmetadata), checked all62facts/186quantities/39operations, and inspected/replayed all30selectedcrops. All4,034 independent supporting checks passed.\n\nMATUHINA-SOURCE-01: SI FigureS4b left-axis unit exponent is2; only the right-axis unit is1/2. The extracted Tauc-axis wording must preserve that distinction without repairing the printed source. No number or asset change is requested.\n\nThe reviewer’s original page13 summary was corrected in a separate preserved addendum; references48–55 are on page13 and the author correctly retained all55references.\n\nNo canonical, atomic-model, training, browser, or publication approval is implied.\n',encoding='utf-8')
print(sha(A/'independent-audit-v1.json'))
