import json,hashlib,datetime
from pathlib import Path
O=Path(__file__).resolve().parent;L=O.parent;S=Path('[local path redacted]')
def rd(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
a=rd(O/'actual-integration-checks.json');b=rd(O/'actual-dispatch-checks.json')
assert a['status']==b['status']=='passed'
bound=a['bound_files']|b['bound_files']
for p in [O/'check_actual_integration.py',O/'check_actual_dispatch.mjs',O/'actual-integration-checks.json',O/'actual-dispatch-checks.json',L/'import_reviewed_lian.py',O/'freeze_transport_audit.py']:bound[str(p)]=sha(p)
assert all(sha(p)==h for p,h in bound.items()),'An inspected file changed; recheck before freezing.'
manual=[
 {'scope':'Promotion and previous-record preservation','result':'The actual 16 canonical files and generated copies are byte-identical to the passed promotion. All original 530 canonical and generated record bytes remain unchanged. The 546-record manifest uses dataset_lib normalized object digests, checked separately from raw file hashes.'},
 {'scope':'Reader and public source assets','result':'The actual reader has only the four declared integration metadata additions/changes; the generated reader adds the approved scope label. The 53 selected crops, 27 chemical files and apparatus module match the approved asset allowlist. Local links on all 16 generated record pages resolve.'},
 {'scope':'Chemical and stock dispatch','result':'The actual shared registries equal the old base plus the precise approved additions. All 45 material slots dispatch to the qualified identities and source-specific captions; all quantity/context pointers used by these captions still equal the actual canonical fields. Five stock contexts preserve all14 components and their whole-charge/aliquot qualifiers. Previous shared entries remain unchanged.'},
 {'scope':'Apparatus integration','result':'The actual shared protocol renderer mounts all21 Lian operations with exactly122 source-specific display rows, authoritative source captions and enlargement controls. All1740 previous-source operations reject the Lian scene selector. Bulk A/B, NC, composite-film, spin-coated film and theoretical operation boundaries remain those of the audited module.'},
 {'scope':'Measurement and symbolic-product scopes','result':'Structural/property measurement maps are exact record-keyed additions; no old source classification changes. The22 symbolic product contexts are transported exactly from their independently passed proposal; unspecified and incompatible contexts are not newly associated.'},
 {'scope':'Readable specimen notes','result':'The builder hides only one precisely matching superseded visual-status note for Lian. Source sample JSON is rendered as escaped labelled details; all other source notes keep their former output. The frozen canonical text is untouched. An explicit script-tag escaping check passed.'},
 {'scope':'Root bulk insertion, transport only','result':'Five bulk assets match the separately root-audited freeze byte for byte; the sixth viewer module differs only by the separately declared root mobile camera ternary. The shared crystal renderer has exactly two insertions: import and a scoped mounting branch after existing identity cards. Its generic missing-coordinate note is replaced only for three explicit Lian records by a partial non-H/source-batch caveat. The authored bulk model/viewer science was not independently audited by this author; approval relies on the separate root coordinate-math and binding audits.'},
 {'scope':'Root mobile presentation delta','result':'The saved unsynced public CSS baseline differs only by the source-digest wrapping rule and the <=620px record-page bulk-view sizing rule. The root-only camera edit sets initial ASU zoom1.0 below400px, retaining1.45 otherwise and .95 for expansion. The import adds only v=0.27.0-r2 to request this current module. Exact text replacements and hash chains pass; source geometry, scientific fields, selection gates and the frozen author module remain unchanged. Actual mobile visual quality remains root browser QA.'},
 {'scope':'Training and release boundaries','result':'All16 actual eligibility objects remain false; none of the six training exports contains Lian records. No complete structure, exact recipe pair, training or public-release gate is approved by this integration audit.'}
]
report={'schema':'mattersyn.independent_integration_transport_audit.v1','source_id':'lian2021','auditor':'/root/peng1998_reader_assets','implementation_author':'/root','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'passed','scope':'Independent root integration transport/code audit; excludes this auditor’s authored bulk-viewer/model science and final integrated browser/publication approval','open_findings':[],'check_count':a['check_count']+b['check_count'],'counts':{'previous_records_preserved':530,'new_records':16,'total_records':546,'source_crops':53,'chemical_public_assets':27,'apparatus_operations':21,'apparatus_display_rows':122,'material_slots':45,'stock_contexts':5,'stock_components':14,'symbolic_product_contexts':22,'bulk_asset_transport_files':6,'new_training_rows':0},'proposal_freeze_sha256':sha(L/'site-integration-proposal/v1/package-freeze.json'),'bulk_adapter_status':'transport/code delta passed; distinct root science proofs retained','distinct_bulk_science_proofs':{name:sha(L/'visuals/bulk-structure-independent-audit'/name) for name in ['coordinate-math-audit.json','binding-audit.json']},'manual_scopes':manual,'initial_snapshot_resolution':'The initial checker snapshot preceded the root bulk insertion metadata and treated two generated HTML pages as cache-token-only files. The final check uses the preserved sequential pre-bulk files, declared root insertions and verified generated Lian count/content additions. No scientific correction was required.','bound_files':bound,'site_modified':False,'canonical_modified':False,'bulk_science_self_approval':False,'integrated_browser_approved':False,'publication_approved':False,'training_approved':False}
p=O/'integration-transport-audit.json';assert not p.exists(),'Preserve the existing audit and version updates.'
p.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
md='# Lian integration transport/code audit\n\nPassed within this bounded independent scope. '+str(report['check_count'])+' mechanical checks and '+str(len(manual))+' manual code/transport scopes are bound to the inspected files. No open finding.\n\n'
md+='The actual Site has 546 records: all530 earlier record bytes are preserved and all16 Lian records match the approved promotion. All source/canonical quantities and task gates are unchanged.\n\n'
for item in manual:md+='## '+item['scope']+'\n\n'+item['result']+'\n\n'
md+='The bulk model and viewer were authored by this auditor and are expressly excluded from self-approval. Their exact asset transport and the root-authored mounting/placeholder delta were reviewed here; coordinate and binding science depend on the distinct root reports named in the JSON. Root owns mounted-browser and release verification.\n'
(O/'integration-transport-audit.md').write_text(md,encoding='utf-8')
print(json.dumps({'status':'passed','audit_sha256':sha(p),'checks':report['check_count'],'bound_files':len(bound),'manual_scopes':len(manual)},indent=2))
