"""Faithful original PDF crops. No redrawing, inferred spectra or digitization."""
import json,hashlib,math
from pathlib import Path
import pypdfium2 as pdfium
from PIL import Image,ImageDraw,ImageFont
OUT=Path(__file__).resolve().parent
SOURCE=Path('[local path redacted]')
EXPECTED='dac183303049a3275d4f1874c66ac0ceece9895bc175f7f7e9727ef7c9cd8f9d'
DPI=300
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert sha(SOURCE)==EXPECTED
S=[]
def add(id,page,box,title,caption,scope,kind='figure',evidence='experimental',notes=None,panels=None):
 S.append(dict(id=id,pdf_page=page,box=box,title=title,caption_paraphrase=caption,sample_scope=scope,type=kind,evidence_type=evidence,scope_caveats=notes or [],panels=panels or []))
MAIN='Main shell-coverage series grown on a divided preparation of approximately 40 Å CdSe cores. The captions often call the core 42 Å ±10% (SAXS), whereas Table 1 reports the bare TEM major dimension as 39 Å ±8.2%. This is not a unique batch identifier or an exact recipe-to-each-trace assignment.'
SERIES='a=bare TOPO/TOP-capped CdSe; b=0.65, c=1.3, d=2.6, e=5.3 monolayers ZnS. The paper defines one monolayer as 3.1 Å along the major axis; shell coverage is TEM-derived, not an exact delivered precursor amount.'
SAXS='Separate dilute-hexane solution-SAXS series: a=bare 42 Å dots; b Zn/Cd=0.42, c=0.85, d=3.1, e=5.3 in Figure 11 caption. The text explicitly excludes direct comparison with the other measurements in Table 1. A p8 body sentence prints 5.6 for e; this unresolved conflict is retained.'
add('figure-01',3,[609,67,1090,578],'Absorption across the CdSe core-size series','Absorption before and after adding approximately 1–2 ZnS monolayers to four CdSe core sizes.','a=23 Å, b=42 Å, c=48 Å, d=55 Å core diameter. These are a size series, distinct from the main coverage sweep.',notes=['Dashed traces are bare organically capped dots; solid traces are overcoated dots.','The core-size-dependent shelling temperatures are in note 22; that note names 40 Å, not a separate 42 Å temperature. No exact dose or run time for each trace is given.'])
add('figure-02',3,[609,592,1090,1122],'PL across the CdSe core-size series','PL of the same four size-series samples before and after ZnS overcoating.','a=23 Å, b=42 Å, c=48 Å, d=55 Å core diameter; caption quantum yields a40%, b50%, c35%, d30%.',notes=['The source has an original ×10 annotation near the smallest bare-dot trace; preserve scaling.','These are ensemble spectra, not emission from individual dots.'])
add('figure-03',4,[99,66,1091,658],'Six original fluorescent sample cuvettes','Photograph of six dilute hexane samples irradiated at 365 nm.','Left to right reported PL peaks:470,480,520,560,594,620 nm. The source does not assign an exact core size, shell thickness or recipe to each cuvette.',evidence='experimental_photograph',notes=['The caption calls this a color photograph, but the supplied PDF contains a grayscale image. The crop faithfully retains that grayscale appearance; no color is reconstructed.','Photography credit F. Frankel is retained in the original caption.'])
add('figure-04',4,[609,668,1091,1277],'Absorption versus ZnS shell coverage','Long-wavelength and UV parts of absorption spectra for the main shell-coverage series.',MAIN+' '+SERIES,notes=['Both horizontal scales and different absorptivity axes remain together.','The caption gives 42 Å±10% seed size, a SAXS convention distinct from the TEM major dimensions in Table1.'])
add('table-01',5,[99,66,1091,271],'Measured and fitted structural summary','Table compares TEM size/aspect ratio, WDS composition and SAXS/WAXS fit results for the main coverage series.',MAIN+' '+SERIES,kind='table',evidence='mixed_measurement_and_fit',notes=['TEM size is the longest particle dimension (major axis), not an isotropic diameter or separately measured core diameter.','SAXS sizes and SAXS/WAXS Zn/Cd columns are calculated/fitted, whereas TEM and WDS columns are measured.','Blank cells are unreported, never zero. The two thicker-shell SAXS patterns were not confidently fitted.'])
add('figure-05',5,[99,282,578,849],'PL and quantum yield versus shell coverage','PL spectra and inset quantum-yield trend for the main coverage series.',MAIN+' '+SERIES,notes=['Inset line is only a guide to the eye.','Reported bare QY15%, maximum50% at~1.3ML and~30% near5ML; this is not a universal quantum-yield-versus-thickness law.','Original axes identify rhodamine590 reference.'])
add('figure-06',5,[609,282,1091,899],'XPS survey and low-binding-energy enlargement','Survey and enlarged low-energy spectra of bare CdSe and ZnS-overcoated dots.',MAIN+' a=bare; b=approximately1.3ML ZnS from body text.',notes=['A and B are views of the same survey comparison; not distinct synthesis experiments.','Photoelectron and Auger features both appear. C/O are attributed mainly to brief air exposure; residual P remains after pyridine exchange.'])
add('figure-07',6,[99,66,578,663],'XPS selenium oxidation comparison','Se3d-region spectra showing an oxide contribution at59eV after exposure to air.','Approximately40Å core samples: a=bare, b=0.65ML, c=1.3ML, d=2.6ML. The body identifies80h exposure for this comparison.',notes=['This is an air-exposure/passivation comparison, not an as-synthesized absorption spectrum.','SeO2 signal present in bare/0.65ML; no visible oxide peak for sufficiently coated specimens does not prove a uniquely resolved atomic shell.'])
add('figure-08',6,[609,66,1091,359],'Two lattice-resolved TEM particles','Individual bare CdSe and2.6ML ZnS-overcoated CdSe particles.','A=one bare CdSe crystallite; B=one crystallite with2.6ML ZnS from the main coverage family.',evidence='experimental_hrtem',notes=['Original shared50Å scale bar retained.','The source explicitly says no well-defined core/shell interface is seen. Slight fringe bending in B is anomalous relative to most particles; do not promote it to a universal shape or defect observation.','No SAED image is present in this paper.'])
add('equation-01',6,[609,377,1091,643],'Depth dependence of XPS and Auger intensity','Equation1 with immediate definitions for flux, atom count, cross section, emission yield, instrument response and electron escape depth.','Analytical XPS/Auger interpretation model, not a measured specimen image.',kind='equation',evidence='analytical_model',notes=['Original formula and definition text are retained; no numerical fitting or new derivation is supplied.'])
add('figure-09',7,[99,65,578,774],'TEM major-axis and aspect-ratio distributions','Histograms across the five main coverage levels.',MAIN+' '+SERIES,notes=['PanelA measures the longest dimension for over150particles in each sample; panelB uses a subset for major/minor-axis ratios.','Histogram bars are original data representation; no coordinates or counts are digitized.'])
add('equation-02',7,[609,189,1091,483],'Discrete Debye scattering expression','Equation2 and definitions used to simulate SAXS and WAXS patterns.','Model framework; atom positions are systematically generated in assumed wurtzite ellipsoids constrained by TEM, not experimentally refined atomic coordinates.',kind='equation',evidence='analytical_model',notes=['PDFium preserves the summation glyph that Poppler rendered incorrectly.','Model core size/distribution fixed while shell distributions are varied; fitted atomic positions must not become measured structural training labels.'])
add('figure-10',8,[99,65,578,668],'Polymer-film SAXS measurements and fitted curves','SAXS of bare and ZnS-overcoated particles embedded in polymer, with fits for low coverage.',MAIN+' '+SERIES,evidence='experimental_scattering_plus_model_fit',notes=['Symbols are experimental; lines are Debye-model fits. Only a–c carry confidently fitted structure.','PVB and MTD300P20 preparations are described; caption alone does not identify which polymer corresponds to every trace.','Low-angle region below~2.5° is unreliable for fitting because of aggregation.'])
add('figure-11',8,[609,65,1091,543],'Separate solution-SAXS series','Background-subtracted intensity from different Zn/Cd ratios at comparable particle number concentrations in hexane.',SAXS,notes=['Do not equate b/c/d/e with the same-letter Table1 specimens.','No shell-monolayer assignment is supplied for these composition ratios.'])
add('equation-03',8,[99,978,578,1220],'Zero-angle scattering intensity and radius dependence','Equation3 and definitions connect total contrast, particle count, specific volume and sixth-power size dependence.','Analytical solution-SAXS relation used for approximate size analysis.',kind='equation',evidence='analytical_model',notes=['The approximation is subject to comparable particle number and contrast assumptions; not a calibrated experimental size law for every specimen.','The later text estimates10–15% size error from treating CdSe and ZnS as a single electron density.'])
add('formula-guinier-context',8,[99,1215,578,1415],'Guinier relation as printed','Unnumbered intensity, form-factor and Guinier expressions embedded in their explanatory text.','Context for the separate solution-SAXS series.',kind='unnumbered_formula_context',evidence='analytical_model',notes=['The source prints exp(−q²RG²/5) and calls RG the Guinier radius for spherical particles. Preserve literally; do not silently substitute a conventional formula or redefine its symbol.'])
add('figure-12',9,[99,65,578,988],'Guinier and Porod analyses of solution SAXS','Two plotting transformations of the Figure11 data, including fit curves.',SAXS,evidence='experimental_transformation_plus_model_fit',notes=['Caption lists σ(a)=0.11,b=0.14,c=0.16,d=0.25, while p9 body gives bare σ≈0.12 and states high-coverage averages/variance cannot be meaningfully extracted. Retain this tension.','For high coverage the discussion estimates the upper size in the distribution, not an average particle radius.','Inset is a restricted q-range of the same specimens, not an extra sample.'])
add('figure-13',9,[609,65,1091,812],'WAXS measurements, simulations and bulk references','Experimental patterns and ellipsoidal-model fits for the main coverage series with bulk wurtzite CdSe and ZnS reference-line panels.',MAIN+' '+SERIES,evidence='experimental_scattering_plus_simulation_and_bulk_references',notes=['Experimental circles, calculated solid curves and pure bulk reference sticks are different evidence types.','At high coverage fits require bulk aCdSe=4.29Å and aZnS=3.82Å; low-coverage data are insensitive to shell lattice parameter. These are model-fit choices, not a deposited sample CIF.','The source discusses locally epitaxial growth, strain, stacking faults and incoherence; do not show a universally perfect coherent shell.'])
add('formula-radius-context',9,[609,829,1091,1292],'Upper-size inference and electron-density approximation','Unnumbered radius-scaling relation with its extrapolation and density limitations.','Separate solution-SAXS series; high-coverage upper distribution size, not population mean.',kind='unnumbered_formula_context',evidence='analytical_model',notes=['Single-electron-density treatment explicitly acknowledged as incorrect; estimated size error10–15%.','Source densities:CdSe≈2.92e/Å³,ZnS≈2.35e/Å³.'])
add('equation-04',10,[609,1190,1091,1503],'Wave-function continuity boundary condition','Equation4 with the model assumptions and interface context.','Spherical concentric core/shell model without interfacial alloying; not a structural measurement.',kind='equation',evidence='theoretical_electronic_model',notes=['Assumed ZnS barrier0.9eV; organic-matrix barriers4eV electron/10eV hole are fitting parameters and must not be transferred as measured material properties.','Definitions continue with equation5 on the following page.'])
add('figure-14',11,[99,65,578,747],'Calculated radial probabilities and band-offset sketches','Modeled electron/hole probability profiles for bare CdSe, ZnS-coated and CdS-coated dots, with conceptual potential diagrams.','Model comparison only; 4Å shell in coated cases.',evidence='theoretical_model_plot_and_diagram',notes=['Caption says20Å diameter while p11body and radial axis use20Å radius. Do not resolve the conflict by silently changing the caption.','Curves are calculated probabilities, not microscopy or measured electron-density maps.','No atomic coordinates, crystalline shell thickness measurements or measured band offsets are supplied by this figure.'])
add('equation-05',11,[99,755,578,962],'Probability-current continuity boundary condition','Equation5 and definitions of radial functions, core radius, effective masses and wavevectors.','Companion to equation4 in the simplified effective-mass model.',kind='equation',evidence='theoretical_electronic_model',notes=['Bulk effective masses and spherical geometry are modeling assumptions; this is not an experimentally solved wavefunction.'])
add('figure-15',11,[609,65,1091,647],'ZnS-induced absorption and PL energy shifts','Experimental absorption/PL shifts plotted against ZnS shell thickness, alongside calculated curves.','Approximately20Å-radius CdSe core ZnS-coverage study; body links this to the main~40Å-core series.',evidence='experimental_points_plus_theoretical_curves',notes=['Solid circles=experimental absorption; squares=experimentalPL; solid/dashed curves=calculated shifts.','PL excitation450nm. Model barriers4/10eV are fit parameters; source warns against literal interpretation.','No graph coordinates are digitized.'])
add('figure-16',12,[99,65,578,554],'CdS-induced absorption energy shifts','Measured and calculated shifts versus CdS shell thickness for the CdS-overgrowth comparison.','Separate CdSe/CdS comparison, not the ZnS-coverage series.',evidence='experimental_points_plus_theoretical_curve',notes=['Caption and p12body identify~16Å-radius cores, methods give33.5–35Ådiameter; p11body instead prints~30Åradius. Preserve unresolved source conflict.','Error bars indicate the TEM size distribution, not repeated-measurement standard error of energy.','Caption associates4/10eV barriers with surroundingCdS, whereas discussion assigns these to organicmatrix and gives CdS barriers0.2/0.55eV. Preserve the conflict.'])
add('source-note-22',13,[609,526,1091,600],'Source note22: size-dependent shelling temperatures','Original numbered note specifying six core-size/temperature choices.','Recipe-family context:23Å→140°C,30Å→140°C,35Å→160°C,40Å→180°C,48Å→200°C,55Å→220°C.',kind='source_note',evidence='reported_process_condition',notes=['This is a source-text excerpt, not an additional figure, table or synthesized batch.','Note does not enumerate a42Å temperature or exact precursor amounts.'])

# Refined against original text-line boundaries after first crop review.
for s in S:
 if s['id']=='equation-01':s['box']=[609,472,1091,924]
 if s['id']=='equation-02':s['box']=[609,198,1091,603]
 if s['id']=='equation-03':s['box']=[99,1030,578,1415]
 if s['id']=='formula-guinier-context':s['box']=[99,1084,578,1415]
 if s['id']=='formula-radius-context':s['box']=[609,828,1091,1390]
 if s['id']=='source-note-22':s['box']=[609,531,1091,598]
doc=pdfium.PdfDocument(SOURCE)
renders={}
for page in sorted({s['pdf_page'] for s in S}):
 im=doc[page-1].render(scale=DPI/72).to_pil().convert('RGB');renders[page]=im
 im.save(OUT/'source-render'/f'pdfium-{page:02d}-300dpi.png')
assets=[]
for s in S:
 normalized=[s['box'][0]/1190,s['box'][1]/1540,s['box'][2]/1190,s['box'][3]/1540]
 im=renders[s['pdf_page']]
 bbox=[round(normalized[i]*(im.width if i%2==0 else im.height)) for i in range(4)]
 cropped=im.crop(bbox);dest=OUT/(s['id']+'.png');cropped.save(dest)
 pwidth,pheight=doc[s['pdf_page']-1].get_size()
 s.update(source_doi='10.1021/jp971091y',source_file=SOURCE.name,source_path=str(SOURCE),source_sha256=EXPECTED,
  printed_page=9462+s['pdf_page'],relative_asset=dest.name,sha256=sha(dest),dpi=DPI,pixel_dimensions=list(cropped.size),
  crop_normalized=normalized,bbox_pixels_at_140dpi=s.pop('box'),bbox_pdf_points_top_left=[normalized[i]*(pwidth if i%2==0 else pheight) for i in range(4)],
  original_source_asset=True,synthetic=False,digitized=False,eligible_training=False,experimental_sample_cif=False,
  original_caption_preserved=s['type'] in ['figure','table'],visually_reviewed=False,
  renderer='PDFium via pypdfium2; original PDF page rasterized and cropped without redrawing',
  render_notes='PDFium chosen after side-by-side checks showed faithful degree, summation, infinity and approximation glyphs; initial Poppler renders substituted some unembedded Symbol glyphs.')
 assets.append(s)
manifest={'source_doi':'10.1021/jp971091y','source_title':'(CdSe)ZnS Core-Shell Quantum Dots: Synthesis and Characterization of a Size Series of Highly Luminescent Nanocrystallites','source_sha256':EXPECTED,'source_file':SOURCE.name,'source_page_count':13,
 'coverage':{'all_source_pages_text_read':True,'all_source_pages_visually_reviewed':True,'numbered_figures':16,'numbered_tables':1,'numbered_equations':5,'supplementary_context_crops':3,'schemes':0,'saed_images':0,'raman_figures':0,'crop_count':len(assets),'individual_crops_visually_reviewed':False},
 'scope':'All numbered source figures/table/equations plus the two long unnumbered solution-SAXS formula contexts and process note22. Other inline variable definitions remain in source text. No supplementary document was reviewed or claimed here.',
 'source_pages':[{'pdf_page':n,'text_read':True,'visual_review':True,'contains_numbered_assets':n in {3,4,5,6,7,8,9,10,11,12}} for n in range(1,14)],
 'assets':assets,'global_limits':['Every asset is a faithful excerpt of the supplied main PDF; crops do not establish an exact experiment or a measured crystal structure.','No synthetic color reconstruction, spectrum redrawing or point digitization.','Model-only and model-fitted information is explicitly distinguished from direct measurements.','Figure3 is grayscale in this source although its caption describes a color photograph.']}
dump(OUT/'manifest.json',manifest)
font=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',22)
for n in range(math.ceil(len(assets)/4)):
 batch=assets[n*4:n*4+4];sheet=Image.new('RGB',(1800,1600),'#eeeeee');draw=ImageDraw.Draw(sheet)
 for k,a in enumerate(batch):
  x=(k%2)*900;y=(k//2)*800;im=Image.open(OUT/a['relative_asset']).convert('RGB');im.thumbnail((878,752))
  draw.text((x+12,y+8),a['id']+' — PDF p'+str(a['pdf_page']),font=font,fill='black');sheet.paste(im,(x+11,y+40))
 sheet.save(OUT/f'contact-{n+1:02d}.png')
print(json.dumps({'count':len(assets),'manifest':str(OUT/'manifest.json'),'types':{t:sum(x['type']==t for x in assets) for t in sorted({x['type'] for x in assets})}}))
