from pathlib import Path
import json,hashlib,shutil
A=Path(__file__).resolve().parent; N=A.parents[1]; C=N/'canonical-proposal/v2'; M=N.parents[4]
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(A/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert not (A/'package-freeze.json').exists(),'Frozen packages are immutable'
manifest=read(C/'record-manifest.json'); records=[]
for x in manifest['records']:
 p=Path(x['path']); assert sha(p)==x['sha256']; r=read(p)
 if r['operations']:records.append(r)
configs={}
def scene(oid,title,art,prose,notes=(),**kw):configs[oid]={'title':title,'art':art,'prose':prose,'notes':[{'label':k,'value':v} for k,v in notes],**kw}
scene('mw-dissolve','Microwave synthesis · dissolve nitrate hydrates','dissolve','Dissolve zinc nitrate hexahydrate and aluminum nitrate nonahydrate in demineralized water. The water amount is a charge, not a verified final stock volume.',[('Formulation','Zn:Al = 1:2; hydrate identities remain explicit.'),('Missing conditions','Mixing duration and temperature are not reported.')],variant='Demineralized water')
scene('mw-base','Microwave synthesis · separate base formulations','base-alternatives','Prepare three separate NaOH-adjusted precursor mixtures. These are alternative formulations, not successive additions to one batch.',[('Final NaOH concentrations','1.5, 1.7 or 2.0 M in separate mixtures.'),('Missing quantities','NaOH masses and final mixture volumes are not reported.')])
scene('mw-load','Microwave synthesis · load quartz vessel','mw-load','Transfer one precursor aliquot into the thick-walled quartz reaction vessel in the Anton Paar Multiwave 3000. Pressure and temperature sensing uses a sapphire immersion tube.',[('Aliquot basis','The transfer is 10 mL of prepared formulation, not the entire water charge.'),('Equipment','Reported quartz vessel and sapphire sensor tube; drawing is schematic.')])
scene('mw-heat','Microwave synthesis · sample-specific heating','microwave','Apply the source heating profile and the separately reported Table 1 sample conditions. Profile 1 is used for M1–M3 and M7–M9; profile 2 only for M4–M6.',[('Distinct samples','Every M row is a separate condition context; never apply all schedules in sequence.'),('Source discrepancy','Printed ramp durations do not reconcile with Table 1 total-minus-dwell times. Both are retained.'),('Unreported','Microwave power and full measured heating traces; SI settings are unverified.')],include_options=True)
scene('acs-load','Autoclave synthesis · load lined vessel','autoclave-load','Fill a Teflon-lined stainless-steel autoclave with the precursor solution described for laboratory synthesis.',[('Separate reactor','Autoclave preparation inherits the described feed formulation; it does not inherit microwave pressure.'),('Unreported','Pressure and closure details.')])
scene('acs-heat','Autoclave synthesis · thermal treatment','autoclave-heat','Heat the autoclave to the reported set point for the selected short or long synthesis. The heating-time estimate is an assumption based on cited prior work.',[('Duration discrepancy','Methods give 1 day or 2.5 weeks; Table 1 gives 1 day or 17 days. These are not silently equated.'),('Heating estimate','Approximately 45–60 min to the set point is assumed, not a measured heating trace.'),('Unreported','Pressure, cooling protocol and heating-device type.')],include_options=True)
scene('scf-feed','Supercritical flow · separate feed streams','flow-feed','Supply solvent and precursor streams at their separately stated flow rates to the cited in-house reactor. The main paper does not reproduce a fully quantified upstream feed formulation.',[('Composition scope','Reported OH concentration is 0.18 M; Zn:Al:OH = 1:2:7.'),('Missing preparation','Full feed formulation, solvent grade and reactor dimensions are unreported in the supplied main.'),('Cited apparatus','The earlier reactor articles have not been read.')])
scene('scf-react','Supercritical flow · reaction conditions','flow-react','React the flowing precursor at the source pressure and the selected sample-specific temperature. The illustration does not establish a reactor residence-time distribution.',[('Temperature discrepancy','Methods say 450 °C for each synthesis; S2 is 380 °C in Table 1 and Results.'),('Time basis','Table 1 approximate total times and zero dwell are retained as printed; no inferred residence time.'),('Unreported','Collection protocol, quench details and reactor geometry.')],include_options=True)
scene('insitu-stock','In situ nitrate study · prepare stock','dissolve','Prepare the concentrated aqueous nitrate stock from the reported hydrate masses to the reported solution volume.',[('Volume basis','30.0 mL is the stated solution volume; no specific water charge is inferred.'),('Distinct stock','This concentrated in situ stock is not the microwave stock.')],variant='Water-based stock')
scene('insitu-mix','In situ nitrate study · mix aliquots','aliquots','Mix one nitrate-stock aliquot with one aqueous NaOH-solution aliquot for each separately defined concentration context.',[('Mixed-reaction basis','0.480 M Zn and 0.960 M Al describe the final mixture; they are not NaOH-stock concentrations.'),('Source ambiguity','The basis of Table 1 NaOH concentrations remains unresolved.'),('Zero-base context','The diluent details for zero-base specimens are unreported.')])
scene('insitu-stir-load','In situ nitrate study · stir and load capillary','stir-capillary','Vigorously stir the resultant slurry, then inject it into a single-crystal sapphire capillary for the in situ experiment.',[('Order','Stir first, then load; the transfer device shape is illustrative.'),('Unreported','Injected volume, pressure and complete acquisition settings.')])
scene('insitu-heat','In situ nitrate study · heat and measure','capillary-heat','Follow the selected nitrate specimen during heating and X-ray diffraction. Each I-series row describes a separate experimental context.',[('I1/I2 only','The change to 430 °C after approximately 34 min applies only to I1/I2.'),('Time discrepancy','Figure 6 axis seconds versus caption/prose minutes remains unresolved.'),('Analysis limits','I3 turbulence prevents quantitative fitting; I12/I13 low yield is not evidence of low crystallinity.'),('Unreported','Complete pressure, exposure and heating schedules; SI remains unverified.')],include_options=True)
scene('oxide-slurry','In situ oxide study · prepare suspension','oxide-slurry','Mix nanosized ZnO and Al(OH)3 in Millipore water, then stir for the stated duration. This is the separate precursor route for I15/I16.',[('Concentration basis','Final Zn and Al concentrations are stated; the water volume is not.'),('Solid precursors','Reported ZnO precursor size is distinct from the product crystallite size.')])
scene('oxide-load','In situ oxide study · load suspension','capillary-load','Inject the stirred suspension into the sapphire capillary. This is distinct from the nitrate-stock preparation.',[('Sample scope','Only I15 and I16 use this oxide/hydroxide preparation.'),('Unreported','Injected volume and complete pressure/acquisition setup.')])
scene('oxide-heat','In situ oxide study · separate thermal experiments','capillary-heat','Follow conversion at the separate Table 1 temperatures for I15 and I16. They are alternative specimens, not one two-temperature sequence.',[('Separate specimens','I15: 425 °C; I16: 400 °C.'),('Unreported','Exact completion times, pressure and full thermal histories.')],include_options=True)
scene('insitu-fit','In situ diffraction · constrained refinement','analysis','Sequentially refine the in situ diffraction data using Fullprof. The paper constrains stoichiometry and defect parameters and reports limitations in displacement parameters.',[('Model boundary','Refined defect hypotheses and size results do not supply a complete measured atomic structure.'),('Limits','Low q range, high background, poor signal-to-noise and high synthesis temperature affect refinement.'),('Unavailable','Detailed SI Table S7 results.')],variant='Sequential Fullprof refinement')
scene('lab-separate','Laboratory workup · isolate separate powders','centrifuge','Separate each synthesis powder from its supernatant by centrifugation until the solution appears colorless. Microwave, autoclave and flow products are treated separately.',[('Retained fraction','Each route’s powder is retained; crude products are not pooled.'),('Endpoint','Solution appears colorless.'),('Unreported','Centrifugation speed, duration and repetition count.')])
scene('lab-wash','Laboratory workup · sequential washing','wash','Wash each retained powder three times with demineralized water, then once with 96% ethanol.',[('Order','Water washes precede the ethanol wash.'),('Retained fraction','Each washed powder remains separate; wash supernatants are separated.'),('Unreported','Wash volumes and separation settings.')])
scene('lab-dry','Laboratory workup · vacuum drying','vacuum-oven','Dry each washed powder in the reported Thermo Scientific Heraeus vacuum oven at the stated temperature and duration.',[('Atmosphere','Vacuum; numeric pressure is not reported.'),('Sample boundary','MW, autoclave and SCF powders remain separate specimens.'),('Unreported','Isolated yields and subsequent storage.')])
scene('lab-xrd-acquire','Laboratory diffraction · acquire patterns','lab-xrd','Measure the dried laboratory powders on the in-house Rigaku SmartLab using Cu Kα1 radiation and Bragg–Brentano geometry. LaB6 NIST 660A provides a separate instrument-resolution reference.',[('Reference','LaB6 is a calibration specimen, not a synthesis reagent or powder additive.'),('Unreported','Scan interval, step and exposure.')])
scene('lab-xrd-fit','Laboratory diffraction · refine phase and size','analysis','Use Fullprof and the stated background, peak-shape and spherical-harmonic size model. Atomic positions and site occupancies are fixed to cited literature values.',[('Model boundary','Literature-fixed positions are not a measured coordinate file for the synthesized powder.'),('Peak profile','Thompson–Cox–Hastings pseudo-Voigt.'),('Unavailable','Detailed SI refinements.')],variant='Fullprof · separate phase models')
scene('synchrotron-load-acquire','Synchrotron diffraction · rotating capillary','rotate-capillary','Pack the selected dried powders in glass capillaries and rotate them during SPring-8 diffraction acquisition. The CeO2 standard is a separate calibration specimen.',[('Selected samples','M1–M3, M7, S1 and A1–A2; do not assign this acquisition to every powder.'),('Geometry','Debye–Scherrer geometry with an image-plate detector.'),('Unreported','Packing mass, rotation rate and exposure.')])
scene('synchrotron-fit','Synchrotron diffraction · fit scattering contributions','analysis','Refine using MAUD, retaining the glass-capillary and small-angle-scattering background contributions and anisotropic particle-size model.',[('Model boundary','Site occupancies and atomic positions are literature-fixed; ADPs are refined. No microstrain contribution was included.'),('Unavailable','Complete refined coordinate/sample files and SI results.')],variant='MAUD · anisotropic size refinement')
scene('pdf-solutions','Total scattering · separate precursor solutions','solution-alternatives','Prepare the separately named nitrate/base precursor solution contexts. These are different solutions for speciation analysis, not one combined synthesis feed.',[('Specimen boundary','D1–D4 remain separate; exact D1/D2 precursor concentrations and volumes are not fully given.'),('No invented treatment','The cited 150–350 °C range belongs to prior work and is not a D2 heating step.')])
scene('pdf-acquire','Total scattering · specimen and background','total-scattering','Collect total scattering at PETRA III beamline P02.1 and measure a separate deionized-water background using the same type of capillary and temperature.',[('Separate reference','LaB6 NIST 660b is used for calibration; background water is measured separately, not added to the solution.'),('Table 1 scope','D1–D4 intervals describe collection contexts; no thermal dwell or heating recipe is inferred.'),('Unreported','Complete energy and detector settings.')],include_options=True)
scene('pdf-reduce-fit','Total scattering · PDF and reciprocal-space fits','analysis','Integrate using Fit2D, obtain PDFs with PDFgetX3, and fit with DiffPy CMI. Keep the D2 crystalline ZnO fit and D3 Zn-cluster Debye-scale fit distinct; reciprocal-space D2 data use Fullprof.',[('Distinct models','D2 size uses a spheroid model; D3 is not assigned the D2 crystalline refinement.'),('Calibration','PDFgui with NIST LaB6 660b; reciprocal-space instrument resolution also uses 660b.'),('Unavailable','Complete SI parameter tables; no atomic reconstruction is inferred.')],variant='PDF / reciprocal-space analysis')
scene('microscopy-disperse','Electron microscopy · disperse by sonication','sonicate','Disperse dried powder by sonication in 99% ethanol. This solvent grade is distinct from the 96% ethanol wash.',[('Unreported','Sonication duration, power, apparatus type and dispersion concentration.'),('Schematic','Vibration marks indicate sonication, not a claimed bath or probe arrangement.')])
scene('microscopy-deposit','Electron microscopy · prepare supported grid','grid-deposit','Place individual drops on 200-mesh copper grids with Formvar/carbon support film and dry in ambient atmosphere.',[('Environment','Ambient atmosphere; no numerical drying temperature or duration supplied.'),('Unreported','Drop volume and exact grid-to-synthesis aliquot identity.')])
scene('microscopy-acquire','Electron microscopy · TEM, STEM and EDS','tem','Acquire bright-field TEM, HAADF-STEM and spatially resolved EDS with the TALOS F200A system. Original images and elemental maps are displayed separately from this apparatus drawing.',[('Equipment','TWIN lens system, X-FEG source, Ceta 16 M camera and Super-X detector; Bruker Esprit and Hyperspy.'),('Unreported','Explicit operating voltage and exact physical cross-assay specimen joins.'),('Evidence boundary','No synthetic micrograph, diffraction pattern or measured atomistic geometry.')])
scene('optical-acquire','Optical properties · diffuse reflectance','reflectance','Measure room-temperature diffuse reflectance on the Shimadzu UV-3101 PC, using BaSO4 as a separate reference.',[('Sample/reference','Powder specimen and BaSO4 reference are distinct; no mixture is implied.'),('Environment','Room temperature; numeric temperature and detailed mounting are unreported.')])
scene('optical-transform','Optical properties · source transform and Tauc analysis','analysis','Apply the printed source reflectance expression and linear Tauc fit. The paper’s printed formula is retained without an unannounced algebraic repair.',[('Expression provenance','Original equation and symbol definitions are preserved in the source reader.'),('Unreported values','Exact numerical current-sample band gaps are not transcribed from unlabeled graph bars.'),('Unavailable','SI Tauc plots and full fit data.')],variant='Source transform → Tauc fit')
bindings=[]
for r in records:
 for i,o in enumerate(r['operations']):
  c=configs[o['id']];c.update(record_id=r['record_id'],operation_pointer=f'/operations/{i}')
  c['option_pointers']=[f'/condition_options/{j}' for j in range(len(r.get('condition_options',[])))] if c.get('include_options') else []
  bindings.append({'record_id':r['record_id'],'record_path':str(C/(r['record_id']+'.json')),'record_sha256':sha(C/(r['record_id']+'.json')),'operation_id':o['id'],'operation_pointer':c['operation_pointer'],'inputs':o['inputs'],'outputs':o['outputs'],'retained_fraction':o['retained_fraction'],'source_evidence':o['evidence'],'canonical_description':o['description'],'human_prose':c['prose'],'art':c['art'],'option_pointers':c['option_pointers']})
assert len(bindings)==len(configs)==31
labels={k:k.replace('_',' ').capitalize() for r in records for o in r['operations'] for k in o['parameters']}
labels.update({'zn_no3_2_6h2o_mass':'Zn(NO3)2·6H2O charge','al_no3_3_9h2o_mass':'Al(NO3)3·9H2O charge','C_NaOH':'Printed NaOH concentration','T_rxn':'Reaction temperature','t_rxn':'Printed total interval','t_dwell':'Printed dwell/collection interval','assumed_time_to_set_point':'Cited assumption: time to set point','wavelength':'Calibrated X-ray wavelength','q_range_endpoint':'Reported q-range endpoint','naoh_solution_aliquot':'NaOH-solution aliquot','final_zn_concentration':'Final mixed Zn concentration','final_al_concentration':'Final mixed Al concentration','zno_mass':'ZnO charge','al_oh_3_mass':'Al(OH)3 charge','source_exponent_x':'Source exponent x'})
data={'source_group':'sommer2020','configs':configs,'parameter_labels':labels}
save('scene-config.json',data);save('records.json',records)
save('canonical-bindings.json',{'author':'/root','status':'private_draft','record_manifest_sha256':sha(C/'record-manifest.json'),'source_freeze_sha256':sha(N/'package-freeze.json'),'bindings':bindings})
if (A/'protocol-template.mjs').exists():(A/'sommer2020-protocol.mjs').write_text((A/'protocol-template.mjs').read_text('utf-8').replace('__CONFIG__',json.dumps(data,ensure_ascii=False,separators=(',',':'))),'utf-8')
shutil.copyfile(M/'recipe-atlas/dist/quantity-value.mjs',A/'quantity-value.mjs')
print(json.dumps({'operations':31,'records':len(records),'operation_parameters':sum(len(o['parameters']) for r in records for o in r['operations'])}))
