"""Freeze the separate molecular science, binding, visual and bounded-delta audit."""
from pathlib import Path
import json,hashlib,datetime
O=Path(__file__).parent;E=O.parents[1];B=E/'visuals/molecules';R=B/'revision-2'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
mechanical=read(O/'initial-review/mechanical-audit.json')
delta=read(O/'caption-revision-audit.json');viewer=read(O/'viewer-revision2-function-audit.json')
assert all(x['status']=='passed' for x in [mechanical,delta,viewer])
bound={**mechanical['bound_files'],**delta['bound_files'],**viewer['bound_files']}
for p in [*O.glob('*.py'),*O.glob('*.mjs'),O/'initial-review/finding.json',O/'initial-review/mechanical-audit.json',O/'caption-revision-audit.json',O/'viewer-revision2-function-audit.json',B/'package-freeze.json',R/'package-freeze.json',E/'reader-assets/si-01.txt']:
    bound[str(p)]=sha(p)
for name in ['10.1021_ja103805s.pdf','10.1021_ja103805s_si_1.pdf','10.1021_ja103805s_si_2.cif']:
    p=Path('[local path redacted]')/name;bound[str(p)]=sha(p)
for path,h in bound.items():assert sha(Path(path))==h,path
scopes=[
 {'topic':'Complete identity and source scope','result':'Read all 50 registry entries, formulas, captions, limitations and functional-group definitions against the already audited source and canonical v3. Thirty-two graph references, 17 symbols and one source molecular model cover 123 material slots.'},
 {'topic':'Independent connectivity and formula reconstruction','result':'Reconstructed all 32 stored 2D graphs from their atom, bond, charge, isotope and hydrogen fields and compared them with independently specified source-named graphs. Exact source R=C17H33 abbreviations remain placeholders in compounds 3, 5 and 8; no unreported conformation is supplied.'},
 {'topic':'Phosphorus chemistry and source diagrams','result':'Reopened the actual retained Table 1 and SI Figures S12/S13 source crops. The P–H bond remains present in secondary phosphines, assigned oxides/selenides and compound 4; the P–P connection and carboxylate/anhydride source schemes are retained.'},
 {'topic':'Isotopes and stereochemical reference limits','result':'Eight explicit deuterium sites are retained in toluene-d8. The named oleic-acid connectivity is a reference identity; the commercial technical-grade material is not upgraded to an assayed pure stereoisomer or exact solution species.'},
 {'topic':'Commercial material and impurity distinctions','result':'Commercial TOP at 90%, 97% and unspecified lot remains separate symbolic contexts. Distillation fractions and phosphorus-integral data do not become mass purity. OA/ODE technical grade, reported reagent purity and unknown grades are source-scoped.'},
 {'topic':'Bound purity correction','result':'Independently found three PbO captions with None%. Revision 2 changes only those captions and their three mirrored binding notes to ≥99.9% (99.9+% as printed). The lower-bound quantity was correct throughout; original files and finding history remain unchanged.'},
 {'topic':'Exact source-slot and stock binding','result':'Every one of the 123 canonical material slots resolves to its exact source-specific reference, evidence and immutable canonical v3 hash. All 13 stock slots and 41 components retain their exact material IDs, quantity objects, concentration scopes and JSON pointers.'},
 {'topic':'Source-neutral reuse','result':'Inspected all retained reuse qualification records and 25 cached asset snapshots. New source-specific copies retain named connectivity without another paper\'s grades, sample assignments or 3D conformers. Nitrogen uses only qualified N≡N connectivity; the old generic 3D geometry is not admitted.'},
 {'topic':'Unknown metal coordination and phase','result':'Cd/Pb oleates remain symbolic rather than fabricated coordination complexes. Bulk oxides, elemental reagents and PbSe/CdSe quantum-dot contexts receive symbolic identities without invented polymorphs, unit cells, ligands or atomic particle coordinates.'},
 {'topic':'Mechanistic hypotheses','result':'Unisolated proposed intermediates 1, 6, 10, 11 and 14 remain labeled symbolic hypotheses. No structure model is inferred from a proposed reaction drawing.'},
 {'topic':'Species 9 identity and source-coordinate transform','result':'The sole 3D model is molecular Pb(Se2PPh2)2, C24H20P2PbSe4. Independently recomputed Cartesian coordinates from the original CIF cell and all 51 fractional sites; exact labels, elements, occupancies and flags match. All 20 hydrogen sites retain calculated riding-model status, not independently measured H positions.'},
 {'topic':'Species 9 molecular extent and contact semantics','result':'All 56 source intra-asymmetric-unit geometry connections are retained as visual sticks with no chemical bond-order assertion. Three source symmetry-related contact rows are excluded from the isolated molecular view. The model is not a complete periodic cell, a solution conformation, a PbSe/CdSe QD or DFT-ready QD structure.'},
 {'topic':'Species 9 binding boundary','result':'The actual binding is evans-2010-reagents, material species9, source_material context supported by SI page 16 crystallization. It is absent from the PbSe quantum-dot route. This audit does not silently add a new product-viewer association.'},
 {'topic':'Actual preview inspection','result':'Independently opened all seven contact sheets covering all 50 actual previews, plus native-size DPPSe, toluene-d8 and species9 images. Titles, formulas, chemical graphics, symbolic labels and scope text are readable. The species9 static orientation is a viewing projection only; source model coordinates are unchanged.'},
 {'topic':'Actual viewer lookup contract','result':'Executed the current Site chemicalEntry pure function against all slots/components with unapproved gates and disposable approved metadata. Source captions are displayed, identity/model override attempts are ignored, foreign records are unresolved and inputs are not mutated. This is not a mounted DOM, mouse/rotation or publication test.'},
 {'topic':'Public projection boundary','result':'The explicit candidate allowlist contains exactly 50 new SVG and 33 new model JSON files. All bytes and paths checked; no original PDF/CIF attachment, whole-page image, full-paper text cache, private source snapshot or local filesystem link is included in those 83 assets.'}
]
pm=read(B/'preview-manifest.json')
native=['evans2010-dppse-reference.png','evans2010-toluene-d8-reference.png','evans2010-species9-reference.png']
visual={'all_contact_sheets_actually_viewed':pm['contact_sheets'],'all_preview_count':50,
 'native_previews_actually_viewed':[{'path':str(B/'previews'/n),'sha256':sha(B/'previews'/n)} for n in native],
 'source_crops_actually_reopened':[{'path':str(B/'source-evidence'/n),'sha256':sha(B/'source-evidence'/n)} for n in ['table-1.png','figure-S12.png','figure-S13.png']],
 'source_reading_boundary':'This molecular audit builds on the separately saved full-source scientific audit, which actually read and viewed all 3 main and 21 SI pages and independently parsed the original CIF. Targeted source diagrams and the SI page-1 reagent passage were reopened for this audit; no fresh complete extraction is claimed.'}
report={'schema':'mattersyn-independent-molecular-source-audit/1','source_id':'evans2010','version':2,
 'created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reviewer':'/root/peng1998_reader_assets','author':'/root/norberg2004_extract',
 'status':'passed','scope':'Independent molecular identity, source-model, material/stock binding and private visual-package qualification. Final integrated browser, apparatus and publication remain separate gates.',
 'effective_package_freeze':{'path':str(R/'package-freeze.json'),'sha256':sha(R/'package-freeze.json')},
 'preserved_original_freeze':{'path':str(B/'package-freeze.json'),'sha256':sha(B/'package-freeze.json')},
 'effective_files':read(R/'package-freeze.json')['effective_files'],
 'counts':{'entries':50,'connectivity_graphs_2d':32,'symbolic_entries':17,'molecular_source_models_3d':1,'material_slots':123,'stock_slots':13,'stock_components':41,'public_candidate_assets':83,'actual_previews_inspected':50,'manual_scientific_scopes':len(scopes)},
 'checks':{'original_molecular_source_binding':mechanical['checks'],'bounded_caption_delta':delta['checks'],'actual_viewer_pure_function':viewer['checks']},
 'scientific_scopes':scopes,'actual_visual_scope':visual,
 'resolved_findings':[{'id':'EVANS-MOLECULE-01','status':'resolved_in_effective_revision_2','history_path':str(O/'initial-review/finding.json'),'resolution':'Exactly six caption leaves corrected; source quantity and all scientific assignments/assets unchanged.'}],
 'open_findings':[],
 'auditor_predicate_history':'Initial diagnostic mismatches in JSON hash serialization, drive-path regex and a too-narrow species9 record-name predicate were corrected in the independent checker using the actual declared contracts. They were auditor checks, not author chemistry defects; initial-predicate-diagnostics.json is retained.',
 'remaining_gates':['Integrate only the revision-2 effective maps with the unchanged registry and assets.','Preserve all source captions and model limitations in the mounted viewer.','Independently test mounted browser rendering and interactions after integration.','Apparatus, website publication and training admission are outside this audit; author flags remain false and no QD-coordinate eligibility is granted.'],
 'no_site_ledger_source_edits':True,'no_network_downloads':True,'bound_files':bound}
j=O/'independent-audit-v2.json';m=O/'independent-audit-v2.md'
if j.exists() or m.exists():raise SystemExit('Refusing to overwrite frozen final audit')
j.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
text='''# Evans 2010 — independent molecular and binding audit\n\nPassed against molecular revision 2 and canonical revision 3. This is private scientific and binding qualification; browser integration and publication are separate gates.\n\nThe review covers 50 identities (32 2D connectivity graphs, 17 symbolic entries and one molecular source-CIF model), 123 material slots, 13 stocks with 41 components, and all 50 actual previews. The original mechanical audit passed 3,644 checks; the exact caption delta passed 17,089 checks; the actual current viewer lookup function passed 1,274 checks. Sixteen scientific/visual scopes are detailed in the JSON report.\n\nOne independent finding was corrected in a preserved revision: three PbO source captions, each duplicated in a binding note, showed “None%” rather than the source lower bound. Exactly six string leaves now display “≥99.9% (99.9+% as printed)”. All graphs, coordinates, quantities, assignments, canonical records and original files are unchanged. No open molecular finding remains.\n\nSpecies 9 is the supplied molecular lead complex C24H20P2PbSe4. All 51 original sites, including 20 calculated riding hydrogens, and 56 intra-unit source connections are retained. Three symmetry-related contact rows are excluded from the isolated molecular view. This is not a QD atomic model, complete periodic cell, inferred solution conformer or exact structure–recipe/DFT pair. Metal oleates, commercial mixtures, unknown phases and unisolated mechanistic species remain symbolic and explicitly qualified.\n\nOnly 50 new SVGs and 33 model JSONs are public-asset candidates. Original papers/SI/CIF attachments, full-page images, raw text and source snapshots are excluded from that allowlist. Use the revision-2 effective binding and slot maps; the original registry and assets remain their exact frozen bytes.\n\n'''
text+=f'Final package freeze: `{sha(R/"package-freeze.json")}`.\n\nAudit JSON SHA256: `{sha(j)}`.\n\nBound files: {len(bound)}. Full source, visual, delta and function-check boundaries are recorded in the JSON. No Site, ledger, source or author-file edits were made by this audit.\n'
m.write_text(text,encoding='utf-8')
print(json.dumps({'status':'passed','audit':str(j),'sha256':sha(j),'markdown_sha256':sha(m),'bound_files':len(bound),'counts':report['counts']},ensure_ascii=False,indent=2))
