import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {prepareExperimental,renderExperimental,mountExperimental} from '../static/experimental-silver.mjs';
const actual=()=>JSON.parse(readFileSync(new URL('../static/data/experimental-silver.json',import.meta.url)));
test('actual source evidence is separate and has zero admission credit',()=>{const x=actual();assert.equal(prepareExperimental(x).status,'ready');assert.equal(x.distinct_sources,1);assert.equal(x.entries[0].fields.length,9);assert.equal(x.usable_complete_recipes,0);assert.equal(x.structure_pair_count_contribution,0);});
test('training/calibration/accuracy tampering rejected',()=>{for(const [key,val] of [['training_ready',true],['measured_accuracy',.99],['calibration_state','approved'],['gold_count_contribution',1]]){const x=actual();x[key]=val;assert.equal(prepareExperimental(x).status,'unavailable');}});
test('quote/path leakage rejected instead of hidden',()=>{for(const mutate of [x=>x.entries[0].quote='private evidence',x=>x.entries[0].fields[0].quote='private evidence',x=>x.entries[0].title='C:/private/source.pdf']){const x=actual();mutate(x);assert.equal(prepareExperimental(x).status,'unavailable');}});
test('unsafe and mismatched DOI links rejected',()=>{for(const url of ['javascript:alert(1)','http://doi.org/10.1021/cm990228p','https://example.com','https://doi.org.evil/10.1021/cm990228p']){const x=actual();x.entries[0].url=url;assert.equal(prepareExperimental(x).status,'unavailable');}});
test('repeated sources and malformed values rejected',()=>{const x=actual();x.entries.push(structuredClone(x.entries[0]));x.distinct_sources=2;assert.equal(prepareExperimental(x).status,'unavailable');for(const value of [NaN,Infinity,true]){const y=actual();y.entries[0].fields[0].value=value;assert.equal(prepareExperimental(y).status,'unavailable');}});
test('caller mutations cannot change prepared values',()=>{const x=actual(),view=prepareExperimental(x);x.entries[0].fields[0].value=999;assert.equal(view.entries[0].fields[0].value,110);});
class Node {constructor(doc,tag){this.ownerDocument=doc;this.tag=tag;this.children=[];this.textContent='';}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}set innerHTML(x){throw Error('HTML injection path forbidden');}}
const dom=()=>{const doc={createElement(tag){return new Node(doc,tag);}};return new Node(doc,'host');};
test('text-only rendering keeps labels and no executable markup',()=>{const x=actual();x.entries[0].title='<img src=x onerror=alert(1)>';const host=dom();renderExperimental(host,prepareExperimental(x));const all=[];const walk=n=>{all.push(n);n.children.forEach(walk);};walk(host);assert.ok(all.some(n=>n.textContent==='<img src=x onerror=alert(1)>'));assert.ok(all.some(n=>n.textContent.includes('Accuracy unmeasured')));assert.ok(all.some(n=>n.textContent.includes('0 complete recipes')));});
test('failed manifest fetch shows unavailable and uses no credentials',async()=>{const host=dom();let request;await mountExperimental(host,{fetcher:async(...args)=>{request=args;return {ok:false};}});assert.deepEqual(request,['data/experimental-silver.json',{credentials:'omit'}]);assert.equal(host.children[0].textContent,'Experimental evidence is unavailable.');});
