import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.join(path.dirname(fileURLToPath(import.meta.url)),'v1');
const {buildHeo2003Scene,renderHeo2003Markup}=await import('./v1/heo2003-protocol.mjs');
const records=JSON.parse(fs.readFileSync(path.join(dir,'records.json'),'utf8'));
fs.mkdirSync(path.join(dir,'scenes'),{recursive:true});
const result=[];let controls='',data=[];
for(const r of records)for(const o of r.operations){const s=buildHeo2003Scene(o,r);if(!s)throw Error(o.id);fs.writeFileSync(path.join(dir,'scenes',s.kind+'.svg'),s.svg);result.push({record_id:r.record_id,operation_id:o.id,kind:s.kind,rows:s.rows,caption:s.caption,description:s.description});data.push({title:s.title,markup:renderHeo2003Markup(s)});controls+=`<option value="${data.length-1}">${data.length}. ${o.label}</option>`;}
if(result.length!==14||new Set(result.map(s=>s.kind)).size!==14)throw Error('Scene coverage mismatch');
fs.writeFileSync(path.join(dir,'scene-output.json'),JSON.stringify(result,null,2)+'\n');
fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Heo2003 protocol illustration review</title><style>body{margin:0;background:#eef4f7;color:#183a50;font:16px/1.65 system-ui}main{max-width:1100px;margin:36px auto;padding:0 18px}h1{font-size:28px}select{width:100%;padding:12px;font-size:16px;border:1px solid #abc;border-radius:8px}article{margin:20px 0;border:1px solid #dce8ef;border-radius:16px;overflow:hidden;background:#fff}h2{font-size:22px;padding:10px 22px 0}nav{display:flex;justify-content:space-between;margin-top:18px}button{font:inherit;padding:8px 18px}</style><main><h1>Synthesis protocol and analytical procedures</h1><p>Heo et al. (2003) · Private illustration review. Canonical v2 source conditions; apparatus geometry is explanatory.</p><label for="operation">Operation</label><select id="operation">${controls}</select><article><h2 id="title"></h2><div id="scene" class="protocol-art protocol-art-heo2003"></div></article><nav><button id="previous">Previous</button><button id="next">Next</button></nav><p id="position"></p></main><script type="module">const scenes=${JSON.stringify(data).replaceAll('<','\u003c')};const s=document.getElementById('operation');function show(){const i=Number(s.value);document.getElementById('title').textContent=scenes[i].title;document.getElementById('scene').innerHTML=scenes[i].markup;document.getElementById('previous').disabled=i===0;document.getElementById('next').disabled=i===scenes.length-1;document.getElementById('position').textContent=(i+1)+' / '+scenes.length;}s.onchange=show;document.getElementById('previous').onclick=()=>{s.value=String(Number(s.value)-1);show()};document.getElementById('next').onclick=()=>{s.value=String(Number(s.value)+1);show()};show();</script></html>`);
console.log(JSON.stringify({scenes:result.length,distinct_svg_files:14,rows:result.reduce((n,s)=>n+s.rows.length,0)}));
