from pathlib import Path
import json,hashlib,datetime
A=Path(__file__).resolve().parent;V=A.parent/'molecules';N=A.parents[1]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):return json.loads(Path(p).read_text('utf8'))
s=read(A/'scientific-checks-v1.json');c=read(A/'consumer-checks-v1.json');f=read(V/'package-freeze.json')
failed=[x for x in s['checks']if not x['passed']]
assert len(failed)==3 and all('Tertiary amine chemical qualification cerium-nitrate'==x['check']for x in failed)
bound={**f['bound_files'],**s['bound_files'],**c['bound_files']}
for p in [V/'package-freeze.json',N/'source-independent-audit/independent-audit.json',N/'canonical-reader-independent-audit/independent-audit-v2.json',A/'scientific-checks-v1.json',A/'consumer-checks-v1.json',Path(__file__)]:bound[str(p)]=sha(p)
for p,h in bound.items():assert sha(p)==h,p
scopes=[
 {'scope':'All 32 preview panels on six contact sheets','result':'Actually visually inspected 20 identity SVG previews, six stock cards and six retained 3D previews. Captions, formulas, symbolic boundaries and solute/solvent distinctions are readable. No browser or rendered WebGL claim.'},
 {'scope':'Cerium nitrate hexahydrate','result':'Disconnected Ce3+, three nitrate ions and six water formula components; no Ce–O bonds or crystal coordination asserted. Formula/graph pass; three false amine group labels require correction.'},
 {'scope':'TEA identity and literal source formula','result':'Three ethanol arms on neutral tertiary N yield C6H15NO3. The inconsistent printed (C2H5OH)3N remains a separate literal-source conflict; free-compound 2D does not assign the unknown Ce complex.'},
 {'scope':'Six solute/solvent stock contexts','result':'Each 0.1 M nitrate or 0.4 M TEA stock uses its own matching ethanol/propanol/butanol solvent. The 100 mL quantity is a transferred portion; total stock preparation charge remains unknown.'},
 {'scope':'Solvent grades and source charges','result':'Ethanol anhydrous qualification does not transfer to propanol or butanol. All canonical quantity and grade links were independently resolved, preserving stated values and missingness.'},
 {'scope':'Workup and diagnostic-only reagents','result':'Acetone belongs after ambient drying; NH4OH remains the separate filtrate diagnostic. Filter and glassware are symbolic objects; pore/flow/reaction quantities remain canonical scoped metadata.'},
 {'scope':'Nitrogen, air and hydrate water','result':'N2 is the BET adsorptive; air is TGA context only and is not promoted to calcination atmosphere. Hydrate water is a stoichiometric component, not an added synthesis-water charge.'},
 {'scope':'Unresolved species and material mixtures','result':'Ce–TEA, hydroxocomplex, proposed hydroxide/hydrated-ceria and protonated TEA are symbolic, with no invented connectivity or coordination. Local ceria identity does not establish pure whole as-prepared powder.'},
 {'scope':'Eight graph identities','result':'Reconstructed atom/bond graphs with independent expected SMILES/formulas using retained local RDKit. Charges, fragments, valence and functional-group chemistry checked; only nitrate annotation fails.'},
 {'scope':'Six cached conformers','result':'Atom and bond arrays exactly equal retained qualified references; graphs and bond lengths independently checked. N2 is 1.09768 Angstrom; no conformer is represented as measured solution geometry.'},
 {'scope':'Private canonical v2 bridge','result':'All 19 record bytes equal v1; the separate passed v2 audit resolves only the supported reader scope token. No binding overlay is needed to change record identity.'},
 {'scope':'Actual consumer execution','result':'Executed current Site chemical-viewer.mjs, equal to the frozen snapshot, with a minimal DOM and 3Dmol data sink. 45 slot overrides, 20 dialogs, six 3D coordinate/bond/group paths, keyboard rotation/reset/zoom, symbolic fallback, six stocks and 12+12 component transitions checked. This is functional execution, not a mounted browser visual audit.'}
]
report={'schema':'mattersyn-independent-molecular-audit/1','auditor':'/root/norberg2004_extract','author':'/root/peng1998_reader_assets','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_id':'pati2009','status':'open_findings','proposal_freeze_sha256':sha(V/'package-freeze.json'),'source_audit_sha256':sha(N/'source-independent-audit/independent-audit.json'),'canonical_v2_audit_sha256':sha(N/'canonical-reader-independent-audit/independent-audit-v2.json'),'counts':f['counts'],'check_count':s['check_count']+c['check_count'],'failed_check_count':3,'manual_scope_count':len(scopes),'manual_scopes':scopes,'findings':[{'id':'PATI-MOL-01','status':'open','severity':'required_scientific_annotation_correction','paths':['registry-additions.json /entries/0/functionalGroups','models/pati2009-cerium-nitrate-2d.json /functionalGroups'],'description':'Nitrate N+ atoms 2, 6 and 10 are each incorrectly labeled Tertiary amine nitrogen. A nitrate N bonded to oxygen is not a tertiary amine. Connectivity, charge, formula and correct nitrate-resonance groups are already correct.','required_correction':'Preserve the initial freeze; remove only the three false amine annotations, updating corresponding registry/model digest dependencies. Retain nitrate/water/Ce groups and TEA actual tertiary-amine annotation; do not change atoms, bonds, coordinates or source/canonical data.','evidence':failed}],'method_limitations':['The minimal-DOM fixture was adapted from the author harness, independently executed with additional checks against the actual current Site consumer; author-reported counts are not counted as auditor execution.','This audit does not approve apparatus science, mounted-browser display, Site installation, publication, training eligibility, crystal coordinates, or exact structure-recipe pairing.'],'bound_files':bound}
(A/'independent-audit-v1.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n','utf8')
(A/'independent-audit-v1.md').write_text('# Pati molecular independent audit — initial freeze\n\nStatus: open finding PATI-MOL-01.\n\nAll 20 identities, 45 slots, six stocks/twelve components, eight chemical graphs, six retained conformers, 32 preview panels and exact canonical v2 byte bridge were reviewed. The independently executed checks total 1,817; three failures all express one nitrate annotation issue.\n\nNitrate N+ atoms 2, 6 and 10 are not tertiary amines. Remove those false annotations in a preserved revision; the atoms, bonds, formulas and nitrate resonance groups are already correct. No other correction was found.\n\nThe 885 viewer checks executed the actual current consumer using a minimal DOM/3Dmol sink; these are not browser screenshots or a mounted viewer approval. Source, canonical, Site integration, apparatus, training and publication gates remain distinct.\n\nExact input hashes, twelve manual scopes and the retained finding are in the JSON report.\n','utf8')
print(json.dumps({'status':report['status'],'audit_sha256':sha(A/'independent-audit-v1.json'),'checks':report['check_count'],'bound_files':len(bound)}))
