from pathlib import Path
B=Path(__file__).resolve().parent;P=B.parent/'jp011815c'
t=(P/'run_build.py').read_text(encoding='utf-8').replace('shah2001-protocol.mjs','gerion2001-protocol.mjs')
(B/'run_build.py').write_text(t,encoding='utf-8')
t=(P/'build_inventory_actual.py').read_text(encoding='utf-8').replace('-shah-actual-local-snapshot','-gerion-actual-local-snapshot').replace("g='shah2001'","g='gerion2001'").replace('paper-reviews/shah2001.json','paper-reviews/gerion2001.json').replace('paper-review.html?id=shah2001','paper-review.html?id=gerion2001')
t=t.replace('All eight supplied main pages text and visually reviewed with independent source, canonical, reader, chemical and apparatus audits; SI not located or verified; deployment tracked separately.','All eleven supplied main pages text and visually reviewed with independent source, canonical, reader, chemical and apparatus audits. Explicitly announced HRTEM/AFM SI remains unlocated or unverified; deployment tracked separately.').replace("'page_count':8","'page_count':11")
old="'notes':['Nine silver experiments A–I and two separate iridium/platinum conditions provide eleven source-linked synthesis variants.','Four common procedures and four contextual observations remain separate from experimental routes.','Twenty-one original source assets preserve eleven figures, Table 1, equations, definitions and procedural notes.','The platinum precursor remains as printed with unresolved identity. Figure 7 cohorts are not silently joined to same-size Table 1 rows. No measured atomic coordinates or exact-structure training labels supplied.']"
new="'notes':['Two downstream CdSe/ZnS coating routes: siloxane growth and MPA ligand exchange. The optional undosed APS extension is a procedure, not a complete independent synthesis.','Sixteen supporting procedures and ten contextual observations preserve original sample scopes, controls, analytical acquisition and interpretation.','Seventeen original crops preserve seven figures, two tables and reagent/procedural notes. HRTEM and AFM supporting figures are declared but unavailable locally.','Color-cohort sizes and spectra do not supply exact recipe–specimen links, measured atomic coordinates or success labels. Named phosphonate identity, filter units, peak values and plotted sample-selection conflicts remain explicit.']"
assert old in t;t=t.replace(old,new)
t=t.replace("'all_shah_records'","'all_gerion_records'").replace("'eleven_shah_routes':row['synthesis_route_variant_count']==11","'two_gerion_routes':row['synthesis_route_variant_count']==2").replace("'nine_explicit_ag_size_labels'","'no_new_unpaired_size_labels'")
(B/'build_inventory_actual.py').write_text(t,encoding='utf-8')
print('Prepared Gerion build and actual-inventory helpers')
