from pathlib import Path
import json
B=Path(__file__).resolve().parent;M=B.parents[3]
p=json.loads((B/'publication-checkpoint.json').read_text(encoding='utf-8'))
assert p['deployment_status']=='succeeded'
inv=json.loads((M/'recipe-atlas/data/inventory-summary.json').read_text(encoding='utf-8'));s=inv['summary']
heading='## 2026-09-19 — Gerion silica-coated CdSe/ZnS added to the existing MatterSyn atlas'
t=f'''{heading}

The user again explicitly confirmed that new materials must appear in the existing MatterSyn website. Preserve the same public Site, periodic-table discovery and material hubs; append reviewed methods alongside earlier contributions. Published version {p['public_live_version']}, dataset 0.14.0, commit {p['source_commit']} at {p['published_at']}. New siloxane-coated CdSe/ZnS hub: {p['material_url']}. Existing CdSe, CdSe/ZnS and ZnS component pages include the new synthesis contributions with precise scope. Same root: {p['public_url']}. Native proof is research-assets/incoming-paper-monitor/reviews/jp0105488/publication-checkpoint.json.

Gerion et al., Synthesis and Properties of Biocompatible Water-Soluble Silica-Coated CdSe/ZnS Semiconductor Quantum Dots, J. Phys. Chem. B 2001,105,8861–8871, DOI10.1021/jp0105488: all eleven supplied main pages read and visually inspected. Legacy and incoming main PDFs are byte-identical, SHA25698a21f9489eda29e1e1f5f40b336661ceb1b27d9468095a9b44ad342a780400b. Source generation2 unchanged at post-publication fingerprint {p['source_fingerprint_at']}. HRTEM/AFM supporting figures are explicitly declared but not located or verified locally. Closure applies to supplied main only; later SI must reopen the source. All36 references/notes are retained as references, not independently read outside papers.

Twenty-eight canonical records: two downstream coating routes (siloxane and MPA), sixteen supporting procedures including the incompletely dosed optional APS extension, and ten contextual observations. Retained82 operations,186 measurement entries,139 reader items covering251 source units,329 typed facts and17 original crops (seven figures, two tables and procedural/reagent notes). Added26 molecular/product reference entries; eleven existing references reused;128 material slots and four product references bound. DTNB positional-isomer connectivity was corrected and independently rechecked in both2D and3D. DMF metadata was made source-neutral with atoms/bonds/coordinates unchanged. Source-specific apparatus scenes cover all82 operations; independent source/canonical/reader/molecular/binding/apparatus and original-asset audits passed. Browser QA scope is recorded separately rather than claiming every interaction was tested.

Scientific distinctions: cited upstream core/shell synthesis is not a reproduced local recipe; initial wet pellets differ from the MPA route’s later dried pellet; dialysis contents, membrane retentate, syringe filtrate, recovered pellet and clarified supernatant must not be confused. Keep stock-solute/solvent identities, unknown TMAH concentration, DMAP mass per unit stock volume, optional branch choices and staged rest periods explicit. Printed phosphonate name/drawing conflict remains unresolved without a guessed corrected formula. Figure1 hydrolyzed MPS is not the methoxy reagent. Preserve filter mm/µm conflicts, rotary-reduction/rest chronology conflicts, table/prose PL differences, visible AFM-bin versus stated exclusion conflict, methods/figure salt-series and pH discrepancies, and observation-duration versus plotted-axis limits. Chromatogram trace colors are not emission labels; peak areas are not particle-number fractions. AFM heights do not prove uniform single-core shell thickness. Ellman results are confounded upper estimates. No missing micrographs, EELS spectrum, XRD, SAED, exact atomic structure, toxicity validation or unreported sample associations invented.

Schema1.3.0 now permits material state kinds analysis_data and sample_set so instrumental outputs and sets of separate comparator aliquots are not mislabeled as physical mixtures. Dataset totals: {s['canonical_records']} records, {s['synthesis_route_variant_records']} synthesis-route records, {s['contextual_control_variant_records']} controls, {s['shared_preparation_workup_characterization_assay_procedures']} supporting procedures, {s['contextual_observation_records']} observations and100 benchmark rows. There are {s['public_material_hubs']} public hubs, {s['direct_synthesis_target_systems']} direct systems and {s['component_only_hubs']} component hubs. Task-specific export counts: {json.dumps(inv['training_eligibility'],ensure_ascii=False)}. These are reviewed task entries, not complete-corpus totals or independent-experiment counts.

Continue oldest eligible local arrival in both existing folders through the existing heartbeat, using within-paper parallel work and source review before publication. No downloads or downloader changes. Quality is the CdSe standard; estimates should use measured completed throughput. Chatbot, DFT and theory-comparison extensions remain deferred.

'''
memory=M/'MEMORY.md';old=memory.read_text(encoding='utf-8')
if heading not in old:memory.write_text(t+old,encoding='utf-8')
ref=M/'skills/mattersyn-paper-to-site/references/incoming-corpus.md';old=ref.read_text(encoding='utf-8');addition=(B/'skill-lessons-draft.md').read_text(encoding='utf-8')
if '## Coating chemistry, analytical states and comparator specimens'not in old:ref.write_text(old.rstrip()+'\n\n'+addition,encoding='utf-8')
print('Publication memory and reusable skill lessons saved')
