from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
write(B/'browser-qa.json',{'status':'passed','at':datetime.now(timezone.utc).isoformat(),'browser':'Codex in-app browser, temporary local tab13','origin':'http://127.0.0.1:5187','checks':['Siloxane route renders complete identities/stocks and thirty source-specific protocol stages.','First consolidation shows approximately60°C/30min/N2; secondary consolidation shows <5min and unreported atmosphere without an invented nitrogen inlet. Already displayed duration bound is not duplicated.','Membrane concentration retains upper concentrate with100000Da cutoff and approximately2mL final volume; force/time remain unreported.','Optional filter preserves0.22mm printed-unit conflict; final clearing shows20000g/30min and retains supernatant.','MPS computed-conformer viewer opens; functional-group highlighting, zoom and mouse rotation exercised and visually inspected.','Figure-scope selector exposes all9 original figures/tables. Original Figure5 opens with TEM/AFM histograms and complete caption.','CdSe/ZnS hub lists previous Dabbousi overgrowth alongside equal-format Gerion MPA and siloxane routes; selecting MPA changes all illustrated stages.','MPA collection shows3000g/1h and retains pellet; N2 drying is distinct; final20000g/30min clearing retains supernatant.','Material measurements use actual sample composition or explicit unassigned composition, without inheriting the record-level formula into MPA comparison contexts.','Complete main-source reader displays139items; DTNB search filters to2 matching source items.','Selecting Cd and Se in periodic table exposes siloxane-coated CdSe/ZnS; clicking its link opens the new hub.','Existing CdSe page retains both Gerion contributions alongside earlier methods.','No browser console errors or warnings observed on checked routes.'],'limitations':['Interactions sample representative controls; all82 generated scenes and all17 original asset bytes are independently audited separately.','No mobile viewport override or complete interactive test of every asset claimed. Declared HRTEM/AFM SI remains unlocated.'],'module_hashes':{f:sha(S/'dist'/f)for f in ['gerion2001-protocol.mjs','protocol-visuals.mjs','material-hub.mjs','crystal-viewer.mjs']},'reader_sha256':sha(S/'data/paper-reviews/gerion2001.json')})
m=read(B/'milestones.json');m['extract']['evidence']=[str(B/f)for f in ['canonical-record-manifest.json','source-audit.json','public-review-proposal/proposal-validation.json']]
m['audit']={'status':'complete','evidence':[str(B/f)for f in ['canonical-records-audit.json','reader-source-audit.json','molecular-source-audit.json','bindings-source-audit.json','visual-source-audit.json','crop-source-audit.json']],'note':'Independent source, canonical, reader, chemical/binding, original-crop and all82apparatus audits pass against frozen artifacts; original main-only scope and announced missing SI remain explicit.'}
m['integrate']={'status':'complete','evidence':[str(B/f)for f in ['integration-manifest.json','build-validation.json','browser-qa.json','reader-assets/integrated-presentation-audit.json']],'note':'28records integrated into the same existing MatterSyn; build passed,25hubs/300records actual inventory reconciled, sample-specific labels and representative browser controls verified. New material and methods discoverable from Cd/Se and existing CdSe hubs.'}
for stage in m.values():
 for f in stage['evidence']:assert Path(f).exists(),f
write(B/'milestones.json',m)
c=read(B/'checkpoint.json');c.update(checkpoint_at=datetime.now(timezone.utc).isoformat(),website_published=False,current_work_items=[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in m.items()],next_action='Publish validated current Site source, fingerprint unchanged source bundle, then close supplied-main scope and save memory/skills.');write(B/'checkpoint.json',c)
im=read(B/'integration-manifest.json');im.update(status='integrated_validated_browser_checked_pending_publication',post_integration_presentation_fixes=['Avoid repeating a condition bound already displayed in the main grid; use µL/µM display labels.','Measurement prefixes use sample composition, never the parent record formula as a substitute for an unassigned specimen composition.'],final_module_hashes=read(B/'browser-qa.json')['module_hashes']);write(B/'integration-manifest.json',im)
print('Read, extraction, audit and integration complete; native publication still pending')
