"""Adapt the established root-only import/build workflow for this immutable contribution."""
from pathlib import Path
A=Path(__file__).resolve().parent;T=A.parent/'acs.cgd.9b01519'
text=(T/'import_reviewed_sommer.py').read_text('utf8')
text=text.replace("C=N/'product-context-proposal'", "C=N/'visuals/product-context'")
text=text.replace('Sommer','Matuhina').replace('sommer2020','matuhina2023').replace('sommer','matuhina')
text=text.replace('==567','==586').replace("'old_records_preserved':567","'old_records_preserved':586").replace("'unchanged_old_records':567","'unchanged_old_records':586")
text=text.replace("'new_records':19","'new_records':21").replace("'integrated_records':19","'integrated_records':21").replace("'new_routes':3","'new_routes':1")
text=text.replace("'new_phase_symbol_entries':3","'new_phase_symbol_entries':7").replace("'selected_source_crops':20","'selected_source_crops':30").replace("'apparatus_scenes':31","'apparatus_scenes':39").replace("'symbolic_product_contexts':77","'symbolic_product_contexts':47")
text=text.replace("+read(C/'registry-additions.json')['entries']","+read(P/'products/registry-additions.json')['entries']")
text=text.replace("read(C/'product-contexts-additions.json')","read(P/'products/product-contexts-additions.json')")
text=text.replace("if e['id'].endswith('-observed-phase-symbol'):\n  src=C/e['svgPath'];assert sha(src)==e['assetHashes']['svgPath'];cp(src,V/e['svgPath'])", "# All product SVGs already copied from the passed public asset allowlist.")
text=text.replace("Source, canonical/reader, molecular and apparatus audits passed. Symbolic product-context binding, integrated browser and publication gates remain separate.","Source, canonical/reader and visual audits passed. Integrated browser and publication gates remain separate; no qualified atomic model is admitted.")
# The dispatch head is now Sommer. Preserve all older precedence and fallback behavior.
start=text.index("rel='dist/protocol-visuals.mjs'")
end=text.index('\nversions=[]',start)
text=text[:start]+'''rel='dist/protocol-visuals.mjs'
edit(rel,"import {buildSommer2020Scene", "import {buildMatuhina2023Scene,createMatuhina2023Art,createMatuhina2023ConditionGrid} from './matuhina2023-protocol.mjs';\\nimport {buildSommer2020Scene")
edit(rel,'const sourceArt=createSommer2020Art','const sourceArt=createMatuhina2023Art(o,r)||createSommer2020Art')
edit(rel,'const sommer=buildSommer2020Scene','const matuhina=buildMatuhina2023Scene(o,r),sommer=buildSommer2020Scene')
edit(rel,"el('p',sommer?.caption","el('p',matuhina?.caption||sommer?.caption")
edit(rel,'if(sommer||ghosh||','if(matuhina||sommer||ghosh||')
edit(rel,'const dl=sommer?createSommer2020ConditionGrid','const dl=matuhina?createMatuhina2023ConditionGrid(o,r):sommer?createSommer2020ConditionGrid')
edit(rel,'&&!ghosh&&!sommer)for','&&!ghosh&&!sommer&&!matuhina)for')
edit(rel,"&&!ghosh&&!sommer){const env=el('div')","&&!ghosh&&!sommer&&!matuhina){const env=el('div')")
edit('scripts/build_dataset.py',"'dataset_version':'0.29.0'","'dataset_version':'0.30.0'",2)
edit('scripts/build_dataset.py',"('sommer2020','private_unapproved_reader_proposal')}","('sommer2020','private_unapproved_reader_proposal'),('matuhina2023','private_unapproved_reader_proposal')}")
edit('scripts/build_dataset.py',"('sommer2020','Chemical identity and source role only; independently qualified molecular/component bindings remain pending.')}","('sommer2020','Chemical identity and source role only; independently qualified molecular/component bindings remain pending.'),('matuhina2023','Identity and role are source scoped; qualified molecular/component bindings remain separate.')}")
edit('scripts/build_dataset.py',"prefix='Source context object: '", "prefix='Source context definition: ' if record['lineage']['source_group']=='matuhina2023' else 'Source context object: '")
edit('scripts/build_dataset.py',"not in {'lian2021','ghosh2012','sommer2020'}", "not in {'lian2021','ghosh2012','sommer2020','matuhina2023'}")
''' +text[end:]
text=text.replace("replace('0.28.0-r1','0.29.0-r1').replace('0.28.0-r2','0.29.0-r2')","replace('0.29.0-r1','0.30.0-r1').replace('0.29.0-r2','0.30.0-r2')")
text=text.replace("'dataset_candidate':'0.29.0'","'dataset_candidate':'0.30.0'")
(A/'import_reviewed_matuhina.py').write_text(text,'utf8')
text=(T/'build_sommer_inventory.py').read_text('utf8').replace('sommer','matuhina').replace('2020','2023').replace('expected_new=19','expected_new=21')
(A/'build_matuhina_inventory.py').write_text(text,'utf8')
text=(T/'build_and_check_site.py').read_text('utf8').replace('sommer','matuhina').replace('2020','2023')
(A/'build_and_check_site.py').write_text(text,'utf8')
print('Prepared root-only helpers; no Site files changed.')
