"""Manual source transcription after all 13 main and 13 SI pages were read/viewed.
Reported findings, interpretations and unresolved contradictions remain distinct.
"""
FACTS=[]
def Q(n,r,u):return (n,str(r),u)
def F(i,d,p,l,title,claim,scope,qs=(),flags=(),kind='reported'):
 FACTS.append((i,d,p,l,title,claim,scope,list(qs),list(flags),kind))
F('identity','main',1,'Title/byline/abstract','Article and experimental scope','Matuhina and coauthors investigate the structure and luminescence of colloidal CsMnCl3 nanocrystals, distinguishing cubic nonemissive and rhombohedral red-emissive products, measured spectroscopy and a separate DFT interpretation.','article')
F('chemicals','main',2,'Experimental: Materials','Reported reagents and grades','Sigma-Aldrich supplies Cs2CO3, octadecene (ODE), oleic acid (OA), technical oleylamine (OlAm), Mn(II) chloride, hexane and methyl acetate. ODE positional/isomer composition and technical ligand composition are not independently assayed.','all-preparations',[Q('Cs2CO3 purity','99.9','%'),Q('ODE purity','90','%'),Q('OA purity','90','%'),Q('OlAm technical grade','70','%'),Q('MnCl2 purity','99','%'),Q('hexane purity','>=95','%'),Q('MeOAc purity','>=98','%')],['G1'])
F('dry-solvents','main',2,'Experimental: Materials and synthesis','Solvent drying scope','Conventional distillation produces anhydrous MeOAc. The text says all other chemicals are used without further purification, while the preparation explicitly calls ODE/OA/OlAm dry and MnCl2 anhydrous; their drying method is not supplied. Anhydrous isopropanol and ethyl acetate occur only in purification trials.','solvents',flags=['G1'])
F('cs-charge','main',2,'Preparation of Cs-oleate','Cesium precursor charge','Load Cs2CO3 and ODE into a three-neck flask. The solvent charge is not a stated final solution volume or standardized molarity.','cs-oleate-stock',[Q('Cs2CO3 mass','407','mg'),Q('ODE charge','18','mL'),Q('flask capacity','50','mL')],['G2'])
F('cs-degas','main',2,'Preparation of Cs-oleate','Initial cesium mixture degassing','Degas the Cs2CO3/ODE charge for one hour at 120 °C.','cs-oleate-stock',[Q('degassing duration','1','h'),Q('degassing temperature','120','degC')])
F('cs-oa','main',2,'Preparation of Cs-oleate','OA addition and dissolution','The text states dry OA is injected under Ar upon an additional 15 min of degassing, then the temperature is raised to 150 °C until the transparent Cs-oleate solution forms. The placement of the additional degassing relative to injection is retained as worded.','cs-oleate-stock',[Q('dry OA charge','1.74','mL'),Q('additional degassing duration','15','min'),Q('dissolution temperature','150','degC')],['G2'])
F('cs-store','main',2,'Preparation of Cs-oleate','Stock storage and reactivation','Cool the Cs-oleate precursor to room temperature and store under vacuum. Before injection, degas at 120 °C for at least 30 min and heat to 150 °C under Ar. Storage duration and pressure are unspecified.','cs-oleate-stock',[Q('pre-injection degassing duration','>=30','min'),Q('pre-injection degassing temperature','120','degC'),Q('pre-injection heating temperature','150','degC')],['G2'])
F('mn-charge','main',2,'Synthesis of CsMnCl3 NCs','Manganese precursor charge','In an inert atmosphere, weigh and load anhydrous MnCl2 with dry ODE, OA and OlAm in a three-neck flask. The synthesis is described as a modification of reference 22, whose content is not treated as newly read.','nc-series',[Q('MnCl2 mass','156','mg'),Q('flask capacity','25','mL'),Q('dry ODE charge','10','mL'),Q('dry OA charge','2','mL'),Q('dry OlAm charge','2','mL')],['G1'])
F('mn-degas','main',2,'Synthesis of CsMnCl3 NCs','Manganese mixture conditioning','Degas under vacuum at 120 °C for 1.5 h; during heating and degassing the precursor changes from reddish-brown to transparent yellow.','nc-series',[Q('degassing duration','1.5','h'),Q('degassing temperature','120','degC')])
F('inject','main',2,'Synthesis of CsMnCl3 NCs','Hot-injection alternatives','Under Ar, raise the manganese precursor to the selected injection temperature and swiftly inject Cs-oleate with vigorous stirring. The source pairs 2, 3 and 4 mL with reported Mn:Cs loading labels 0.7, 0.5 and 0.35. These labels are not recalculated from reagent charges; no complete stock final concentration is given. No obvious color change follows injection.','nc-series',[Q('injection temperature option 1','150','degC'),Q('injection temperature option 2','180','degC'),Q('injection temperature option 3','200','degC'),Q('Cs-oleate aliquot option 1','2','mL'),Q('Cs-oleate aliquot option 2','3','mL'),Q('Cs-oleate aliquot option 3','4','mL'),Q('reported Mn:Cs option 1','0.7','ratio'),Q('reported Mn:Cs option 2','0.5','ratio'),Q('reported Mn:Cs option 3','0.35','ratio')],['G2'])
F('variant-map','main',3,'Results first paragraph and Figure 1','Five source-defined variants','150@NCs and 200@NCs use the reported Mn/Cs loading ratio 0.7. At 180 °C the three variants are 180@NCs//0.7, //0.5 and //0.35. These five preparation conditions are not a fully crossed nine-condition matrix or independent batch replicates.','nc150/nc180-07/nc180-05/nc180-035/nc200',flags=['G3'])
F('quench','main',2,'Synthesis of CsMnCl3 NCs','Short growth and quench','Keep the reaction at the injection temperature for 5 s, then rapidly quench in an ice-water bath. Cooling trajectory and final quench temperature are unreported.','nc-series',[Q('hold after injection','5','s')],['G2'])
F('isolate','main',2,'Synthesis of CsMnCl3 NCs','Primary isolation','Centrifuge the crude reaction solution without antisolvent. Discard the supernatant and retain the white-pinkish NC precipitate. The generic red-emission observation must not override the nonemissive cubic 150@ result.','nc-series',[Q('centrifuge speed','8550','rpm'),Q('centrifuge duration','5','min')],['G3'])
F('dry-redisperse','main',2,'Synthesis of CsMnCl3 NCs','Drying and redispersion','Dry the retained precipitate in a vacuum desiccator, typically overnight, to remove excess solvent, then redisperse in hexane. The primary redispersion volume, numerical overnight duration and vacuum pressure are not given. The authors report high colloidal stability for the resulting suspensions.','nc-series',[Q('typical desiccator duration','overnight',None)],['G2'])
F('unisolated','si',3,'Figure S1d','Unisolated degradation control','Unisolated CsMnCl3 NCs left in ODE in air for 1 h become black/degraded. This is a control on unpurified material, not the long-term purified-dispersion stability test.','unisolated-control',[Q('air exposure duration','1','h')])
F('centrifuge-trial','main',2,'Purification of CsMnCl3 NCs','Hexane-only purification trial','After the first purification, disperse NCs in 2 mL hexane and centrifuge at varied speeds. No visible NC precipitation is observed; durations and individual sample identities are unspecified.','hexane-only-trial',[Q('hexane volume','2','mL'),Q('centrifuge speed interval','8600-14000','rpm')],['G4'])
F('antisolvent-trial','main',2,'Purification of CsMnCl3 NCs','Isopropanol and ethyl acetate trials','Divide crude solution into equal portions; add one portion anhydrous isopropanol or anhydrous ethyl acetate to two portions NC dispersion in separate trials. The resulting precipitate has no visible PL. The source does not give centrifugation settings or assign these trials to particular five-series variants.','ipa-trial/etoac-trial',[Q('antisolvent:dispersion portions','1:2','ratio_parts')],['G4'])
F('meoac-trial','main',2,'Purification of CsMnCl3 NCs','Methyl acetate trial','Add anhydrous MeOAc at a 1:1 volume ratio to prepurified NC suspension, then centrifuge at 12000 rpm. A white-pinkish precipitate with structural and optical properties similar to the first-purification product is reported. Time, quantitative recovery and exact specimen identities are unreported.','meoac-trial',[Q('MeOAc:prepurified suspension volume ratio','1:1','ratio_parts'),Q('centrifuge speed','12000','rpm')],['G4'])
F('xrd-prep','main',2,'Characterization Techniques','Diffraction specimens','Drop-cast as-synthesized dispersions on precleaned microscopy cover glass, using similar thickness for comparison. No deposited volume or measured thickness is given.','five-series-xrd',[Q('cover-glass side 1','20','mm'),Q('cover-glass side 2','20','mm')],['G3'])
F('xrd-acquire','main',2,'Characterization Techniques','XRD acquisition and refinement','Use a Malvern Panalytical Empyrean Alpha 1 diffractometer in powder geometry under identical scan settings. HighScore supplies Rietveld analysis; VESTA supplies crystal illustrations. The native tables are reported refinement results, not a validated exportable atomistic model.','five-series-xrd',[Q('Cu Kalpha wavelength','1.5406','angstrom'),Q('cathode voltage','45','kV'),Q('cathode current','40','mA'),Q('scan interval','4-62','degree_2theta'),Q('step size','0.0262','degree_2theta'),Q('time per step','17','s')],['G5'])
F('xrd-ambient','main',3,'Structural and Morphological Analysis','Diffraction environment','All five NC XRD patterns are recorded in ambient conditions.','five-series-xrd',[Q('relative humidity','~40','%'),Q('temperature','25','degC')])
F('tem','main',2,'Characterization Techniques','TEM and SAED specimens','Drop-cast 20 µL of NC dispersion in hexane, adjusted to absorbance 0.2 at 280 nm, on carbon-coated Cu grids. TEM uses JEM-F200 at 200 kV. Figures 3 and S2 provide corresponding SAED assignments; no universal same-particle identity across methods is established.','five-series-tem',[Q('deposition aliquot','20','uL'),Q('absorbance at 280 nm','0.2','dimensionless'),Q('absorbance wavelength','280','nm'),Q('accelerating voltage','200','kV')],['G3'])
F('optical-acquisition','main',2,'Characterization Techniques','Absorption, PL, quantum yield and decay','Use Shimadzu UV-3600 UV-vis-NIR for absorption and FLS1000 Edinburgh with integrating sphere and microflash lamp for steady PL, absolute QY and TRPL.','optical-dispersions',[Q('microflash lamp frequency','100','Hz')],['G3'])
F('stability-storage','main',3,'Characterization continuation','Ambient storage protocol','Monitor the same diluted NC dispersions stored in the dark at ambient RH about 40% and 25 °C. Film XRD storage and dispersion PL stability are separate measurement specimens.','stability',[Q('relative humidity','~40','%'),Q('temperature','25','degC')],['G3'])
F('ta-acquisition','main',3,'Ultrafast TA methods','Transient absorption apparatus','Measure dispersions in a 2 mm quartz cuvette using 300 nm laser pulses (Libra F/Topas C), heavy-water white continuum probe and ExciPro CCD detection. Figure 6 supplies the 80 µW excitation condition.','ta-three-samples',[Q('cuvette thickness','2','mm'),Q('laser excitation wavelength','300','nm'),Q('time resolution','~150','fs')],['G3'])
F('ta-power','main',7,'Figure 6 caption','TA plotted conditions','Figure 6 compares nc150, nc180-07 and nc180-05 under 300 nm/80 µW excitation. Decays are monitored at 445 nm for nc150 and 550 nm for the two rhombohedral samples.','ta-three-samples',[Q('excitation wavelength','300','nm'),Q('excitation power','80','uW'),Q('cubic probe wavelength','445','nm'),Q('rhombohedral probe wavelength','550','nm')])
F('icp','main',3,'ICP-MS methods','Composition analysis preparation','Dissolve purified precipitates in concentrated HNO3, then dilute and measure in 2% HNO3 using Thermo Scientific iCAP RQ. Cs and Mn ionic standards span the stated range in 2% HNO3 (Romil-SpA super-pure chemicals); Milli-Q water supplies dilution. Concentrated-acid volume and the basis of the 2% value are unspecified.','icp-five-series',[Q('HNO3 matrix concentration','2','%'),Q('ionic standard concentration interval','0.001-1000','ug/L'),Q('Milli-Q water resistivity','18.2','Mohm cm')],['G4'])
F('ltpl','main',3,'Low-temperature PL methods','Low-temperature film PL','Deposit NCs on silica substrate and measure in CTI CCS-150 cryostat from 30 to 293 K at 20 K intervals, excited by a pE-4000 CoolLED at 380 nm. Figure 7 says cool initially to 30 K and then increase temperature; this is the acquisition order despite prose describing cooling trends.','ltpl-nc180-05',[Q('temperature interval','30-293','K'),Q('temperature increment','20','K'),Q('excitation wavelength','380','nm')],['G3'])
F('dft-method','main',3,'DFT Calculations','Theory inputs and settings','Use primitive cell models based on reported cubic and rhombohedral structures; determine most stable magnetic state then bands. HSE06 and zero-order regular approximation treat scalar relativity. Γ-centered k meshes are 6×6×6 for cubic and 3×3×3 for rhombohedral. No computed state is a direct measured nanocrystal configuration.','dft-cubic/dft-rhombohedral',[Q('cubic k-grid','6:6:6','grid_dimensions'),Q('rhombohedral k-grid','3:3:3','grid_dimensions')],['G5'],kind='reported_model')
F('dft-exchange','main',5,'DFT discussion','Magnetic and functional interpretation','FHI-aims implements HSE06 with 25% screened Hartree-Fock exchange. Cubic G-type AFM is favored; rhombohedral nearest-neighbor Mn2+ sites with unpaired 3d5 electrons favor opposite-spin AFM. These are calculation results, not measured magnetic moments.','dft-cubic/dft-rhombohedral',[Q('screened Hartree-Fock fraction','25','%')],['G5'],kind='reported_model')
F('lsc-setup','main',3,'LSC Setup','Photocurrent proof-of-concept setup','A thin NC film is deposited on glass; its edge is placed directly on a silicon pn photodiode. Cover the surrounding diode area opaquely, place it in a dark box and illuminate perpendicular to the glass center using a lens-collimated warm-white-like beam. The experimental film is unencapsulated, not a demonstrated polymer-embedded recipe.','lsc-film',[Q('window edge length','~2','cm'),Q('window edge thickness','~0.15','cm'),Q('photodiode side 1','2','cm'),Q('photodiode side 2','2','cm'),Q('beam spectrum','400-700','nm'),Q('spot diameter','~1.6','cm'),Q('beam power','~9.5','mW'),Q('applied bias interval','-5-0.5','V')],['G6'])
F('temperature-outcome','main',3,'Results first paragraph','Synthesis temperature outcomes','Below 150 °C no NC formation is reported. Products at 200 °C have lower QY than products at 180 °C. This unsuccessful lower-temperature observation is retained without invented trial temperatures or yields.','below150/nc200/nc180',[Q('no-formation temperature boundary','<150','degC')],['G2'])
F('phase','main',3,'Structural analysis, continued main4','Reported phase assignment','The 150@ sample is assigned cubic Pm-3m, corner-sharing MnCl6 in three dimensions. Products at 180 and 200 °C are assigned rhombohedral R-3m, with face-sharing Mn3Cl12 motifs linked into a three-dimensional framework. The 1D label describes the chain/polyhedral motif and does not mean an isolated chain-only product.','five-series',flags=['C1','C7','G5'])
F('phase-hypothesis','main',3,'Structural analysis','Metastability hypothesis','The authors hypothesize high surface energy of small cubic NCs stabilizes a kinetically trapped high-pressure-like structure at ambient pressure. This is a mechanistic interpretation, not a measured formation free energy. Prior bulk heating at 300 °C for a few hours is cited background rather than the current colloidal route.','phase-model',[Q('cited bulk conversion temperature','300','degC'),Q('cited bulk conversion duration','a few hours',None)],['G5'],kind='author_interpretation')
F('icp-result','si',7,'Table S3','Measured composition ratios','ICP-MS reports near-unity Mn:Cs ratios for all five named samples with the printed uncertainties. These analytical composition ratios are distinct from the precursor-loading labels 0.7/0.5/0.35.','icp-five-series',flags=['G3'])
F('morphology','main',5,'Morphology paragraph','Particle morphology and prose sizes','The cubic sample is mixed morphology, predominantly rods. At 180 °C the 0.7 particles are truncated spheres and reducing the loading ratio toward 0.35 produces clearer edges/hexagonal shapes. Main prose gives diameters 10.8±0.8 to13.4±1.0 nm and calls the cubic 3.9±0.9 nm a length; native histograms use diameter and different error labels.','five-series',[Q('prose lower diameter','10.8±0.8','nm'),Q('prose upper diameter','13.4±1.0','nm'),Q('prose nanorod length','3.9±0.9','nm')],['C2','C3'])
F('tem-histograms','si',5,'Figure S3; main Figure3d','Source histogram values','Figure S3 gives nc150 3.9±0.9 nm, nc180-07 11.0±1.0 nm, nc200 10.8±0.8 nm and nc180-035 13.4±0.8 nm. Figure3d separately gives nc180-05 13.4±0.9 nm. Histograms count sizes, not independently identified batches or shape models.','five-series',[Q('nc150 diameter S3a','3.9±0.9','nm'),Q('nc180-07 diameter S3b','11.0±1.0','nm'),Q('nc200 diameter S3c','10.8±0.8','nm'),Q('nc180-035 diameter S3d','13.4±0.8','nm'),Q('nc180-05 diameter Figure3d','13.4±0.9','nm')],['C2','C3'])
F('optical-summary','main',5,'Optical Properties','Measured optical distinction','Cubic NCs absorb at275 nm and are nonemissive; rhombohedral NCs absorb around280 nm and emit near670 nm. The source reports40% QY for the optimized sample,2.6 eV Stokes shift and97 nm FWHM. Main and SI optical gaps are4.8 eV cubic and5.0 eV rhombohedral. TableS4 separately prints282 nm for0.35.','cubic/rhombohedral',[Q('cubic absorption peak','275','nm'),Q('rhombohedral absorption peak prose','280','nm'),Q('PL maximum','670','nm'),Q('optimized PLQY','40','%'),Q('Stokes shift','2.6','eV'),Q('PL FWHM','97','nm'),Q('cubic optical gap','4.8','eV'),Q('rhombohedral optical gap','5.0','eV')],['G3'])
F('distortion','main',5,'Octahedral distortion paragraph','Reported octahedral distortion','The source uses the mean absolute relative Mn-Cl bond-length deviation over six bonds and reports7.8% for rhombohedral versus undistorted cubic octahedra. This is a source structural interpretation, not independently regenerated geometry.','structure-model',[Q('reported rhombohedral distortion','7.8','%')],['G5'],kind='reported_model')
F('bands','main',6,'DFT discussion and Figure5','Computed electronic structure','The cubic CB edge has dispersed Mn4s character, yielding indirect5.18 eV and direct5.37 eV gaps. The rhombohedral system is direct; Figure5c marks Γ states at5.35 and5.37 eV. VB character includes Cl3p/Mn3d with dx2-y2 and dz2; model symmetry/spin restrictions are proposed to explain nonemissive cubic versus emissive rhombohedral behavior.','dft-models',[Q('cubic indirect gap','5.18','eV'),Q('cubic direct gap','5.37','eV'),Q('cubic higher Gamma state','5.95','eV'),Q('rhombohedral Gamma state 1','5.35','eV'),Q('rhombohedral Gamma state 2','5.37','eV'),Q('VB energy reference','0','eV')],['G5'],kind='reported_model')
F('emission-mechanism','main',7,'Bandgap interpretation','Unresolved emission mechanism','Calculated HSE gaps exceed the experimental emission energy and absorption onset. Defects, self-trapping or another unresolved mechanism are proposed; the source does not establish a unique microscopic origin from an exact atomistic structure.','rhombohedral-model',flags=['G5'],kind='author_interpretation')
F('ple','main',7,'PLE paragraph','PLE features and assignments','Monitor the PLE spectrum at670 nm. Six additional peaks are assigned with crystal-field/Tanabe-Sugano reasoning; TableS5 gives literal wavenumbers/term symbols.','rhombohedral-ple',[Q('monitored PL wavelength','670','nm'),Q('PLE peak1','335','nm'),Q('PLE peak2','355','nm'),Q('PLE peak3','370','nm'),Q('PLE peak4','420','nm'),Q('PLE peak5','450','nm'),Q('PLE peak6','530','nm'),Q('band-edge PLE feature','280','nm')],['C10'],kind='reported_interpretation')
F('crystal-field','main',7,'Crystal field discussion/TableS5','Calculated crystal-field parameters','Using the lowest d-d transitions near450 and530 nm, the authors obtain Racah B and splitting Δ. These are spectroscopic model parameters, not measured bond lengths.','rhombohedral-ple',[Q('Racah B','770','cm^-1'),Q('Racah B alternative units','0.095','eV'),Q('splitting Delta','8601','cm^-1'),Q('splitting Delta alternative units','1.06','eV')],['C10'],kind='reported_model')
F('qy-series','main',7,'PLQY and Mn-Mn discussion','Loading ratio and luminescence trend','At180 °C,0.5 gives40% QY,0.7 around12%, and0.35 gives24%; corresponding reported Mn-Mn separations are3.52,3.13 and3.17 Å. The source correlates separation and QY while acknowledging surface-trap effects; it does not identify ligand coverage.','nc180-05/nc180-07/nc180-035',[Q('nc180-05 QY','40','%'),Q('nc180-07 QY','~12','%'),Q('nc180-035 QY','24','%'),Q('nc180-05 Mn-Mn','3.52','angstrom'),Q('nc180-07 Mn-Mn','3.13','angstrom'),Q('nc180-035 Mn-Mn','3.17','angstrom')],['C4','G5'])
F('excitation-qy','main',7,'Excitation dependence and Figure4c','Excitation-dependent QY','The most intense d-d PLE peak around420 nm yields the largest QY. Figure4c uses two distinct source loading variants. Emission maxima and shape are reported invariant across180/200 °C and ratio variants; the prose size interval10.8–15.5 nm differs from the plotted histogram endpoints.','rhombohedral-series',[Q('largest QY excitation','420','nm'),Q('prose emissive size interval','10.8-15.5','nm')],['C2','C4'])
F('trpl','main',8,'TRPL first paragraph and TableS6','TRPL lifetimes','Rhombohedral decays are fitted with a biexponential model and described as around240 µs. SI TableS6 contains individual coefficients, lifetimes and averages. The printed averaging equation and tabulated values are retained separately without silent correction.','nc180-05-trpl',[Q('approximate PL lifetime','~240','us'),Q('reported Mn-Mn interval','3.12-3.52','angstrom')],['C8'],kind='reported_model')
F('ta-ste','main',8,'STE Formation','TA spectra and STE interpretation','Rhombohedral samples show broad positive PIA extending toward750 nm, unlike the cubic signal up to about560 nm. A redshift after1.5 ps in nc180-05 and long-lived decay are assigned to STEs; assignments remain an author interpretation.','ta-three-samples',[Q('rhombohedral PIA tail','750','nm'),Q('cubic PIA tail','~560','nm'),Q('redshift after elapsed time','1.5','ps')],['G5'],kind='author_interpretation')
F('ta-components','main',8,'STE Formation and Table1','TA fitted components','Fit cubic data biexponentially and rhombohedral data triexponentially. The authors assign fast τ1<2 ps to carrier trapping, τ2<200 ps to energy transfer and τ3>8 ns to STE-related radiative recombination. The cubic signal instead includes a negative tail. Exact fitted values are in Table1.','ta-three-samples',[Q('fast lifetime boundary','<2','ps'),Q('intermediate lifetime boundary','<200','ps'),Q('slow lifetime boundary','>8','ns')],['G5'],kind='reported_interpretation')
F('ta-below-gap','si',11,'FigureS6, mainp8 discussion','Excitation-dependent TA control','For nc180-07, FigureS6 compares300,370 and420 nm excitation and monitors the decay at600 nm. The source interprets the370/420 nm response as not producing STEs. The description of300 nm as above-gap has unresolved tension with the reported~5 eV optical gap.','nc180-07-ta',[Q('probe wavelength','600','nm'),Q('excitation1','300','nm'),Q('excitation2','370','nm'),Q('excitation3','420','nm')],['C11'],kind='author_interpretation')
F('ltpl-shift','main',8,'Low-temperature PL discussion','Temperature-dependent peak position','For optimized nc180-05, the deposited-film PL maximum is described as655 nm at room temperature, shifting to about680 nm near110 K, then673 nm below100 K. This specimen/acquisition context must not silently replace the670 nm solution-spectrum peak.','ltpl-nc180-05',[Q('room-temperature peak','655','nm'),Q('intermediate peak','~680','nm'),Q('intermediate temperature','~110','K'),Q('low-temperature peak','673','nm'),Q('low-temperature regime','<100','K')],['G3'])
F('binding-energy','main',8,'Thermal-quenching equation and Figure7','Thermal-quenching model','Fit integrated PL over100–300 K with the printed activated-quenching expression and obtain exciton binding energy100±18 meV. This fitted parameter is not direct atomistic evidence. Figure7b separately prints I0=26.8,A=96.7 and R-squared0.96.','ltpl-nc180-05',[Q('fit temperature interval','100-300','K'),Q('fitted exciton binding energy','100±18','meV'),Q('Figure7b I0','26.8','relative_intensity'),Q('Figure7b A','96.7','dimensionless'),Q('Figure7b R squared','0.96','dimensionless')],['G5'],kind='reported_model')
F('ltpl-width','main',8,'FWHM discussion and FigureS7','Low-temperature emission width','The FWHM decreases from69 to52 meV as the sample cools from293 to50 K; reduced phonon coupling is proposed. FigureS7 labels meV, so no conversion into nm is assumed.','ltpl-nc180-05',[Q('warm FWHM','69','meV'),Q('cold FWHM','52','meV'),Q('warm temperature','293','K'),Q('cold temperature','50','K')],kind='reported_interpretation')
F('phase-stability','main',8,'Structural and Emission Stabilities, continuedp9','Stored-film phase stability','Rhombohedral film diffraction remains similar after3 months, whereas cubic150@ changes after9 weeks in air. FigureS8 gives separate aged-phase refinement fractions. Film phase stability is distinct from dispersion luminescence stability.','cubic-film/rhombohedral-film',[Q('rhombohedral structural observation','3','month'),Q('cubic aging time','9','week')],['G3'])
F('aged-phase-fractions','si',13,'FigureS8 legend','Source-reported aged cubic refinement','The fresh150@ pattern is labeled100% cubicCsMnCl3. The aged pattern is labeled88.1% CsCl,4.5% Cs3MnCl5 and7.4% CsMn4Cl9. These are author-refined phase assignments/fractions with no supplied uncertainty or independent structural validation.','aged-nc150',[Q('fresh cubic CsMnCl3 fraction','100','%'),Q('aged CsCl fraction','88.1','%'),Q('aged Cs3MnCl5 fraction','4.5','%'),Q('aged CsMn4Cl9 fraction','7.4','%')],['G5'],kind='reported_model')
F('pl-stability','main',9,'Stability paragraph and Figure8b','Luminescence degradation','The prose calls the retained quantity PLQY/PL efficiency and states>70% after1 week,50% after20 days and5% after55 days; Figure8b labels normalized integrated PL and the endpoint appears closer to0.15. Preserve the prose values and original plot without declaring them interchangeable.','rhombohedral-dispersion',[Q('retained after one week','>70','%'),Q('first observation time','1','week'),Q('retained after twenty days','50','%'),Q('second time','20','day'),Q('prose retained after fifty-five days','5','%'),Q('third time','55','day')],['C9'])
F('aged-tem','si',13,'FigureS9; mainp9','Aged morphology interpretation','TEM of aged rhombohedral NCs shows partial aggregation. The source proposes ligand stripping and newly formed surface/structural defects as quenching pathways, without measured ligand coverage or exact aged batch/age assignment for these images.','aged-rhombohedral',[Q('storage RH','~40','%'),Q('storage temperature','25','degC')],['G3','G5'],kind='author_interpretation')
F('lsc-result','main',10,'LSC results and Figure9','Measured device comparison','Dark, bare-glass, fresh-NC-film glass and the same film aged11 weeks are compared. NC-film photocurrent is about an order of magnitude above bare glass and approximately four orders above dark current. Aging lowers it nearly threefold but leaves it above reference. No precise absolute current or device efficiency is inferred from the curves.','lsc-film',[Q('film aging time','11','week'),Q('fresh/bare order difference','~1','order_of_magnitude'),Q('fresh/dark order difference','~4','order_of_magnitude'),Q('aging current reduction factor','~3','ratio')],['G6'])
F('outlook','main',10,'Conclusions','Conclusions and unresolved improvements','The authors propose ligand engineering to improve passivation, QY and stability. Protective-matrix integration is a future expectation; no polymer encapsulation recipe or successful long-term protected device is supplied.','outlook',flags=['G5','G6'],kind='author_interpretation')
F('source-availability','main',10,'Associated Content','Supporting information scope','The main declares a PDF containing synthesis photos, TEM/size distributions, Rietveld parameters, optical fits and stability data. The locally matched13-page SI is fully read. No separate CIF, raw XRD, raw optical dataset or DFT input file is declared in this Associated Content list.','source-availability',flags=['G5'])

# Rows below are manually transcribed from native tables; no numeric token repair.
TABLES=[
('table-1','main',8,'TA decay fits',['sample','A1','tau1','A2','tau2','A3','tau3'],[None,'%', 'ps','%','ps','%','ps'],'''150@NCs|95.8|0.4|4.2|47.1||
180@NCs//0.7|70.9|1.5|10.6|152.7|18.5|8026.8
180@NCs//0.5|71.8|1.1|11.2|161.7|17.0|8525.1'''),
('table-s1','si',6,'Lattice parameters and fit statistics',['sample','space_group','a','b','c','V','Rwp','chi_squared'],[None,None,'angstrom','angstrom','angstrom','angstrom^3','%',None],'''NCs@150|Pm-3m|10.23|10.23|10.23|1072.03|2.06|2.90
NCs@180//0.7|R-3m|7.27|7.27|27.23|1245.89|1.54|2.23
NCs@180//0.5|R-3m|7.30|7.30|27.19|1255.17|1.27|1.78
NCs@180//0.35|R-3m|7.30|7.30|27.22|1254.61|1.57|2.22
NCs@200|R-3m|7.29|7.29|28.03|1289.91|2.31|3.57'''),
('table-s2','si',6,'Rietveld atomic parameters',['sample','atom','Wyckoff','sof','x','y','z','B'],[None,None,None,None,'fractional','fractional','fractional','10^4 pm^2'],'''NCs@150|Cs1|1b|1|0.5|0.5|0.5|0.5
NCs@150|Mn1|1a|0|0|0|0|0.5
NCs@150|Cl1|3d|0|0.5|0|0|0
NCs@180//0.7|Cs1|4b|1|0|0.25|0.625|2.97
NCs@180//0.7|Mn1|16f|1|0.105|0.0426|0.1323|1.6
NCs@180//0.7|Cl1|16f|1|0.1041|0.0521|0.369|1.64
NCs@180//0.7|Cl2|16f|1|0.2903|0.1539|0.1307|1.35
NCs@180//0.7|Cl3|4a|1|0|0.25|0.125|1.71
NCs@180//0.5|Cs1|3a|1|0|0|0|2.01077
NCs@180//0.5|Cs2|6c|1|0|0|0.2185|2.00025
NCs@180//0.5|Mn1|3b|1|0|0|0.5|1.16154
NCs@180//0.5|Mn2|6c|1|0|0|0.3836|1.31244
NCs@180//0.5|Cl2|9e|1|0.5|0|0|2.4775
NCs@180//0.5|Cl1|18h|1|0.49093|0.50907|0.22447|1.61072
NCs@180//0.35|Cs1|3a|1|0|0|0|2.01077
NCs@180//0.35|Cs2|6c|1|0|0|0.2185|2.00025
NCs@180//0.35|Mn1|3b|1|0|0|0.5|1.16154
NCs@180//0.35|Mn2|6c|1|0|0|0.3836|1.31244
NCs@180//0.35|Cl1|9e|1|0.5|0|0|2.4775
NCs@180//0.35|Cl2|18h|1|0.49093|0.50907|0.22447|1.61072'''),
('table-s3','si',7,'ICP-MS Mn:Cs ratios',['sample','Mn_Cs'],[None,'ratio'],'''NCs@150|0.98±0.11
NCs@180//0.7|1.02±0.13
NCs@200|1.02±0.11
NCs@180//0.5|1.04±0.14
NCs@180//0.35|0.99±0.12'''),
('table-s4','si',9,'Optical-property summary',['sample','absorption_peak','band_gap','PL_peak','FWHM'],[None,'nm','eV','nm','nm'],'''temperature150|275|4.8|-|-
temperature180|280|5.0|670|97
temperature200|280|5.0|670|97
ratio0.7|280|5.0|670|97
ratio0.5|280|5.0|670|97
ratio0.35|282|5.0|670|97'''),
('table-s5','si',10,'d-d assignments and crystal-field parameters',['transition_or_parameter','wavenumber'],[None,'cm^-1'],'''6A1 → 4T1(G)|18868
6A1 → 4T2(G)|22371
6A1 → 4A1,4E(G)|23810
6A1 → 4T2g(D)|26882
6A1 → 4E(D)|28011
6A1 → 4T1(P)|29940
Delta/B|11.18
B|770
Delta|8601'''),
('table-s6','si',10,'Excitation-dependent optimized-sample TRPL',['lambda_ex','A1','tau1','A2','tau2','tau_avg'],['nm','%','us','%','us','us'],'''280|85.63|182.7|14.37|397.4|240.12
330|86.48|185.6|13.52|415.3|245.13
355|89.14|195.3|10.86|405.4|237.71
370|88.85|194.1|11.15|414.1|240.56
420|87.56|189.0|12.44|417.2|243.50
445|83.83|184.1|16.17|388.5|243.23
530|86.14|181.8|13.86|407.3|241.55''')]

CONFLICTS=[
('C1','Figure2 caption and visible reference phases','main',4,'Figure2a/h and caption','Caption pairs(a,h) with cubic/rhombohedral and codes04-007-9082/01-073-02227; visible a is rhombohedral#01-073-0227 and h is cubic#04-007-9082. Caption also says manganese iodide while the chemistry/legend is chloride. Preserve literal original and label ambiguity.'),
('C2','Reported size summaries differ','main',5,'Morphology paragraph; main7; Figure3d and S3','Main5 upper size13.4±1.0 differs from Figure3d13.4±0.9 and S3d13.4±0.8; main7 gives10.8–15.5 nm while the shown mean values top out13.4. Each source value retains its original scope.'),
('C3','Rod dimension and polygon naming','si',5,'FigureS3 caption; main5','Main5 calls cubic3.9±0.9 nm a length while S3 calls diameter. Captions call polygon diameters pentagons while main describes hexagons/truncated spheres. No shape or dimension repair.'),
('C4','Ratio naming and nonuniform sample legend conventions','main',5,'Figure4c caption; SI8 FigureS4','Figure4c says Cs/Mn although methods and sample labels use Mn/Cs. S4a/c/d legends use1:3 and1:4 whereas S4b uses0.5 and0.35. Retain source-defined conditions and flag cross-legend association instead of equating inverted ratios.'),
('C5','TEM panel indices conflict','si',4,'FigureS2 panels/caption continuedS5','Third row labels are c1,c3,c2 rather than the caption convention x1,x2,x3; the final visible row d is called(e) in the caption. Panel content/source sample labels remain explicit.'),
('C6','Excitation wavelength330 versus335','si',10,'TableS6 second row versus FigureS5 legends','TableS6 prints330 nm; FigureS5 legends print335 nm. Do not silently overwrite either.'),
('C7','Structural tables require model qualification','si',6,'TablesS1-S2 continuedS7','S2 prints zero Mn1 and Cl1 occupancies for cubic150@; nc180-07 has4b/16f/4a labels unlike the S1 R-3m entry. Cubic a10.23 Å and remaining settings lack independent reconstruction. S2 gives identical position/B numbers for0.5/0.35 with exchanged Cl labels and no200@ coordinate block. Literal tables are retained; no corrected CIF or exact structure label is approved.'),
('C8','Printed average-lifetime expression differs from numerical means','si',10,'TableS6 footnote','Printed tau_avg=sum Ai*taui with Ai percentages does not reproduce the table averages even when normalized by100. For280 nm it gives213.55209 µs, not240.12 µs. Preserve formula, coefficients and tabulated results without silently choosing another expression.'),
('C9','Stability prose and plotted observable/endpoints','main',9,'Figure8b and stability prose','Prose labels retention PLQY/PL efficiency and states5% at55days; plot labels normalized integrated PL and visually ends near0.15. Plot reading is qualitative, not a replacement exact value.'),
('C10','Transition labels and unit context','si',10,'TableS5','Delta/B=11.18 appears under the common wavenumber heading but is a dimensionless ratio by its expression. PLE peak labels/main rounded wavelengths differ slightly from exact table wavenumbers; retain separate literal and interpreted units.'),
('C11','Above-gap interpretation versus reported optical gap','main',8,'STE discussion; Figure6 and S6','The authors describe300 nm excitation as enabling above-gap carriers while optical gaps are~4.8–5.0 eV. No source correction or new microscopic mechanism is inferred; these are distinct source statements.'),
('C12','LSC embedded wording versus actual film','main',10,'Figure9 caption versus main3 methods and main10 text','Figure9 says embedded NCs but methods specify a deposited NC film and main10 explicitly unencapsulated. No polymer/protective matrix preparation is supplied; retain actual deposited-film scope.')]
GAPS=[
('G1','Reagent identity and drying detail','Dry ODE/OA/OlAm and anhydrous solvents are named without their full drying protocols; ODE/technical ligand isomer distributions and surface coverage are not measured.'),
('G2','Reproducibility quantities','Stock final volume/molarity, Ar/vacuum pressure, injection speed, stirring rpm, cooling trace, numerical overnight duration, primary redispersion amount and synthetic yield are absent. Source loading labels are retained without reconstructed molarity.'),
('G3','Specimen association','Five preparation labels are supported, but independent batch counts, exact aliquot sharing across measurements, deposition thicknesses and every stability/LSC sample loading label are not supplied. A common material family is not proof of the same specimen.'),
('G4','Purification and analytical preparation detail','Alternative precipitation times, exact tested variant, fraction recovery, acid volumes and percentage basis are incomplete. Failed/no-visible-precipitation trials remain part of the source.'),
('G5','Atomic/theory and model limits','Printed coordinates, occupancies, B values and spacegroups are retained literally but require separate symmetry/geometry/scattering validation. No CIF, raw refinement or DFT input file is supplied in this local pair. Author interpretations of STEs, passivation and fitted parameters are not exact measured atomistic labels.'),
('G6','Device implementation and future work','LSC film loading, thickness, preparation/drying detail, exact loading variant and device efficiency are absent. Protective polymer encapsulation and ligand engineering are proposed future work, not an observed current synthesis.')]
