from pathlib import Path
from datetime import datetime,timezone
import json,subprocess,sys
A=Path(__file__).resolve().parent;MON=A.parents[2];M=A.parents[4]
read=lambda p:json.loads(p.read_text('utf8'))
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n','utf8')
now=datetime.now(timezone.utc).isoformat();ed=read(MON/'public-progress-editorial.json')
ed['current_work']=[
 {'short_label':'Matuhina et al. (2023)','title':'Role of CsMnCl3 Nanocrystal Structure on Its Luminescence Properties','stage':'Source and structured reader audits passed; visual and website integration gates in progress','summary':'All 13 main and 13 matched SI pages have been read and independently audited. The structured contribution retains five paired synthesis conditions, 21 records, 39 operations, 30 original crops and source-specific specimen assignments. Canonical/reader, apparatus and product-context audits passed; molecular review and website integration are tracked separately.','stages':[{'label':'Main/SI pairing, complete source reading and extraction','status':'complete','detail':'Independent source audit passed after correcting the description of the two Tauc-plot axis exponents. Original contradictory values remain explicit.'},{'label':'Structured data and reader','status':'complete','detail':'21 records and 380 reader items independently checked against source facts, typed quantities, table cells and sample contexts.'},{'label':'Illustrations and public website','status':'in_progress','detail':'39 apparatus scenes and 47 symbolic product-context mappings passed their separate audits. Molecular and integrated browser/publication gates remain separate.'}],'gaps':['Printed atomic-coordinate tables require further qualification; no exact atomistic training pair is approved.','Local reviewed proposals are not yet a new public science release.']},
 {'short_label':'Pati et al. (2009)','title':'Precipitation of Nanocrystalline CeO2 Using Triethanolamine','stage':'Complete main/SI source audit passed; structured records and reader in preparation','summary':'All four main and four SI pages are read and independently audited. Extraction retains alcohol-specific precipitation, workup/calcination, particle characterization and the complete SI XPS table. Main/SI identity uses the paper declaration, matching content and embedded document metadata.','stages':[{'label':'Source pairing, complete reading and extraction','status':'complete','detail':'The frozen source extraction passed independent review without corrections. The SI has no title/byline; supporting pairing evidence is recorded.'},{'label':'Canonical records, reader and illustrations','status':'in_progress','detail':'Separate alcohol routes, six stocks, specimen states and XPS contexts are being mapped. A distinct reviewer will audit the frozen proposal.'}],'gaps':['The as-prepared whole-specimen composition is not established by local CeO2 lattice fringes.','Source formula, particle-size metric and XPS label discrepancies remain explicit.']}
]
ed['estimate']['current_batch']='Matuhina CsMnCl₃ source, canonical/reader, apparatus and symbolic-context audits passed; molecule/site gates continue. Pati CeO₂ main/SI source extraction passed independent review and its structured reader is in preparation. Whole-corpus finish date remains unvalidated.'
ed['recent_milestones'].insert(0,{'at':now,'text':'Matuhina and Pati complete supplied main/SI source extractions passed separate audits. Matuhina structured data/reader, 39 apparatus scenes and 47 symbolic product-context mappings also passed their scoped audits. These private proposals remain outside the live scientific dataset pending remaining website gates.'})
D=MON/'deadline-20260920';active=read(D/'active-cutoff.json');partpath=D/'matuhina-review-scope-20260920.json'
subprocess.run([sys.executable,str(D/'partition_deadline_scope.py'),'--cutoff-manifest',active['cutoff_manifest']['path'],'--ledger',str(MON/'ledger.json'),'--output',str(partpath)],check=True,capture_output=True)
part=read(partpath);n=part['counts']['included_pending_scopes']
ed['workflow'].update(fixed_pending_provisional_scopes=n,scope_counts_updated_at=now,later_arrival_groups_current=part['counts']['later_arrival_group_candidates'],later_arrival_file_candidates_current=part['counts']['later_arrival_file_candidates'])
save(MON/'public-progress-editorial.json',ed)
p=M/'MEMORY.md';p.write_text(f'''## 2026-09-20 — Parallel review checkpoint; source/data gates kept separate

Saved {now}. User-authorized screen-first, evidence-ranked parallel extraction and independent per-paper audit continue. Fixed-cutoff screening accounts for13,831 top-level copies; three nested identity cases remain held. Later arrivals remain separate; latest partition at research-assets/incoming-paper-monitor/deadline-20260920/matuhina-review-scope-20260920.json. Screening is neither full scientific review nor a no-recipe decision. No paid API run or source download is authorized by this checkpoint.

Matuhina2023 CsMnCl3 full main13+SI13 source v2 passed (2ace0d73…); canonical/reader v1 passed unchanged (db000b5e…),21records/39operations/380readeritems/678measurements. Root product-context audit passed (5816c413…),47mappings/45record-sample contexts/seven symbolic assets; Peng apparatus audit passed(42ccc8a9…),39scenes168rows. Molecular package91666cff… is with Peng for distinct audit. Root prepare_site_proposal.py and import/build helpers exist outside Site; promotion/transport/browser/live gates remain separate. Source SI coordinate tables exist but are not qualified exact atomic models. Five preparation choices are paired alternatives, not a Cartesian series or independent physical-batch count. Aging films, optical dispersions, ICP digests and LSC films retain separate contexts.

Pati2009 CeO2 source freeze b2d275bd… independently passed(792fe4a1…),four main+four SI pages. Backlog now authors canonical/reader; Norberg remains separate auditor. Preserve as-prepared unresolved bulk identity despite local CeO2 fringes, alcohol branches and literal XPS conflicts. Source files unchanged.

Live science remains0.29.0(586records114routes47hubs37sourcegroups32readers) until exact verified release. Public/memory/skills/reference sync uses filtered projections; original PDFs/SI/full text/full pages remain local. Continue from immutable passed packages rather than rerunning their reviews.

'''+p.read_text('utf8'),'utf8')
print(json.dumps({'status':'saved_local_progress_and_memory','pending_cutoff_scopes':n,'counts':part['counts']}))
