assets={a['id']:a for a in manifest['assets']};groups={k:[] for k in ['figures','tables','schemes','equations','source_notes']}
def asset(key,group,caption,scope,rs,classification,notes=(),panels=(),axes=()):
 a=assets[key];e=ev(a['source_pdf_page'],a['label'])
 groups[group].append({'id':key,'label':a['label'],'document_role':'main','page':a['source_pdf_page'],'printed_page':e['printed_page'],'source_locators':[e['locator']],'caption_paraphrase':caption,'sample_scope':scope,'sample_links':[P+r for r in rs],'sample_linkage':'Source-defined individual, spherical-assembly, wire, optical or device context. Caption/body ratio conflicts and unassigned physical batch identity are retained.','evidence_class':classification,'public_asset':a['public_asset'],'public_asset_sha256':a['sha256'],'asset_provenance':{'source_file':a['source_filename'],'source_sha256':a['source_sha256'],'source_pdf_page':a['source_pdf_page'],'crop_bbox_pdf_points_top_left':a['crop_bbox_pdf_points_top_left'],'crop_normalized':a['crop_normalized'],'render_dpi':a['render_dpi'],'pixel_dimensions':a['pixel_dimensions'],'renderer':'PDFium 300 dpi original-source crop','transformation':a['transformation']},'quantitative_context':list(notes),'panels':list(panels),'notes':list(notes),'axes':list(axes),'text_reviewed':True,'visual_reviewed':True,'reviewed':False,'reader_render_verified':False,'training_eligible':False,'source_asset_type':a['source_asset_type']})
asset('figure-1','figures','Original individual-particle HRTEM, spherical assembly microscopy, SAED and diameter–time plot.','A: low-ratio approximately5 min aliquot. B–F: spherical assembly series; caption0.5:1:50 differs from method/body0.5:1.2:50.',['individual-structure','sphere-structure'],'experimental_image_and_growth_plot',['A5 nm bar; B/C/D200 nm bars.','B10 min, C25 min, D40 min.','E is the actual polycrystalline SAED pattern.','F is an assembly-diameter plot; no exact digitized data table manufactured.'],['A: individual particle','B–D: assembly growth','E: SAED','F: diameter versus time'],['Diameter / nm, labeled0/200/400','Time / min, labeled0/20/40/60'])
asset('figure-2','figures','Original ordered wire image, junction micrograph and selected-area electron diffraction.','Caption high-ratio preparation conflicts with the body intermediate-ratio90 min description; no unique batch assignment.',['wire-structure'],'experimental_image',['A40 nm bar; B500 nm bar.','C includes020 label, [100] zone-axis assignment and6.1 Å lattice constant.','Dark segments are author-assigned near-zone-axis grains; rotation behavior is reported in text.'],['A: bright-field wire','B: junction','C: SAED'])
asset('figure-3','figures','Original bent-wire overview and high-resolution images at its junction and edge.','High-ratio1:2.5:50 preparation; exact reaction duration not assigned to this image.',['wire-structure'],'experimental_image',['B10 nm scale bar.','A/C3.05 Å(200) fringes; C[100] label.','Approximately10 nm cubic building blocks and6.1 Å rock-salt lattice parameter are source interpretation.'],['A: junction','B: bent assembly','C: edge'])
asset('figure-4','figures','Original near-IR absorption spectra of spherical assemblies after30,35 and40 min.','Caption0.5:1:50 conflicts with the Results0.5:1.2:50 stock;150 °C preparation.',['absorption'],'experimental_spectrum',['All three traces and both horizontal axes preserved.','Body bands1000–1600 nm,0.775–1.240 eV.','Arbitrary-unit spectra are not quantitative concentration or yield measurements.'],['30 min','35 min','40 min'],['Wavelength / nm,500–2500 labels','Upper Energy / eV,2.8/2.1/1.4/0.7 labels','Absorbance / arbitrary units'])
asset('figure-5','figures','Original device schematic, contacted-wire SEM, circuit and three current–voltage curves.','High-ratio1:2.5:50 named in caption; three electrical wires retain separate paired dimensions.',['device-fabrication','electrical'],'experimental_and_schematic',['A/C are author schematics, not atomic structures.','B SEM display3.00 µm and10.0 kV; general method4 kV retained as a separate context.','D squares110×700 nm; circles60×1000 nm; triangles150×1200 nm.','Room-temperature data; no gate-response result supplied.'],['A: wire/substrate surface','B: actual contacted wire','C: circuit and Si back gate','D: I–V data'],['Current / nA','Voltage / mV'])
asset('dipole-model','equations','Original inline dipole-moment and interaction-energy expressions and definitions.','Author model, with r explicitly called diameter and single μ in the printed energy expression.',['assembly-model'],'author_model',['μ estimate500 D and ΔH estimate−28 kJ/mol are author-derived.','Excerpt begins within the source paragraph and continues to the entropy sentence at the column boundary; the continuation is in the assembly-model excerpt.','No dimensional repair or numerical recalculation performed.'])
asset('transport-model','equations','Original electrical model expressions and estimates, including dielectric, capacitance and transfer-energy relations.','Model values derived by the authors from reported room-temperature electrical data.',['transport-model'],'author_model',['Preserves unusual effective dielectric typography and r convention.','E≈V/(εmL), C=4πε0εm(r+D), τ=RC, E_T=πℏ/τ and eED appear in context.','Printed comparison barriers are in µeV.','Paragraph begins as the continuation from the preceding page; no text reflow or equation redraw.'])
for key,rs,caption,scope in [
 ('synthesis-method',routes,'Original precursor ratios, stock preparation, hot injection and two temperature branches.','Paired with the workup-method crop for the sentence that continues into the next column.'),
 ('workup-method',['aliquot-workup'],'Original aliquot-quench and repeated centrifugation workup.','Begins with the continuation of the sampling sentence from the left column.'),
 ('characterization-method',['microscopy','absorption'],'Original instruments and specimen preparation.','SEM, TEM/EDAX/SAED, HRTEM and optical instrumentation; EDAX results are not supplied.'),
 ('device-method',['device-fabrication','electrical'],'Complete original six-step electrical device preparation and optimization caveats.','Unreported annealing and solvent choices remain missing.'),
 ('assembly-model',['assembly-model'],'Original free-energy claim, proposed ordering kinetics and technical-TOPO impurity effect.','Starts with the entropy continuation from dipole-model; author interpretations are not established mechanisms.'),
 ('summary-conflict',['source-context'],'Original summary including stock-ratio and electric-field wording inconsistencies.','Summary0.25:0.6:0.5 and voltage-per-particle wording retained as printed.')]:
 asset(key,'source_notes',caption,scope,rs,'direct_source_excerpt')
links={'figure-1':['individual-hrtem','sphere-morphology','sphere-saed','sphere-growth'],'figure-2':['wire-image','wire-saed','wire-orientation'],'figure-3':['bent-wire'],'figure-4':['absorption-cohorts','absorption-spectrum','absorption-shift'],'figure-5':['device-sem','electrical-specimens','iv-curves','conductivity'],'synthesis-method':['low-stock','intermediate-stock','high-stock','injection','individual-growth','heated-growth'],'workup-method':['aliquot-quench','purification'],'characterization-method':['microscopy-method','microscopy-preparation','absorption-method'],'device-method':['device-surface','device-positioning','device-contacts','contact-optimization'],'dipole-model':['dipole-equation','interaction-energy'],'transport-model':['internal-field','capacitance','transfer-energy','barrier'],'assembly-model':['entropy','kinetic-ordering','topo-impurities'],'summary-conflict':['ratio-conflicts','terminology-conflicts']}
for key,targets in links.items():
 a=assets[key]
 for target in targets:items[target].setdefault('original_assets',[]).append({'id':key,'label':a['label'],'public_asset':a['public_asset'],'public_asset_sha256':a['sha256']})
