route_stock={'individual-low':'low-stock','sphere-intermediate':'intermediate-stock','wire-intermediate':'intermediate-stock','wire-high':'high-stock'}
operation_targets={}
for rid,stock in route_stock.items():operation_targets[rid]={'prepare-stock':stock,'heat-topo':'mother-solution','injection':'injection','grow':{'individual-low':'individual-growth','sphere-intermediate':'sphere-series','wire-intermediate':'wire-intermediate','wire-high':'wire-high'}[rid],'cool':'individual-growth','ramp':'heated-growth'}
operation_targets.update({'aliquot-workup':{'withdraw':'aliquot-quench','quench':'aliquot-quench','centrifuge':'purification','redisperse':'purification','repeat':'purification'},'microscopy':{'deposit':'microscopy-preparation','dry':'microscopy-preparation','tem':'microscopy-method','hrtem':'microscopy-method','sem':'microscopy-method','saed':'microscopy-method','edax':'microscopy-method','microdiffraction':'wire-saed'},'absorption':{'prepare':'absorption-method','measure':'absorption-method'},'device-fabrication':{'hydrophobize':'device-surface','mark':'device-surface','spin-wire':'device-positioning','locate':'device-positioning','coat-resist':'device-positioning','anneal':'device-positioning','write-develop':'device-contacts','evaporate-contacts':'device-contacts','remove-resist':'device-contacts','inspect':'device-contacts'},'electrical':{'measure':'electrical-method','normalize':'conductivity'}})
measurement_targets={}
def mg(record,target,ids):
 for k in ids.split():measurement_targets.setdefault(record,{})[k]=target
for r,t in [('individual-low','individual-growth'),('sphere-intermediate','sphere-series'),('wire-intermediate','wire-intermediate'),('wire-high','wire-high')]:mg(r,t,'framework')
mg('aliquot-workup','aliquot-quench','scope');mg('microscopy','microscopy-method','edax-limit')
mg('device-fabrication','contact-optimization','contact');mg('device-fabrication','electrical-method','gate')
mg('absorption','absorption-cohorts','time-30 time-35 time-40');mg('absorption','absorption-spectrum','bands wavelengths energies');mg('absorption','absorption-shift','redshift blueshift evolution')
mg('individual-structure','individual-morphology','size-range distribution shape');mg('individual-structure','individual-hrtem','f1-time f1-temperature f1-size f1-spacing f1-scale f1-zone endpoint-link')
mg('sphere-structure','sphere-morphology','f1B-time f1B-scale f1C-time f1C-scale f1D-time f1D-scale body-range abstract-range size-scope');mg('sphere-structure','sphere-saed','polycrystal');mg('sphere-structure','sphere-growth','onset plateau')
mg('wire-structure','wire-overview','width-typical length-typical width-growth');mg('wire-structure','wire-image','junction-fraction f2a-scale f2b-scale f2b-time');mg('wire-structure','wire-orientation','orientation helix');mg('wire-structure','wire-saed','f2-cell f2-zone');mg('wire-structure','bent-wire','f3-cell f3-fringe f3-block f3-scale f3-scope')
mg('electrical','electrical-specimens','square-width square-length circle-width circle-length triangle-width triangle-length building-block');mg('electrical','conductivity','resistivity conductivity');mg('electrical','iv-curves','linear');mg('electrical','device-sem','sem-scale');mg('electrical','electrical-scope','transport-limit')
mg('assembly-model','spacing','general-separation present-separation');mg('assembly-model','coupling-boundary','exchange-threshold dipolar-threshold distance-effects');mg('assembly-model','ligand-heating','heated-gap');mg('assembly-model','permanent-dipoles','dipole-origins');mg('assembly-model','dipole-equation','dipole-equation pbse-dielectric topo-dielectric model-diameter dipole');mg('assembly-model','interaction-energy','interaction-equation epsilon0 enthalpy');mg('assembly-model','entropy','free-energy');mg('assembly-model','kinetic-ordering','sphere-time ordered-time order');mg('assembly-model','topo-impurities','impurity-effect impurity')
mg('transport-model','internal-field','field-equation dielectric-equation diameter gap voltage field resistance');mg('transport-model','capacitance','capacitance time capacitance-equation');mg('transport-model','transfer-energy','transfer spacing lifetime-equation transfer-equation');mg('transport-model','barrier','drop barrier drop-equation');mg('transport-model','conductivity-comparators','film-conductivity well-conductivity');mg('transport-model','transport-options','candidates');mg('transport-model','terminology-conflicts','summary-units')
mg('source-context','coverage','scope references');mg('source-context','identity','date');mg('source-context','ratio-conflicts','conflicts');mg('source-context','structure-boundary','structures');mg('source-context','outlook','future');mg('source-context','bulk-context','gap temperature dielectric bohr ratio mass bulk-phase');mg('source-context','literature-optical','prior-gap prior-properties');mg('source-context','prior-synthesis','prior-core-shell wire-width wire-length rod-width rod-length cube');mg('source-context','heated-growth','maximum-extended-duration');mg('source-context','intermediate-stock','caption-intermediate-selenium caption-intermediate-lead_precursor caption-intermediate-tbp');mg('source-context','low-stock','summary-low-selenium summary-low-lead_precursor summary-low-tbp')
material_targets={'topo-reagent':'topo','silica-layer':'device-surface','selenium':'selenium','lead-chxbu':'lead-source','tbp':'tbp'}
stock_targets={'feed-stock':'stock-preparation'}
