from pathlib import Path
B=Path(__file__).resolve().parent;P=B.parent/'jp0105488'
t=(P/'run_build.py').read_text(encoding='utf-8').replace('gerion2001-protocol','braun2001-protocol')
(B/'run_build.py').write_text(t,encoding='utf-8')
t=(P/'build_inventory_actual.py').read_text(encoding='utf-8')
t=t.replace('-gerion-actual-local-snapshot','-braun-actual-local-snapshot').replace("g='gerion2001'","g='braun2001'").replace('paper-reviews/gerion2001.json','paper-reviews/braun2001.json').replace('paper-review.html?id=gerion2001','paper-review.html?id=braun2001')
a=t.index('row={');b=t.index("inv['per_paper']=",a)
row="""row={'source_group':g,'doi':src['doi'],'url':src['url'],'title':src['title'],'year':src['year'],'has_local_corpus_group':src['doi'].lower()in localdois,'review_status':'full_supplied_main_review_si_unverified','review_scope':'All four supplied main pages text and visually reviewed with independent source, canonical, reader, chemical and apparatus audits. Matching local SI not located or verified; cited upstream preparations and theory not independently inspected here.','documents':[{'role':'main','page_count':4,'all_text_read':True,'all_visually_reviewed':True}],'evidence_locator':'data/paper-reviews/braun2001.json','paper_review_url':'paper-review.html?id=braun2001','si_status':'not_located_or_verified','canonical_record_count':len(rr),'synthesis_route_variant_count':len(rr.keys()&routes.keys()),'contextual_control_count':len(rr.keys()&controls.keys()),'contextual_observation_count':len(rr.keys()&observations.keys()),'procedure_count':len(rr.keys()&procedures.keys()),'benchmark_row_count':0,'measurement_entry_count':sum(len(r['measurements'])for r in rr.values()),'record_type_counts':dict(sorted(Counter(r['record_type']for r in rr.values()).items())),'canonical_recipe_family_ids':sorted({r['lineage']['recipe_family']for r in rr.values()}),'direct_route_material_systems':sorted({routes[k]['material']['formula']for k in rr.keys()&routes.keys()}),'record_ids':sorted(rr),'record_urls':{k:'records/'+k+'.html'for k in sorted(rr)},'notes':['Three CdS/HgS/CdS architectures retain A–B–C, A–B–C–B–C and A–B–C–C–C–B–C synthesis sequences. Surface exchange differs from adding a deposited layer.','Three acquisition procedures and three contextual observations preserve optical settings, sample architecture, author interpretation and uninspected cited context.','Four original figures and four experimental source excerpts are preserved. Missing counterions, stabilizer form, feed doses and core-size discrepancies remain explicit.','Architecture diagrams and cited morphology are not measured atomic coordinates; no sample CIF, missing microscopy, XRD, SAED or nanocrystal Raman spectrum is invented.']}
"""
t=t[:a]+row+t[b:]
t=t.replace("'all_gerion_records'","'all_braun_records'").replace("'two_gerion_routes':row['synthesis_route_variant_count']==2","'three_braun_routes':row['synthesis_route_variant_count']==3")
t=t.replace("'no_new_optical_labels':elig['optical_outcome']==95,",'')
(B/'build_inventory_actual.py').write_text(t,encoding='utf-8')
print('Build and actual-inventory helpers prepared; no Site changes yet.')
