from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
write(B/'browser-qa.json',{'status':'passed','at':datetime.now(timezone.utc).isoformat(),'browser':'Codex in-app browser, temporary local tab15','origin':'http://127.0.0.1:5187','checks':['New CdS/HgS/CdS hub shows seven precursor/stock identities and three equal method cards.','System III selection displays sixteen stages. Conditional additional Cd dose remains unquantified, with no inherited temperature or atmosphere.','C4 growth shows25min andpH7 with unknown stock dose; final purge shows at least20min andargon, retaining the colloid. Stage illustration and layout visually inspected.','H2S three-atom computed reference opens in molecular viewer; zoom and mouse rotation exercised and visually inspected.','Original Figure4 opens in enlargement dialog with legible original axes and insets.','Complete paper reader shows85items across all4supplied main pages and explicit unverified SI. Searching3.5 returns5items including the core-size conflict.','Hg periodic-table selection exposes the complete CdS/HgS/CdS system and a clearly labeled HgS component; opening the material reaches its three methods.','Existing CdS hub contains all three Braun methods alongside earlier contributions.','No browser console errors or warnings observed.'],'limitations':['Representative browser interactions preceded only the final reagent-role normalization. Final integrated runtime audit covers those data changes; unchanged assets and interactions are not redundantly re-tested.','No mobile check or interactive check of every asset claimed; all8original crops and all45scenes audited separately.','Matching SI not located or verified.'],'module_hashes':{f:sha(S/'dist'/f)for f in ['braun2001-protocol.mjs','protocol-visuals.mjs','material-hub.mjs','crystal-viewer.mjs']},'reader_sha256':sha(S/'data/paper-reviews/braun2001.json')})
m=read(B/'milestones.json')
m['extract']={'status':'complete','evidence':[str(B/f)for f in ['canonical-record-manifest.json','source-audit.json','public-review-proposal/proposal-validation.json']],'note':'Nine records preserve three routes, three acquisition procedures, three observations,45operations,75measurements,85reader items and132source units.'}
m['audit']={'status':'complete','evidence':[str(B/f)for f in ['canonical-records-audit.json','reader-source-audit.json','molecular-source-audit.json','bindings-source-audit.json','visual-source-audit.json','role-normalization-source-audit.json']],'note':'Independent source, canonical, reader, all8original-crop, molecular, binding and all45apparatus audits passed. Role-only delta independently re-audited; main-only/SI-unverified scope retained.'}
m['integrate']={'status':'complete','evidence':[str(B/f)for f in ['integration-manifest.json','build-validation.json','browser-qa.json','reader-assets/integrated-presentation-audit.json','reader-assets/reader-runtime-check.json']],'note':'Same existing MatterSyn atlas:309records,27hubs,69routes. Build passed;2285integrated and1413runtime checks passed. New material discoverable from periodic table and existing CdS hub.'}
for stage in m.values():
 for f in stage['evidence']:assert Path(f).exists(),f
write(B/'milestones.json',m)
c=read(B/'checkpoint.json');c.update(checkpoint_at=datetime.now(timezone.utc).isoformat(),website_published=False,current_work_items=[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in m.items()],next_action='Publish validated source on the same Site, verify unchanged source bundle, close supplied-main scope and save memory/skills.');write(B/'checkpoint.json',c)
print('Read, extraction, audit and integration complete; native publication pending.')
