import fs from 'node:fs';import path from 'node:path';import {pathToFileURL,fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const O=path.dirname(fileURLToPath(import.meta.url)),S='[local path redacted]',E=path.dirname(O);
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');const checks=[],check=(label,v)=>checks.push({label,passed:!!v});
class El{
 constructor(tag){this.tag=tag;this.children=[];this.attributes={};this.dataset={};this.style={};this.className='';this.textContent='';this.isConnected=true;this.listeners={};this.classList={add:()=>{},toggle:()=>{}};}
 append(...xs){this.children.push(...xs)}replaceChildren(...xs){this.children=[...xs]}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,fn){this.listeners[k]=fn}
 set innerHTML(t){this._html=t;this.children=t.includes('<svg')?[new El('svg')]:[]}get innerHTML(){return this._html||''}
 all(fn){return this.children.flatMap(n=>[...(fn(n)?[n]:[]),...(n.all?.(fn)||[])])}
 querySelector(s){return this.all(n=>s==='svg'?n.tag==='svg':s==='[data-evans-species9]'?!!n.dataset?.evansSpecies9:false)[0]||null}
}
globalThis.document={createElement:t=>new El(t),body:new El('body')};
const products=await import(pathToFileURL(S+'/dist/evans2010-products.mjs'));const protocol=await import(pathToFileURL(S+'/dist/protocol-visuals.mjs'));const scenes=await import(pathToFileURL(S+'/dist/evans2010-protocol.mjs'));
const files=fs.readdirSync(S+'/data/records').filter(f=>f.endsWith('.json'));const records=files.map(f=>read(S+'/data/records/'+f));const before=JSON.stringify(records);
const expected=new Map([['evans-2010-species9-crystallization','species9-crystallization'],['evans-2010-molecular9-structure','species9-cif']]);
const registry=read(S+'/dist/assets/chemical-registry/registry.json'),data={entries:new Map(registry.entries.map(x=>[x.id,x]))};const original=data.entries.get(products.EVANS_SPECIES9.registryId),oldEntry=JSON.stringify(original);let positive=0,productScopes=0,sceneCount=0,rowCount=0;
for(const r of records){
 const ctx=products.evansSpecies9Context(r);check('Only two installed record contexts '+r.record_id,!!ctx===expected.has(r.record_id));if(ctx)positive++;
 for(const p of r.products){check('Exact installed product scope '+r.record_id+'/'+p.sample_id,!!products.evansSpecies9Context(r,p.sample_id)===(expected.get(r.record_id)===p.sample_id));productScopes++;}
 if(!expected.has(r.record_id)){const host=new El('div');let calls=0;const result=await products.mountEvansSpecies9(host,r,{chemicalApi:{chemicalRegistry:()=>{calls++;throw Error('unexpected')}}});check('Foreign record exits before chemical API '+r.record_id,result.mounted===false&&calls===0&&host.children.length===0);}
 if(r.lineage.source_group==='evans2010'&&r.operations.length){
  const host=new El('div');protocol.mountProtocol(host,r);const buttons=host.children[0].children;
  for(let i=0;i<r.operations.length;i++){
   buttons[i].listeners.click();const op=r.operations[i],s=scenes.buildEvans2010Scene(op,r);const grids=host.all(n=>n.tag==='dl'&&n.className==='protocol-condition-grid');
   check('One conditions grid '+op.id,grids.length===1);const rows=grids[0].children.map(n=>({label:n.children[0].textContent,value:n.children[1].textContent}));check('Exact rows with no generic duplicates '+op.id,JSON.stringify(rows)===JSON.stringify(s.rows));
   const art=host.all(n=>n.className==='protocol-art protocol-art-evans2010');check('Installed source apparatus selected '+op.id,art.length===1&&art[0].innerHTML===s.artSvg);check('Source caption selected '+op.id,host.all(n=>n.className==='protocol-visual-note').some(n=>n.textContent===s.caption));sceneCount++;rowCount+=rows.length;
  }
 }
}
for(const [rid,sample]of expected){
 const r=records.find(r=>r.record_id===rid),ctx=products.evansSpecies9Context(r);check('Registry qualification '+rid,!!products.evansSpecies9Entry(data,ctx));
 for(const x of [{...r,lineage:{source_group:'other'}},{...r,material:{formula:'PbSe'}},{...r,products:[]},{...r,record_id:'unbound-same-composition'}])check('Wrong identity refused '+rid,!products.evansSpecies9Context(x));
 check('Wrong explicit sample refused '+rid,!products.evansSpecies9Context(r,'unbound-sample'));
 for(const k of ['formula','depictionKind','svgPath','model3dPath']){const x={...original,[k]:'wrong'};check('Wrong reference field refused '+rid+'/'+k,!products.evansSpecies9Entry({entries:new Map([[x.id,x]])},ctx));}
 for(const k of ['svgPath','model3dPath']){const x={...original,assetHashes:{...original.assetHashes,[k]:'0'.repeat(64)}};check('Wrong asset digest refused '+rid+'/'+k,!products.evansSpecies9Entry({entries:new Map([[x.id,x]])},ctx));}
 check('Wrong CIF refused '+rid,!products.evansSpecies9Entry({entries:new Map([[original.id,{...original,provenance:{...original.provenance,sourceCifSha256:'wrong'}}]])},ctx));
 let opened=null;const api={chemicalRegistry:async()=>data,chemicalImage:()=>new El('img'),openChemical:async e=>{opened=e}};const host=new El('div');const mounted=await products.mountEvansSpecies9(host,r,{chemicalApi:api});check('Mount exact sample '+rid,mounted.mounted&&mounted.sampleId===sample);
 const button=host.all(n=>n.tag==='button')[0];await button.onclick();check('Rotate delegates source model '+rid,opened.id===original.id&&opened.caption.includes('20 H'));
 const dl=host.all(n=>n.tag==='a')[0];check('Download existing model only '+rid,new URL(dl.href).pathname.endsWith('/assets/chemical-registry/'+products.EVANS_SPECIES9.model3dPath)&&new URL(dl.href).searchParams.get('sha')===products.EVANS_SPECIES9.modelSha256&&dl.download.endsWith('.json'));
 check('Duplicate mount refused '+rid,!(await products.mountEvansSpecies9(host,r,{chemicalApi:api})).mounted&&host.children.length===1);
 const detached=new El('div');detached.isConnected=false;check('Detached host refused '+rid,!(await products.mountEvansSpecies9(detached,r,{chemicalApi:api})).mounted&&detached.children.length===0);
 check('Caption disclaims QD coordinates '+rid,host.all(n=>n.textContent?.includes('No nanocrystal coordinates')).length===1);
}
const display=read(S+'/data/measurement-display.json'),text=fs.readFileSync(S+'/dist/material-hub.mjs','utf8'),match=text.match(/const structural=\(m,r\)=>([^;]+);/);check('Actual hub classifier extracted',!!match);const classify=new Function('m','r','displayCategories','return '+match[1]);let classCount=0;
for(const r of records)for(const m of r.measurements){const has=Object.hasOwn(display.record_structural_measurement_ids||{},r.record_id),expected=has?display.record_structural_measurement_ids[r.record_id].includes(m.id):display.structural_properties.includes(m.property)||display.structural_property_fragments.some(p=>m.property.includes(p));check('JS classification '+r.record_id+'/'+m.id,classify(m,r,display)===expected);classCount++;}
const sectionExpr=text.match(/const measurements=r\.measurements\.filter\(m=>(.+?)\);const products=/)[1],sectionClassify=new Function('m','r','isStructure','displayCategories','structural','return '+sectionExpr);let propertyCount=0;
for(const r of records)for(const m of r.measurements){const st=classify(m,r,display),pr=Object.hasOwn(display.record_property_measurement_ids||{},r.record_id)?display.record_property_measurement_ids[r.record_id].includes(m.id):!st;check('Actual section structural filter '+r.record_id+'/'+m.id,sectionClassify(m,r,true,display,(a,b)=>classify(a,b,display))===st);check('Actual section property filter '+r.record_id+'/'+m.id,sectionClassify(m,r,false,display,(a,b)=>classify(a,b,display))===pr);if(r.lineage.source_group==='evans2010'&&pr)propertyCount++;}check('193Evans property fields',propertyCount===193);
const {stockScope}=await import(pathToFileURL(S+'/dist/stock-scope.mjs'));let stockCount=0;
for(const r of records)for(const stock of r.stocks){const host=stockScope(stock,r);if(r.lineage.source_group!=='evans2010'){check('Other-source stock unchanged '+r.record_id+'/'+stock.id,host.children.length===1&&host.children[0].textContent===stock.scope);continue;}let fields,end=-1;for(let i=0;i<stock.scope.length;i++){try{fields=JSON.parse(stock.scope.slice(0,i+1));end=i+1;break;}catch{}}const rows=host.children[0].children,normal=Object.entries(fields).filter(([k])=>!['id','source_unit_id'].includes(k));check('All stock fields displayed '+stock.id,rows.length===normal.length);for(let i=0;i<normal.length;i++){const[k,v]=normal[i],expected=v===null?'Not explicitly reported':typeof v==='object'?JSON.stringify(v):String(v).replaceAll('_',' ');check('Exact readable stock field '+r.record_id+'/'+stock.id+'/'+k,rows[i].children[0].textContent===k.replaceAll('_',' ')&&rows[i].children[1].textContent===expected);}for(const k of ['id','source_unit_id'])if(k in fields)check('Provenance retained '+stock.id+'/'+k,host.children[2].children[1].textContent.includes(k+': '+fields[k]));check('Stock trailing source note retained '+stock.id,host.children[1].textContent===stock.scope.slice(end).trim());stockCount++;}check('13Evans stock scopes',stockCount===13);
const model=read(S+'/dist/assets/chemical-registry/'+products.EVANS_SPECIES9.model3dPath);check('Existing51atom model with20H',model.atoms.length===51&&model.atoms.filter(a=>a.element==='H').length===20);check('Model exact qualified bytes',sha(S+'/dist/assets/chemical-registry/'+products.EVANS_SPECIES9.model3dPath)===products.EVANS_SPECIES9.modelSha256);check('All record input objects unchanged',JSON.stringify(records)===before);check('Registry object unchanged',JSON.stringify(original)===oldEntry);check('46scenes153rows',sceneCount===46&&rowCount===153);
const report={status:checks.every(x=>x.passed)?'passed':'failed',auditor:'/root/norberg2004_extract',checks:checks.length,records:records.length,product_scopes:productScopes,positive_record_scopes:positive,protocol_scenes:sceneCount,condition_rows:rowCount,measurement_classifications:classCount,evans_property_fields:propertyCount,evans_stock_scopes:stockCount,failures:checks.filter(x=>!x.passed),actual_browser_test:false,scope:'Executed actual installed modules read-only using a small independent DOM harness. DOM behavior and guards checked; this is not a mounted-browser visual review.',module_hashes:Object.fromEntries(['evans2010-products.mjs','evans2010-protocol.mjs','protocol-visuals.mjs','material-hub.mjs','stock-scope.mjs'].map(n=>[n,sha(S+'/dist/'+n)]))};fs.writeFileSync(O+'/installed-module-checks.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(report.status==='failed')process.exitCode=1;
