"""Durable progress only. Does not mark unfinished website contributions complete."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,subprocess,sys
F=Path(__file__).resolve().parent;MON=F.parents[2];M=F.parents[4];J=F.parent/'acs.jpcc.5c05144'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
sys.path.insert(0,str(MON));import monitor
now=datetime.now(timezone.utc).isoformat()
source_j=J/'source-independent-audit/independent-audit-v2.json';assert read(source_j)['status']=='passed'
v3=F/'canonical-independent-audit/independent-audit-v3.json'
reader_pass=v3.exists() and read(v3)['status']=='passed'
f_audits=['source-independent-audit/independent-audit-v2.json','molecular-independent-audit/independent-audit-v2.json','molecular-bindings-independent-audit/independent-audit.json','apparatus-independent-audit/independent-audit.json','product-independent-audit/independent-audit.json']
for rel in f_audits:assert read(F/rel)['status']=='passed',rel
if reader_pass:f_audits.append('canonical-independent-audit/independent-audit-v3.json')
monitor.checkpoint(MON/'ledger.json','mattersyn-primary',group_id='legacy::10.1021_acs.inorgchem.8b02945',data={'source_audit_passed':True,'canonical_reader_audit_passed':reader_pass,'visual_audits_passed':True,'audit_artifacts':{r:sha(F/r) for r in f_audits},'publication_status':'not published; integration and browser checks pending'},note='Separate chemical, exact molecular binding, stage illustration and product-context audits passed; reader correction is tracked separately.',milestones={'audit':{'status':'partial','evidence':[str(F/r) for r in f_audits],'note':'Separate source and visual audits passed. Structured-reader pass: '+str(reader_pass)+'. Integrated browser/publication checks remain open.'}})
monitor.checkpoint(MON/'ledger.json','mattersyn-primary',group_id='legacy::10.1021_acs.jpcc.5c05144',data={'source_audit_passed':True,'effective_source_freeze':str(J/'source-extraction-revision-2/package-freeze.json'),'effective_source_freeze_sha256':sha(J/'source-extraction-revision-2/package-freeze.json'),'source_audit_sha256':sha(source_j),'source_status':'complete main/SI source reading and independent audit passed; canonical mapping in progress','publication_status':'not published'},note='Sasongko source audit passed after the preserved SI Raman locator addition. Canonical authoring now in progress.',milestones={'read':{'status':'complete','evidence':[str(source_j)],'note':'All nine main and eleven SI pages independently read and visually checked.'},'extract':{'status':'complete','evidence':[str(source_j)],'note':'All source scientific values,121table cells and17crops checked; locator-only correction passed.'},'audit':{'status':'partial','evidence':[str(source_j)],'note':'Source audit passed. Canonical, visual, browser and publication gates are separate.'}})
ed=read(MON/'public-progress-editorial.json');f=ed['current_work'][0];j=ed['current_work'][1]
f['stage']='Source, data and illustration audits passed; website integration pending' if reader_pass else 'Scientific and illustration audits passed; final reader corrections under review'
f['summary']='All 33 main/SI pages were independently reviewed. The 30-record proposal has separately checked chemical references, 77 exact material bindings, 58 stage illustrations and 88 symbolic product contexts. Reader prose and named-sample links have a preserved correction; original numeric values and 51 figure crops are unchanged.'
f['stages'][2]={'label':'Structured records and scientific illustrations','status':'complete' if reader_pass else 'in_progress','detail':'Independent molecular, material/stock binding, apparatus and product-context audits passed. '+('Corrected reader also passed.' if reader_pass else 'Final reader correction is undergoing its independent check.')}
f['stages'][3]={'label':'Website integration, browser checks and publication','status':'pending','detail':'This contribution is not yet in the live scientific dataset.'}
j['stage']='Source audit passed; structured recipes and reader in preparation'
j['summary']='The extractor and independent reviewer inspected all nine main pages and eleven SI pages. All 121 table cells and 17 selected crops were checked. A missing Raman figure-page citation was corrected without changing scientific values. Canonical recipe/sample mapping is now underway.'
j['stages']=[{'label':'Main/SI pairing and complete source reading','status':'complete','detail':'All 20 supplied pages independently inspected; title, source identity and supporting information matched.'},{'label':'Extraction and independent source audit','status':'complete','detail':'Preserved revision 2 passed; scientific quantities and original figure crops unchanged.'},{'label':'Structured records and website preparation','status':'in_progress','detail':'Recipe, comparison and characterization contexts are being mapped into the common schema; no current measured atomic-coordinate model is inferred from reference crystal parameters.'},{'label':'Publication','status':'pending','detail':'This contribution is not yet published.'}]
save(MON/'public-progress-editorial.json',ed)
for script in ['build_queue_report.py','build_public_progress.py']:subprocess.run([sys.executable,str(MON/script)],check=True)
notes=f'''## 2026-09-20 — Screen-first parallel workflow: independent gates and release staging

Checkpoint {now}. The user's three workflow changes are active: fixed-corpus screening before detailed review, parallel authoring/independent audit across papers with separate per-paper audit history, and grouped publication from reviewed records and qualified reusable visual components. No paid API run or new paper download is authorized. Stable original filenames and supplied main/SI content checks remain mandatory. Current fixed-cutoff screen:13,831top-level document copies disposed;9,532known included provisional canonical scopes,9,502pending,30terminal, plus3nested identity cases held. Last scan14:19:20Z saw14,286copies/9,976provisional canonical scopes;444later-arrival groups/455files remain separate. These are screening/provisional counts, not fully reviewed papers.

Friedfeld2019(InP): source main8+SI25 passed; canonical draft-v3 freeze197e498c257c3103975548128a4ca766092c825aba83dfcab01b6a05a7cc61f6 preserves all30record bytes,2,131typed fields and51crop bytes while correcting reader display prose and62named-sample links. Reader v3 independent pass at this checkpoint: {reader_pass}. Root molecular correctionv2, Peng exact molecular-binding audit, root apparatus and root product-context audits passed. Apparatus58scenes/115typed quantities; exact bindings77material slots/eightstock instances/16components; product88mapped contexts/14symbols, no atomic geometry. Root inspected all58apparatus art scenes and two full-size condition layouts and independently executed the actual module. Final browser/WebGL checks are still separate. No Friedfeld record or scientific page is published yet.

Friedfeld audit hashes: {json.dumps({r:sha(F/r) for r in f_audits},ensure_ascii=False)}.

N2 correction preserves the original failed package and uses qualified1.09768Å reference geometry, with gas/coolant context separate. Other corrected annotations remove inherited prior-paper assay conditions and identify PubChem241as unlabeled benzene parent rather than benzene-d6identity. Both project and installed visual skill include these reusable checks; skill reference SHA5b54707db6af4c42d96538378951cf4bf44b3ce44a694a4274137d271eb3493a.

Sasongko2025(FAPbI3): complete main9+SI11 source reading/audit passed. Preserved source-overlay freeze d34778349e9942a73a1d275536af354e93d52739692e689fe2f12d394db7fddc; independent audit c709225b9555ba89d3d952a6153561b011351c00fb2c62733c920447479edb58. The only post-audit correction adds exactSIp5FigureS2locators for Raman80–190K, retainingp4/p6; all source scientific leaves,121table cells and17crops unchanged. Norberg is authoring canonical/reader proposal outside Site. One coherent hot-injection workflow with linked purification and explicitly paired comparison contexts; no invented Cartesian experiments, sample joins or measured-cell labels.

Root prepared publication-only F/site-integration-proposal/v1/package-freeze.json SHA1714710fcab2068a7b9dc13e0392ccb8dd708cc661961c324ef969c6fee34612 with162allowlisted assets and30records, preserving scientific data. Windows path/allowlist staging failures are recorded before the successful freeze. Backlog is independently auditing permitted metadata and asset-path differences. Unexecuted helpers are F/import_reviewed_friedfeld.py,build_friedfeld_inventory.py,build_and_check_site.py. Before integration require the independent publication-projection pass and unchanged-record receipt; then import, validate existing626record andsixtraining-export preservation, exercise actual desktop/mobile browser and publish a completed contribution batch. Do not run old frozen source/package author scripts again. Reuse this staging work; do not restart full PDF readings or passed audits for metadata changes.

Live science remains0.31.0:626records,118route/variant records,49hubs,39sourcegroups,34formal readers; exact structure–recipe pairs0. Most recent verified progress-only site commit03a8d782783e683cc9affc36e124a6a9d229e5e1 and project29a72f4abae00f5db6fe2b8f4b78352b5561e725 were verified public; F/progress-publication/anonymous-progress-verification.json records exact Pages build plusfiveanonymous endpoint matches. New progress snapshot is locally regenerated by this checkpoint; record the later deployment receipt separately. The earlier324-endpoint science verification is preserved. No new science-publication claim is made.

Keep the single existing five-minute heartbeat mattersyn-sequential-paper-review, two active paper claims and separate source histories; no duplicate automation or newpaperclaim was created. Paid pilot decision stays deferred. Public project filtering excludes originalPDF/SI, whole-document text, complete page renders, credentials and runtimes. Continue synchronizing memory,skills,audits and references at meaningful milestones. Whole-corpus two-month completion remains unvalidated.

'''
p=M/'MEMORY.md';p.write_text(notes+p.read_text(encoding='utf-8'),encoding='utf-8')
save(F/'parallel-checkpoint.json',{'at':now,'source_groups':['friedfeld2019','sasongko2025'],'friedfeld_reader_v3_pass':reader_pass,'sasongko_source_audit_sha256':sha(source_j),'live_dataset_version':'0.31.0','new_scientific_contributions_published':0,'progress_publication_pending':True})
print(json.dumps({'memory_saved':True,'progress_snapshot':'local','friedfeld_reader_pass':reader_pass,'sasongko_source_pass':True}))
