from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,sys
E=Path(__file__).resolve().parent;MON=E.parents[2];N=E.parent/'acs.inorgchem.7b01711'
sys.path.insert(0,str(MON));import monitor
p=N/'visuals/apparatus/package-freeze.json';digest=hashlib.sha256(p.read_bytes()).hexdigest();assert digest=='1c7688c5d9c0d073fcb8c1812cb20de6ff16909dfca820a5e1a1324d5dc6d5b5'
monitor.checkpoint(MON/'ledger.json','mattersyn-primary',group_id='10.1021_acs.inorgchem.7b01711',note='Apparatus author package frozen and handed to a distinct auditor. Molecular/source/canonical audits passed; apparatus independent check, root integration and browser/publication remain.',data={'current_step':'Independent apparatus audit in progress; root integration next if passed','apparatus_proposal':{'path':str(p),'sha256':digest},'apparatus_reviewer':'/root/peng1998_reader_assets'})
monitor.checkpoint(MON/'ledger.json','mattersyn-primary',group_id='legacy::10.1021_acsami.1c18038',note='Source author reports all34local main/SIpages read/viewed and is completing extraction. A distinct reviewer now independently reads/audits alongside extraction; no frozen source audit pass yet.',data={'current_step':'Source extraction and independent source reading in parallel','independent_source_reviewer':'/root/norberg2004_extract','author_reading_scope':'8main+26SIpages reported read/viewed; source freeze and independent audit pending','missing_attachment_scope':'Declared crystalZIP/MP4 absent from intake; local matches may be checked, no downloads.'})
(E.parent/'final-handoffs-20260920T0730.json').write_text(json.dumps({'at':datetime.now(timezone.utc).isoformat(),'evans':'Published; no further scientific edits pending','morrison':{'source_audit':'passed revision2','canonical_audit':'passed v2','molecular_audit':'passed v1','apparatus_freeze_sha256':digest,'apparatus_audit':'in_progress','shared_site_integration':'pending'},'lian':{'source_author':'/root/backlog_eta','source_auditor':'/root/norberg2004_extract','source_package_frozen':False,'full_independent_approval':False},'monitor':'Existing single5minuteheartbeat active; latestmemoryandledger supersede snapshot prompts'},indent=2)+'\n',encoding='utf8')
print('Saved current per-paper handoffs without changing live scientific records.')
