import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const base=path.join(path.dirname(fileURLToPath(import.meta.url)),'apparatus/v1');
const {buildEvans2010Scene}=await import('./apparatus/v1/evans2010-protocol.mjs');
const records=JSON.parse(fs.readFileSync(path.join(base,'records.json'),'utf8'));
const scenes=[];fs.mkdirSync(path.join(base,'svg'),{recursive:true});
for(const r of records)for(const o of r.operations){const s=buildEvans2010Scene(o,r);if(!s)throw Error('Missing scene '+o.id);fs.writeFileSync(path.join(base,'svg',o.id+'.svg'),s.svg);scenes.push({record_id:r.record_id,operation_id:o.id,kind:s.kind,title:s.title,rows:s.rows,description:s.description});}
if(scenes.length!==46)throw Error('Wrong operation count');
fs.writeFileSync(path.join(base,'rendered-scenes.json'),JSON.stringify(scenes,null,2)+'\n');
fs.writeFileSync(path.join(base,'index.html'),`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Evans operation illustrations · private review</title><style>body{font:16px system-ui;background:#edf3f7;color:#17384b;margin:24px}main{max-width:1150px;margin:auto}header{position:sticky;top:0;background:#edf3f7;padding:12px 0;z-index:1}select{max-width:100%;padding:12px;font:inherit}#scene{background:white;padding:20px;border-radius:16px}h1{font-size:24px}#art svg{width:100%;max-height:600px}#gallery[hidden]{display:none}#gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}#gallery article{background:white;padding:15px;border-radius:12px;min-width:0}#gallery svg{width:100%;height:auto}#gallery h2{font-size:14px}#gallery p{font-size:12px}button{padding:10px;font:inherit}@media(max-width:700px){body{margin:12px}#gallery{grid-template-columns:1fr}}</style><main><header><h1>Evans · 46 operation-specific illustrations</h1><p>Private author proposal; independent apparatus audit and Site integration pending.</p><label for="choose">Select operation</label> <select id="choose"></select><button id="prev">Previous</button><button id="next">Next</button><button id="grid">Show contact sheet</button></header><section id="scene"></section><section id="gallery" hidden></section></main><script type="module">import {buildEvans2010Scene,renderEvans2010Markup} from './evans2010-protocol.mjs';const records=await(await fetch('records.json')).json(),all=records.flatMap(r=>r.operations.map(o=>({r,o}))),choose=document.querySelector('#choose'),scene=document.querySelector('#scene'),gallery=document.querySelector('#gallery');for(const [i,{r,o}] of all.entries()){let x=document.createElement('option');x.value=i;x.textContent=(i+1)+' · '+o.label;choose.append(x);}function render(){const {r,o}=all[Number(choose.value)],s=buildEvans2010Scene(o,r);scene.dataset.operation=o.id;scene.innerHTML='<h2>'+s.title+'</h2>'+renderEvans2010Markup(s);}choose.addEventListener('change',render);for(const [id,delta] of [['prev',-1],['next',1]])document.getElementById(id).onclick=()=>{choose.value=Math.max(0,Math.min(all.length-1,Number(choose.value)+delta));render();};document.getElementById('grid').onclick=()=>{gallery.hidden=!gallery.hidden;scene.hidden=!gallery.hidden;};for(const [i,{r,o}] of all.entries()){const s=buildEvans2010Scene(o,r),a=document.createElement('article');a.dataset.operation=o.id;a.innerHTML='<h2>'+(i+1)+' · '+s.title+'</h2>'+s.artSvg;gallery.append(a);}render();</script>`);
console.log(JSON.stringify({scenes:scenes.length,rows:scenes.reduce((n,s)=>n+s.rows.length,0),records:records.length}));
const art=records.flatMap(r=>r.operations.map(o=>buildEvans2010Scene(o,r)));
for(let j=0;j<4;j++)fs.writeFileSync(path.join(base,`contact-${j+1}.html`),`<!doctype html><meta charset="utf-8"><title>Evans apparatus sheet ${j+1}</title><style>body{font:14px system-ui;background:#edf3f7;margin:12px;color:#183a50}main{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}article{min-width:0;background:#fff;padding:12px}svg{width:100%}h2{font-size:14px;min-height:36px}</style><h1>Evans apparatus · sheet ${j+1} / 4</h1><main>${art.slice(j*12,j*12+12).map((s,i)=>`<article><h2>${j*12+i+1}. ${s.title}</h2>${s.artSvg}</article>`).join('')}</main>`);
