"""Save bounded review progress without changing the published scientific dataset."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,sys
R=Path(__file__).resolve().parents[2]; M=R.parents[1]
sys.path.insert(0,str(R));import monitor
E=Path(__file__).resolve().parent/'ja103805s';N=E.parent/'acs.inorgchem.7b01711'
def read(p):return json.loads(p.read_text(encoding='utf8'))
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.now(timezone.utc).isoformat()
source=E/'source-scientific-audit.json';canonical=E/'proposal-independent-audit/independent-audit-v3.json';molecules=E/'visuals/molecules-independent-audit/independent-audit-v2.json';apparatus=E/'visuals/apparatus/v1/package-freeze.json'
assert read(canonical)['status']=='passed' and read(molecules)['status']=='passed'
monitor.checkpoint(R/'ledger.json','mattersyn-primary',group_id='10.1021_ja103805s',note='Canonical/reader v3 and molecular revision2 independently passed; 46 root-authored apparatus scenes frozen after local browser QA, separate apparatus audit active. No scientific publication yet.',data={'current_step':'Apparatus independent audit; prepare website integration after remaining gates','canonical_v3_audit':{'path':str(canonical),'sha256':sha(canonical)},'molecular_v2_audit':{'path':str(molecules),'sha256':sha(molecules)},'apparatus_v1_freeze':{'path':str(apparatus),'sha256':sha(apparatus)}},milestones={'read':{'status':'complete','evidence':[str(source)]},'extract':{'status':'complete','evidence':[str(E/'source-extraction-revision-2/source-extraction-freeze.json'),str(E/'proposal-freeze-v3.json'),str(canonical)]},'audit':{'status':'partial','evidence':[str(source),str(canonical),str(molecules)],'note':'Scientific source/canonical and molecular audits passed; apparatus/integration/release remain separate gates.'},'integrate':{'status':'partial','evidence':[str(apparatus),str(E/'visuals/apparatus/v1/browser-author-qa.json')],'note':'Private illustration preview only; no integrated Site approval.'}})
monitor.checkpoint(R/'ledger.json','mattersyn-primary',group_id='10.1021_acs.inorgchem.7b01711',note='Cutoff-ranked Morrison2017 admitted after content-confirmed legacy alias reconciliation and generation2 fingerprint. Author read all27main/SI pages; detailed extraction active and distinct reviewer starting source checks.',data={'current_step':'Full extraction; independent source review in parallel','source_inventory':str(N/'source-inventory.json'),'local_only':True,'upstream_cited_only_methods_are_gaps':True},milestones={'read':{'status':'partial','evidence':[str(N/'source-inventory.json'),str(N/'page-coverage.json')],'note':'Author reports all10main+17SI pages read and visually inspected; frozen source handoff and independent coverage audit pending.'},'extract':{'status':'partial','evidence':[str(N/'source-facts.json'),str(N/'source-tables.json')],'note':'Author draft; not yet independently approved.'}})
editorial=read(R/'public-progress-editorial.json')
e=editorial['current_work'][0]
e['stage']='Source, structured-data and molecular audits passed; apparatus audit in progress'
e['summary']='All 24 main/SI pages and the molecular CIF were independently checked. The 32 structured records and source reader passed a separate audit after preserving the distinction between distillation residue and collected fractions. Fifty chemical references also passed their own audit. Forty-six operation-specific diagrams have completed author browser checks and are undergoing independent review.'
e['stages'][2]={'label':'Canonical records and reader audit','status':'complete','detail':'32 records; 457 facts; residue-C lineage correction retained in version history'}
e['stages'][3]={'label':'Molecular illustrations and exact source bindings','status':'complete','detail':'50 chemical references; 123 material slots and 41 stock components; lower-bound purity captions corrected'}
e['stages'].append({'label':'Apparatus, integrated website and publication','status':'in_progress','detail':'46 diagrams; 153 condition rows; private preview controls checked. Independent apparatus and integrated website checks remain.'})
editorial['current_work'].append({'short_label':'Morrison et al. (2017)','title':'Cadmium Bis(phenyldithiocarbamate) as a Nanocrystal Shell-Growth Precursor','stage':'Main/SI paired; extraction and independent source reading in parallel','summary':'A synthesis-rich cutoff paper was admitted through the screened queue. The matched 10-page main paper and 17-page SI cover a CdS shell-growth precursor and CdSe/CdS quantum belts. Existing legacy and incoming copies were matched by content hashes; original filenames remain unchanged.','stages':[{'label':'Main/SI pairing and author reading','status':'complete','detail':'10 main-paper and 17 SI pages inspected by the extracting reviewer'},{'label':'Detailed extraction and independent audit','status':'in_progress','detail':'Recipes, controls, measurements, figures and SI coordinate tables; separate reviewer'},{'label':'Illustrations and publication','status':'pending','detail':'Not yet approved for the website or training exports'}],'gaps':['Upstream ammonium precursor and CdSe-belt preparations are cited, but complete recipes are not supplied in this source bundle.','SI coordinates describe the molecular precursor crystal, not the CdSe/CdS quantum-belt product.','Printed amount, condition and caption discrepancies remain explicit until their individual source checks are complete.']})
editorial['recent_milestones'].insert(0,{'at':now,'text':'Evans structured records/reader and molecular source bindings passed separate audits. Forty-six operation diagrams entered independent review. Morrison CdSe/CdS shell-growth paper was admitted through the fixed-cutoff evidence-ranked queue and is being extracted alongside a distinct source reviewer.'})
editorial['estimate']['current_batch']='The original five-paper pilot remains 5/5 published. Evans is in visual/integration review and Morrison is in source extraction/audit. These are active reviews, not completed publications; required two-month throughput remains unvalidated.'
partition=read(R/'deadline-20260920/admission-20260920T055502Z/post-alias-scope-partition.json')
pending=len(partition['included_pending_group_ids'])
editorial['workflow']['fixed_pending_provisional_scopes']=pending
editorial['estimate']['summary']=f'The two-month target covers the fixed existing collection. Following completed reviews and duplicate reconciliation, {pending:,} provisional cutoff scopes remain pending, plus three nested identity cases. Roughly 159 closures/day over 60 days or 190/day over 50 production days would be required. Achievable capacity and the recipe-bearing fraction remain unverified.'
editorial['workflow']['screening_scope']='The fixed-cutoff screen accounts for all 13,831 top-level document copies: 13,593 text-screened candidates and 238 manual format/text cases. Three nested PDFs were separately screened and remain held for identity reconciliation. Later arrivals stay outside the fixed completion target. Screening is not full reading or a no-recipe exclusion.'
save(R/'public-progress-editorial.json',editorial)
memory=f'''## 2026-09-20 — Parallel review checkpoint: Evans data passed; Morrison admitted

Saved {now}. Existing public science remains dataset 0.24.0: 480 structured records, 98 synthesis routes/variants, 44 material/component hubs, 32 source groups and 27 formal readers. No new exact structure–recipe pair or training eligibility was added. This checkpoint updates workflow/progress only; deployment is verified separately below when complete.

Evans (10.1021/ja103805s): independent canonical/reader v3 audit PASSED ({sha(canonical)}), bound to proposal freeze 0e419d0d014740f7713debcd1baf3446b17a08ef2e4e1a67df394d2b45cc43dd. All 32 records preserve the original quantities and distinct controls/contexts. Residual pot C has a separate material state from collected distillates; B is an independently prepared stock. Molecular audit revision2 PASSED ({sha(molecules)}): 50 identities, 123 slots, 41 stock components. Exactly six PbO caption leaves now retain the lower-bound purity ≥99.9%; original assets/quantities are unchanged. Use revision2 effective bindings with the original registry/assets. Molecular species9 CIF is not QD coordinates.

Root apparatus package v1 frozen ({sha(apparatus)}): 46 operations, 33 visual types, 153 condition rows. Actual preview controls, all four contact sheets and a 390px responsive view checked; 159 author checks. Separate apparatus audit is assigned to the molecular author, who did not author the apparatus. Do not confuse private preview QA with integrated Site approval. Integration, release verification and publication remain pending.

Morrison (10.1021/acs.inorgchem.7b01711), Cadmium Bis(phenyldithiocarbamate) as a Nanocrystal Shell-Growth Precursor, admitted through the audited cutoff-selection wrapper. Main/SI bundle 7bdb53c0976b097b3794eb9282469f1d34e8514fbfd6a1ea0bc74813ac8433f3 at generation2 after content-confirmed legacy alias reconciliation. All 10 main and 17 SI pages author-read/viewed; detailed extraction is active and another reviewer is independently reading. Precursor Cd(PTC)2·THF coordinates must not become a CdSe/CdS product structure. Upstream cited-only recipes and printed unit/caption conflicts remain gaps. Files are under batches/20260920-rolling-pipeline/acs.inorgchem.7b01711/.

There are two active paper claims, within the existing five-paper rolling limit, and four agents including root. Continue screened evidence-priority admission; preserve per-paper audits and publish completed contributions together. No paid API processing, new infrastructure or paper download was started. Latest intake scan: 13,933 document copies; counts are copies/provisional scopes, not verified papers/recipes. The fixed-cutoff pending count after duplicate reconciliation is {pending:,}. Original documents, complete raw text and full-page scans remain excluded from public repositories. Existing heartbeat remains the single scheduler.

'''
mem=M/'MEMORY.md';mem.write_text(memory+mem.read_text(encoding='utf8'),encoding='utf8')
save(E.parent/'parallel-review-checkpoint.json',{'at':now,'published_science_changed':False,'evans_canonical_audit':sha(canonical),'evans_molecule_audit':sha(molecules),'evans_apparatus_freeze':sha(apparatus),'active_claims':2,'fixed_pending_scopes':pending,'publication_verification':'pending'})
print(json.dumps({'saved_at':now,'evans_canonical_and_molecules':'passed','apparatus':'independent_audit_in_progress','morrison':'extraction_and_separate_source_review','fixed_pending_scopes':pending,'science_publication_changed':False}))
