"""Schwartz et al. 2003: complete 14-page main and four-page matched SI curation."""
from pathlib import Path
from copy import deepcopy
import sys,json,hashlib
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas';sys.path.insert(0,str(S/'scripts'))
from record_helpers import record,source,ev,fact,qty,material,operation,state,product,measurement
from dataset_lib import validate_record
SID='schwartz2003';PRE='schwartz-2003-'
SRC=source(SID,'10.1021/ja036811v','Magnetic Quantum Dots: Synthesis, Spectroscopy, and Magnetism of Co2+- and Ni2+-Doped ZnO Nanocrystals','Dana A. Schwartz; Nick S. Norberg; Quyen P. Nguyen; Jason M. Parker; Daniel R. Gamelin',2003,si='Four supplied SI pages, Figures S1–S6, matched by exact main-paper declarations and cross-references plus Gamelin metadata. No standalone SI title/byline. All pages text-read and visually inspected.')
SRC['main_status']='All 14 main pages read as text and original images, including Figures 1–11, Tables 1–2, Scheme 1, equations 1–10 and references 1–51. Independent audit pending.'
def E(p,s):return ev(SID,f'Main PDF p. {p}, printed p. {13204+p}, {s}')
def SI(p,s):return ev(SID,f'Matched SI PDF p. {p}, '+s)
SYN=E(2,'II.A Sample Preparation');PHY=E(3,'II.B Physical Measurements');TOPO=SYN+E(9,'IV.C Postsynthetic Processing');KIN=E(3,'Figure 1 and kinetics discussion');MAG=E(6,'Figure 10 discussion')+E(7,'Figure 10')+E(13,'IV.D.v Ferromagnetism');OPT=E(5,'Figures 6–7 discussion')+E(6,'Figures 7–9')
def Q(v=None,u='',e=SYN,**kw):return qty(v,u,deepcopy(e),**kw)
def F(v=None,e=SYN,**kw):return fact(v,deepcopy(e),**kw)
CHEM={
 'zinc-acetate-dihydrate':('Zinc acetate dihydrate','Zn(C2H3O2)2·2H2O',SYN),
 'cobalt-acetate-tetrahydrate':('Cobalt(II) acetate tetrahydrate','Co(C2H3O2)2·4H2O',SYN),
 'nickel-perchlorate-hexahydrate':('Nickel(II) perchlorate hexahydrate','Ni(ClO4)2·6H2O',SYN),
 'tetramethylammonium-hydroxide-pentahydrate':('Tetramethylammonium hydroxide pentahydrate','C4H13NO·5H2O',SYN),
 'dmso':('Dimethyl sulfoxide','C2H6OS',SYN),'ethanol':('Ethanol','C2H6O',SYN),
 'ethyl-acetate':('Ethyl acetate','C4H8O2',SYN),'heptane':('Heptane','C7H16',SYN),
 'dodecylamine':('Dodecylamine','C12H27N',SYN),'toluene':('Toluene','C7H8',SYN),
 'topo-technical':('Technical-grade trioctylphosphine oxide (Aldrich), with unspecified phosphonic-acid impurities',None,SYN+E(2,'Note 16')),
 'topo-component':('Trioctylphosphine oxide, named component of the technical reagent','C24H51OP',SYN+E(2,'Note 16')),
 'zinc-acetate-additive':('Zinc acetate clarity-restoration additive; hydration unspecified','Zn(C2H3O2)2',SYN),
 'zno-specimen':('ZnO nanocrystal specimen; batch specified by context','ZnO',SYN),
 'co-specimen':('Co2+-doped ZnO nanocrystals; dopant content specified by specimen','ZnO:Co',SYN),
 'ni-specimen':('Ni2+-doped ZnO nanocrystals; dopant content specified by specimen','ZnO:Ni',SYN),
 'surface-co-specimen':('ZnO nanocrystals with Co intentionally bound at the surface; loading/preparation incomplete',None,SI(2,'Figure S2')),
 'co-aggregate-specimen':('Aggregated 3.6% Co2+:ZnO nanocrystals','ZnO:Co',MAG),
 'quartz':('Quartz disk for spin-coated optical film','SiO2',PHY),
 'helium':('Helium vapor for cryostat cooling','He',PHY)
}
def C(i,role,stage='synthesis',notes=None,e=None,quantities=None):
 n,f,d=CHEM[i];return material(i,n,f,role,stage,deepcopy(e or d),quantities=quantities,notes=notes or [])
def base(k,title,kind='observation',method='Source-scoped characterization and interpretation',formula='ZnO'):
 r=record(PRE+k,'Schwartz et al. (2003) · '+title,formula,'ZnO and separately Co2+- or Ni2+-doped ZnO quantum dots',method,deepcopy(SRC),'Complete 14-page main and matched four-page SI',kind)
 r['schema_version']='1.3.0';r['collection']='reviewed_literature';r['material'].update(elements=['Zn','O']+(['Co']if formula=='ZnO:Co'else['Ni']if formula=='ZnO:Ni'else[]),components=[formula],architecture='single_material')
 r['lineage'].update(source_group=SID,recipe_family='schwartz2003-zno-doping')
 r['intended_target']['composition']=F(formula,E(1,'Abstract'),note='Dopant notation denotes the material family, not a refined site occupancy. Shared analytical records retain distinct compositions in their product/sample contexts.')
 r['quality'].update(review_status='imported_unreviewed',review_scope='All supplied main and SI pages text-read and visually inspected; no cited external full texts downloaded. Independent audits and publication pending.',missing_fields=['Per-specimen synthesis batches and complete links between nominal feed doping and measured incorporation are not given.','Several workup volumes, separation hardware, stirring speed, aging times, TOPO/powder ratio and exact purification cycles are unreported.','No measured atomic coordinate file, sample-specific refined dopant occupancy, raw spectral array or full statistical error model is supplied.'],conflicts=[],requested_tasks=['precursor_selection','partial_protocol']if kind=='literature_protocol'else[],experimental_outcome='reported_product'if kind=='literature_protocol'else'not_established')
 r['context_links']=[{'label':'Complete source review','url':'../paper-review.html?id='+SID,'relation':'Main figures, matched SI, tables, equations and evidence limitations.'}]
 return r
def add(r,i,action,label,inputs,out,e,pars=None,stage='synthesis',desc='',env=None,end=None,kind='reaction_batch',depends=None,retain=False,parents=None):
 if out:r['material_states'].append(state(out,label+' output',inputs if parents is None else parents,kind))
 r['operations'].append(operation(i,action,label,deepcopy(e),inputs,[out]if out else[],depends=depends if depends is not None else([r['operations'][-1]['id']]if r['operations']else[]),parameters=pars or{},stage=stage,description=desc,environment=F(env,e),endpoint=F(end,e),retained_fraction=out if retain else None))
def P(r,i,label,e,formula=None,st=None,explicit=False,notes=None):
 p=product(i,formula or r['material']['formula'],deepcopy(e),link='explicit'if explicit else'general_context',state=st,notes=notes or[]);p['source_sample_label']=label;r['products'].append(p);return p
def M(r,i,s,prop,v,u,e,tech='Source-reported observation',conditions='',**kw):r['measurements'].append(measurement(i,s,prop,Q(v,u,e,**kw),tech,deepcopy(e),conditions))
def T(r,i,s,prop,v,e,tech='Source-reported observation',conditions='',**kw):r['measurements'].append(measurement(i,s,prop,F(v,e,**kw),tech,deepcopy(e),conditions))
def link(r,k,title,rel='Source-scoped related preparation or characterization.'):r['context_links'].append({'label':title,'url':'../records/'+PRE+k+'.html','relation':rel})
def stock(r,i,name,components,concentrations,e,prep=None,scope=''):
 r['stocks'].append({'id':i,'name':name,'components':[{'material_id':c,'quantities':{}}for c in components],'concentrations':concentrations,'preparation_operation_ids':prep or[],'scope':scope,'evidence':deepcopy(e)})
records=[]

for metal,formula,dopant in [('zno','ZnO',None),('co','ZnO:Co','cobalt-acetate-tetrahydrate'),('ni','ZnO:Ni','nickel-perchlorate-hexahydrate')]:
 r=base(metal+'-route',('Undoped'if metal=='zno'else'Co2+-doped'if metal=='co'else'Ni2+-doped')+' ZnO by alkaline hydrolysis in DMSO','literature_protocol','Room-temperature alkaline hydrolysis and condensation',formula)
 inh={}if metal=='zno'else{'status':'inherited','qualifier':'Common typical preparation framework; not an independently quantified batch for each dopant concentration.'}
 r['materials']=[C('zinc-acetate-dihydrate','metal_precursor'),C('tetramethylammonium-hydroxide-pentahydrate','base'),C('dmso','solvent'),C('ethanol','solvent'),C('ethyl-acetate','antisolvent','workup'),C('heptane','alternative_antisolvent','workup')]
 if dopant:r['materials'].append(C(dopant,'metal_precursor',quantities={'initial_dopant_fraction':Q(u='mol %',qualifier='Variable nominal feed loading; not equal to the measured incorporated concentration in every characterized specimen.')}))
 comps=['zinc-acetate-dihydrate']+([dopant]if dopant else[])+['dmso']
 stock(r,'metal-stock','Zinc'+(' and dopant'if dopant else'')+' precursor in DMSO',comps,{'total_metal_concentration':Q(.101,'mol/L',**inh)},SYN,prep=['prepare-metal'],scope='For doped solutions Zn is reduced to maintain the total initial metal concentration. Individual dopant salt doses are not reported; no fixed Zn concentration is asserted for doped mixtures.')
 stock(r,'base-stock','Tetramethylammonium hydroxide in ethanol',['tetramethylammonium-hydroxide-pentahydrate','ethanol'],{'base_concentration':Q(.552,'mol/L',**inh)},SYN,prep=['prepare-base'])
 add(r,'prepare-metal','precursor_solution_preparation','Prepare the metal-acetate/DMSO solution'if metal!='ni'else'Prepare Zn acetate and Ni perchlorate in DMSO',comps,'metal-solution',SYN,{'solution_volume':Q(90,'mL',**inh),'total_metal_concentration':Q(.101,'mol/L',**inh)},stage='precursor_preparation',desc='Hydrated salts are printed explicitly. Dissolution temperature/time and water balance are unknown. '+('Replace part of Zn with the dopant to keep total metal constant; do not copy 0.101 M as the Zn-only concentration.'if dopant else'The quoted Zn stock is the typical undoped preparation.'))
 add(r,'prepare-base','base_solution_preparation','Prepare the ethanolic hydroxide feed',['tetramethylammonium-hydroxide-pentahydrate','ethanol'],'base-solution',SYN,{'solution_volume':Q(30,'mL',**inh),'base_concentration':Q(.552,'mol/L',**inh)},stage='precursor_preparation',depends=[])
 add(r,'add-base','dropwise_hydrolysis_condensation','Add the hydroxide solution dropwise with constant stirring',['metal-solution','base-solution'],'as-grown',SYN,{'addition_rate':Q(2,'mL/min',approximate=True,**inh),'base_equivalents':Q(1.8,'equiv',**inh),'temperature':Q(u='°C',qualifier='Room temperature; numerical value unreported.')},depends=['prepare-metal','prepare-base'],desc='Room-temperature synthesis in open containers is described; no controlled gas, numeric pressure, stirring speed or separately timed post-addition hold. The printed 1.8 equivalents is retained, without replacing it by arithmetic from rounded quantities.')
 add(r,'precipitate','antisolvent_precipitation','Precipitate nanocrystals with ethyl acetate or heptane',['as-grown','ethyl-acetate','heptane'],'precipitated',SYN,stage='workup',retain=True,parents=['as-grown'],desc='Ethyl acetate and heptane are mutually exclusive alternatives, not co-added mandatory inputs. Source does not specify their volumes, solvent ratio or isolation hardware. Alternative inputs are listed for inventory completeness; the retained particle-state lineage does not assert both solvents were used.')
 add(r,'wash','ethyl_acetate_washing','Wash the precipitated nanocrystals with ethyl acetate',['precipitated','ethyl-acetate'],'washed',SYN,stage='workup',retain=True,desc='Wash count, volume and separation conditions are not reported; no centrifugation settings are invented.')
 add(r,'redisperse','colloid_redispersion','Redisperse in DMSO or ethanol',['washed','dmso','ethanol'],'colloid',SYN,stage='workup',parents=['washed'],desc='DMSO and ethanol are mutually exclusive alternate redispersion solvents. Final volume, concentration and storage conditions are unreported. Alternative inputs are listed for inventory completeness; the particle-state lineage does not assert both solvents were used.')
 r['condition_options']=[{'id':'precipitation-ethyl-acetate','label':'Precipitate with ethyl acetate; mutually exclusive with the heptane option.','parameters':{},'evidence':deepcopy(SYN)},{'id':'precipitation-heptane','label':'Precipitate with heptane; mutually exclusive with the ethyl-acetate option.','parameters':{},'evidence':deepcopy(SYN)},{'id':'redispersion-dmso','label':'Redisperse in DMSO; mutually exclusive with the ethanol option.','parameters':{},'evidence':deepcopy(SYN)},{'id':'redispersion-ethanol','label':'Redisperse in ethanol; mutually exclusive with the DMSO option.','parameters':{},'evidence':deepcopy(SYN)}]
 p=P(r,'route-product','General '+formula+' preparation framework',SYN,st='colloid',explicit=True);p['phase']=F('Wurtzite ZnO host',E(5,'Figure 5')+E(7,'Pure ZnO phase discussion'),note='Phase supported in characterized examples; no refined dopant occupancy or guarantee of identical batches.')
 if dopant:T(r,'nominal-vs-incorporated','route-product','dopant_loading_scope','Initial salt fraction is a controlled feed variable. ICP-AES determines dopant concentration, but the source does not provide a complete per-batch feed-to-incorporation table.',SYN+PHY)
 T(r,'scale','route-product','author_preparation_scale','The authors report rapid, reproducible gram-quantity preparation in open containers without special atmospheric precautions or temperature stabilization. No exact isolated mass/yield is provided for the typical recipe.',E(2,'Introduction')+E(13,'Conclusion'),status='author_derived')
 link(r,'topo-'+metal,'TOPO processing and surface-dopant removal');link(r,'microscopy','Microscopy and electron diffraction');link(r,'dopant-series','Nominal-doping series');records.append(r)

r=base('clarity-restoration','Zinc-acetate addition to cloudy ZnO colloids','procedure','Colloid redispersion')
r['materials']=[C('zno-specimen','specimen','workup'),C('zinc-acetate-additive','stabilizing_additive','workup')]
add(r,'add-zinc','clarity_restoration','Add zinc acetate to the cloudy ZnO suspension',['zno-specimen','zinc-acetate-additive'],'clear-colloid',SYN,{'zinc_acetate_mass':Q(10,'mg',approximate=True)},stage='workup',desc='Hydration state, starting colloid volume/concentration, final composition, mixing time and quantitative optical criterion are unspecified.',end='Optical clarity restored')
P(r,'clarified','Cloudy colloid treated with zinc acetate',SYN,st='clear-colloid',explicit=True);records.append(r)

for metal,formula,spec in [('zno','ZnO','zno-specimen'),('co','ZnO:Co','co-specimen'),('ni','ZnO:Ni','ni-specimen')]:
 r=base('topo-'+metal,formula+' TOPO treatment and redispersion','procedure','Surface cleaning and ligand exchange',formula)
 r['materials']=[C(spec,'specimen','workup'),C('dmso','solvent','workup'),C('dodecylamine','surface_ligand','workup'),C('ethanol','antisolvent','workup'),C('toluene','solvent','workup'),C('topo-technical','surface_ligand','workup',notes=['Technical Aldrich TOPO contains unspecified phosphonic acids; their proposed primary ligation role is an author inference (note 16). The mixture has no exact molecular formula.']),C('topo-component','named_reagent_component','workup',notes=['Structural reference for the named TOPO component only; no separate dose, pure-stock claim or known impurity fraction.'])]
 add(r,'remove-excess','precursor_removal_check','Remove excess dissolved Zn precursor before amine addition',[spec,'dmso'],'cleaned-dmso-colloid',TOPO,stage='workup',desc='Washed nanocrystals are required. The paper gives no exact extra wash count or removal assay. This represents the explicit precaution, not an invented separation method.')
 add(r,'amine-precipitate','amine_induced_precipitation','Precipitate the nanocrystals from DMSO with dodecylamine',['cleaned-dmso-colloid','dodecylamine'],'amine-precipitate',TOPO,{'dodecylamine_amount':Q(u='g',e=TOPO)},stage='workup',retain=True,desc='Excess Zn2+ must be removed first because amine causes rapid growth at the expense of size uniformity.')
 add(r,'ethanol-wash','solvent_washing','Wash with ethanol to remove DMSO',['amine-precipitate','ethanol'],'amine-capped',TOPO,stage='workup',retain=True)
 add(r,'toluene-resuspend','redispersion','Resuspend the dodecylamine-capped particles in toluene',['amine-capped','toluene'],'toluene-colloid',TOPO,stage='workup')
 add(r,'ethanol-precipitate','antisolvent_precipitation','Precipitate the toluene dispersion with ethanol',['toluene-colloid','ethanol'],'first-cycle-solid',TOPO,stage='workup',retain=True)
 add(r,'repeat-cycle','repeat_redispersion_precipitation','Repeat toluene resuspension and ethanol precipitation once',['first-cycle-solid','toluene','ethanol'],'powder',TOPO,{'total_cycles':Q(2,'cycles',TOPO)},stage='workup',retain=True,desc='Two total toluene/ethanol cycles, not two additional cycles. Powder drying method is not specified.')
 add(r,'heat-topo','topo_thermal_treatment','Heat the resulting powder in technical-grade TOPO',['powder','topo-technical'],'topo-treated',TOPO,{'temperature':Q(180,'°C',TOPO),'duration':Q(u='min',e=TOPO,minimum=30),'topo_mass':Q(u='g',e=TOPO)},stage='workup',desc='At least 30 min is reported. Atmosphere, vessel, heating ramp, powder/TOPO ratio and exact duration for individual characterized samples are not supplied.')
 add(r,'cool','cooling','Cool the TOPO-treated nanocrystals below 80 °C',['topo-treated'],'cooled-topo',TOPO,{'target_temperature':Q(u='°C',e=TOPO,maximum=80,maximum_exclusive=True)},stage='workup')
 add(r,'precipitate','product_precipitation','Precipitate the cooled TOPO-treated particles',['cooled-topo'],'topo-precipitate',TOPO,stage='workup',retain=True,desc='The source names ethanol washing next but does not independently specify the precipitation agent or its amount in this sentence.')
 add(r,'wash','ethanol_washing','Wash the precipitated particles with ethanol',['topo-precipitate','ethanol'],'cleaned-topo-powder',TOPO,stage='workup',retain=True)
 add(r,'redisperse','nonpolar_redispersion','Redisperse with 1 mg additional TOPO in a nonpolar solvent',['cleaned-topo-powder','topo-technical','toluene'],'topo-colloid',TOPO,{'additional_topo_mass':Q(1,'mg',TOPO),'solvent_volume':Q(u='mL',e=TOPO)},stage='workup',desc='Toluene is the explicitly discussed example; other nonpolar solvents are not named. The 1 mg is additional redispersion TOPO, not the unknown heated-bath amount.')
 p=P(r,'treated','General '+formula+' TOPO-processing framework',TOPO,st='topo-colloid',explicit=True);p['surface']=F('TOPO-treated surface; exact ligating composition unresolved',TOPO)
 M(r,'concentration','treated','reported_achieved_zno_toluene_concentration',None,'g/mL',SYN,minimum=.4,minimum_exclusive=True,conditions='General reported attainable colloid concentration; not a per-sample concentration or dopant-specific measured value.')
 T(r,'stability','treated','author_colloid_stability_observation','High-optical-quality solutions appear indefinitely stable with no observed growth, aggregation, dopant mobility or precipitation. A numerical aging duration and quantitative detection limits are not supplied.',SYN,status='author_derived')
 T(r,'cleaning','treated','author_surface_dopant_removal',('Related doped-sample context only: this interpretation applies to Co/Ni-doped examples; pure ZnO has no intentional dopant. 'if metal=='zno'else'')+'TOPO treatment solvates exposed surface dopants; only internally doped ions remain according to the ligand-field spectroscopy interpretation. S2 intentionally surface-bound Co is a separate test specimen.',E(9,'IV.C')+SI(2,'S2'),status='author_derived')
 T(r,'ripening','treated','topo_ripening_condition','If particles have not already ripened in DMSO, heating in TOPO accelerates Ostwald ripening and increases diameter. No universal diameter change is asserted for every specimen.',E(9,'IV.C'))
 link(r,metal+'-route','Initial colloid synthesis');records.append(r)

r=base('aggregation','Room-temperature aggregation of Co2+:ZnO colloids','procedure','Evaporation-driven aggregation','ZnO:Co')
r['materials']=[C('co-specimen','specimen','workup'),C('ethanol','solvent','workup')]
add(r,'prepare-ethanol','concentrated_ethanol_suspension','Use a concentrated ethanol suspension of the doped nanocrystals',['co-specimen','ethanol'],'concentrated-colloid',SYN,{'concentration':Q(u='g/mL')},stage='workup',desc='No numerical concentration, volume or new evaporation/concentration step is provided. The starting individual dots are described as paramagnetic.')
add(r,'evaporate','ambient_evaporation_aggregation','Allow solvent to evaporate in air on a benchtop',['concentrated-colloid'],'aggregates',SYN+E(13,'IV.D.v'),{'temperature':Q(u='°C',qualifier='Room temperature; no numeric value.'),'duration':Q(u='h')},stage='workup',env='Air',desc='Slow, reaction-limited aggregation is described. No elevated-temperature anneal or post-aggregation treatment is used; vessel geometry and evaporation rate are missing.')
P(r,'aggregate','Figure 10: 3.6% Co2+:ZnO aggregates',MAG,st='aggregates',explicit=True)
M(r,'dopant','aggregate','reported_specimen_cobalt_percentage',3.6,'%',MAG,conditions='Reported aggregate specimen composition; not the nominal salt feed fraction.')
M(r,'size-results','aggregate','reported_starting_dot_diameter',5.0,'nm',E(6,'Figure 10 discussion'),conditions='Results-section value; discussion uses 4.9 nm for the same aggregate context.')
M(r,'size-discussion','aggregate','reported_starting_dot_diameter',4.9,'nm',E(13,'IV.D.v'),conditions='Discussion value; not silently merged with 5.0 nm earlier.')
T(r,'phase','aggregate','aggregation_diffraction_comparison','Aggregated and nonaggregated samples have identical powder diffraction patterns; no new phase is reported. Actual paired XRD patterns are not reproduced in the supplied bundle.',E(13,'IV.D.v'))
T(r,'morphology','aggregate','aggregate_morphology','Dense micron-scale gel structures are shown by SEM. Related Ni aggregates discussed with reference 50 are external/forthcoming context, not a supplied Ni-aggregation dataset.',E(6,'Figure 10 discussion')+E(7,'Figure 10 inset')+E(13,'IV.D.v'))
r['quality']['conflicts']=['The Figure 10 aggregate starting-particle diameter is 5.0 nm in Results and 4.9 nm in Discussion; both remain source-scoped.'];link(r,'magnetometry','Aggregate magnetic measurements');records.append(r)

def kinetic_materials(r,dopants=()):
 r['materials']=[C('zinc-acetate-dihydrate','metal_precursor'),C('dmso','solvent'),C('tetramethylammonium-hydroxide-pentahydrate','base'),C('ethanol','solvent')]+[C(d,'metal_precursor')for d in dopants]

r=base('pure-kinetics','ZnO nucleation and growth after one base addition','procedure','Time-resolved absorption during hydrolysis')
kinetic_materials(r)
stock(r,'metal-stock','Zn acetate in DMSO',['zinc-acetate-dihydrate','dmso'],{'concentration':Q(.101,'mol/L',KIN)},KIN)
stock(r,'base-stock','Hydroxide in ethanol',['tetramethylammonium-hydroxide-pentahydrate','ethanol'],{'concentration':Q(.554,'mol/L',KIN)},KIN)
add(r,'prepare','kinetic_specimen_preparation','Prepare the small-volume Zn acetate/DMSO specimen',['metal-stock'],'kinetic-stock',KIN,{'stock_volume':Q(250,'µL',KIN)},stage='characterization')
add(r,'add-base','kinetic_reaction_initiation','Add the printed hydroxide aliquot',['kinetic-stock','base-stock'],'kinetic-reaction',KIN,{'base_volume':Q(30,'µL',KIN),'base_equivalents_prose':Q(.6,'equiv',KIN)},stage='characterization',desc='The printed 30 µL × 0.554 M / (250 µL × 0.101 M) corresponds to about 0.658, while the prose/caption calls this 0.6 equivalent. Preserve both printed quantities; do not repair the recipe. S1 explicitly states 0.66 equivalent.')
add(r,'measure','time_resolved_absorption','Record successive band-gap absorption spectra',['kinetic-reaction'],'kinetic-data',KIN,{'first_measurement':Q(30,'s',KIN,approximate=True),'sampling_interval':Q(30,'s',KIN),'last_measurement':Q(10,'min',KIN)},stage='characterization',kind='analysis_data')
P(r,'pure','Figure 1a: pure ZnO kinetic run',KIN,explicit=True)
M(r,'metastable','pure','time_to_metastable_state',10,'min',KIN,approximate=True)
T(r,'evolution','pure','kinetic_spectral_evolution','Band-gap absorption increases, narrows and shifts to lower energy; narrowing is assigned to size focusing. Subsequent room-temperature Ostwald ripening occurs on day/week timescales.',KIN,status='author_derived')
r['quality']['conflicts']=['Figure 1a says 0.6 equivalents; printed concentrations and aliquot volumes imply approximately 0.658. Figure S1 and Figure 4 state 0.66.'];records.append(r)

for name,formula,dopants in [('pure-titration','ZnO',()),('co-titration','ZnO:Co',('cobalt-acetate-tetrahydrate',))]:
 e=KIN if name=='pure-titration'else E(4,'Figure 3 and Co titration')+E(7,'Figure 11')+E(8,'Dopant incorporation analysis')
 r=base(name,('Pure ZnO'if not dopants else'98% Zn / 2% Co')+' base titration','procedure','Incremental hydroxide titration',formula);kinetic_materials(r,dopants)
 comps=['zinc-acetate-dihydrate']+list(dopants)+['dmso']
 stock(r,'metal-stock','Metal precursor in DMSO',comps,{'total_metal_concentration':Q(.101,'mol/L',e,status='inherited'if dopants else'reported')},e,scope='Co titration uses conditions described as identical to the pure experiment; total metal is held fixed.')
 stock(r,'base-stock','Ethanolic hydroxide feed',['tetramethylammonium-hydroxide-pentahydrate','ethanol'],{'concentration_prose':Q(.554,'mol/L',KIN),'concentration_figure1b_caption':Q(.552,'mol/L',E(3,'Figure 1b caption'))},KIN,scope='Conflicting prose/caption concentrations are preserved, not two co-added stocks.')
 add(r,'prepare','titration_specimen_preparation','Prepare the undoped metal solution'if not dopants else'Prepare 98% Zn / 2% Co in DMSO',['metal-stock'],'titration-stock',e,{'nominal_cobalt_fraction':Q(2,'mol %',e)}if dopants else{},stage='characterization')
 add(r,'titrate','incremental_base_titration','Add hydroxide in 0.2-equivalent aliquots',['titration-stock','base-stock'],'titration-mixture',e,{'aliquot_base_equivalents':Q(.2,'equiv',e)},stage='characterization',desc='The displayed titration contains finer regions discussed in the text; intermediate volume, waiting time and exact full aliquot schedule are not tabulated.')
 add(r,'measure','titration_absorption','Measure band-gap and ligand-field spectral evolution',['titration-mixture'],'titration-data',e,stage='characterization',kind='analysis_data')
 P(r,'titration','Figure 1b pure ZnO'if not dopants else'Figures 3 and 11: nominal 2% Co titration',e,explicit=True)
 if not dopants:
  for i,v,pr in [('initial',.2,'base_equivalents_initial_cluster_regime'),('nucleation',.4,'base_equivalents_nucleation_onset'),('strong',.6,'base_equivalents_strong_exciton'),('linear',1.0,'base_equivalents_linear_intensity_onset'),('endpoint',2.0,'figure1b_labeled_final_equivalents')]:M(r,i,'titration',pr,v,'equiv',KIN,approximate=i in ['nucleation','linear'])
  for i,en,diam,equiv in [('early',32500,2,.4),('later',30000,3.2,.6)]:
   M(r,i+'-energy','titration','band_gap_absorption_energy',en,'cm^-1',E(7,'IV.A'),conditions=f'After approximately {equiv} equivalents OH−.')
   M(r,i+'-size','titration','optically_estimated_particle_diameter',diam,'nm',E(7,'IV.A'),approximate=True,status='author_derived',conditions='Empirical tight-binding estimate assuming pseudospherical crystallites; not direct TEM.')
  T(r,'early','titration','early_nucleation_observation','First and second aliquots yield broad high-energy absorption above 30000 cm−1; green ZnO trap luminescence supports crystal formation at 0.4 equivalent. Intensity increases are initially erratic, then linear above about 1 equivalent.',KIN+E(7,'IV.A'))
 else:
  for i,v,pr,u in [('precursor',19000,'octahedral_precursor_ligand_field_energy','cm^-1'),('final',33000,'final_doped_band_gap_energy','cm^-1'),('nochange',.3,'base_equivalents_without_apparent_co_change','equiv'),('intermediate-onset',.35,'base_equivalents_intermediate_onset','equiv'),('intermediate',17500,'intermediate_band_maximum_results','cm^-1'),('intermediate-discussion',19000,'intermediate_band_center_discussion','cm^-1'),('intermediate-max',.6,'base_equivalents_intermediate_maximum','equiv'),('internal-onset',.45,'base_equivalents_internal_signal_onset','equiv'),('internal',16500,'internal_co_ligand_field_peak','cm^-1'),('iso1',18550,'isosbestic_energy','cm^-1'),('iso2',20750,'isosbestic_energy','cm^-1'),('intercept',.36,'internal_co_fit_zero_intercept','equiv')]:M(r,i,'titration',pr,v,u,e,approximate=i in ['intermediate-onset','intermediate','intermediate-discussion','internal-onset'],status='author_derived'if i=='intercept'else'reported')
  T(r,'color','titration','coordination_color_evolution','Pink pseudo-octahedral Co2+ becomes blue tetrahedral Co2+ as ZnO forms. Figure 3 photographs are qualitative stages without uniquely tabulated elapsed time or aliquot for each image.',E(4,'Figure 3'))
  T(r,'deconvolution','titration','figure11_decomposition_scope','Source single-valued decomposition separates band-gap, intermediate and internal-Co signals. Internal and intermediate signals are scaled ×60 in Figure 11a; fitted intermediate spectra are compared with excess-acetate Co/DMSO and TOPO-treated internally doped dots.',E(7,'Figure 11'),status='author_derived')
  r['quality']['conflicts'].append('Intermediate absorption maximum is approximately 17500 cm−1 in Results and described as centered around 19000 cm−1 in Discussion. Distinct printed descriptions remain unreconciled.')
 r['quality']['conflicts'].append('Figure 1b caption gives 0.552 M base, while its prose gives 0.554 M.');records.append(r)

r=base('dopant-series','Nominal Co/Ni loading effects and matched kinetic comparisons','procedure','Nominal-dopant concentration and time series')
kinetic_materials(r,('cobalt-acetate-tetrahydrate','nickel-perchlorate-hexahydrate'))
for series,dopant in [('pure',None),('co','cobalt-acetate-tetrahydrate'),('ni','nickel-perchlorate-hexahydrate')]:
 stock(r,series+'-metal-series',('Undoped Zn'if series=='pure'else'Zn/'+series.upper())+' comparison solutions in DMSO',['zinc-acetate-dihydrate']+([dopant]if dopant else[])+['dmso'],{'total_metal_concentration':Q(.101,'mol/L',E(4,'Figure 4'))},E(4,'Figure 4')+SI(1,'S1'),scope='Separate '+series+' comparison series, never a co-doped stock. Zn is reduced to hold total metal fixed for doped solutions. Figure 4 generic TM(OAc)2 notation does not override the explicit Ni perchlorate reagent in Methods. Individual loading-specific salt amounts are unreported.')
stock(r,'base-stock','Ethanolic hydroxide',['tetramethylammonium-hydroxide-pentahydrate','ethanol'],{'base_concentration':Q(.554,'mol/L',E(4,'Figure 4'))},E(4,'Figure 4'))
add(r,'prepare','separate_dopant_series_preparation','Prepare separate pure, Co-doped and Ni-doped comparison solutions',['pure-metal-series','co-metal-series','ni-metal-series'],'series-specimens',E(4,'Figure 4')+SI(1,'S1'),{'specimen_volume':Q(250,'µL',E(4,'Figure 4'))},stage='characterization',kind='sample_set',desc='Figure 4 plots nominal 0, 2, 4, 6 and 8% loading; S1 compares pure and 2% added Co or Ni. These are distinct measured contexts and separate stocks, not one mixed reaction.')
add(r,'add-base','comparison_reaction_initiation','Add 0.66 equivalents of hydroxide to each separate specimen',['series-specimens','base-stock'],'series-reactions',E(4,'Figure 4')+SI(1,'S1'),{'base_equivalents':Q(.66,'equiv',E(4,'Figure 4')+SI(1,'S1'))},stage='characterization',kind='sample_set')
add(r,'measure','comparative_absorption','Measure metastable band gaps and time dependence',['series-reactions'],'series-data',E(4,'Figure 4')+SI(1,'S1'),{'independent_measurements':Q(3,'measurements',E(4,'Results'))},stage='characterization',kind='analysis_data',desc='Three independent measurements are averaged for Figure 4. S1 uses single-exponential fit lines without tabulated rate constants. No precise y values are reconstructed from graph pixels.')
for k,f in [('co','ZnO:Co'),('ni','ZnO:Ni')]:
 P(r,k,'Figure 4 nominal '+k.upper()+' series',E(4,'Figure 4'),formula=f,explicit=True)
 for n in [0,2,4,6,8]:M(r,k+'-nominal-'+str(n),k,'figure4_nominal_dopant_fraction',n,'mol %',E(4,'Figure 4 markers'),status='inferred',conditions='Read from labeled graph marker positions, not a measured incorporated dopant fraction.')
 M(r,k+'-slope',k,'author_nucleation_inhibition_fit_slope',-9 if k=='co'else-6,'% nucleation / % dopant',E(8,'IV.B'),status='author_derived')
 M(r,k+'-two-percent',k,'author_relative_nucleation_reduction_at_2percent',35,'%',E(8,'IV.B'),approximate=True,status='author_derived')
 T(r,k+'-trend',k,'dopant_bandgap_trend','Co band-gap energy increases approximately linearly with nominal loading.'if k=='co'else'Ni addition increases the gap, but further loading above about 1% changes it little; Figure 4 markers are 2, 4, 6 and 8%.',E(4,'Results'),status='author_derived')
 P(r,k+'-kinetics','S1: 2% added '+k.upper(),SI(1,'S1'),formula=f,explicit=True)
 M(r,k+'-kinetic-feed',k+'-kinetics','nominal_added_dopant_fraction',2,'%',SI(1,'S1'))
P(r,'pure-kinetics','S1 pure ZnO reference',SI(1,'S1'),explicit=True)
T(r,'s1','pure-kinetics','si_kinetic_fit_scope','S1 follows energy decrease and absorption increase for pure, 2% Co-added and 2% Ni-added ZnO; lines are single-exponential fits. No fitted rate constant/error or individual raw time series is tabulated.',SI(1,'S1'))
M(r,'base-control','pure-kinetics','base_only_inhibition_relative_factor',20,'dimensionless',E(8,'IV.B'),approximate=True,status='author_derived',conditions='Varying only base concentration has an approximately twentyfold smaller effect than dopant addition; complete control concentrations are not supplied.')
r['quality']['conflicts']=['Figure 4 calls the precursor TM(OAc)2 generically, while Methods explicitly names Ni(ClO4)2·6H2O. No nickel acetate is substituted.'];records.append(r)

r=base('thermal-ripening','ZnO ripening at 50 °C in DMSO','procedure','Thermally accelerated Ostwald ripening')
r['materials']=[C('zno-specimen','specimen'),C('dmso','solvent')]
add(r,'heat','thermal_ripening','Heat the ZnO/DMSO dispersion at 50 °C',['zno-specimen','dmso'],'ripening-colloid',KIN,{'temperature':Q(50,'°C',KIN)},desc='No initial powder mass, precursor concentration, vessel, gas, ramp or final isolated yield is specified.')
add(r,'measure','time_resolved_absorption','Measure the time-dependent band-gap spectra',['ripening-colloid'],'ripening-data',KIN,stage='characterization',kind='analysis_data')
P(r,'heated','Figure 1c heating series',KIN,explicit=True)
for t in [2,5,20,40,120]:M(r,'time-'+str(t),'heated','figure1c_heating_time',t,'min',E(3,'Figure 1c caption'))
T(r,'trend','heated','ripening_optical_trend','Band gap shifts to lower energy and decreases in intensity with heating; authors assign slow growth by Ostwald ripening. No per-time fitted particle size is tabulated.',KIN,status='author_derived');records.append(r)

r=base('room-aging','Room-temperature aging of pure ZnO in DMSO','procedure','Ostwald ripening')
r['materials']=[C('zno-specimen','specimen'),C('dmso','solvent')]
add(r,'age','ambient_aging','Age the pure ZnO nanocrystals in DMSO at room temperature',['zno-specimen','dmso'],'aged-zno',E(7,'IV.A'),{'duration':Q(2,'day',E(7,'IV.A')),'temperature':Q(u='°C',e=E(7,'IV.A'),qualifier='Room temperature, numerical value unstated.')},desc='Figure 2 specimen is linked in the discussion to two days of aging; its complete preceding synthesis aliquot/batch is not identified.')
P(r,'aged','Figure 2 aged pure ZnO specimen',E(4,'Figure 2')+E(7,'IV.A'),st='aged-zno',explicit=True)
M(r,'bandgap','aged','band_gap_absorption_energy',29500,'cm^-1',E(3,'Figure 2 discussion'))
M(r,'tem-diameter','aged','tem_mean_particle_diameter',3.8,'nm',E(3,'Figure 2 discussion')+E(4,'Figure 2'),qualifier='Printed ±0.6 nm distribution width; statistical uncertainty type is not specified.')
M(r,'distribution','aged','tem_reported_distribution_width',.6,'nm',E(4,'Figure 2 caption'),conditions='Not relabeled as uncertainty of the mean.')
M(r,'optical-size','aged','optically_estimated_particle_diameter',3.8,'nm',E(3,'Figure 2 discussion'),status='author_derived');records.append(r)

r=base('surface-cleaning-control','TOPO removal of deliberately surface-bound cobalt','procedure','Surface-dopant removal control','ZnO:Co')
r['materials']=[C('surface-co-specimen','specimen','workup'),C('topo-technical','surface_ligand','workup'),C('topo-component','named_reagent_component','workup',notes=['The named component of technical TOPO, not an additional independently dosed material.'])]
add(r,'treat','surface_cobalt_solvation','Treat ZnO with deliberately surface-bound Co in TOPO',['surface-co-specimen','topo-technical'],'treated-control',TOPO+SI(2,'S2'),{'temperature':Q(180,'°C',TOPO,status='inherited',qualifier='Shared TOPO procedure; S2 caption does not independently restate its temperature.')},stage='workup',desc='The deliberate adsorption recipe and initial surface-Co dose/speciation are not quantified. This control is not a substitutionally doped production batch.')
add(r,'measure','cleaning_control_absorption','Compare initial, 30 min and 120 min absorption spectra',['treated-control'],'cleaning-data',SI(2,'S2'),stage='characterization',kind='analysis_data')
P(r,'surface-control','S2 deliberately surface-bound Co control',SI(2,'S2'),explicit=True,notes=['ZnO:Co family notation does not assert internal doping in this control.'])
for t in [0,30,120]:M(r,'time-'+str(t),'surface-control','topo_cleaning_observation_time',t,'min',SI(2,'S2'),conditions='Zero identifies the caption’s initial spectrum, not a measured time uncertainty.')
T(r,'decrease','surface-control','surface_co_absorption_decrease','Surface-associated Co ligand-field absorption decreases strongly during TOPO treatment. No precise removal fraction, solution-Co assay or calibrated residual surface occupancy is supplied.',SI(2,'S2')+E(9,'IV.C'));records.append(r)

r=base('microscopy','TEM, HREM, electron diffraction and aggregate SEM','procedure','Electron microscopy and size-distribution analysis')
r['materials']=[C(x,'specimen','characterization')for x in ['zno-specimen','co-specimen','ni-specimen','co-aggregate-specimen']]+[C('ethyl-acetate','antisolvent','characterization'),C('ethanol','solvent','characterization')]
add(r,'precipitate','tem_specimen_isolation','Precipitate the Figure 5 Co-doped sample with ethyl acetate',['co-specimen','ethyl-acetate'],'co-tem-precipitate',E(5,'Figure 5 preparation'),stage='characterization',retain=True,desc='This explicitly documented transfer applies to the as-grown approximately 5% Co sample; no identical grid preparation is asserted for all other micrographs.')
add(r,'redisperse','tem_ethanol_redispersion','Resuspend the isolated Co-doped particles in ethanol',['co-tem-precipitate','ethanol'],'co-tem-ethanol',E(5,'Figure 5 preparation'),stage='characterization')
add(r,'deposit','tem_substrate_deposition','Deposit the ethanolic Co sample on a graphite TEM substrate',['co-tem-ethanol'],'co-tem-substrate',E(5,'Figure 5 preparation'),stage='characterization',desc='Droplet volume, grid mesh and drying time/temperature are not reported.')
add(r,'image','electron_microscopy','Image the separate pure, Co-doped, Ni-doped and aggregate specimens',['co-tem-substrate','zno-specimen','ni-specimen','co-aggregate-specimen'],'micrograph-data',PHY+E(4,'Figure 2')+E(5,'Figure 5')+E(7,'Figure 10 inset')+SI(2,'S3'),{'tem_accelerating_voltage':Q(200,'kV',PHY)},stage='characterization',kind='analysis_data',desc='HREM/TEM: JEOL 2010, high-brightness LaB6 filament, PNNL. Aggregate SEM: Serion XL-30 field-emission instrument; its accelerating voltage/working distance are not given. The 200 kV setting is TEM only.')
add(r,'diffraction','wide_area_electron_diffraction','Record wide-area electron diffraction of separate specimens',['co-tem-substrate','zno-specimen','ni-specimen'],'electron-diffraction-data',PHY+E(4,'Figure 2c')+E(5,'Figure 5c')+SI(2,'S3'),stage='characterization',kind='analysis_data',depends=['deposit'],desc='Actual diffraction images exist for pure ZnO, Co-doped ZnO and TOPO-treated Ni-doped ZnO. No camera length, selected-area aperture size or atom-coordinate reconstruction is supplied.')
add(r,'histogram','particle_size_histogram','Analyze separate particle-size histograms',['micrograph-data'],'size-data',E(4,'Figure 2b')+E(5,'Figure 5b'),{'particles_per_distribution':Q(100,'particles',E(4,'Figure 2b')+E(5,'Figure 5b'),approximate=True)},stage='characterization',kind='analysis_data',depends=['image'],desc='Approximately 100 particles are analyzed for each main-paper histogram, not an aggregate total or a sample count for the SI Ni micrograph.')
for i,label,f,e in [('pure','Figure 2 pure ZnO aged in DMSO','ZnO',E(4,'Figure 2')),('co5','Figure 5 approximately 5% Co2+:ZnO as grown','ZnO:Co',E(5,'Figure 5')),('ni-si','S3 TOPO-treated Ni2+:ZnO; concentration not stated','ZnO:Ni',SI(2,'S3')),('aggregate','Figure 10b SEM inset, Co2+:ZnO aggregates','ZnO:Co',E(7,'Figure 10'))]:
 p=P(r,i,label,e,formula=f,explicit=True);p['morphology']=F('Nearly spherical nanocrystals'if i!='aggregate'else'Dense micron-scale aggregate structures',e)
for sample,mean,width,opt in [('pure',3.8,.6,3.8),('co5',2.9,.3,2.8)]:
 e=E(4,'Figure 2')+E(3,'Results')if sample=='pure'else E(5,'Figure 5')
 M(r,sample+'-mean',sample,'tem_mean_particle_diameter',mean,'nm',e,tech='TEM histogram',qualifier=f'Printed ±{width} nm distribution; its statistical type is not explicitly identified.')
 M(r,sample+'-width',sample,'tem_reported_distribution_width',width,'nm',e,conditions='Not an error on the mean.')
 M(r,sample+'-optical',sample,'optically_estimated_particle_diameter',opt,'nm',e,status='author_derived')
 M(r,sample+'-count',sample,'particle_histogram_population',100,'particles',e,approximate=True)
 for tag,sz in [('overview',20),('hrtem',5)]:M(r,sample+'-'+tag+'-scale',sample,'micrograph_scale_bar',sz,'nm',e,tech='Printed image scale')
 T(r,sample+'-diffraction',sample,'wide_area_diffraction_assignment','Indexed rings include (101)/(002), (102), (110), (103) and (112), supporting highly crystalline wurtzite ZnO. Ring labels are source assignments, not a fitted lattice-constant dataset.',e)
M(r,'co5-dopant','co5','reported_specimen_cobalt_percentage',5,'%',E(5,'Figure 5'),approximate=True,conditions='The specimen is described as approximately 5% Co-doped; do not assume this is its nominal precursor percentage.')
M(r,'co-overview-count','co5','overview_visible_particle_count',30,'particles',E(5,'Figure 5a discussion'),approximate=True)
M(r,'ni-scale','ni-si','micrograph_scale_bar',200,'nm',SI(2,'S3'),tech='Printed TEM scale')
T(r,'ni-diffraction','ni-si','si_nickel_microscopy_scope','S3 supplies a TEM overview and electron-diffraction rings after TOPO treatment; no Ni percentage, particle histogram or average size is printed. It is not proven identical to the 1.5% Ni optical film.',SI(2,'S3'))
M(r,'aggregate-scale','aggregate','sem_scale_bar',50,'µm',E(7,'Figure 10b inset'),tech='Printed SEM scale')
records.append(r)

r=base('diffraction','Powder XRD and Scherrer-size comparison','procedure','Powder X-ray diffraction')
r['materials']=[C(x,'specimen','characterization')for x in ['zno-specimen','co-specimen','ni-specimen','co-aggregate-specimen']]
add(r,'acquire','powder_xrd','Collect powder diffraction patterns of separate samples',[m['id']for m in r['materials']],'xrd-data',PHY,stage='characterization',kind='analysis_data',desc='Philips PW1830; radiation wavelength, scan range/step/rate, tube settings, instrumental broadening standard and sample-specific fitted widths are not supplied.')
P(r,'study','Study-wide powder XRD and size checks',PHY);P(r,'aggregates','Aggregated versus nonaggregated Co2+:ZnO',E(13,'IV.D.v'),formula='ZnO:Co')
T(r,'scherrer','study','scherrer_comparison_scope','Routine optical diameters agree with Scherrer analysis of XRD peak widths for the same samples, with selective TEM verification. No source table of per-sample Scherrer diameters is provided.',PHY)
T(r,'phase','study','powder_xrd_phase_assignment','Electron and powder XRD confirm highly crystalline wurtzite ZnO. No atomic coordinates, Rietveld dopant occupancies or numeric phase detection limit are supplied.',E(7,'IV.A'))
T(r,'aggregate','aggregates','aggregation_xrd_comparison','Aggregated and nonaggregated samples give identical patterns, supporting no newly formed phase within the reported characterization. Original paired XRD curves are not included.',E(13,'IV.D.v'));records.append(r)

r=base('icp','Dopant-concentration measurement by ICP-AES','procedure','Inductively coupled plasma atomic emission spectroscopy')
r['materials']=[C('co-specimen','specimen','characterization'),C('ni-specimen','specimen','characterization')]
add(r,'analyze','icp_aes','Determine dopant concentrations in separate samples',[m['id']for m in r['materials']],'icp-data',PHY,stage='characterization',kind='analysis_data',desc='Jarrel Ash model 955. Digestion acid/procedure, standards, wavelengths, recovery, uncertainty and sample-by-sample nominal-to-incorporated mappings are absent.')
P(r,'method','Dopant analysis method, no full table',PHY)
T(r,'scope','method','dopant_measurement_scope','The paper states that ICP-AES determined dopant concentrations; characterization labels therefore remain reported specimen percentages. No universal equality with initial salt fraction or exact uniform atomic occupancy is asserted.',PHY+SYN);records.append(r)

def optical_samples(r):
 P(r,'co17','Figure 6a/7a/8a/9: 1.7% Co2+:ZnO, frozen solution',E(5,'Figure 6a')+E(6,'Figures 7–9'),formula='ZnO:Co',explicit=True)
 P(r,'ni15','Figure 6b/7b/8b: 1.5% Ni2+:ZnO, TOPO-treated thin film',E(5,'Figure 6b')+E(6,'Figures 7–8'),formula='ZnO:Ni',explicit=True)

r=base('optical-absorption','Room-temperature and low-temperature absorption','procedure','Electronic absorption spectroscopy')
r['materials']=[C(x,'specimen','characterization')for x in ['zno-specimen','co-specimen','ni-specimen']]+[C('quartz','substrate','characterization'),C('helium','coolant','characterization')]
add(r,'room','room_temperature_absorption','Measure room-temperature colloids in quartz cuvettes',['zno-specimen','co-specimen','ni-specimen'],'room-absorption-data',PHY,{'optical_path_length':Q(1.0,'cm',PHY)},stage='characterization',kind='analysis_data',desc='Cary 5E (Varian); individual colloids are separate. Concentration, baseline and spectral resolution are not universally specified.')
add(r,'film','optical_film_preparation','Spin-coat TOPO-treated nanocrystals onto quartz disks',['co-specimen','ni-specimen','quartz'],'optical-films',PHY,stage='characterization',kind='sample_set',depends=[],parents=['co-specimen','ni-specimen'],desc='Thin films are an alternative to frozen solutions; do not place every specimen through both preparations. Rotation rate, film thickness, dose and drying are unreported; quartz is support, not part of the nanocrystal composition.')
add(r,'glass','frozen_solution_preparation','Prepare separate frozen-solution optical specimens',['co-specimen','ni-specimen'],'optical-glasses',PHY,stage='characterization',kind='sample_set',depends=[],desc='Glassy solvent identity/composition and cooling schedule are not stated. Co Figure 6a is a frozen solution; Ni Figure 6b is a thin film.')
add(r,'cool','helium_cryostat_cooling','Cool the selected film or frozen-solution specimen with helium vapor',['optical-films','optical-glasses','helium'],'cold-optical-specimens',PHY,{'temperature':Q(7,'K',PHY)},stage='characterization',kind='sample_set',depends=['film','glass'],parents=['optical-films','optical-glasses'],desc='Janis STVP-100 continuous-flow optical cryostat inside Cary 5E. Film and glass are alternative specimen preparations, not physically combined materials.')
add(r,'acquire','low_temperature_absorption','Acquire low-temperature electronic absorption spectra',['cold-optical-specimens'],'cold-absorption-data',PHY+OPT,{'temperature':Q(7,'K',PHY+OPT)},stage='characterization',kind='analysis_data')
optical_samples(r)
for sample,doping,size in [('co17',1.7,5),('ni15',1.5,4.0)]:
 M(r,sample+'-doping',sample,'reported_specimen_dopant_percentage',doping,'%',E(5,'Figure 6'))
 M(r,sample+'-diameter',sample,'reported_optical_specimen_diameter',size,'nm',E(5,'Figure 6 discussion'),conditions='Characterized specimen diameter, not uniquely linked to a complete route batch.')
M(r,'co-lf','co17','co_ligand_field_band_center',15900,'cm^-1',E(5,'Figure 6a discussion'))
M(r,'co-oscillator','co17','integrated_ligand_field_oscillator_strength',.002,'dimensionless',E(5,'Figure 6a discussion'),status='author_derived')
P(r,'bulk-co','Cited bulk Co2+:ZnO optical comparator',E(5,'Comparison to reference 19'),formula='ZnO:Co')
M(r,'bulk-oscillator','bulk-co','cited_bulk_oscillator_strength',.005,'dimensionless',E(5,'Comparison to reference 19'),conditions='Literature comparator, not a current-paper bulk synthesis.')
for i,a,b in [('ligand-field',15160,16300),('charge-transfer',19400,25300),('bandgap',26000,28000)]:M(r,'ni-region-'+i,'ni15','nickel_'+i.replace('-','_')+'_spectral_region',None,'cm^-1',E(5,'Figure 6b discussion'),minimum=a,maximum=b)
for i,x in [('a1',15163),('e',15198)]:M(r,'ni-origin-'+i,'ni15','nickel_trigonal_ligand_field_origin',x,'cm^-1',E(9,'IV.D.i'),conditions='A1'if i=='a1'else'E')
M(r,'ni-linewidth','ni15','ligand_field_transition_fwhm',30,'cm^-1',E(9,'IV.D.i'),approximate=True)
M(r,'co-fine-agreement','co17','ligand_field_agreement_with_bulk_tolerance',1,'cm^-1',E(9,'IV.D.i'),approximate=True,conditions='Source quantitative agreement statement, not instrumental energy uncertainty.')
M(r,'co-fano','co17','fano_antiresonance_energy',17700,'cm^-1',E(9,'Note 25'))
T(r,'co-lines','co17','co_ligand_field_assignment','Structured tetrahedral Co2+ 4A2→4T1(P) absorption includes nearby doublets. Fine structure closely matches bulk, supporting localized ligand-field states and homogeneous substitutional doping; no measurable confinement energy shift is established.',E(5,'Figure 6a')+E(9,'IV.D.i'),status='author_derived')
T(r,'ni-lines','ni15','ni_ligand_field_assignment','Ni3T1(F)→3T1(P) features include oppositely signed A1 and E origins in MCD, while higher-energy electronic/vibronic overlap broadens structure. The quoted approximately 30 cm−1 widths support homogeneous sites.',E(9,'IV.D.i'),status='author_derived')
T(r,'co-tail','co17','co_absorption_tail','Band-gap absorption tails into the visible without an inflection even at low temperature; a distinct Co charge-transfer maximum cannot be isolated in absorption alone.',E(5,'Figure 6a')+E(10,'IV.D.ii'))
r['quality']['conflicts']=['The text uses inconsistent 4T1(P)/4T2(P) labels for some Co multiplet references; original equations, captions and discussion are retained without changing measured line positions.'];records.append(r)

r=base('mcd','Variable-field and variable-temperature magnetic circular dichroism','procedure','Magnetic circular dichroism')
r['materials']=[C('co-specimen','specimen','characterization'),C('ni-specimen','specimen','characterization')]
add(r,'prepare','magneto_optical_mounting','Place the separate optical specimens in Faraday geometry',[m['id']for m in r['materials']],'mcd-specimens',PHY,stage='characterization',kind='sample_set',desc='Aviv 40DS-based UV/VIS/NIR spectropolarimeter with Cryo Industries SMC-1659-OVT cryostat; samples are those used in absorption. Instrument capability below 1.5 to 300 K and 0–7 T is not the actual setting of every trace.')
add(r,'field-scan','variable_field_mcd','Acquire variable-field MCD spectra',['mcd-specimens'],'field-mcd-data',OPT,{'temperature':Q(5,'K',E(5,'Figure 6')),'figure6_field_range':Q(u='T',e=E(5,'Figure 6'),minimum=0,maximum=6.5),'figure7_field':Q(7,'T',E(6,'Figure 7'))},stage='characterization',kind='analysis_data')
add(r,'temperature-scan','variable_temperature_mcd','Measure the selected ligand-field and band-gap intensities',['mcd-specimens'],'temperature-mcd-data',E(6,'Figure 8'),stage='characterization',kind='analysis_data',depends=['prepare'],desc='Co Figure 8a compares 5 and 10 K; Ni Figure 8b spans 5–80 K. Caption and body monitor energies conflict and are retained as separate measurements below.')
add(r,'normalize','mcd_normalization','Normalize circular absorbance differences by absorption',['field-mcd-data','temperature-mcd-data'],'normalized-mcd',PHY,stage='characterization',kind='analysis_data',depends=['field-scan','temperature-scan'],desc='ΔA = AL − AR; θ(deg) = 32.9 ΔA/A. MCD model C0/D0 and B0/D0 coefficients are treated separately.')
optical_samples(r)
for sample,typ,rows in [('co17','C0/D0',[('ligand-field',.36,15432),('charge-transfer',.081,25000),('band-gap',.0032,28000)]),('ni15','B0/D0',[('ligand-field',.057,15163),('charge-transfer',.016,23000),('band-gap',.00088,28000)])]:
 for name,v,en in rows:
  M(r,sample+'-'+name+'-ratio',sample,'mcd_'+typ.replace('/','_').lower(),v,'',E(6,'Table 1'),status='author_derived',approximate=sample=='co17'and name=='charge-transfer',conditions=name+'; '+('Co charge transfer overlaps band-gap onset, so ratio and energy are approximate.'if sample=='co17'and name=='charge-transfer'else'Source Table 1 parameterization; ratio units are not explicitly printed in the table.'))
  M(r,sample+'-'+name+'-energy',sample,'table1_mcd_transition_energy',en,'cm^-1',E(6,'Table 1'),approximate=sample=='co17'and name=='charge-transfer',conditions=name)
M(r,'co-ct-observed','co17','negative_mcd_peak_visible_energy',25200,'cm^-1',E(5,'Figure 6a')+E(10,'IV.D.ii'),approximate=True)
M(r,'co-ct-bound','co17','co_charge_transfer_maximum_lower_bound',None,'cm^-1',E(10,'IV.D.ii'),minimum=25200,conditions='Overlap obscures the actual band maximum; source treats the visible 25200 cm−1 feature as a lower limit.')
for i,s,en,loc in [('co-lf-caption','co17',15600,'Figure 8 caption'),('co-lf-prose','co17',15700,'Figure 8 discussion'),('co-bg','co17',27200,'Figure 8 caption/discussion'),('ni-caption','ni15',15400,'Figure 8 caption'),('ni-prose','ni15',15165,'Figure 8 discussion')]:M(r,i,s,'mcd_monitor_energy',en,'cm^-1',E(6,loc))
for sample,ts in [('co17',[5,10]),('ni15',[5,10,20,40,80])]:
 for t in ts:M(r,sample+'-T'+str(t),sample,'figure8_temperature',t,'K',E(6,'Figure 8 plotted labels and text'))
M(r,'ni-flat','ni15','ni_temperature_independence_upper_context',40,'K',E(6,'Figure 8 discussion'),approximate=True)
T(r,'co-saturation','co17','co_mcd_saturation','Intensity across spectral regions increases uniformly with field/decreasing temperature and saturates at high field/low temperature, consistent with a shared Co chromophore and C-term behavior.',E(5,'Figure 6a')+E(6,'Figure 8a'))
T(r,'ni-response','ni15','ni_mcd_response','All regions share field/temperature response; the signal does not saturate and is almost temperature-independent below about 40 K. The weak band-gap response needed a different sample thickness and is poorer quality.',E(5,'Figure 6b')+E(6,'Figure 8b'))
M(r,'co-ratio','co17','bandgap_to_ligandfield_mcd_relative_reduction',100,'dimensionless',E(5,'MCD discussion'),approximate=True,status='author_derived')
M(r,'ni-relative','ni15','ni_vs_co_bandgap_rotational_strength_reduction',10,'dimensionless',E(5,'MCD discussion'),approximate=True,status='author_derived')
T(r,'normalization','co17','mcd_normalization_equation','ΔA = A_L − A_R; θ(deg) = 32.9 ΔA/A.',PHY)
r['quality']['conflicts']=['Figure 8 monitor energies: Co caption 15600 versus body 15700 cm−1; Ni caption 15400 versus body 15165 cm−1. These are not silently normalized.'];records.append(r)

r=base('zeeman','Field-dependent band-edge Zeeman shifts','procedure','Band-edge Zeeman spectroscopy','ZnO:Co')
r['materials']=[C('co-specimen','specimen','characterization')]
add(r,'acquire','zeeman_single_beam_transmission','Measure single-beam transmission as magnetic field varies',['co-specimen'],'zeeman-transmission',PHY+E(6,'Figure 9'),{'temperature':Q(5,'K',E(6,'Figure 9 discussion')),'field_range':Q(u='T',e=E(6,'Figure 9'),minimum=0,maximum=7)},stage='characterization',kind='analysis_data',desc='Same magneto-optical instrument, single-beam mode. Abs = −log(I/I0); no exact absorption threshold or fitting window is printed.')
add(r,'extract','band_edge_shift_extraction','Determine band-edge energy shifts relative to zero field',['zeeman-transmission'],'zeeman-data',E(6,'Figure 9'),stage='characterization',kind='analysis_data')
P(r,'co17','1.7% Co2+:ZnO sample from Figure 6a',E(6,'Figure 9'),explicit=True)
M(r,'average','co17','average_zeeman_redshift_per_tesla',53,'cm^-1/T',E(6,'Results'),approximate=True,conditions='Average redshift magnitude over 0–7 T, not a constant linear slope.')
M(r,'high-field','co17','high_field_zeeman_redshift_per_tesla',65,'cm^-1/T',E(6,'Results'),approximate=True,conditions='3–7 T region.')
M(r,'turning','co17','zeeman_turning_field_interval',None,'T',E(6,'Results'),minimum=1,maximum=3)
T(r,'plot','co17','figure9_model_scope','Figure 9a is the modeled band-level splitting for H parallel z; Figure 9b contains measured shifts and calculated lines. No quantum-dot crystallographic alignment or per-particle band structure is measured.',E(6,'Figure 9'));link(r,'exchange-model','Exchange-coupling analysis');records.append(r)

r=base('magnetometry','Co2+:ZnO powder magnetometry','procedure','SQUID magnetometry','ZnO:Co')
r['materials']=[C('co-aggregate-specimen','specimen','characterization'),C('co-specimen','comparison_specimen','characterization')]
add(r,'mount','sq_uid_specimen_mounting','Mount separate Co2+:ZnO powder specimens',[m['id']for m in r['materials']],'magnetometer-specimens',PHY,stage='characterization',kind='sample_set',desc='Quantum Design MPMS SQUID; holder material, powder mass, packing, field-cooling/zero-field-cooling history and sweep rate are not supplied.')
add(r,'measure','variable_field_temperature_magnetometry','Measure magnetization versus field and temperature',['magnetometer-specimens'],'raw-magnetization',PHY+MAG,{'hysteresis_temperature':Q(300,'K',E(7,'Figure 10a')),'temperature_limit':Q(350,'K',E(6,'Figure 10 discussion'))},stage='characterization',kind='analysis_data')
add(r,'subtract','holder_diamagnetism_subtraction','Subtract sample-holder diamagnetism',['raw-magnetization'],'magnetization-data',PHY,stage='characterization',kind='analysis_data',desc='No independently specified additional paramagnetic subtraction, mass correction or background polynomial is invented.')
P(r,'aggregate','Figure 10: 3.6% Co2+:ZnO aggregates',MAG,explicit=True);P(r,'isolated','Free-standing isolated Co2+:ZnO dots',E(13,'IV.D.v'))
for i,prop,v,u in [('coercivity','room_temperature_coercivity',105,'Oe'),('remanence','room_temperature_remanence',.000465,'emu/g'),('saturation','room_temperature_saturation_moment',.00256,'emu/g')]:M(r,i,'aggregate',prop,v,u,E(6,'Figure 10 discussion'),conditions='300 K, reported aggregate powder result; no uncertainty supplied.')
M(r,'tc','aggregate','curie_temperature_lower_bound',None,'K',E(6,'Figure 10 discussion')+E(13,'IV.D.v'),minimum=350,minimum_exclusive=True,conditions='No Curie transition observed up to the instrumental temperature limit; not a measured exact TC.')
T(r,'hysteresis','aggregate','aggregate_magnetic_behavior','Hysteresis properties depend only weakly on temperature; rapid saturation and a clear loop indicate ferromagnetism according to the authors. Figures preserve original field/temperature traces.',MAG,status='author_derived')
T(r,'isolated','isolated','isolated_dot_magnetic_behavior','Free-standing dots exhibit isolated-paramagnetic-dopant saturation and no long-range ordering; source explicitly distinguishes this from superparamagnetic behavior.',E(13,'IV.D.v'))
M(r,'ferro-fraction','aggregate','estimated_ferromagnetic_fraction_of_10K_signal',10,'%',E(13,'IV.D.v'),approximate=True,status='author_derived')
M(r,'per-co','aggregate','estimated_300K_ferromagnetic_moment_per_cobalt',.3,'Bohr magneton/Co',E(13,'IV.D.v'),approximate=True,status='author_derived',conditions='Potential overestimate because antiferromagnetic/spin-glass contributions can render dopants silent; source uses 10% of 3 μB/Co.')
M(r,'reference-per-co','aggregate','source_low_temperature_moment_reference',3,'Bohr magneton/Co',E(13,'IV.D.v'),status='author_derived')
link(r,'aggregation','Ambient aggregation procedure');records.append(r)

r=base('luminescence','Trap luminescence quenching by cobalt doping','procedure','Absorption and photoluminescence comparison')
r['materials']=[C('zno-specimen','specimen','characterization'),C('co-specimen','specimen','characterization'),C('ethanol','solvent','characterization')]
add(r,'prepare','ethanol_optical_specimens','Prepare separate pure and 2% Co2+:ZnO ethanol suspensions',[m['id']for m in r['materials']],'pl-specimens',SI(3,'S4'),stage='characterization',kind='sample_set',desc='These are separate samples; concentration, optical density and matched absorbed-photon normalization are not quantified.')
add(r,'measure','luminescence_absorption_comparison','Measure absorption and trap luminescence at 300 K',['pl-specimens'],'pl-data',SI(3,'S4')+E(9,'IV.D.i'),{'temperature':Q(300,'K',SI(3,'S4')),'excitation_wavelength':Q(u='nm',e=SI(3,'S4'))},stage='characterization',kind='analysis_data',desc='Excitation wavelength, collection geometry, emission instrument, slit widths, absolute yield and detector correction are not supplied; no digitized peak maxima are fabricated.')
P(r,'pure','S4 pure ZnO in ethanol',SI(3,'S4'),explicit=True);P(r,'co2','S4 2% Co2+:ZnO in ethanol',SI(3,'S4'),formula='ZnO:Co',explicit=True)
M(r,'dopant','co2','reported_specimen_cobalt_percentage',2,'%',SI(3,'S4'))
M(r,'quenching','co2','trap_luminescence_quenching_fraction',None,'%',E(9,'IV.D.i'),minimum=99,minimum_exclusive=True,conditions='Relative quenching of ZnO surface-trap emission versus pure comparator, not an absolute photoluminescence quantum yield.')
T(r,'pure','pure','pure_zno_trap_luminescence','Visible emission is dominated by surface traps; no numerical peak energy or absolute yield is printed.',E(9,'IV.D.i')+SI(3,'S4'))
T(r,'co','co2','co_quenching_interpretation','Authors attribute quenching to Co deep traps and rapid nonradiative relaxation through ligand-field states. No upper excited-state ligand-field emission is observed at room temperature.',E(9,'IV.D.i'),status='author_derived');records.append(r)

r=base('topo-optical-comparisons','TOPO, bulk and isocrystalline core/shell comparisons')
for i,label,f,e in [('co-topo','S5 TOPO-cleaned 5% Co dots','ZnO:Co',SI(3,'S5 plot label')),('co-ics','S5 earlier isocrystalline core/shell reference','ZnO:Co',SI(3,'S5 caption and reference 13')),('co-bulk','S5 bulk single-crystal reference','ZnO:Co',SI(3,'S5')),('zno-before','S6 approximately 4.2 nm ZnO before TOPO treatment','ZnO',SI(4,'S6')),('zno-after','S6 approximately 4.2 nm ZnO after TOPO treatment','ZnO',SI(4,'S6'))]:P(r,i,label,e,formula=f)
M(r,'co-topo-fraction','co-topo','si5_reported_dopant_percentage',5,'%',SI(3,'S5 plot label'),conditions='Not proven to be the same batch as the 5% as-grown Figure 5 TEM specimen.')
for i in ['zno-before','zno-after']:M(r,i+'-diameter',i,'si6_reported_particle_diameter',4.2,'nm',SI(4,'S6'),approximate=True,conditions='Before/after comparison scope; not a universal TOPO-induced size increase.')
M(r,'toluene','zno-after','solvent_absorption_onset_context',35000,'cm^-1',SI(4,'S6'),conditions='The rising absorbance is assigned to toluene, not a new ZnO transition.')
T(r,'s5','co-topo','si5_ligand_field_comparison','Room-temperature spectra compare bulk single crystal, present TOPO-cleaned dots and earlier ICS dots. Greater homogeneity after TOPO is inferred from improved resolution; curves are not an independently quantified synthesis recipe for ICS.',SI(3,'S5')+E(9,'IV.C'),status='author_derived')
T(r,'ics','co-ics','cited_ics_method_scope','Earlier isocrystalline core/shell processing grows pure ZnO epitaxially around doped ZnO in ethanol. References 13–14 are cited, but their full recipes are not reproduced or downloaded here.',E(9,'IV.C'))
T(r,'s6','zno-after','si6_absorption_comparison_scope','S6 compares band-gap spectra of approximately 4.2 nm dots before and after TOPO treatment; DMSO synthesis and TOPO-capped/toluene states are labelled. No exact peak-fit table or raw absorbance array is supplied.',SI(4,'S6'));records.append(r)

r=base('nucleation-model','Dopant exclusion, growth inhibition and Gibbs–Thompson interpretation')
P(r,'model','Author model of separate pure and Co/Ni-doped ZnO syntheses',E(7,'IV.A–B')+E(8,'Scheme 1 and IV.B'))
T(r,'eq3','model','equation_gibbs_thomson','S_r = S_B exp[2σV_m/(rRT)]. S_r is crystallite solubility at radius r; S_B is bulk solubility, V_m molar volume, σ specific surface energy, R gas constant and T temperature.',E(8,'Equation 3'),status='author_derived')
T(r,'cluster','model','basic_acetate_cluster_hypothesis','Early noncrystalline absorption is attributed to basic zinc-acetate clusters. Zn4O(OAc)6 and Zn10O4(OAc)12 are cited ethanol structures; analogous DMSO precursors are proposed, not directly identified in this study.',E(7,'IV.A'),status='author_derived')
T(r,'exclusion','model','dopant_exclusion_inference','Critical surviving nuclei exclude dopants; subsequent surface binding and OH− reaction incorporate Co nearly isotropically during growth. This is inferred from spectral titration, not an atom-by-atom dopant map.',E(8,'IV.B')+E(9,'IV.B continuation'),status='author_derived')
T(r,'scheme','model','scheme1_scope','Scheme 1 contrasts surviving undoped ZnO nuclei followed by surface Co binding/growth with inhibited direct nucleation from Co-containing precursors. The circles and symbols are mechanistic illustrations, not measured structure coordinates.',E(8,'Scheme 1'),status='author_derived')
T(r,'geometry','model','coordination_barrier_rationale','Pseudo-octahedral dopants in basic acetate precursors must convert to tetrahedral ZnO coordination, adding a nucleation barrier. The authors also emphasize reduced thermodynamic driving force from impurity strain.',E(8,'IV.B'),status='author_derived')
T(r,'strain','model','strain_solubility_rationale','Surface/near-surface dopants increase strain and specific surface energy, increasing solubility and the critical nucleation radius and lowering metastable final dimensions. No numerical σ, solubility, critical radius or activation energy is fitted.',E(8,'Equation 3 discussion')+E(9,'Continuation'),status='author_derived')
T(r,'surface-intermediate','model','surface_intermediate_assignment','A broad intermediate is assigned to inhomogeneous tetrahedral Co bound at ZnO surfaces, as monomers or basic-acetate fragments, before incorporation by hydroxide. Comparison to excess-acetate Co in DMSO supports stronger acetate than lattice-oxide ligand fields.',E(8,'IV.B'),status='author_derived')
T(r,'linearity','model','base_consumption_inference','Band-gap intensity versus added base extrapolates nearly through the origin after nucleation, suggesting most added hydroxide forms ZnO rather than persistent molecular precursors. Internal-Co intensity instead intercepts near 0.36 equivalent, supporting initial core exclusion.',E(7,'Figure 11 and discussion')+E(8,'Continuation'),status='author_derived')
T(r,'scope','model','spatial_homogeneity_limit','Nearly isotropic incorporation during growth and homogeneous substitutional spectroscopy do not imply uniform dopant content in the initial undoped critical nucleus or zero lattice defects.',E(1,'Abstract')+E(8,'IV.B'),status='author_derived');records.append(r)

r=base('mcd-intensity-model','MCD intensity parameterization and ground-state response')
P(r,'co','Co2+:ZnO MCD interpretation',E(5,'Equation 1')+E(12,'IV.D.iv'),formula='ZnO:Co');P(r,'ni','Ni2+:ZnO MCD interpretation',E(5,'Equation 2')+E(12,'IV.D.iv'),formula='ZnO:Ni')
T(r,'eq1','co','equation_mcd_c_term','C0/D0 = (kT/βH)(Δε/ε). Here T is kelvin temperature, H the applied field in tesla, Δε the source-defined molar ellipticity and ε the molar absorption coefficient; source Co intensities are corrected for saturation.',E(5,'Equation 1'),status='author_derived')
T(r,'eq2','ni','equation_mcd_b_term','B0/D0 = (1/βH)(Δε/ε). Source temperature-independent B-term intensity parameterization, using the same β,H and spectroscopic definitions.',E(5,'Equation 2'),status='author_derived')
for i,v,u in [('k',.69503,'cm^-1/K'),('beta',.46686,'cm^-1/T')]:M(r,i,'co','source_mcd_constant_'+i,v,u,E(5,'Equation 1 definitions'),status='author_derived')
M(r,'co-spin','co','co_ground_spin',1.5,'dimensionless',E(12,'IV.D.iv'),status='author_derived')
M(r,'co-zfs','co','cited_co_zero_field_splitting_2D',5.5,'cm^-1',E(12,'IV.D.iv and references 20,48'),conditions='Positive 2D, from cited bulk spectroscopy; no independent nanocrystal fit is tabulated.')
T(r,'co-ground','co','co_ground_state_interpretation','Tetrahedral 4A2 has no orbital angular momentum. Out-of-state spin–orbit coupling gives a small positive zero-field splitting and explains nested S=3/2 saturation curves.',E(12,'IV.D.iv'),status='author_derived')
for i,v in [('first',160),('second',260)]:M(r,'ni-'+i,'ni','cited_nickel_ground_multiplet_excitation',v,'cm^-1',E(12,'IV.D.iv and reference 49'),conditions='A2 and E (J=1) excited levels above A1 (J=0); values estimated from bulk susceptibility, approximately ±25 cm−1 accuracy.')
M(r,'ni-level-accuracy','ni','cited_nickel_level_estimate_accuracy',25,'cm^-1',E(12,'IV.D.iv'),approximate=True,conditions='Source stated accuracy of cited level estimates, not a current fitted confidence interval.')
T(r,'ni-ground','ni','ni_ground_state_interpretation','Spin–orbit coupling splits tetrahedral 3T1(F), leaving nondegenerate A1(J=0) and near-zero <Sz>. Magnetic-field-induced mixing with A2 and E produces weaker second-order Zeeman/B-term response without high-field saturation.',E(12,'IV.D.iv')+E(13,'Continuation'),status='author_derived')
T(r,'sumrules','co','co_mcd_sum_rule_interpretation','Co ligand-field integration has a small net negative sum-rule violation attributed primarily to out-of-state spin–orbit coupling with 4T2(F).',E(9,'IV.D.i'),status='author_derived')
T(r,'ni-sumrule','ni','ni_mcd_sum_rule_interpretation','Net positive Ni ligand-field MCD violates the intensity sum rule, attributed to strong spin–orbit coupling within 3T1(F).',E(9,'IV.D.i'),status='author_derived');records.append(r)

r=base('charge-transfer-model','Charge-transfer assignment and optical electronegativity analysis')
P(r,'co','Co2+:ZnO charge-transfer analysis',E(10,'IV.D.ii'),formula='ZnO:Co');P(r,'ni','Ni2+:ZnO charge-transfer analysis',E(10,'IV.D.ii'),formula='ZnO:Ni');P(r,'reference','Molecular/reference model comparisons',E(10,'IV.D.ii')+E(11,'Continuation'))
T(r,'eq4','ni','equation_lmct_state','Ni2+ + hν → Ni+ + h+_VB. The charge-transfer excitation is described as a central Ni+ ion with an electrostatically bound valence-band hole having hydrogen-like character.',E(10,'Equation 4'),status='author_derived')
T(r,'eq5','reference','equation_optical_electronegativity','E_LMCT = 30000 cm−1[χopt(L) − χopt(M)] + ΔSPE + 10Dq. χopt values use the source optical/Pauling-scale relationship; 10Dq accounts for excitation into the antibonding t2 set.',E(10,'Equation 5'),status='author_derived')
T(r,'eq6a','reference','equation_spin_pairing_energy','SPE = [<S(S+1)> − S(S+1)]D.',E(10,'Equation 6a'),status='author_derived')
T(r,'eq6b','reference','equation_spin_pairing_parameter','D = (7/6)[(5/2)B + C]. B and C are Racah repulsion parameters from ligand-field data; this D differs from the zero-field-splitting notation used elsewhere.',E(10,'Equation 6b'),status='author_derived')
T(r,'eq7a','reference','equation_charge_transfer_mixing','ψ′_A = sqrt(1−c²) ψ_A − c ψ_D, with unperturbed acceptor and donor one-electron orbitals ψ_A and ψ_D.',E(11,'Equation 7a'),status='author_derived')
T(r,'eq7b','reference','equation_mixing_coefficient','c ≈ −<ψ_A|H|ψ_D>/(E_A−E_D). Charge-transfer intensity is proportional to c²; donor–acceptor resonance overlap competes with valence-shell ionization-energy mismatch.',E(11,'Equation 7b and discussion'),status='author_derived')
for sample,dq,b,cb,spe,chi in [('co',390,775,4.5,8440,1.9),('ni',420,770,4.8,4370,2.0)]:
 for key,val,u in [('dq',dq,'cm^-1'),('racah-b',b,'cm^-1'),('c-over-b',cb,'dimensionless'),('delta-spe',spe,'cm^-1'),('chi-opt',chi,'dimensionless')]:M(r,sample+'-'+key,sample,'source_model_'+key.replace('-','_'),val,u,E(10,'Equation 5–6 parameter discussion'),status='author_derived',approximate=key=='chi-opt',conditions='Spectroscopic/cited model parameters, not independently optimized synthesis outputs.')
for i,s,prop,v,u in [('halide-gap','reference','cited_tetrahalide_lmct_energy_difference',6600,'cm^-1'),('chi-difference','reference','nickel_cobalt_optical_electronegativity_difference',.1,'dimensionless'),('calculated-gap','reference','calculated_lmct_energy_difference',6770,'cm^-1'),('ni-onset','ni','estimated_lmct_onset',19500,'cm^-1'),('co-predicted','co','predicted_lmct_onset',26300,'cm^-1'),('bound-oxide','reference','effective_dopant_bound_oxide_electronegativity',2.4,'dimensionless'),('molecular-oxide','reference','typical_molecular_oxide_electronegativity',3.2,'dimensionless'),('pure-oxide','reference','cited_pure_zno_oxide_electronegativity',2.0,'dimensionless'),('confinement','reference','predicted_accessible_electronegativity_increase',.02,'dimensionless')]:M(r,i,s,prop,v,u,E(10,'IV.D.ii')+E(11,'Continuation'),status='author_derived',approximate=i not in ['chi-difference'])
M(r,'oxide-range','reference','cited_molecular_oxide_electronegativity_range',None,'dimensionless',E(10,'Note 33'),minimum=3.0,maximum=3.9)
M(r,'oxidation-ease','reference','model_oxide_oxidation_energy_difference',None,'eV',E(11,'Optical electronegativity discussion'),minimum=2,minimum_exclusive=True,status='author_derived')
M(r,'ni-ct-context','ni','nickel_ct_absorption_discussion_range',None,'cm^-1',E(9,'IV.D.ii'),minimum=18000,maximum=23000,approximate=True,conditions='Broad discussion interval; Figure 6b region is separately described as 19400–25300 cm−1.')
T(r,'co-assignment','co','co_lmct_assignment','Authors favor LMCT for the broad negative MCD feature visible around 25200 cm−1, based on its intensity, small C0/D0 and comparison with Ni. Overlapping MLCT or other transitions are not excluded; the true band maximum is obscured by band-gap intensity.',E(10,'IV.D.ii'),status='author_derived')
T(r,'weak-mlct','co','weak_mcd_mlct_hypothesis','A broad much weaker negative MCD feature across the visible is proposed as an MLCT candidate and follows S=3/2 saturation. The source says Co-to-valence-band but subsequently describes a conduction-band acceptor; this wording is retained as an unresolved proposed assignment, not a proven transition.',E(11,'IV.D.ii continuation'),status='author_derived')
M(r,'weak-relative','co','proposed_mlct_to_lmct_intensity_reduction',10,'dimensionless',E(11,'IV.D.ii'),approximate=True,status='author_derived')
T(r,'covalency','reference','charge_transfer_covalency_inference','Strong p–d hybridization produces greater LMCT intensity than s–d hybridization produces MLCT. Low effective oxide electronegativity reflects its participation in the extended host bands; slight local polarization and small confinement changes are inferred.',E(11,'IV.D.ii'),status='author_derived')
r['quality']['conflicts']=['The weak-MLCT proposal names a valence-band transition then describes conduction-band acceptor overlap; it remains a source hypothesis with unresolved wording.'];records.append(r)

r=base('exchange-model','Mean-field Zeeman and exchange-coupling analysis')
P(r,'co17','1.7% Co2+:ZnO Zeeman model',E(11,'IV.D.iii')+E(12,'Continuation'),formula='ZnO:Co');P(r,'ni15','1.5% Ni2+:ZnO exchange estimate',E(12,'IV.D.iii'),formula='ZnO:Ni');P(r,'reference','Bulk/reference model context',E(12,'Table 2 and discussion'))
T(r,'eq8a','co17','equation_conduction_zeeman','ΔE_Zeeman(CB) = x N0α <Sz>. x is dopant mole fraction; <Sz> is the spin-Hamiltonian expectation value.',E(11,'Equation 8a'),status='author_derived')
T(r,'eq8b','co17','equation_valence_zeeman','ΔE_Zeeman(VB) = x N0β <Sz>. Exchange parameters describe conduction- and valence-band coupling. The Γ9 |±3/2> levels follow this expression; Γ7 |±1/2> levels split one-third as much in the adopted model.',E(11,'Equation 8b')+E(12,'Continuation'),status='author_derived')
T(r,'eq9','reference','equation_exchange_hybridization','N0β_hyb ≈ −(1/S)[<ψ_VB|H_pd|ψ_t2>²/E_LMCT]. Resonance overlap is scaled by spin and charge-transfer energy.',E(12,'Equation 9'),status='author_derived')
for i,s,prop,val,u,qual in [('alpha-ev','co17','fixed_n0_alpha',.2,'eV','Fixed typical value, not independently fitted.'),('alpha-cm','co17','fixed_n0_alpha',1600,'cm^-1','Source alternative unit.'),('valence-split','reference','cited_zero_field_valence_splitting',56,'cm^-1','Cited ZnO wurtzite versus cubic valence splitting.'),('beta-co','co17','fitted_n0_beta',-2.3,'eV','Printed ±0.3 eV; model-dependent estimate.'),('beta-co-width','co17','reported_n0_beta_uncertainty',.3,'eV','Statistical interpretation not specified.'),('beta-co-cm','co17','fitted_n0_beta',-18500,'cm^-1','Source alternative unit.'),('beta-co-cm-width','co17','reported_n0_beta_uncertainty',2400,'cm^-1','Printed source equivalent uncertainty.'),('geff','co17','effective_valence_g_factor',200,'dimensionless','Effective Γ9 valence-doublet estimate.'),('beta-ni','ni15','estimated_n0_beta',-4.5,'eV','Printed ±0.6 eV; estimated using relative LMCT energies and spins, not a direct Ni Zeeman fit.'),('beta-ni-width','ni15','reported_n0_beta_uncertainty',.6,'eV','Source stated uncertainty.'),('beta-ni-cm','ni15','estimated_n0_beta',-36300,'cm^-1','Source alternative unit.'),('ratio','ni15','estimated_ni_to_co_exchange_magnitude_ratio',1.9,'dimensionless','Assumes similar resonance integrals.'),('scaling','reference','cited_volume_scaling_prediction_n0_beta',-5,'eV','Approximate prior prediction, not the fitted nanocrystal result.'),('scaling-cm','reference','cited_volume_scaling_prediction_n0_beta',-40000,'cm^-1','Approximate source unit equivalent.'),('a','reference','cited_zno_lattice_parameter_a',3.2495,'Å','Reference host dimensions, not nanocrystal refinement.'),('c','reference','cited_zno_lattice_parameter_c',5.2067,'Å','Reference host dimensions, not nanocrystal refinement.')]:M(r,i,s,prop,val,u,E(11,'IV.D.iii')+E(12,'IV.D.iii and Table 2'),status='author_derived'if i not in ['a','c','valence-split']else'reported',approximate=i in ['geff','ratio','scaling','scaling-cm','valence-split'],qualifier=qual)
for dopant,host,value,ref in [('Co','CdTe',-2.33,39),('Co','CdSe',-2.12,39),('Co','ZnTe',-3.03,39),('Mn','CdTe',-.83,40),('Mn','CdSe',-1.30,40),('Mn','ZnTe',-1.1,40),('Mn','ZnO',-2.7,40)]:
 sid='ref-'+dopant.lower()+'-'+host.lower();P(r,sid,'Table 2 bulk '+dopant+':'+host+' literature comparator',E(12,'Table 2'),formula=host+':'+dopant)
 M(r,sid,sid,'cited_bulk_n0_beta',value,'eV',E(12,'Table 2'),tech='Cited literature comparison',conditions=f'Reference {ref}; no current synthesis or measured nanocrystal data are asserted for this host/dopant.')
T(r,'model-limits','co17','zeeman_model_limitations','Mean-field fit omits full anisotropies in ZnO splitting, optical selection rules and Co susceptibility. Preliminary fixed-anisotropy modeling gives similar N0β but worse reproduction; extra parameters are not warranted by these data.',E(12,'IV.D.iii'),status='author_derived')
T(r,'beta','reference','exchange_magnitude_interpretation','Antiferromagnetic p–d covalency dominates N0β; small unit-cell dimensions increase overlap but high LMCT energy counteracts volumetric scaling. Volume-only predictions omit electronegativity and confinement effects.',E(11,'IV.D.iii')+E(12,'IV.D.iii'),status='author_derived')
T(r,'ni-contrast','ni15','nickel_exchange_zeeman_contrast','Estimated |N0β| is about 1.9 times larger for Ni, yet its 5 K MCD/Zeeman response is at least an order smaller because spin–orbit coupling makes the Ni ground state weakly magnetized.',E(12,'IV.D.iii–iv')+E(13,'Continuation'),status='author_derived');records.append(r)

r=base('magnetization-model','Aggregate domains, magnetic anisotropy and proposed coupling','observation',formula='ZnO:Co')
P(r,'aggregate','3.6% Co2+:ZnO aggregate interpretation',E(13,'IV.D.v'))
T(r,'eq10','aggregate','equation_magnetization_lifetime','τ = τ0 exp[KV/kT]. KV is the magnetocrystalline anisotropy-energy barrier, K the anisotropy factor and V the magnetic-domain volume. τ0 is the inverse attempt frequency related to Larmor precession.',E(13,'Equation 10'),status='author_derived')
M(r,'attempt-time','aggregate','order_of_magnitude_attempt_time',1e-9,'s',E(13,'Equation 10 discussion'),approximate=True,status='author_derived')
M(r,'domain-spin','aggregate','effective_domain_spin_lower_bound',None,'dimensionless',E(13,'Brillouin-function interpretation'),minimum=8000,approximate=True,status='author_derived')
M(r,'domain-co','aggregate','cobalt_ions_per_domain_lower_bound',None,'ions',E(13,'Brillouin-function interpretation'),minimum=5000,approximate=True,status='author_derived')
M(r,'co-per-dot','aggregate','estimated_cobalt_ions_per_dot',200,'ions',E(13,'Domain-size calculation'),approximate=True,status='author_derived',conditions='Author estimate for 3.6% Co and 4.9 nm dots.')
M(r,'dots-per-domain','aggregate','dots_per_domain_lower_bound',None,'nanocrystals',E(13,'Domain-size calculation'),minimum=25,approximate=True,status='author_derived')
T(r,'domains','aggregate','domain_size_model_limit','Brillouin-function curvature gives a lower-bound effective spin/domain estimate; actual domains may be much larger and may contain walls. These are not measured grain dimensions or counts of particles in the SEM image.',E(13,'IV.D.v'),status='author_derived')
T(r,'interface','aggregate','interface_carrier_hypothesis','Aggregation may introduce fusion-interface defects providing carriers for double exchange, RKKY or Zener coupling, while larger domains raise anisotropy barriers. These mechanisms are proposed, with experiments still in progress.',E(13,'IV.D.v'),status='author_derived')
T(r,'intrinsic','aggregate','author_intrinsic_ferromagnetism_claim','The authors attribute room-temperature ferromagnetism to substitutional dopants rather than segregated phases, using unchanged diffraction and low-temperature aggregation. This is their interpretation of the reported evidence, not an independent modern verification.',E(13,'IV.D.v')+E(14,'Conclusion'),status='author_derived');records.append(r)

r=base('source-context','Document coverage, references and unresolved source differences')
P(r,'source','Current main article and matched supporting information',E(1,'Title and abstract')+E(14,'Supporting Information Available'))
T(r,'coverage','source','inspected_document_scope','All 14 main pages and four matched SI pages are text-read and visually inspected: Figures 1–11, Scheme 1, Tables 1–2, Equations 1–10 with subparts, Figures S1–S6 and numbered references 1–51. Source reading is separate from reviewing full cited papers.',E(1,'Opening')+E(14,'Ending')+SI(1,'S1')+SI(2,'S2–S3')+SI(3,'S4–S5')+SI(4,'S6'))
T(r,'si-match','source','supporting_information_identity','Main p.14 enumerates all six SI figures with matching contents. SI metadata identifies Daniel Gamelin; the four SI pages lack a standalone paper title/byline but contents and exact cross-references match.',E(14,'SI declaration')+SI(1,'Heading and metadata'))
T(r,'prior','source','prior_synthesis_context','Ethanol-based DMS synthesis and ICS shell processing are prior references 13–14, not fully reconstructed here. Thin-film deposition claims and other transition-metal/host systems are cited background, not additional recipes from this source.',E(1,'Introduction')+E(2,'Introduction and references')+E(9,'IV.C'))
T(r,'structures','source','atomic_structure_availability','The bundle includes real wide-area electron-diffraction images for pure and Co-doped ZnO and SI Ni-doped ZnO. It supplies no measured atomic-coordinate file, refined sample cell/dopant occupancy or atom-resolved spatial dopant map. Bulk lattice constants in theory are reference context.',E(4,'Figure 2c')+E(5,'Figure 5c')+SI(2,'S3')+E(12,'Exchange discussion'))
T(r,'outlook','source','author_future_outlook','Colloids are proposed as processable building blocks for more sophisticated ferromagnetic architectures and spintronic applications. No spin-LED, current–voltage, spin-injection efficiency or device-performance measurement is reported.',E(14,'Conclusion'),status='author_derived')
T(r,'unreconciled','source','source_conflict_register','Preserve 0.6 versus 0.66 base equivalents and printed-volume arithmetic, 0.552 versus 0.554 M titration feed, generic TM acetate versus explicit Ni perchlorate, Figure 8 caption/body monitor energies, aggregate 5.0 versus 4.9 nm, intermediate Co band 17500 versus 19000 cm−1, inconsistent Co term labels and tentative MLCT band wording. No silent repair is made.',E(3,'Figure 1')+E(4,'Figures 3–4')+E(6,'Figure 8')+E(8,'Intermediate discussion')+E(11,'MLCT discussion')+E(13,'Aggregate discussion'))
records.append(r)

if __name__=='__main__':
 out=B/'canonical-drafts';out.mkdir(exist_ok=True);errors=[]
 for r in records:
  errors+=validate_record(r);(out/(r['record_id']+'.json')).write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 report={'status':'failed'if errors else'passed','record_count':len(records),'operation_count':sum(len(r['operations'])for r in records),'measurement_count':sum(len(r['measurements'])for r in records),'material_slots':sum(len(r['materials'])for r in records),'source_read_pages':18,'source_visual_pages':18,'main_pages':14,'si_pages':4,'errors':errors}
 (B/'records-validation.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 (B/'canonical-material-identities.json').write_text(json.dumps({'source_id':SID,'source_group':SID,'materials':[{'id':i,'name':n,'formula':f}for i,(n,f,e)in CHEM.items()],'record_material_ids':{r['record_id']:[m['id']for m in r['materials']]for r in records}},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 raw=json.loads((B/'source-manifest.json').read_text(encoding='utf-8-sig'))
 (B/'canonical-record-manifest.json').write_text(json.dumps({'source_id':SID,'source_group':SID,'source_fingerprint':raw.get('fingerprint'),'main_pages_read_and_visually_inspected':14,'si_pages_read_and_visually_inspected':4,'supporting_information':'Four matched pages containing S1–S6, confirmed by main declaration/cross-references and author metadata; all inspected.','records':[{'id':r['record_id'],'record_type':r['record_type'],'sha256':hashlib.sha256((out/(r['record_id']+'.json')).read_bytes()).hexdigest(),'operation_ids':[o['id']for o in r['operations']],'sample_ids':[p['sample_id']for p in r['products']],'measurements':len(r['measurements'])}for r in records]},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 print(json.dumps(report))
 if errors:raise SystemExit(1)
