from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
B=Path(__file__).resolve().parent;MON=B.parent.parent;M=MON.parent.parent;S=M/'recipe-atlas'
def read(p):return json.loads(p.read_text(encoding='utf8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
n=read(B/'native-publication.json');saved=n['saved_version'];d=n['deployment']
assert d['status']=='succeeded' and d['url'] and saved['id']==d['version_id']
assert saved['source']['commit_sha']==read(B/'publication-source.json')['commit_sha']
ledger=read(MON/'ledger.json');assert ledger['current_paper']['group_id']=='10.1021_ja036811v'
g=ledger['groups']['10.1021_ja036811v'];fp=g['fingerprint'];assert fp['generation']==g['generation']==2
assert fp['bundle_sha256']=='74a80b33be45718ddc1d745e0a5c48baf80dae69ff1e01671abcc14c32b96c2f'
assert set(fp['files'].values())=={'48bb96493905290ae44c58f2346c6313677041e68ec5a9d50bdc428011c2be9f','aba65f3549f74271d5d716e49c343977a43891fb9bd58dac76b0bb3bb59d08ef'}
write(B/'final-source-fingerprint.json',{'group_id':'10.1021_ja036811v',**fp})
inv=read(S/'data/inventory-summary.json');row=next(x for x in inv['per_paper']if x['source_group']=='schwartz2003')
index=read(S/'dist/data/materials-index.json');hubs=[x for x in index['materials']if x['formula']in['ZnO','ZnO:Co','ZnO:Ni']];assert len(hubs)==3
reader=read(S/'data/paper-reviews/schwartz2003.json');audit=read(B/'source-audit.json');records=[read(S/'data/records'/(k+'.json'))for k in row['record_ids']]
archive=S/'.sites-runtime/site-schwartz2003.tar.gz';assert sha(archive)==read(B/'archive-validation.json')['sha256']
p=dict(status='published',source_commit=saved['source']['commit_sha'],site_project_id=saved['project_id'],public_live_version=saved['version_number'],dataset_version=read(S/'dist/data/dataset-manifest.json')['dataset_version'],source_pushed=True,archive=str(archive.relative_to(M)),archive_sha256=sha(archive),archive_storage=saved['archive_storage'],version_id=saved['id'],deployment_id=d['id'],deployment_status=d['status'],public_url=d['url'],published_at=d['updated_at'],review_scope='supplied_main_and_matched_si',source_id='schwartz2003',doi='10.1021/ja036811v',records=len(records),synthesis_routes=row['synthesis_route_variant_count'],controls=row['contextual_control_count'],supporting_procedures=row['procedure_count'],contextual_observations=row['contextual_observation_count'],measurement_entries=sum(len(r['measurements'])for r in records),operations=sum(len(r['operations'])for r in records),reader_evidence_items=sum(len(s['items'])for s in reader['reader_sections']),source_audit_units=audit['unit_count'],typed_facts=sum(reader['counts'][k]for k in ['typed_characterization_rows','operation_parameter_facts','reagent_quantity_facts','stock_quantity_facts']),source_typed_anchors=audit['typed_anchor_count'],original_assets=len(read(B/'reader-assets/crop-manifest.json')['assets']),original_figures=17,original_main_figures=11,original_si_figures=6,original_tables=2,original_schemes=1,numbered_equations=10,equation_components=13,canonical_records_total=inv['summary']['canonical_records'],material_hubs_total=len(index['materials']),source_groups_total=inv['summary']['total_canonical_source_groups'],source_documents_unchanged=True,source_generation=2,source_fingerprint_at=fp['created_at'],bundle_sha256=fp['bundle_sha256'],native_publication_evidence='native-publication.json',browser_checks='browser-qa.json',build_checks='build-validation.json',independent_audit=['source-audit.json','canonical-records-audit.json','reader-source-audit.json','molecular-source-audit.json','bindings-source-audit.json','visual-source-audit.json','public-review-proposal/proposal-validation.json','reader-assets/integrated-presentation-audit.json'],material_urls={h['formula']:d['url'].rstrip('/')+'/'+h['url']for h in hubs},paper_url=d['url'].rstrip('/')+'/paper-review.html?id=schwartz2003',si_status='Matched four-page SI containing all six declared figures fully text-read and visually reviewed.')
assert len(records)==30 and p['synthesis_routes']==3 and p['dataset_version']=='0.20.0'
write(B/'publication-checkpoint.json',p)
ms=read(B/'milestones.json');ms['publish']={'status':'complete','evidence':[str(B/'publication-checkpoint.json'),str(B/'native-publication.json'),str(B/'final-source-fingerprint.json')],'note':'Native publication succeeded on the same existing public MatterSyn Site. Source generation unchanged. Closure covers all14 main+4 matched SI pages; later or changed evidence reopens review.'};assert all(x['status']=='complete' and x['evidence']for x in ms.values());write(B/'milestones.json',ms)
c=read(B/'checkpoint.json');c.update(website_published=True,checkpoint_at=datetime.now(timezone.utc).isoformat(),public_live_version=saved['version_number'],dataset_version=p['dataset_version'],publication_evidence=str(B/'publication-checkpoint.json'),current_work_items=[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in ms.items()],next_action='Supplied main and matched SI contribution published and closed. Continue oldest eligible local arrival through existing heartbeat; changed evidence reopens this source.');write(B/'checkpoint.json',c)
print(json.dumps({'publication':'succeeded','version':p['public_live_version'],'material_urls':p['material_urls'],'records':p['records'],'milestones':'complete'}))
