from pathlib import Path
import json, hashlib, shutil
A=Path(__file__).resolve().parent
P=A.parents[1]; C=P/'canonical-proposal/v1'; ROOT=P.parents[4]
def read(p): return json.loads(p.read_text('utf-8'))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def save(name,value): (A/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n','utf-8')
assert not (A/'package-freeze.json').exists(), 'Frozen proposals are immutable'
records=[]
for item in read(C/'record-manifest.json')['records']:
    p=Path(item['path']); assert sha(p)==item['sha256']
    r=read(p)
    if r['operations']: records.append(r)
cfg={}
def scene(oid,title,art,prose,notes=(),**extra):
    cfg[oid]=dict(title=title,art=art,prose=prose,notes=[dict(label=k,value=v) for k,v in notes],**extra)
scene('cs-load','Cs-oleate preparation · precursor charge','load','Load Cs2CO3 and ODE into the reported 50 mL three-neck flask.', [('Volume basis','18 mL is the ODE charge, not a verified final stock volume.'),('Unreported','Initial mixing duration and final Cs-oleate molarity.')], reagent='Cs2CO3',solvent='ODE',flask='50 mL three-neck flask')
scene('cs-degas','Cs-oleate preparation · initial degassing','degas','Degas the initial Cs2CO3/ODE mixture at the reported temperature and duration.', [('Unreported','Numeric pressure and heating-device type.'),('Scope','OA addition belongs to the next stage.')], contents='Cs2CO3 + ODE',atmosphere='Degassing')
scene('cs-add-oa','Cs-oleate preparation · OA addition and dissolution','add-heat','Inject dry OA under Ar after an additional 15 min of degassing; then increase the temperature to 150 °C until a fully transparent solution forms.', [('Order','Additional degassing → OA injection under Ar → heating to dissolution.'),('Unreported','Injection speed, dissolution duration and final stock concentration.')], contents='Cs precursor + ODE',addition='Dry OA',atmosphere='Ar',endpoint='Transparent solution')
scene('cs-store','Cs-oleate preparation · cooling and storage','store','Cool the prepared stock to room temperature, then store it under vacuum for later use.', [('Environment','Room temperature; storage under vacuum.'),('Unreported','Numeric room temperature, vacuum pressure and storage duration.')], contents='Cs-oleate stock',atmosphere='Vacuum storage')
scene('cs-reactivate','Cs-oleate preparation · pre-injection conditioning','two-heat','Before injection, degas the stored stock at 120 °C for at least 30 min, then heat it to 150 °C under Ar.', [('Separate phases','120 °C degassing precedes 150 °C heating under Ar.'),('Unreported','Numeric pressure and duration of the final heating phase.')],left='Degas at 120 °C',right='Heat to 150 °C',bottom='Then use the specified aliquot')
scene('mn-load','Hot injection · manganese precursor charge','load','Load anhydrous MnCl2 with dry ODE, OA and OlAm into the reported 25 mL three-neck flask; scaling and handling occur under an inert atmosphere.', [('Reagents','Dry ODE, dry OA and dry OlAm are separate named components.'),('Unreported','Full drying procedures and inert-gas identity during initial handling.')], reagent='Anhydrous MnCl2',solvent='ODE + OA + OlAm',flask='25 mL three-neck flask')
scene('mn-degas','Hot injection · manganese precursor degassing','degas','Heat and degas the manganese precursor solution under vacuum. The source describes a reddish-brown to transparent-yellow change.', [('Atmosphere','Vacuum; numeric pressure unreported.'),('Unreported','Heating-device type and stirring speed.')], contents='MnCl2 / ODE / OA / OlAm',atmosphere='Vacuum')
scene('nc-inject','Hot injection · five separate preparation conditions','inject','Under Ar, raise the reaction flask to the selected injection temperature and swiftly inject its paired Cs-oleate aliquot with vigorous stirring.', [('Condition selection','Five demonstrated preparation labels are listed below; they are alternatives, not successive additions or a full Cartesian grid.'),('Loading basis','Printed Mn/Cs loading labels are retained without reconstructing an unreported stock molarity.'),('Unreported','Injection speed, stirring rpm and numeric Ar pressure.')],contents='Mn precursor solution',addition='Cs-oleate aliquot',include_options=True)
scene('nc-grow-quench','Hot injection · short growth and cooling','quench','Keep the reaction at its selected injection temperature for 5 s, then quickly quench it in an external ice-water bath.', [('Order','Growth hold precedes the external ice-water bath.'),('Bath boundary','Ice-water is external coolant, not a reaction ingredient.'),('Unreported','Bath temperature, cooling trace and terminal reaction temperature.')],include_options=True)
scene('nc-centrifuge','Primary isolation · retain precipitate','centrifuge','Centrifuge each crude solution without antisolvent. Retain the white-pinkish nanocrystal precipitate.', [('Added antisolvent','None for this primary isolation.'),('Retained fraction','Precipitate; the subsequent step discards supernatant.'),('Unreported','Rotor radius and relative centrifugal force; rpm is not converted.')],contents='Crude NC dispersion',outcome='Retain precipitate')
scene('nc-dry','Primary isolation · vacuum desiccation','desiccator','Discard the supernatant and dry the vials containing NC precipitate in a vacuum desiccator, typically overnight.', [('Duration','Typically overnight; no numerical duration inferred.'),('Unreported','Drying temperature and numeric vacuum pressure.')],contents='Retained NC precipitate')
scene('nc-redisperse','Primary isolation · hexane dispersion','redisperse','Redisperse the dried NC precipitate in hexane for further use.', [('Sample boundary','Keep the five preparation conditions as separate dispersions.'),('Unreported','Primary redispersion volume and NC concentration.')],reagent='Dry NC precipitate',solvent='Hexane')
scene('hexane-spin','Purification control · hexane-only centrifugation','centrifuge','Centrifuge prepurified NCs dispersed in 2 mL hexane at the reported range of speeds. No visible precipitation was observed.', [('Outcome','No visible NC precipitation; no recovered pellet is asserted.'),('Unreported','Spin duration and number of individual trials.')],contents='Prepurified NCs in hexane',outcome='No visible precipitation')
scene('ipa-or-etoac','Purification control · alternative antisolvents','split','Test anhydrous isopropanol and anhydrous ethyl acetate in separate crude-dispersion portions. The paper specifies one antisolvent portion per two NC-dispersion portions.', [('Separate trials','IPA OR ethyl acetate; do not combine them.'),('Volume basis','Antisolvent : NC dispersion = 1 : 2 by portions.'),('Outcome','Resulting precipitates showed no visible PL.'),('Unreported','Absolute portion volumes and centrifugation settings.')],left='Isopropanol trial',right='Ethyl acetate trial',bottom='Distinct precipitates / no visible PL')
scene('meoac-spin','Purification control · methyl acetate precipitation','centrifuge','Add anhydrous methyl acetate to the prepurified NC suspension at a 1:1 volume ratio, then centrifuge at 12000 rpm.', [('Volume basis','MeOAc : prepurified suspension = 1 : 1.'),('Outcome','Retained white-pinkish precipitate had structural/optical properties similar to the first isolation.'),('Unreported','Absolute volumes, duration and exact physical sample identity.')],contents='Prepurified NCs + MeOAc',outcome='Retain precipitate')
scene('leave-crude','Unisolated control · air exposure','store','Leave unisolated NCs in ODE in air for the stated one-hour observation. Figure S1d shows the degraded, darkened material.', [('Control scope','Unisolated material; this is not the storage protocol for purified dispersions.'),('Unreported','Numerical temperature and full product composition.')],contents='Unisolated NCs in ODE',atmosphere='Air exposure')
scene('xrd-deposit','XRD preparation · separate films','deposit','Drop-cast the dispersions onto precleaned microscopy cover glasses. Similar thickness was used for comparison, without a numerical thickness.', [('Substrate','Microscopy cover glass; each source-labeled specimen remains separate.'),('Unreported','Deposition volume, film thickness and drying schedule.')],substrate='20 × 20 mm cover glass')
scene('xrd-acquire','XRD acquisition · powder-diffraction mode','xrd','Measure with the Malvern Panalytical Empyrean Alpha 1 using Cu Kα radiation and the reported scan settings.', [('Specimen','Drop-cast NC sample; ambient measurement conditions.'),('Time basis','17 s is acquisition time per scan step, not synthesis dwell time.'),('Evidence','Measured patterns remain the original figure assets.')])
scene('xrd-refine','Structure analysis · refinement and visualization','analysis','Use Malvern Panalytical HighScore for Rietveld refinement; the authors use VESTA to draw crystal structures.', [('Coordinate status','SI coordinate tables are retained. Their source discrepancies require separate model qualification before interactive atomic use.'),('Boundary','No website-generated exact nanocrystal or DFT input is implied.')],variant='HighScore refinement / VESTA')
scene('tem-deposit','TEM preparation · supported grid','grid','Adjust the hexane dispersion to absorbance 0.2 at 280 nm and drop 20 µL onto a carbon-coated copper grid.', [('Substrate','Carbon-coated Cu grid.'),('Unreported','Drying conditions and exact same-aliquot relation to optical/XRD specimens.')])
scene('tem-acquire','Electron microscopy · TEM and SAED','tem','Acquire TEM using the JEM-F200 microscope at 200 kV. Display source TEM and SAED panels with their reported specimen labels.', [('Evidence','Original microscopy and diffraction panels remain distinct from this schematic.'),('Unreported','Dose/exposure settings and an exact atomic reconstruction.')])
scene('optical-acquire','Optical characterization · absorption and emission','optical','Measure UV–vis absorption using Shimadzu UV-3600 and PL, absolute PLQY and TRPL using FLS1000 with its integrating sphere and microflash lamp.', [('Technique boundary','Absorption, PL, absolute QY and decay measurements remain separately labeled.'),('Unreported','Every specimen concentration and exact cross-assay aliquot identity.')])
scene('trpl-fit','Time-resolved PL · source decay analysis','analysis','Fit the optimized-sample decay data using the source model. Preserve the printed averaging expression and its documented disagreement with reported summary values.', [('Source conflict','Literal source equation, typed fit coefficients and author-reported lifetime remain separate.'),('Boundary','No recomputed value replaces a source number without an explicit derived-data label.')],variant='Reported decay fit / lifetime expression')
scene('ta-load','Transient absorption · dispersion cell','cuvette','Place a NC dispersion in the reported 2 mm quartz cuvette for transient-absorption measurements.', [('Specimen boundary','Dispersion specimens; exact links to film or TEM aliquots are unreported.'),('Unreported','NC concentration and cuvette fill volume.')])
scene('ta-acquire','Transient absorption · separate pump/probe series','pump-probe','Use the home-built TA spectrometer, laser excitation and heavy-water continuum probe. Figure 6 and Figure S6 have distinct acquisition settings.', [('Figure 6','150@NCs, 180@NCs//0.7 and 180@NCs//0.5: 300 nm excitation at 80 µW; plotted decays use 445 nm for cubic and 550 nm for rhombohedral samples.'),('Figure S6','180@NCs//0.7 only: separate 300, 370 and 420 nm excitations with the 600 nm probe.'),('Equipment','Libra F / Topas C excitation; ExciPro spectrometer with CCD.'),('Boundary','Heavy water generates the probe continuum; it is not the NC-dispersion solvent.')])
scene('ta-fit','Transient absorption · phase-specific kinetic fits','analysis','Fit the cubic decay with a biexponential and the rhombohedral decay with a triexponential source model.', [('Separate model scopes','Fit parameters retain their sample and probe assignments; they are not shared rate constants for all specimens.'),('Boundary','No new kinetic curve is synthesized from the diagram.')],variant='Cubic: 2 components / rhombohedral: 3')
scene('icp-dissolve','ICP-MS preparation · destructive digestion','digest','Dissolve purified NC precipitate in concentrated nitric acid.', [('State change','Digestion is destructive; the solution is not an intact nanocrystal specimen.'),('Unreported','Acid volume, NC mass, digestion temperature and duration.')])
scene('icp-dilute','ICP-MS preparation · acid matrix','dilute','Dilute the digest into the source 2% HNO3 matrix using ultrapure water.', [('Concentration basis','The source does not state the denominator of 2%; no mass/volume conversion is made.'),('Unreported','Final digest volume and dilution factor.')])
scene('icp-calibrate-measure','ICP-MS acquisition · separate standards','icp','Prepare separate Cs and Mn ionic calibration standards in 2% HNO3 and measure using Thermo Scientific iCAP RQ.', [('Standard/sample distinction','Calibration standards are separate from digested NC specimens.'),('Boundary','Measured Mn/Cs ratios are not identical to precursor loading labels.')])
scene('ltpl-deposit','Low-temperature PL · silica-supported specimen','deposit','Deposit NCs on silica for low-temperature PL. The analyzed PL series is assigned to 180@NCs//0.5.', [('Specimen','Deposited specimen, distinct from a hexane-dispersion measurement.'),('Unreported','Film thickness, deposition volume and drying conditions.')],substrate='Silica substrate')
scene('ltpl-acquire','Low-temperature PL · cryostat sequence','cryostat','Cool the supported sample to 30 K, then measure during warming over the reported range using 380 nm excitation.', [('Equipment','CTI CCS-150 cryostat; pE-4000 CoolLED.'),('Temperature schedule','The stated 20 K increments and 293 K endpoint are retained literally; intermediate points are not invented.'),('Unreported','Equilibration duration and warming rate.')])
scene('ltpl-fit','Low-temperature PL · thermal-quenching fit','analysis','Fit the source thermal-quenching expression over its stated 100–300 K fit interval.', [('Separate intervals','The fitting interval is not the complete 30–293 K measurement interval.'),('Source conflict','Reported fit values and uncertainty remain as printed.')],variant='Thermal-quenching fit')
scene('age-specimens','Stability study · films and dispersions','aging','Store the separately identified films and dispersions in the dark under the stated ambient conditions.', [('Specimen boundary','Film XRD and dispersion PL are different contexts, not one merged sample.'),('Unreported','Exact exposure histories, every loading label and all physical cross-assay links.')])
scene('stability-measure','Stability study · source-specific observations','age-measure','Follow the reported structural, optical and microscopy aging observations with their own sample/time assignments.', [('Rhombohedral film','Structural stability observed for three months.'),('Cubic film','Nine-week structural observation; reported transformed components stay separate.'),('Dispersion / aged microscopy','One week, 20 days and 55 days are source observation contexts, not a common synthesis schedule.'),('Boundary','No interpolation of missing aging points.')])
scene('dft-calculate','Computational analysis · magnetic and electronic structure','analysis','Select magnetic states and calculate primitive-cell electronic structures using HSE06 and the zero-order regular approximation.', [('Separate models','Cubic Pm-3m: Γ-centered 6×6×6 k mesh, G-type antiferromagnetic state. Rhombohedral R-3m: Γ-centered 3×3×3 mesh.'),('Source linkage','Authors discuss measured structures and cite prior structures. Exact calculation inputs and outputs were not supplied.'),('Boundary','SI refinement coordinates are not automatically validated DFT inputs or a nanocrystal atomic model.')],variant='HSE06 / scalar-relativistic ZORA')
scene('lsc-deposit','Luminescent concentrator · glass-supported film','deposit','Deposit an unencapsulated NC film on a glass plate for the proof-of-concept concentrator.', [('Scope','Film device specimen; exact NC loading ratio and film thickness are not supplied.'),('Unreported','Deposition volume, preparation method and drying schedule.')],substrate='Glass plate / unencapsulated film')
scene('lsc-assemble','Luminescent concentrator · edge-coupled detector','lsc','Place the edge of the coated glass on a silicon pn-junction photodiode, cover the surrounding diode area and place it in a dark box.', [('Geometry','Reported window edge and photodiode dimensions are shown as quantities; full plate dimensions are not inferred.'),('Optical boundary','Opaque cover suppresses direct illumination of surrounding diode area.')])
scene('lsc-measure','Luminescent concentrator · photocurrent controls','lsc-light','Illuminate the middle of the glass perpendicular to its surface with the source warm-white-like beam and measure the bias-dependent photocurrent.', [('Separate controls','NC-coated illuminated, bare-glass illuminated and dark conditions retain separate identities.'),('Boundary','No synthetic current curve or conversion efficiency is inferred.')])
scene('lsc-age-remeasure','Luminescent concentrator · same-film reassessment','lsc-age','Remeasure the source device film after 11 weeks in air.', [('Identity','The paper explicitly describes the same film for this reassessment.'),('Boundary','This device aging interval is separate from dispersion PL and film-XRD stability series.')])
bindings=[]
for r in records:
    for i,o in enumerate(r['operations']):
        c=cfg[o['id']]; c.update(record_id=r['record_id'],operation_pointer=f'/operations/{i}')
        c['option_pointers']=[f'/condition_options/{j}' for j in range(len(r.get('condition_options',[])))] if c.get('include_options') else []
        bindings.append(dict(record_id=r['record_id'],record_path=str(C/(r['record_id']+'.json')),record_sha256=sha(C/(r['record_id']+'.json')),operation_id=o['id'],operation_pointer=c['operation_pointer'],inputs=o['inputs'],outputs=o['outputs'],retained_fraction=o['retained_fraction'],source_evidence=o['evidence'],canonical_description=o['description'],human_prose=c['prose'],art=c['art'],option_pointers=c['option_pointers']))
assert len(bindings)==len(cfg)==39
labels={k:k.replace('_',' ').capitalize() for r in records for o in r['operations'] for k in o['parameters']}
labels.update({'cs2co3_mass':'Cs2CO3 charge','dry_oa_charge':'Dry OA charge','dry_ode_charge':'Dry ODE charge','dry_olam_charge':'Dry OlAm charge','ode_charge':'ODE charge','mncl2_mass':'Anhydrous MnCl2 charge','reported_loading_Mn_Cs':'Reported Mn/Cs loading label','cs_oleate_aliquot':'Cs-oleate aliquot','injection_temperature':'Injection temperature','hno3_matrix_concentration':'Printed HNO3 matrix concentration','ionic_standard_concentration_interval':'Separate ionic-standard concentration range','screened_hartree_fock_fraction':'Screened Hartree–Fock fraction','hold_after_injection':'Hold at selected injection temperature','time_per_step':'XRD acquisition time per step'})
data=dict(source_group='matuhina2023',configs=cfg,parameter_labels=labels)
save('scene-config.json',data); save('records.json',records)
save('canonical-bindings.json',dict(author='/root',status='private_draft',record_manifest_sha256=sha(C/'record-manifest.json'),source_freeze_sha256=sha(P/'package-freeze.json'),bindings=bindings))
template=A/'protocol-template.mjs'
if template.exists(): (A/'matuhina2023-protocol.mjs').write_text(template.read_text('utf-8').replace('__CONFIG__',json.dumps(data,ensure_ascii=False,separators=(',',':'))),'utf-8')
shutil.copyfile(ROOT/'recipe-atlas/dist/quantity-value.mjs',A/'quantity-value.mjs')
print(json.dumps(dict(records=len(records),operations=len(bindings),parameters=sum(len(o['parameters']) for r in records for o in r['operations']))))
