"""Independent audit of the supplied Dabbousi 1997 main article, not a Site importer."""
from pathlib import Path
from datetime import datetime, timezone
import json, hashlib
B=Path(__file__).resolve().parent
PDF=Path(r'[local path redacted]')
SID='dabbousi1997'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def E(p,loc):return {'source_id':SID,'pdf_page':p,'printed_page':9462+p,'locator':loc}
def I(id,text,p,loc,claim='reported_experiment',**kw):
 return dict(id=id,text=text,claim_type=claim,evidence=[E(p,loc)],**kw)
def plus(item,p,loc):item['evidence'].append(E(p,loc));return item

chem=[]
for id,name,formula,role,note in [
 ('topo','Trioctylphosphine oxide','C24H51OP','coordinating solvent and surface ligand','90% pure, Strem; shell vessel charge 5 g.'),
 ('top','Trioctylphosphine','C24H51P','solvent and ligand','95% pure, Fluka; distinguish TOPSe stock solvent, 0.5 mL vessel addition and 2–4 mL shell-feed solvent.'),
 ('cdme2','Dimethylcadmium','C2H6Cd','Cd precursor','Alfa; filtered separately through 0.2 µm filter in inert-atmosphere box. Filter material not specified. Used for CdSe cores and CdS shell comparison.'),
 ('znet2','Diethylzinc','C4H10Zn','Zn precursor','Fluka; separately filtered through 0.2 µm filter in inert-atmosphere box. Do not import Danek PTFE or supplier.'),
 ('selenium','Selenium shot','Se','TOPSe stock precursor','0.1 mol in 100 mL TOP; selenium supplier and purity not stated here.'),
 ('topse','Trioctylphosphine selenide','C24H51PSe','CdSe core precursor stock','Author states 1 M stock, made from selenium shot and TOP. No stock reaction time/temperature or final measured volume reported.'),
 ('tms2s','Hexamethyldisilathiane / bis(trimethylsilyl)sulfide','C6H18SSi2','S precursor','(TMS)2S from Aldrich used as purchased. This is sulfide, not the selenium precursor used in other articles.'),
 ('nhexane','n-Hexane','C6H14','dispersion solvent','HPLC grade, EM Sciences. Also used with butanol to store CdS-overcoated dots.'),
 ('methanol','Methanol','CH4O','precipitation antisolvent','HPLC grade, EM Sciences.'),
 ('pyridine','Pyridine','C5H5N','ligand-exchange and specimen solvent','HPLC grade, EM Sciences; XPS shows residual phosphorus even after pyridine exchange.'),
 ('butanol','1-Butanol','C4H10O','storage-fluid additive','HPLC grade, EM Sciences. Prevents TOPO solidification; source does not assign Danek alcoholysis rationale.'),
 ('chloroform','Chloroform','CHCl3','possible redispersion solvent','Listed among solvents compatible with isolated overcoated particles; no charge or purity stated.'),
 ('toluene','Toluene','C7H8','redispersion and PVB specimen solvent','1 mL nanocrystal dispersion and 0.5 mL PVB solution; no supplier stated.'),
 ('thf','Tetrahydrofuran','C4H8O','redispersion and MTD300P20 specimen solvent','Used for both dots and functional polymer in the alternate SAXS specimen.'),
 ('octane','Octane','C8H18','TEM specimen solvent','Source says octane without an explicitly named isomer or grade.'),
 ('nitrogen','Nitrogen','N2','ZnS overgrowth atmosphere','Reaction-flask atmosphere; purity, flow and pressure not stated.'),
 ('pvb','Poly(vinyl butyral)',None,'SAXS matrix polymer','10 wt% in toluene; no molecular weight or grade stated.'),
 ('mtd300p20','Phosphine-functionalized diblock copolymer MTD300P20',None,'alternative SAXS matrix','[methyltetracyclododecene]300-[norbornene-CH2O(CH2)5P(oct)2]20; preparation belongs to reference23.'),
 ('silicon','Silicon','Si','WDS/XPS/SAXS/WAXS substrate','WDS explicitly Si(100); do not transfer this orientation to every other Si support.'),
 ('carbon','Amorphous carbon','C','WDS/TEM specimen coating and TEM grid support','Prevents charging or beam damage; not a chemically grown nanocrystal shell.'),
 ('copper','Copper','Cu','TEM grid and X-ray anode','TEM grid support; Cu Kα radiation for scattering instruments.'),
 ('magnesium','Magnesium','Mg','XPS anode','Mg Kα used; Al anode capability listed but not selected.'),
 ('aluminum','Aluminum','Al','XPS available anode','Instrument dual Mg/Al capability; actual reported acquisition uses Mg.'),
 ('rhodamine590','Rhodamine590',None,'fluorescence standard','Either rhodamine590 or rhodamine640 at matched excitation optical density; exact salt, standard quantum yield, solvent and concentrations not reported.'),
 ('rhodamine640','Rhodamine640',None,'fluorescence standard','Alternative dye reference; not assigned to an individual plotted sample.')]:
 chem.append(I(id,name+': '+note,2,'Experimental Section: Materials and characterization',formula=formula,role=role))

procedures=[
 I('precursor_filtration','Separately filter dimethylcadmium and diethylzinc through 0.2 µm filters in an inert-atmosphere box. Filter membrane material, gas, amount, filtration pressure and temperature are unstated.',2,'Materials',quantities={'filter_pore_um':0.2}),
 I('topse_stock','Dissolve 0.1 mol selenium shot in 100 mL TOP; authors call this a 1 M TOPSe stock. Do not infer a measured final volume or synthesis time/temperature.',2,'Materials',quantities={'selenium_mol':0.1,'top_mL':100,'author_stock_mol_L':1}),
 I('cdse_core_growth','CdMe2 and TOPSe pyrolysis in TOPO follows reference3 but restates injection at 340–360 °C and growth at 290–300 °C from initially 23 Å diameter dots. Selected final cores span 23–55 Å. Core precursor charges, injection volume/rate, growth times and detailed atmosphere are not repeated.',2,'Synthesis of Composite Quantum Dots: (CdSe)ZnS',quantities={'injection_temperature_C':[340,360],'growth_temperature_C':[290,300],'initial_diameter_A':23,'selected_diameter_A':[23,55]}),
 I('core_fractionation','Collect CdSe cores as powders by size-selective precipitation with methanol, then redisperse in hexane. Detailed selection procedure is cited to reference3; volumes, cycles and thresholds not restated.',2,'Synthesis: core preparation'),
 I('shell_vessel_preparation','Heat 5 g TOPO to 190 °C under vacuum for several hours, cool to 60 °C, then add 0.5 mL TOP. Vacuum pressure, ramp rates, exact duration and flask geometry are not supplied.',2,'Synthesis: (CdSe)ZnS',quantities={'topo_g':5,'vacuum_temperature_C':190,'duration_raw':'several hours','cool_to_C':60,'top_mL':0.5}),
 I('seed_loading','Transfer approximately 0.1–0.4 µmol CdSe DOTS in hexane by syringe and pump off solvent. These are moles of nanocrystal particles, not CdSe formula units. Hexane volume, removal pressure/time and temperature are not stated.',2,'Synthesis: (CdSe)ZnS',quantities={'particle_amount_umol':[0.1,0.4],'amount_basis':'CdSe dots, not CdSe formula units'}),
 I('target_shell_dose_model','Estimate average core radius using TEM or SAXS, then calculate the ZnS/CdSe dose for a chosen shell from spherical shell/core volume ratio and bulk lattice parameters. Larger cores require smaller Zn/Cd for the same thickness. Actual deposited ZnS is generally less than added material because of incomplete reaction and flask-wall losses. This prescription is not a measured conversion, exact precursor charge or direct final composition.',2,'Synthesis: target precursor amount','author_model'),
 I('zn_s_feed','Mix equimolar ZnEt2 and (TMS)2S in 2–4 mL TOP in an inert-atmosphere glovebox. Load a syringe and transfer to an addition funnel attached to the vessel. Absolute precursor amounts, feed concentration and residual delivered fraction are unspecified; do not assign the 0.1–0.4 µmol particle amount to either precursor.',2,'Synthesis: (CdSe)ZnS',quantities={'Zn_to_S_precursor_molar_ratio':1,'top_solvent_mL':[2,4]}),
 plus(I('zns_overgrowth','Heat the CdSe/TOPO/TOP dispersion under N2; add precursors dropwise to vigorous stirring over 5–10 min at the temperature selected for core size. Temperatures are size-dependent, not a free 140–220 °C recipe interval. Stirring rate, pressure and continuous numerical flow are not stated.',2,'Synthesis: (CdSe)ZnS',quantities={'addition_duration_min':[5,10],'general_temperature_C':[140,220]}),13,'Reference/experimental note22'),
 I('temperature_size_map','Experimental note22 provides the actual size-to-overgrowth-temperature map: 23 Å→140 °C;30 Å→140 °C;35 Å→160 °C;40 Å→180 °C;48 Å→200 °C;55 Å→220 °C. The 40 Å label here is not silently changed to the 42 Å optical/SAXS label.',13,'Reference/experimental note22',quantities={'rows':[{'core_diameter_A':d,'overgrowth_temperature_C':t} for d,t in [(23,140),(30,140),(35,160),(40,180),(48,200),(55,220)]]}),
 I('postgrowth_hold','After addition, cool to 90 °C and stir for several hours. This is a separate post-addition hold; no exact time or ramp/cooling rate is given.',2,'Synthesis: (CdSe)ZnS',quantities={'temperature_C':90,'duration_raw':'several hours'}),
 I('zns_storage','Add a 5 mL aliquot of butanol to prevent TOPO solidifying on cooling to room temperature. Store in the growth solution to preserve TOPO surface passivation. A numerical storage temperature, gas atmosphere and duration are not specified.',2,'Synthesis: (CdSe)ZnS',quantities={'butanol_mL':5}),
 plus(I('zns_isolation','Later recover powders by methanol precipitation and redisperse in hexane, chloroform, toluene, THF or pyridine. Results additionally describes final size-selective precipitation as assurance against separate ZnS particles; it does not establish complete elimination or enumerate cycles.',2,'Synthesis: (CdSe)ZnS'),3,'Results III.A final purification'),
 I('cds_overgrowth','CdSe cores of 33.5–35 Å diameter are overcoated with CdS using the same basic procedure, with Me2Cd and (TMS)2S as shell precursors. Add at 180 °C and approximately 1 mL/min. The solution darkens and the immediate absorption shifts markedly red. Shared-framework quantities should retain their inherited provenance rather than be advertised as a fully restated independent run.',2,'Synthesis: (CdSe)CdS',quantities={'core_diameter_A':[33.5,35],'temperature_C':180,'feed_mL_min':1}),
 I('cds_storage','For CdS-overcoated dots add equal amounts of hexane and butanol because butanol alone appears to flocculate the particles. Equality is reported without explicit volume/mass basis or absolute amounts; do not invent 5 mL each.',2,'Synthesis: (CdSe)CdS'),
 I('wds_specimen','Cast approximately 1 µm thick films of dots from concentrated pyridine onto Si(100), completely evaporate solvent, then add a thin amorphous-carbon coating against charging. Concentration, casting volume and carbon thickness are not reported.',2,'Wavelength Dispersive X-ray Spectroscopy',quantities={'dot_film_thickness_um':1}),
 I('xps_specimen','Exchange all XPS samples with pyridine and spin-cast onto Si to make films several monolayers thick. This is specimen-film thickness, not ZnS shell coverage. Spin rate, solvent volume and ligand-exchange recipe are unspecified; residual P is detected.',2,'X-ray Photoelectron Spectroscopy'),
 I('tem_specimen','Place one drop of dilute octane dispersion on a Cu grid supporting amorphous carbon, wait 30 s, wick off solvent, then evaporate another amorphous-carbon layer. Concentration, drop volume and carbon thickness are unspecified.',2,'Transmission Electron Microscopy',quantities={'contact_s':30}),
 plus(I('saxs_pvb_specimen','Disperse approximately 5 mg nanocrystals in 1 mL toluene; add 0.5 mL of 10 wt% PVB in toluene; concentrate under vacuum to a viscous solution and cast on Si. Film approximately 200 µm thick, clear to slightly opaque. Particle mass basis and final polymer ratio/volume are not established.',2,'SAXS in Polymer Films',quantities={'nanocrystals_mg':5,'dispersion_mL':1,'polymer_solution_mL':0.5,'PVB_wt_percent':10,'film_thickness_um':200}),3,'SAXS in Polymer Films continuation'),
 plus(I('saxs_mtd_specimen','Use the same polymer-film preparation with phosphine-functionalized MTD300P20, with THF replacing toluene for both particles and polymer. Distinguish this alternate matrix from PVB; polymer synthesis is reference23.',2,'SAXS in Polymer Films'),3,'SAXS in Polymer Films continuation'),
 I('solution_saxs_specimen','Fill quartz capillaries with the desired dispersion, approximately 1 mm optical path, and flame-seal. Measure reference intensity first, then sample; analyze Is−Iref. Figure11 specimens are dilute hexane at comparable particle concentration, with no numerical concentration provided.',3,'SAXS in Dilute Solutions',quantities={'optical_path_mm':1}),
 I('waxs_specimen','Precipitate TOPO/TOP-capped dots with methanol, exchange with pyridine, and drop a highly concentrated pyridine dispersion onto Si. Slow solvent evaporation produces glassy films for diffraction. Amounts, exchange cycles and evaporation conditions are not given.',3,'WAXS'),
 I('xps_air_exposure','Use air exposure as an oxidation/passivation probe, not a synthesis step. Initial handling exposes samples for typically approximately 15 min; bare-dot follow-up values are reported after16 h and80 h, and shell-coated comparisons after prolonged exposure including80 h.',5,'XPS Results',quantities={'initial_handling_min':15,'followup_h':[16,80]}),
 I('split_core_coverage_series','Prepare a large batch of approximately40 Å diameter CdSe, split into fractions and add varying Zn/S amounts at identical temperatures and addition times. This gives the main shell-coverage series. Exact per-fraction seed amount and precursor doses are not given; common batch origin does not make all separate measurement aliquots identical physical specimens.',4,'Optical Characterization: coverage series')
]

methods=[
 I('uvvis','HP8452 diode-array absorption spectrometer; dilute dots in hexane in1 cm quartz cuvettes. UV/vis tracks core/shell spectral changes; do not derive raw spectra from pictures.',2,'Optical Characterization',quantities={'cuvette_path_cm':1}),
 I('pl','SPEX Fluorolog-2 in front-face mode. Room-temperature yield from integrated sample emission against rhodamine590 or640 at identical optical density at excitation. Dye-specific reference yield, solvent, detector correction details and excitation wavelengths for every spectrum are not given.',2,'Optical Characterization'),
 I('wds','JEOL SEM733 electron microprobe at15 kV. Elemental-composition uncertainty is reported as less than ±5%; this is a method statement, not an independently assigned error bar on each table value.',2,'WDS',quantities={'accelerating_voltage_kV':15,'reported_relative_uncertainty_percent_bound':5}),
 I('xps','Physical Electronics5200C with dual Mg/Al anodes and concentric hemispherical analyzer. Actual Mg Kα1253.6 eV acquisition:300 W,15 keV,20 mA; survey0–1100 eV with pass energy179 eV/resolution2 eV; close scans71.5 eV/resolution1 eV; base pressure10^-8 Torr. Instrument capability Al is not a second measured acquisition.',2,'XPS',quantities={'photon_eV':1253.6,'anode_W':300,'source_energy_keV':15,'current_mA':20,'survey_range_eV':[0,1100],'survey_pass_eV':179,'survey_resolution_eV':2,'close_pass_eV':71.5,'close_resolution_eV':1,'base_pressure_Torr':1e-8}),
 I('tem','Topcon EM002B at200 kV with objective aperture selecting (100),(002),(101) wurtzite planes. Analyze more than150 crystallites per sample for longest-axis size; aspect ratios use a subset. Histogram widths are distribution spreads, not uncertainty in a mean.',2,'TEM',quantities={'accelerating_voltage_kV':200,'number_per_size_sample':{'qualifier':'greater_than','value':150}}),
 I('saxs_polymer','Rigaku300 Rotaflex in Bragg geometry with Cu Kα,60 kV,300 mA; scatter and diffraction slits1/6° and collection slit0.3 mm. Subtract polymer background and correct beam overspill for sample width generally2 cm. Low-angle data below approximately2.5° are unreliable from aggregation; do not treat the correction as a new synthesis operation.',3,'SAXS polymer acquisition',quantities={'kV':60,'mA':300,'scatter_slit_deg':1/6,'diffraction_slit_deg':1/6,'collection_slit_mm':0.3,'typical_sample_width_cm':2,'excluded_low_angle_deg':2.5}),
 I('saxs_solution','Rotating Cu anode40 kV/25 mA; apparent source area~10^-2 mm²; beam3×0.3 mm² at PSPE(ELPHYSE) detector; useful detector length50 mm; stated D370 mm has a self-referential detector-distance wording; spatial resolution200 µm. q range6×10^-3–0.40 Å^-1, resolution~3×10^-3 Å^-1. Do not invent the other endpoint of D.',3,'SAXS in Dilute Solutions',quantities={'kV':40,'mA':25,'source_area_mm2':0.01,'beam_mm':[3,0.3],'detector_length_mm':50,'D_mm_reported':370,'detector_resolution_um':200,'q_range_A_inverse':[0.006,0.40],'q_resolution_A_inverse':0.003}),
 I('waxs','Same setup as polymer SAXS; Cu Kα glassy particle films. WAXS simulation uses the Debye approach with stacking faults, thermal fluctuations, aspect ratio and distributions; simulated atomic coordinates are models, not experimentally solved crystal structures.',3,'WAXS')
]
plus(methods[2],5,'WDS Results: uncertainty');plus(methods[4],6,'TEM statistics');plus(methods[4],7,'Figure9 caption');plus(methods[5],7,'SAXS polymer analysis');plus(methods[7],10,'WAXS simulation')

cohorts=[
 I('size_series_F1_F2','Bare and 1–2 monolayer ZnS-overcoated size series: a23 Å,b42 Å,c48 Å,d55 Å core diameters. Figure2 shell-coated room-temperature PL yields40%,50%,35%,30%, respectively. Bare dots mean organic TOPO/TOP caps. Exact layer coverage and complete shell recipe for each size are not enumerated.',3,'Figures1 and2',quantities={'rows':[{'label':a,'core_diameter_A':d,'coated_PL_yield_percent':y} for a,d,y in [('a',23,40),('b',42,50),('c',48,35),('d',55,30)]]}),
 I('photograph_F3','Six hexane dispersions in matching quartz cuvettes illuminated with365 nm UV. Left-to-right PL peaks470,480,520,560,594,620 nm. These six specimens are not mapped by the paper to all four Figure1/2 specimens. Supplied reproduction is grayscale, despite color-photo caption.',4,'Figure3 and discussion',quantities={'excitation_nm':365,'PL_peak_nm':[470,480,520,560,594,620]}),
 I('main_coverage_series','Main split-core series: approximately40 Å body,42 Å±10% optical/SAXS labels; TEM bare major diameter39 Å±8.2%. Coverage labels0,.65,1.3,2.6,5.3 monolayers derive from TEM major-axis growth. Use method-specific size fields rather than choosing one as universally exact. Figures4,5,8,9,10,13 and Table1 describe this coverage progression.',4,'Figures4/5 and body',quantities={'coverage_monolayers':[0,0.65,1.3,2.6,5.3]}),
 I('xps_cohorts','XPS examines multiple approximately33 and40 Å core samples with variable shells. Figure6 explicitly compares approximately40 Å bare with approximately1.3 monolayers; Figure7 compares bare,.65,1.3,2.6 monolayers. Do not automatically assign each XPS result to an identical physical TEM/optical aliquot.',5,'XPS Results and Figure6'),
 I('oxidized_bare_xps','Bare-dot air-exposure series: initial Se/Cd~.87 (46%Se/54%Cd);16 h Se/Cd.77 (43/57) and SeO2 peak13% total Se;80 h Se/Cd.37 (28/72),SeO2 peak22%. Different numbers are whole measured signals, not shell stoichiometry or direct synthesis yield.',6,'XPS air-exposure Results',quantities={'rows':[{'time_h':0,'Se_Cd':0.87,'Se_percent':46,'Cd_percent':54,'SeO2_signal_percent':None},{'time_h':16,'Se_Cd':0.77,'Se_percent':43,'Cd_percent':57,'SeO2_signal_percent':13},{'time_h':80,'Se_Cd':0.37,'Se_percent':28,'Cd_percent':72,'SeO2_signal_percent':22}],'time_zero_basis':'initial baseline, not a reported precisely zero-air-exposure specimen'}),
 I('solution_saxs_F11_F12','Independent dilute-hexane SAXS cohort explicitly has different Zn/Cd ratios than Table1 and must not be merged with it. Bare caption42 Å; coated ratios.42,.85,3.1; highest ratio5.3 in Figure11/p9 versus5.6 in p8. Bare fitted R0≈19.50 Å,σ≈.12 in text; Figure12captionσ=.11,.14,.16,.25 for a–d. Higher-coverage fits are described as unreliable, so quoted captionσ does not certify reliable mean sizes.',8,'Figures11/12 discussion',quantities={'ratio_labels':[0,0.42,0.85,3.1],'highest_ratio_reports':[5.3,5.6],'bare_fitted_radius_A':19.50,'bare_sigma_body':0.12,'sigma_caption_a_to_d':[0.11,0.14,0.16,0.25]}),
 I('theory_F14','Figure14 is calculated radial probability and band-offset diagrams, not measured atomic or carrier-density data. Body says20 Å core radius, caption20 Å diameter; shells4 Å ZnS orCdS. Preserve source conflict and do not train an exact geometry label from it.',11,'Figure14 and body','author_model',quantities={'core_size_number_A':20,'core_size_definition_conflict':['radius','diameter'],'shell_A':4}),
 I('zns_shift_F15','Approximately20 Å radius CdSe cores overcoated with ZnS: measured absorption and PL energy shifts versus shell thickness with model curves. PL excitation450 nm. Largest body-reported absorption redshift~36 meV at16 Å ZnS. Figure15 is not a tabulated raw-data series; do not invent intermediate point coordinates.',11,'Figure15 and discussion',quantities={'core_radius_A':20,'PL_excitation_nm':450,'largest_shell_A':16,'absorption_shift_magnitude_meV':36}),
 I('cds_shift_F16','CdS overcoating comparison has inconsistent core-size wording: experimental33.5–35 Å diameter;p11~30 Å radius;Figure16caption andp12~16 Å radius. Body reports~210 meV shift for15 Å CdS on~16 Å radius core. Error bars inFigure16 represent TEM size distribution, not energy uncertainty. Plot model curves and the source-label conflict remain separate.',12,'Figure16 and discussion',quantities={'body_shell_A':15,'body_core_radius_A':16,'shift_magnitude_meV':210})
]
plus(cohorts[2],5,'Table1 and Figure5');plus(cohorts[3],6,'Figure7');plus(cohorts[4],5,'XPS initial composition');plus(cohorts[5],9,'Figure12 caption and fitted-radius discussion');plus(cohorts[7],12,'Discussion continuation');plus(cohorts[8],2,'(CdSe)CdS experimental method');plus(cohorts[8],11,'Figure16 discussion')

rows=[]
for coverage,tem,spread,aspect,saxs,sp,wd,sr,wr in [(0,39,8.2,1.12,42,10,None,None,None),(.65,43,11,1.16,46,13,.46,.58,.7),(1.3,47,10,1.16,50,18,1.50,1.32,1.4),(2.6,55,13,1.23,None,None,3.60,None,2.9),(5.3,72,19,1.23,None,None,6.80,None,6.8)]:
 rows.append(dict(TEM_derived_coverage_monolayers=coverage,TEM_major_axis_A=tem,TEM_relative_size_spread_percent=spread,TEM_average_aspect_ratio=aspect,SAXS_polymer_fitted_size_A=saxs,SAXS_polymer_fitted_spread_percent=sp,WDS_measured_Zn_Cd=wd,SAXS_polymer_calculated_Zn_Cd=sr,WAXS_calculated_Zn_Cd=wr))
tables=[I('table1','All table cells visually checked. Empty cells are null (not zero). TEM sizes are longest-axis means; ±percent entries describe size distributions. SAXS and WAXS columns are calculated/fitted results distinct from WDS measured compositions. Coverage is TEM-derived, not precursor dose.',5,'Table1','mixed_reported_and_author_derived',rows=rows)]

observations=[
 I('scope_performance','Study-level core diameters23–55 Å, room-temperature PL30–50%, linewidth fwhm≤40 nm and emission spanning approximately470–625 nm. These are summary ranges, not labels applying identically to every specimen.',1,'Abstract and Introduction',quantities={'diameter_A':[23,55],'PL_yield_percent':[30,50],'fwhm_nm':{'qualifier':'less_than_or_equal','value':40},'emission_span_nm':[470,625]}),
 I('bare_surface','Bare dots throughout the paper remain TOPO/TOP capped; core/shell dots also retain organic caps after ZnS growth. Pyridine exchange is a later specimen or dispersion preparation.',3,'III.A Synthesis'),
 I('temperature_tradeoff','Excessive overgrowth temperature causes core Ostwald ripening and broader distributions; too low can leave precursor decomposition incomplete or reduce shell crystallinity. Temperature is optimized independently for each core size.',3,'III.A Synthesis','author_interpretation'),
 I('slow_feed','Low concentration and slow addition favor growth on seeds over separate ZnS nucleation, but authors explicitly do not claim to eliminate separate small ZnS particles. Final size selection offers further assurance.',3,'III.A Synthesis','author_interpretation'),
 I('monolayer_definition','One ZnS monolayer is3.1 Å, distance between consecutive planes along bulk-wurtzite [002], measured along the prolate-particle major axis. TEM-derived coverage is not a direct assertion of uniform isotropic shell thickness.',3,'III.B Optical Characterization',quantities={'monolayer_major_axis_thickness_A':3.1}),
 I('size_series_spectra','Coating broadens and redshifts absorption; smaller cores show stronger shift, interpreted as exciton leakage into ZnS. Bare PL yields generally5–15% become30–50%; deep-trap emission of small bare cores is suppressed, producing stronger band-edge emission.',4,'Optical Characterization','author_interpretation',quantities={'bare_PL_percent':[5,15],'coated_PL_percent':[30,50]}),
 I('coverage_spectra','The main shell series uses equal area under the lowest absorption feature as constant oscillator strength. Increasing shell shifts absorption/PL red, broadens the distributions and increases ultraviolet absorption into ZnS. These are spectral normalization and interpretation, not constant synthesis concentration measurements.',4,'Figure4 discussion','author_interpretation'),
 I('coverage_PL_maximum','For the main series, yield begins15% bare, approaches50% near1.3 monolayers, then falls to30% at approximately5 monolayers. Intermediate inset points are plotted but not numerically tabulated; do not pretend exact point extraction.',5,'Figure5 and discussion',quantities={'bare_yield_percent':15,'maximum_yield_percent':50,'maximum_coverage_ML':1.3,'high_coverage_yield_percent':30,'high_coverage_ML_approx':5}),
 I('wds_cd_rich','WDS consistently measures Se/Cd approximately0.8–0.9/1 for bare dots, interpreted as Cd-rich nanoparticles. This is distinct from each Zn/Cd shell ratio.',5,'WDS Results',quantities={'Se_Cd':[0.8,0.9]}),
 I('xps_contamination_ligands','XPS C/O signals are attributed mainly to approximately15 min air exposure and have adsorbate-like energies, suggesting no significant charging. Residual P remains after pyridine exchange, indicating bound TOP/TOPO; do not import Danek below-detection P result.',5,'XPS Results','author_interpretation'),
 I('xps_sensitivity_correction','Relative Cd/Se peak areas are divided by sensitivity factors and corrected for finite-particle escape-depth attenuation, integrating exp(-z/λ) over a sphere. InitialSe/Cd~.87 (46%Se/54%Cd) agrees with WDS. The correction is a model, not an extra precursor quantity.',5,'XPS Results','author_model'),
 I('auger_parameters','Cd Auger parameter for bare and coated dots466.8±.2 eV agrees with bulkCdSe; Zn parameter757.5 eV for1.3/2.6 monolayer samples is compared with expected758.0 eV. Reference758.0 is not a second sample measurement.',6,'XPS Results',quantities={'Cd_parameter_eV':466.8,'Cd_uncertainty_eV':0.2,'Zn_parameter_eV':757.5,'Zn_bulk_comparison_eV':758.0}),
 I('oxidation_coverage','SeO2 peak at59 eV appears after80 h for bare and.65ML specimens. At estimated~1.3ML or more oxide is absent on prolonged air exposure; another sentence says >1.3ML Se/Cd unchanged after80 h. This supports possibly continuous passivation, not exact coverage of every site.',6,'XPS Results','author_interpretation',quantities={'oxide_binding_energy_eV':59,'exposure_h':80,'threshold_ML_approx':1.3}),
 I('oxidation_surface_account','For~40 Å dots the estimated surface-atom fraction34% is used to infer that much surface Se has desorbed after80 h. No Cd–O peak is seen, but bare Cd Auger parameter changes466.8→467.5 eV;1.3/2.6ML coated values remain unchanged. Surface fraction is calculated context, not a measured yield.',6,'XPS Results','mixed_reported_and_author_derived',quantities={'estimated_surface_atoms_percent':34,'bare_Cd_parameter_before_eV':466.8,'bare_Cd_parameter_after80h_eV':467.5}),
 I('xps_auger_attenuation','Normalized XPS-to-Auger Cd intensity ratio increases for a shell because Cd Auger electrons have shorter escape depths. Reported calculated normalized ratios1.28 and1.60 for.65 and2.6ML support surface-localized ZnS; they are not Zn/Cd composition ratios.',6,'Equation1 discussion','author_derived',quantities={'rows':[{'coverage_ML':.65,'normalized_XPS_Auger_ratio':1.28},{'coverage_ML':2.6,'normalized_XPS_Auger_ratio':1.60}]}),
 I('escape_depths','Experimental note26 supplies electron escape depths used in XPS analysis; these are analytical constants, not measured shell thicknesses.',13,'Reference/note26','methodological_reference',quantities={'escape_depth_A':{'CdSe':{'Cd3d':15,'CdAuger':10,'Se3d':21},'ZnS':{'Cd3d':23.7,'CdAuger':13.2,'Se3d':31.2,'Zn2p':9.6,'ZnAuger':26.8,'S2p':28.9}}}),
 I('tem_structure','Lattice fringes extend through a2.6ML particle and suggest epitaxy, but no resolved core/shell interface is observed. Unusual bending in Figure8B may indicate strain; most fringes are straight. At high coverage some patchy growth/misshapen particles occur, without observed tethered separate ZnS nuclei.',6,'TEM Results','author_interpretation'),
 I('saxs_polymer_trend','Increasing shell shifts SAXS ringing to smaller angles; low coverage0–1.3ML retains structure. Above~2.5ML structure is sparse;2.6/5.3ML main-series curves cannot be fitted confidently. Other >3ML samples also give structureless curves.',7,'SAXS in Polymer Films','author_interpretation'),
 I('polymer_saxs_model','Use discrete Debye scattering from wurtzite atoms retained inside ellipsoidal core/shell outlines. Dimensions and aspect distributions come from TEM; hold core size/distribution/aspect fixed while fitting shell size/spread. A shape distribution barely changes curves but substantially improves predicted Zn/Cd agreement with WDS.',7,'Equation2 and polymer SAXS model','author_model'),
 I('shape_weight_example','Illustrative20 Å radius particle/aspect1.2 curve is similar to weighted20 Å radius curves with aspect1.1/1.2/1.3/1.4 at24/36/24/16%. This is an explanatory model example, not four independent synthesized populations with measured fractions.',7,'SAXS model example','author_model',quantities={'radius_A':20,'aspect_ratios':[1.1,1.2,1.3,1.4],'weights_percent':[24,36,24,16]}),
 I('polymer_aggregation','Shoulder below2θ~2° indicates aggregation, attributed to poor ZnS/TOPO passivation and irreversible flocculation during repeated size selection. MTD300P20 is only slightly better than PVB; preparing films under inert atmosphere does not improve separation. Below~2.5° unsuitable for fitting but ringing position/size estimate is less affected.',7,'Polymer SAXS aggregation discussion','author_interpretation'),
 I('solution_saxs_analysis','Analyze background-subtracted intensity with Guinier/Porod plots and log-normal or Gaussian radius distributions. Comparable low particle concentrations isolate form-factor effects. I(0) scales approximatelyN R^6; nonlinearity at high coverage is attributed to polydispersity, although attractive interactions could also produce it.',8,'Solution SAXS analysis','author_model'),
 I('solution_saxs_upper_bounds','Bare R0≈19.50 Å and σ≈.12 are fitted away from origin. High-coverage data lack reliable average-size/variance fits; instead authors derive upper-distribution radii from the sixth root of intensity ratios and restricted low-q extrapolation. No numerical table of those upper radii is given.',9,'Solution SAXS fitting','author_derived'),
 I('density_model_error','Assuming one core/shell electron density neglects CdSe~2.92 versusZnS~2.35 e/Å³ and incurs estimated10–15% size error. This is a systematic model assumption, not each TEM measurement uncertainty.',9,'Solution SAXS density approximation','author_model',quantities={'CdSe_e_A3':2.92,'ZnS_e_A3':2.35,'estimated_size_error_percent':[10,15]}),
 I('waxs_features','Bare broad feature combines(100),(002),(101); reduced(102)/(103) is assigned to [002] stacking faults. Coating shifts/broadens the first feature~26°, decreases(102)~36°, changes peaks~47°, and at high coverage adds~56° peak. These are approximate plot angles; Figure13axis2θ differs from the text simulation interval labelledθ.',10,'WAXS Results','author_interpretation',quantities={'approx_peak_angles_deg':[26,36,47,56]}),
 I('waxs_core_model','Bare WAXS model: average1.4 stacking faults/crystallite, prolate~1200-atom core, aspect1.1. Later model paragraph says CdSe aspect1.15. These are model settings, not measured atom counts or a unified exact aspect ratio; fixed core settings carry into shell simulations.',10,'WAXS model','author_model',quantities={'core_stacking_faults':1.4,'core_atoms_approx':1200,'core_aspect_reports':[1.1,1.15]}),
 I('waxs_lattice_model','At2.6/5.3ML, reasonable fits require bulk lattice parameters aCdSe4.29 Å,aZnS3.82 Å; small-coverage ZnS parameter weakly affects fit. ZnS first-feature scattering area estimated~3-fold weaker than CdSe; heavy coverage is needed to resolve shell structure. These bulk-valued fit choices are not a deposited-CIF refinement.',10,'WAXS model','author_model',quantities={'a_CdSe_A':4.29,'a_ZnS_A':3.82,'first_feature_CdSe_ZnS_area_ratio_approx':3}),
 I('waxs_shell_model','Shell aspect distribution weighted1.2–1.4 from TEM, biased toward large values at high coverage. Highest coverage best fit uses3 shell stacking faults/crystallite. Other shells contribute too little for reliable fault inference. ModelZn/Cd=.7,1.4,2.9,6.8 as inTable1.',10,'WAXS model','author_model',quantities={'shell_aspect_range':[1.2,1.4],'highest_shell_faults':3,'model_Zn_Cd':[.7,1.4,2.9,6.8]}),
 I('waxs_interface_limit','Rotating shell(100) to core(101) does not significantly improve the highest-coverage fit. Including or omitting cross-material pair terms(Cd–S,Zn–Se,S–Se,Cd–Zn) modifies scattering less than changing composition, aspect or fault density. Interface orientation/atomic positions are not uniquely solved.',10,'WAXS interface sensitivity','author_model'),
 I('electronic_model','Noninteracting charge carriers in a spherical core/concentric shell without interfacial alloying, with Coulomb attraction as first-order perturbation. ZnS electron/hole barriers.9 eV each; organic electron/hole barriers4/10 eV are fitted phenomenological parameters, explicitly not literal band-offset measurements.',10,'IV.A Electronic structure','author_model',quantities={'ZnS_electron_barrier_eV':.9,'ZnS_hole_barrier_eV':.9,'organic_electron_barrier_eV':4,'organic_hole_barrier_eV':10}),
 I('cds_barriers','CdS model electron barrier.2 eV permits greater delocalization; hole barrier.55 eV permits more penetration than ZnS but less than electron. These are model parameters/context, not measured synthesis activation barriers.',11,'Electronic structure discussion','author_model',quantities={'CdS_electron_barrier_eV':.2,'CdS_hole_barrier_eV':.55}),
 I('model_wavefunction_trend','Bare light-electron wavefunction spans the core, heavier hole is central; ZnS mainly lets electron leak outward, lowering confinement until saturation. CdS allows substantially more electron leakage and hence larger absorption redshifts. Figure14 is a schematic calculated model.',11,'Figure14 discussion','author_model'),
 I('pl_shift_weighting','PL shifts exceed absorption shifts increasingly at high coverage; authors attribute much of it to broadening and preferential excitation of larger dots. Figure15 excitation450 nm is described as~100 nm blue of first absorption. Note38 converts absorption linewidth to an effective bare-dot distribution and weights by effective radius cubed(volume).',11,'Figure15 discussion','author_model'),
 I('same_material_counterfactual','ObservedZnS16 Å shell/~20 Å radius core gives~36 meV shift; hypothetical CdSe shell of same thickness/core would yield~290 meV. ObservedCdS15 Å/~16 Å core gives~210 meV; hypotheticalCdSe15 Å would yield~390 meV. The CdSe-shell values are counterfactual model comparisons, not extra shell-synthesis recipes.',12,'Discussion first paragraph','mixed_reported_and_author_model',quantities={'observed_ZnS_shift_meV':36,'hypothetical_CdSe16A_shift_meV':290,'observed_CdS_shift_meV':210,'hypothetical_CdSe15A_shift_meV':390}),
 I('passivation_PL_link','The maximum~50% yield near1.3ML coincides with first tested coverage lacking Se oxide after80h, suggesting most vacancy/nonradiative sites are passivated. This is a cohort correlation, not proof all surfaces or samples share an exact universal optimum.',12,'IV.B shell and yield','author_interpretation'),
 I('thick_shell_decline','Higher coverage favors [002] elongation, nonuniform morphology and irreversible flocculation; inferred weak ligand binding and modeled stacking faults may create nonradiative sites and lower PL yield. Defect mechanism remains inferred rather than atomically localized.',12,'IV.B shell and yield','author_interpretation'),
 I('growth_mechanism_options','Data are interpreted as local/coherent epitaxy at low coverage and epitaxial but incoherent growth above~2ML. TEM cannot resolve lattice-spacing difference or out-of-plane defects, while WAXS is orientation-insensitive. Two proposed mechanisms are coherent growth relaxing via dislocations/grain boundaries, or coherent islands coalescing with grain boundaries.',12,'IV.B growth mechanism','author_interpretation'),
 I('mismatch_comparison','CdSe/ZnS mismatch~12% is used to motivate strain relaxation. The cited CdSe/ZnSe quantum-well comparison has7% mismatch and diminished PL above4 CdSe monolayers; those values describe reference40, not the current nanocrystal critical thickness.',12,'Growth-mechanism comparison','citation_context',quantities={'current_pair_mismatch_percent':12,'cited_quantum_well_mismatch_percent':7,'cited_quantum_well_CdSe_threshold_ML':4})
]
plus(observations[32],13,'Reference/model note38')

figdefs=[
 (1,3,'Absorption, four core sizes','size_series_F1_F2','Bare dashed and1–2ML shell solid;23/42/48/55Å. Retain axes/legend; no raw-data digitization.'),
 (2,3,'Photoluminescence, four core sizes','size_series_F1_F2','Same nominal size series;coated yields40/50/35/30%;retain small-size ×10 annotation.'),
 (3,4,'Luminescence photograph','photograph_F3','Six spectra-linked cuvettes;left-to-right470/480/520/560/594/620nm. Supplied PDF is grayscale; do not recolor as original data.'),
 (4,4,'Absorption versus shell coverage','main_coverage_series','Two wavelength windows with distinct axes and molar-absorptivity scales;0/.65/1.3/2.6/5.3ML;42±10%Å core.'),
 (5,5,'PL and quantum-yield inset','main_coverage_series','Main intensity plus right quantum-yield axis and inset;relative toRhodamine590 label. Line in inset only eye guide.'),
 (6,5,'XPS survey and low-binding-energy enlargement','xps_cohorts','A/B panels;bare vs~1.3ML. Keep photoelectron/Auger transition labels and atmosphericC/O context.'),
 (7,6,'Se3d oxidation/passivation spectra','xps_cohorts','Bare/.65/1.3/2.6ML,59eVSeO2;air-exposure interpretation from body.'),
 (8,6,'High-resolution TEM','main_coverage_series','A one bare dot;B one2.6ML dot;50Å scale bar. No resolved core/shell boundary.'),
 (9,7,'Major-axis and aspect histograms','main_coverage_series','Five coveragesA/B panels;major diameterÅ;>150 particles forsize,subsetforaspect.'),
 (10,8,'SAXS in polymer','main_coverage_series','Experimental circles and fitted lines only reliable forbare/.65/1.3ML;logintensity,2θ.'),
 (11,8,'SAXS dilute hexane','solution_saxs_F11_F12','Independentratio cohort;caption highest5.3 conflicts body5.6;I_s−I_ref;corecaption42Å.'),
 (12,9,'Guinier/Porod plots with inset','solution_saxs_F11_F12','Bothpanels+inset;captionσa–d.11/.14/.16/.25;preservebodyfitlimitations.'),
 (13,9,'WAXS and ellipsoidal model','main_coverage_series','Experimentalcircles/models;wurtziteCdSe/ZnS line referenceinsets are bulk context, not a rawsample CIF.'),
 (14,11,'Calculated radial probabilities and band diagrams','theory_F14','Puretheory;core20Åradius/diameterconflict;4ÅZnS/CdS;organicmatrix distinctfromshell.'),
 (15,11,'Measured and modeled ZnS energy shifts','zns_shift_F15','Absorptioncircles,PLsquares;modelsolid/dashed;~20Åradius;no exactplotpointtable.'),
 (16,12,'Measured and modeled CdS energy shifts','cds_shift_F16','Experimentalpoints/TEMshell-sizedistributionerrorbars;corecaption~16Åradius vsbody~30;captionbarriermatrixconflict.')]
figures=[I('figure'+str(n),desc,p,'Figure'+str(n),'original_figure_inventory',title=title,sample_scope=scope,all_panels_required=True) for n,p,title,scope,desc in figdefs]
equations=[
 I('eq1','I=J0 N(z)i σi Yi,n F(KE) exp[-z/λ(KE)] describes depth-dependent XPS/Auger intensity. Subsequent same-atom ratios cancel flux, population and absorption cross section.',6,'Equation1','author_model'),
 I('eq2','Discrete Debye form I(q)=I0[f²(q)/q] sum_k[ρ(rk)/rk sin(q rk)], with q=4πsinθ/λ. Applied to generated wurtzite ellipsoids for SAXS and WAXS. Preserve source mathematical notation; not a DFT result.',7,'Equation2','author_model'),
 I('eq3','Zero-angle contrast integral I(0)=integral_0^infinity4πr²Δρ_tilde²(r)dr=N(v<Δρ>)² approximatelyNR^6. Used with comparable particle concentrations; density differences and polydispersity limit inferred sizes.',8,'Equation3','author_model'),
 I('eq4','Radial-wavefunction continuity at the core/shell radius: R1S,CdSe(k1r1)=R1S,ZnS(kappa2r1).',10,'Equation4','author_model'),
 I('eq5','Continuity of inverse-effective-mass-weighted radial derivative at r1. This probability-current boundary condition uses bulk effective masses without listing their numerical values.',11,'Equation5','author_model'),
 I('unnumbered_guinier','Printed Guinier expression uses I(q,N)≈I(0,N)exp(-q²RG²/5), describing RG as Guinier radius for spheres. Preserve the printed factor/definition rather than silently replacing by another convention.',8,'Solution SAXS Guinier expression','author_model'),
 I('unnumbered_radius_ratio','R≈R0m[Inm(0)/I0m(0)]^(1/6) yields effective/upper radii from zero-angle intensities; high-coverage values are upper-distribution estimates, not means.',9,'Solution SAXS extrapolation','author_model'),
 I('unnumbered_xps_ratio','Normalize the Cd photoelectron/Auger intensity ratio of a coated specimen by that of bareCdSe; this ratio is not elemental Zn/Cd stoichiometry.',6,'After Equation1','author_model'),
 I('unnumbered_escape_correction','Finite-size XPS sensitivity uses an integral of exp(-z/λ), evaluated over spherical nanocrystal geometry; not an independently measured shape proof.',5,'XPS sensitivity correction','author_model')]

conflicts=[
 I('c_core40_42_39','Main-series approximate40Å body,42Å±10% optical/SAXS and39Å±8.2%TEM describe method-specific size estimates; preserve their definitions and errors. Note22 specifies40Å→180°C, not42Å.',5,'Table1 and Figure5','ambiguity',resolution='Do not replace source sizes with a single averaged/exact size.'),
 I('c_saxs5p3_5p6','Highest independent solution-SAXS Zn/Cd ratio is5.3 inFigure11caption andp9 but5.6 in p8Guinier discussion.',8,'Figure11 caption and body','source_conflict',resolution='Keep both reports, exclude exact-ratio conditioning pending resolution.'),
 I('c_sigma','Bare solution-SAXS σ≈.12 in p9body versus.11 inFigure12caption.',9,'Figure12 and following text','source_conflict',resolution='Keep source-labelled fit values, do not silently choose.'),
 I('c_high_saxs_fit','Figure12caption givesσ=.25 for d while text says high-coverage data cannot yield meaningful average/variance fits. These may be illustrative rather than reliable fits.',9,'Figure12 and fitting discussion','source_tension',resolution='Preserve caption value only as model context with reliability limitation.'),
 I('c_F14_core','Figure14caption says20Ådiameter while body says~20Åradius; plotted core boundary around20Å fromcenter aligns with radius interpretation but is not authority to erase caption.',11,'Figure14 and body','source_conflict',resolution='Keep model geometry conflict explicit; no exactstructure training label.'),
 I('c_CdS_core','Experimental CdS cores33.5–35Ådiameter;p11Fig16discussion~30Åradius;Fig16caption/p12body~16Åradius. Different-sample possibility is not resolved.',11,'Figure16 discussion','source_conflict',resolution='Do not merge exact core-size labels across these passages.'),
 I('c_F16_barrier','Figure16caption calls4eV/10eV the barriers into surrounding CdS matrix; electronic-model body assigns4/10eV to organic matrix, andCdS barriers.2/.55eV.',12,'Figure16 caption','source_conflict',resolution='Retain caption conflict and distinguish actual model-region parameters.'),
 I('c_detector_distance','Experimental SAXS says detector placed atD370mm from the detector. This is self-referential wording.',3,'SAXS in Dilute Solutions','source_ambiguity',resolution='Report D370mm with endpoints unresolved; do not manufacture sample-distance definition.'),
 I('c_theta','WAXS text simulation interval15°<θ<60° while Figure13axis is2θ; the plotted feature positions use26/36/47/56°.',10,'WAXS simulation;Figure13 onp9','notation_ambiguity',resolution='Preserve stated angle labels; do not convert all values without resolving convention.'),
 I('c_model_aspect','WAXS bare-core model aspect1.1 early paragraph versus1.15 later;Table1TEMmean1.12. These are model descriptions and a distinct measured mean.',10,'WAXS model','source_ambiguity',resolution='Do not equate or average the three values.'),
 I('c_photo_color','Figure3caption calls color photograph, but supplied PDF visibly provides grayscale cuvettes.',4,'Figure3','source_asset_limitation',resolution='Use original grayscale; retain textual wavelength/color explanation without invented source colors.'),
 I('c_nominal_actual','Geometric precursor target, actualWDSZn/Cd, TEM-derivedshellcoverage, SAXS-fitcomposition andWAXS-fitcomposition are different quantities; incorporation is lower than precursoraddition.',2,'Synthesis and Table1','semantic_hazard',resolution='Keep separate dose/measurement/model fields.'),
 I('c_cds_storage_equal','Equal amounts hexane/butanol forCdSstorage lacks unit basis or absolute quantities.',2,'(CdSe)CdS method','missingness',resolution='Do not infer5mL each or a measured 1:1 volume ratio.'),
 I('c_monolayer_geometry','Shell monolayer is3.1Å along majoraxis while precursor-dose model assumes sphericalgeometry; realhighcoverage particles areprolate/nonuniform.',3,'Monolayerdefinition;Synthesisp2','semantic_hazard',resolution='Do not generate an experimentally validated uniform concentricatomic shell.'),
 I('c_oxidation_threshold','Oxide absence stated~1.3MLormore, unchangedSe/Cdratio statedmorethan1.3ML, and1.3/2.6MLAuger parametersunchanged.',6,'XPS oxidation discussion','source_wording_limit',resolution='Preserve individual observation thresholds; no universal exact protective threshold.'),
 I('c_model_counterfactual','Hypothetical16/15ÅCdSe shells with290/390meVshifts are counterfactual modelcomparisons, not extraexperimentallysynthesizedmaterial records.',12,'Discussion first paragraph','semantic_hazard',resolution='Reader/modelcontext only.'),
 I('c_prior_film_devices','Introduction~10%ES-OMCVDfilmPL and cathodoluminescence refer toreference21;LEDproposals reference20 manuscripts. They are not synthesis/measurements performed and fully specified inthisarticle.',1,'Introduction','citation_scope',resolution='Referencecontextonly, no inventedfilmrecipe.')]
plus(conflicts[1],9,'Solution SAXS body');plus(conflicts[5],2,'CdS synthesis');plus(conflicts[5],12,'Figure16caption and body');plus(conflicts[6],10,'Electronicmodelorganicbarriers');plus(conflicts[6],11,'CdSbarriers');plus(conflicts[13],2,'Dosemodel')

refdata=[
 (1,'Brus1991;Alivisatos1996;Weller1993;Bawendi etal.1990 reviews','Quantum confinement background.'),
 (2,'Bawendi etal.,J.Chem.Phys.1989,91,7282','Bulk-like nanocrystal lattice/structural and WAXS modeling background.'),
 (3,'Murray,Norris,Bawendi,JACS1993,115,8706','CdSe core synthesis and size selection;Debye/stacking-fault structural methods. Current article restates only selected details.'),
 (4,'Chemsiddine,Weller,Ber.Bunsen-Ges.Phys.Chem.1993,97,636','Prior monodisperse nanocrystal preparation.'),
 (5,'Micic etal.,J.Phys.Chem.1995,99,7754','Prior monodisperse nanocrystal preparation.'),
 (6,'Ekimov etal.,J.Opt.Soc.Am.B1993,10,100','Electronic-state spectroscopy.'),
 (7,'Alivisatos etal.,J.Chem.Phys.1988,89,3435','Electronic-state spectroscopy.'),
 (8,'Nirmal,Murray,Bawendi,Phys.Rev.B1994,50,2293','Electronic-state spectroscopy.'),
 (9,'Chamarro etal.,Jpn.J.Appl.Phys.1995,Suppl34-1,12','Electronic-state spectroscopy.'),
 (10,'Efros etal.,Phys.Rev.B1996,54,4843','Electronic-state spectroscopy.'),
 (11,'Norris,Bawendi,Phys.Rev.B1996,53,16338','Electronic-state spectroscopy.'),
 (12,'Tian etal.,J.Chem.Phys.1996,100,8927 as printed','PriorCdSe/CdScore-shell structures; bibliography wording retained.'),
 (13,'Youn,Baral,Fendler,J.Phys.Chem.1988,92,6320','PriorZnS/CdS and effective-mass context.'),
 (14,'Kortan etal.,JACS1990,112,1327','PriorZnS/CdSe and inverse structures;XPS/Auger attenuation comparison.'),
 (15,'Mews etal.,J.Phys.Chem.1994,98,934','CdS/HgS/CdSquantumwells.'),
 (16,'Danek,Jensen,Murray,Bawendi,Chem.Mater.1996,8,173','PriorCdSe/ZnSe route motivating two-step current method; do not inherit its reagentpurity,quenchrationale orPtFEfilter.'),
 (17,'Littau etal.,J.Phys.Chem.1993,97,1224','PriorSi/SiO2core-shellcontext.'),
 (18,'Wilson,Szajowski,Brus,Science1993,262,1242','PriorSi/SiO2opticalcontext.'),
 (19,'Hines,Guyot-Sionnest,J.Phys.Chem.1996,100,468','PriorCdSe/ZnS50%yield andmethodbasis.'),
 (20,'Dabbousi etal.;Mattoussi etal.,manuscriptsinpreparation','ProspectiveLEDstructures, not currentverifieddevicefabrication.'),
 (21,'Rodriguez-Viejo etal.,Appl.Phys.Lett.1997,70,2132','CitedZnS-matrixES-OMCVDfilms:~10%PL,>2ordersimprovement,cathodoluminescence; distinctsource.'),
 (22,'Experimental note: size-dependent overcoating temperatures','Currentpaperexperimentaldata, fully inventoried in temperature_size_map.'),
 (23,'Fogg etal.,Macromolecules1997,30,417','Phosphinefunctional diblockpolymer identity/preparation/passivation.'),
 (24,'Moulder etal.,HandbookofX-rayPhotoelectronSpectroscopy,Perkin-Elmer1993','XPScalibration,sensitivity,Augerparameters.'),
 (25,'Kuno etal.,J.Chem.Phys.1997,105,9869 as printed','Ligandbinding/residualP andStokesshiftbackground; bibliographic yearnotexternallyverified.'),
 (26,'Methodnote: electronescape depths','Currentanalyticalconstantvalues retained in escape_depths.'),
 (27,'Bowen-Katari,Colvin,Alivisatos,J.Phys.Chem.1994,98,4109','Seleniumoxide formation in air.'),
 (28,'Hoener etal.,J.Phys.Chem.1992,96,3812','XPS/Auger shell-location methodology.'),
 (29,'Guinier,Founet,SmallAngleScatteringofX-rays,Wiley1955 as printed','SAXStheory; bibliography spelling preserved.'),
 (30,'Kratky,Glatter,SmallAngleX-rayScattering,Academic1982','SAXStheory.'),
 (31,'Klug,Alexander,X-rayDiffractionProcedures,Wiley1954','Beam-footprint correction.'),
 (32,'Murray,MITPhDthesis1996','PolymerSAXS andDebyeanalysiscontext.'),
 (33,'Kagan etal.,Phys.Rev.Lett.1996,76,1517','Aggregation signature in nanocrystal films.'),
 (34,'Mattoussi etal.,J.Chem.Phys.1996,105,9890','SolutionSAXS andpossibleinterparticleeffects.'),
 (35,'Haus etal.,Phys.Rev.B1993,47,1359','Effective-masscore-shellmodel.'),
 (36,'Schooss etal.,Phys.Rev.B1994,49,49','Effective-masscore-shellmodel.'),
 (37,'Nethercot,Phys.Rev.Lett.1974,33,1088','Band-offsetmodelbackground.'),
 (38,'Modelnote: linewidth-derived effective distribution and a³ weighting','CurrentpaperPLmodelprocedure, not a separatepaper or experiment.'),
 (39,'Aven,Prener,PhysicsandChemistryofII–VICompounds,1967,p144','Low stacking-fault formationenergycontext.'),
 (40,'Zajicek etal.,Appl.Phys.Lett.1993,62,717','CdSe/ZnSequantum-well7%mismatch and4MLcriticalthickness comparison;notcurrentdotthreshold.')]
refs=[I('ref'+str(n),bib+'. '+text,13,'References and Notes, '+str(n),'current_paper_note' if n in [22,26,38] else 'citation_context',reference_number=n,bibliographic_label=bib,external_source_read=False) for n,bib,text in refdata]

intuition=[
 I('intuition_temperature','Select the overgrowth temperature jointly with core size: retain the core distribution while enabling precursor decomposition and crystalline shells. The source map is empirical for this chemistry and cannot be generalized automatically.',3,'III.A and note22','author_intuition'),
 I('intuition_dose','Keep seeded growth favored through dilute, slow precursor addition; measure actual composition/coverage because incomplete conversion and wall losses break the equality between nominal dose and deposited shell.',2,'Synthesis dose discussion','author_intuition'),
 I('intuition_optimum','An inorganic shell passivates surface traps, but more shell is not monotonically better. Source evidence links~1.3ML to maximumPL and suppression ofSeoxidation, while thicker nonuniform/defective shells reduceyield.',12,'IV.B','author_intuition'),
 I('intuition_multimethod','UseTEMlong-axis statistics, WDScomposition, surfaceXPS, scattering fits andoptical spectra together; no one method resolves allgeometry,phase,composition andbatchidentity.',12,'IV.B','author_intuition'),
 I('intuition_shellchoice','ZnS provides stronger carrier confinement thanCdS in the simplifiedmodel;CdSallows moredelocalization andlargerredshift. These observations motivate chemicaldesign butare not a universal efficiency ranking acrossmaterials.',11,'IV.A','author_intuition'),
 I('intuition_ligands','Retain growthsolution to preserve organic caps, and treat purification as a possible stability-changing operation. Pyridineexchange neednotremove everyphosphorusligand; highcoverage ZnS dots mayirreversiblyflocculate.',2,'Storage andp5/p7discussion','author_intuition'),
 I('intuition_future','Mechanistic improvement would distinguish strain-relaxation dislocations from coalescing-shell-island boundaries and improve ligand stabilization. Bothgrowthscenarios remain sourceproposals; no undocumented optimizedrecipe is implied.',12,'Growthmechanisms','author_intuition')]

out={
 'audit_version':'1.0','audited_at_utc':datetime.now(timezone.utc).isoformat(),
 'status':'independent_supplied_main_text_and_visual_review_complete','review_scope':'supplied_main_only_si_unverified',
 'source':{'source_id':SID,'basename':PDF.name,'sha256':sha(PDF),'doi':'10.1021/jp971091y','title':'(CdSe)ZnS Core-Shell Quantum Dots: Synthesis and Characterization of a Size Series of Highly Luminescent Nanocrystallites','authors':['B. O. Dabbousi','J. Rodriguez-Viejo','F. V. Mikulec','J. R. Heine','H. Mattoussi','R. Ober','K. F. Jensen','M. G. Bawendi'],'journal':'Journal of Physical Chemistry B','year':1997,'volume':101,'issue':46,'pages':'9463–9475','received':'1997-03-27','final_form':'1997-06-26','advance_abstract':'1997-09-01','page_count':13},
 'scope_limit':'Independent source reading of all13 supplied pages with visual verification. No external cited papers read, SI matching, canonical-record audit, figure-crop certification, Site/queue writes, training or publication decision.',
 'supporting_information':{'status':'not_located_or_verified','note':'Identity/SI matching is handled separately by the parent team; this bounded audit inspected the supplied main only.'},
 'page_review':[{'pdf_page':p,'printed_page':9462+p,'text_reviewed':True,'visual_reviewed':True,'text_file':f'plain-page-{p}.txt','image_file':f'main-{p:02d}.png','text_sha256':sha(B/f'plain-page-{p}.txt'),'image_sha256':sha(B/f'main-{p:02d}.png')} for p in range(1,14)],
 'relevance':{'synthesis':True,'structure':True,'properties':True,'materials':['CdSe cores','CdSe/ZnS core-shell quantum dots','CdSe/CdS core-shell comparison'],'do_not_promote':['Reference-only ZnS-matrix films/devices','Hypothetical CdSe shells','Bulk/theoretical atomic models as measured structures']},
 'chemical_inventory':chem,'procedures_and_controls':procedures,'characterization_methods':methods,'sample_and_figure_joins':cohorts,'observations_and_author_interpretations':observations,'figures':figures,'tables':tables,'equations':equations,'conflicts_and_semantic_hazards':conflicts,'reference_contexts':refs,'source_specific_intuition':intuition,
 'missing_information':['MatchedSIunverified.','No complete per-run corecharges/times; no absolute shellprecursor charges/concentrations or incorporationyield.','0.1–0.4µmol is particleamount with exactrun assignmentsmissing.','No exactvacuumpressure,ramp,stirringrpm,flaskgeometry,precursorfiltermaterial orpurificationcycles.','No mapping fromeveryoptical/structuralfigure toonequantifiedrecipe orphysicalaliquot.','No exactCdSstorageamount/basis.','No complete rawdigitizedspectra/pointtables beyondTable1.','No refinedatomiccoordinates/measuredCIF oruniquelyresolvedcore-shellinterface.','No SAED,Raman,devicefabrication/electricaltesting asnewcompleteproceduresinthispaper.','Modelbarriers,escape-depthconstants,stackingfaultcounts andhypotheticalstructures are not directexperimentaltrainingtargets.'],
 'OCR_and_visual_checks':['Read all13 textpages andrenderedPNGs.','Verified Table1alignment andblankcells visually.','Checked≤40nmfwhm,±spreads,Å,µmolparticles andGreeknotation againstpageimages.','Figure8scale50Å;Figure9axisMajorDiameter corresponds longestdimension.','Figure3grayscale reproductioncannotdemonstrateoriginalhues.','Figure14captiondiameter/bodyradius andFigure16captionmatrixwordingarevisibleinthePDF.','Note22/26/38 are scientificcontent despite locationinreferences.','OCR quote approx maybe renderedhyphen inFigure16; negativephysicalradius isnotreported.'],
 'new_parameter_concepts':['Particle-number amount versus formula-unit amount','Core-size-conditionedovergrowthtemperature','Nominalgeometricdose versus incorporatedcomposition','Major-axis-derivedmonolayers versus uniformshellthickness','Method-specificsize/distributiondefinitions','Oxidationexposurestate and surfacechemicalcomposition','Specimen-specificligandexchange andcarboncoating','Polymer/solutionSAXScohorts andaggregationlimitations','Bulk-valuedscatteringfitparameters andsensitivity','Counterfactualelectronicmodelpredictions','Cross-source versus currentexperimentalnotes'],
 'administrative_exclusions':['Acknowledgment,funding,affiliations,downloadstamp,publishercopyright andsharingnotices are not synthesis/structure/property data.'],
 'coverage_note':'Inventory covers every scientific paragraph, all16 numberedfigures andpanels,Table1 withallcells,5 numbered plus4 unnumberedequationcontexts,and40 numberedreferences/notes. Items are grouped by scientificclaim; count does not imply separate experiments. Source-to-canonical and source-to-reader coverage must still be audited.'}
out['inventory_counts']={k:len(out[k]) for k in ['chemical_inventory','procedures_and_controls','characterization_methods','sample_and_figure_joins','observations_and_author_interpretations','figures','tables','equations','conflicts_and_semantic_hazards','reference_contexts','source_specific_intuition']}
ids=[x['id'] for k in out['inventory_counts'] for x in out[k]]
assert len(ids)==len(set(ids))
assert len(figures)==16 and len(refs)==40 and len(rows)==5
(B/'source-audit.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines=['# Independent source audit — Dabbousi et al. 1997','',out['source']['title'],'','DOI:10.1021/jp971091y. All13 main pages read in text and visually. SI unverified. No Site, training or publication certification.','',f"Source SHA-256: `{out['source']['sha256']}`.",'','## Inventory','']
for k,v in out['inventory_counts'].items():lines.append(f'- {k}: {v}')
lines+=['','## Source conflicts and semantic hazards','']
for x in conflicts:lines += [f"- **{x['id']}**: {x['text']} {x['resolution']}"]
lines+=['','## Synthesis and supporting procedures','']
for x in procedures:lines += [f"- **{x['id']}** (PDFp{x['evidence'][0]['pdf_page']}): {x['text']}"]
lines+=['','## Cohort boundaries','']
for x in cohorts:lines += [f"- **{x['id']}**: {x['text']}"]
lines+=['','All table cells, method settings, model parameters, observations, references and exact locators are in source-audit.json. Scientific source coverage is complete for the supplied main within this bounded audit; canonical and reader integration still require their own checks.']
(B/'source-audit.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps(out['inventory_counts'],indent=2))
