import json,hashlib
from pathlib import Path
root=Path(__file__).resolve().parent
out=root/'apparatus-review'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def dump(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
m=read(out/'manifest.json');render=read(out/'render-validation.json')
assert m['status']=='passed' and render['status']=='passed'
assert sha(root/'dabbousi-protocol.mjs')==m['moduleSha256']
contacts=sorted(out.glob('contact-*.png'));assert len(contacts)==10
m['visualReview']={'status':'passed','scope':'All 60 SVG scenes were inspected in ten contact sheets. After explicit Arial text styling and three collision corrections, all final contact sheets were reviewed; the final WDS cast-and-dry edit was separately inspected at full panel size. This is static SVG/render validation, not browser integration QA.',
 'assets':[{'file':p.name,'sha256':sha(p)} for p in contacts],
 'resolvedIssues':['Shell-stock vial and transfer text overlapped; separated horizontally.','Vacuum pressure label touched the vacuum line; moved away.','Solvent-removal label touched the horizontal vacuum line; moved below.','WDS film panel now explicitly depicts casting and drying, with the reported final 1 micrometer thickness.']}
m['sourceSemantics']={'sourceMainSha256':m['sourceSha256'],'primaryLocators':['Main PDF p. 2 / printed p. 9464: Materials; ZnS and CdS synthesis; optical, WDS, XPS and TEM methods; polymer-film preparation.','Main PDF p. 3 / printed p. 9465: polymer-film SAXS continuation, solution SAXS and WAXS methods.','Main PDF p. 13 / printed p. 9475: note 22, six paired seed-diameter and ZnS-overgrowth-temperature conditions.','Main PDF pp. 5–6 / printed pp. 9467–9468: separate air-exposure states.'],
 'preservedBoundaries':['ZnS uses an addition funnel, not a syringe pump. A syringe transfers the stock to the funnel.','ZnS heating/addition shows source-paired temperature, never an arbitrary chosen temperature or interpolation.','CdS has explicit 180 degC and approximately 1 mL/min; common steps are inherited from the stated same basic procedure.','1-butanol prevents TOPO solidification in ZnS storage; no quench. CdS needs equal amounts of hexane and butanol, with unspecified basis/absolute amounts.','TOPO vacuum conditioning and later seed-solvent removal are distinct. No numerical vacuum pressure or unreported heater is imposed.','The 1 M TOPSe stock is 0.1 mol Se in 100 mL TOP; this is not the unspecified injected seed charge.','Organometallic filtration does not assume PTFE, argon or the prior paper\u2019s precursor treatment.','WDS carbon coating method is unknown; TEM additional carbon evaporation is explicit.','PVB/toluene and MTD300P20/THF polymer procedures remain alternatives.','Solution SAXS and polymer-film SAXS have distinct specimens and operating voltages. The printed 370 mm referent remains unresolved.','The source explicitly names a concentric hemispherical XPS analyzer. Measured excitation is Mg K-alpha, not simultaneous Al.','Air-exposure groups are not a mandatory serial chain. No synthetic SAED, spectrum, crystal/interface or exact particle count is presented.'],
 'visualInference':'All containers, arrows, heating symbols, instrument blocks, particles and layer proportions are explanatory; none is a measured apparatus or atomistic reconstruction.'}
dump(out/'manifest.json',m)
audit={'status':'passed_static_source_and_render_review','module':'dabbousi-protocol.mjs','moduleSha256':m['moduleSha256'],'sourceDoi':m['sourceDoi'],'sourceSha256':m['sourceSha256'],
 'operationCount':len(m['files']),'actionTypeCount':len(set(x['action'] for x in m['files'])),'programmaticCheckCount':m['checkCount'],'textOutsideBounds':render['textOutsideBounds'],
 'visualReview':m['visualReview'],'sourceSemantics':m['sourceSemantics'],'remaining':['Root integration must retain operation evidence, inheritance, alternatives and quantity fields alongside the scene.','Root will perform browser QA after importing the module.','Molecular binding source-record hashes may need refresh after independently audited canonical revisions; material IDs and bindings are unchanged.'],
 'noSiteEdits':True,'noDownloads':True}
dump(root/'apparatus-audit.json',audit)
(root/'apparatus-audit.md').write_text('# Dabbousi apparatus asset audit\n\nPassed static source and render review: 60 operations, 35 action types. Exports are `buildDabbousiScene(o, r)` and `createDabbousiArt(o, r)`. The exact DOI and supported-action guards return null for other papers or unknown operations.\n\nAll ten contact sheets and the final WDS casting panel were inspected. Three label collisions were corrected. All final rendered text remains inside the SVG bounds. No synthetic spectra, diffraction patterns or atomic-interface geometry are included.\n\nThe source explicitly names a concentric hemispherical analyzer for XPS (main PDF p. 2). WDS casting is labeled as cast-and-dry, with the 1 micrometer thickness assigned to the final film. Source and state boundaries are enumerated in `apparatus-audit.json`.\n\nThis review does not replace root browser integration QA. Molecular source-record hashes can be refreshed after the final canonical promotion while retaining unchanged material bindings.\n',encoding='utf-8')
print(json.dumps({'moduleSha256':m['moduleSha256'],'checks':m['checkCount'],'scenes':len(m['files']),'manifestSha256':sha(out/'manifest.json')}))
