from pathlib import Path
from datetime import datetime, timezone
import json
B=Path(__file__).resolve().parent; MON=B.parent.parent
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
g=read(MON/'ledger.json')['groups']['10.1021_jp0208743']; m=read(B/'source-manifest.json');m['fingerprint']=g['fingerprint'];m['documents']=[{'filename':k,'sha256':v,'role_candidate':'main','page_count':5}for k,v in g['fingerprint']['files'].items()];write(B/'source-manifest.json',m)
write(B/'root-reading.json',{'status':'supplied_main_read','read_at':datetime.now(timezone.utc).isoformat(),'doi':'10.1021/jp0208743','title':'Anti-Stokes Photoluminescence in Nanocrystal Quantum Dots','authors':['Noelio Oliveira Dantas','Fanyao Qu','R. S. Silva','Paulo César Morais'],'year':2002,'journal':'Journal of Physical Chemistry B','volume':106,'pages':'7453–7457','main_pages_text_read':[1,2,3,4,5],'main_pages_visually_inspected':[1,2,3,4,5],'source_sha256':m['sha256'],'si_status':'Matching local SI not located or verified; no SI declaration observed in supplied main.','source_scope':'All five main pages, seven original figures and 21 references/notes; cited works not independently read.','critical_boundaries':['Six annealing conditions are two analytical cohorts; SG1–4 optical and AFM1–2 microscopy specimens are distinct.','PbO2 is printed as precursor; aluminum crucible at1400 C is retained as a source ambiguity, not silently corrected to alumina.','Sulfur reagent and all oxide proportions/doses are missing.','Model-derived optical size/radius ambiguity and AFM grain-height measures remain separate.','Figure6 exponent0.86 is SG1 only; intensity axis kW/cm2.','Proposed two-step/two-photon and resonant Raman interpretations are hypotheses, not measured electronic structures or independent Raman spectra.']})
ms={'read':{'status':'complete','evidence':[str(B/'root-reading.json'),str(B/'source-manifest.json')],'note':'All five supplied main pages text-read and visually inspected; incoming/legacy byte-identical. SI unverified.'},'extract':{'status':'partial','evidence':[str(B/'root-reading.json')],'note':'Independent canonical extraction, complete reader assets and source audit in progress within this paper.'},'audit':{'status':'pending','evidence':[],'note':'Source-to-canonical/reader/molecular/apparatus gates pending.'},'integrate':{'status':'pending','evidence':[],'note':'Private staging; no Dantas Site changes yet.'},'publish':{'status':'pending','evidence':[],'note':'Existing Site version23 remains current.'}}
write(B/'milestones.json',ms)
write(B/'checkpoint.json',{'paper':'10.1021/jp0208743','title':'Anti-Stokes Photoluminescence in Nanocrystal Quantum Dots','source_id':'dantas2002','source_generation':g['generation'],'review_scope':'supplied_main_only_si_unverified','main_pages_text_reviewed':[1,2,3,4,5],'main_pages_visually_reviewed':[1,2,3,4,5],'si_status':'Matching SI not located or verified; no SI declaration observed.','website_published':False,'checkpoint_at':datetime.now(timezone.utc).isoformat(),'current_work_items':[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in ms.items()],'next_action':'Complete source, canonical and reader extraction; build source-specific molecular/apparatus assets, independently audit, integrate, validate and publish this same paper.'})
print('Source identity and complete main reading saved; claim remains active.')
