"""Independent full-source inventory; local PDF evidence only, no Site mutation."""
import json,hashlib,datetime,re
from pathlib import Path
B=Path(__file__).parent
source=Path(r'[local path redacted]')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
U=[]
def add(id,page,loc,kind,text,disposition='retain_source_linked_evidence',**kw):
    U.append(dict(id=id,source_unit_id=id,source_role='main',pdf_page=page,printed_page=9432+page,locator=loc,kind=kind,claim=text,disposition=disposition,**kw))
add('identity',1,'Title, byline, journal banner and footer','identity','Nanocrystal Arrested Precipitation in Supercritical Carbon Dioxide. Parag S. Shah, Shabbir Husain, Keith P. Johnston and Brian A. Korgel. J. Phys. Chem. B 2001, 105, 9433–9440. DOI 10.1021/jp011815c is printed in the footer; issue 39 appears on subsequent pages.')
add('identity-dates',1,'Received line and publication footer','identity','Received May 11, 2001; published on the Web August 31, 2001. The July 7, 2026 institutional-download watermark is not a publication or experiment date.',disposition='retain_identity_and_administrative_distinction')
add('identity-affiliation',1,'Affiliation and correspondence footnote','administrative','Department of Chemical Engineering and Texas Materials Institute, Center for Nano- and Molecular Science and Technology, University of Texas at Austin; Johnston and Korgel are corresponding authors. Contact/download details are administrative, not experimental parameters.',disposition='administrative_context')
for n,t in enumerate([
'The abstract reports fluorocarbon-coated Ag, Ir and Pt nanocrystals with characteristic diameters 20–120 Å, produced from soluble organometallic precursors in a single CO2 phase. This is a study-wide size statement, not a sample-specific minimum/maximum or an Ir/Pt size measurement.',
'Hydrogen reduction is performed at elevated temperatures spanning 60–100 °C in the presence of perfluorooctanethiol. Species-specific numerical variants appear later; do not assign the whole range to each sample.',
'Authors describe precursor degradation, nucleation, ligand binding and growth arrest; CO2-solvated ligands provide a steric barrier to aggregation. This is the proposed mechanistic interpretation.',
'Particles redisperse in acetone and fluorinated solvents. This is distinct from the later explicit failure to redisperse washed C8-ligand particles in pure CO2.',
'The authors infer cluster agglomeration followed by ligand passivation, self-similar distributions and about ±47% relative standard deviation, with larger sizes at higher precursor loading. The tabulated individual standard deviations must remain separate from this summary.'
],1):add(f'abstract-{n:02}',1,'Abstract','study_summary',t)
for n,t in enumerate([
'Nanocrystals of roughly 20–100 Å are introduced as having size-dependent optical, catalytic, magnetic and electronic properties; applications are background context from references 1–3, not measured performance in this paper.',
'Arrested precipitation uses organic ligands to passivate growing surfaces and stabilize colloids. SCFs offer sufficient density for solvation with lower viscosity and higher diffusivity than conventional liquid solvents; reference 4.',
'Changing pressure/temperature changes SCF density and ligand-tail/solvent interactions. Theory, simulation, light and neutron scattering in references 5–12 motivate tunable steric stabilization and possible reversible stabilization, separation and self-assembly.',
'CO2 is described as nonflammable, essentially nontoxic and environmentally benign. The source prints critical temperature 31 °C and critical pressure 71 bar. Retain these as source-reported background, not new verified thermophysical constants or synthesis conditions.',
'Low CO2 polarizability and refractive index produce weak van der Waals solvent interactions, motivating CO2-philic fluorinated tails. Fluoroacrylates, alkanes and ethers are cited surfactant classes, not additional current reagents; references 13–19.',
'Earlier Ag and CdS synthesis in water-in-CO2 microemulsions (references 20/21) is distinguished from this single-phase method; particle recovery can cause irreversible aggregation when surfactant is not bound.',
'Reference 23 describes fluorinated-thiol particles prepared in acetone/water using a modification of Brust’s biphasic method and later dispersed in liquid/supercritical CO2. This is a separate earlier preparation, not the current sc-CO2 reaction.',
'The introduction claims this arrested-precipitation route as a first use in CO2. Retain as the authors’ historical claim, not a verified present-day novelty statement.',
'References 24–26 concern hydrogen reduction of organometallic precursors in CO2 to make thin metal films; film deposition is contextual prior work, not a nanoparticle recipe here.'
],1):add(f'context-{n:02}',1,'Introduction','cited_context',t,disposition='retain_context_without_new_recipe')
chem=[
('ag','Silver acetylacetonate, Ag(acac), from Aldrich Chemical Co.; soluble Ag precursor. Supplier is reported, purity is not. No synthesis of this purchased precursor is given.'),
('ir','(Methylcyclopentadienyl)(1,5-cyclooctadiene)iridium(I), from Strem Chemicals, Inc.; Ir precursor. No preparation, purification or purity is specified.'),
('pt','Platinum precursor is printed as dimethyl(1,5-cyclopentadiene)platinum(II), from Strem Chemicals, Inc., on both pages 2 and 4. Preserve the source name and unresolved identity; do not silently substitute cyclooctadiene or invent a molecular formula/geometry.'),
('ligand','Stabilizing ligand: 1H,1H,2H,2H-perfluorooctanethiol, C6F13C2H4SH, Oakwood Products Inc. This partially fluorinated C8 ligand is distinct from the C10 fluorinated comparison ligand.'),
('co2','CO2 purity >99.99%, Matheson Gas Products; used as received. Preserve the strict lower purity bound and distinguish reaction-side CO2 from piston-backside pressurizing CO2.'),
('h2','H2 purity >99.999%, Praxair, Inc.; used as received. It is the reducing reagent, not merely an inert atmosphere.'),
('acetone','Omnisolv spectrophotometry-grade acetone, EM Science, is used to collect particles from the cell and redisperse them for analysis. Collection/redispersion volumes are unreported.'),
('heptane','Heptane is the antisolvent used to precipitate nanocrystals. Unreacted precursor, unbound ligands and undesired byproducts remain in the supernatant; no heptane amount or separation hardware is specified.'),
('fluorinert','Fluorinert-brand electronic liquid is reported as a compatible fluorinated redispersion solvent; exact grade/composition and amount are not stated.'),
('freon','1,1,2-Trichlorotrifluoroethane (Freon) is also reported as a redispersion solvent. No grade or quantity is given.'),
('tem-grid','TEM specimen support is a 200-mesh carbon-coated copper grid. Grid carbon/copper must not be interpreted as an intentionally synthesized metal-core component.')]
for key,t in chem:add('chemical-'+key,2,'Experimental Section: Synthesis and Characterization','chemical_inventory',t)
steps=[
('cell','All reactions use a temperature-controlled stainless-steel high-pressure variable-volume view cell with a piston, front sapphire window and inside diameter 1.75 cm.'),
('load','A typical Ag experiment loads 5.9–16.0 mg Ag(acac) into a cell with working volume 27 mL, explicitly the volume with the piston in the cell. The range is not assigned to individual Table 1 rows.'),
('initial-co2','Seal the cell and fill with 14–18 mL CO2 at 138 bar and 20 °C. This is a charging stage, distinct from the later 276 bar reaction pressure and selected reaction temperature.'),
('pressurize','Pressurize the cell to 276 bar using CO2 on the backside of the piston and a Dionex model 501 Computer Controlled Syringe Pump. Backside fluid supplies pressure; do not count it as a known additional reacting-side solvent amount.'),
('heat','Heat to the selected reaction temperature using heating tape and an Omega CN76000 temperature controller. The precursor is reported not to decompose under these pre-reduction conditions. Heating rate and dwell time are not given.'),
('simultaneous-dose','Simultaneously introduce 162–324 mg fluorinated thiol and 6.22 mg hydrogen through a high-pressure injection pump and two Valco six-port rotary valves in series with sample loops. Do not turn these into sequential additions or infer dose duration.'),
('temperature-verification','Verify reaction temperature with a thermocouple inserted into the cell. This is a measured cell temperature, not solely a heater setting; exact thermocouple position/calibration is unspecified.'),
('constant-pressure','Hold pressure constant throughout the reaction; the typical synthesis pressure is 276 bar. No pressure-time trace or absolute/gauge convention is reported.'),
('reaction-duration','Continue reaction for 3 h to ensure completion. Visual darkness reaches its maximum after approximately 1 h; that observation is not the preparative reaction endpoint or a measured conversion.'),
('cool','After reaction, cool the cell to room temperature. Cooling rate and numerical room temperature are unspecified.'),
('depressurize','Depressurize the cooled cell; CO2 is then vented as vapor from the top, leaving most components other than H2 in the cell. No vent rate, residual gas fraction or recovery yield is supplied.'),
('collect','Collect nanocrystals from the cell with spectrophotometry-grade acetone; no collection volume or number of rinses is given.'),
('precipitate','Precipitate collected nanocrystals with heptane. Keep the particle fraction; excess/unreacted chemicals remain in the supernatant. No centrifugation speed, filtration medium or wash-cycle count is stated.'),
('redisperse','Redisperse nanocrystals in acetone for further analysis. Alternative compatibility with fluorinated solvents is reported separately, not as mandatory additional washing stages.'),
('variant-inheritance','The detailed method is described as a typical Ag experiment. The apparatus applies to all reactions, but Ir/Pt-specific concentrations, ligand ratios, temperature and pressure are separately reported. Shared-method inheritance must be marked; do not assign the Ag precursor-mass range or exact row-specific solvent amount to Ir/Pt.'),
('missing','No precursor-stock preparation, stock concentration separate from the reaction concentration, injection rate, stirring/mixing speed, gas partial pressure, actual per-run reaction volume, acetone/heptane amount, final isolated yield or storage conditions are reported.')]
for n,(key,t) in enumerate(steps,1):add('synthesis-'+key,2,'Experimental Section: Synthesis','operation_or_condition',t)
char=[
('tem-instrument','TEM/HRTEM uses a JEOL 2010 with 1.7 Å point-to-point resolution and 200 kV accelerating voltage; GATAN digital photography system.'),
('tem-deposition','Deposit nanocrystals on 200-mesh carbon-coated copper grids. Suspension concentration, deposition volume, drying conditions and a separate staining treatment are not specified.'),
('size-analysis','Particle sizes and distributions are obtained using Scion Image for Windows; at least 400 nanocrystals are measured for each sample. Preserve ≥400 as a lower bound, not exactly 400.'),
('eds-instrument','EDS is performed in situ on a JEOL 2010 TEM equipped with an Oxford Link ISIS EDS instrument. The EDS figure concerns Ag particles; no Ir/Pt EDS dataset is provided.'),
('size-method','Table 1 particle diameters and dispersities are microscopy-derived sample distributions. Error bars in Figures 3/4 denote sample polydispersity, not uncertainty in the measurement technique.'),
('optical-instrument-gap','Figure 7 reports UV–vis absorbance but the supplied main does not specify the optical instrument, cuvette length, concentration, acquisition temperature or spectral bandwidth. Do not transfer TEM settings to optical measurements.')]
for key,t in char:add('characterization-'+key,2 if key!='optical-instrument-gap' else 4,'Characterization; corresponding figure/caption','measurement_method',t)
table=[('A',1.8,14.9,60,39,18,46),('B',2.2,10.3,90,26,11,45),('C',2.9,8.2,70,50,23,45),('D',3.4,6.0,80,57,33,57),('E',3.4,5.7,90,55,27,49),('F',3.4,6.0,100,59,31,52),('G',3.6,5.8,70,56,22,40),('H',3.9,6.4,70,69,34,49),('I',4.9,11.0,70,107,40,38)]
add('table1',2,'Table 1, heading and column units','table','Nine experiments A–I with precursor concentration (mM), thiol/precursor ratio (mol/mol), temperature (°C), mean nanocrystal diameter (Å), standard deviation (Å) and percent standard deviation. Preserve all six printed values per experiment independently; these are distinct named conditions, not nine time points.')
for label,conc,ratio,temp,diam,sd,percent in table:
    add('table1-'+label.lower(),2,'Table 1, experiment '+label,'table_row',f'Experiment {label}: Ag(acac) {conc:g} mM; thiol/precursor {ratio:g} mol/mol; {temp} °C; mean diameter {diam} Å; standard deviation {sd} Å; relative standard deviation {percent}%.',source_sample_label=label,values={'precursor_concentration_mM':conc,'thiol_precursor_mol_ratio':ratio,'temperature_degC':temp,'mean_diameter_angstrom':diam,'standard_deviation_angstrom':sd,'relative_standard_deviation_percent':percent})
add('fig1-overview',2,'Figure 1, apparatus schematic and caption','apparatus_schematic','Original schematic shows a pressure supply/gauge, piston variable-volume view cell, injection pump and two series sample loops. It is source apparatus geometry, not a generic open heated flask.')
add('fig1-thiol-loop',2,'Figure 1, upper injection-loop label','apparatus_quantity','Thiol injection-loop capacity is labeled 100/200 µL. Retain the printed alternatives; do not assign either capacity to a particular Table 1 row or assume a measured delivered solution volume.')
add('fig1-hydrogen-loop',2,'Figure 1, lower injection-loop label','apparatus_quantity','Hydrogen injection-loop capacity is labeled 800 µL. This is hardware volume, distinct from the text’s 6.22 mg hydrogen charge; no unreported gas state or partial pressure is derived.')
results=[
('ag-reduction','The authors describe H2-assisted Ag(acac) reduction, Ag–Ag bond formation and ligand binding to growing particles; these are mechanistic interpretations rather than directly resolved reaction intermediates.'),
('temperature-comparison','Ag reactions at 60–100 °C are contrasted with roughly 140 °C metal-film chemical vapor deposition using similar precursors (reference 27). The higher CVD temperature is not a current synthesis stage.'),
('low-temperature-explanation','Low-temperature reactivity is attributed to high solubility of H2 and organometallic precursors in CO2, citing references 28/29; no solubility values are measured in this paper.'),
('diameter-range','Results first state Ag mean diameters 26–107 Å; a subsequent paragraph says 25–107 Å. Table 1 reports experiment B as 26 Å. Preserve the mismatch rather than silently changing the row.'),
('concentration-effect','The authors state that higher precursor loading increases average size and summarize a roughly twofold loading change. Table 1 also changes temperature and ligand ratio; do not derive an unqualified continuous concentration-to-size predictor.'),
('polydispersity','Broad size distributions are summarized as approximately ±47% about the mean and relatively insensitive to concentration. Individual Table 1 relative widths range 38–57%; the summary does not replace these values.'),
('temperature-effect','Figure 4 and discussion say diameter/dispersity are not greatly affected by temperature for approximately constant concentration/ligand-ratio experiments D–G. This is a scoped comparison, not a universal invariance.')]
for key,t in results:add('result-'+key,2,'Results discussion','reported_observation_or_interpretation',t)
add('fig2a',3,'Figure 2a, image and caption','tem_figure','Representative Ag nanocrystal TEM image with a 50 nm scale bar. Particles carry C6F13C2H4SH-derived ligands. No experiment letter A–I is assigned to this image.')
add('fig2b',3,'Figure 2b, image and caption; page 2 Results','tem_figure','Ag particle array with a 40 nm scale bar and extended hexagonal close packing, despite broad size dispersity and without size fractionation. This is particle assembly packing, not a measured hcp crystal phase of Ag.')
add('fig2c',3,'Figure 2c, HRTEM image; page 2 Results','hrtem_figure','Ag nanocrystal with a 5 nm scale bar and visible lattice fringes identified in the text as {111} planes. No lattice-spacing value, unit-cell refinement or sample-letter join is given.')
add('fig3',3,'Figure 3, plot and caption','data_figure','Mean Ag diameter (Å) versus initial precursor concentration (mM). Error bars are sample polydispersity, not sizing-technique uncertainty. Plot represents Table 1 experiments; numerical extraction should use the table rather than redigitizing this small plot.')
add('fig3-symbols',3,'Figure 3 caption and axes','figure_metadata','Temperature symbols: 60 °C filled square, 70 °C filled circle, 80 °C downward triangle, 90 °C diamond, 100 °C upward triangle. Visible axes span concentration 0–6 mM and diameter 0–175 Å.')
add('fig4',3,'Figure 4, plot and caption','data_figure','Mean Ag diameter (Å) versus temperature (°C), captioned experiments D–G. Error bars again denote sample polydispersity. The image visibly contains five points including two at 70 °C, although D–G names only four experiments. Keep the original plot and this unresolved extra-point discrepancy.')
add('fig4-axes',3,'Figure 4 axes','figure_metadata','Visible temperature axis 60–110 °C and diameter axis 0–150 Å. The upper 70 °C point resembles the Table H mean but is not explicitly labeled H; do not assert that association as verified.')
add('result-thiol-ratio',3,'Results, first paragraphs below Figure 2','reported_observation','Thiol/precursor ratios are described as about 6:1–15:1 with little apparent size effect under a large ligand excess. Authors state that a more intensive study is needed to determine this effect. Table values 5.7 and 5.8 must not be rounded away.')
add('result-coverage-rationale',3,'Results, thiol-excess discussion','author_interpretation','Large excess thiol is used to seek complete surface coverage because stabilization in sc-CO2 is difficult. This intention does not establish a quantitatively measured full monolayer coverage.')
add('result-redispersion',3,'Results, redispersion paragraph continuing right column','reported_observation','The coated nanocrystals can be repeatedly redispersed in acetone and fluorinated solvents. The authors attribute this to tight ligand binding; exact repeat count and concentration are unreported.')
add('result-spacing',3,'Right column, ligand/interparticle separation discussion','measurement','Approximately 20 Å particle-to-particle separation is observed in TEM (Figure 2a is an example). This is interparticle spacing, not core radius, shell thickness or a crystal lattice spacing.')
add('comparison-octanethiol-spacing',3,'Right column, reference 30 comparison','cited_measurement_context','Octanethiol-coated Ag nanocrystals in earlier work have roughly 10 Å edge-to-edge separation. This is a distinct hydrocarbon-ligand comparison, not a second measurement of the current C8 fluorinated sample.',disposition='retain_cited_comparison_not_current_recipe')
add('intuition-ligand-rigidity',3,'Right column, reference 33 discussion','author_interpretation','Fluorocarbon monolayers are described as more rigid because bulky fluorine groups limit bending/flexing, offering an explanation for larger separations than hydrocarbon-capped particles. No flexibility constant is measured here.')
add('fig5-overview',4,'Figure 5, nine histograms and caption','histogram_figure','Ag diameter distributions for experiments A–I, nine separate conditions explicitly mapped by panel/letter. Horizontal axes diameter (Å), shown from 0 to 200; vertical axes Frequency without numerical count labels. No raw particle list or bin-count table is supplied.')
for label,*_ in table:add('fig5'+label.lower(),4,'Figure 5 panel '+label,'histogram_panel',f'Diameter-frequency histogram for experiment {label}, explicitly corresponding to Table 1 row {label}. The distribution is not an independent additional synthesis or time series.',source_sample_label=label)
add('fig6',4,'Figure 6, EDS curve and caption','eds_figure','EDS of perfluorooctanethiol-capped Ag nanocrystals shows labeled C, F, S and Ag signals. Energy axis spans 0–5 keV; vertical Counts has no numerical scale. No quantitative elemental fractions or specimen-letter A–I are supplied.')
add('fig6-scope',3,'Results, EDS interpretation','measurement_scope','Authors cite EDS as evidence for carbon, fluorine, sulfur and silver in the sample. Carbon-coated grids are also used; this figure does not quantify ligand coverage, prove all carbon comes from ligands, or provide an Ir/Pt composition measurement.')
add('fig7-overview',4,'Figure 7, plot and caption','optical_figure','Three original Ag UV–vis absorbance traces versus wavelength (nm), 325–575 nm shown, arbitrary absorbance scale. Current sc-CO2 route and two comparison preparations are kept distinct; no exact FWHM or absolute absorption coefficient is tabulated.')
add('fig7-i',4,'Figure 7 trace i and associated text on pages 3–4','optical_cohort','Ag(acac) reduction/decomposition in sc-CO2 with C6F13C2H4SH; measured dispersion in acetone. Text assigns this sample diameter 59 Å and a surface-plasmon absorbance maximum at 400 nm. It is not explicitly identified as Table 1 experiment F, despite the matching mean size.')
add('fig7-ii',4,'Figure 7 trace ii and associated text','cited_optical_cohort','AgNO3 reduction in water/acetone with C8F17C2H4SH (C10 fluorinated thiol), measured in acetone. Text gives diameter 55 Å and relates this preparation to reference 23. No full procedure for this comparison is supplied here.',disposition='retain_comparison_evidence_not_new_complete_synthesis')
add('fig7-iii',4,'Figure 7 trace iii and associated text','comparison_optical_cohort','AgNO3 reduction in a water/chloroform biphasic medium using C12H25SH (dodecanethiol), measured in hexane. Described as approximately equal in size to the fluorocarbon-coated sample, but no exact trace-iii diameter or full recipe is provided.',disposition='retain_comparison_evidence_not_new_complete_synthesis')
add('optical-comparison-interpretation',4,'Left column below Figures 5/6','author_interpretation','Authors attribute a width difference between traces i/ii to 59 versus 55 Å size, and the broader fluorocarbon-coated versus dodecanethiol-coated resonance to a shorter electron mean free path associated with highly electronegative fluorine groups. Retain as an interpretation, not measured mean-free-path data.')
add('ir-conditions',4,'Results, Ir/Pt paragraph','protocol_variant','Ir synthesis uses the named (methylcyclopentadienyl)(1,5-cyclooctadiene)iridium(I) precursor at 3.3 mM, thiol/precursor 7.6:1, 80 °C and 276 bar. Exact precursor mass, source-assigned batch ID, yield and quantitative size distribution are unreported.')
add('pt-conditions',4,'Results, Ir/Pt paragraph','protocol_variant','Pt synthesis uses the source-named dimethyl(1,5-cyclopentadiene)platinum(II) at 3.6 mM, thiol/precursor 6.6:1, 80 °C and 276 bar. Preserve the ambiguous precursor identity; exact mass, yield and quantitative size distribution are unreported.')
add('ir-pt-crystallinity',4,'Results, end of Ir/Pt paragraph','reported_observation','Both Ir and Pt particles are reported to exhibit crystalline cores, with their TEM images in Figure 8. No lattice constants, diffraction pattern, indexed phase or measured mean diameter is tabulated.')
add('eq1',4,'Equation 1 and its following paragraph','equation','Equal-radius particle van der Waals interaction: ΦvdW = −A/6 [2R²/(d²+4Rd) + 2R²/(d²+4Rd+4R²) + ln((d²+4Rd)/(d²+4Rd+4R²))]. R is particle radius; d is edge-to-edge separation; A is the Hamaker constant. It is an interaction model, not a fitted measurement.')
add('eq2',5,'Equation 2 and surrounding definitions','equation','Simplified Lifshitz estimate: A121 = (3/4)kT[(ε1−ε2)/(ε1+ε2)]² + [3hνe/(16√2)](n1²−n2²)²/(n1²+n2²)^(3/2). Subscript 1 denotes particles, 2 solvent; ε dielectric constant, n refractive index, h Planck constant. No sample-specific dielectric measurement is supplied.')
add('eq2-uv-frequency',5,'Paragraph below Equation 2','model_parameter','The source calls νe a maximum electronic ultraviolet “adsorption” frequency, typically assumed 3×10^15 s−1. Preserve the printed term/value as a model assumption, not a measured spectrum peak.')
add('eq2-vacuum',5,'Paragraph below Equation 2','model_assumption','For CO2 interactions across vacuum, set ε2 = n2 = 1. A size-dependent Ag dielectric response is acknowledged; the estimate substitutes a bulk-silver vacuum Hamaker value of 2.2 eV from reference 37.')
add('eq3',5,'Equation 3 and following definitions','equation','A131 ≈ (√A11 − √A33)², where A131 is two Ag cores interacting across CO2, A11 is Ag across vacuum and A33 is CO2 across vacuum. Approximate mixing relation; not a measured particle interaction potential.')
add('model-hamaker-comparison',5,'Paragraph following Equation 3','model_result','The authors state a silver-in-CO2 Hamaker constant of 1.4 eV at 25 °C, versus 0.93 eV in acetone, and nearly 50% stronger attraction in CO2. The phrase “sc-CO2 at 25 °C” is inconsistent with their own earlier 31 °C critical temperature; preserve this as a source-model condition discrepancy, not a synthesis temperature.')
add('intuition-solvation',5,'Left column, ligand-tail solvation paragraph','author_interpretation','Ligand tails must be solvated and protrude into the medium so chain fluctuations provide repulsion sufficient to overcome core attraction. Fluorination promotes CO2 solvation, and chain length is important for stabilization.')
add('comparison-c10-ligand',5,'Left column, reference 23 ligand comparison','cited_context','Earlier C8F17C2H4SH has eight fluorinated carbons and two hydrocarbon carbons and permits redispersion in pure CO2. Current C6F13C2H4SH has six fluorinated and two hydrocarbon carbons. Prior C10-ligand results are not a newly executed variant in this paper.',disposition='retain_cited_ligand_comparison')
add('result-inreaction-stability',5,'Left column, current C8-ligand discussion','reported_observation','Current C8 fluorinated ligands control growth, and no flocculation is reported during synthesis. In-reaction stability does not imply stability after solvent removal and washing.')
add('result-no-co2-redispersion',5,'Left column, current C8-ligand discussion','reported_negative_outcome','After collection and washing, current C8-ligand particles do not redisperse in pure CO2, although they redisperse in acetone and fluorocarbon solvents and appear capped in TEM. Retain this negative outcome without inventing a tested concentration, pressure or aggregation rate.')
add('intuition-chain-length',5,'Lower-left paragraph continuing upper-right','author_interpretation','Authors argue that CO2 primarily solvates the fluorinated segment, so the current ligand behaves like a C6 stabilizer. They print that this fluorinated part is 20% shorter than the C10-ligand counterpart. Six versus eight fluorinated carbons implies a different fractional reduction; preserve the source claim and structural counts separately.')
add('comparison-hexanethiol',5,'Right column opening paragraph','cited_context','Hexanethiol-coated Ag is described as difficult to disperse in conventional organic solvents; octanethiol can stabilize Ag in such solvents. These are comparison arguments, not current synthetic variants or measured outcomes.')
add('intuition-polar-solvents',5,'Right column opening paragraph','author_interpretation','The authors explain acetone/ethanol solvation through dipole interactions with the CH2–CF2 group, citing reference 39. Ethanol is discussed in this mechanistic context, not as a fully described additional workup or independently quantified redispersion test.')
model=[
('three-stages','Precursor decomposition produces metal atoms in the ligand’s presence. The cited Chen model separates nucleation, growth and passivation; silver supersaturation drives nucleation until atom concentration falls below saturation. No measured precursor-decay or nucleation-rate trace is given.'),
('temporal-separation','References 3 and 40–42 motivate temporally separated nucleation and growth for narrow distributions; current broad Ag particles are not a demonstrated narrow-distribution implementation of Peng’s separate protocol.'),
('growth-paths','After nucleation, growth can proceed by atom condensation/diffusion-limited addition or by core fusion/coagulation. Organic ligands eventually bind and halt growth; the proposed mechanism is inferred from distributions and images.'),
('self-preserving','At long times relative to nucleation, a self-preserving size-distribution form is expected to depend on mechanism rather than initial nuclei distribution. Current data compare endpoint samples, not time-resolved proof of long-time evolution.'),
('psi1','Similarity transformation ψ1(η) = n(v)φ/N∞², with η = vN∞/φ. n(v) is particle concentration at volume v; φ/N∞ is average particle volume. Source uses lowercase volume notation; preserve definitions rather than treat η as dimensional particle diameter.'),
('integrals','N∞ = ∫₀∞ n(v) dv and φ = ∫₀∞ v n(v) dv are model/distribution definitions. They are not separately measured particle number or mass-yield values.'),
('sphere-assumption','Experimental TEM diameters are converted to particle volumes assuming spherical particles. This geometric assumption must accompany Figures 9/10 and is distinct from a measured atomistic structure.'),
('mechanism-independence','Self-similarity of ψ1 across the samples is interpreted as evidence that precursor concentration does not change the growth mechanism within these experiments.'),
('broadening-narrowing','Limiting-theory comparisons associate condensation with late-time narrowing and coagulation with broad distributions. These are mechanistic arguments, not independent synthesis outcomes.'),
('coagulation-inference','The approximately 47% dispersity and log-normal distribution shapes support a coagulation-dominated interpretation. No raw fit coefficients or proof that condensation is completely absent are supplied.')]
for key,t in model:add('model-'+key,5 if key!='coagulation-inference' else 6,'Growth Mechanism discussion','author_model_or_analysis',t)
add('model-radius-means',6,'Text below Figure 10, continued from left column','equation_definitions','μ1 = r3/rh and μ3 = r1/r3. Arithmetic mean r1 = Σri/N∞; cube-mean r3 = (Σri³/N∞)^(1/3); harmonic mean rh = N∞/Σ(1/ri). Preserve these definitions, not ordinary raw first/third moments inferred from their subscripts.')
add('model-monodisperse-limit',6,'Radius-mean paragraph','model_limit','For a monodisperse sample, r1 = r3 = rh and μ1 = μ3 = 1. This is a theoretical limit, not the measured current dispersity.')
add('model-measured-moments',6,'Radius-mean paragraph','derived_study_result','The study reports average μ1 = 1.48 and μ3 = 0.82. These are study-level distribution-derived ratios, not a separately reported pair for each Table 1 sample.')
add('model-thresholds',6,'Radius-mean paragraph','model_criterion','The cited criteria μ1 >1.25 and μ3 <0.905 indicate coagulation-controlled growth. Preserve the strict inequalities; these are interpretive thresholds rather than measured recipe conditions.')
add('model-psi2',6,'Nondimensional cumulative-distribution paragraph','equation','ψ2(η) = Nv/N∞ = ∫η∞ ψ1(η) dv as printed; Nv = ∫v∞ n(v) dv is the number of particles larger than v. The first integral mixes dimensionless η with differential dv; retain the source notation and avoid a silent mathematical correction.')
add('model-brownian',6,'Figure 10 discussion','model_comparison','The theoretical curve represents long-time Brownian coagulative growth with particle sticking probability 1. It is not a fit establishing measured probability 1 for these particles.')
add('model-sticking',6,'Figure 10 discussion','author_interpretation','Data agree approximately with the model but skew toward larger average volume in the middle of the distribution. Authors interpret this as sticking probability below 1 as ligands passivate particles, eventually approaching zero for stability. No fitted numerical probability or time dependence is supplied.')
add('fig8a',6,'Figure 8a main image and caption','tem_figure','Ir nanocrystals capped with C6F13C2H4SH; main scale bar 10 nm. The sole described Ir condition family is at 3.3 mM, 7.6:1, 80 °C, 276 bar. No author-assigned batch or numerical mean diameter is supplied.')
add('fig8a-inset',6,'Figure 8a upper-right inset','hrtem_figure','Ir lattice-resolved inset with 5 nm scale bar; no indexed planes, measured d-spacing or refined unit cell is given.')
add('fig8b',6,'Figure 8b image and caption','tem_figure','Pt nanocrystals capped with C6F13C2H4SH; scale bar 10 nm. The sole described Pt family is at 3.6 mM, 6.6:1, 80 °C, 276 bar. No numerical mean diameter or exact crystal phase is supplied.')
symbols={'A':'open circle','B':'open square','C':'open diamond','D':'open upward triangle','E':'filled circle','F':'filled square','G':'filled diamond','H':'filled upward triangle','I':'filled downward triangle'}
add('fig9',6,'Figure 9, plot and caption','derived_data_figure','ψ1(η) versus η for experiments A–I; both axes logarithmic. Approximate displayed η ticks 0.001–100 and ψ1 ticks 0.0001–1. TEM-to-volume conversion assumes spheres. No raw numerical transformed distribution is tabulated.',sample_symbols=symbols)
add('fig10',6,'Figure 10, plot and caption','derived_data_and_model_figure','ψ2(η) versus η for experiments A–I with the same marker map, plus a solid theoretical coagulation curve. η axis is logarithmic, 0.001–100; ψ2 is linear, 0–1.2. Keep experimental points distinct from the theoretical line.',sample_symbols=symbols)
add('result-polycrystallinity',6,'Discussion of Figure 11','reported_observation','Some Ag cores show multiple misaligned lattice fringes; most particles examined appear single crystalline (Figure 2c). Do not assign every particle the polycrystalline label or infer a measured fraction.')
add('intuition-realignment',6,'Discussion of Figure 11','author_interpretation','Internal domains may relate to nuclei before coagulation; the authors suggest lattice planes can realign after fusion while some polycrystallinity remains. These are ex situ images, not a directly imaged time sequence or definitive mechanism proof.')
add('comparison-gold-restructuring',6,'Yacamán discussion, reference 48','cited_context','Gold particles up to 70 Å reportedly reorganize after coagulation; reference 48 is a personal communication. This is not an Ag size outcome or a primary paper independently reviewed here.',disposition='retain_personal_communication_context')
for panel,bar in [('a',5),('b',5),('c',5),('d',6)]:
    add('fig11'+panel,7,'Figure 11'+panel+', image and caption','hrtem_figure',f'Ag nanocrystal panel {panel} with {bar} nm scale bar. '+('Multiple misaligned lattice fringes are reported.' if panel!='d' else 'Caption describes a coagulated nanocrystal with partial plane realignment.')+' No Table 1 sample letter, acquisition chronology, quantitative domain sizes or direct precursor-to-image batch ID is given.')
conclusions=[
'Ag, Ir and Pt particles and their acetone/fluorinated-solvent redispersion are summarized. The claimed first synthesis in pure CO2 is historical author framing, not an externally verified modern novelty claim.',
'Future candidate precursors should dissolve in CO2, remain stable at moderate temperature and decompose upon H2 addition. Higher temperatures or stronger reductants are proposed if H2 fails; these are outlook conditions, not performed additional experiments.',
'The ligand should interact favorably with solvent while binding weakly enough to permit growth and strongly enough to arrest it. No universal optimized binding energy or ligand-selection model is measured.',
'The authors summarize mean Ag sizes 26–107 Å, approximately size-independent broad dispersity and distribution self-similarity as evidence for predominantly coagulative growth.',
'C8 fluorinated ligands provide in-reaction control but insufficient redispersibility in pure CO2 after isolation, whereas the cited C10 ligands stabilize more effectively. Stronger attraction in low-polarizability CO2 is the authors’ explanation; alternatives remain source-scoped.'
]
for n,t in enumerate(conclusions,1):add(f'conclusion-{n:02}',7,'Conclusions','author_summary_or_outlook',t)
add('acknowledgments',7,'Acknowledgment continuing on page 8','administrative','Support: NSF STC CHE-9876674, Petroleum Research Fund, Welch Foundation and UT Austin Separations Research Program; Korgel acknowledges a DuPont young-professor grant; John Mendenhall assisted with TEM. This is provenance/acknowledgment, not an experimental condition.',disposition='administrative_record_only',additional_pages=[8])
reftext=(B/'main-08.txt').read_text(encoding='utf-8')
for n in range(1,49):
    m=re.search(r'\('+str(n)+r'\)\s+(.*?)(?=\('+str(n+1)+r'\)\s|\Z)',reftext,re.S)
    assert m,n
    citation=re.sub(r'\s+',' ',m.group(1)).strip()
    if n==48:citation=citation.split('9440 J. Phys.')[0].strip()
    add(f'reference-{n:02}',8,f'References and Notes, item {n}','reference_or_note',citation,disposition='bibliographic_context_not_independently_read_in_this_source_review',reference_number=n)
add('note22-context',8,'Reference/Note 22','cited_synthesis_context','The note describes silicon nanowires in supercritical hexane at 500 °C using gold seed crystals stabilized by thiol ligands, citing Holmes et al., Science 2000, 287, 1471. This does not add a current silicon recipe or transfer 500 °C to the Ag/Ir/Pt reactions.',disposition='retain_cited_context_only')
add('note32-context',8,'Reference/Note 32','cited_quantitative_context','Prior biphasic thiol/precursor ratios below 1, Brust’s 10–30 Å Au particles with final thiol/Au =1:3, and Leff’s precursor ratios 1:1–6:1 are cited to justify excess thiol in the current study. These are distinct reported quantities/denominators, not current Ag reaction ratios.',disposition='retain_cited_context_only')
conflicts=[
('pt-identity','The twice-printed Pt precursor name contains 1,5-cyclopentadiene. Identity is chemically ambiguous; no unstated correction to a cyclooctadiene complex or exact formula/3D model is permitted without verified separate evidence.',[2,4]),
('minimum-diameter','The body states 25 Å once, whereas Table 1 B and other text give 26 Å. Preserve the tabulated26 value and the prose discrepancy.',[2]),
('fig4-point-count','Figure 4 caption D–G names four conditions but shows five plotted points, including two at70°C. A possible H-like value is not a verified sample assignment.',[3]),
('hamaker-co2-state','The modeled1.4eV interaction is called sc-CO2 at25°C although the introduction states31°C critical temperature. Retain the reported model context and conflict; do not use25°C as reaction temperature.',[1,5]),
('fluorinated-length','Source formulas specify six versus eight fluorinated carbons, while prose says the current fluorinated part is20%shorter. Preserve both rather than silently substitute25% or change formulas.',[5]),
('percent-dispersity','Tabulated percentages are source values and need not exactly equal100×rounded SD/rounded mean. Do not recompute or silently overwrite the published percent column.',[2]),
('population-scope','Abstract/conclusion20–120Å is a broad family description; histograms extend toward200Å and individual samplemeans differ. Do not interpret20–120Å as a strict min/max for every particle or an Ir/Ptmean.',[1,4,6]),
('cohort-joins','Figures2/6/11 lackA–I sample labels. Figure7i59Å matchesTableFmean but has no explicitFjoin; keep opticalcohortdistinct. Figure8hasmaterial-specificIr/Ptmethodassociation but noauthorbatchIDs.',[3,4,6,7]),
('volume-bases','27mL workingcell,14–18mLCO2fill,100/200µLthiolloop and800µLH2loop are different quantities. No per-row precursor mass or exact gaspartialpressure should be derived from them.',[2]),
('distribution-integral','Printed ψ2 integral uses η as lower bound and ψ1 argument but dv as differential. Preserve the displayed mathematical notation and flag this variable mismatch instead of silently repairing it.',[6])]
for key,t,pages in conflicts:add('conflict-'+key,pages[0],'Cross-check of printed source claims','source_conflict_or_join_restriction',t,disposition='preserve_explicit_unresolved_scope',additional_pages=pages[1:])
add('scope-no-precursor-preparation',2,'Complete Experimental Section','missingness','Metal precursors and stabilizing ligand are purchased; no upstream syntheses of these compounds are supplied. Do not invent precursor synthesis instructions or label purchased inputs as prepared stocks.')
add('scope-no-diffraction',6,'Complete supplied main article','missingness','No SAED pattern, XRD pattern, measured CIF, refined lattice constants, Raman data or Ir/Pt absorption spectrum is supplied. HRTEM fringes and qualitative crystalline-core statements remain the supported structural evidence.')
add('scope-no-si',8,'Supplied bundle scope','missingness','No supporting-information file is supplied in this reviewed bundle. The absence of a supplied SI is not proof that none exists; record SI not located or verified.')
pages=[]
for n in range(1,9):
    pages.append({'pdf_page':n,'printed_page':9432+n,'text_read':True,'visual_review':True,'text_sha256':sha(B/f'main-{n:02}.txt'),'render_sha256':sha(B/f'main-{n:02}.png'),'source_unit_ids':[u['id'] for u in U if u['pdf_page']==n or n in u.get('additional_pages',[])]})
assert len({u['id'] for u in U})==len(U)
report={'schema':'mattersyn-independent-source-audit-1','source_id':'shah2001','doi':'10.1021/jp011815c','title':'Nanocrystal Arrested Precipitation in Supercritical Carbon Dioxide','authors':['Parag S. Shah','Shabbir Husain','Keith P. Johnston','Brian A. Korgel'],'journal':'Journal of Physical Chemistry B','year':2001,'volume':105,'issue':39,'printed_pages':'9433–9440','dates':{'received':'2001-05-11','published_web':'2001-08-31'},'source_path':str(source),'source_sha256':sha(source),'checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reviewer':'independent_shah2001_source_audit','status':'supplied_main_text_and_visual_inventory_complete','review_scope':'All eight supplied main pages independently read and visually inspected, including eleven figures, nine-row table, three numbered equations, inline mathematical definitions,48references/notes,and administrative material. SI not located/verified in this supplied bundle.','supporting_information':{'status':'not_located_or_verified','absence_not_proven':True},'page_review':pages,'unit_count':len(U),'units':U,'table1_rows':[{'experiment':r[0],'precursor_mM':r[1],'thiol_precursor_mol_ratio':r[2],'temperature_degC':r[3],'mean_diameter_angstrom':r[4],'standard_deviation_angstrom':r[5],'relative_standard_deviation_percent':r[6]} for r in table],'independent_canonical_audit_status':'awaiting_root_drafts','scope_limits':['Source inventory is not proof of canonical integration, reader coverage, browser verification or publication.','Cited works remain separate; no external paper or supplement was downloaded or inspected.','No plot digitization, inferred specimen joins, repaired precursor identity or measured atomic models introduced.']}
(B/'source-audit.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines=['# Independent full-source audit — Shah et al. (2001)','',f"DOI10.1021/jp011815c. All8suppliedmainpagesreadandvisuallyinspected; {len(U)}stableunits. SI not located or verified.",'','Critical distinctions: nine Ag experiments A–I retain all six table values; Ir/Pt conditions remain separately scoped; simultaneous H2/thiol injection and pressure/volume bases preserved; purchased precursors have no fabricated upstream preparation. Ambiguous Pt nomenclature, Figure4pointcount,25/26Åminimum,25°Csc-CO2modelwording,and fluorinatedchainlengthclaimremainexplicit.','']
for u in U:lines+=['## '+u['id'],f"Main PDF p.{u['pdf_page']}, printed p.{u['printed_page']}; {u['locator']}. [{u['kind']}; {u['disposition']}]",u['claim'],'']
(B/'source-audit.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
(B/'independent-page-coverage.json').write_text(json.dumps({'source_id':'shah2001','source_sha256':report['source_sha256'],'checked_utc':report['checked_utc'],'page_review':pages},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'units':len(U),'pages':len(pages),'source_sha256':report['source_sha256'],'audit_sha256':sha(B/'source-audit.json')},ensure_ascii=False))
