"""Derive a private inventory proposal from the current canonical and generated atlas."""
from pathlib import Path
from collections import Counter
from datetime import datetime,timezone
import json,sys,hashlib,copy
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas';O=B/'inventory-proposal'
sys.path.insert(0,str(S/'scripts'))
from dataset_lib import eligibility,build_groups,digest
from build_atlas import synthesis_route
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(n,x):(O/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
base=read(O/'base-inventory-summary.json');inv=copy.deepcopy(base)
records={p.stem:read(p)for p in (S/'data/records').glob('*.json')}
routes={k:r for k,r in records.items()if synthesis_route(r)}
lit={k:r for k,r in records.items()if r['collection']=='reviewed_literature'}
procedures={k:r for k,r in lit.items()if r['record_type']=='procedure'}
observations={k:r for k,r in lit.items()if r['record_type']=='observation'}
controls={k:r for k,r in lit.items()if k not in routes and k not in procedures and k not in observations}
benchmark={k:r for k,r in records.items()if r['collection']=='published_benchmark'}
groups=build_groups(list(records.values()));sourcegroups=sorted({r['lineage']['source_group']for r in records.values()})
sources={g:next(s for r in records.values()if r['lineage']['source_group']==g for s in r['sources']if s['id']==g)for g in sourcegroups}
index=read(S/'dist/data/materials-index.json');hubs={m['formula']:read(S/'dist/data/materials'/(m['id']+'.json'))for m in index['materials']}
reviews=read(S/'dist/data/paper-review-index.json')['papers'];mainonly=[r for r in reviews if r['review_scope']=='supplied_main_only_si_unverified'];mainsi=[r for r in reviews if r['review_scope']=='supplied_main_and_matched_si']
library=read(S/'dist/data/library-index.json');localdois={p['doi'].lower()for p in library['papers']};reviewedlocal={s['doi'].lower()for s in sources.values()}&localdois
direct=sorted({r['material']['formula']for r in routes.values()});component=sorted(f for f,h in hubs.items()if h['component_only'])
elig={t:sum(eligibility(r)[t]['eligible']for r in records.values())for t in eligibility(next(iter(records.values())))}
ss=inv['summary'];ss.update(canonical_records=len(records),reviewed_literature_records=len(lit),reviewed_literature_source_groups=len({r['lineage']['source_group']for r in lit.values()}),total_canonical_source_groups=len(sourcegroups),local_groups_without_canonical_records=len(localdois)-len(reviewedlocal),synthesis_route_variant_records=len(routes),contextual_control_variant_records=len(controls),shared_preparation_workup_characterization_assay_procedures=len(procedures),contextual_observation_records=len(observations),nonprocedure_literature_records=len(lit)-len(procedures),recipe_or_control_literature_records=len(routes)+len(controls),literature_record_type_counts=dict(sorted(Counter(r['record_type']for r in lit.values()).items())),canonical_record_type_counts=dict(sorted(Counter(r['record_type']for r in records.values()).items())),literature_recipe_family_ids=len({r['lineage']['recipe_family']for r in lit.values()}),primary_synthesis_recipe_family_ids=len({r['lineage']['recipe_family']for r in routes.values()}),contextual_observation_family_ids=len({r['lineage']['recipe_family']for r in observations.values()}),public_material_hubs=len(hubs),direct_synthesis_target_systems=len(direct),component_only_hubs=len(component),all_nonprocedure_literature_product_identity_categories_including_controls=len({r['material']['formula']for r in lit.values()if r['record_type']!='procedure'}),formal_full_main_reviews_si_unverified=len(mainonly),formal_full_main_only_review_pages=sum(r['pages_read']for r in mainonly),formal_full_main_and_matched_si_reviews=len(mainsi),formal_full_review_pages=sum(r['pages_read']for r in mainsi),verified_exact_structure_recipe_pairs=elig['exact_structure_recipe'])
inv['inventory_version']=datetime.now(timezone.utc).date().isoformat()+'-shah-actual-local-snapshot'
inv['scope']='Reviewed inventory derived from current canonical records and generated atlas. Source documents, complete recipes and independent experiments remain different counts. Incoming-folder monitoring counts are separate.'
inv['material_system_lists'].update(direct_synthesis_targets=direct,component_only_public_hubs=component,control_only_additional_product_labels=sorted({r['material']['formula']for r in controls.values()}-set(direct)),contextual_observation_product_labels=sorted({r['material']['formula']for r in observations.values()}))
g='shah2001';rr={k:r for k,r in records.items()if r['lineage']['source_group']==g};src=sources[g]
review=read(S/'data/paper-reviews/shah2001.json')
row={'source_group':g,'doi':src['doi'],'url':src['url'],'title':src['title'],'year':src['year'],'has_local_corpus_group':src['doi'].lower()in localdois,'review_status':'full_supplied_main_review_si_unverified','review_scope':'All eight supplied main pages text and visually reviewed with independent source, canonical, reader, chemical and apparatus audits; SI not located or verified; deployment tracked separately.','documents':[{'role':'main','page_count':8,'all_text_read':True,'all_visually_reviewed':True}],'evidence_locator':'data/paper-reviews/shah2001.json','paper_review_url':'paper-review.html?id=shah2001','si_status':'not_located_or_verified','canonical_record_count':len(rr),'synthesis_route_variant_count':len(rr.keys()&routes.keys()),'contextual_control_count':len(rr.keys()&controls.keys()),'contextual_observation_count':len(rr.keys()&observations.keys()),'procedure_count':len(rr.keys()&procedures.keys()),'benchmark_row_count':0,'measurement_entry_count':sum(len(r['measurements'])for r in rr.values()),'record_type_counts':dict(sorted(Counter(r['record_type']for r in rr.values()).items())),'canonical_recipe_family_ids':sorted({r['lineage']['recipe_family']for r in rr.values()}),'direct_route_material_systems':sorted({routes[k]['material']['formula']for k in rr.keys()&routes.keys()}),'record_ids':sorted(rr),'record_urls':{k:'records/'+k+'.html'for k in sorted(rr)},'notes':['Nine silver experiments A–I and two separate iridium/platinum conditions provide eleven source-linked synthesis variants.','Four common procedures and four contextual observations remain separate from experimental routes.','Twenty-one original source assets preserve eleven figures, Table 1, equations, definitions and procedural notes.','The platinum precursor remains as printed with unresolved identity. Figure 7 cohorts are not silently joined to same-size Table 1 rows. No measured atomic coordinates or exact-structure training labels supplied.']}
inv['per_paper']=sorted([p for p in inv['per_paper']if p['source_group']!=g]+[row],key=lambda p:p['source_group'])
old={m['material_system']:m for m in inv['per_material']};new=[]
for f in sorted(set(old)|set(hubs)|{r['material']['formula']for r in records.values()}):
 m=copy.deepcopy(old.get(f,{'material_system':f,'notes':[]}));h=hubs.get(f);rr={k:r for k,r in records.items()if r['material']['formula']==f};dr=sorted(rr.keys()&routes.keys());hids=set(h['record_ids'])if h else set();cid=sorted(hids-set(dr));sg=sorted({records[k]['lineage']['source_group']for k in rr.keys()|hids})
 m.update(direct_synthesis_route_variant_count=len(dr),direct_route_record_ids=dr,contextual_control_count=len(rr.keys()&controls.keys()),contextual_control_record_ids=sorted(rr.keys()&controls.keys()),contextual_observation_count=len(rr.keys()&observations.keys()),contextual_observation_record_ids=sorted(rr.keys()&observations.keys()),procedure_count=len(rr.keys()&procedures.keys()),benchmark_row_count=len(rr.keys()&benchmark.keys()),public_hub_exists=bool(h),public_hub_component_only=h['component_only']if h else None,public_hub_route_contributions=len(hids),component_route_contribution_count=len(cid),component_route_record_ids=cid,primary_reviewed_source_count=len({r['lineage']['source_group']for k,r in rr.items()if k in lit and k not in procedures}),material_hub_id=h['id']if h else None,material_hub_url=h['url']if h else None,source_groups=sg,source_links=[{'source_group':g,'doi':sources[g]['doi'],'url':sources[g]['url'],'title':sources[g]['title']}for g in sg],direct_route_recipe_family_ids=sorted({routes[k]['lineage']['recipe_family']for k in dr}))
 if f=='ZnS':m['notes']=['Shell-component context only; this page does not claim an isolated ZnS synthesis.']
 new.append(m)
inv['per_material']=new
inv['training_eligibility']=elig
inv['provenance'].update(canonical_record_files=len(records),canonical_tree_sha256=digest({k:digest(r)for k,r in sorted(records.items())}),canonical_tree_hash_rule='SHA256 of sorted record-ID to normalized-record-digest JSON from actual integrated records.',inventory_mode='actual_local',promotion_assumption='No simulated promotion; actual source-reviewed canonical records counted.',publication_verification='Tracked separately by publication checkpoint.',generated_dataset_version_observed=read(S/'dist/data/dataset-manifest.json')['dataset_version'])
expected_new=len(list((B/'canonical-drafts').glob('*.json')))
checks={'record_id_inventory_exact':{k for p in inv['per_paper']for k in p['record_ids']}==set(records),'category_partition':len(routes)+len(controls)+len(procedures)+len(observations)+len(benchmark)==len(records),'all_shah_records':len(row['record_ids'])==expected_new,'eleven_shah_routes':row['synthesis_route_variant_count']==11,'unchanged_benchmark':len(benchmark)==100,'full_corpus_totals_unknown':ss['full_corpus_recipe_count']is None and ss['full_corpus_distinct_synthesized_material_count']is None,'one_source_group':len({groups[k]for k in row['record_ids']})==1,'nine_explicit_ag_size_labels':elig['size_conditioned_recipe']==15,'no_exact_structure':elig['exact_structure_recipe']==0,'no_success_labels':elig['success_prediction']==0,'no_new_optical_labels':elig['optical_outcome']==95,'old_records_preserved':len(records)-expected_new==base['summary']['canonical_records']}
assert all(checks.values()),checks
write('inventory-summary.json',inv);write('validation.json',{'status':'passed','checks':checks,'summary':ss,'training_eligibility':elig,'source_group':g,'measurement_entries':row['measurement_entry_count']})
print(json.dumps({'status':'passed','records':len(records),'routes':len(routes),'procedures':len(procedures),'observations':len(observations),'hubs':len(hubs),'direct':len(direct),'component':len(component),'training':elig}))
