from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,subprocess,sys,shutil
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas';N='[local path redacted]'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
results=[]
commands=[[N,str(B/'reader-assets/check_reader_runtime.mjs')],[sys.executable,'-X','utf8',str(B/'reader-assets/check_integrated_presentation.py')]]
commands += [[sys.executable,'-X','utf8',str(S/'scripts'/f)]for f in ['check_site.py','check_quality.py']]
commands += [[N,'--check',str(S/'dist'/f)]for f in ['shah2001-protocol.mjs','protocol-visuals.mjs','crystal-viewer.mjs','source-evidence.mjs','paper-review.mjs','material-guide.mjs']]
for cmd in commands:
 r=subprocess.run(cmd,cwd=S,capture_output=True,text=True,encoding='utf-8');results.append({'command':cmd,'returncode':r.returncode,'stdout':r.stdout,'stderr':r.stderr});print(r.stdout,end='');print(r.stderr,end='')
 if r.returncode:break
passed=all(x['returncode']==0 for x in results)
write(B/'final-validation.json',{'status':'passed'if passed else'failed','at':datetime.now(timezone.utc).isoformat(),'results':results})
if not passed:sys.exit(1)
if not (B/'initial-build-validation.json').exists():shutil.copy2(B/'build-validation.json',B/'initial-build-validation.json')
write(B/'build-validation.json',{'status':'passed','initial_build':'initial-build-validation.json','final_checks':'final-validation.json','resolved_findings':['Initial legacy quality rule assumed Ag was only a Stiger supported-particle component; updated to check the nine audited direct colloidal routes and preserve the supported route.','Public reader now preserves exact independently audited material-evidence ordering and notes.','Shared reagent specifications are grouped once for display, keeping all canonical facts and links unchanged. Updated module cache versions verified in browser.'],'canonical_records':272,'routes':64,'procedures':68,'observations':26,'controls':14,'benchmark_rows':100,'hubs':24,'direct_systems':19,'component_hubs':5,'training':read(S/'dist/data/validation-report.json').get('eligible_by_task'),'final_source_module_sha256':sha(S/'dist/source-evidence.mjs')})
write(B/'browser-qa.json',{'status':'passed','at':datetime.now(timezone.utc).isoformat(),'browser':'Codex in-app browser; temporary local QA tab12','origin':'http://127.0.0.1:5187','checks':['Ag experiment A renders six chemical entries, correct purity bounds, five protocol stages and original source evidence.','Selecting Ag A condition stage changes the pressure-cell illustration and reports 60 C / 276 bar, with no fabricated duration.','Fluorinated ligand viewer opens its computed conformer; highlight toggle, zoom and keyboard rotation exercised.','Figure scope changes from selected formulation (3 of 12 figures/tables) to all source originals; original Figure7 opens at enlarged resolution.','Complete source reader renders 138 items; purity search finds relevant source evidence. Shared CO2 specification displays once with 12 linked-record note after final cache update.','Pt material hub renders its reviewed method, explicit unresolved precursor identity and Figure8 only in selected-figure scope.','Pt hold shows 80 C / 276 bar and inherited 3 h qualifier; original Figure8 a/b retain Ir/Pt panel attribution.','Ir reference viewer renders unchanged bulk FCC unit cell and 2x2x2 lattice with reference CIF download and explicit no-measured-Shah-phase caveat.','Selecting Pt in periodic table yields one reviewed Pt page linked to material.html?id=pt-b602b7.','Ag hub selector contains nine Shah variants plus existing Stiger supported-particle route; selecting B updates condition stage to 90 C / 276 bar.','No browser console errors or warnings observed on checked routes.'],'limitations':['All 74 generated scene outputs and all 21 original asset hashes checked by independent/private runtime verification; UI interactions sampled representative stages and assets, not every possible click.','No fabricated Ag/Pt atomic lattice; only verified local Ir bulk comparison was reused.'],'source_module_sha256':sha(S/'dist/source-evidence.mjs'),'apparatus_module_sha256':sha(S/'dist/shah2001-protocol.mjs'),'reader_sha256':sha(S/'data/paper-reviews/shah2001.json')})
m=read(B/'milestones.json');m['audit']={'status':'complete','evidence':[str(B/p)for p in ['source-audit.json','canonical-records-audit.json','reader-source-audit.json','molecular-source-audit.json','visual-source-audit.json','ir-reference-audit.json','reader-assets/canonical-to-reader-audit.json','reader-assets/integrated-presentation-audit.json']],'note':'Independent complete source, canonical, reader, molecular, figure and apparatus audits passed with explicit source limits.'};m['integrate']={'status':'complete','evidence':[str(B/'integration-manifest.json'),str(B/'build-validation.json'),str(B/'browser-qa.json')],'note':'Existing Site extended with 19 records, Pt hub and Ag/Ir methods; all affected checks passed and representative controls verified.'};write(B/'milestones.json',m)
print('Final scientific integration and browser checks saved; native publication remains pending.')
