from pathlib import Path
import json,hashlib,datetime
A=Path(__file__).resolve().parent;G=A.parents[1];C=G/'canonical-proposal/v2';P=G/'public-review-proposal/v2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def save(n,x):(A/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert not (A/'package-freeze.json').exists(),'Never silently overwrite a frozen author package'
validation=read(A/'author-validation.json');assert validation['checks']==947 and validation['operations']==33
scenes=read(A/'rendered-scenes.json');cfg=read(A/'scene-config.json');previews=read(A/'preview-manifest.json');bindings=read(A/'canonical-bindings.json')
assert len(scenes)==len(bindings['bindings'])==33
for b in bindings['bindings']:assert sha(Path(b['record_path']))==b['record_sha256']
bindings['status']='author_frozen_pending_distinct_independent_audit';save('canonical-bindings.json',bindings)
previews['visual_review_status']='All 33 scenes actually viewed on nine contact sheets; five changed/critical final full previews reopened.';save('preview-manifest.json',previews)
review={'author':'/root/norberg2004_extract','reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'author_visual_review_complete_independent_audit_pending','scene_count':33,'viewed_contact_sheets':[{'path':str(A/x['path']),'sha256':sha(A/x['path']),'operation_ids':x['operation_ids']} for x in previews['contacts']],'final_individual_previews_viewed':['ensemble-acquire','constant-s-grow','core-inject','shell-cycles','single-acquire'],'source_basis':'Author previously independently read and viewed all 10 main + 9 SI source pages and all 36 original crops during the separate passed source audit. These apparatus illustrations use the passed canonical v2 records and retain source-stage missingness. No new source download or original re-render.','author_findings_resolved_before_first_freeze':[{'finding':'Neutral count units needed for wash cycles, FTIR scans and frames.','reported_by':'/root/backlog_eta during pre-freeze review','resolution':'Unit remains count; parameter labels specify context. No source numeric change.'},{'finding':'Ensemble icon arrows could imply separate instruments were used exclusively for sample and reference.','reported_by':'/root/norberg2004_extract during actual own visual review','resolution':'Explicit separate sample/reference acquisitions feed both instrument contexts; diagram does not combine solutions.'}],'visual_scope_notes':['All 33 diagrams and their conditions read for clipping, complete labels and stage-specific action.', 'Three repeated core-isolation scenes intentionally reuse the same workup action with distinct branch labels; other diagrams vary by action.', 'Round-bottom vessels/condenser/thermocouple are reported for common core synthesis; other detailed geometry is explanatory.', 'No bath or numerical pressure is invented; thermal symbols do not specify heater type.', 'Nanocrystal symbols appear after core formation or for pre-existing seed/measurement inputs.', 'Separate alternatives and pure-ligand FTIR specimens are not a combined batch.', 'Cd passivation is not a full CdS layer; only paired additions complete the illustrated shell cycle.', 'CCD nitrogen is instrument cooling only; no sample cryogenic condition assigned.', 'No synthetic spectrum, micrograph, SAED pattern or atomic coordinates.'],'mounted_browser_test':False,'independent_scientific_approval':False}
save('author-visual-review.json',review)
readme='''# Ghosh 2012 apparatus proposal

Private author package for all 33 canonical operations in 15 records. Source extraction revision 2 and canonical/reader revision 2 are separately audited; this illustration package requires distinct independent review and later Site/browser checks.

Public module candidate: `ghosh2012-protocol.mjs` only. It imports the existing source-neutral `quantity-value.mjs` dependency, whose copied hash is bound here. Private records, manifests, source files, preview index and audit helpers are not public attachment candidates.

API: `buildGhosh2012Scene(operation, record)`, `createGhosh2012Art(operation, record)`, `createGhosh2012ConditionGrid(operation, record)`, `renderGhosh2012Markup(scene)` and `ghosh2012SceneSelection`. Dispatch rejects foreign source groups, unrelated record IDs and unknown operations. Use the dedicated conditions grid instead of duplicating generic conditions alongside it.

The 70 operation parameters and ten Table 1 alternative-schedule parameters are read from the actual supplied canonical objects. Source-specific prose and 103 scope/missingness notes form 183 display rows. Approximate quantities, ranges and strict inequalities retain their qualifiers. No inferred gas, pressure, dose, bath, atomic geometry or spectra are introduced.

The 33 SVGs/PNGs and nine contact sheets were actually viewed. Final ensemble/core-injection/shell-cycle/constant-sulfur/single-dot previews were reopened after bounded label changes. Minimal DOM tests exercise both public factories; these are not a mounted-browser approval. All frozen source/canonical/reader bytes remain unchanged.
'''
(A/'README.md').write_text(readme,encoding='utf-8')
allpaths=[p for p in A.rglob('*') if p.is_file() and p.name!='package-freeze.json' and '__pycache__' not in p.parts]
allpaths += [G/'package-freeze.json',G/'source-facts.json',G/'source-inventory.json',G/'source-tables.json',G/'source-independent-audit/independent-audit-v2.json',G/'canonical-reader-independent-audit/independent-audit-v2.json',C/'package-manifest.json',C/'record-manifest.json',P/'ghosh2012.json']
allpaths += [Path(b['record_path']) for b in bindings['bindings']]
bound={str(p):sha(p) for p in allpaths}
manifest={'schema':'mattersyn-private-apparatus-freeze/1','source_id':'ghosh2012','doi':'10.1021/ja212032q','author':'/root/norberg2004_extract','frozen_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'author_frozen_pending_independent_audit','source_freeze_sha256':sha(G/'package-freeze.json'),'canonical_package_sha256':sha(C/'package-manifest.json'),'canonical_audit_sha256':sha(G/'canonical-reader-independent-audit/independent-audit-v2.json'),'counts':{'operation_records':15,'scenes':33,'art_types':len(set(c['art'] for c in cfg['configs'].values())),'operation_parameters':70,'alternative_schedule_parameters':10,'source_scope_notes':103,'display_rows':183,'svg_previews':33,'png_previews':33,'contact_sheets':9,'executed_author_checks':validation['checks']},'public_assets':[{'path':str(A/'ghosh2012-protocol.mjs'),'sha256':sha(A/'ghosh2012-protocol.mjs'),'target':'ghosh2012-protocol.mjs','role':'source_specific_explanatory_apparatus'}],'existing_dependency':{'path':'quantity-value.mjs','sha256':sha(A/'quantity-value.mjs')},'bound_files':bound,'scientific_independent_approval':False,'browser_approved':False,'site_imported':False,'published':False,'training_approved':False}
save('package-freeze.json',manifest)
print(json.dumps({'freeze_sha256':sha(A/'package-freeze.json'),'module_sha256':sha(A/'ghosh2012-protocol.mjs'),'bound_files':len(bound),'counts':manifest['counts']},ensure_ascii=False))
