"""Adapt the existing count derivation; scientific source metadata stays explicit."""
from pathlib import Path
B=Path(__file__).resolve().parent
template=Path('[local path redacted]').read_text(encoding='utf8')
template=template.replace("S=B.parents[3]/'recipe-atlas'","S=Path('[local path redacted]')").replace('sashchiuk2004','gu2004').replace('sashchiuk','gu')
start=template.index('row={');end=template.index("\ninv['per_paper']",start)
row="""row={'source_group':g,'doi':src['doi'],'url':src['url'],'title':src['title'],'year':src['year'],'has_local_corpus_group':src['doi'].lower()in localdois,'review_status':'full_supplied_main_and_matched_si_review','review_scope':'All two main and three matched SI pages text-read and visually inspected. Independent source, canonical, reader, molecular, product, apparatus and task-eligibility audits. Stage identities, failed intermediate isolation, analytical/model contexts and the main/SI XRF discrepancy remain distinct. Cited external full texts are not claimed read.','documents':[{'role':'main','page_count':2,'all_text_read':True,'all_visually_reviewed':True},{'role':'si','page_count':3,'all_text_read':True,'all_visually_reviewed':True}],'evidence_locator':'data/paper-reviews/gu2004.json','paper_review_url':'paper-review.html?id=gu2004','si_status':'matched_and_reviewed','canonical_record_count':len(rr),'synthesis_route_variant_count':len(rr.keys()&routes.keys()),'contextual_control_count':len(rr.keys()&controls.keys()),'contextual_observation_count':len(rr.keys()&observations.keys()),'procedure_count':len(rr.keys()&procedures.keys()),'benchmark_row_count':0,'measurement_entry_count':sum(len(r['measurements'])for r in rr.values()),'record_type_counts':dict(sorted(Counter(r['record_type']for r in rr.values()).items())),'canonical_recipe_family_ids':sorted({r['lineage']['recipe_family']for r in rr.values()}),'direct_route_material_systems':sorted({routes[k]['material']['formula']for k in rr.keys()&routes.keys()}),'record_ids':sorted(rr),'record_urls':{k:'records/'+k+'.html'for k in sorted(rr)},'notes':['One FePt/CdS heterodimer route plus a separate Cd(acac)2 precursor procedure; ten records are not ten independent syntheses.','All seven figures, one scheme and four excerpts retained as twelve original assets; actual final-product SAED Figure1D is supplied.','Exact atomic coordinates and numeric initial ether boiling point are not supplied. Formal chemical component diagrams and product-domain illustrations are excluded from measured-structure training targets.']}"""
template=template[:start]+row+template[end:]
anchor="inv['training_eligibility']=elig"
definition_fix="""inv['count_definitions'].update(contextual_control='Source-scoped controls or diagnostic variants, counted separately from synthesis routes, supporting procedures and observations; not automatically independent physical experiments.',recipe_family='Grouping identifiers used to connect related source protocols and procedures. They are not unique physical recipes or independent runs.',material_system='Direct synthesis targets retain product architecture and unresolved composition; component-only hubs link the whole-system route without claiming an isolated component synthesis.',contextual_observation='Source-scoped characterization series, model interpretations or incomplete observations retained separately from synthesis routes. They do not create additional verified syntheses.')
inv['material_system_lists'].pop('excluded_precursor_procedure_identity',None)
inv['material_system_lists']['excluded_precursor_procedure_identities']=['Fe–C–H–O',records['gu-2004-cdacac-preparation']['material']['formula']]
"""
template=template.replace(anchor,definition_fix+anchor)
anchor="inv['provenance'].update("
provenance_fix="""current_inputs=[S/'data/corpus/library-source.json',S/'dist/data/dataset-manifest.json',S/'dist/data/validation-report.json',S/'dist/data/materials-index.json',S/'dist/data/library-index.json',S/'dist/data/paper-review-index.json']+list((S/'dist/data/materials').glob('*.json'))+list((S/'data/paper-reviews').glob('*.json'))
inv['provenance']={'baseline_inventory_sha256':hashlib.sha256((O/'base-inventory-summary.json').read_bytes()).hexdigest(),'baseline_provenance':copy.deepcopy(base['provenance']),'baseline_provenance_scope':'Historical inherited inventory provenance; these nested paths and hashes are not current Gu audit inputs. The current summary hashes and canonical tree below supersede them.','corpus_summary_snapshot':base['provenance'].get('corpus_summary_snapshot'),'files_used':[str(p.relative_to(S)).replace(chr(92),'/') for p in current_inputs]+['data/records/*.json'],'summary_artifact_sha256':{str(p.relative_to(S)).replace(chr(92),'/'):hashlib.sha256(p.read_bytes()).hexdigest() for p in current_inputs}}
"""
template=template.replace(anchor,provenance_fix+anchor)
(B/'build_inventory_actual.py').write_text(template,encoding='utf8')
print('Prepared Gu inventory count builder from prior verified count derivation.')
