from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
O=Path(__file__).resolve().parent;A=O.parent/'apparatus';P=A.parents[1]
def read(p):return json.loads(p.read_text('utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
checks=read(O/'package-checks.json');runtime=read(O/'runtime-checks.json');pixels=read(O/'preview-replay.json')
bound=checks['bound_files'].copy()
for rel in ['package-checks.json','runtime-checks.json','preview-replay.json','finalize_audit.py']:bound[str((O/rel).resolve())]=sha(O/rel)
ca=P/'canonical-reader-independent-audit/independent-audit-v2.json'
assert sha(ca)=='e59bfbcec0f265178bb502b814993c40649bf57ac006ced6394648146dcad55a'
assert read(ca)['status']=='passed'
bound[str(ca.resolve())]=sha(ca)
for p,h in bound.items():assert sha(Path(p))==h,'Changed bound file '+p
manual=[
 {'scope':'Three solvent-specific routes','evidence':'Main PDF pp. 1–2, Experimental','finding':'Each route uses only its selected alcohol for both 0.1 M nitrate and 0.4 M TEA stocks and the alcohol wash. Three route realizations of one described method do not create inferred replicates. The named TEA formula conflict remains explicit.'},
 {'scope':'Stock preparation versus transferred portions','evidence':'Main pp. 1–2','finding':'Separate 100 mL nitrate and 100 mL TEA portions are shown in the receiving Erlenmeyer/burette step, without treating them as stock-preparation volumes or inventing charges, storage, numeric room temperature, or stirring speed.'},
 {'scope':'Addition and post-precipitation stirring','evidence':'Main pp. 1–2','finding':'3–4 mL/min and the separate 1 h post-precipitation hold remain distinct; no inferred total feeding duration.'},
 {'scope':'Solid isolation and filtrate branch','evidence':'Main p. 2','finding':'Whatman 42, 2.5 µm suction filtration retains powder. The 10 mL filtrate aliquot plus ammonium hydroxide is a separate diagnostic; NH4OH volume/concentration and explicit observation criterion are unreported. It is not a main-route precipitant or returned fraction.'},
 {'scope':'Washing and drying order','evidence':'Main p. 2','finding':'Alcohol wash precedes 24 h room-temperature drying, followed by acetone wash. No post-acetone drying, washing quantities/cycles, atmosphere, or vacuum setting is invented.'},
 {'scope':'Calcination versus thermogravimetry','evidence':'Main p. 2; Figure 3/main p. 3','finding':'Calcination uses 10 °C/min, 200 °C and 3 h with unknown atmosphere. Analytical TGA is separately performed in air at 10 °C/min on the as-prepared butanol context; its residual solid is not mapped to the 200 °C calcined product.'},
 {'scope':'XRD and local TEM evidence','evidence':'Main pp. 2–3; Figures 1–2','finding':'Cu Kα 1.5408 Å and named acquisition instruments are preserved. Three as-prepared alcohol specimens and the calcined-butanol TEM specimen remain separate. Local CeO2 fringes/SAED do not imply pure as-prepared bulk CeO2 or a recovered atomic structure.'},
 {'scope':'BET analysis','evidence':'Main pp. 2–3','finding':'ASAP 2010C and calcined solvent contexts are qualified. Source nitrogen adsorption interpretation is distinct from an unreported detailed gas/degassing protocol; derived spherical BET diameters are not TEM sizes.'},
 {'scope':'DSC specimen boundaries','evidence':'Main pp. 2–3; Figure 3 caption','finding':'The as-prepared butanol trace and calcined comparison are distinct; exact calcined batch identity, atmosphere, scan rate and modulation settings remain unknown.'},
 {'scope':'XPS acquisition and irradiation time','evidence':'Main pp. 2–3; SI pp. 1–3','finding':'1486.6 eV source and 160/20 eV pass energies remain acquisition settings. Four as-prepared/calcined short/long exposure contexts remain distinct. Main <15 min versus SI ~15 min/15 min and >5 h exposure are not synthesis hold durations or whole-powder composition.'},
 {'scope':'XPS fit workflow and conflicts','evidence':'SI pp. 1–3, Figure S1/Table S1','finding':'Shirley background and 50% Gaussian/50% Lorentzian model are preserved; 884.5 eV calibration versus 884.8 eV tabulation and source spectrum/spin/area-formula inconsistencies remain visible. No synthetic spectrum or recomputed oxidation fractions are introduced.'},
 {'scope':'DLS and powder packing','evidence':'Main pp. 2,4','finding':'DLS alcohol dispersions retain unknown concentration/sample prep/measurement details and radius-versus-diameter conflict. Packing is hand packing in a preweighed 1 mL pipet, not crystallographic density.'},
 {'scope':'All actual static previews','evidence':'Nine contact sheets, all 35 scene panels; preview-manifest.json','finding':'All panels actually viewed. Titles, labels, proportions and readable condition notes preserve stage-specific unknowns. Illustrative instrument geometry is identified as explanatory and does not synthesize spectra, source micrographs, or atomic coordinates.'},
 {'scope':'Source and record dispatch','evidence':'Actual frozen module execution on independent canonical reads','finding':'Exact source-group/record-ID/operation-ID selection, missing/foreign sources and unknown/nonmember operations tested. Runtime objects were recursively frozen and remained unchanged. This is a module/minimal-DOM audit, not a mounted browser test.'}
]
out={
 'schema':'mattersyn-independent-apparatus-audit/1','reviewer':'/root/peng1998_reader_assets','proposal_author':'/root/backlog_eta','source_id':'pati2009','doi':'10.1021/la8031286','created_at':datetime.now(timezone.utc).isoformat(),'status':'passed','open_findings':[],
 'proposal_freeze_sha256':sha(A/'package-freeze.json'),'module_sha256':sha(A/'pati2009-protocol.mjs'),
 'canonical_binding':{'authored_package_version':'v1','authored_package_sha256':sha(P/'canonical-proposal/v1/package-manifest.json'),'latest_passed_package_version':'v2','latest_package_sha256':sha(P/'canonical-proposal/v2/package-manifest.json'),'independent_audit_sha256':sha(ca),'all_19_record_bytes_unchanged':True,'apparatus_rewrite_needed':False,'note':'V2 changes only the reader review_scope token. The apparatus binds unchanged exact canonical record bytes; no envelope rewrite is needed.'},
 'counts':{'scenes':35,'operational_records':14,'distinct_source_operations':19,'canonical_numeric_rows':43,'display_rows':167,'contact_sheets_actually_viewed':9,'preview_panels_actually_viewed':35,'independent_pixel_replays':35,'manual_review_scopes':len(manual),'runtime_checks':runtime['checks'],'package_checks':checks['checks'],'pixel_checks':pixels['pixel_checks'],'supporting_checks':runtime['checks']+checks['checks']+pixels['pixel_checks'],'bound_files':len(bound),'final_hash_rechecks':len(bound)},
 'actual_source_reading_scope':{'main_pdf_pages':[1,2,3,4],'si_pdf_pages':[1,2,3,4],'method':'Original local rendered pages reopened and visually read for the apparatus-relevant passages, figures, and fitting table; SI page 4 bibliography inspected. This is not a repeated full extraction certification.'},
 'manual_scopes':manual,
 'independence_note':'This reviewer previously authored the source extraction. A distinct reviewer independently passed that source package. This report independently audits Backlog’s new apparatus against the original pages and frozen canonical records, and does not replace or self-certify the source extraction audit.',
 'runtime_contract_limit':'ID dispatch does not independently authenticate a modified same-ID runtime object. Exact source/canonical hashes and transported operation arrays are verified by the separate package checks; integration must preserve those bound records.',
 'gates':{'apparatus_source_and_static_visual_audit':True,'actual_pure_function_execution':True,'mounted_browser_test':False,'site_integration':False,'publication':False,'atomic_model_or_training_approval':False},
 'scope_exclusions':['No Site, ledger, source, canonical, author-package, or prior audit mutation.','No independent browser, integrated consumer, public deployment, molecular or product-coordinate approval.','No resolution of printed scientific conflicts, unknown batch identities, absent acquisition settings or unknown calcination atmosphere.'],
 'bound_files':bound}
(O/'independent-audit.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n','utf-8')
lines=['# Pati 2009 apparatus: independent audit','',f"Status: **passed**. No open apparatus finding. Frozen package `{out['proposal_freeze_sha256']}`.",'',f"Checked all 35 scenes in 14 operational records, 19 distinct source actions, 43 numeric rows and 167 display rows. All nine contact sheets / 35 panels were actually viewed. The actual module and minimal-DOM factories passed {runtime['checks']:,} checks; package/source transport passed {checks['checks']:,}; 35 independent SVG replays passed 70 dimension/pixel checks. {len(bound)} exact files are bound and rechecked at close.",'','Canonical v2 changes only the reader review-scope token. All 19 canonical records are byte-identical to v1, so the frozen apparatus remains exactly bound. The distinct canonical v2 pass is included.','','The important boundaries pass: separate solvent stocks and transfers; filtrate-only NH4OH diagnostic; source wash/dry order; unknown calcination atmosphere versus TGA air; distinct XPS irradiation/analysis contexts; local TEM evidence versus uncertain as-prepared bulk composition.','','Actual source review covered apparatus-relevant passages in main pages 1–4 and SI pages 1–4. The source extraction itself was previously authored by this reviewer and separately passed by another reviewer; this report audits Backlog’s apparatus, not the reviewer’s extraction.','','This pass is for the private apparatus source mapping, static visuals and executed functions. Mounted-browser, integrated Site, publication, molecular and atomic/training gates remain separate.','','## Manual checks','']
for m in manual:lines.extend([f"- **{m['scope']}** ({m['evidence']}): {m['finding']}",''])
(O/'independent-audit.md').write_text('\n'.join(lines),'utf-8')
print(json.dumps({'audit_sha256':sha(O/'independent-audit.json'),'checks':out['counts']['supporting_checks'],'bound_files':len(bound),'status':'passed'}))
