import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
O=Path(__file__).resolve().parent;P=O/'private'
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def receipt(role,pages,section,finding):return dict(role=role,pages=pages,section=section,finding=finding)
rows=[dict(rank=59,title='Tailoring Indium Oxide Nanocrystal Synthesis Conditions for Air-Stable High-Performance Solution-Processed Thin-Film Transistors',authors_short='Sarah L. Swisher et al.',year=2015,
 source_pairing='main/SI matching title and authors',synthesis_presence='yes_explicit_target_nanocrystal_recipe',
 method_receipts=[receipt('main',[2],'Experimental methods','Quantified In(acac)3/oleylamine degassing and argon thermal decomposition at 250 C for 4 h, followed by washing and colloidal storage.'),receipt('si',[3],'Nanocrystal synthesis','Adds vessel, solvent quantities and centrifugation/washing details to the current In2O3 procedure.')],
 structure_receipts=[receipt('main',[5],'Figures2-3 and discussion','Named 250 C air-free product is linked to TEM size 9.3 +/- 2.5 nm, HRTEM spacing, and measured XRD matching cubic In2O3 reference. Scherrer size is separately reported.')],
 link_assessment='direct_named_synthesis_condition_to_phase_and_TEM; final annealed transistor film is a distinct material state',structure_level='measured_phase_spacing_size_morphology_candidate',coordinates='not_established_from_inspected_sections',gaps=['Other synthesis-condition variants and remaining SI pages are unchecked.','The later 500 C oxygen anneal is not silently joined to as-synthesized NC measurements.'],visual_pages=[],followup='prioritize_complete_variant_and_film_state_review'),
 dict(rank=60,title='Thiol-Free Synthesized Copper Indium Sulfide Nanocrystals as Optoelectronic Quantum Dot Solids',authors_short='David So and Gerasimos Konstantatos',year=2015,
 source_pairing='main/SI matching title and authors',synthesis_presence='yes_explicit_target_recipe_and_temperature_variants',
 method_receipts=[receipt('main',[2],'Experimental section','Quantified CuI/InCl3/TOP/ODE/oleylamine synthesis, TMS injection at 170 C, 150 C growth for 15 min, distinct zinc-oleate treatment and fraction-specific purification.'),receipt('si',[2],'TableS1','Visual table confirms injection/growth/coating temperatures and washing solvent ratios across seven temperature variants; complete numeric transcription is deferred.')],
 structure_receipts=[receipt('main',[3],'Figure1 and discussion','XRD, Raman and TEM/SAXS support composition/phase/size evidence, but cubic versus tetragonal remains author-discussed ambiguity. Zinc sulfide overlap and alloying/surface-passivation interpretation are not resolved into a unique shell structure.')],
 link_assessment='temperature_series_and_named_reference_NC linked_to_characterization; exact_all_variant_measurement_links_pending',structure_level='measured_phase_ambiguous_size_morphology_candidate',coordinates='not_established_from_inspected_sections',gaps=['Do not normalize ambiguous phase into uniquely cubic or tetragonal.','Do not infer a uniform ZnS shell.','Other SI TEM/size pages and complete purification variant inventory remain unchecked.'],visual_pages=[dict(role='si',page=2,purpose='Resolve table column/row mapping and washing variants')],followup='prioritize_full_temperature_series_review_with_phase_ambiguity'),
 dict(rank=61,title='Exposing the Dynamics and Energetics of the N-Heterocyclic Carbene-Nanocrystal Interface',authors_short='Haipeng Lu et al.',year=2016,
 source_pairing='main/SI title matches; SI1 visually confirms all four authors after incomplete text extraction',synthesis_presence='yes_explicit_metal_NC_and_chalcogenide_conversion_recipes',
 method_receipts=[receipt('si',[6,7],'S3 Synthetic procedures','Quantified NHC-AgBr/CuBr reduction, isolated metal NCs, and 120 C chalcogen addition/conversion with 2:1 or 1:1 metal/chalcogen ratio, quench and workup. Powder versus redispersed colloid characterization states are explicit.')],
 structure_receipts=[receipt('main',[2],'Figure1 and discussion','Named NHC-Ag, Ag2S and Ag2Se products have measured XRD phase assignment and TEM morphology/size; Ag seed mean diameter links to chalcogenide products.'),receipt('main',[3],'Figure3 and Cu extension discussion','DFT cluster geometries/binding energies are theory, separate from experimental NC phase evidence. Copper phase assignments depend on chalcogen feed ratio; detailed SI figures not inspected.')],
 link_assessment='direct_named_route_products_to_phase_morphology; no exact finite-particle experimental atom model',structure_level='measured_phase_morphology_with_separate_theory_models',coordinates='DFT_cluster_models_are_not_measured_target_coordinates',gaps=['SI6 visually prints 0.4 C (ice bath), whereas its Cu paragraph describes Ag reduction at 0 C; preserve as source discrepancy.','Precursor/ligand synthesis upstream pages and detailed copper measurement inventory are unchecked.','Full computational-coordinate inventory unreviewed; no experimental atom claim.'],visual_pages=[dict(role='si',page=1,purpose='Confirm matching title and full authors'),dict(role='si',page=6,purpose='Check unusual 0.4 C versus 0 C printed temperature')],followup='prioritize_route_and_surface_chemistry_review_keep_theory_separate'),
 dict(rank=62,title='Synthesis and Characterization of Cu3(Sb1-xAsx)S4 Semiconducting Nanocrystal Alloys with Tunable Properties for Optoelectronic Device Applications',authors_short='Robert B. Balow et al.',year=2017,publication_note='DOI contains 2016; inspected journal pages identify volume29 (2017).',
 source_pairing='main/SI matching title and authors',synthesis_presence='yes_explicit_target_alloy_composition_series',
 method_receipts=[receipt('main',[2],'Materials and Methods; Synthesis of alloy nanocrystals','Quantified Cu/As/Sb and sulfur stock solutions, five explicit cation stock-mixing ratios, sequential anion/cation injection at 175 C, 10 min growth and fraction-specific washing.')],
 structure_receipts=[receipt('main',[2,3],'Figures1-2 and discussion','Same five named compositions have measured XRD/Raman and TEM/HRTEM/FFT size/morphology assignments. Tetragonal phase is compared with endmember reference patterns; impurity formation at different conditions is discussed.'),receipt('si',[3],'Lattice parameter calculation and FigureS3','Cell parameters derive from XRD spacings, and Raman before/after PEC is separately identified; cell metrics are not atom-position data.')],
 link_assessment='explicit_composition_recipe_series_to_named_phase_and_morphology_panels; exact_aliquot_join_not_established',structure_level='measured_phase_cell_morphology_size_candidate',coordinates='not_established; simulated diffraction pattern comparisons do not establish measured atomic coordinates',gaps=['Remaining main/SI pages, detailed composition table and PEC material-state comparison remain unreviewed.','No complete variant or impurity-condition inventory is claimed.'],visual_pages=[],followup='prioritize_complete_alloy_series_review')]
for r in rows:
 r.update(status='fast_methods_first_partial_triage',full_source_review_complete=False,scientific_admission=False,training_admission=False,automatic_exclusion=False)
 save(O/f"scope-rank{r['rank']:03d}.json",r)
d=json.loads((P/'source-inputs.json').read_text(encoding='utf-8'))
events=[json.loads(x) for x in (P/'read-events.jsonl').read_text(encoding='utf-8').splitlines()]
visual=json.loads((O/'visual-events.json').read_text())
for r in rows:
 for v in r['visual_pages']:visual.append(dict(rank=r['rank'],**v))
save(O/'visual-events.json',visual)
after={k:sha(f['source_path']) for k,f in d['files'].items()}
assert all(after[k]==f['source_sha256'] for k,f in d['files'].items())
receipts=[]
for s in d['scopes']:
 r=json.loads((O/f"scope-rank{s['rank']:03d}.json").read_text(encoding='utf-8'));r['group_id']=s['group_id'];r['source_generation']=s['generation']
 r['source_bindings']=[dict(file_key=k,role=d['files'][k]['historical_role'],source_sha256=d['files'][k]['source_sha256'],cached_text_sha256=d['files'][k]['cached_text_sha256'],source_hash_before_after_equal=True,page_count=d['files'][k]['page_count']) for k in s['file_keys']]
 for key in ['method_receipts','structure_receipts']:
  for e in r[key]:
   f=next(f for f in r['source_bindings'] if f['role']==e['role']);e.update(file_key=f['file_key'],source_sha256=f['source_sha256'],inspection_mode='cached_page_text; separately listed visual_pages identify rendered checks')
 r['coverage']={'full_cached_page_text_read':{k:sorted({e['page'] for e in events if e['file_key']==k and e['kind']=='full_cached_page_text_displayed'}) for k in s['file_keys']},'visual_pages':r['visual_pages'],'all_pages_read':False,'unchecked_SI_not_synthesis_negative':True}
 save(O/f"scope-rank{s['rank']:03d}.json",r);receipts.append(r)
now=datetime.now(timezone.utc);start=datetime.fromisoformat('2026-09-23T13:02:58+00:00')
full=[e for e in events if e['kind']=='full_cached_page_text_displayed'];ident=[e for e in events if e['kind']=='identity_excerpt_displayed'];idx=[e for e in events if e['kind']=='machine_search_index_only']
summary=dict(status='frozen_partial_methods_first_triage',started_utc=start.isoformat(),finished_utc=now.isoformat(),elapsed_seconds=(now-start).total_seconds(),timing_scope='Includes setup, source hashing, reading/viewing, receipt preparation and interruption/context overhead; selected positives only, no corpus throughput extrapolation.',scopes=10,file_copies=19,unique_source_hashes=19,original_hashes_before_after_equal=True,explicit_target_synthesis_positive=10,measured_phase_morphology_candidates=9,morphology_surface_composition_candidate_with_geometric_models=1,verified_atomic_coordinate_pairs=0,scientific_admissions=0,training_admissions=0,automatic_exclusions=0,missing_local_si_scopes=[receipts[0]['group_id']],counts=dict(full_cached_page_text_read_events=len(full),unique_full_cached_pages_read=len({(e['file_key'],e['page']) for e in full}),identity_excerpt_events=len(ident),unique_identity_sources=len({e['file_key'] for e in ident}),machine_index_page_events=sum(e['indexed_pages'] for e in idx),machine_index_is_not_human_read=True,rendered_pages_viewed=len(visual)),scope_results=[dict(rank=r['rank'],group_id=r['group_id'],title=r['title'],synthesis_presence=r['synthesis_presence'],structure_level=r['structure_level'],followup=r['followup']) for r in receipts],limitations=['Partial Methods/SI and structure triage only; no full-paper extraction, exact aliquot join or atomic-coordinate absence proof.','Historical cached text has current text hash and historically recorded source hash; current original PDF hashes verified before/after. Selected original visual checks are explicitly listed.','The nine local main/SI pairings are content matched; rank53 has no local SI in frozen inputs.','All remaining SI/source pages are unchecked, never treated as synthesis-negative.'])
save(O/'summary.json',summary);save(O/'progress.json',dict(phase='frozen',receipts_completed=10,started_utc=start.isoformat(),finished_utc=now.isoformat()))
save(O/'private/source-hash-after.json',after)
(O/'README.md').write_text('# Phase batch 01: partial Methods-first triage\n\nTen scopes (ranks 53–62) have explicit target synthesis in inspected Methods/SI. Nine retain measured phase/morphology nominations; the PbSe surface-chemistry paper is narrowed to morphology/composition and geometric models. None is an admitted scientific/training pair or a verified measured atomic-coordinate pair.\n\nSee summary.json for timing and actual read/view counts, selection-manifest.json for eligibility and skips, and one concise receipt per scope. Missing or unchecked SI is not negative evidence. Exact source hashes are attached to receipts; raw caches and page renders stay private.\n\nFull extraction, all variant/source coverage and exact sample/aliquot joins remain future work. This deliberately selected positive batch cannot establish corpus throughput.\n',encoding='utf-8')
freeze=dict(frozen_utc=now.isoformat(),scope='author freeze; partial source triage only',files={str(p.relative_to(O)).replace('\\','/'):sha(p) for p in sorted(O.rglob('*')) if p.is_file() and p.name!='author-freeze.json'},scientific_admission=False,training_admission=False)
save(O/'author-freeze.json',freeze);print(json.dumps({'summary':summary,'freeze_sha256':sha(O/'author-freeze.json')},ensure_ascii=False,indent=2))
