REFS=[
('Dresselhaus, M. S.; Dresselhaus, G.; Avouris, P. Carbon Nanotubes: Synthesis, Structure, Properties, and Applications; Springer-Verlag: New York, 2001.','General nanotube properties and applications.'),
('Mitchell, G. P.; Mirkin, C. A.; Letsinger, R. L. J. Am. Chem. Soc. 1999, 121, 8122.','Biological recognition in assembly.'),
('Yang, Y.; Huang, S.; He, H.; Mau, A. W. H.; Dai, L. J. Am. Chem. Soc. 1999, 121, 10832.','Recognition and assembly strategies.'),
('Sano, M.; Kamino, A.; Okamura, J.; Shinkai, S. Nano Lett. 2002, 2, 531.','Supramolecular hierarchical assemblies.'),
('Cassell, A. M.; McCool, G. C.; Ng, H. T.; Koehne, J. E.; Chen, B.; Li, J.; Han, J.; Meyyappan, M. Appl. Phys. Lett. 2003, 82, 817.','Nanotube network formation.'),
('Zhang, Z.; Wei, B.; Ajayan, P. M. Chem. Commun. 2002, 9, 962.','Nanotube network formation; citation format preserved.'),
('Choi, K. H.; Bourgoin, J. P.; Auvray, S.; Esteve, D.; Duesberg, G. S.; Roth, S.; Burghard, M. Surf. Sci. 2000, 462, 195.','Patterned-substrate nanotube assembly.'),
('Lewenstein, J. C.; Burgin, T. P.; Ribayroi, A.; Nagahara, L. A.; Tsui, R. K. Nano Lett. 2002, 2, 443.','Patterned-substrate assembly; spelling as printed.'),
('Wei, B. Q.; Vajtai, R.; Jung, Y.; Ward, J.; Zhang, R.; Ramanath, G.; Ajayan, P. M. Nature 2002, 416, 495.','Patterned nanotube growth.'),
('Avouris, P. Acc. Chem. Res. 2002, 35, 1026.','Nanotube device applications.'),
('Huynh, W. U.; Dittmer, J. J.; Alivisatos, A. P. Science 2002, 295, 2425.','Photovoltaic motivation and charge separation.'),
('Kong, J.; Franklin, N. R.; Zhou, C.; Chapline, M. G.; Peng, S.; Cho, K.; Dai, H. Science 2000, 287, 622.','Nanotube sensing context.'),
('Hirsch, A. Angew. Chem., Int. Ed. 2002, 41, 1853. Banerjee, S.; Kahn, M. G. C.; Wong, S. S. Chem. Eur. J. 2003, 9, 1898.','Two cited works in one numbered entry: nanotube functionalization chemistry.'),
('Sinnott, S. B. J. Nanosci. Nanotechnol. 2002, 2, 113.','Nanotube derivatization and property preservation.'),
('Bahr, J.; Tour, J. M. J. Mater. Chem. 2002, 12, 195.','Nanotube chemistry background.'),
('Bahr, J. L.; Yang, J.; Kosynkin, D. V.; Broniskowski, M. J.; Smalley, R. E.; Tour, J. M. J. Am. Chem. Soc. 2001, 123, 6536.','Covalent modification of nanotube sidewalls.'),
('Georgakilas, V.; Kordatos, K.; Prato, M.; Guldi, D. M.; Holzinger, M.; Hirsch, A. J. Am. Chem. Soc. 2002, 124, 760.','Covalent nanotube chemistry.'),
('Mickelson, E. T.; Huffman, C. B.; Rinzler, A. G.; Smalley, R. E.; Hauge, R. H.; Margrave, J. L. Chem. Phys. Lett. 1998, 296, 188.','Covalent nanotube functionalization.'),
('Chen, R. J.; Zhang, Y.; Wang, D.; Dai, H. J. Am. Chem. Soc. 2001, 123, 3838.','Noncovalent π-stacking context.'),
('Chen, J.; Hamon, M. A.; Hu, H.; Chen, Y.; Rao, A. M.; Eklund, P. C.; Haddon, R. C. Science 1998, 282, 95.','End/defect functionality chemistry.'),
('O’Connell, M.; Boul, P.; Ericson, L. M.; Huffman, C.; Wang, Y.; Haroz, E.; Kuper, C.; Tour, J.; Ausman, K. D.; Smalley, R. E. Chem. Phys. Lett. 2001, 342, 265.','Macromolecular wrapping.'),
('Riggs, J. E.; Guo, Z.; Carroll, D. L.; Sun, Y.-P. J. Am. Chem. Soc. 2000, 122, 5879.','Macromolecular nanotube modification.'),
('Star, A.; Stoddart, J. F.; Steurman, D.; Diehl, M.; Boukai, A.; Wong, E. W.; Yang, X.; Chung, S.-W.; Choi, H.; Heath, J. R. Angew. Chem., Int. Ed. 2001, 40, 1721.','Macromolecular wrapping; names retained as printed.'),
('Zhang, Y.; Suenaga, K.; Colliex, C.; Iijima, S. Science 1998, 281, 973.','BN/nanotube heterostructure context.'),
('Suenaga, K.; Colliex, C.; Demoncy, N.; Loiseau, A.; Pascard, H.; Willaime, F. Science 1997, 278, 653.','Coaxial BN growth.'),
('Zhang, Y.; Ichihashi, T.; Landree, E.; Nihey, F.; Iijima, S. Science 1999, 285, 1719.','Solid-state carbide-related heterostructures.'),
('Hu, J.; Ouyang, M.; Yang, P.; Lieber, C. M. Nature 1999, 399, 48.','Si nanowire/nanotube growth.'),
('Banerjee, S.; Wong, S. S. Nano Lett. 2002, 2, 195.','Earlier CdSe/TiO₂ attachment and amide-coupling comparison.'),
('Ravindran, S.; Chaudhary, S.; Colburn, B.; Ozkan, M.; Ozkan, C. S. Nano Lett. 2003, 3, 447.','Analogous coupled nanotube–nanocrystal systems.'),
('Haremza, J. M.; Hahn, M. A.; Krauss, T. D.; Chen, S.; Calcines, J. Nano Lett. 2002, 2, 1253.','Analogous attachment methods.'),
('Azamian, R.; Coleman, K.; Davis, J.; Hanson, N.; Green, M. Chem. Commun. 2002, 366.','Analogous attachment methods; source author initials retained.'),
('Banerjee, S.; Wong, S. S. Nano Lett. 2002, 2, 49.','Nanotubes as bulky metal-coordination ligands.'),
('Banerjee, S.; Wong, S. S. J. Am. Chem. Soc. 2002, 124, 8940.','Metal coordination, catalysis and steric effects.'),
('Frehill, F.; Vos, J. G.; Benrezzak, S.; Koos, A. A.; Konya, Z.; Ruther, M. G.; Blau, W. J.; Fonseca, A.; Nagy, J. B.; Biro, L. P.; Minett, A. I.; in Het Panhuis, M. J. Am. Chem. Soc. 2002, 124, 13694.','Ruthenium-functionalized nanotube interconnects.'),
('Hiura, H.; Ebbesen, T. W.; Tanigaki, K. Adv. Mater. (Weinheim, Ger.) 1995, 7, 275.','Referenced oxidative purification/functionalization method; external conditions not imported.'),
('Peng, Z. A.; Peng, X. J. Am. Chem. Soc. 2001, 123, 183.','CdO-based one-pot nanocrystal procedure modified for this experiment.'),
('Peng, Z. A.; Peng, X. J. Am. Chem. Soc. 2002, 124, 3343.','CdO-based synthesis and cadmium–phosphonic-acid growth context.'),
('Ajayan, P. M.; Ebbesen, T. W.; Ichihashi, T.; Iijima, S.; Tanigaki, K.; Hiura, H. Nature 1993, 361, 333.','Tip curvature/reactivity context.'),
('Yao, N.; Lordi, V.; Ma, S. X. C.; Dujardin, E.; Krishnan, A.; Treacy, M. M. J.; Ebbesen, T. W. J. Mater. Res. 1998, 13, 2432.','Acid etching at nanotube tips and walls.'),
('Peng, Z. A.; Peng, X. J. Am. Chem. Soc. 2001, 123, 1389.','Diffusion-limited anisotropic growth interpretation.'),
('Rolo, A. G.; Vasilevskiy, M. I.; Gaponik, N. P.; Rogach, A. L.; Gomes, M. J. M. Phys. Status Solidi B 2002, 229, 433.','CdTe-cluster Raman shift/broadening comparison.'),
('Rao, A. M.; Richter, E.; Bandow, S.; Chase, B.; Eklund, P. C.; Williams, K. A.; Fang, S.; Subbaswamy, K. R.; Menon, M.; Thess, A.; Smalley, R. E.; Dresselhaus, G.; Dresselhaus, M. S. Science 1997, 275, 187.','Nanotube Raman mode context.'),
('Banerjee, S.; Wong, S. S. J. Phys. Chem. B 2002, 106, 12144.','Future oxidative-protocol control.'),
]
referenced=[]
for n,(bib,context) in enumerate(REFS,1):
 page=1 if n<=22 else 2 if n<=37 else 6 if n<=39 else 7 if n==40 else 8 if n==41 else 9
 item('sources',f'reference-{n:02}',f'Reference {n}',bib+' '+context,page,f'References, entry {n}',scope='cited_context',kind='source_reference',notes=['Bibliographic entry inspected in the supplied article; external full text not independently inspected in this review.'])
 referenced.append({'id':f'reference-{n}','reference_number':n,'bibliography':[bib],'context':context,'cited_work_independently_reviewed_in_this_task':False,'import_experimental_evidence':False,'source_locators':[ev(page,f'References, entry {n}')['locator']]})
