assets={a['id']:a for a in manifest['assets']}
groups={'figures':[],'tables':[],'schemes':[],'equations':[],'source_notes':[]}
def asset(key,group,caption,scope,records,classification,notes=(),panels=(),rows=None,axes=()):
 a=assets[key];e=ev(a['source_pdf_page'],a['label'])
 d={'id':key,'label':a['label'],'document_role':'main','page':a['source_pdf_page'],'printed_page':e['printed_page'],'source_locators':[e['locator']],'caption_paraphrase':caption,'sample_scope':scope,'sample_links':[P+r for r in records],'sample_linkage':'Explicit source cohort association only; a color name does not identify the same physical batch across different experiments.','evidence_class':classification,'public_asset':a['public_asset'],'public_asset_sha256':a['sha256'],'asset_provenance':{'source_file':a['source_filename'],'source_sha256':a['source_sha256'],'source_pdf_page':a['source_pdf_page'],'crop_bbox_pdf_points_top_left':a['crop_bbox_pdf_points_top_left'],'crop_normalized':a['crop_normalized'],'render_dpi':a['render_dpi'],'pixel_dimensions':a['pixel_dimensions'],'renderer':'PDFium 300 dpi original-source crop','transformation':a['transformation']},'quantitative_context':list(notes),'panels':list(panels),'notes':list(notes),'axes':list(axes),'text_reviewed':True,'visual_reviewed':True,'reviewed':False,'reader_render_verified':False,'training_eligible':False,'source_asset_type':a['source_asset_type']}
 if rows is not None:d['structured_rows']=rows
 groups[group].append(d)
asset('figure-1','figures','Original mechanism schematic for TOPO displacement, silane hydrolysis/condensation and later functionalization.','Source mechanism schematic; not an experimentally solved atomic shell.',['silica-silanization','silanization-mechanism'],'author_mechanism_schematic',['The source explicitly depicts hydrolyzed MPS for convenience, not the purchased trimethoxy precursor.','Functional groups include thiol, amine and phosphonate; the final quench step is not drawn.','Phosphonate drawing connects propyl–P(=O)(O−)–CH₃; its complete stock identity and counterion are unresolved.'],['Ligand exchange','Hydrolysis and crosslinking','Surface functional groups'])
asset('figure-2','figures','Original normalized absorption and photoluminescence across five emission-color cohorts, with a green-parent comparison.','Optical cohorts only; not automatically Table 2 physical specimens.',['optical-properties'],'experimental',['Top: absorption; blue omitted because no resolved absorption feature above approximately 450 nm.','Bottom: emission, blue/green/yellow/orange/red.','Inset: green silanized in aqueous buffer, solid; TOPO-coated parent in toluene, dashed.','Figure caption says 10 mM PBS whereas optical method says PB; added NaCl is not inferred.'],['Normalized absorption','Normalized emission','Green parent/coated comparison'],axes=['Wavelength (nm), labeled ticks 480–720','Relative absorption (arbitrary units)','Relative fluorescence (arbitrary units)'])
asset('table-1','tables','Five optical-color cohorts with reported absorption, emission, absolute quantum yield and relative retained yield.','Table 1 optical cohort identities only; blue missing values remain null.',['optical-properties'],'experimental_table',['All table columns, five rows and footnote retained.','Blue absorption and quantum yields are not reported, not zero.','Green/yellow table emission 544/576 nm conflicts with prose 542/572 nm.'],rows=[{'color':c,'absorption_nm':a,'emission_nm':e,'quantum_yield_percent':q,'relative_quantum_yield_percent':r,'canonical_record_id':P+'optical-properties'} for c,a,e,q,r in [('blue',None,504,None,None),('green',522,544,18,81),('yellow',560,576,12,66),('orange',576,595,9,60),('red',620,644,5,71)]])
asset('figure-3','figures','Fluorescence over one month for green, orange and red silanized quantum dots in 10 mM PB.','Storage/periodic-excitation cohorts; normalized fluorescence, not absolute quantum yield.',['storage-photostability'],'experimental',['Green 544 nm; orange 595 nm; red 644 nm.','Daily excitation; methods average four subsequent measurements and normalize to day one.','Error bars and fitted source lines retained; no digitized numerical trajectory invented.'],['Green','Orange','Red'],axes=['Day, 0–30','Relative fluorescence intensity'])
asset('figure-4','figures','Continuous-wave illumination comparison of silanized nanocrystals and rhodamine 6G.','CW optical comparison; color-coded emission cohorts, R6G black.',['cw-photostability'],'experimental',['0.5 mW Ar⁺ illumination; stated spot size 700 µm; approximately 1 µL sample; OD 0.065 at 488 nm.','Caption claims stability for at least approximately 4 h and R6G bleaching after approximately 10 min.','Actual plot ends at 4,000 s; no 4 h curve extension has been fabricated.','Initial brightening is normalized intensity, not 120–200% absolute quantum yield.'],axes=['Time (s), 0–4,000','Normalized intensity, 0–2.0'])
asset('figure-5','figures','Yellow parent-particle TEM diameter histogram and silica/MPA coating AFM height histograms.','Explicit common yellow parent for the three displayed states.',['size-yellow'],'experimental_distribution',['Top: plain CdSe/ZnS TEM; middle: silanized AFM; bottom: MPA-coated AFM.','AFM measures height although source x-axis says diameter.','Caption and note 27 exclude features below the corresponding core/shell diameter; raw all-feature histograms are not supplied.','No exact numeric bin frequencies are reconstructed.'],['Core/shell TEM','Silica-coated AFM','MPA-coated AFM'],axes=['Source label diameter (nm), 0–20; AFM quantity is height','Frequency'])
asset('table-2','tables','Size comparison for four linked core/core-shell/silica/MPA color cohorts.','Links within each Table 2 row; no assumed join to Table 1 optical cohorts.',['size-green','size-yellow','size-red','size-dark-red'],'experimental_table',['All four rows, column labels and shell-thickness footnote preserved.','The coating measurement is AFM height, not a directly imaged shell diameter.','Shell thickness is defined as half the AFM–TEM size difference; author approximations are not atomically resolved uniform layers.'],rows=[{'color':c,'core_tem_nm':a,'core_shell_tem_nm':b,'silica_afm_nm':s,'mpa_afm_nm':m,'canonical_record_id':P+'size-'+c} for c,a,b,s,m in [('green',2.7,4.2,6,5),('yellow',3.1,4.4,9,5),('red',4.1,5.6,14,9),('dark-red',4.8,6.4,17,12)]])
asset('figure-6','figures','Two green-parent silanization preparations compared by HPLC and gel mobility.','Blue standard and red additionally purified preparations from the same green parent; not proven same aliquot before/after.',['hplc-acquisition','hplc-purification'],'experimental',['UV detection at 210 nm; sample OD approximately 0.1.','Blue peaks near 13, 15 and 21 min have 8%, 49% and 43% total detector area in prose. Only the middle fraction fluoresces.','Nonfluorescent small-component assignment to siloxane is tentative.','Red uses further MWCO 100,000 dialysis and repeated NAP 10 columns.','Inset: 1% gel, 10 mM PB, pH 7.2, 40 min, 50 V; scale bar 5 mm; dotted loading line.'],['Chromatograms','Gel inset, R and B'],axes=['Time (min), 0–approximately 27','UV absorption, no numerical ordinate scale printed'])
asset('figure-7','figures','Original pH stability, salt stability and electrophoretic band-narrowing comparisons.','Panel-specific source cohorts; shared parent relationship is stated for coating comparisons only.',['gel-ph-stability','gel-salt-stability','gel-band-narrowing'],'experimental',['All scale bars 1 cm.','a: green/yellow/red, MPA/silanized; pH 5.4 and 7.2, no NaCl; 1% gel, 1 h, 75 V. Red lanes were contrast-enhanced by source authors.','b: green MPA/silanized, pH 7.3; 5 h incubation, 0–1,000 mM NaCl; 1% gel, 30 min, 100 V. Image adds a 2 mM lane omitted by methods.','c: original versus narrowed green band; image pH 8.5, caption approximately 8.6; 50 mM TBE, 1% gel, 1 h.'],['a1: pH 5.4','a2: pH 7.2','b1: green MPA salt series','b2: green silica salt series','c: band narrowing'],axes=['Gel lane identities and migration direction; no calibrated charge axis','NaCl series (mM): 0, 1, 2, 5, 10, 20, 50, 100, 200, 500, 1,000'])
asset('note-27-start','source_notes','First column of note 27 describing low-height AFM features.','Source analysis note, continued in next crop.',['afm-acquisition','surface-interpretation'],'direct_source_note',['Read together with note-27-continuation.'])
asset('note-27-continuation','source_notes','Continuation of note 27: attribution and omission of low-height features.','Exclusion and interpretation of AFM data, not an independent chemical identification.',['afm-acquisition','surface-interpretation'],'direct_source_note',['0.5–2 nm features attributed to silica complexes and residual ZnS.','Displayed histogram excludes heights below corresponding core/shell diameter.'])
asset('note-28','source_notes','Source diagnostic comparisons supporting possible residual ZnS particles.','No-CdSe control and aged stock, not a fully specified ZnS synthesis.',['upstream-controls'],'direct_source_note',['No exact precursor concentrations, injection temperature or reaction time are supplied.','UV spectra discussed here are not displayed and are not reconstructed.'])
asset('note-34','source_notes','Qualitative scattering comparison during ligand exchange.','Source optical aggregation diagnostic, not a calibrated size measurement.',['upstream-controls'],'direct_source_note',['Approximately 100-fold scattering increase in methanol versus toluene for TOPO-coated particles.','MPS-primed particles in methanol show no corresponding scattering.'])
asset('silanization-start','source_notes','Initial precipitation and MPS charging from the original Methods.','Typical downstream coating route, continued in the next crop.',['silica-silanization'],'direct_source_method',['1 mL starting dispersion with OD approximately 2; wet precipitate dissolved in 50 µL MPS.'])
asset('silanization-continuation','source_notes','Original priming, crosslinking, quenching, purification and aqueous-transfer sequence.','Complete main-text continuation with original numeric conditions and conflicts.',['silica-silanization'],'direct_source_method',['Original 0.22 mm optional filter wording retained.','20,000×g final clarification retains supernatant; earlier primary stock precipitation is a separate operation.','TMAH solution molarity and stirring speed are unreported.'])
asset('mpa-coating','source_notes','Original MPA exchange and recovery procedure.','Separate MPA downstream coating route.',['mpa-exchange'],'direct_source_method',['First recovery centrifugation retains precipitate; final clarification retains supernatant.','NAP cleanup is optional.'])
asset('reagent-inventory','source_notes','Original chemicals, buffers and purification materials list.','Source inventory and catalog identities, not a new stock preparation.',['core-shell-stock','silica-silanization','mpa-exchange','buffer-exchange'],'direct_source_inventory',['Original 0.45 mm materials-list filter unit retained alongside the protocol’s 0.45 µm wording.','42 wt/wt% phosphonate solution; no TMAH stock molarity.'])
