# Scientific details and conflicts checked against the independently compiled unit inventory.
items['identity']['text']+=' The July 6, 2026 download watermark is not a publication or experiment date. This article is part of the Royce W. Murray Festschrift; correspondence marks, copyright and sharing notices are administrative metadata.'
items['structure-scope']['text']+=' The abstract describes CdSe cores of 2–5 nm and study-wide overall coated sizes of 6–17 nm. The introduction describes silica shells of about 2–5 nm, while the abstract and discussion summarize about 1–5 nm; these are differently scoped summaries.'
items['silica-prime']['text']+=' The typical procedure is said to be scalable and applicable to CdSe/ZnS sizes of approximately 2–8 nm; this applicability range is not the measured size of every tabulated sample.'
items['chemical-phosphonate']['text']+=' Figure 1 draws propyl–P(=O)(O−)–CH₃, whereas the reagent name says methylphosphonate. This source-specific name/drawing ambiguity leaves the complete stock formula and counterion unresolved; a P–O–CH₃ linkage is not silently imposed.'
more('chemical-phosphonate',3,'Figure 1 functional-group drawing')
items['silica-finish']['text']+=' Discussion describes storage in air and light with stability for months, without supplying a unique storage temperature, container or concentration for that observation.'
more('silica-finish',9,'Discussion, final aqueous dispersion')
items['optical-overview']['text']+=' The emission remains symmetric rather than showing a dye-like red tail. The original labeled wavelength ticks span 480–720 nm; the absorption axis is 0–1.6 arbitrary units and emission 0–1.0.'
items['optical-width']['text']+=' Typical retained quantum yield is described as 60–80%, while Table 1 preserves a green value of 81%; the approximate prose range does not override the row.'
items['afm-results']['text']+=' The authors summarize coating-associated height increments as approximately 2, 4, 8 and 10 nm for green through dark red, rather than exact subtraction from rounded table values.'
items['si-microscopy']['text']+=' The described observation is at an edge of a lacey-carbon film; imaging is difficult against ultrathin carbon for core/shell particles below 7 nm, and proposed porosity remains an interpretation.'
items['afm-exclusions']['text']+=' The published yellow AFM distribution still visibly includes roughly 3–4 nm features below its 4.4 nm core/shell TEM diameter. The reported cutoff is therefore preserved as a claim, not certified as uniformly applied to the image.'
more('afm-exclusions',6,'Figure 5 visible features and caption')
items['figure5-yellow']['text']+=' Frequency ticks reach 30 for TEM, 60 for silanized AFM and 70 for MPA AFM.'
items['hplc-three']['text']+=' The fractions were separately collected and examined by epifluorescence microscopy; the chromatography itself uses a UV detector, not a simultaneous fluorescence detector. The original labeled time ticks run 0–25 min, with the trace extending slightly beyond.'
items['shell-thickness']['text']+=' The source also says thickness below 5 nm while listing approximately 5 nm for dark red; this approximate boundary wording is retained rather than turned into an exact strict limit.'
items['column-chemistry']['text']+=' Discussion permits either 10 mM PB at pH approximately 7 or 18 MΩ water as the G25 equilibration medium, with roughly 2 mL sample loaded and 3 mL fluorescent eluate collected. It describes 2–3 mL after concentration rather than the approximately 2 mL Methods value.'
items['equilibration']['text']+=' Discussion permits rotary evaporation or a Schlenk line and explicitly describes at least 24 h under N₂ after concentration; no separate Schlenk-line temperature or vacuum level is provided.'
items['surface-chemistry']['text']+=' Same-size pure silica spheres cannot be excluded even after optional dialysis. The number of phosphonate groups is unknown, and no measured zeta potential or surface charge density is supplied.'
items['gel-charge']['text']+=' Different emission colors have similar broad migration positions; band location alone does not resolve color-dependent crystal dimensions.'
item('intuition','background-quantitative','Scope of the cited optical background','The introduction cites wet-chemical nanocrystals about 1.5–8 nm, increasing confinement energy as size decreases, broad continuum absorption and narrow approximately excitation-independent emission. Cited higher-band-gap shell passivation yields 50–70% quantum efficiency in earlier work, not the present silica-coated cohort. Prior dye lifetimes below 5 ns and semiconductor lifetimes around 30–100 ns motivate time-gated detection; no present time-resolved lifetime measurement is reported.',1,'Introduction, references 1–18',['literature-context'],'cited_context')
item('intuition','silica-literature','Silica-growth context and earlier optical losses','The discussion cites alkaline TEOS hydrolysis/polycondensation in ethanol (reference 31) and coatings of Au, Ag, CdS, CdTe, CdSe and CdSe/CdS (references 19, 20, 23, 32 and 33). Earlier aqueous coating routes are described as giving roughly 40–80 nm shells and trapped-state emission; a cited CdSe/CdS silica system lost fluorescence about twentyfold. These contextual systems are not additional current syntheses or interchangeable controls.',8,'Discussion, prior silica methods',['literature-context'],'cited_context')
more('silica-literature',9,'Discussion, prior optical comparison')
item('structures','afm-cross-reference-conflict','AFM discussion cross-reference and feature-order errors','The discussion refers to AFM data in Figure 4 even though the distributions are Figure 5. Its initial wording reverses the one/two-feature assignments, while subsequent sentences and the actual distributions describe two features for silica and one broad feature for MPA. The original figure and detailed interpretation are retained, with this prose error explicit.',9,'Discussion, particle-size paragraph',['surface-interpretation'],'curator_interpretation','source_evidence_conflict')
item('intuition','hplc-outlook','Further size-resolution methods proposed','The authors propose an elution model to obtain quantitative HPLC size distributions and simultaneous fluorescence/absorption to distinguish nanocrystal-containing particles from silica. These measurements were not already performed in the plotted UV-only chromatogram. They argue that unstable partially coated particles would be lost during workup, but that selection argument does not prove a uniform, complete shell.',10,'Discussion, HPLC limitations and coverage argument',['surface-interpretation'],'author_outlook','author_outlook')
item('sources','study-summary','Conclusions within their experimental scope','The paper concludes that silica-coated particles retain blue-to-dark-red emission, about 32 nm widths and useful stability over months of storage and hours of illumination. Its phrase quantum yields of a few tens of percent does not replace the exact Table 1 values of 5–18%. The abstract’s physiological-salt claim above 150 mM and introductory stability through 200 mM summarize selected cohorts. MPA exchange is easier, while silica shows better buffer robustness in the comparisons. Recent DNA coupling and programmable assemblies remain future context without a new quantified protocol here.',10,'Conclusions',['literature-context'],'source_cohort')
more('study-summary',1,'Abstract stability statement');more('study-summary',2,'Introduction, salt-stability summary')
