"""Freeze a passed private author package without promoting any review status."""
from pathlib import Path
import json,hashlib,datetime
O=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
entries=read(O/'registry-additions.json')['entries']
visual={'status':'author_visual_inspection_completed','reviewer':'/root/peng1998_reader_assets','scope':'All 42 actual SVG renderings viewed on seven contact sheets; chemical layouts 1–3 were re-viewed after explicit-H suppression and translation correction. All eight model JSON conformers viewed in XY/XZ/YZ projection. This is author inspection, not independent audit or live WebGL validation.','depictions':[{'id':e['id'],'svg_sha256':sha(O/e['svgPath']),'render_sha256':sha(O/'review'/f'{e["id"]}.png'),'findings':'No remaining clipping, incomplete formula or source-specific grade/identity contamination found in the inspected depiction.'} for e in entries],'conformers':[{'id':e['id'],'model_sha256':sha(O/e['model3dPath']),'projection_path':f'review/{e["id"]}-3d-projections.png','projection_sha256':sha(O/'review'/f'{e["id"]}-3d-projections.png'),'scope':'Reference atom/bond geometry only; not a measured source conformation.'} for e in entries if e.get('model3dPath')],'resolved_author_findings':['Nested-SVG offset was replaced by a translated group to avoid renderer-specific positioning errors.','Dense explicit-H 2D depictions were converted to standard skeletal layouts; all stereochemical/reference graphs remain verified.','Unresolved polymer end-group labels were split across two lines.','Legacy source names and grade/template notes were removed from all new displayed metadata.'],'browser_interaction_verified':False,'independent_scientific_audit':'pending'}
write(O/'author-visual-inspection.json',visual)
qualification={'schema':'mattersyn-chemical-reference-author-qualification/1','status':'author_qualified_pending_independent_audit','scope':'Reference identities only. No new paper, physical specimen measurement or recipe condition is imported from external chemical references.','references':[{'material_id':mid,'pubchem_cid':cid,'qualification':desc} for mid,cid,desc in [('na2s',14804,'Formal Na2S composition with disconnected 2Na+ and S2−; hydration unknown in source.'),('nabh4',4311764,'Formal Na+ / BH4− connectivity; four explicit B–H bonds, no Na–B bond.'),('eo',6354,'Three-membered cyclic ether; 2D/3D SDF graphs agree.'),('ama',17869,'2-(Dimethylamino)ethyl methacrylate reference; source PAMA identity interpretation is labeled.'),('pdp-alcohol',140135,'3,3-Diethoxypropan-1-ol; explicit interpretation of corresponding alcohol for named PDP.'),('biocytin-hydrazide',128197,'N6-biotinyl-L-lysine hydrazide reference with four specified stereocenters. Not free biotin, biocytin, or short biotin hydrazide.')]],'manufacturer_identity_check':{'url':'https://documents.thermofisher.com/TFS-Assets/LSG/manuals/MAN0016370_2160451_EZ_Link_Hydrazide_Biocytin_UG.pdf','scope':'Primary manual identity and molecular-weight metadata read via web; no reaction, storage, concentration or spacer-length claim transferred into Nagasaki data. Primary PDF screenshot request failed, so no manual-diagram pixel comparison is claimed. The actual reference graph is bound to retained PubChem properties and SDF files.','web_read_date':'2026-09-19','product_number':28020},'source_name_interpretations':[{'material_id':'pdp','status':'formal name-derived components; no exact external salt record','formula':'C7H15KO3','basis':'Named potassium 3,3-diethoxypropanolate and alcohol reference CID 140135; formal removal of terminal alcohol H and addition of disconnected K+.','has3d':False},{'material_id':'potassium-naphthalene','status':'exact electronic-state/connectivity reference unresolved','depiction':'Literal source-name card only; no invented neutral naphthalene equivalence or metal–arene geometry.'}],'all_unreported_hydration_and_source_formula_fields_preserved':True,'independent_audit':'pending'}
write(O/'reference-author-qualification.json',qualification)
if __name__=='__main__':
 print('Saved author visual/reference qualification notes. Run both validators, then use --final to freeze.')
 import sys
 if '--final' in sys.argv:
  a=read(O/'author-validation.json');v=read(O/'viewer-author-smoke-check.json');assert a['status']==v['status']=='passed'
  manifest={'schema':'mattersyn-private-component-package/1','source_id':'nagasaki2004','status':'frozen_authored_pending_independent_scientific_audit','frozen_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'counts':{'entries':42,'material_slots':61,'stocks':2,'svg_assets':42,'models_2d':14,'models_3d':8,'author_checks':a['counts']['checks'],'viewer_smoke_checks':v['counts']['checks']},'scientific_input_hashes':read(O/'input-hashes-before.json'),'bound_files':{str(p.relative_to(O)):sha(p) for p in sorted(O.rglob('*')) if p.is_file() and p.name!='package-freeze.json'},'site_or_ledger_modified':False,'frozen_source_canonical_reader_modified':False,'independent_audit':'pending','binding_approved':False,'published':False,'eligible_training':False,'remaining_gates':['Distinct chemical/source-slot scientific audit.','Promotion-aware Site integration and source-bound display audit.','Live browser/WebGL/2D zoom/slot and stock selector checks.','Any CdS crystal reference is separately qualified and not supplied here.']}
  write(O/'package-freeze.json',manifest);print('package-freeze.json',sha(O/'package-freeze.json'))
