assets={a['id']:a for a in manifest['assets']}
groups={'figures':[],'tables':[],'schemes':[],'equations':[],'source_notes':[]}
def asset(key,group,caption,scope,records,classification,notes=(),panels=(),rows=None,axes=()):
 a=assets[key];e=ev(a['source_pdf_page'],a['label'])
 d={'id':key,'label':a['label'],'document_role':'main','page':a['source_pdf_page'],'printed_page':e['printed_page'],'source_locators':[e['locator']],'caption_paraphrase':caption,'sample_scope':scope,'sample_links':[P+r for r in records],'sample_linkage':'Explicit source cohort association only; repeated initial spectra do not identify the same physical batch across systems.','evidence_class':classification,'public_asset':a['public_asset'],'public_asset_sha256':a['sha256'],'asset_provenance':{'source_file':a['source_filename'],'source_sha256':a['source_sha256'],'source_pdf_page':a['source_pdf_page'],'crop_bbox_pdf_points_top_left':a['crop_bbox_pdf_points_top_left'],'crop_normalized':a['crop_normalized'],'render_dpi':a['render_dpi'],'pixel_dimensions':a['pixel_dimensions'],'renderer':'PDFium 300 dpi original-source crop','transformation':a['transformation']},'quantitative_context':list(notes),'panels':list(panels),'notes':list(notes),'axes':list(axes),'text_reviewed':True,'visual_reviewed':True,'reviewed':False,'reader_render_verified':False,'training_eligible':False,'source_asset_type':a['source_asset_type']}
 if rows is not None:d['structured_rows']=rows
 groups[group].append(d)
asset('figure-1','figures','Source architecture and potential/wavefunction sketches for a single-layer well, a double-layer well and two separated wells.','Three source layer architectures; drawings and cited functions are schematic, not current microscopy or computed atomic coordinates.',ROUTES+['chemical-interpretation'],'author_structure_schematic',['CdS green, HgS red. All displayed cores are 3.2 nm; this conflicts with the 3.5 nm step-A endpoint.','Nominal HgS thickness is 0.4 nm in I, 0.8 nm in II, and two 0.4 nm wells separated by 0.8 nm CdS in III; all CdS caps are 0.4 nm.','Caption attributes wavefunctions to reference 18; the body explicitly says no lowest-exciton-energy calculation is available for this system III.','Cited tetrahedral 111-facet morphology does not make these circles measured spherical particles.'],['I: one monolayer well','II: one contiguous double-layer well','III: two separated monolayer wells'],axes=['Radius (nm), ticks 0, 1, 2, 3','Potential and wavefunction sketches: no calibrated numerical ordinate'])
asset('figure-2','figures','Original stage-resolved absorption spectra for the three layer sequences.','I, II and III source stages; identical initial spectra do not prove a common physical batch.',ROUTES,'experimental',['Initial CdS absorption feature is stated as 470 nm.','I has a–c; II has a–e; III has a–f. III curve d follows both extra C steps; no intermediate two-CdS-layer spectrum is separately labeled.','The source compares lowest-transition oscillator strength but does not supply an independent concentration-normalization or integration procedure.','Original curves and full caption retained; no raw point arrays reconstructed.'],['I: a core, b one HgS layer, c CdS cap','II: a–c as I, d contiguous second HgS layer, e CdS cap','III: a–c as I, d three CdS layers, e second HgS well, f CdS cap'],axes=['Energy (eV), labeled approximately 1.2–3.0','Upper wavelength (nm): 1,000, 800, 600','Absorption (OD); panel-specific vertical ranges'])
asset('figure-3','figures','Original steady-state photoluminescence spectra of systems I–III.','Final source architectures under common PL acquisition; broad spectra in arbitrary units are not calibrated individual quantum yields.',ROUTES,'experimental',['PL maxima: I 820 nm, II 950 nm, III 820 nm.','The article estimates quantum yield below 1% for all systems.','Water-reference subtraction removes Raman/background; no separate nanocrystal Raman spectrum is presented.','Noise and baseline excursions preserved without smoothing.'],['System I','System II','System III'],axes=['Energy (eV), labeled approximately 1.2–3.0','Upper wavelength (nm): 1,000, 800, 600','PL intensity (a.u.)'])
asset('figure-4','figures','Original energy-dependent negative-transient decay times and selected kinetic traces following 400 nm excitation.','Final I–III source systems; short bleach recovery and longer low-energy signal retain distinct interpretations.',ROUTES,'experimental',['The high-energy component is approximately 5 ps; lower-energy decay becomes longer with wavelength.','Crossover wavelengths are I 600 nm, II 700 nm and III 650 nm, distinct from second-derivative absorption minima.','Lines are least-squares fits described mainly as a visual aid; no fitting coefficients or raw lifetime array are supplied.','All inset traces are labeled bleach; the body and caption interpret the long-wavelength component as stimulated emission. No source labels have been altered.'],['I inset: 650 and 500 nm','II inset: 900 and 500 nm','III inset: 750 and 600 nm'],axes=['Main: decay time (ps) versus energy (eV), upper wavelength (nm)','Inset: bleach intensity (a.u.) versus delay time (ps), 0–100'])
asset('preparation-start','source_notes','Original preparation overview and beginning of step A, including charge, pH and nucleation.','Shared A/B/C preparation context; read together with preparation-continuation.',ROUTES,'direct_source_method',['250 mL flask, 100 mL 2 × 10⁻⁴ M Cd²⁺, argon, hexametaphosphate, pH 7.9 and 0.6 mL H₂S gas.','Excerpt ends mid-sentence; continuation preserves the completion.','The printed S⁻ notation is source wording, not a verified speciation model.'])
asset('preparation-continuation','source_notes','Original completion of step A, cation exchange B and CdS growth C, followed by system I.','Common step definitions; repeated B/C applications remain within each route.',ROUTES,'direct_source_method',['Original 3.5 nm growth endpoint and final pH 4.6 retained.','B uses aqueous Hg²⁺; salt and counterion are not given.','C uses dropwise aqueous H₂S for 25 min and at least 20 min argon purge.','Additional Cd²⁺ is conditional when C does not immediately follow B; amount unreported.'])
asset('system-ii-iii','source_notes','Original descriptions of system II and III construction and the common dimensional assignments.','Source layer sequences and nominal dimensions, not independently resolved radial microscopy.',['system-ii','system-iii','chemical-interpretation'],'direct_source_method',['II forms one contiguous double-layer well.','III retains two CdS barrier layers after exchange of the third outer CdS layer.','The common core is described here as 3.2 nm, conflicting with step A.'])
asset('optical-methods','source_notes','Original transient-absorption and photoluminescence acquisition details.','Common analytical procedures; room-temperature statement is not assigned automatically to synthesis.',['absorption-acquisition','photoluminescence-acquisition','transient-absorption-acquisition'],'direct_source_method',['Excerpt begins after the preceding-column introduction to transient methods; detailed setup is cited to submitted reference 13.','400 nm, 100 fs FWHM, 100 µJ pump; 450–1,050 nm continuum probe; delay resolution 3 µm (21 fs); rotated 2 mm glass cell.','440 nm PL excitation; Nd:YAG-pumped OPO; the pump has 5 ns pulses at 10 Hz; 90° collection; water-reference subtraction.','No numerical room temperature or fs-pump repetition rate is supplied.'])
