"""Explicit semantic source-unit to academic-reader mapping."""
from pathlib import Path
import json
O=Path(__file__).resolve().parent;B=O.parent
M={}
def bind(target,*units):
 for u in units:
  key='braun2001-'+u
  M.setdefault(key,[])
  for t in target.split():
   if t not in M[key]:M[key].append(t)
bind('identity','identity-title','identity-journal','identity-dates')
bind('identity source-context','identity-authors')
bind('source-context','identity-administrative')
bind('historical-claim well-count-design','abstract-architecture')
bind('structural-inference','abstract-evidence')
bind('coupling-outlook','abstract-outlook','conclusion-coupling','conclusion-outlook')
bind('motivation theory-context','context-prior-work')
bind('morphology-scope','context-tetrahedral')
bind('step-b sequence-framework','context-exchange')
bind('motivation','context-motivation')
bind('theory-context','context-prior-theory')
bind('cadmium-stock','chemical-cadmium')
bind('mercury-stock','chemical-mercury')
bind('h2s-gas','chemical-h2s-gas')
bind('h2s-water','chemical-h2s-water')
bind('stabilizer','chemical-hexametaphosphate')
bind('water-argon','chemical-argon','chemical-water')
bind('figure1-scope ta-excitation','chemical-materials-scope')
bind('sequence-framework reference-02 reference-13','step-a-scope')
bind('step-a-charge','step-a-vessel','step-a-initial-ph','step-a-gas-injection')
bind('nucleation-ph','step-a-nucleation')
bind('step-a-grow nucleation-ph','step-a-acidification')
bind('step-a-grow','step-a-growth')
bind('step-a-purge','step-a-purge')
bind('core-size-conflict','step-a-size-conflict')
bind('step-b','step-b-feed','step-b-exchange','step-b-unknowns')
bind('exchange-driving-force','step-b-thermodynamics')
bind('cadmium-recycling step-c-cadmium','step-b-released-cadmium')
bind('step-b system-ii-sequence system-iii-sequence','step-b-repeat')
bind('step-c-cadmium','step-c-cadmium-rule','route-iii-topups')
bind('step-c-feed','step-c-growth','step-c-purge','step-c-missing')
bind('step-a-purge missing-fields','step-c-medium')
for r in ['i','ii','iii']:
 bind('system-'+r+'-sequence','route-'+r+'-sequence','route-'+r+'-transforms')
 bind('batch-scope','route-'+r+'-scope')
 bind('system-'+r+'-structure','structure-'+r)
 bind('absorption-stages-'+r,'abs-stages-'+r)
 bind('absorption-'+r,'abs-result-'+r)
 bind('emission-'+r,'pl-result-'+r)
 bind('dynamics-'+r,'ta-result-'+r+'-transition')
 bind('figure4-insets','figure4-'+r+'-inset')
bind('temperature-scope','route-temperature')
bind('missing-fields','route-final-state')
bind('system-i-structure system-ii-structure system-iii-structure core-size-conflict','structure-core')
bind('system-i-structure system-ii-structure system-iii-structure','structure-cap')
bind('morphology-scope missing-fields','structure-coordinates')
bind('ta-excitation','ta-method-pump','ta-method-probe','ta-method-cell')
bind('ta-delay','ta-method-delay')
bind('ta-excitation reference-13','ta-method-upstream')
bind('ta-delay temperature-scope','ta-method-temperature')
bind('pl-method','pl-method-excitation','pl-method-collection','pl-method-correction')
bind('absorption-method','abs-method-missing')
bind('absorption-stages-i absorption-stages-ii absorption-stages-iii','abs-result-core')
bind('absorption-comparison','abs-result-progression','abs-result-energy-order','abs-result-oscillator-ratio')
bind('oscillator-interpretation','abs-result-atom-context','abs-result-state-mixing')
bind('emission-comparison','pl-result-qy','pl-result-onset')
bind('trap-location','pl-result-broad','pl-result-trap-assignment')
bind('dynamics-i dynamics-ii dynamics-iii','ta-result-short','ta-result-transition-scope')
bind('figure4-decays','ta-result-long','figure4-fits')
bind('bleach-vs-emission','ta-result-negative-signal','ta-result-stimulated-emission','ta-result-bleach')
bind('theory-context','ta-result-theory')
bind('figure1-scope system-i-structure system-ii-structure system-iii-structure','figure1')
bind('theory-context figure1-scope','figure1-theory-scope')
bind('figure2-axes absorption-stages-i absorption-stages-ii absorption-stages-iii','figure2')
bind('figure3-axes','figure3')
bind('figure4-decays figure4-insets','figure4')
bind('inset-label-conflict','figure4-label-conflict')
bind('acknowledgment','acknowledgment')
bind('coverage','si-search')
bind('missing-fields','unreported-techniques')
for n in range(1,20):bind(f'reference-{n:02}',f'reference-{n:02}')
audit=json.loads((B/'source-audit.json').read_text(encoding='utf8'));ids={u['id'] for u in audit['units']}
assert set(M)==ids,(ids-set(M),set(M)-ids)
(O/'source-item-mapping.json').write_text(json.dumps(M,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(len(M),'source units mapped')
