from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
B=Path(__file__).resolve().parent;M=B.parents[3];G=B/'ja0496423';MON=B.parents[1]
def read(p):return json.loads(Path(p).read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
pub=read(G/'publication-checkpoint.json');assert pub['anonymous_verification']['status']=='passed'
skill=M/'skills/mattersyn-paper-to-site/references/full-paper-review.md'
installed=Path('[local path redacted]')
assert sha(skill)==sha(installed)
progress=read(B/'presentation-progress.json')['private_packages']
def audit_status(suffix):
 p=B/suffix/'canonical-records-audit.json'
 return f"independent canonical audit {read(p).get('status')} (SHA256 {sha(p)})" if p.exists() else 'independent canonical audit pending'
heo=B/'jp0219348/si-pages-1-2-independent-audit.json'
hs=f"Independent pages 1–2 numerical audit status: {read(heo).get('status')}; SHA256 {sha(heo)}." if heo.exists() else 'A separate auditor is checking pages 1–2; independent numerical approval is still pending.'
heading='## 2026-09-19 — Gu FePt–CdS published; evidence-priority batch advances'
entry=f'''{heading}

Published the same existing public MatterSyn Site version 29, dataset 0.22.0, at {pub['deployment']['updated_at']}; commit 72f7df1cf7d4dbd97d1f5c95d65c04e760ee1fca. Native deployment succeeded and five actual public routes passed anonymous checks without cookies, login or Sites bypass. Gu whole-material hub: https://mattersyn-recipe-atlas.cuiy781513.chatgpt.site/material?id=fept-cds-dbce8b ; source reader: https://mattersyn-recipe-atlas.cuiy781513.chatgpt.site/paper-review.html?id=gu2004 . FePt component-context hub fept-138f6f also added. The existing Site browser tab is on the published hub, normal viewport restored; local preview stopped. Detailed proof: research-assets/incoming-paper-monitor/batches/20260919-five-paper-pilot/ja0496423/publication-checkpoint.json. Previous entries saying no Site changes/new Gu publication are historical and superseded.

Gu supplied scope: DOI10.1021/ja0496423, all2main+3matchedSIpages,4copies/2uniquePDFs, source generation2 unchanged at release. All95facts and126sourceunits retained. Ten canonical records are one synthesis route, six supporting procedures and three observation/model/reference contexts, not ten independent syntheses. They contain33operations,132 measurement/quantitative/context entries,28materialslots and27sample/contextIDs. Reader138items,12original crops,actual TEM/HRTEM/final-product SAED panel1D,XRF inset table,magnetic/optical figures and model/context retained. All source/canonical/reader/molecular/apparatus/product/promotion/integration audits passed, with exact frozen hashes. Integration audit1,669checks plus targeted status-only addendum765checks/657currentbindings (SHA d064ac96cf766c8bf76d17c73fc4235e2cf9b881d1f3d30268600188244323fa). Actual browser exercised all33scenes and28chemical/specimen viewers, functional-group toggle,zoom/reset/rotation,completeSAED enlargement,source search,periodic-table discovery and390px mobile rendering. Final local checks passed438pages/424canonical-publichashes,40hubs,quality25,922checks,0errors/0warnings.

Scientific limits preserved: main Fe/Pt/Cd/S≈1:1:3:3.6 conflicts with uncorrected SI XRF mol%; Si/Rh are not assigned as dopants. Intact intermediate shells were not successfully isolated. Ether boiling temperature, gas identity for general reaction, pressure/rates, several purification/acquisition conditions and sample-batch joins remain unknown. CdCl2 80.5% hydration/assay basis unresolved. No XRD trace, atomic coordinates, CIF, interface/ligand geometry or exact structure–recipe training pair is supplied. Metal-chelate name lookups with H16 were rejected for the required formal H14 ligand stoichiometry; component depictions do not assert coordination geometry. New Gu N2 model uses NIST1.09768Å reference with arbitrary orientation; previously discovered shared1.460Å model was not reused and remains a separate reuse limitation for future audits. Scoped Gu97%oleylamine and technical90%diol/TOPO captions now render correctly in the viewer.

Released reviewed subset:424records,93synthesisroutes/variants,40material/componenthubs(30directsystems+10componentcontexts),28sourcegroups(27literature+1benchmark). Formal reader reviews23(9fullmain+matchedSI,14main-only),215pages in that review-index scope. Training eligibility: precursor_selection91,partial_protocol110,size_conditioned_recipe15,optical_outcome95,exact_structure_recipe0,success_prediction0. Gu adds1precursor-selection and2partial-protocolrows, all in source split group-0b23b092025d. These are not unique-paper, independent-experiment or whole-folder completion counts.

Preserve current batch batch-1789847144800065200-1. Gu is now closed with complete current-generation read/extract/audit/integrate/publish evidence; the other four remain active. Nagasaki la036034c:16private records (one representative CdS route,one incomplete biotin variant,10procedures,4observations),36ops,122measurement/contextentries,61materialslots,2stocks,28contexts; {audit_status('la036034c')}. Ribeiro jp0473669:11private records(1route5procedures5observations),13ops,147measurement/contextentries; {audit_status('jp0473669')}. Norberg ja048427j:19private records(1route11procedures7observations),47ops; all201facts,174inventoryobjects,68references and26originalprotocolstages mapped; {audit_status('ja048427j')}. These46 unpublished drafts still need reader/visual preparation and independent presentation audits. Do not change their imported_unreviewed/tasks[] status until the appropriate gate passes. Each has a frozen manifest, source-coverage map, author validation and notes; do not overwrite those with status updates.

Heo jp0219348: main9pages/narrative/all5tables independently audited earlier. New SI pages1–2 (printed41–42) transcription retains170rows,1,020numericcells,170markers and all5negative observed values. Author source-comparison is separate from independent numerical audit. {hs} Pages3–14 remain untranscribed/unaudited at cell level; remaining24page/block selectors recorded. Preserve printed scaling,negativeintensities,coordinate/occupancy/sourceconflicts; no CIF or exact pair generated. See si-numerical-verification-checkpoint.json and si-reflections-transcription.json.

Queue refreshed from current ledger without another corpus-wide scan. Latest intake snapshot21:57UTC:13,555documentcopies(6,182incoming+7,373legacy),9,245waitingprovisionalscopes; after Gu closure4active and19historicallyclosednew-queue scopes. Unique-paper/material/recipe whole-corpus totals remain unknown. Source-priority automated screening snapshot and rankings remain active; refresh new/changed-source screening before selecting a later batch. Preserve original arrival metadata and filenames. No source papers downloaded. The existing five-minute heartbeat remains the sole recurring review automation; no duplicate created. Four active-agent slots including root remains the actual concurrency cap, not five simultaneous independent workers. Scope-richness priority reflects extraction usefulness, not intrinsic paper quality; low-signal screening is not a no-recipe exclusion.

Memory and reusable skill saved. Project/installed full-paper-review.md identical SHA256 {sha(skill)}; both skill validators passed. Added reference-stoichiometry/bond validation, source-scoped caption rendering and targeted post-audit refinement guidance. Private incoming-paper-monitor/latest-publication.json now drives queue release metadata, and build_queue_report.py regenerated truthful29/424/93/40status. Reuse save_presentation_checkpoint.py for safe current-package status refresh; do not rerun old save_source_review_checkpoint.py, whose phase assumptions/global registry bindings are stale. Site publishing on Windows needs the installed Git Bash bin/usr-bin on process PATH; GNU tar archive argument uses /c/... to avoid treating C: as a remote host. The validated packaged archive was saved/deployed only after exact source push; no credentials persisted.

Nagasaki visual-reuse-plan.json/.md is frozen privately:61slots/42materialidentities/16records;18slots have8existing-reference candidates,11slots need8chemical-reference qualifications,32slots require polymer/protein/specimen/support/unknown-reagent treatment. Candidate plan SHA25602c67878cf48378023871226eba7316d83e8628ec0e11d6e16f6147e71c6e363. This is not final binding approval. Five existing candidates need source-neutral presentation cleanup. Gu CdCl2 SVG embeds80.5% and cannot be reused by only changing binding text; acetic-acid registry/model/SVG metadata retain other-paper context; unspecified Na2S hydration cannot inherit nonahydrate; Formvar-grid model has unreported mesh/carbon specifics. Inspect every asset's embedded wording before reuse. No new model or source download was performed for the plan.

Next: complete the remaining bounded audits, prepare Nagasaki/Ribeiro/Norberg academic readers and source-specific visuals in parallel, and continue Heo SI numerical review. Publish independently passed contributions to the same Site; do not claim the entire corpus is done. Future chatbot/DFT/theory-comparison functions and task-specific descriptor/reference-prototype training improvements remain planned, not implemented by this release.

'''
p=M/'MEMORY.md';prior=p.read_text(encoding='utf-8-sig')
if prior.startswith(heading):
 boundary=prior.find('\n## ',len(heading))
 assert boundary!=-1
 prior=prior[boundary+1:]
p.write_text(entry+prior,encoding='utf-8')
print(json.dumps({'memory':str(p),'skill_sha256':sha(skill),'publication_version':29,'updated_at':datetime.now(timezone.utc).isoformat()}))
