import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parent
rows=[]
def row(record,stage,apparatus,flow,conditions,locator,limits):rows.append({'record_id':record,'proposed_stage':stage,'apparatus':apparatus,'material_flow':flow,'source_conditions':conditions,'source_locators':locator,'limits':limits,'exact_operation_id':'pending root canonical draft'})
p1=['Main PDF p. 1, printed p. 2117, Chemicals / QDOH formation'];p2=['Main PDF p. 2, printed p. 2118, Experimental'];t1=['Main PDF p. 3, printed p. 2119, Table 1']
r='veinot-1997-qdoh'
row(r,'prepare two stocks','Two separately labeled solution vessels','Na2S·9H2O plus 4-hydroxythiophenol stock; separate cadmium-acetate stock','First stock: 2.53 g / 11 mmol sulfide and 4.93 g / 39 mmol thiol in 150 mL acetonitrile/methanol/water 1:1:2 v/v. Cadmium stock: 5.05 g / 29 mmol in the same solvent system.',p1,['Cadmium-stock volume is not stated; do not depict 150 mL for each stock or total volume as 150 mL.','Preserve cadmium mass/amount discrepancy. No hydration-state repair or measured molecular Cd coordination.'])
row(r,'combine and react','Stirred vessel protected from light, nitrogen atmosphere','Sulfide/thiol solution added to rapidly stirred cadmium solution; yellow precipitate forms','12 h under nitrogen; reaction temperature is not supplied.',p1,['Not hot injection, not a high-temperature furnace or shell-growth reactor.','Do not label room temperature merely because later drying is at room temperature.'])
row(r,'concentrate','Rotary evaporator, not a generic heated flask','Reaction mixture concentrated before collection','About one-third of original total volume.',p2,['No specific final mL: total original volume is unknown. Bath temperature, vacuum and speed absent.'])
row(r,'collect and wash','Centrifuge plus sonication vessel with ordered solvent sequence','Collect solid; repeated washing/sonication/centrifugation with water, then acetone, then ether','Order explicit; number of cycles, solvent amounts, speed, time, sonicator settings unknown.',p2,['Do not add methanol to this QDOH washing sequence; it appears in ester workup.','Ether identity is not expanded in the workup text.'])
row(r,'dry','Vacuum chamber with powder','Washed solid → QDOH powder','High vacuum overnight at room temperature; yield 2.23 g.',p2,['No exact hours, numerical vacuum pressure or oven temperature; 12 h belongs to reaction, not drying.'])
row('veinot-1997-pyrenecarbonyl-chloride','dissolve and heat','Stirred vessel under dry nitrogen; separate heating and cooling stages','1-pyrenecarboxylic acid in thionyl chloride; olive precipitate forms, redissolves on heating','1.0 g / 4.1 mmol acid, 20 mL thionyl chloride; room-temperature stirring for several minutes, then 80 °C for 3 h.',p2,['No SO2/HCl gas-flow arrows or reaction stoichiometry beyond reported materials.'])
row('veinot-1997-pyrenecarbonyl-chloride','isolate precursor','Cooling → filtration → vacuum removal','Remove excess thionyl chloride from filtrate; orange-yellow solid immediately used for 3c','Cooling endpoint, filtration material, vacuum and yield not stated.',p2,['Distinct from 100 °C hot filtration in N-acylimidazole chloride routes.'])
for s in ['a','b']:
 r='veinot-1997-acylimidazole-3'+s
 row(r,'anhydride acylation','Stirred vessel under dry nitrogen','Imidazole dissolves in a large excess of acetic or butyric anhydride','Room temperature; common text says 30 min. Table 1 gives 3a 30 min / 100% yield; 3b 15 min / 50% yield.',p2+t1,['No acyl chloride or imidazole-hydrochloride filtration imposed on these specifically described anhydride routes.','Large excess is qualitative; quantities and concentration unknown.'])
 row(r,'isolate acylimidazole','Vacuum liquid removal, then toluene recrystallization','Remove acid/excess anhydride; obtain white crystals and recrystallize','Reduced pressure; temperatures and times of recrystallization not specified.',p2,['No ice bath is inherited from the separate chloride procedure unless explicitly represented as that procedure.'])
for s in ['c','d','e']:
 r='veinot-1997-acylimidazole-3'+s
 row(r,'chloride acylation','Dropwise addition to stirred toluene solution','50% solution of the corresponding acyl chloride in dry toluene → 2.05 equivalents imidazole in toluene','Addition at room temperature, then heat to 100 °C. Table 1 gives 3c 30 min / 65%; 3d 15 min / 100%; 3e 30 min / 100%.',p2+t1,['50% concentration basis is unstated; no mass/volume assumption.','Table time is a route summary, not explicitly assigned to the 100 °C hold.','No addition funnel or syringe pump is specified. Use neutral dropwise delivery.'])
 row(r,'hot filtration and crystallization','Hot filter followed by ice-bath cooling','Remove imidazole hydrochloride precipitate; cool filtrate, collect crystals and recrystallize once from toluene','Hot filtration follows heating to 100 °C; ice bath for precipitation.',p2,['Filter type, transfer temperature, bath composition beyond ice, cooling time and collection method are not stated.'])
for s in ['a','b','c','d','e']:
 r='veinot-1997-ester-2'+s
 row(r,'disperse QDOH and dose acylimidazole','Sonication vessel, then rapid stirring with dropwise feed; light protection and dry nitrogen','QDOH in DMSO + matching 3a–e in DMSO → terminal phenolic ester 2a–e','Representative 2a: 300 mg QDOH in 5 mL DMSO plus 170 mg acetylimidazole in 5 mL DMSO. Room temperature, 30 min. Table 1 gives every ester 30 min.',p2+t1,['Exact charges independently explicit only for 2a; do not reuse 170 mg for other acylimidazoles.','Show source-supported O-acylation, not a new crystalline CdS shell or explicit ligand-covered atomic nanoparticle.','Conversion percentages are 95,97,95,100,100 for 2a–e; not every drawing may claim exactly complete conversion.'])
 row(r,'cool and quench','Ice bath then water addition','Reaction mixture cooled; water quench yields precipitate','Ice-bath cooling before water; quench volume not stated.',p2,['Here water is explicitly a quench, unlike the preceding Dabbousi butanol storage step.','No 0 °C sample temperature is invented from the ice-bath description.'])
 row(r,'collect wash dry','Centrifuge, sonication/washing sequence, vacuum drying','Precipitate → repeatedly sonicated in water, methanol, acetone, ether → dry ester powder','Consecutive solvent order; high vacuum, room temperature, 24 h drying.',p2,['Do not transfer the QDOH overnight drying or omit the ester-specific methanol wash.','Repeated centrifugation after each sonication is not independently restated in this sentence; preserve only canonical inheritance if source-audited.'])
row('veinot-1997-reagent-conditioning','independent reagent treatments','Separate branches: sieves/filter; ion-exchange/charcoal columns; recrystallization/vacuum dryer; reduced-pressure distillation','Toluene; water; cadmium acetate; 4-hydroxythiophenol are conditioned separately','Toluene:4 Å sieves/filter. Water: D8902 then D8204. Cd acetate: glacial acetic acid recrystallization, 100 °C vacuum drying. Thiol: reduced-pressure distillation immediately before use.',p1,['Do not portray these as a single sequential material stream or assign Cd-acetate drying temperature to the thiol.'])
row('veinot-1997-nmr','prepare and measure','NMR tube and 400 MHz instrument; separate D2O-exchange branch','QDOH and clusters except 2e in DMSO-d6; 2e in CDCl3; Figure 2 3e precursor in DMSO-d6','Bruker ARX 400 MHz; QDOH Figure 1 before/after one D2O drop.',p2+['Main PDF p. 4, printed p. 2120, Figures 1–3'],['No synthetic spectrum or invented deuterated-solvent ratios.','The D2O exchange applies to QDOH; 3e and 2e are different chemical products.'])
row('veinot-1997-ftir','prepare pellet and measure','KBr pellet and FTIR source/detector','Selected cluster + KBr → spectrum','Mattson 3000; Figure 4 is 2e; Table 2 gives all compounds.',p2+['Main PDF pp. 3 and 5, Table 2 / Figure 4'],['No pressure, pellet mass, concentration or coating thickness invented.','Original Figure 4 plots transmittance despite caption calling it absorption.'])
row('veinot-1997-uv-visible','prepare cuvette and measure','1 cm quartz cuvette with optical source and detector','QDOH in methanol OR ester 2a–e in chloroform','HP 8452; Figure 5 QDOH concentration 10^-4 M.',p2+['Main PDF p. 5, Figure 5'],['QDOH concentration does not apply to all esters.','Calculated optical diameter must remain distinct from TEM and unresolved optical-edge conflict.'])
row('veinot-1997-tem','clean support and deposit','300-mesh carbon/Cu grid, cleaning vials, filter-paper support','Acetone → chloroform → acetone cleaning; air-dry; freshly sonicated/centrifuged chloroform suspension deposited','2.5 mg nanocluster in 3 mL CHCl3; three drops; solvent absorbed through grid by filter paper; room-temperature air drying.',p2,['Source describes both aggregates and individual clusters; do not draw all particles as isolated.','No generic 200 kV, objective aperture or carbon evaporation inherited from Dabbousi.'])
row('veinot-1997-tem','calibrate and image','Philips EM-301 TEM; distinct calibration grid','Calibration standard then selected nanocluster specimen','Silicon grid 21 600 lines/cm; Figure 6 caption magnification 290000×.',p2+['Main PDF p. 6, Figure 6'],['Do not assign a crystalline CdS lattice or synthetic SAED.','Figure6 6 nm scale and body1100 Å aggregate remain unresolved.'])
row('veinot-1997-unfunctionalized-control','control outcome','Neutral reaction comparison boxes','Thiophenol-capped CdS + unspecified N-acylimidazole → unchanged clusters; organic acid recovered after aqueous workup','Exact reagent selection, quantities and operational settings not restated.',['Main PDF p. 5, printed p. 2121, control paragraph'],['Not a successful phenolic-surface synthesis; do not inherit a complete recipe without source qualification.'])
row('veinot-1997-direct-acylchloride-degradation','failed direct acylation','Neutral source-outcome panel','Direct acyl chloride attempts destroy the cluster','Specific conditions and acyl identity unreported.',['Main PDF pp. 2–3, discussion'],['No exact decomposition pathway, bulk phase or parameter threshold assigned.'])
row('veinot-1997-prolonged-degradation','prolonged exposure failure','Time-extension warning/outcome panel','QDOH under acylation conditions → bulk CdS precipitate plus corresponding crystalline O,S-diester','Prolonged exposure >12 h.',['Main PDF p. 5, printed p. 2121, degradation paragraph'],['Do not choose 13 h, 24 h or a unique acyl group. Crystallinity of organic product does not identify its CIF or CdS phase.'])
data={'source_id':'veinot1997','source_doi':'10.1021/cm970189m','status':'source-grounded apparatus plan awaiting exact operation IDs','stages':rows,'principles':['Every apparatus graphic is illustrative, not a measured reactor or material geometry.','Bind a source-specific module only to source DOI10.1021/cm970189m and known canonical actions; return null for unsupported contexts.','Use actual vessels, rotary evaporation, centrifuge, sonication, filtration, ice bath, vacuum dryer and analytical supports as appropriate.','Retain unknown temperature/time/pressure and all source conflicts.','Surface-state drawing: CdS region — S — para-phenyl — OH changes at O to O—C(=O)—R; no finite-particle atom list, exact ligand count or phase.','Keep reagent stock, precursor, surface-functionalized cluster and analytical specimen roles separate.']}
dump=lambda p,x:p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
dump(ROOT/'apparatus-plan.json',data)
(ROOT/'apparatus-plan.md').write_text('# Veinot 1997 apparatus and surface-state proposal\n\nThe source calls for a light-protected, nitrogen-atmosphere precipitation route, followed by rotary concentration, centrifugation, sonication/washing and vacuum drying. Surface esterification is a separate mild reaction: matching N-acylimidazole in DMSO, then an ice bath and explicit water quench. The 2a charge is representative and must not be copied as a measured charge for all derivatives.\n\nPrecursor routes must remain distinct: 3a/3b use acid anhydrides; 3c/3d/3e use acyl chlorides and hot filtration. Pyrene acid chloride has its own 80 °C / 3 h preparation.\n\n`apparatus-plan.json` maps all proposed stages to root-approved record IDs, conditions, material flow and missingness. Exact operation IDs await root canonical drafts. The surface illustration should show S-bound phenyl-OH changing to phenyl-O-C(=O)-R, with an explicitly conceptual CdS region, no crystal lattice and no numerical cap count.\n',encoding='utf-8')
print(len(rows))
