from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text(encoding='utf8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
audit={'source_doi':'10.1021/cm970189m','source_sha256':'eac4fe78e4bc3ab9c15e0409b69232e4294a0c07787d3ca650c378f6341d4adc','status':'passed_creator_source_and_render_review','module':'veinot-protocol.mjs','module_sha256':sha(R/'veinot-protocol.mjs'),'exports':['buildVeinotScene','createVeinotArt'],'operations_covered':133,'actions_covered':41,'dispatch_checks_passed':534,'full_source_scope':'All six main pages text and visuals reviewed for the asset extraction; no supporting information supplied or downloaded.','visual_review':{'all_operations_rendered':133,'distinct_contextual_frames_inspected':97,'contact_sheets_inspected':17,'out_of_bounds_text':0,'corrections':['Moved vacuum-distillation receiver above the footer','Separated rotary-evaporator receiver label from the vessel','Restricted the 3b timing conflict note to the 3b scene','Removed the anhydride note from the pyrene-chloride scene']},'source_scope_checks':['3a/3b use the anhydride route; 3c–e use the chloride route','3b 15/30 min conflict stays visible; no unique operative time','QDOH reaction temperature unknown; drying temperature not transferred','Cadmium-stock volume and original total volume unknown; no 50 mL concentration endpoint','Only 2a displays representative 300 mg/5 mL and 170 mg/5 mL charges','2b–e depict inherited common method without borrowed absolute quantities','Water quench follows ice cooling; ice bath does not establish sample temperature','Ester wash sonication does not invent a centrifugation at every solvent change','Control and degradation panels remain observation flow diagrams without invented apparatus','TEM retained fraction remains unspecified; 3 drops, filter-paper wicking and source calibration grid retained','Molecular precursor 3e NMR is separate from CdS specimens','No synthetic TEM/SAED, measured CdS lattice, atomistic surface or spectrum generated'], 'remaining_limits':['Creator review is not independent audit; parent coordinates independent check and browser integration QA','All apparatus, support layouts, particle counts and connection motifs are illustrative','Live browser layout must be checked by parent after integration'],'manifest_sha256':sha(R/'apparatus-review/scene-manifest.json')}
save(R/'apparatus-audit.json',audit)
(R/'apparatus-audit.md').write_text('Veinot 1997 apparatus handoff\n\nCreator source/render review passed for all 133 operations and 41 actions. All 97 distinct contextual frames were inspected across 17 contact sheets. The final module passed 534 dispatch, source-DOI guard and SVG checks and has no out-of-bounds text.\n\nModule SHA256: '+audit['module_sha256']+'\n\nSource scope: six main pages read and visually reviewed. Inherited ester methods, unknown reactor charges and temperatures, the 3b timing conflict, distinct molecular/colloidal NMR specimens and TEM subfraction ambiguity remain explicit. No measured CdS phase, atomic coordinates, surface coverage, diffraction pattern or synthetic spectrum is supplied.\n\nFinal layout corrections raised the distillation receiver above the footer and separated the rotary receiver label; both corrected frames were re-inspected. Independent source review and live Site browser QA remain parent tasks.\n',encoding='utf8')
reg=read(R/'molecular-assets/registry-additions.json')
handoff={'status':'stable_for_parent_integration','source_doi':'10.1021/cm970189m','source_assets':{'original_crops':11,'manifest':'crop-assets/manifest.json','manifest_sha256':sha(R/'crop-assets/manifest.json')},'chemical_assets':reg['summary'],'molecular_validation':{'checks_passed':615,'formula_bonds_charge_isotopes_roundtrip':True,'all_22_2d_and_3d_visuals_inspected':True},'binding_validation':{'checks_passed':297,'all_25_cards_inspected':True,'registry_neutralizations':'molecular-assets/registry-neutralizations.json','resolved_audit_findings':['SOCl2 functional group is Thionyl group, not Sulfoxide','Actual Veinot acetonitrile and acetone binding notes contain no earlier-paper process conditions']},'module':{'file':'veinot-protocol.mjs','sha256':audit['module_sha256'],'operations':133,'actions':41},'integration_files':['crop-assets/manifest.json','molecular-assets/registry-additions.json','molecular-assets/bindings-additions.json','molecular-assets/registry-neutralizations.json','molecular-assets/reused-references.json','molecular-assets/product-reference-proposal.json','molecular-assets/asset-manifest.json','veinot-protocol.mjs'],'site_writes':False,'network_access':False}
save(R/'asset-handoff.json',handoff)
(R/'molecular-assets/README.md').write_text('Veinot 1997 chemical reference package\n\n47 new source-specific references: 22 explicitly named free-molecule connectivity/conformer models and 25 honest material/family/support cards. Eight existing identities are reused without duplicate asset files. All 115 material instances across 21 private canonical records have exact bindings.\n\nThe five ester cards and QDOH/control motifs illustrate only sulfur-bound para-substituent connectivity. CdS is the inorganic component formula; no measured nanocluster graph, lattice, phase or complete surface coverage is assigned. Deuterium is hydrogen isotope 2 in the JSON and should render as D or ²H.\n\n615 molecule checks and 297 package checks passed. All molecule and card visuals were inspected. registry-neutralizations.json proposes neutral shared metadata for acetonitrile/acetone; preserve their coordinate assets and existing hashes. Exact draft-byte hashes in bindings may be refreshed by the parent after canonical promotion.\n\nImport registry-additions.json, bindings-additions.json, individual svg/ and models/ files, and optional product-reference-proposal.json. Aggregate molecules-3d-additions.json is a convenience, not a replacement for individual model files. All output is private until parent integration; no Site or network actions were taken.\n',encoding='utf8')
print(json.dumps({'status':handoff['status'],'module_sha256':audit['module_sha256']}))
