from pathlib import Path
from datetime import datetime,timezone
import json
B=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
now=datetime.now(timezone.utc).isoformat();c=read(B/'checkpoint.json')
c.update(checkpoint_at=now,canonical_records_created=21,measurement_entries=232,operation_count=133,si_status='Matching supporting information not located or verified. Two local mains are byte-identical.',website_published=False,current_work_items=[{'label':'Main text and visual reading','status':'complete','scope':'All6 supplied pages; local source identity verified, SI unverified.'},{'label':'Canonical extraction and independent scientific audit','status':'complete','scope':'21records,232measurements(202quantities+30qualitative facts),133operations;124independent canonical checks pass;141source units mapped.'},{'label':'Reader and original evidence','status':'in_progress','scope':'101readeritems,11originalassets,23fulltablerows,15references/notes prepared; privatepreflight963checks passed. Actual Site rendering not yet verified.'},{'label':'Molecules, surface references and protocol diagrams','status':'in_progress','scope':'115chemicalbindings,22new computed molecules and25identity/surface cards. Reused caption audit identified wrong-paper wording; corrections and independent apparatus audit pending.'},{'label':'Integration and publication','status':'pending','scope':'Site schema/rendering extended for qualitative facts and intended surface,39scientific regression tests passed. Current paper not imported/published; live Site stillversion15.'}],next_action='Finish neutral chemical-reference captions and apparatus module; independently audit bindings and scenes; import audited records,build atlas/inventory,run independent actual-reader and browserchecks,publish existingSite,save releaseproof andcompleteallfivemilestones.')
write(B/'checkpoint.json',c)
milestones={'read':{'status':'complete','evidence':[str(B/x)for x in['source-manifest.json','source-identity.json','source-audit.json']],'note':'Six supplied main pages read and visually inspected; SI unverified.'},'extract':{'status':'complete','evidence':[str(B/x)for x in['canonical-records-audit.json','public-review-proposal/source-item-coverage.json','crop-assets/manifest.json']],'note':'Complete supplied-main canonical/context inventory extracted; source contradictions retained.'},'audit':{'status':'in_progress','evidence':[str(B/'canonical-records-audit.json')],'note':'Canonical/source audits passed; chemical-reference and apparatus audits pending.'},'integrate':{'status':'pending','evidence':[],'note':'Not yet imported/built/reader-validated.'},'publish':{'status':'pending','evidence':[],'note':'Current paper not published; existing liveversion15unchanged.'}}
for m in milestones.values():
 if m['status']=='in_progress':m['status']='partial'
write(B/'milestones.json',milestones)
write(B/'schema-regression-tests.json',{'status':'passed','tests':39,'scope':'Scientific dataset and paper-review regressions including3newtypedqualitative/surface-target tests. Executed after schema/data helpers changed; no browser claim.','at':now})
print('Saved exact reading/extraction/audit progress; publication remains incomplete.')
