import json
from pathlib import Path
O=Path(__file__).resolve().parent
def add(rank,title,methods,structure,link,gaps,coordinates='not_established_in_inspected_sections',pairing='Main/SI matching title and authors',level='measured_phase_morphology_candidate'):
 r=dict(rank=rank,title=title,source_pairing=pairing,synthesis_presence='yes_explicit_target_procedure',method_receipts=methods,structure_receipts=structure,link_assessment=link,gaps=gaps,coordinates=coordinates,structure_level=level,status='partial_methods_first_triage',full_source_review_complete=False,scientific_admission=False,training_admission=False,automatic_exclusion=False)
 (O/f'scope-rank{rank:03d}.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def e(role,pages,section,finding,key=None):
 d=dict(role=role,pages=pages,section=section,finding=finding)
 if key:d['file_key']=key
 return d
add(63,'Hybrid PbS Quantum Dot/Nanoporous NiO Film Nanostructure: Preparation, Characterization, and Application for a Self-Powered Cathodic Photoelectrochemical Biosensor',
 [e('main',[3],'Experimental section','Quantified TGA-stabilized PbS aqueous preparation at pH11/N2, nanoporous NiO on ITO via heating and 300C conversion, and alternating PDDA/PbS assembly; hybrid/biosensor stages distinct.')],
 [e('main',[3,4],'Structural characterization; Figures1-3','Named as-synthesized PbS QDs, NiO film and hybrid have TEM/SEM and measured XRD assignments; PbS quasi-spherical about6nm, NiO interconnected nanosheets. JCPDS patterns are references.')],
 'Direct named preparation-to-component/hybrid characterization; exact aliquot not established.', ['No local SI in selected scope; absence is not negative synthesis evidence.','Full hybrid/biosensor variant coverage not attempted.'],pairing='Main identity confirmed; no local SI available')
add(64,'Enzymatic Preparation of Plasmonic-Fluorescent Quantum Dot-Gold Hybrid Nanoprobes for Sensitive Detection of Glucose and Alkaline Phosphatase and Dual-Modality Cell Imaging',
 [e('main',[2,3],'Experimental section','Explicit SILAR ZnS shelling on preformed CdSe, polymer/PLH and enzyme assembly, then HAuCl4 with glucose/GOx or AAP/ALP at room temperature. CdSe seed synthesis is not supplied in these inspected sections.')],
 [e('main',[3,5],'Figures1 and5','Measured XRD described as wurtzite before/after transfer; named GOx and ALP routes separately linked to TEM/HRTEM core-satellite and core-shell products.')],
 'Named enzymatic routes map to distinct morphology panels; do not merge seed, ZnS shell and gold assembly into one atomic model.', ['Seed recipe and exact precursor formulations require follow-up.','Remaining SI figures and assay variants unchecked.'],pairing='Main/SI title and all authors matched; SI1 visually checked after damaged text extraction')
add(65,'Interface Modeling Leading to Giant Exchange Bias from the CoO/CoFe2O4 Quantum Dot Heterostructure',
 [e('main',[2,3],'Experimental Methods','Quantified CoO seed thermal decomposition followed by Co/Fe precursor addition onto30mg CoO; 15/30min annealing aliquots, washing and redispersion.')],
 [e('main',[3,4],'Figures1-2 and Table1','Measured two-phase XRD and lattice metrics; explicit30min product chosen for TEM/HRTEM. Authors state XRD alone cannot establish core-shell; region-specific fringes support their structural interpretation.')],
 'Explicit annealing-time link;30min selected morphology and properties. Reference bulk cells remain separate.', ['Full SI images unchecked.','Interface sharpness is partly inferred from magnetic response, not measured atomic coordinates.','Table1 contains cell/crystallite sizes, not atom positions.'])
add(66,'Room Temperature Synthesis of Stable, Printable Cs3Cu2X5 Colloidal Nanocrystals with Near-Unity Quantum Yield Green Emitters',
 [e('main',[7],'Experimental section','Explicit room-temperature antisolvent and160C hot-injection Cs3Cu2Cl5 recipes, precursors, purification and distinct ligand/halide variants; drop-cast PXRD and TOPAS refinement methods.')],
 [e('main',[2],'Figure1 and discussion','Current NC diffraction, Cmcm cell and disordered Cu model are linked to SI TableS1; main describes antisolvent results and improved purity by hot injection.'),e('si',[3,7],'FigureS4 and TableS1','Actual six-site Cs/Cu/Cl x,y,z/occupancy table, explicitly captioned as Rietveld-refined NC positions; visually confirmed. FigureS4 is hot-injection refinement with95.7% reported phase purity.')],
 'Current-material synthesis and refined average structure evidenced; exact TableS1 preparation variant/aliquot not explicitly resolved by this partial pass.', ['Keep minority/impurity phases separate; no universal purity claim.','Two Cu sites have fractional occupancy, requiring disorder-aware average representation.','No finite-particle measured model; full refinement constraints and source/sample join still need focused review.'],coordinates='present_source_refined_atomic_position_table; average_disordered_crystal; exact_recipe_variant_link_unresolved',level='atomic_table_followup_candidate')
add(67,'Quantitative Analysis of Plasmonic Metal Oxide Nanocrystal Ensembles Reveals the Influence of Dopant Selection on Intrinsic Optoelectronic Properties',
 [e('main',[3],'Nanocrystal synthesis','Explicit slow injection of In/dopant oleates into oleyl alcohol at290C,0.35mL/min; dopant incorporation corrections, workup and varying injected volume for size.')],
 [e('main',[4],'Table2 and discussion','Named Sn/Ti/Ce/Zr dopants with measured STEM radii and ICP/XPS doping; radial segregation is an interpretation.'),e('si',[2],'FigureS1; TableST1','Measured XRD assigned to cubic bixbyite reference; substrate peaks distinguished and STEM/Scherrer radius comparison shown.')],
 'Dopant/size series linked to preparation, but exact injected volumes for each table row not resolved.', ['HEDA optical model is not atom coordinates.','Full size/dopant variant recipe map and SI pages unchecked.'])
add(68,'An Experimental Introduction to Colloidal Nanocrystals through InP and InP/ZnS Quantum Dots',
 [e('si',[2,5],'Experimental Section: InP cores and core/shell synthesis','Quantified adapted teaching-lab InP hot injection and staged ZnS shelling; purification alternatives. SI2 is authoritative procedure; SI1 is a student report, SI3 a handout.','10.1021_acs.jchemed.2c01167_si_2.pdf')],
 [e('main',[3],'Structural Analysis; Figure2','Diffractogram explicitly for synthesized large InP core sample, compared with zinc-blende bulk reference. Size edge length derives from absorption sizing curve; tetrahedral shape correction comes from cited work.'),e('si',[1],'Author note on student report','Warns that the student report used an outdated spherical sizing curve; do not treat its size difference as a different measured morphology.','10.1021_acs.jchemed.2c01167_si_1.pdf')],
 'Large InP synthesis linked to phase comparison; do not transfer one supplied class diffractogram to every student batch/core-shell sample.', ['Medium/small core and complete purification pages unchecked.','Student report, handout and current procedure remain separate evidence roles.','No independent TEM size established in inspected sections.'],pairing='All three SI titles/authors match; contents distinguish student report, experimental detail, and handout')
add(69,'Colloidal Chemistry in Molten Inorganic Salts: Direct Synthesis of III-V Quantum Dots via Dehalosilylation of (Me3Si)3Pn with Group III Halides',
 [e('si',[4],'GaAs/GaP heat-up synthesis in CsI/KI/NaI eutectic','Explicit masses, molten salt/TMS pnictide mixture, nitrogen400-500C/30min, salt removal, GaI3 treatment and ligand redispersion.')],
 [e('main',[5],'Figure5; Table1','Temperature/time-labelled GaAs PXRD/HRTEM/Raman panels and separate III-V synthesis-condition/Scherrer-size table; structural perfection depends on thermal history.')],
 'Named reaction families and temperature/time characterization support phase/morphology linkage; no exact aliquot or complete variant join.', ['Only one representative complete SI route read; numerous other routes remain unchecked.','Do not equate Scherrer size with TEM diameter or infer point-defect coordinates.'])
add(70,'Synthesis of monodisperse cobalt nanocrystals and their assembly into magnetic superlattices (invited)',
 [e('main',[3],'II Experiment','Quantified CoCl2/oleic acid/trialkylphosphine and superhydride reduction at200C20min; fractionation, separate superlattice assembly and300C annealing.')],
 [e('main',[4],'III Results; Figures1-2','TEM size fractions and measured11nm cobalt diffraction assigned to epsilon phase by beta-Mn symmetry comparison. Reference20-atom cell description is not a current atom-position table.')],
 'Synthesis/fractionation linked to sized NC products; assembled superlattice and annealed hcp products are distinct states.', ['No local SI available.','Extracted oleic-acid redispersion volume has a suspect unit and must be visually verified before numeric extraction.','All phase/annealing/assembly variants not covered.'],pairing='Main publisher cover title/authors match article contents; no local SI')
add(71,'A Simple Colloidal Route to Nanocrystalline ZnO/CuInS2 Bilayers',
 [e('main',[3],'Experimental','Explicit ZnO colloid/dip-coating/sintering procedure and separate In/Cu-TPP complexes, sulfur addition, concentration, coating and vacuum400C CIS annealing.')],
 [e('main',[2],'Figures3-4 and discussion','Named sintered CIS samples show HRTEM/EDX and tetragonal chalcopyrite diffraction; initial fresh colloid phase is explicitly unresolved by broad XRD. Powder from spontaneously grown/crushed crystals is a separate state.')],
 'Sintering times/states map to measured structure; fresh colloid cannot inherit the sintered or crushed-crystal phase unqualified.', ['No local SI available.','Trailing PDF page includes another communication per text index; not treated as target evidence.','Complete film-state and stoichiometry inventory remains unchecked.'],pairing='Target main title/authors and article pages confirmed; no local SI')
add(72,'Selective Synthesis of Co3O4 Nanocrystal with Different Shape and Crystal Plane Effect on Catalytic Property for Methane Combustion',
 [e('si',[2],'Experimental Section','Three explicit cobalt oxide routes: ethanol/oleylamine cubes, aqueous hydroxide sheets and glycerol-containing carbonate/hydroxide belts; distinct hydrothermal conditions and350C3h air calcination.')],
 [e('main',[1],'Figure1 and discussion','Named cube/sheet/belt recipes map to electron microscopy and exposed-plane interpretation; XRD assigned to spinel/fcc reference. Facet structural cartoons are not source-refined coordinates.')],
 'Explicit shape-route association; precursor morphology and calcined final product remain separate.', ['Complete SI microscopy and catalytic-state inventory unchecked.','Hydroxide/carbonate precursor notation needs careful visual transcription before numeric extraction.','Sheets/belts have micron lateral dimensions; do not recast all objects as small QDs.'])
add(73,'Multicolor Tuning of Manganese-Doped ZnS Colloidal Nanocrystals',
 [e('main',[2],'Experimental Section','Quantified ZnCl2/MnCl2 oleylamine/TOPO route with sulfur injection and290C1h growth; purification and a separate mercaptoacetic-acid phase-transfer treatment.')],
 [e('main',[2],'Phase and Morphology; Figure1','Explicit undoped and0.16Mn representatives have measured zinc-blende XRD and near-spherical about8nm TEM/HRTEM; other nominal dopings described as similar but patterns not shown.')],
 'Named doping endpoints directly linked; other concentration phases are source assertions, not individually shown here.', ['Feed doping and measured incorporated composition must not be equated.','Full spectral/concentration series and transferred-sample pages unchecked.'])
add(74,'Boron-Doped Graphene Quantum Dots for Selective Glucose Sensing Based on the Abnormal Aggregation-Induced Photoluminescence Enhancement',
 [e('main',[2,3],'Experimental Section','Explicit graphene/B2O3 thermal treatment, oxidation, hydrothermal cutting at200C11.5h and dialysis; modified-Hummers GO starting material is cited rather than detailed here.')],
 [e('main',[3,5],'Figures1 and3; structural discussion','Named BGQDs have TEM/AFM, broad diffraction/interlayer-spacing and Raman/XPS evidence. Boron bonding assignments and drawn graphene motif are interpretations, not a resolved atom-position model.')],
 'Prepared BG/BGQD states separately identified in structure comparisons; precursor GO procedure gap remains.', ['Acid oxidation total volume and upstream GO protocol not established by inspected sections.','Do not turn schematic carbon/boron bonding network into measured coordinates.','Remaining SI and aggregation conditions unchecked.'],level='measured_disordered_carbon_structure_morphology_candidate')
add(77,'One-Step Synthesis of Water-Soluble Quantum Dots from Ag2S and AgInS2 QDs',
 [e('main',[2],'Experimental Section','Explicit aqueous silver acetate/indium nitrate/L-cysteine recipe; three reaction temperatures, workup and powder characterization. Nominal Ag/In/S ratio is stated; no independently printed cysteine charge added here.')],
 [e('main',[2,3],'Figures1-2','Temperature/time-labelled XRD/EDS and TEM/HRTEM panels distinguish Ag2S at80/90C and100C up to3h from AIS at100C4h.')],
 'Direct temperature/time-to-phase/morphology mapping; phase labels not borrowed across the conversion boundary.', ['No local SI available.','Caption/paragraph differ in one EDS time reference; preserve before detailed variant extraction.','Full time series and photocatalysis material states unchecked.'],pairing='Main title/authors/content confirmed; no local SI')
add(79,'2D Nanosheets of Topological Quantum Materials from Homologous (Bi2)m(Bi2Se3)n Heterostructures: Synthesis and Ultralow Thermal Conductivity',
 [e('main',[2,3],'Experimental Section; Synthesis','Three explicit BiSe/Bi4Se3/Bi2Se3 composition recipes at120C1.5h in oleylamine/phenanthroline; washed/dried nanosheets distinct from later spark-plasma-sintered specimens.')],
 [e('main',[3,4],'PXRD assignment; Figure3','Measured PXRD, HRTEM, AFM and HAADF-STEM/line profile support named nanosheet phases and layer stacking. BiSe image visually checked; measured layer thicknesses do not provide full3D atom coordinates.')],
 'Explicit composition routes map to named nanosheet characterization; separate nanosheets from SPS transport specimens and bulk reference models.', ['Main crystal-model/cell descriptions cite prior structures.','Remaining SI and Bi4Se3 image details unchecked.','No full refined coordinate table found in inspected pages; this is not an all-source absence claim.'],coordinates='measured_layer_stacking_images_present; no_full_atom_coordinate_dataset_established',level='measured_phase_layer_stacking_morphology_candidate')
add(80,'Synthesis of Wurtzite In and Ga Phosphide Quantum Dots Through Cation Exchange Reactions',
 [e('main',[8],'Materials and Methods','Explicit Cu3P template synthesis, In/Ga precursors, repeated InP/GaP exchange, alloy routes and shelling; quantitative reaction temperature/time/workup provided.')],
 [e('main',[3],'Figure1-linked results','Cu3P-2.25 and InP-2.25 named template/product link, repeated-exchange residual-Cu and size comparisons, measured XRD/HRTEM support wurtzite phase.'),e('main',[8],'Characterization','Fractional coordinates expressly obtained from Materials Project mp-8882/mp-966800 and combined with literature cell parameters for VESTA/Mercury simulations.')],
 'Strong named template-to-product measured phase/morphology link; database-coordinate models are explicitly external.', ['SI variant tables and full Ga/alloy/shell figure mapping remain unchecked.','Printed GaP precursor amount uses Cu rather than Cu3P basis in one sentence; preserve for full extraction.','Do not present database atomic positions as measured in these products.'],coordinates='external_Materials_Project_fractional_positions_for_reference_models; current_measured_phase_only')
