from pathlib import Path
import json,hashlib,datetime
A=Path(__file__).resolve().parent;B=A.parent
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
C=B/'canonical-proposal/v1';P=B/'public-review-proposal/v1'
freeze=C/'package-manifest.json';manifest=load(freeze)
assert sha(freeze)=='d095fb8c95ada7a91831731ab86af875c9ed913ed33e5a498a338eb3e370b0e6'
bound=dict(manifest['bound_files'])
for p,h in bound.items():assert Path(p).is_file() and sha(Path(p))==h,p
transport=load(A/'transport-checks-v1.json');readerchecks=load(A/'reader-checks-v1.json');runtime=load(A/'runtime-schema-checks-v1.json')
assert not transport['failures'] and not readerchecks['failures'] and runtime['status']=='passed'
reader=load(P/'lian2021.json');records={p.stem:load(p) for p in C.glob('lian-*.json')}
assert readerchecks['reader_sha256']==sha(P/'lian2021.json')==manifest['reader_sha256']
assert transport['record_hashes']=={rid:sha(C/(rid+'.json')) for rid in records}
manual=[
('Preparation and material roles','All 16 record contexts and 21 operation descriptions, dependencies, inputs, outputs, retained fractions, materials, stocks and scoped quantities read. Two literature routes and the explicit B variant remain distinct from six procedures and seven observations.'),
('Bulk A/B preparation','A uses 2 mmol cation salt/1 mmol SbCl3/800 microlitres DMF and four-day room-temperature evaporation. B changes the cation charge to 1 mmol and explicitly inherits the remaining framework; no invented independent batch or absolute room temperature.'),
('Nanocrystal preparation','1 mmol cation salt/0.5 mmol SbCl3 in 2000 microlitres DMF; 500 microlitre aliquot into 5 mL toluene/500 microlitres oleic acid; 7000 rpm for 3 min. Solvent charge is not a calibrated final stock volume; no exact aliquot mmol, bulk RT inheritance, wash or drying procedure is fabricated.'),
('Material grades and utilities','All 45 material slots preserve original material names and scope notes: DMF >=99.8%, SbCl3 99.98%, cation salt 97%, toluene >=99.5%, technical oleic acid 90%, approximate PS Mw with unstated unit. Liquid nitrogen is an instrumental coolant; nitrogen is restricted to TGA.'),
('Film procedures','The five composite blue/yellow mass-part ratios 1/0, 1/3, 1/2, 2/3 and 0/1 remain a series, not five fabricated independent recipes. Stirring is 20 min. Glass is retained as a casting input but excluded from the peeled-film material ancestry.'),
('Separate spin coating','2/1 mmol salts in 1000 microlitres DMF; 200 microlitre aliquot, 2000 rpm/40 s, 80 degC/30 min. Missing composite solvent amounts and drying conditions are explicitly scoped to the other procedure, not applied as spincoat missingness.'),
('Acquisition','All 21 operations checked against the relevant main pp.6-7 methods and audited source objects. N2 is restricted to TGA, XPS has no atmosphere claim. The 300 kV TEM setting and no grid/preparation inference are retained.'),
('Sample-state boundaries','Bulk A, bulk B, NC family, dried NC powder, colloidal settling, spin-coated film, composite ratio series and beta-film test remain source contexts. Physical cross-technique identity remains unproved. No beta-film identity is assigned to one numbered blend.'),
('Bulk and NC optical results','Bulk A PLQE 96.8% and dried NC PLQE 89.3% remain separated; B non-emission is not a zero PLQE. Nanosecond and microsecond channels and monitored wavelengths retain their correct contexts.'),
('Size and microscopy','6.43 nm mean and 6.43 +/-0.17 nm SI value retain the unknown uncertainty definition and broad distribution. HRTEM 3.4 angstrom (224) and 20/5 nm panel scale bars remain imaging observations, not particle coordinates or SAED.'),
('Stability','Three-month bulk air storage, five-minute toluene settling and qualitative several-month dried-powder stability remain separate metrics. No common degradation rate or controlled humidity/irradiation condition is inferred.'),
('Crystallographic context','Bulk A P-1 and bulk B P21/c remain separate. The nine printed tables retain all 311 rows/891 cells; A/B S1 columns now map explicitly to bulk-a-crystal and bulk-b-crystal.'),
('Numerical table transport','Every source table cell was mechanically compared to its canonical and reader field, including 885 numerical/bound entries and six categorical cells, raw tokens, scaled uncertainties, range/exclusive-bound flags and table locators. This is downstream transport verification, not a repeated independent visual transcription of all SI cells.'),
('Coordinate and ADP limits','S6/S7 have 32/36 heavy-atom rows; the literal U11,U22,U33,U23,U13,U12 order, 1e-4 coordinate and 1e-3 displacement scaling, negative/unwrapped positions and signed off-diagonal values remain. No H/occupancy completion, ZIP/CIF, nanocrystal atomistic model or DFT eligibility is claimed.'),
('Local geometry conflict','The B main-text distortion/mean-distance set is not assigned to one of its two independent Sb sites; all individual table sites remain intact. No all-bond averaging is asserted to reproduce the reported value.'),
('Photophysical models','Activation energy, Huang-Rhys/phonon parameters and singlet/triplet assignments remain author fits/interpretations. Literal source equations and original crops remain accessible without invented curve arrays.'),
('DFT and symmetry','A 4x4x4 and B 2x4x4 meshes, 400 eV cutoff and force <0.01 eV/angstrom are retained. Computed PBE/HSE06 gaps are not measured optical edges. Both space groups are centrosymmetric; the parity interpretation does not declare A noncentrosymmetric.'),
('Radioluminescence','0.4 MeV,16 kW,400 Gy/s remain acquisition settings. Bulk and flexible-film demonstrations do not become absolute scintillation yield, detection limit or radiation-aging measurements.'),
('Reader prose and section placement','All 224 item titles/texts and remaining-gap/conflict prose read. Structure/size/TEM and optical/thermal cards are classified by their content. Figure 5 correctly describes photographs and spectra, with no numerical film chromaticity claim.'),
('Original images and evidence','All 53 selected source crops viewed on nine contact sheets; Figure 5 additionally reopened at native resolution. Hash, crop rectangle, document role, page, source hash, product links and existing record links checked. No new plot or whole-page attachment is introduced.'),
('References and missing attachments','All 30 bibliographic items remain uninspected cited-context records. The locally supplied 8-page main and 26-page SI PDF are supported by the passed source audit; cited ZIP and MP4 remain unlocated and unread.'),
('Training and publication boundary','All requested_tasks remain empty, records imported_unreviewed, structure_assets empty and actual eligibility() results false. Reader visual/publication flags remain false. No private full-text or wholepage attachment path is present in the reader.'),
]
pre=load(A/'pre-freeze-reading-notes.json')
resolved=[]
for finding in pre['downstream_findings']:
    resolved.append({**finding,'status':'resolved_in_first_author_freeze','verification':'Rechecked against the exact frozen record/reader hashes and independently executed transport checks.'})
source_scope={'dependency':'The separate passed source audit by /root/norberg2004_extract covers all 34 supplied PDF pages, source facts and original numerical transcription. This audit checks the downstream canonical/reader projection independently and reopens the relevant source scope below.','main_text_pages_actually_reread':[2,3,4,5,6,7],'main_page_images_actually_viewed':[2,3,4,5,6,7],'si_text_pages_actually_reread':[2,3],'source_fact_claims_and_definitions_read':57,'source_fact_quantities_checked':134,'selected_original_crops_viewed':53,'contact_sheets_viewed':9,'native_individual_crop_reopened':'figure-5.png','table_cell_transport_checked':891,'full_si_cell_by_cell_visual_reread_in_this_audit':False}
extras=[freeze,A/'check_transport.py',A/'check_reader.py',A/'check_runtime_schema.py',A/'transport-checks-v1.json',A/'reader-checks-v1.json',A/'runtime-schema-checks-v1.json',A/'preparation-checkpoint.json',A/'pre-freeze-reading-notes.json',Path(__file__)]
extras += [B/f'private/text/main-{n:02}.txt' for n in range(2,8)] + [B/f'source-render/main-{n:02}.png' for n in range(2,8)]
extras += [B/f'private/text/si-{n:02}.txt' for n in (2,3)] + [B/f'private/crop-contact-{n:02}.png' for n in range(1,10)]
for p in extras:bound[str(p)]=sha(p)
for p,h in runtime['validator_hashes'].items():assert sha(Path(p))==h;bound[p]=h
out={'schema':'mattersyn.independent-canonical-reader-audit/1','paper_id':'lian2021','doi':'10.1021/acsami.1c18038','auditor':'/root/peng1998_reader_assets','author':'/root/backlog_eta','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'passed','proposal_freeze_sha256':sha(freeze),'canonical_manifest_sha256':sha(C/'record-manifest.json'),'reader_manifest_sha256':sha(P/'reader-manifest.json'),'reader_sha256':sha(P/'lian2021.json'),'source_freeze_sha256':manifest['source_freeze_sha256'],'source_audit':manifest['source_audit'],'scope':'Independent canonical/reader scientific projection, transport, specimen/operation scope, original-image/field linkage, schema and empty training gates. No molecular/apparatus/product-model/integrated browser or publication approval.','counts':{**manifest['canonical_counts'],**readerchecks['counts'],'source_table_rows':311,'source_table_numeric_or_bound_cells':885,'source_table_text_cells':6,'references':30,'manual_scientific_scopes':len(manual)},'supporting_checks':{'canonical_transport':transport['check_count'],'reader_transport':readerchecks['check_count'],'frozen_file_hashes':len(manifest['bound_files']),'record_schema_semantic_eligibility_executions':16,'current_reader_validator_execution':1,'mechanical_total':transport['check_count']+readerchecks['check_count']+len(manifest['bound_files'])+17},'manual_checks':[{'id':f'manual-{i+1:02}','title':title,'finding':text,'status':'passed'} for i,(title,text) in enumerate(manual)],'actual_source_scope':source_scope,'resolved_pre_freeze_findings':resolved,'open_findings':[],'retained_source_conflicts':reader['evidence_conflicts'],'remaining_gates':['Independent reagent/component viewers and exact material/stock bindings','Independent stage-specific apparatus','Any proposed crystal/product-model qualification and mapping','Site integration and actual browser testing','Publication and any separately authorized training admission'],'site_modified':False,'author_inputs_modified':False,'training_admission_granted':False,'bound_files':bound}
dest=A/'independent-audit-v1.json';dest.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
md='# Lian 2021 canonical/reader independent audit\n\nPassed for the frozen private canonical/reader proposal; no open findings in this scope.\n\n'
md+=f'- Proposal SHA256: `{sha(freeze)}`\n- Reader SHA256: `{out["reader_sha256"]}`\n- Audit JSON SHA256: `{sha(dest)}`\n- Records: 16; operations: 21; material slots: 45; stocks: 5; contexts: 44.\n- Reader: 224 items and 1,465 exact canonical fields; all 57 facts/134 source quantities, 167 inventory units, nine tables/891 cells, 53 crops and 30 references remain reachable.\n- Independent supporting checks: {out["supporting_checks"]["mechanical_total"]}; manual scientific scopes: {len(manual)}; bound files: {len(bound)}.\n\n'
md+='The five bounded pre-freeze scope/presentation findings were corrected before the first author freeze. No source numbers or original asset bytes were changed. Current Site schema/eligibility and reader validators passed against an isolated private projection.\n\n'
md+='This downstream audit relied on the distinct passed source audit for the full 34-page source transcription. I independently reread/viewed main pages 2–7, reread SI methods pages 2–3, viewed all 53 crops on nine contact sheets and reopened Figure 5 at native size. All numerical table cells were transport-checked; this is not a claim of a second full cell-by-cell visual transcription.\n\n'
for title,text in manual:md+=f'**{title}.** {text}\n\n'
md+='Molecular, apparatus, crystal/product-model, integrated browser and publication gates remain separate. No Site, source/canonical author input, ledger or training admission was changed.\n'
(A/'independent-audit-v1.md').write_text(md,encoding='utf-8')
print(json.dumps({'status':'passed','audit_path':str(dest),'audit_sha256':sha(dest),'bound_files':len(bound),'checks':out['supporting_checks'],'open_findings':[]},indent=2))
