import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parent
load=lambda p:json.loads((R/p).read_text(encoding='utf-8'))
dump=lambda p,x:(R/p).write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding='utf-8')
docs=load('source-manifest.json')
sections={
 'main':[['Bibliographic identity, abstract and graphical abstract','Introduction: magnetic proximity, exchange bias and size limitations'],['Introduction continuation: interface sharpness and cited prior core–shell work','Experimental materials and CoO core synthesis','CoO/CoFe2O4 synthesis start'],['Shell synthesis continuation and aliquot workup','XRD, TEM, SQUID and magnetic heating methods','Equations 1 and 2','XRD Figure 1 and Table 1'],['Lattice strain interpretation and explicit 30 min selection','Figure 2 TEM/HRTEM and size/fringe results','Magnetic results, blocking and suspected uncoated phase','Cooling protocol in results'],['Figures 3 and 4, exchange bias/coercivity field and temperature dependence','Heating assay and settling caveat'],['Heating outlook and conclusions','Matched SI availability statement','Author information and acknowledgments','References 1–24 start'],['References 24 continuation through 54']],
 'si':[['Title/authors/affiliations and correspondence; matched identity'],['Figure S1 size histograms','Figure S2 HRTEM, fringe spacings and contrast'],['Figure S3 hysteresis and FC/ZFC magnetization','Figure S4 heating curve and initial slope']]}
unresolved={('main',2):['Unspecified acetate hydration and procedural fields retained.'],('main',3):['Cooling start conflicts with results; Table 1 size limitation and parenthetical size semantics retained.'],('main',4):['Unknown ± statistic, no physical batch IDs; interface sharpness/trace CoO are interpretations.'],('main',5):['No raw curve arrays; SLP uses all powder despite settling.'],('main',6):['References discussed are not independently read in this package.'],('main',7):['References discussed are not independently read in this package.'],('si',3):['Figure S3a caption and plot legend reverse the temperature/color assignments.']}
for d in docs:
 d['identity_verification']='Main DOI/title/authors/journal verified on first page; SI exact title/authors/affiliations and listed contents match main associated-content statement. SI itself does not print a DOI.'
 for p in d['pages']:
  p.update(text_read=True,visual_review=True,sections=sections[d['role']][p['page']-1],unresolved=unresolved.get((d['role'],p['page']),[]))
  if p.get('render_notes'):p['visual_assessment']='Renderer warning retained; displayed graphical abstract and critical symbols inspected and readable. Crops independently visually checked.'
dump('source-manifest.json',docs)
assets=load('figure-provenance.json')
for a in assets:a['visual_review']=True
dump('figure-provenance.json',assets)
ad={a['id']:a for a in assets}
core='saha-2019-coo-core';grow='saha-2019-coo-cofe2o4-seeded-growth';chars='saha-2019-structural-magnetic-characterization';heat='saha-2019-magnetic-heating-assay'
c='saha2019-coo-core';a15='saha2019-core-shell-15min';a30='saha2019-core-shell-30min'
def item(id,label,loc,caption,samples,facts,gaps=None):
 return {'id':id,'label':label,'document_role':ad[id]['document_role'],'page':ad[id]['page'],'source_locators':[loc],'caption_paraphrase':caption,'sample_links':samples,'quantitative_facts':facts,'gaps':gaps or [],'reviewed':True,'text_reviewed':True,'visual_reviewed':True,'original_crop':ad[id]['asset'],'asset_provenance':ad[id]}
figs=[
item('graphical-abstract','Graphical abstract','main p.2421','Summary schematic of CoO core/cobalt-ferrite shell, 2 K hysteresis and HRTEM inset.',[a30],['Hysteresis curves labeled 0, 30 and 70 kOe cooling.','Inset repeats 2.43 Å (111), 2.58 Å (311) and a 5 nm scale.'],['Schematic is authors’ illustration, not atomic coordinates or an additional experiment.']),
item('figure-1','Figure 1','main p.2423','Powder diffraction of core, 15 min and 30 min products alongside bulk reference patterns.',[c,a15,a30],['Displayed 2θ range 20–70 degrees.','CoO reference indices (111), (200), (220).','CoFe2O4 reference indices (220), (311), (222), (400), (422), (511), (440).','Dots identify CoO, stars identify cobalt ferrite; relative ferrite features grow with annealing time.'],['Phase coexistence alone does not establish core–shell geometry. Bulk patterns are references, not measured independent colloidal syntheses.','Raw intensity arrays absent; no curve digitization.']),
item('figure-2','Figure 2','main p.2424','TEM panels a/b show core/30 min heterostructures; HRTEM panels c/d show corresponding crystalline regions.',[c,a30],['TEM scale bars 20 nm; HRTEM scale bars 5 nm.','Core and core region fringe (111) = 2.43 Å; shell (311) = 2.58 Å.','Associated text: core 12 ± 3.2 nm; whole heterostructure 14.9 ± 3.6 nm.','Approximately 300–350 particles analyzed; precise count for each cohort not stated.','Associated text describes nearly spherical particles and an approximately 1.5 nm shell.'],['± statistic not defined. Images not independently segmented; particle distributions are author-reported.','30 min assignment is explicit in p.2424 text; not assigned to 15 min.']),
item('figure-3','Figure 3','main p.2425','Hysteresis loop shifts under varied cooling field and measurement temperature.',[a30],['a/b/c: 2 K, 10/30/70 kOe field cooling respectively, compared with 0 kOe.','d/e/f: 10/100/200 K with 70 kOe field cooling and ZFC comparison.','Plots show H −40 to +40 kOe and magnetization emu/g.','Largest stated exchange-bias value is 5.6 kOe at 2 K.'],['Cooling-start conflict: methods RT/300 K, results 400 K.','No raw magnetization curves or physical batch IDs supplied.']),
item('figure-4','Figure 4','main p.2425','Exchange bias versus cooling field and exchange bias/coercivity versus measurement temperature.',[a30],['Panel a: 2 K, cooling-field range 0–70 kOe; graphical settings include 0/10/30/50/70 kOe.','Panel b: exchange bias red, coercivity black; solid lines are guides to the eye.','Text gives HE 5.6 kOe and Hc 10.5 kOe at 2 K; nearly vanishing values near room temperature.','Plot contains error bars but their statistical definition is not supplied.'],['50 kOe field appears in plot; method paragraph only lists 10, 30, 70 kOe. Do not fabricate another synthesis or full measured row.','Numerical graph points/error-bar arrays have not been digitized.']),
item('figure-s1','Figure S1','SI p.S2','Size distributions for the CoO core and selected core–shell cohort.',[c,a30],['Core label 12 ± 3.2 nm; heterostructure label 14.9 ± 3.6 nm.','Size axis nm; counts lack numerical y-axis calibration.'],['± meaning, fit family and exact individual counts not stated. Histograms are not independent synthesis trials.']),
item('figure-s2','Figure S2','SI p.S2','Two additional core–shell HRTEM views; one marks fringe spacings, the other emphasizes core/shell contrast.',[a30],['Both scale bars 5 nm.','Marked core (111) 2.43 Å and shell (311) 2.58 Å.'],['No measured atomic coordinates, composition line profile or diffraction spot dataset.']),
item('figure-s3','Figure S3','SI p.S3; main p.2424','Hysteresis at two temperatures with low-field inset and FC/ZFC magnetization versus temperature.',[a30],['Legend: black 300 K and olive 2 K; caption reverses these colors.','Body text associates approximately 95 Oe coercivity with room temperature.','At 2 K magnetization not fully saturated even at 4 T.','Magnetization-temperature measurement uses 200 Oe.','ZFC maximum is 292 K; a shoulder spans 200–250 K.'],['Color/temperature contradiction retained; do not assign curves solely by caption colors.','200–250 K shoulder attributed tentatively to uncoated CoO; no phase fraction or distinct synthesis sample established.']),
item('figure-s4','Figure S4','SI p.S3; main pp.2423,2425','Heating curve versus exposure time with red initial-slope fit.',[a30,'saha2019-heating-suspension'],['Fit annotation dT/dt=0.034; axes imply °C/s.','Main methods: 0.8 mg powder in 2 mL water, 500 kHz, 37.4 kA/m.','Authors report approximately 355 W/g using Equation 1.'],['Particles settle in water; active suspended mass uncertain.','Fit window, raw temperature array and replicate uncertainty absent. Heating sample mapped to 30 min/high-EB cohort, exact vial not known.'])]
table=item('table-1','Table 1','main p.2423','XRD-derived crystallite sizes and cubic lattice parameters; parentheses contain TEM sizes.',[c,a30],['CoO core: 14.7 nm XRD, parenthetical 12 nm TEM, lattice a=4.258 Å.','CoO phase in 30 min heterostructure: 16.4 nm XRD, parenthetical 14.9 nm TEM, a=4.246 Å.','CoFe2O4 phase in 30 min heterostructure: crystallite size blank, a=8.373 Å.'],['16.4 nm retained despite adjacent overlap caveat.','The 14.9 nm TEM value denotes whole core–shell particles in Figure 2/S1; do not relabel it as embedded CoO-core diameter.','No inferred value fills the blank CoFe2O4 size cell.'])
table['columns']=['phase/sample','crystallite_size_nm','TEM_parenthetical_nm','lattice_a_angstrom']
table['rows']=[{'sample_id':c,'phase':'CoO','crystallite_size_nm':14.7,'TEM_parenthetical_nm':12,'lattice_a_angstrom':4.258},{'sample_id':a30,'phase':'CoO in core–shell','crystallite_size_nm':16.4,'TEM_parenthetical_nm':14.9,'lattice_a_angstrom':4.246,'TEM_scope':'whole core–shell particle by prose/Figure 2/S1; row juxtaposition is misleading if read as core-only size'},{'sample_id':a30,'phase':'CoFe2O4 in core–shell','crystallite_size_nm':None,'TEM_parenthetical_nm':None,'lattice_a_angstrom':8.373}]
eqs=[item('equation-1','Equation 1','main p.2423','Specific loss power from initial heating slope.',[a30],['SLP = (C V_s / m) × (dT/dt)','C_water = 4185 J L^-1 K^-1; V_s=2 mL; m=0.8 mg total powder.'],['Uses solution volumetric heat capacity and all weighed powder. Authors note settling; no measured suspended-mass correction.']),item('equation-2','Equation 2','main p.2423','Cubic interplanar-spacing relation used to obtain lattice parameter.',[c,a30],['d = a / sqrt(h^2+k^2+l^2)','d is interplanar spacing; a cubic lattice parameter; h,k,l plane indices.'],['Assumes cubic phase assignment. No full structural refinement or atomic coordinates.','Scherrer analysis is named separately; a numerical shape factor or explicit Scherrer equation is not supplied.'])]
conflicts=[
 {'id':'fc-initial-temperature','source_locators':['main p.2423 Characterization','main pp.2424–2425 magnetic results'],'issue':'Methods specify cooling from RT (300 K); results specify 400 K.','handling':'Both retained as distinct source statements in characterization operation; no averaging or corrected protocol guessed.'},
 {'id':'si-s3-temperature-colors','source_locators':['SI p.S3 Figure S3a graph legend and caption'],'issue':'Legend black=300 K, olive=2 K; caption black=2 K, dark yellow=room temperature.','handling':'Original graphic retained with a visible conflict note; numerical text observations preserved, color-specific curves not exported as certain temperature labels.'},
 {'id':'xrd-overlap-size','source_locators':['main p.2423 discussion and Table 1'],'issue':'Prose limits approximate crystallite size to core-only because peaks overlap, while Table 1 also gives 16.4 nm for CoO in core–shell.','handling':'16.4 nm stored as author-derived conditional value with caveat; not presented as reliable independent core diameter.'},
 {'id':'table-tem-scope','source_locators':['main p.2423 Table 1','main p.2424 Figure 2 and SI p.S2 Figure S1'],'issue':'14.9 nm is parenthesized on the CoO-from-core-shell row but identified elsewhere as whole-particle TEM size.','handling':'14.9 nm linked only to whole core–shell diameter; no embedded-core diameter asserted.'},
 {'id':'slp-normalization','source_locators':['main p.2423 Equation 1','main p.2425 heating discussion'],'issue':'All 0.8 mg weighed powder enters SLP normalization although authors report insolubility and sedimentation.','handling':'Approximately 355 W/g remains author-derived using stated total mass; no active-fraction or clinical-performance correction.'},
 {'id':'xrd-instrumental-broadening-explanation','source_locators':['main p.2423 discussion'],'issue':'Authors say Scherrer sizes are larger than TEM because instrumental broadening was not considered.','handling':'Preserve as author explanation, not an independently verified diffraction correction. No raw peak widths allow reanalysis.'}]
inventory=[{'id':'core','label':'Purchased acetates / CoO seed synthesis, wash and storage','record_ids':[core],'status':'source_reviewed_partial_protocol','source_locators':['main p.2422 Materials and Synthesis'],'gaps':['No precursor-preparation synthesis; chemicals purchased.','Acetate hydration, full workup and storage settings unknown.']},{'id':'growth','label':'CoO seed loading plus independently prepared Co/Fe feed and two annealing aliquots','record_ids':[grow],'status':'source_reviewed_partial_protocol','source_locators':['main pp.2422–2423 shell synthesis'],'gaps':['15/30 min aliquots are related products, not two independent synthesis records.','Injection, aliquot and purification details remain incomplete.']},{'id':'characterization','label':'XRD/TEM/SQUID/DC magnetization','record_ids':[chars],'status':'shared_procedure_not_training_synthesis','source_locators':['main pp.2423–2425','Figures 1–4 and SI S1–S3'],'gaps':['Cooling conflict and missing scan/mounting details.']},{'id':'heating','label':'Water-suspension AC heating assay','record_ids':[heat],'status':'assay_not_training_synthesis','source_locators':['main p.2423 and p.2425; SI S4'],'gaps':['Water transfer chemistry and active suspended mass not measured.']},{'id':'pure-ferrite','label':'Standalone pure CoFe2O4 route','record_ids':[],'status':'not_reported_in_this_paper','source_locators':['main pp.2422–2423'],'gaps':['No isolated pure-CoFe2O4 recipe may be inferred from this shell-growth recipe.']}]
intuition=[
 {'id':'seeded-geometry','title':'Why grow a ferrite shell on CoO?','author_evidence':'XRD detects two phases, with stronger ferrite features at longer annealing; TEM/HRTEM show a larger particle and different inner/outer fringes.','author_interpretation':'Seed growth forms an inverted AFM-core/FiM-shell structure and allows the CoO core to remain highly crystalline.','curator_caveat':'XRD alone does not prove geometry, as the paper explicitly acknowledges. No independent nucleation fraction is quantified.','outlook':'Spatially resolved composition could test interface width and any separately nucleated ferrite. This is an unperformed follow-up, not a source result.','source_locators':['main pp.2422–2424; Figures 1–2; SI S2']},
 {'id':'interface-strain','title':'Lattice shifts and the proposed interface strain','author_evidence':'CoO lattice a changes from 4.258 to 4.246 Å; shell phase a=8.373 Å.','author_interpretation':'Authors attribute the CoO shift to lattice mismatch and strain at the core–shell interface.','curator_caveat':'The paper does not provide an atomically refined strain map or interface composition profile.','outlook':'Separate strain and chemical intermixing measurements would test this explanation.','source_locators':['main pp.2423–2424; Table 1']},
 {'id':'sharp-interface-eb','title':'Exchange bias as an indirect probe of the interface','author_evidence':'The selected cohort shows HE=5.6 kOe at 2 K and high coercivity, with field-cooling dependence.','author_interpretation':'Crystalline CoO, a thin ferrite shell and a sharp interface stabilize exchange coupling; authors explicitly use EB as an indirect interface-quality indicator.','curator_caveat':'Interface sharpness is an interpretation supported indirectly; no measured atom-by-atom interface or controlled roughness series is supplied. Initial cooling temperature conflicts across sections.','outlook':'A controlled interface-composition series and independent chemical mapping could distinguish proposed mechanisms.','source_locators':['main pp.2422,2424–2425; Figures 3–4']},
 {'id':'size-and-uncoated-core','title':'Broad size distributions and magnetic heterogeneity','author_evidence':'Means 12 and 14.9 nm have reported ± spreads of 3.2 and 3.6 nm; blocking peak 292 K and a 200–250 K shoulder.','author_interpretation':'Authors associate broad heterostructure size with the core distribution and suggest a trace uncoated-CoO contribution to the shoulder.','curator_caveat':'The ± statistic and uncoated-phase fraction are not measured/defined. 291 K is a literature bulk Néel reference, not a new sample measurement.','outlook':'Particle-resolved morphology and composition, together with magnetic distribution analysis, could test the uncoated-core assignment.','source_locators':['main p.2424; SI S1,S3']},
 {'id':'ligand-context','title':'What is known about the reaction medium?','author_evidence':'Commercial OA/OlAm and Co(II)/Fe(II) acetates are used in separately degassed mixtures and staged thermal treatment.','author_interpretation':'The authors describe thermal decomposition and controlled seed growth; they do not report a molecular precursor-conversion mechanism.','curator_caveat':'Do not invent metal–ligand connectivity, hydrate composition, oxygen source, surface ligand coverage or an experimentally demonstrated ligand-specific causal role.','outlook':'Speciation and reaction-kinetics measurements would be needed to make those mechanistic assignments.','source_locators':['main p.2422 Materials; pp.2422–2423 synthesis']},
 {'id':'heating-outlook','title':'Heating performance is limited by dispersion knowledge','author_evidence':'Approximately 355 W/g is calculated from a 0.034 °C/s initial slope at 500 kHz and 37.4 kA/m; particles settle in water.','author_interpretation':'Authors propose that improved water dispersibility could increase apparent SLP by preventing sedimentation.','curator_caveat':'This is a proposed improvement. No ligand-exchange protocol, stable aqueous formulation, active-mass measurement or biological outcome is demonstrated.','outlook':'A controlled water-transfer study and mass-resolved heating assay could test the proposal.','source_locators':['main pp.2423,2425–2426; Equation 1; SI S4']}]
characterization=[
 {'technique':'XRD','source_locators':['main p.2423; Figure 1; Table 1; Equation 2'],'sample_ids':[c,a15,a30],'conditions':'Bruker D8 Advance; Cu Kα 1.5406 Å.','reported_assignment':'Cubic CoO; cubic inverse-spinel CoFe2O4. No space group numbers or measured CIF.','gaps':['Raw peaks/scan settings and reliable independent shell crystallite size absent.']},
 {'technique':'TEM/HRTEM and image size distributions','source_locators':['main pp.2423–2424; Figure 2; SI S1,S2'],'sample_ids':[c,a30],'conditions':'Technai F30 UHR, 200 kV field emission, bright field; source calls grids Cu-coated holey carbon. About 300–350 particles analyzed.','gaps':['Exact per-cohort counts, spread statistic, deposited specimen preparation and atomic composition maps absent.']},
 {'technique':'SQUID VSM / DC magnetization','source_locators':['main pp.2423–2425; Figures 3,4; SI S3'],'sample_ids':[a30],'conditions':'Quantum Design; 2 K/300 K plus temperature series; ZFC and 10/30/70 kOe FC; 200 Oe susceptibility.','gaps':['FC initial-temperature conflict, sweep settings and raw arrays absent.']},
 {'technique':'Magnetic heating / specific loss power','source_locators':['main pp.2423,2425; Equation 1; SI S4'],'sample_ids':[a30,'saha2019-heating-suspension'],'conditions':'0.8 mg powder / 2 mL water, EASYHEAT Ameritherm induction coil, thermometer, 500 kHz, 37.4 kA/m.','gaps':['Sedimentation, unmeasured suspended mass and unspecified heat-loss treatment.']},
 {'technique':'Not presented','source_locators':['all main/SI pages'],'scope':'No SAED, Raman, optical absorption/emission, XPS/XAS, EDS elemental map, full crystallographic refinement or atomically resolved composition series is supplied.'}]
refs=[{'references':[24,25],'bibliography':'Lima et al., Chem. Mater. 2012, 24, 512–516; Lavorato et al., Nanotechnology 2014, 25, 355704.','role':'Earlier CoO/CoFe2O4 core–shell studies cited in introduction, not an adopted recipe with inherited quantities.','status':'Original methods not read in this package.'},{'references':[20],'bibliography':'Lottini et al., Chem. Mater. 2016, 28, 4214–4222.','role':'Different-composition inverted core–shell exchange-bias precedent.','status':'No quantities or structures borrowed.'},{'references':[48,49],'bibliography':'Ghosh et al., Chem. Mater. 2005, 17, 2348–2352; Sanpo et al., J. Nano Res. 2013, 25, 110–121.','role':'Lattice/magnetic comparison; reference 49 is copper-substituted cobalt ferrite, not a replacement method.','status':'Bibliography and current-paper claims read; originals unresolved here.'},{'references':[51],'bibliography':'Baaziz et al., Chem. Mater. 2014, 26, 5063–5073.','role':'Potential distinct pure-CoFe2O4/heterostructure literature route.','status':'Not inspected; no recipe quantities inherited.'},{'references':[42,43,53,54],'role':'Interface theory/intermixing and prior heating-performance comparisons.','status':'Current authors’ interpretations identified; underlying originals not independently verified in this package.'}]
records=[json.loads(f.read_text(encoding='utf-8')) for f in sorted((R/'canonical').glob('*.json'))]
coverage={'paper':{'doi':'10.1021/acs.jpcc.8b11124','title':'Interface Modeling Leading to Giant Exchange Bias from the CoO/CoFe2O4 Quantum Dot Heterostructure','authors':'Avijit Saha; Siddhartha Sohoni; Ranjani Viswanatha','journal':'Journal of Physical Chemistry C','year':2019,'volume':123,'pages':'2421–2427','published_online':'2019-01-02','url':'https://doi.org/10.1021/acs.jpcc.8b11124'},'documents':docs,'recipe_inventory':inventory,'figures':figs,'tables':[table],'equations':eqs,'schemes':[],'characterization_inventory':characterization,'quantitative_observations':[{'record_id':r['record_id'],**m} for r in records for m in r['measurements']],'evidence_conflicts':conflicts,'chemical_intuition':intuition,'referenced_methods_not_locally_resolved':refs,'coverage_status':{'document_reading':'complete_for_supplied_main_and_matched_si','pages_read':10,'pages_visually_reviewed':10,'numbered_figures_reviewed':8,'graphical_abstracts_reviewed':1,'tables_reviewed':1,'equations_reviewed':2,'canonical_synthesis_protocols':2,'canonical_shared_procedures_and_assays':2,'canonical_record_count':4,'source_conflicts_resolved':False,'exact_recipe_outcome_pairing_complete':False,'raw_curve_digitization_complete':False,'scope':'Whole-document section/figure/method inventory completed. Does not imply a complete executable SOP, raw numerical dataset or independent experimental validation.'},'remaining_gaps':['Source conflicts listed above remain unresolved.','Physical batch/specimen identifiers, most workup settings, acetate hydration, ligand coverage and complete surface chemistry absent.','No measured atomic coordinates/CIF or exact-structure-to-complete-recipe label.','Raw curve data, TEM individual measurements and error-bar statistics absent and not digitized.','Cited originals are not independently reviewed; separate sources must supply any standalone cobalt-ferrite recipe.','Public reuse permission for original article graphics is not established by this extraction.'],'training_note':'Two literature protocols support precursor/partial-protocol supervision and explicitly linked mean-size tasks with cohort limitations. Related 15/30 min aliquots are not independent batches. Characterization/heating procedures have requested_tasks empty. Exact structure labels remain ineligible; references/illustrations are never measured sample labels.','independent_audit':'Passed independent scientific source-consistency audit by synthesis_prior_art: all 7 main and 3 SI pages, all 12 final source crops, 4 canonical records and 19 measurements inspected; no material corrections required. See audit.md and audit.json. This is not laboratory reproduction.'}
dump('coverage.json',coverage)
print(json.dumps({'records':len(records),'observations':len(coverage['quantitative_observations']),'figures':len(figs),'tables':1,'equations':2,'pages_reviewed':10,'coverage_sha256':hashlib.sha256((R/'coverage.json').read_bytes()).hexdigest()}))
