"""Dataset discovery page, generated from validated manifest counts."""
import json
from pathlib import Path

def render(report,manifest,head,header,esc,human):
    tasks=report['eligible_by_task']
    s=head('Synthesis records')+'<body>'+header()+'''<main class="dataset-main"><div class="dataset-heading"><span class="eyebrow">MATERIALS SYNTHESIS DATASET · PILOT COLLECTION</span><h1>Synthesis records</h1><p>Individual protocols and experimental observations, with traceable sources and task-specific training exports.</p></div><div class="dataset-summary">'''
    for n,label in [(report['curated_recipes'],'Reviewed protocols and controls'),(report['published_benchmark_rows'],'Published PbS experiment rows'),(report['families'],'Material families'),(tasks['exact_structure_recipe'],'Verified exact structure–recipe pairs')]:
        s+='<div><strong>'+str(n)+'</strong><span>'+label+'</span></div>'
    s+='''</div><div class="dataset-filters"><label>Search records<input id="record-search" type="search" placeholder="Material, paper or method"></label><label>Material family<select id="family-filter"><option value="">All families</option>'''+''.join('<option>'+esc(f)+'</option>' for f in manifest['families'])+'''</select></label><label>Training task<select id="task-filter"><option value="">All records</option>'''+''.join('<option value="'+k+'">'+esc(human(k))+'</option>' for k in tasks)+'''</select></label><label>Collection<select id="type-filter"><option value="recipes">Recipes and experiment rows</option><option value="reviewed">Reviewed literature records</option><option value="benchmark">Published PbS benchmark</option><option value="procedure">Shared procedures</option><option value="all">All records</option></select></label></div><p id="record-count" class="record-count" aria-live="polite"></p><div id="catalog-results" class="record-list"></div><div class="catalog-pagination"><button id="page-prev" type="button">← Previous</button><span id="page-label"></span><button id="page-next" type="button">Next →</button></div>'''
    s+='''<section id="exports" class="record-section"><div class="section-heading"><div><h2>Dataset downloads<small>One canonical record generates each page and its permitted training views.</small></h2></div></div><div class="export-grid"><a href="data/records.jsonl" download><strong>All canonical records ↓</strong><span>JSONL · protocols, observations and shared procedures</span></a><a href="data/record.schema.json" download><strong>Record schema ↓</strong><span>Typed quantities, evidence, sample links and explicit missingness</span></a><a href="data/dataset-manifest.json" download><strong>Dataset manifest ↓</strong><span>Hashes, source groups, versions and eligibility</span></a><a href="data/validation-report.json" download><strong>Validation report ↓</strong><span>Schema and scientific referential-integrity checks</span></a></div><div class="export-grid">'''+''.join('<a href="data/exports/'+k+'.jsonl" download><strong>'+esc(human(k))+' ↓</strong><span>'+str(v)+' eligible records · JSONL</span></a>' for k,v in tasks.items())+'''</div><div class="record-notice"><strong>Scope and reuse</strong><p>The reviewed records describe literature protocols, variants and controls, not independently reproduced experiments. Shared preparation, characterization and assay procedures are separate records. The PbS collection contains 100 selected rows from one published study: 95 optical outcomes and five flagged failures. It is not 100 newly curated papers.</p><p>The PbS data are adapted from Voznyy et al. (2019), <a href="https://doi.org/10.1021/acsnano.9b03864.s002">official dataset</a>, under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>. Attribution and the noncommercial restriction travel with the exports. Changes: named columns and units, row IDs, selected subset, derived cohort labels, and null continuous targets for failure placeholders. Other article and figure rights remain separate.</p><p>All records from a connected source/recipe group stay together. The small collection and its source/lineage-group partitions do not establish reliable cross-study performance. Use a frozen, audited split manifest for any model comparison. The PbS benchmark below uses a separately documented within-study evaluation. No input examples use contextual figures or chemical-intuition text as experimental labels.</p></div></section>'''
    s+='<section class="record-section"><h2>Pilot source queue</h2><p>'+str(report.get('queue_count',0))+' remaining papers across '+str(report.get('queue_families',0))+' candidate families await full extraction. First-page screening is not recipe curation.</p><a class="data-download" href="data/pilot-source-queue.json" download>Download source queue ↓</a></section>'
    baseline=json.loads((Path(__file__).resolve().parents[1]/'dist/data/baseline-report.json').read_text(encoding='utf-8'))
    s+='''<section class="record-section"><h2>Baseline evaluation<small>PbS absorption-wavelength prediction</small></h2><p>Three compact models were evaluated using all 2,529 continuous-outcome rows from the published 2,552-row dataset. The 23 failure-coded rows were excluded from regression. The 100-page coverage subset was not used to estimate performance.</p><div class="table-scroll"><table class="reagent-table"><thead><tr><th>Evaluation</th><th>Mean predictor MAE</th><th>Ridge MAE</th><th>kNN MAE</th></tr></thead><tbody>'''
    for key,label in [('grouped_within_study_holdout','Held-out recipe groups'),('author_rule_cohort_transfer','Author-defined cohort transfer')]:
        m=baseline['evaluations'][key]['metrics'];s+='<tr><td>'+label+'</td>'+''.join('<td>'+format(m[k]['mae_nm'],'.2f')+' nm</td>' for k in ['training_mean','ridge','distance_weighted_knn'])+'</tr>'
    s+='''</tbody></table></div><p>Repeated physical recipes stay together. Scaling and parameter selection use training data only. These results concern one study and one optical property; they do not evaluate crystal-to-recipe generation, laboratory reproducibility, or cross-material generalization.</p><a class="data-download" href="data/baseline-report.json">Inspect methods, limitations and results ↗</a></section></main><script type="module" src="dataset-app.mjs"></script></body></html>'''
    return s
