from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
B=Path(__file__).resolve().parent;M=B.parents[3];MON=B.parents[1]
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def read(p):return json.loads(p.read_text(encoding='utf-8'))
source=read(B/'source-manifest.json');assert source['page_count']==1
source['pages'][0].update(text_read=True,visual_review=True)
source.update(role='main_news_article',title='Quantum Dots Meet Biomolecules',author='Mitch Jacoby',publication='Chemical & Engineering News',publication_date='1998-09-28',volume=76,issue=39,printed_page=8,doi='10.1021/cen-v076n039.p008',identity_basis='Printed title, byline, date and page visually verified. DOI/volume/issue are local bibliographic identifiers, not printed DOI evidence. SI not located or verified.',main_sha256=source['sha256'])
write(B/'source-manifest.json',source)
units=[]
def u(i,loc,summary,disposition='secondary_context_only',reason='Secondary science-news report; no independently identified physical sample, experimental acquisition data or quantitative preparation record.'):
 units.append({'id':i,'page':1,'printed_page':8,'locator':loc,'summary':summary,'disposition':disposition,'reason':reason})
u('identity','Header, title, subtitle, byline, footer','Quantum Dots Meet Biomolecules; method uses fluorescing semiconductor nanocrystals as labels. Mitch Jacoby. C&EN,28September1998,p8.','bibliographic_identity','Source identity retained; not a primary research paper.')
u('overview','Left column, opening paragraphs','Independent Indiana University and UC Berkeley biomolecular-label demonstrations; CdSe cores, Indiana ZnS shells, Berkeley ZnS or CdS shells.')
u('cited-primary-work','Left column, second paragraph','Science281,2013and2016(1998) cited as underlying studies.','unverified_primary_reference','Citation retained; underlying papers not inspected as part of this news source; do not infer DOI or procedural detail.')
u('yeung-comment','Left column, Edward S. Yeung comment','Expert commentary on a new class of labels and possible relevance to cell imaging,DNA sequencing,immunoassays.','expert_commentary','Opinions/applications do not create synthesis,measurement or success labels.')
u('mirkin-comment','Left-bottom paragraph continuing center column below schematic','Chad A. Mirkin commentary: tunable emission advantageous; quantum yield may limit assay sensitivity.','expert_commentary','No quantitative quantum yield or measured assay sensitivity supplied.')
u('photophysics-claim','Center column, Shuming Nie discussion','Claims narrower and brighter spectra than common organic dyes, inexpensive/custom/large-scale preparation; some semiconductor labels shine100timeslonger than dye molecules.','secondary_comparison','No dye-specific sample/protocol/intensity/time basis or primary curve; retain claim without a lifetime or photostability training target.')
u('surface-treatment','Center-column final paragraph continuing top-right','Nie and Chan react ZnS-capped CdSe with mercaptoacetic acid to confer water solubility and biomolecule association.','incomplete_secondary_method','No reagent charges,solvent,pH,temperature,duration,workup,coupling chemistry or sample identifiers. Not a canonical synthesis route.')
u('biomolecule-tests','Right column, second paragraph','Transferrin-labelled dots reportedly recognized by human-cell receptors; labeled immunomolecules recognize antibodies/antigens.','secondary_application','No cell line,dose,incubation,washing,imaging or assay data supplied.')
u('berkeley-silica','Right column, silica paragraph','Berkeley group uses silica to make labels water soluble. Named researchers Bruchez,Alivisatos,Moronne,Gin,Weiss.2nmcoresgreen,4nmparticlesred.','secondary_structure_property_context','No primary synthesis,diameter measurement basis,emission peak wavelength or exact sample join; preserve core/particle wording difference.')
u('selective-labelling','Right column, functionalization paragraph','Differently functionalized green and red dots selectively stain different mouse-cell regions;10color experiment is proposed.','secondary_application_and_outlook','Ten-color claim is future outlook, not an accomplished experiment.')
u('cell-image','Bottom-left unnumbered colored image and full caption','Green mouse-cell nuclei with2nm dots carrying urea/acetate groups; red filaments with biotin-covered4nmparticles. Image is cell fluorescence context, notTEM,SAEDorXRD.','original_visual_secondary_context','No scale bar,acquisition parameters,quantitativeintensities or physical linkage to a primary recipe. Preserve as identified source visual; no training outcome.')
u('binding-schematic','Center-top unnumbered cartoon','CdSecore/ZnSshell with sulfur-linked acetate/mercaptoacetate-like groups and a protein icon.','explanatory_schematic','Schematic connectivity/interface illustration; not measured atomic structure,micrograph,full coupling mechanism or chemical recipe.')
u('alivisatos-outlook','Right column, final quoted passage','Basic-research history and unexpected biological applications,contrasted with anticipated optoelectronics.','expert_commentary','Historical/editorial statement, no experimental condition or data.')
u('adjacent-business-news','Bottom-right separate heading and incomplete paragraph','Companies raise warning flags for third quarter: economic/financial news fragment.','excluded_out_of_scope','Separate non-materials business article fragment; no synthesis,structure/property evidence.')
u('publisher-footer','Left rotated download/license text','Institutional download and publisher sharing notice.','excluded_administrative','Administrative text not scientific evidence; no institutional download metadata published.')
inventory={'source':source,'review_scope':'all_supplied_main_page; SI_unverified','units':units,'counts':{'supplied_pages':1,'source_units':len(units),'synthesis_routes':0,'primary_measurement_records':0,'figures_or_schematics':2,'tables':0,'equations':0},'disposition':'secondary_news_retained_privately_not_recipe_or_training_example','publication_decision':'No new material,method or measured-property page. Source news does not establish a reproducible synthesis or primary sample-linked outcome; its qualitative context and underlying citations remain in this private disposition for future primary-source comparison.','missing_information':['No numerical synthesis conditions,amounts,workup or specimen mapping','SI not located or verified','Underlying Science reports not inspected in this source scope','No measured crystal phase,atomic coordinates or quantitativeprimaryspectra']}
write(B/'source-disposition.json',inventory)
print('Saved complete one-page inventory and scoped exclusion proposal:',len(units),'units.')
