from pathlib import Path
import json,hashlib,datetime
A=Path(__file__).parent
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
inp=json.loads((A/'reading-inputs.json').read_text(encoding='utf-8'))
notes={
 'main-01':'Title Pati/Lee/Gaskell/Ehrman, Langmuir2009,25,67–70;online2008-12-05. Precipitation CeO2 nanoparticles; prior diethylamine400C2h/~8nm belongs citedref19. Own materials Ce(NO3)3·6H2O99%Aldrich,TEA98%Aldrich,ethanol/1propanol/1butanol99.9%Fisher. Anhydrous explicitly modifies ethanol; cannot silently assign grade to other solvents. Printed TEAformula(C2H5OH)3N suspect. Separate nitrate0.1M/TEA0.4M stocks in each solvent. RTprecipitation100mL0.1M nitrate at3–4mLmin intoTEA.',
 'main-02':'Nitrate from burette into100mL0.4MTEA inErlenmeyer withmildstir;1hpostprecipitationstir;suctionWhatman42pore2.5um. Separate10mLfiltrate aliquot testedNH4OH toconfirmcompletion, reagentconcentration/volume/outcomeobservations unspecified. Solidwashsamealcohol,RT24hdry,THENacetonewash;postacetonedryingunspecified.10Cmin ramp/200C3hcalcination;atmosphereunspecified. XRD1.5408A/BrukerAXSD8;BETASAP2010C;JEOL2100;TGair10Cmin;DSC2920;XPSAlKa1486.6eVhybrid160eVsurvey20eVhighres;DLSHeNe05LHP121/FEU79;packingdensity1mLpipet. Figure1four5nmbarswithSAEDinsets. As-prepared3±1nmcrystallites(grains),aggregatescalledparticles;0.267nminterfringecompared0.271nmreference200. SAED200/220/311as-prepared,dcalcinedalso111. HydrodynamicRADII72±20/50±18/14±8nmEtOH/propanol/butanol. Calcined1butanolFigure1d200C3h. As-preparedXRDunknowncompound,matchesLaTEAcomplexpattern only byanalogy,possibleCeTEA/CeOH4/hydrousCeO2mixture;notcertifiedpureCeO2.',
 'main-03':'Figure2XRDasp/calcined200C3h;sourcepeakscubicCeO2calcined. Scherrer~5nmcalcined,aspdiametercannotestimatedXRD. BET78/80/84m2g and model-derivedsphericaldiam10/9.8/9.3nm forEtOH/propanol/butanol. Figure3TGandDSC1butanolsource;TG200–350Closswater/nitrate/TEAassigned,350–600ClossCassigned,>600Cstablepurityinference;observed~58%loss versuscalculated72%complex/18%CeOH4. DSC40–250C173Cendotherm,calcinednopeak;phasechange150–180Cinterpretation. XPSaspCe/O/N/C,calcinedNabsent;less15min exposure81/19%CeIII/IVasp and33/67%calcined. Mechanisticcomparison70–85Cis literature,notcurrentprotocol.',
 'main-04':'Complexdeprotonationinterpretationandreactionexplicitlyhypothetical. PrintedTEAformulaunbalanced/omittedparenthesisretained,notauthoritativechemicalgraph. FourOHneeded/sixprecursorwatersreasoning;noaddedwaterclaim. Packingdensity~.6gcm3measuredroughly,7.65gcm3bulk citedref28. ConclusioncallsDLSsame72/50/14nmDIAMETERS conflictingradii. ProposedfutureWGS/SOFCdopedsystemsarenotdemonstratedrecipes. Mainreference27calledbutbibliographicentryabsent(1–26,28present). AssociatedSIdeclaresXPSspectra/fitting andmainfooterLA8031286.',
 'si-01':'No independent title/byline. EmbeddedACSsourcepathla8031286_si_001 and XPScontentmatchmainSIdeclarationandnumericresults. FigureS1fourCe3dspectra:aasp>5h,basp~15min,ccalcined>5h,dcalcined~15min supportedfollowingprose,firstcaptionmissing(a)/misplaced(b)retained. Plot870–930eV,CeIIIv0/u0/vprime/uprime;IVv/u/vdoubleprime/udoubleprime/vtripleprime/utripleprime. TextprintsCe3d5/2and3d7/2;do not silentlyrewrite.',
 'si-02':'XPSphotoreductionacknowledged. Calibrationv^1at884.5eV,50%Gaussian50%Lorentzian,Shirleybackground. Prosecallsbotha/caspreparedconflictingseparatecalcinedassignment. Repeatedspectrum3a/3(c)locatorsdonotmatchS1;retain. FourpeaksS1a,~916eVabsentCeIV,10peakscmixed. Good>5hfitsconstrainlowexposurefits;notindependentfittingmethodspernewbatch.',
 'si-03':'TableS1all20numericcells/10peaklabelsmanuallytranscribed below;printed3d7/2and5/2headingsretained. FormulaCeIII=Iv0+Iu0+Iv+Iuprime printsno primeonIv,conflictsCeIVassignment;CeIVsumIv+Iu+Ivdoubleprime+Iudoubleprime+Ivtripleprime+Iutripleprime. %III=III/(III+IV)*100. ~15minasp81/19%,calcined33/67%;>5haspnoevidenceIV(notabsolutezeroquantification),calcined~45%III(noexplicit55%IVvalue).',
 'si-04':'Fourreferencesfullyread:Burroughs1976,Mullins1998,Park1996,Suchorski2007. Bibliographictyposnotresolvedexternally. No otherfigures,recipes,CIF,atomiccoordinatefiles inthisSI.'
}
table={
 'id':'si-tableS1','source':'SIpage3','columns':['printed block','peak','assigned oxidation state','binding energy eV','FWHM eV'],
 'rows':[['Ce3d7/2','v0','Ce3+','880.3','3.0'],['Ce3d7/2','v','Ce4+','881.9','2.2'],['Ce3d7/2','vprime','Ce3+','884.8','3.9'],['Ce3d7/2','vdoubleprime','Ce4+','888.3','3.8'],['Ce3d7/2','vtripleprime','Ce4+','897.8','2.3'],['Ce3d5/2','u0','Ce3+','898.8','3.2'],['Ce3d5/2','u','Ce4+','900.4','1.5'],['Ce3d5/2','uprime','Ce3+','902.9','4.5'],['Ce3d5/2','udoubleprime','Ce4+','906.8','2.9'],['Ce3d5/2','utripleprime','Ce4+','916.1','2.3']],
 'scope':'Manually read all20numericcells before author extraction opened. Fitmodel parameters, not raw peak-area data; original block names retained with explicit conflict note.'}
bound=[]
for c in inp['original_copies']:
 assert sha(c['path'])==c['sha256'];bound.append(c)
for d in inp['documents']:
 for p in d['pages']:
  for key in ['text','render']:
   assert sha(p[key])==p[key+'_sha256'];bound.append({'path':p[key],'sha256':p[key+'_sha256']})
out={'schema':'mattersyn-independent-source-reading-notes/1','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reviewer':'/root/norberg2004_extract','status':'original_reading_complete_author_comparison_pending','title':'Precipitation of Nanocrystalline CeO2 Using Triethanolamine','doi':'10.1021/la8031286','year':2009,'pages_read_and_viewed':{'main':[1,2,3,4],'si':[1,2,3,4]},'pairing_basis':'Embedded ACS la8031286 source path plus exact XPS81/19 and33/67numerical match and detailedfitting describedmainSI declaration. SI lacksitsownarticle title/byline;not falsely claimedexacttitlematch.','page_notes':notes,'independent_table':table,'scope_limits':['Noauthorfactsopened;notfinalscientificaudit.','As-preparedpowderpossiblemixture;calcinedcubicphaseauthorassignmentnotindependentphasepurityverification.','DLSradius/diameterunresolved;nosingleunqualifiedsizedatum.','MainXPS/mostassayssolventnotexplicit;donotassignallto1butanolbecauseTGAandFigure1dareexplicit.','Noexactcoordinatesortrainingapproval.','Noactualcatalysis/fuelcellperformancedata;futureoutlookonly.'],'bound_files':bound,'intake_sha256':inp['intake_sha256']}
(A/'independent-reading-notes.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(A/'independent-reading-notes.md').write_text('# Pati2009 independent original-source reading\n\nAll4main+4SI pages read and visually inspected before author comparison. Two PDF hashes reverified.\n\n'+'\n\n'.join('**'+k+'** '+v for k,v in notes.items())+'\n',encoding='utf-8')
print(sha(A/'independent-reading-notes.json'))
