from pathlib import Path
import json,hashlib,datetime
R=Path(__file__).resolve().parent;V=R/'visuals';read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();dump=lambda p,x:p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
d=read(R/'visual-source-audit-checks.json');expected='48d30537615d2333b56fb17b850bda0150a6ea360ad1119face3781d24dbf3c2';assert sha(V/'visual-author-manifest.json')==expected
for p,h in d['bound_files'].items():assert sha(Path(p))==h,p
manual=[
 ('Hydrolysis precursor','Main p.2 Experimental Procedure','SnCl2·2H2O retains Sn(II), two Cl and two hydrate waters. The ionic diagram creates no Sn–Cl/Sn–O coordination or isolated dissolved species.'),
 ('Solvent grade and concentration','Main p.2 Experimental Procedure','Absolute ethanol/Merck applies to the initial 0.0025–0.1 M precursor solution. Neither that range nor the five colloid icons enumerate experiments or specify final aqueous concentration.'),
 ('Hydrolysis ratio and sequence','Main p.3 Section3.1 water/Sn statement','Approximately 500:1 is faithfully shown without invented molar, mass or volume basis. Water grade, addition direction/order/rate and absolute volumes remain unreported; 2 h monitoring is not a hold instruction.'),
 ('Reaction and dialysis','Main p.2 Experimental Procedure','Room-temperature hydrolysis produces white turbidity; dialysis against deionized water retains clear colloid. Membrane, time, exchange schedule and endpoint are not invented.'),
 ('Water reference reuse','Main pp.2–3; cached water reference','Hydrolysis water is not asserted to be deionized or Milli-Q. Deionized grade belongs only to dialysis. Binding overrides explicitly prevent grade leakage from the old registry alias; integration remains a separate gate.'),
 ('pH series origin','Main p.2 Experimental Procedure','The acid-set 1.5–8.5 treatment series originates from 0.025 M Sn(II) precursor colloids. This is not final particle concentration or the final pH after TBAOH.'),
 ('Ageing','Main p.2 Experimental Procedure','24 h is the interval before redispersion. The artwork explicitly leaves ageing temperature/atmosphere unknown instead of inheriting hydrolysis room temperature.'),
 ('Nitric acid reference','Main p.2; cached PubChem944 SDF/properties','Undissociated HNO3 reference with formal-charge resonance representation is identified as a reference, not aqueous speciation. The 3D model preserves exactly the cached heavy-atom coordinates; the hydroxyl H is implicit, not an invented H coordinate.'),
 ('TBAOH redispersion','Main p.2 Experimental Procedure','Tetrabutylammonium hydroxide, J.T.Baker, 0.4 M aqueous stock is distinct from final concentration. The cation has four butyl chains and OH counterion; no Br or fixed solvent-water stoichiometry is introduced.'),
 ('Probe sonication','Main p.2 Experimental Procedure, original page visually checked','Actual source specifies 2 min, correctly shown. It does not specify 1 h. Power, dimensions, temperature and automatic assignment to all TEM specimens remain absent.'),
 ('TEM preparation','Main p.2 Experimental Procedure','One colloid drop wets carbon-coated copper for20s; air drying preserves the grid, without bulk powder isolation, heating, drying time, Formvar, mesh or thickness claims.'),
 ('TEM acquisition','Main p.2 and Figure5 source context','PhilipsCM200,200kV,at least200particles per distribution; particle-count is not a replicate count. Radius/diameter distinctions remain explicit and original images supply morphology evidence.'),
 ('UV/visible acquisition','Main p.2 Experimental Procedure/Figure1a','Perkin-Elmer stated220–360nm interval, room-temperature colloids. The narrower printed display is not rewritten as acquisition bounds. Cell path/dilution remain unknown.'),
 ('PL acquisition','Main p.2 Experimental Procedure/Figure1b','Xe-lamp250nm excitation, Jobin-YvonFL3-12,250–400nm stated acquisition interval and photomultiplier detection are retained; no synthetic trace or cross-technique batch equivalence is created.'),
 ('Zeta context','Main pp.2,5/Figure6','BrookhavenZetaplus belongs to the 0.025M-origin zeta series. Isoelectric pH is not prescribed synthesis pH; electrodes and cell are visibly schematic without invented field strength.'),
 ('Proposed hydroxide','Main p.3 polycondensation discussion','Sn(OH)4 is formula-only author-proposed intermediate. No isolated reagent, measured oxidation path, unique coordination or model-trained mechanistic truth is claimed.'),
 ('Product identity','Main p.2 characterization and Figs4–7','Cassiterite assignment is source prose; original main provides no matching XRD trace or SAED/CIF. Shared SnO2 composition icon is explicitly non-atomic and does not join the five specimen contexts.'),
 ('Component controls','Exact /stocks/0 and /materials/1,/materials/2 bindings','Three component proposals resolve to existing source parents. Aqueous acid/TBAOH component selectors are not newly minted canonical stocks or fixed composition solution structures.'),
 ('Rendering and selection','All four apparatus contact sheets; six molecular/identity PNGs; three coordinate projections','All13stage drawings are readable with distinct material flow and acquisition contexts. The exact module replay reproduces all SVGs without mutation, rejects foreign record/source/operation IDs, and resolves48condition rows.'),
]
visual_files=[V/'apparatus/review'/f'contact-{i:02}.png'for i in range(1,5)]+sorted((V/'molecules/review').glob('*.png'))+[R/'visual-audit-assets/reference-coordinate-contact.png']
for p in visual_files:d['bound_files'][str(p)]=sha(p)
for p in [R/'independent_visual_source_audit.py',R/'independent_visual_scene_replay.mjs',R/'close_independent_visual_audit.py',R/'visual-source-audit-checks.json']:d['bound_files'][str(p)]=sha(p)
out={'schema':'mattersyn-independent-visual-source-audit/1','source_id':'ribeiro2004','auditor':'/root/norberg2004_extract','author':'/root/backlog_eta','status':'passed','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'author_manifest_path':str(V/'visual-author-manifest.json'),'author_manifest_sha256':expected,'scope':'Independent scientific visual, cached chemical-reference, canonical-binding, source-flow and read-only module audit of the frozen private proposal. No full source extraction re-audit, mounted viewer or publication approval.','counts':{**d['counts'],'manual_scope_checks':len(manual),'bound_files':len(d['bound_files'])},'checks':d['checks'],'replay_checks':read(R/'visual-scene-independent-replay.json')['checks'],'manual_checks':[{'topic':a,'locator':b,'result':c,'status':'passed'}for a,b,c in manual],'visual_inspection':{'actually_viewed':[str(p)for p in visual_files],'source_pages_visually_rechecked':[2,3],'source_text_pages_read':[1,2,3,4,5,6],'all_new_identity_images':6,'all_apparatus_scenes':13,'model_geometry_projections':3},'bound_files':d['bound_files'],'geometries':d['geometries'],'open_findings':[],'author_corrections_requested':[],'audit_implementation_notes':['A first checker compared literal element-order formula strings and rejected Cl2H4O2Sn versus H4Cl2O2Sn; the checker was corrected to compare elemental counts. This was not a source or author error.'],'remaining_gates':['Install and actually consume source-specific binding/component overrides; do not inherit the generic water Milli-Q alias.','Actual desktop/mobile viewer rotation, stage controls and layout checks.','Separate publication/promotion approval; this audit supplies no measured SnO2 CIF or exact structure–recipe pair.'],'site_or_canonical_or_reader_or_author_edits':False,'publication_approved':False,'browser_approved':False}
dump(R/'visual-source-audit.json',out)
md=f'''# Ribeiro visual source audit

Passed against frozen visual-author-manifest SHA256 `{expected}`. No author correction was required.

Independently checked all 13 operation scenes, 13 material slots, three component contexts, six new entries/four new molecular models, and two reused references. Read all six main-text pages; visually rechecked original pages2–3, all four apparatus contacts, all six new identity images and three actual-coordinate projections. The 321 independent consistency checks and 101 read-only module checks are separate from 19 manual scientific scope checks.

Source limits are preserved: initial versus final concentration, approximately500:1 with unspecified ratio basis, unknown hydrolysis-water grade and addition order, incomplete dialysis details, acid-set versus post-TBAOH measurement pH, actual2min probe sonication, and separate TEM/optical/zeta contexts. Hydrate waters, hydroxide counterion, proposed Sn(OH)4 status and composition-only SnO2 identity are correct. Nitric-acid heavy-atom coordinates agree exactly with the retained PubChem reference, without an aqueous-speciation claim.

All 13 SVGs reproduce exactly with no canonical mutation or foreign-ID fallback. Source-specific water/ethanol/model metadata must be applied during integration. Browser controls, component-selector integration and publication remain pending. No synthetic measured spectrum/image or measured atomic structure was approved.

The JSON binds {len(d['bound_files'])} actual files, source PDFs, frozen canonical/reader inputs, original visual assets, audit code and independent projections. No Site, author proposal, canonical or frozen reader file was edited.
'''
(R/'visual-source-audit.md').write_text(md,encoding='utf-8');print(json.dumps({'status':'passed','audit_sha256':sha(R/'visual-source-audit.json'),'manifest_sha256':expected,'bound_files':len(d['bound_files'])}))
