"""Author extraction from all 12 main and 4 matched SI pages, 2026-09-19.

No scientific audit, machine-training eligibility, or publication is asserted.
"""
from pathlib import Path
import json,hashlib,re
from datetime import datetime,timezone

B=Path(__file__).resolve().parent
AUTHOR='/root/norberg2004_extract'
NOW=datetime.now(timezone.utc).isoformat()
MH='ed5e5f4cc0db81c73fd9863922471bfd3d641ecd2a2793d4ea654e1a6d1550f3'
SH='b357afa581c9d2e1e15b6dfc6520c4a81542b8d9d24fe6c1e590dd0a17f47dfc'
def save(name,obj): (B/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def ev(page,locator,role='main'):
 return {'source_id':'norberg2004-'+role,'source_role':role,'source_sha256':MH if role=='main' else SH,'pdf_page':page,'printed_page':str(9386+page) if role=='main' else 'S-'+str(page),'locator':locator}
facts=[]
def f(key,sample,prop,value,unit,page,loc,status='reported',approx=False,uncertainty=None,raw=None,role='main',qualifier=''):
 facts.append({'id':'norberg2004-'+key,'source_unit_id':sample,'sample_scope':sample,'property':prop,'value':value,'unit':unit,'status':status,'approximate':approx,'uncertainty':uncertainty,'raw_text':raw,'qualifier':qualifier,'evidence':[ev(page,loc,role)],'eligible_training':False,'review_state':'extracted_pending_independent_audit'})

materials=[]
def chem(cid,name,formula,role,purity=None,supplier=None,source='II.A Materials',page=2,notes=''):
 materials.append({'id':cid,'name':name,'formula':formula,'formula_status':'normalized chemical identity; hydration/source formula notes retained','roles':role,'purity_percent':purity,'supplier':supplier,'pretreatment':'used as received' if page==2 else None,'storage':None,'quantity_status':'see source facts and stocks; no absolute synthesis scale supplied','notes':notes,'evidence':[ev(page,source)]})
chem('zinc-acetate-dihydrate','Zinc acetate dihydrate','Zn(CH3COO)2·2H2O',['host precursor','oxidation-inhibition control'],98,'Strem',notes='Magnetic impurities <0.0005%.')
chem('manganese-acetate-tetrahydrate','Manganese(II) acetate tetrahydrate','Mn(CH3COO)2·4H2O',['dopant precursor','surface-doping control','oxidation control'],99.999,'Strem')
chem('manganese-nitrate-hydrate','Manganese(II) nitrate hydrate','Mn(NO3)2·xH2O',['oxidation control'],98,'Sigma-Aldrich',notes='Hydration number unspecified; not the reported ZnO synthesis precursor.')
chem('tmah-pentahydrate','Tetramethylammonium hydroxide pentahydrate','N(CH3)4OH·5H2O',['hydrolysis base'],97,'Sigma-Aldrich',notes='Materials prints N(CH4)4OH·5H2O, while preparation uses N(Me)4OH·5H2O. Normalized by named identity; source discrepancy retained, not silently inherited.')
chem('dodecylamine','Dodecylamine','CH3(CH2)11NH2',['capping ligand','surface-dopant removal medium'],98,'Sigma-Aldrich',notes='Melting point ca.30°C reported in II.B.')
chem('topo','Trioctylphosphine oxide (technical grade)','[CH3(CH2)7]3PO',['alternative surface-cleaning/capping medium'],90,'Sigma-Aldrich',notes='Optional procedure points to reference32; its detailed independent method was not inspected in this task.')
chem('dmso','Dimethyl sulfoxide','(CH3)2SO',['reaction solvent','stock/control solvent'],99.7,'Acros')
chem('ethanol','Absolute ethanol','C2H5OH',['base-stock solvent','washing/resuspension medium'],None,'AAPER')
chem('ethyl-acetate','Ethyl acetate','CH3COOC2H5',['initial antisolvent'],source='II.B Sample Preparation',page=3)
chem('heptane','Heptane','C7H16',['washing antisolvent'],source='II.B Sample Preparation',page=3)
chem('toluene','Toluene','C6H5CH3',['final colloid/characterization medium'],source='II.B-C',page=3)
chem('lithium-hydroxide','Lithium hydroxide','LiOH',['surface-doping control base'],source='II.B Surface-bound Mn control',page=3,notes='Hydration, purity, concentration and supplier not given; do not substitute TMAH stock concentration.')
chem('sodium-acetate','Sodium acetate','CH3COONa',['oxidation control'],source='Figure4/III Results',page=4,notes='Hydration and supplier not given; II.A materials list is incomplete relative to controls.')
chem('nitrogen','Nitrogen','N2',['surface-cleaning atmosphere'],source='II.B amine treatment',page=3)
chem('air','Air',None,['ambient synthesis atmosphere','annealing atmosphere','oxidation control'],source='Abstract; II.B; IV.E',page=1,notes='Atmospheric synthesis, not nitrogen synthesis. No numerical pressure supplied.')
chem('fused-silica','Fused silica','SiO2',['film substrate'],source='II.B Films',page=3)
chem('quartz-disks','Quartz disks','SiO2',['MCD frozen-solution support'],source='Figure6 caption',page=5)

stocks=[
 {'id':'stock-metal-acetates','components':['zinc-acetate-dihydrate','manganese-acetate-tetrahydrate'],'solvent':'dmso','total_concentration':{'value':0.10,'unit':'mol/L','basis':'combined metal acetate concentration before base addition'},'composition':'x Mn(OAc)2·4H2O + (1-x) Zn(OAc)2·2H2O','volume':None,'storage':None,'evidence':[ev(3,'II.B first paragraph')]},
 {'id':'stock-tmah','components':['tmah-pentahydrate'],'solvent':'ethanol','concentration':{'value':0.55,'unit':'mol/L'},'volume':None,'preparation_details':None,'evidence':[ev(3,'II.B first paragraph')]},
 {'id':'stock-lioh-control','components':['lithium-hydroxide'],'solvent':'ethanol','concentration':None,'volume':None,'evidence':[ev(3,'II.B surface-bound Mn control')]},
 {'id':'stock-mn-oxidation','components':['manganese-acetate-tetrahydrate'],'solvent':'dmso','concentration':{'value':0.002,'unit':'mol/L'},'volume':None,'storage':'5 days open to atmosphere or specified anaerobic/control variant','evidence':[ev(4,'Figure4 and accompanying Results'),ev(8,'IV.E')]},
 {'id':'stock-nitrate-control','components':['manganese-nitrate-hydrate'],'solvent':'dmso','concentration':{'value':0.002,'unit':'mol/L'},'volume':None,'storage':'5 days in air','evidence':[ev(5,'Results continuation from Figure4'),ev(8,'IV.E')]}]

protocols=[]
def protocol(pid,title,kind,scope,steps,page,loc,gaps,variants=None):
 protocols.append({'id':pid,'title':title,'method':kind,'scope':scope,'operations':[{'id':pid+'-op-'+str(i+1),'sequence':i+1,**step} for i,step in enumerate(steps)],'variants':variants or [],'evidence':[ev(page,loc)],'missing_fields':gaps,'review_state':'full_source_extraction_pending_audit'})
protocol('protocol-hydrolysis','Colloidal Mn2+:ZnO by acetate hydrolysis/condensation','solution hydrolysis and condensation','Common route; composition-specific measured products retain separate sample IDs',[
 {'action':'dissolve','inputs':['zinc-acetate-dihydrate','manganese-acetate-tetrahydrate','dmso'],'output':'stock-metal-acetates','conditions':'0.10 M total; xMn/(1-x)Zn; room temperature; atmospheric conditions'},
 {'action':'add_dropwise','inputs':['stock-tmah','stock-metal-acetates'],'output':'initial-colloids','conditions':'1.7 equivalents 0.55 M ethanolic N(Me)4OH·5H2O; constant stirring at room temperature; no exact addition time'},
 {'action':'grow','inputs':['initial-colloids'],'output':'grown-colloids','conditions':'Initial growth on minutes scale; Ostwald ripening over several days at room temperature OR accelerated near60°C; these are alternatives, not two required consecutive holds'},
 {'action':'precipitate','inputs':['grown-colloids','ethyl-acetate'],'output':'initial-precipitate','retained_fraction':'nanocrystal precipitate','conditions':'After growth; isolation equipment/force/time unspecified'},
 {'action':'resuspend','inputs':['initial-precipitate','ethanol'],'output':'ethanolic-colloids','conditions':'Amount unspecified'},
 {'action':'wash_iteratively','inputs':['ethanolic-colloids','heptane','ethanol'],'output':'washed-colloids','retained_fraction':'precipitated nanocrystals, resuspended in ethanol','conditions':'Heptane precipitation/ethanol resuspension, repeated; cycle count unspecified'},
 {'action':'cap_and_transfer','inputs':['washed-colloids','dodecylamine','toluene'],'output':'dodecylamine-capped-colloids','conditions':'Initial capping conditions/amount unspecified; distinct from subsequent180°C cleaning'}
],3,'II.B first paragraph',['absolute masses and reaction/stock volumes','exact feed x for every characterized sample','drop rate/addition duration','stirring speed','reaction-vessel geometry','generic growth duration and endpoint','workup volumes, isolation force/time and washing repetitions','initial dodecylamine capping amount/temperature/duration','yield'],variants=[{'id':'undoped-zno-control','change':'x=0, no Mn(OAc)2','evidence':[ev(3,'II.B surface-bound control'),ev(10,'IV.G')]},{'id':'feed-0.50pct','change':'initial Mn level0.50% produces post-treatment0.20±0.01% product by ICP-AES','evidence':[ev(3,'Results Figure1b')]},{'id':'feed-0.02pct','change':'0.02% Mn/99.98% Zn, aliquot series10min/60°C2h/amine-treated','evidence':[ev(4,'Figure2/Results')]}])
protocol('protocol-amine-cleaning','Removal of surface-exposed Mn using dodecylamine','ligand-mediated surface cleaning with concurrent ripening','Post-treatment of dodecylamine-capped colloids; changes surface composition and size',[
 {'action':'heat','inputs':['dodecylamine-capped-colloids','dodecylamine'],'output':'surface-cleaned-colloids-hot','conditions':'180°C, ca.30min, nitrogen; dodecylamine mp ca.30°C'},
 {'action':'cool','inputs':['surface-cleaned-colloids-hot'],'output':'surface-cleaned-colloids-cool','conditions':'Below80°C before precipitation; not exactly80°C'},
 {'action':'precipitate_and_wash','inputs':['surface-cleaned-colloids-cool','ethanol'],'output':'amine-treated-powder','retained_fraction':'nanocrystal powder','conditions':'Ethanol precipitation/washing; volumes/repetitions unspecified'},
 {'action':'resuspend','inputs':['amine-treated-powder','toluene'],'output':'cleaned-final-colloids','conditions':'Toluene or other nonpolar solvent; optically high quality, stable several months; storage conditions not specified'}
],3,'II.B second paragraph; IV.B-D pp9393–9394',['nanocrystal charge','dodecylamine amount','ramp/cooling rate','isolation details','quantitative storage duration/conditions'])
protocol('protocol-surface-control','Deliberately surface-bound Mn2+:ZnO control','post-synthetic surface doping','Figure2a reference, intended100% surface Mn population',[
 {'action':'synthesize_and_wash','inputs':['undoped-zno-control','ethanol'],'output':'washed-pure-zno','conditions':'Common route without Mn feed; washed/resuspended in ethanol'},
 {'action':'add','inputs':['washed-pure-zno','manganese-acetate-tetrahydrate'],'output':'surface-control-mixture','conditions':'Small Mn(OAc)2 amount ca.2% of Zn2+'},
 {'action':'add_dropwise','inputs':['surface-control-mixture','stock-lioh-control'],'output':'surface-bound-mn-zno','conditions':'0.002 equivalent ethanolic LiOH; equivalent reference not explicitly stated'},
 {'action':'wash_cap_transfer','inputs':['surface-bound-mn-zno','dodecylamine','toluene'],'output':'surface-control-epr','conditions':'Subsequently washed, capped and resuspended in toluene for EPR; do NOT automatically apply surface-stripping180°C stage to this surface-bound reference'}
],3,'II.B surface-bound Mn control',['Mn absolute charge','LiOH concentration/volume and equivalent basis','contact time','capping details'])
protocol('protocol-titration','Mn:Zn acetate base titration','reaction-monitoring aliquot series','Figure1a; aliquots/dilution are measurements of one progression, not synthesis replicates',[
 {'action':'prepare_stock','inputs':['stock-metal-acetates'],'output':'titration-stock','conditions':'0.10 M total in DMSO;2% Mn/98%Zn'},
 {'action':'add_incrementally','inputs':['titration-stock','stock-tmah'],'output':'titration-series','conditions':'Successive0.15-equivalent portions0.55 M base in ethanol; Figure1a solid trace1.65eq; additionalbase beyondca.1.65eq begins clouding'},
 {'action':'sample_and_measure','inputs':['titration-series'],'output':'spectral-aliquots','conditions':'Extract aliquot, measure, dilute70× and remeasure to capture weak/intense bands; spectra300K,1cm path'}
],3,'II.C and Figure1a',['absolute volumes','interval between additions','exact last increment beyond1.65eq'])
protocol('protocol-topo','Alternative TOPO surface treatment','cited alternative ligand treatment','TOPO-capped1.1% MCD/absorption nanocrystals',[
 {'action':'heat_in_topo','inputs':['grown-colloids','topo'],'output':'topo-cleaned-colloids','conditions':'Technical gradeTOPO; procedure cited as reference32; heating conditions not restated'},
 {'action':'prepare_mcd','inputs':['topo-cleaned-colloids','quartz-disks'],'output':'topo-frozen-solution','conditions':'Drop-coating onto quartz disks to form frozen solutions;5Kvariable-fieldMCD'}
],3,'II.B-C; Figure6 p9391',['TOPO temperature/time/amount and upstreamref32 uninspected','initialMn feed for1.1% product','colloidMCD solvent/film amount','do not inherit180°C30min amine treatment'])
protocol('protocol-films','Spin-coated and annealed Mn2+:ZnO nanocrystalline films','spin coating and brief air annealing','Films A–F; same nominal0.20±0.01% colloid material, per-film parameters retained',[
 {'action':'spin_coat','inputs':['cleaned-final-colloids','fused-silica'],'output':'fresh-film-layer','conditions':'Dodecylamine-treatedcolloids;1cm×0.5cm fusedsilica substrates (A–C specified)'},
 {'action':'anneal','inputs':['fresh-film-layer','air'],'output':'annealed-layer','conditions':'525°C2min inair aftereachspin-coatedlayer (A–C preparation section); no1kbar anneal'},
 {'action':'repeat','inputs':['annealed-layer','cleaned-final-colloids'],'output':'film-series','conditions':'A40coats;B20;C20. SI D–F spincoated, exact coat counts/anneal inheritance not independently stated.'}
],3,'II.B films; SI FigureS3/TableS4',['spin speed/time','dispensed volume and colloid concentration','ramp/cooling profile','finalthickness','D–F layer counts and independentlyassignedannealconditions'],variants=[{'sample_id':'film-a','coats':40,'main_mass_mg':0.59,'si_mass_ug':593},{'sample_id':'film-b','coats':20,'main_mass_mg':0.24,'si_mass_ug':236},{'sample_id':'film-c','coats':20,'main_mass_mg':0.28,'si_mass_ug':279},{'sample_id':'film-d','coats':None,'si_mass_ug':483},{'sample_id':'film-e','coats':None,'si_mass_ug':305},{'sample_id':'film-f','coats':None,'si_mass_ug':282}])
protocol('protocol-oxidation-controls','Manganese precursor oxidation and Zn-acetate inhibition','stock-solution stability controls','Figure4; retain negative outcomes and controls; not nanocrystal synthesis recipes',[
 {'action':'prepare','inputs':['stock-mn-oxidation'],'output':'oxidation-control-series','conditions':'0.002 M Mn(OAc)2·4H2O in DMSO'},
 {'action':'vary_conditions','inputs':['oxidation-control-series'],'output':'oxidation-control-variants','conditions':'air baseline; addedZn(OAc)2 varyingZn:Mn ratios; anaerobic baseline;0.010 M NaOAc(5:1NaOAc:Mn);or0.002 M Mn(NO3)2 insteadofMnacetate'},
 {'action':'store_and_measure','inputs':['oxidation-control-variants'],'output':'oxidation-observations','conditions':'5days; air variants open toatmosphere; absorption at20000cm−1; roomtemperature described in IV.E'}
],4,'Figure4; Results pp9390–9391; IV.E p9394',['solution volumes','exact full zinc-ratio list onlyplotted','anaerobicgas andhandlingdetails','measuredpH','raw numericalabsorbancepoints'])

# Quantities anchored to their real scopes, including absence and contextual limits.
for key,s,p,v,u,pg,loc,kw in [
 ('zn-purity','zinc-acetate-dihydrate','purity',98,'%',2,'II.A',{}),('zn-magnetic-impurities','zinc-acetate-dihydrate','magnetic impurity upper bound',0.0005,'%',2,'II.A',{'qualifier':'strictly less than'}),('mn-purity','manganese-acetate-tetrahydrate','purity',99.999,'%',2,'II.A',{}),('nitrate-purity','manganese-nitrate-hydrate','purity',98,'%',2,'II.A',{}),('tmah-purity','tmah-pentahydrate','purity',97,'%',2,'II.A',{}),('dda-purity','dodecylamine','purity',98,'%',2,'II.A',{}),('topo-purity','topo','purity',90,'%',2,'II.A',{}),('dmso-purity','dmso','purity',99.7,'%',2,'II.A',{}),
 ('metal-conc','stock-metal-acetates','combined metal concentration',0.10,'mol/L',3,'II.B',{}),('tmah-conc','stock-tmah','concentration',0.55,'mol/L',3,'II.B',{}),('base-eq','protocol-hydrolysis','base added',1.7,'equiv',3,'II.B',{'qualifier':'metalacetate mixture basis implied by procedure; absolute scale unreported'}),('growth-ambient','protocol-hydrolysis','initial growth temperature','room temperature',None,3,'II.B',{}),('growth-duration','protocol-hydrolysis','initial growth timescale','minutes',None,3,'II.B',{'qualifier':'qualitative timescale, not fixedhold'}),('ripening-days','protocol-hydrolysis','ambient ripening timescale','several days',None,3,'II.B',{}),('ripening-heat','protocol-hydrolysis','accelerated ripening temperature',60,'°C',3,'II.B',{'approx':True}),
 ('dda-mp','dodecylamine','melting point',30,'°C',3,'II.B',{'approx':True}),('clean-temp','protocol-amine-cleaning','cleaning temperature',180,'°C',3,'II.B',{}),('clean-time','protocol-amine-cleaning','cleaning duration',30,'min',3,'II.B',{'approx':True}),('clean-atmosphere','protocol-amine-cleaning','atmosphere','nitrogen',None,3,'II.B',{}),('cool-limit','protocol-amine-cleaning','precipitation temperature upper bound',80,'°C',3,'II.B',{'qualifier':'strictly below80°C'}),('colloid-stability','cleaned-final-colloids','reported colloidal stability','several months',None,3,'II.B',{'qualifier':'unspecified storage atmosphere/temperature/lighting'}),
 ('surface-mn','protocol-surface-control','Mn addition relative to Zn',2,'%',3,'II.B',{'approx':True}),('surface-lioh','protocol-surface-control','LiOH charge',0.002,'equiv',3,'II.B',{'qualifier':'equivalentreference not explicit; LiOH concentration unreported'}),
 ('film-substrate','protocol-films','substrate dimensions',[1,0.5],'cm',3,'II.B',{}),('film-anneal-t','protocol-films','per-layer annealing temperature',525,'°C',3,'II.B',{}),('film-anneal-time','protocol-films','per-layer annealing duration',2,'min',3,'II.B',{}),('film-anneal-atmosphere','protocol-films','annealing atmosphere','air',None,3,'II.B',{}),
 ('titration-feed','titration-series','Mn feed fraction',2,'%',3,'Figure1a',{}),('titration-increment','titration-series','base increment',0.15,'equiv',3,'Figure1a',{}),('titration-onset','titration-series','ZnO excitonic and sub-bandgap onset',0.45,'equiv base',3,'Results/Figure1a',{}),('titration-solid','titration-series','solid-trace base total',1.65,'equiv',3,'Figure1a',{}),('titration-clouding','titration-series','clouding threshold',1.65,'equiv base',3,'Results',{'approx':True,'qualifier':'beyondca.1.65eq; not identical tocommonrecipe1.7eq'}),('titration-dilution','spectral-aliquots','spectral remeasurement dilution',70,'fold',3,'II.C',{}),
 ('feed-to-product','cleaned-0.20pct','initial Mn feed',0.50,'%',3,'Results Figure1b',{}),('product-mn','cleaned-0.20pct','Mn content by ICP-AES',0.20,'%',3,'Results Figure1b/continuationp4',{'uncertainty':{'value':0.01,'unit':'%','definition':'not specified'},'qualifier':'Reported compositionZn0.998Mn0.002O; feed is0.50%, not0.20%'}),
 ('aliquot-feed','growth-0.02pct-series','initial Mn feed',0.02,'%',4,'Figure2/Results',{'qualifier':'Figure5nominal0.02% label doesnotestablishICPmeasuredproductconcentration'}),('aliquot-early-time','growth-02-b','time after base addition',10,'min',4,'Figure2b',{}),('aliquot-early-size','growth-02-b','diameter estimated from absorption',4.0,'nm',4,'Figure2b/Results',{'status':'author_estimated','approx':True}),('aliquot-growth-t','growth-02-c','ripening temperature',60,'°C',4,'Figure2c',{}),('aliquot-growth-time','growth-02-c','ripening duration',2,'h',4,'Figure2c',{}),('aliquot-growth-size','growth-02-c','diameter estimated from absorption',5.6,'nm',4,'Figure2c',{'status':'author_estimated','approx':True}),('aliquot-clean-time','growth-02-d','amine-treatment duration',30,'min',4,'Results Figure2d',{'qualifier':'Here30min; common method saysca.30min'}),
 ('epr-surface-splitting','surface-control-epr','apparent hyperfine splitting',88,'G',4,'Figure2/Results',{'approx':True}),('epr-clean-splitting','growth-02-d','apparent major-line hyperfine splitting',78,'G',4,'Figure2/Results',{'approx':True}),('surface-fraction-4nm','growth-02-b','statistical surface dopant fraction',25,'%',7,'IV.A',{'status':'author_model','approx':True}),('surface-fraction-56nm','growth-02-c','statistical surface dopant fraction',20,'%',7,'IV.A',{'status':'author_model','approx':True}),
 ('morphology','cleaned-0.20pct','TEM morphology','approximately spherical, highlycrystalline',None,4,'Figure3b–d/Results',{}),('tem-diameter','cleaned-0.20pct','mean TEM diameter',6.1,'nm',4,'Figure3c',{'uncertainty':{'value':0.7,'unit':'nm','definition':'reporteddiameterdistributionspread; notexplicitlydefinedSD'}}),('tem-count','cleaned-0.20pct','particles in size histogram',100,'particles',4,'Figure3c caption',{'qualifier':'body saysca.100; caption100'}),('tem-spacing-1','cleaned-0.20pct','HRTEM spacing label',2.34,'Å',4,'Figure3d image annotation',{}),('tem-spacing-2','cleaned-0.20pct','HRTEM spacing label',2.74,'Å',4,'Figure3d image annotation',{}),('tem-scalebar-overview','cleaned-0.20pct','TEM overview scale bar',50,'nm',4,'Figure3b',{}),('tem-scalebar-hr','cleaned-0.20pct','HRTEM scale bar',5,'nm',4,'Figure3d',{}),('xrd-phase-colloids','cleaned-0.20pct-powder','XRD phase assignment','wurtziteZnO',None,4,'Figure3a',{'qualifier':'All observedpeaks matchreference; noatomisticrefinement/CIFsupplied'}),('xrd-phase-film','film-a','XRD phase assignment','wurtziteZnO',None,4,'Figure3a',{}),('xrd-diameter','cleaned-0.20pct-powder','Scherrer average crystallite diameter',6.1,'nm',8,'IV.D',{'status':'author_derived_from_XRD'}),('film-xrd-size','film-a','Scherrer effective crystallite diameter',20,'nm',11,'IV.H',{'status':'author_derived_from_XRD','qualifier':'authors describeincreasefrom6to20nm; notdirectTEMfilmmeasurement'}),('abs-size-estimate','cleaned-0.20pct','band-gap estimated diameter range',[6,7],'nm',8,'IV.D',{'status':'author_estimated','qualifier':'authors explicitly saybandgap sizesunreliableinthisrange'}),('zno-bohr-radius','zno-reference','Bohr radius',3.5,'nm',8,'IV.D',{'status':'contextual_reference_constant'}),
 ('stock-mn-conc','oxidation-controls','Mn concentration',0.002,'mol/L',4,'Figure4',{}),('stock-storage-time','oxidation-controls','storage duration',5,'days',4,'Figure4',{}),('stock-probe','oxidation-controls','absorption probe wavenumber',20000,'cm−1',4,'Figure4',{}),('inhibition-ratio','oxidation-zinc-series','near-complete oxidation inhibition Zn:Mn ratio',3,'mol/mol',4,'Figure4/IV.Ep8',{'approx':True}),('naoac-conc','oxidation-naoac','NaOAc concentration',0.010,'mol/L',5,'Results',{}),('naoac-ratio','oxidation-naoac','NaOAc:Mn ratio',5,'mol/mol',4,'Figure4caption',{}),('naoac-effect','oxidation-naoac','absorbance increase relative to air Mnacetate baseline',50,'%',5,'Results',{}),('anaerobic-effect','oxidation-anoxic','discoloration reduction relative to air',84,'%',8,'IV.E',{}),('nitrate-effect','oxidation-nitrate','absorbance/discoloration after5days','little or no change',None,5,'Results/IV.Ep8',{}),('mn-stock-color','oxidation-air','stock evolution','colorless to brown, broad tail withshoulder20000cm−1',None,8,'IV.E',{}),('synthesis-ratio-context','protocol-hydrolysis','Zn:Mn ratio asdiscussed',49,'mol/mol',8,'IV.E',{'qualifier':'authors say>49:1, whileFigure1a2% feedisexactly49:1; preservewordingratherthanstrictglobalconstraint'}),
 ('exciton-titration','titration-series','first excitonic absorption',30000,'cm−1',3,'Results Figure1a',{'approx':True}),('subgap-titration','titration-series','sub-bandgap absorption',24000,'cm−1',3,'Results Figure1a',{}),('film-bandgap','film-a','band edge',27000,'cm−1',4,'Results continuationFigure1b',{'approx':True,'qualifier':'thinfilm absorbance reachesstraylightlimitca.27000cm−1; bandedgesimilartobulkZnO'}),('colloid-vs-film-gap','cleaned-0.20pct','bandgap comparedwithfilm','slightly larger, attributed to weakquantumconfinement',None,4,'Results',{'status':'reported_with_author_interpretation'}),
 ('topo-mn','topo-1.1pct','reported dopant level',1.1,'%',5,'Figure6',{'qualifier':'initialfeedandseparatemeasurementuncertaintynotgiven'}),('mcd-center','topo-1.1pct','pseudo-A MCD center',23600,'cm−1',8,'IV.F',{}),('mcd-onset','topo-1.1pct','negative high-energyMCDonset',28000,'cm−1',5,'ResultsFigure6',{}),('mcd-low-energy','topo-1.1pct','plotted lowerenergy limit',16000,'cm−1',5,'ResultsFigure6',{}),('mcd-saturates','topo-1.1pct','field abovewhichMCDapproachessaturation',4,'T',5,'ResultsFigure6',{'approx':True}),('mcd-probe','topo-1.1pct','MCDmagnetizationprobe',21900,'cm−1',5,'Figure6insetcaption',{}),('subgap-epsilon','cleaned-0.20pct','per-Mn molarextinctioncoefficient',950,'M−1 cm−1',9,'IV.F',{'qualifier':'24000cm−1,300K; Figure6scale1000isnotanother measuredvalue'}),
 ('lum-low-mn','optical-0.13pct','Mn concentration',0.13,'%',5,'Figure7',{'status':'author_estimated'}),('lum-high-mn','optical-1.3pct','Mn concentration',1.3,'%',5,'Figure7',{'qualifier':'no sample-specificICPuncertaintystated'}),('lum-excitation','optical-series','excitation wavenumber',28200,'cm−1',5,'ResultsFigure7',{}),('lum-abs-range','optical-series','absorbanceat excitation',[0.1,0.4],'absorbance',5,'ResultsFigure7',{'qualifier':'normalized tosameabsorbance;emissionscaledproportionally'}),('lum-green','optical-pure-zno','visibleemissionpeak',18600,'cm−1',5,'ResultsFigure7',{'approx':True}),('lum-uv','optical-pure-zno','UVemissionpeak',26900,'cm−1',5,'ResultsFigure7',{}),('lum-low-green','optical-0.13pct','visiblequenchingvsundoped',42,'%',5,'ResultsFigure7',{}),('lum-low-uv','optical-0.13pct','UVquenchingvsundoped',69,'%',5,'ResultsFigure7',{}),('lum-high-green','optical-1.3pct','visiblequenchingvsundoped',96,'%',5,'ResultsFigure7',{}),('lum-no-mn','optical-series','Mn ligand-fieldemission','not observed',None,10,'IV.G',{'qualifier':'negativeobservation, notamissingmeasurement'}),('lum-high-uv','optical-1.3pct','UVemission','no corresponding excitonicfeature; weakintensitymaybescattering',None,5,'ResultsFigure7',{}),
 ('epr-g','growth-02-d','fitted isotropic g',1.999,None,7,'IV.C/Equation1',{'status':'author_fit'}),('epr-A','growth-02-d','fitted hyperfineA',-0.00740,'cm−1',7,'IV.C',{'status':'author_fit','raw':'−74.0 ×10−4 cm−1'}),('epr-D','growth-02-d','fitted axialD',-0.0236,'cm−1',7,'IV.C',{'status':'author_fit','uncertainty':{'value':0.0005,'unit':'cm−1'},'raw':'(−2.36 ±0.05)×10−2 cm−1'}),('epr-dstrain','growth-02-d','D-strain sigma relative toD',2,'%',7,'IV.C/Figure5',{'status':'author_fit'}),('epr-S','growth-02-d','electron spin',2.5,None,7,'IV.C',{'status':'author_model'}),('epr-I','growth-02-d','55Mn nuclear spin',2.5,None,7,'IV.C',{'status':'reference_quantum_number'}),('epr-bulk-g','bulk-mn-zno-reference','literatureg parallel/perpendicular',[1.998,2.000],None,7,'IV.Crefs42–43',{'status':'cited_reference'}),('epr-bulk-A','bulk-mn-zno-reference','literatureAparallel/perpendicular',[-0.00740,-0.00735],'cm−1',7,'IV.Crefs42–43',{'status':'cited_reference'}),('epr-bulk-D','bulk-mn-zno-reference','literatureD',-0.0236,'cm−1',7,'IV.Crefs42–43',{'status':'cited_reference'}),
 ('film-remanence','films-a-b-c','meanrelative remanenceMR/MS at300K',0.12,None,6,'Results continuationfromp5',{'uncertainty':{'value':0.01,'definition':'sourceaverageerrorunspecified'}}),('film-coercivity','films-a-b-c','meancoercivity300K',92,'Oe',6,'Results',{'uncertainty':{'value':7,'unit':'Oe','definition':'sourceaverageerrorunspecified'}}),('tc-bound','films-a-b-c','Curie temperature lowerbound',350,'K',1,'Abstract; Results/IV.H/SIFigureS2',{'qualifier':'Tc>350K; instrumentceiling350K; noexactTcmeasured'}),('paramagnetic-ratio','film-a','residualparamagneticMn fraction',0.64,None,11,'IV.H/Brillouinfit',{'status':'author_fit'}),('transition-fraction','film-a','non-paramagneticMn fraction',36,'%',11,'IV.H',{'status':'author_derived'}),('lower-ferro-a','film-a','ferromagneticallyalignedMn lowerbound',13,'%',11,'IV.H',{'status':'author_model_bound','qualifier':'assumesmaximum5μB/Mn; notexactferromagneticfraction'}),('lower-ferro-b','film-b','ferromagneticallyalignedMn lowerbound',24,'%',11,'IV.H',{'status':'author_model_bound'}),('lower-ferro-c','film-c','ferromagneticallyalignedMn lowerbound',27,'%',11,'IV.H',{'status':'author_model_bound'}),('domain-spin-bound','film-a','effectiveferromagneticdomainspinlowerbound',800,None,11,'IV.H',{'status':'author_estimated','qualifier':'averageSexceeds800,from300Ksaturationcurvature; notatomicspin'}),('radical-resonance','film-a','newsharpEPRfield',3362,'G',6,'ResultsFigure10',{}),('radical-g','film-a','newsharpEPRg',2.00,None,6,'ResultsFigure10',{}),('zfc-field','films-a-b','ZFCmeasurementfield',80,'Oe',6,'Figure9acaption',{}),('paramag-probe-field','film-a','temperature-seriesresidualmagnetizationfield',1,'T',6,'Figure9c',{}),('zfc-transition-absence','films-a-b','ZFC magneticphase transitions','not observed in5–350Kwindow',None,11,'IV.H',{'qualifier':'sourcearguesagainstMnO/Mn3O4, whose citedNCmaxima<ca.45K; no universalimpuritydetectionlimit'}),
 ('model-dq','ct-model','estimatedDq',420,'cm−1',9,'IV.F',{'status':'author_model'}),('model-B','ct-model','estimatedRacahB',596,'cm−1',9,'IV.F',{'status':'author_model'}),('model-Cratio','ct-model','estimatedC/B',6.5,None,9,'IV.F',{'status':'author_model'}),('model-electronegativity-mn','ct-model','opticalelectronegativityMn',1.45,None,9,'IV.Fref53',{'status':'cited_model_input','approx':True}),('model-electronegativity-cb','ct-model','opticalelectronegativityZnOCB',1.1,None,9,'IV.Fref53',{'status':'cited_model_input','approx':True}),('model-electronegatativity-vb','ct-model','opticalelectronegativityZnOVB',2.0,None,9,'IV.Fref53',{'status':'cited_model_input','approx':True}),('model-electronegatativity-vb-alt','ct-model','alternativeopticalelectronegativityVB',2.4,None,9,'IV.Fref32',{'status':'cited_model_input','approx':True}),('ct-lmct','ct-model','predictedLMCTenergywithVB2.0',37400,'cm−1',9,'IV.F',{'status':'author_model','approx':True}),('ct-mlct','ct-model','predictedMLCTenergy',23000,'cm−1',9,'IV.F',{'status':'author_model','approx':True}),('ct-lmct-alt','ct-model','predictedLMCTenergywithVB2.4',49400,'cm−1',9,'IV.F',{'status':'author_model','approx':True}),('ct-identity','ct-model','subgapassignment','tentative Mn2+→conductionband charge transfer',None,9,'IV.F',{'status':'author_tentative_interpretation'}),('theory-carriers','theory-context','predictedrequiredp-typecarrierconcentration',3.5e20,'cm−3',11,'IV.Hcitingrefs2–3',{'status':'cited_theory','approx':True,'qualifier':'notmeasuredcarrierconcentrationinthesefilms'}),('solubility-context','solubility-reference','MnZnOsolidsolubility',10,'%',11,'IV.Href22',{'status':'cited_reference','qualifier':'exceeds10%at525°Cand1kbar; notactualfilmprocessingpressure'}),('mn900-context','oxidation-reference','O2pressureupperboundmaintainingMnOat900°C',1e-7,'atm',8,'IV.Eref45',{'status':'cited_reference','qualifier':'below; NOTthisroomtemperaturesynthesispressure'})
]: f(key,s,p,v,u,pg,loc,**kw)

# Instruments/acquisition parameters remain tied to their measurement, not synthesis.
instruments=[
 ('epr-x','X-band EPR','Bruker EMX',{'frequency_GHz':9.34,'temperature':'room temperature; figures300K','sample':'toluene colloids;filmattachedtoEPRtubewithnonmagnetictape perpendicular tofield'},3),
 ('epr-q','Q-band EPR','Bruker ESP300E',{'frequency_GHz':34.0,'temperature':'roomtemperature','sample':'toluene colloids'},3),
 ('epr-sim','EPR simulation','SIM version2002, Høgni Weihe',{'algorithm':'full-matrix diagonalization','Hamiltonian':'Equation1'},3),
 ('abs','Electronic absorption','Cary500E Varian',{'path_length_cm':1,'temperature':'roomtemperature','sample':'colloids;filmA separatelyshown','aliquot_redilution':70},3),
 ('mcd','Magnetic circular dichroism','priorref32apparatus notrestated',{'temperature_K':5,'field_T_range':[0,7],'sample':'drop-coatedfrozenTOPO1.1%colloids onquartz','definition':'ΔA=AL−AR; θ(deg)=32.9ΔA/A asprinted'},3),
 ('lum','Luminescence','Jobin Yvon FluoroMax-2',{'cuvette_cm':[1,1],'excitation_cm-1':28200,'temperature_K':300},3),
 ('xrd-powder','Powder XRD','Philips PW1830',{'radiation':'CuKα'},3),
 ('xrd-film','Thin-film XRD','Rigaku Rotaflex RTP300',{'radiation':'CuKα'},3),
 ('tem','HRTEM','JEOL2010',{'accelerating_voltage_kV':200,'electron_source':'high-brightnessLaB6filament'},3),
 ('icp','ICP-AES','Jarrel Ash955',{'role':'dopant concentration'},3),
 ('mag','SQUID magnetometry','QuantumDesignMPMS-5S',{'sample':'rapidlyprecipitatedtoluene-colloidpowders orspin-coatedfilms','correction':'substrateandholderdiamagnetismsubtracted','instrument_temperature_ceiling_K':350},3)]
for iid,tech,instr,conds,pg in instruments:
 f('instrument-'+iid,'measurement-'+iid,'instrument and acquisition',{'technique':tech,'instrument':instr,**conds},None,pg,'II.C; technique-specificfigurecaptions')

# Complete SI table transcriptions: actual samples are TableS4 only; S1–S3 are
# literature/model knowledge, not extra synthesis outcomes.
tables=[]
tables.append({'id':'table-s1','role':'si','page':2,'status':'cited_literature_compilation','columns':['species','Dq_cm-1','B_cm-1','si_reference'],'rows':[
 ['NiCl4^2−',354,734,1],['CoCl4^2−',315,719,2],['MnCl4^2−',360,558,3],['NiBr4^2−',332,680,1],['CoBr4^2−',289,705,2],['MnBr4^2−',310,536,3],['Ni2+:ZnO',420,770,4],['Co2+:ZnO',390,775,4]],'notes':'Species are reference ligand-field systems, not thispapersprecursorinventory.'})
tables.append({'id':'table-s2','role':'si','page':2,'status':'author_estimation_from_literature','columns':['parameter','TM','Cl_ratio','Br_ratio','average_ratio','estimated_MnZnO_cm-1'],'rows':[
 ['Dq','Ni',0.983,1.071,1.027,409],['Dq','Co',0.875,0.932,0.904,432],['B','Ni',1.315,1.269,1.292,596],['B','Co',1.289,1.315,1.302,595]],'final_averages':{'Dq_cm-1':420,'B_cm-1':596},'notes':'RatiosTM2+/Mn2+ averageCl/Br, thenapplyNiZnO/CoZnOvalues; donor inputnotmeasuredMnZnOfit.'})
tables.append({'id':'table-s3','role':'si','page':2,'status':'author_model_and_cited_comparison','columns':['transition_from_6A1','MnZnO_calculated_cm-1','MnZnS_calculated_cm-1','MnZnS_cited_experimental_cm-1'],'rows':[
 ['4T1(G)',24850,16680,18600],['4T2(G)',25230,18290,20100],['4E(G),4A1(G)',25330,19170,21500]],'notes':'Tanabe-Sugano matrices withoutspin-orbitcoupling;C/B6.5estimatedfromMnCl4/MnBr4ratios6.32/6.59. ZnScalculationusesCo/NiZnSparametersref4; experimentalZnSref5. MaintextroundsfirstMnZnOstate toca.24900cm−1.'})
filmrows=[['A',593,0.087,0.67],['B',236,0.154,1.18],['C',279,0.175,1.35],['D',483,0.038,0.29],['E',305,0.059,0.45],['F',282,0.076,0.59]]
tables.append({'id':'table-s4','role':'si','page':4,'status':'reported_measurement_summary','columns':['film','mass_ug','Ms_emu_g','Ms_muB_per_Mn2+'],'rows':filmrows,'temperature_K':300,'notes':'TableS4 numericvaluestranscribed asprinted; checkplottedD/Forderingseparately. MainA–Cmassesrounded0.59/0.24/0.28mg.'})
for table in tables:
 table['evidence']=[ev(table['page'],table['id'].replace('-',' ').title(),'si')]
 for i,row in enumerate(table['rows'],1):
  f(table['id']+'-row-'+str(i),table['id'],'table row',dict(zip(table['columns'],row)),None,table['page'],table['id']+' row'+str(i),status=table['status'],role='si')
for L,mass,emu,mu in filmrows:
 sid='film-'+L.lower()
 for key,val,unit in [('mass-si',mass,'µg'),('Ms-emu',emu,'emu/g'),('Ms-per-Mn',mu,'µB/Mn2+')]:f(sid+'-'+key,sid,key,val,unit,4,'TableS4',role='si',qualifier='300K saturation moment forMs; reportedmassforsample')
for L,mass,coats in [('a',0.59,40),('b',0.24,20),('c',0.28,20)]:
 f('film-'+L+'-mass-main','film-'+L,'maintext mass',mass,'mg',3,'II.B')
 f('film-'+L+'-coats','film-'+L,'spincoated layercount',coats,'layers',3,'II.B')
for s,mean in [('optical-0.13pct',7.9),('optical-1.3pct',79)]:
 f(s+'-model-size',s,'size assumedfordopingstatistics',6.5,'nm',3,'FigureS1',status='author_model_input',role='si')
 f(s+'-model-mn-count',s,'meanMnionspernanocrystal',mean,'ions/particle',3,'FigureS1/equationsS1–S2',status='author_model',role='si',qualifier='Assumeduniformsize,notdirectlycounteddopants. Printedλdefinitionisambiguous; retainedsourcefigureauthoritative.')

# Explicit sample and measurement lineage, never joined merely by nearby text.
samples=[
 {'id':'titration-series','parent_protocol':'protocol-titration','composition':'2%Mnfeed','state':'DMSO/ethanolreactionmixture','linked_items':['figure-1a'],'link_status':'explicit'},
 {'id':'surface-control-epr','parent_protocol':'protocol-surface-control','composition':'ca.2%MnaddedtoZnO','state':'washed,capped,toluenecolloid','linked_items':['figure-2a'],'link_status':'explicit; feednotICPoutcome'},
 {'id':'growth-02-b','parent_protocol':'protocol-hydrolysis','composition':'0.02%Mnfeed','state':'10minaliquot,washedandcapped,toluene','linked_items':['figure-2b'],'link_status':'explicitaliquotseries'},
 {'id':'growth-02-c','parent_protocol':'protocol-hydrolysis','parent_sample':'growth-02-b','lineage_type':'lateraliquotofsamegrowthseries,notphysicalre-useofearliermeasuredaliquot','composition':'0.02%Mnfeed','state':'2hat60°C,washedandcapped','linked_items':['figure-2c'],'link_status':'explicitseries'},
 {'id':'growth-02-d','parent_protocol':'protocol-amine-cleaning','parent_sample':'growth-02-c','composition':'nominal0.02%;feedbasisexplicit','state':'washed,aminecleaned30min180°C,toluene','linked_items':['figure-2d','figure-5'],'link_status':'explicitFigure5asFigure2d'},
 {'id':'cleaned-0.20pct','parent_protocol':'protocol-amine-cleaning','upstream_protocol':'protocol-hydrolysis','composition':'0.20±0.01%MnbyICP;0.50%feed','state':'amine-treatedcolloids','linked_items':['figure-1b-colloid','figure-3b','figure-3c','figure-3d','figure-10-colloid'],'link_status':'explicit samecolloidforFigure1b/Figure3/filmA;Figure10samefilmAprecursor'},
 {'id':'cleaned-0.20pct-powder','parent_sample':'cleaned-0.20pct','lineage_type':'rapidprecipitationfromtoluene','state':'freestandingpowder','linked_items':['figure-3a-colloid','figure-8-colloid','figure-9b-colloid'],'link_status':'explicitmaterialstate;individualaliquotIDsnotreported'},
 {'id':'topo-1.1pct','parent_protocol':'protocol-topo','composition':'1.1%Mnreported','state':'TOPO-cappedcolloid→quartzdrop-coatedfrozensolutionforMCD','linked_items':['figure-6'],'link_status':'explicitsamesampleabs/MCD;not0.20%sample'},
 {'id':'optical-pure-zno','parent_protocol':'protocol-hydrolysis','variant':'undopedcontrol','state':'dodecylamineheated,capped,toluene','linked_items':['figure-7'],'link_status':'explicitopticalcontrol;notnecessarilyphysicalsamesynthesisbatchassurfacecontrol'},
 {'id':'optical-0.13pct','parent_protocol':'protocol-hydrolysis','post_treatment':'protocol-amine-cleaning','composition':'0.13%estimatedMn','state':'dodecylaminecappedtoluene','linked_items':['figure-7','figure-s1'],'link_status':'explicitoptical/statisticsmatch;feednotgiven'},
 {'id':'optical-1.3pct','parent_protocol':'protocol-hydrolysis','post_treatment':'protocol-amine-cleaning','composition':'1.3%Mnreported','state':'dodecylaminecappedtoluene','linked_items':['figure-7','figure-s1'],'link_status':'explicitoptical/statisticsmatch;feednotgiven'},
]
for L in 'abcdef':
 samples.append({'id':'film-'+L,'parent_protocol':'protocol-films','parent_sample':'cleaned-0.20pct' if L in 'abc' else None,'composition':'0.20±0.01%Mnreported','state':'nanocrystallinespincoatedfilm','linked_items':(['figure-8','figure-s2','figure-s3','table-s4']+(['figure-1b-film','figure-3a-film','figure-9','figure-10-film'] if L=='a' else ['figure-9a'] if L=='b' else [])) if L in 'abc' else ['figure-s3','table-s4'],'link_status':'A–Cexplicit0.20%precursorlink;D–Fsame nominalmaterial/procedure butindividualparentbatchnotgiven','missing':'Noindependentinitialfeed/coatcountforD–F'})
for name in ['air','zinc-series','anoxic','naoac','nitrate']:
 samples.append({'id':'oxidation-'+name,'parent_protocol':'protocol-oxidation-controls','state':'DMSOstockafter5days','linked_items':['figure-4'],'link_status':'explicitcontrolvariant','composition':'0.002MMnacetate exceptnitratevariant0.002MMnnitrate'})

equations=[
 {'id':'equation-1','page':7,'role':'main','expression':'H = g μB H·S + A S·I + D[Sz² − S(S+1)/3]','classification':'authorfitHamiltonian','meaning':'Zeeman,hyperfineandaxialzero-fieldsplitting;g/Aapproximatedisotropic;wurtzitehexagonalsymmetry','asset':'equation-1'},
 {'id':'equation-2','page':8,'role':'main','expression':'Mn2+ + 2OH− + O2 → MnOx·nH2O','classification':'schematiccontextreaction','meaning':'Genericoxidationpath,notbalancedpreparativeequation;productphase/hydrationunspecified','asset':'equation-2'},
 {'id':'equation-3','page':9,'role':'main','expression':'ECT = 30000 cm−1[χopt(D) − χopt(A)] + ΔSPE ± 10Dq','classification':'citedelectronegativitymodel','meaning':'Jørgensenopticalelectronegativitymodel;ΔSPE=+(28/9)[(5/2)B+C]forMnacceptor/donortransitions','asset':'equation-3'},
 {'id':'equation-4','page':10,'role':'main','expression':'M = (N g μB/2){(2S+1)coth[(2S+1)gμBH/(2kT)] − coth[gμBH/(2kT)]}','classification':'Brillouinmodel','meaning':'Nanocrystal5Kdata reproducedwithS5/2,g1.999,NfromICPwithoutfitting;filmAparamagneticresidualfitusesNonly','asset':'equation-4'},
 {'id':'equation-s1','page':3,'role':'si','expression':'P(n|N) = N!/[n!(N−n)!] (x/N)^n (1−x/N)^(N−n)','classification':'printedbinomialexpressionwithnotationambiguity','meaning':'PrintedtextcallsMnstatisticsPoisson;sourceusesnforensembleMn,Ntotalcations,andxplottedionsperNC. Preserveprintedexpression;notexecutedasauditedstatisticalcode.','asset':'figure-s1-equations'},
 {'id':'equation-s2','page':3,'role':'si','expression':'P(x) = λ^x exp(−λ)/x!','classification':'Poissonmodelwithambiguousparameterdefinition','meaning':'PrintedλdefinedasoverallMnconcentrationn/(N+n),butreportedmean7.9/79requiresmeanperparticle,notfraction0.0013/0.013. No silentcorrection;sourcefiguresandmeanspreserved.','asset':'figure-s1-equations'},
 {'id':'mcd-definition','page':3,'role':'main','expression':'ΔA = AL−AR; θ(deg) = 32.9 ΔA/A','classification':'reportedmeasurementnormalization','meaning':'Adenominatorasprinted;notrecastasgenericrawellipticitydefinition','asset':'main-page-3'}]
for q in equations:q['evidence']=[ev(q['page'],q['id'],q['role'])]

figure_specs=[
 ('figure-1',3,'Measured300Kabsorption:titrationand0.20%colloid/filmA','titration-series,cleaned-0.20pct,film-a','Panelaincrements0.15eq;panelbcolloidvsfilmA;separateexperiments;filmstraylightlimit27kcm−1.'),
 ('figure-2',4,'Measured300KX-bandEPRgrowth/surfacecleaning','surface-control-epr,growth-02-b,growth-02-c,growth-02-d','Surfacecontrolandthreealiquots;notfourindependentfullyquantifiedsyntheses.'),
 ('figure-3',4,'XRD,TEM,histogram,HRTEM','cleaned-0.20pct,cleaned-0.20pct-powder,film-a','XRDexperimentalpowder/filmpluswurtzitereferencepositions100,002,101,102,110,103;TEM50nmbar,HRTEM5nmbar2.34/2.74Å.'),
 ('figure-4',4,'Manganese-stockoxidationcontrolabsorption','oxidation-air,oxidation-zinc-series,oxidation-anoxic,oxidation-naoac,oxidation-nitrate','Dataand0/5dayinset;concentration/atmospherecontrols;notproductphaseidentification.'),
 ('figure-5',5,'X/Q-bandEPRexperimentandsimulations','growth-02-d','X1/Q1with2%D-strain;X2/Q2without;simulationtracesnotadditionalmeasurements.'),
 ('figure-6',5,'TOPO1.1%absorptionand5Kvariable-fieldMCD','topo-1.1pct','MeasuredspectraandsaturationplusS5/2Brillouinmodel;frozensolutiononsupport,notspincoatedferromagneticfilm.'),
 ('figure-7',5,'Measuredabsorptionandluminescence','optical-pure-zno,optical-0.13pct,optical-1.3pct','Normalizedabsorbanceatemissionexcitation;0.13%estimated;negativeMn-emissionresultretained.'),
 ('figure-8',6,'Measuredmagnetization5/300K','cleaned-0.20pct-powder,film-a,film-b,film-c','Colloidsparamagnetic,filmsferromagneticwithresidualparamagnetism.'),
 ('figure-9',6,'ZFCandparamagneticresidualanalysis','film-a,film-b,cleaned-0.20pct-powder','PanelZFC80Oe;5Kfieldseriesand1Ttemperatureseries;solidcurvesBrillouinmodel;errorbarsMncontentuncertainty.'),
 ('figure-10',6,'Measured300KEPRcolloid/filmA','cleaned-0.20pct,film-a','FMRbroadfilmresonanceplusparamagneticMnandnewg2.00line.'),
 ('figure-s1-equations',3,'Calculateddopantnumberdistributions','optical-0.13pct,optical-1.3pct','Uniform6.5nmparticles;7.9/79meandopants;notcountedatomisticstructure;notationgap.','si'),
 ('figure-s2',4,'Temperature-dependentfilmhysteresisparameters','film-a,film-b,film-c','Ms,MR/MS,Hc;originalpointsnotdigitized;Tcnotlocatedwithinrange.','si'),
 ('figure-s3',4,'300Krawandmass-normalizedfilmhysteresis','film-a,film-b,film-c,film-d,film-e,film-f','Sixfilms;substratediamagnetismsubtracted;panelrawEMUversusnormalizedEMU/g;TableS4heldseparately.','si')]
visuals=[]
for spec in figure_specs:
 aid,pg,title,sids,note,*r=spec;role=r[0] if r else 'main'
 visuals.append({'id':aid,'kind':'figure','title':title,'sample_ids':sids.split(','),'evidence':[ev(pg,aid,role)],'asset_id':aid,'disposition':'original_readable_asset_and_semantic_extraction','numeric_trace_status':'not_digitized','notes':note})
for t in tables:visuals.append({'id':t['id'],'kind':'table','evidence':t['evidence'],'asset_id':t['id'],'disposition':'allprintedrows_transcribed;originalassetretained','sample_ids':['film-'+r[0].lower() for r in filmrows] if t['id']=='table-s4' else [],'notes':t['notes']})
visuals.append({'id':'scheme-1','kind':'scheme','title':'AuthorschemeforZnacetateinhibitionofMnoxidation','evidence':[ev(8,'Scheme1')],'asset_id':'scheme-1','disposition':'authorchemicalinterpretation_notmeasuredmechanisticintermediate','notes':'Mn(OAc)2→manganeseoxidesunderO2;withZn(OAc)2oxidationblocked;N(Me)4OHgivesMn2+:ZnO.'})

intuition=[
 {'id':'homogeneous-feed','classification':'authorrationale','claim':'Directsolutionchemistryaimstocontrolcompositionandavoidsegregatedoxide/reducing/high-temperaturedopantimpurities;highqualitycolloidsenablesolutionprocessing.','evidence':[ev(2,'Introduction'),ev(12,'Conclusion')]},
 {'id':'induction','classification':'authorinterpretationwithcitedmodel','claim':'0.45eqinductioninterpretedassupersaturationbeforeZnOnucleation,LaMermodelref39;basiczincacetateclustersbelievedprecursorsrefs35/40.','evidence':[ev(6,'IV.A')]},
 {'id':'amine-clean','classification':'authorsupportedinterpretation','claim':'Dodecylamineligates/solvatessurface-exposeddopants;sharperEPRsupportsmorehomogeneousinternalMn;concurrentOstwaldripeningchangesparticlesize.','evidence':[ev(7,'IV.B-D'),ev(8,'IV.D')]},
 {'id':'air-protection','classification':'authorproposedmechanism','claim':'Zn2+-boundwateracidificationversusacetatebasicityproposedtoinhibitMnoxidation;measuredpHnotreported. ClusterincorporationproposedtopreventMn-richcoalescence.','evidence':[ev(8,'IV.E/Scheme1')]},
 {'id':'dstrain','classification':'authorinterpretation','claim':'SmallD-strainattributedtosurfacerelaxationandgreaterdistortionrange;notrefinedatomiccoordinates.','evidence':[ev(7,'IV.C')]},
 {'id':'ct','classification':'authortentativeassignment','claim':'SubgapintensityandMCDdisfavorweakligand-fieldorigin. OpticalelectronegativitymodeltentativelyassignsMn→CBCT;strongintensitycouldsuggestVB→Mn,acknowledgeduncertaintyretained.','evidence':[ev(8,'IV.F'),ev(9,'IV.F')]},
 {'id':'luminescence','classification':'authorproposedphotophysics','claim':'DodecylaminepassivationassociatedwithhigherUV:greenemission. LowlyingMLCTproposedasnonradiativeMnrelaxation;Mnlikelycompeteswithsurfacetrapsforexcitonicenergy,ratherthanstrongdirectFörsterquenching.','evidence':[ev(10,'IV.G')]},
 {'id':'ferromagnetism','classification':'authormagneticinterpretation','claim':'FilmFMRandhysteresisconsistentwithcooperativemagnetism;residualparamagnetismretained. AbsenceofXRDimpuritypeaksisnotdecisiveat0.2%Mn;ZFC/noMnOorMn3O4transitionandhomogeneousprecursorssupportauthorsargument.','evidence':[ev(11,'IV.H')]},
 {'id':'carrier-hypothesis','classification':'authoroutlook_hypothesis_unverified','claim':'Radical-likeg2.00linecouldsignalredoxduringfilmformation;dodecylamine-derivednitrogenp-typedefectsisonepossibility. Carrierpolarity,density,nitrogenincorporationandmagneticmechanismnotdemonstrated;authorsacknowledgen-typecompensationdifficulty.','evidence':[ev(11,'IV.H'),ev(12,'IV.Hcontinued')]}
]

gaps=[
 {'id':'g-absolute-scale','scope':'retainedsynthesisroutes','issue':'No absolute synthesischarge, stock/reactionvolumes, yield, additionrate, washvolumes/cycles, separationforce/time, orquantifiedinitialcappingstage.','effect':'PartialprotocolrecordsusefulbutnotcompleteSOP/fullyquantifiedrecipeoutcomelabel.'},
 {'id':'g-tmah-formula','scope':'materials','issue':'II.AprintsN(CH4)4OH·5H2O;II.BN(Me)4OH·5H2O.','resolution':'Keeprawmisprintandnormalizenamedtetramethylammoniumidentity;notpropagatetheCH4formula.'},
 {'id':'g-base','scope':'1.7equivgenericrecipe/1.65equivtitration','issue':'Titrationcloudsbeyondca.1.65eqwhilecommonprotocoluses1.7eq.','resolution':'Keepseparatescopes;donotchangethepublishedrecipeorclaimexact1.65limitforallfeeds.'},
 {'id':'g-topo','scope':'TOPO1.1%sample','issue':'Heatingprocedurecitesref32withoutrestatingquantities/conditions;ref32fulltextnotinspectedinthistask.','resolution':'Retainpartialalternativeandlocalreferenceidentity;noautomaticinheritancefromamineprocedure.'},
 {'id':'g-mn-feed','scope':'0.02%versus0.20%andoptical/MCDsamples','issue':'Only0.20±0.01%productexplicitlylinkedto0.50%feed;0.02%EPRusesfeed/nominaldescriptor;optical0.13%estimatedand1.3%,MCD1.1%donotstateinitialfeed.','resolution':'Separatesamplegroups;maskunreportedfeed/outcomefields.'},
 {'id':'g-s4-count','scope':'supportinventory','issue':'MainSIdeclarationsaysthreetables,actualmatchedSIhasfourincludingTableS4.','resolution':'Inventoryanduseallfour;notexcludetheadditionalfilms.'},
 {'id':'g-poisson','scope':'SIEqS1/S2','issue':'Printedvariablesandλdefinitionmixconcentrationandmeanperparticle;mean7.9/79notfraction0.0013/0.013.','resolution':'Preserveequationassetsandreportedmeansasauthormodel,flagnotation;noautomaticallyexecutedmodeloratomiccounttraininglabels.'},
 {'id':'g-structure','scope':'sample-specificcrystalstructure','issue':'WurtziteXRDandHRTEMevidencebutnoCIF,VESTA,atomiccoordinates/refinedoccupancies/latticeconstants;noSAEDpatterninall16inspectedpages.','resolution':'Phase/morphologyrecordallowed;exactexperimentalstructure-recipepairfalse. Anyfuturebulkunitcellmustbeexternalreferenceorillustrative.'},
 {'id':'g-film-df','scope':'filmsD–F','issue':'SIincludesmassesandmagnetizationbutnocoatcounts/exactparentbatches/individuallyreportedannealingconditions.','resolution':'Retainpartialfilmoutcomes;donotassume20or40coats.'},
 {'id':'g-film-mass','scope':'filmsA–C','issue':'Main0.59/0.24/0.28mgversusSI593/236/279µg.','resolution':'Bothprintedformsretained;likelyroundingconsistent,notindependentmassmeasurements.'},
 {'id':'g-si-curve-table','scope':'FigureS3/TableS4','issue':'Plot-onlyD–FcurveorderingrequiresindependentcheckagainstTableS4;do notderiveadditionalprecisemagnetizationvaluesfromundigitizedimage.','resolution':'Originalfigureandexacttablevaluesseparate;auditorcheckrequested.'},
 {'id':'g-raw-curves','scope':'allplottedcharacterization','issue':'Sourceprovidesplots,notrawnumericalarrays;curves/histogrampointsnotdigitized.','resolution':'Readableoriginalassetsandreportedscalaranchorsretained;rawdatastatusunavailable.'},
 {'id':'g-interpretation','scope':'mechanism/properties','issue':'No measuredpH,carrierdensity/polarity,nitrogenheteroatomcontent,orquantifiedimpuritydetectionlimit.','resolution':'Authorshypothesesnotexperimentallabels;Tc350Kisalowerbound.'},
 {'id':'g-other-techniques','scope':'characterizationcoverage','issue':'No Raman,SAED,measuredatomicstructure,DFTcalculationforthespecificsample,orelectricalcarriertransportreportedinthesuppliedmain/SI.','resolution':'Do notinventtheseassetsorvalues;MCD/EPR/magneticpropertiesaretheactualadditionaltechniques.'}
]

# Retain all numbered bibliographic entries as reference text and page locators.
# Main references are interleaved below columns; source-backed text retained in
# reference-pages.json for exact provenance, and semantic roles summarized here.
refpages={1:list(range(1,16)),2:list(range(16,35)),3:list(range(35,39)),6:[39,40],7:[41,42,43,44],8:[45,46],9:list(range(47,54)),10:[54,55,56,57,58],11:[59,60,61],12:[62,63]}
references=[]
for pg,nums in refpages.items():
 text=(B/f'main-{pg:02d}.txt').read_text(encoding='utf-8')
 for n in nums:
  match=re.search(r'(?m)^\('+str(n)+r'\)\s',text)
  if not match: raise AssertionError((pg,n))
  tail=text[match.start():]
  nxt=re.search(r'(?m)^\('+str(n+1)+r'\)\s',tail)
  chunk=tail[:nxt.start()] if nxt else tail
  # Last footer may remain; original source page is authoritative.
  references.append({'id':f'main-ref-{n}','reference_number':n,'source_role':'main','pdf_page':pg,'bibliography_extracted_text':chunk.strip(),'inspection_status':'citationandpaperdiscussionread; citedfullworknotinspectedinthistask','role':'upstreamTOPOmethodandMCDprocedure' if n==32 else 'context/model/comparison,notthissamplesexperiment'})
si_refs=[
 'Smith, G.P.; Liu, C.H.; Griffiths, T.R. J. Am. Chem. Soc. 1964,86(22),4796–4802.',
 'Marcotrigiano,G.; Menabue,L.; Pellacani,G.C. J. Coord. Chem.1977,7(1),1–8.',
 'Cotton,F.A.; Goodgame,D.M.L.; Goodgame,M. J. Am. Chem. Soc.1962,84(2),167–172.',
 'Weakliem,H.A. J. Chem. Phys.1962,36,2117–2140.',
 'Dreyhsig,J.; Allen,J.W. J. Phys.:Condens.Matter1989,1,1087–1099.']
for i,text in enumerate(si_refs,1):references.append({'id':'si-ref-'+str(i),'reference_number':i,'source_role':'si','pdf_page':4,'bibliography_transcription':text,'inspection_status':'citationonly;citedfullworknotinspected','role':'literatureinputtoTablesS1–S3'})

inventory={'schema':'mattersyn-complete-source-extraction/1','source_id':'norberg2004','doi':'10.1021/ja048427j','title':'Synthesis of Colloidal Mn2+:ZnO Quantum Dots and High-TC Ferromagnetic Nanocrystalline Thin Films','authors':['Nick S. Norberg','Kevin R. Kittilstved','James E. Amonette','Ravi K. Kukkadapu','Dana A. Schwartz','Daniel R. Gamelin'],'year':2004,'journal':'Journal of the American Chemical Society','volume':126,'pages':'9387–9398','published_online':'2004-07-14','received':'2004-03-18','extraction_author':AUTHOR,'created_at':NOW,'source_generation':2,'bundle_sha256':'1d9c4eafe7b6aee109447951f6c9be2a2fc20780802bcbe577b93ee7dc3ea5ad','scope':'All12main+4matchedSIpagesreadandvisuallyinspectedbysourceauthor. Structuredextractioncompletependingindependentaudit;plotpreservationdoesnotmeanrawtracedigitization.','source_documents':[{'id':'norberg2004-main','role':'main','sha256':MH,'pages':12},{'id':'norberg2004-si','role':'si','sha256':SH,'pages':4}],'materials':materials,'stocks':stocks,'protocols':protocols,'samples':samples,'figures_tables_schemes':visuals,'equations':equations,'tables':tables,'chemical_intuition':intuition,'references':references,'gaps':gaps,'other_source_content':[{'kind':'acknowledgment','evidence':[ev(12,'Acknowledgment')],'disposition':'preservedsourcepage;funding/instrumentassistancecontext,notexperimentalrecord','notes':'NSFDMR-0239325/ECS-0224138;UW/PNNLJointInstitutes;NIHP30ES07033;EMSL/DOE;Weihe/Tregenna-PiggottEPR,Wang/BryanTEM.'},{'kind':'copyright/accessfooter','evidence':[ev(1,'marginandfooter')],'disposition':'sourcemetadataonly;notinstructions'},{'kind':'unpublishedreference60','evidence':[ev(11,'Reference60')],'disposition':'unpublishedCoZnOcomparison;noindependentlyavailableexperimentextracted'}],'training_status':{'exact_experimental_structure_recipe_pair':False,'reason':'Noexperimentallyrefinedatomiccoordinatesforthesesamples;incompleteabsoluteprotocolfields.','all_facts_eligible_training':False,'note':'Task-specificinclusionrequirescanonicalizationandindependentaudit;phase/precursor/relative-conditionknowledgecanbeusefulwithoutCIF.'},'audit_state':'pending','integration_state':'not_started','publication_state':'not_started'}
save('source-inventory.json',inventory)
save('source-facts.json',{'schema':'mattersyn-source-facts/1','source_id':'norberg2004','source_sha256':MH,'si_sha256':SH,'created_at':NOW,'author':AUTHOR,'scope':'Source-nativequantities,fullytranscribedSItables,authorsmodelsandcitedcontextseparatelytyped. Noautomatictrainingadmission.','facts':facts})

page_topics={1:'Title/identity,abstract,Introduction,refs1–15',2:'Introductioncontinued;II.Afullmaterials;refs16–34',3:'II.Ballpreparation/controls/films;II.Cinstruments;Results/figure1;refs35–38',4:'Results/figures2–4,EPRaliquotlineage,XRD/TEM/scalebars,oxidationcontrols',5:'Results/figures5–7,EPR/MCD/opticalsampleboundaries,quenching,magnetsummary',6:'Results/figures8–10;ZFC/residualparamagnetism;IV.A;refs39–40',7:'IV.A–D,EPRsurfacecleaningandHamiltonianfit;eq1;refs41–44',8:'IV.D–F,XRDdiameter,oxidationcontrols,eq2,Scheme1,MCDassignment;refs45–46',9:'IV.Fcharge-transferanalysis/modelinputs/eq3;refs47–53',10:'IV.Gluminescence,IV.Hmagneticmodel/eq4;refs54–58',11:'IV.HFMR,filmXRDsize,impuritylimits,magneticfractions,carrierhypothesis;refs59–61',12:'Carrierhypothesis,Conclusion,Acknowledgment,SIdeclaration;refs62–63'}
coverage=[]
for role,count in [('main',12),('si',4)]:
 for p in range(1,count+1):
  coverage.append({'source_role':role,'sha256':MH if role=='main' else SH,'pdf_page':p,'printed_page':str(9386+p) if role=='main' else 'S-'+str(p),'text_read':True,'visual_inspection':True,'reviewer':AUTHOR,'scope':page_topics[p] if role=='main' else {1:'Identitytitleandcompleteauthorlist',2:'TablesS1–S3allrows/footnotes/modelversusreferencevalues',3:'FigureS1,eqS1/S2,printedvariables,7.9/79means;notationambiguity',4:'FigureS2/S3allpanels,TableS4all6films,5references'}[p],'text_cache':f'{role}-{p:02d}.txt','visual_initial':f'main-{p:02d}.png' if role=='main' else f'si-{p}.png','high_resolution_original_asset':f'{role}-page-{p}','raw_curve_digitization':False,'unread_regions':[]})
save('page-coverage.json',{'schema':'mattersyn-page-coverage/1','author':AUTHOR,'created_at':NOW,'main_pages_read':12,'main_pages_visually_inspected':12,'si_pages_read':4,'si_pages_visually_inspected':4,'pages':coverage,'source_author_read_complete':True,'independent_scientific_audit':'pending','claim_limit':'Allprovidedpagesread/inventoried;notrawtracedigitization,citedfullreferenceinspection,externalreproductionorpublication.'})
save('extraction-summary.json',{'created_at':NOW,'author':AUTHOR,'main_pages':12,'si_pages':4,'protocol_families':len(protocols),'protocol_count_is_independent_complete_recipe_count':False,'materials':len(materials),'stocks':len(stocks),'samples_and_controls':len(samples),'facts':len(facts),'main_figures':10,'si_figures':3,'tables':4,'schemes':1,'numbered_equations':6,'additional_measurement_equations':1,'numbered_main_references':63,'numbered_si_references':5,'independent_scientific_audit':'pending','integrated':False,'published':False})
print(json.dumps({'facts':len(facts),'protocol_families':len(protocols),'samples':len(samples),'references':len(references)}))
