"""Bind completed independent manual and programmatic reader review to final files."""
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
B=Path(__file__).resolve().parent;O=B/'public-review-proposal'
def rd(p):return json.loads(Path(p).read_text(encoding='utf8'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
L=rd(B/'reader-link-audit.json');P=rd(B/'reader-original-pixel-audit.json');D=rd(B/'reader-render-delta-audit.json');R=rd(O/'norberg2004.json');M=rd(O/'reader-package-manifest.json');C=rd(B/'canonical-records-audit.json')
assert L['status']=='passed'and P['status']=='passed'and D['status']=='passed'
assert L['reader_sha256']==P['reader_sha256']==sha(O/'norberg2004.json')
manual=[
 ('identity','The retained 12-page main article and four-page SI remain correctly paired by the existing independently audited source identity. Their exact source hashes and current canonical audit boundary are unchanged.'),
 ('source-count','The main declaration of three SI tables is distinguished from the four supplied tables. All four tables and three SI figures are reachable.'),
 ('prose','All 288 reader cards, their notes and the 47 revised operation texts were independently read. The requested operation-prose correction removes compressed descriptions without changing typed values or canonical links.'),
 ('route-count','One common partial Mn:ZnO route is not inflated into separate complete syntheses for optical, film, control or model contexts. Unknown absolute scale, feed assignments and workup conditions remain unknown.'),
 ('precursors','Hydrated acetate identities, TMAH pentahydrate, DMSO, ethanol and reagent grades remain distinct. The printed TMAH formula discrepancy is explicit; technical TOPO is not presented as an assayed pure compound.'),
 ('atmospheres','Atmospheric common synthesis is distinguished from nitrogen used in 180 °C amine cleaning. The anaerobic oxidation control does not receive a guessed gas identity or pressure.'),
 ('base-series','Common 1.7-equivalent synthesis, the 1.65-equivalent titration trace, 0.15-equivalent increments and onset/clouding statements retain separate scope.'),
 ('ripening','Ambient ripening over days and heating near 60 °C are alternatives. A later sampled reaction is not represented as consuming an already analyzed aliquot.'),
 ('workup','Ethyl-acetate precipitation, ethanol resuspension, repeated heptane washing, initial amine capping and subsequent heated cleaning remain separate operations with unreported volumes and separation settings.'),
 ('cleaning','Approximately 30 min at 180 °C under nitrogen and cooling strictly below 80 °C remain source-qualified. Dodecylamine melting point is a reagent property, not an additional hold.'),
 ('surface-control','The deliberate surface-bound Mn control starts with pure ZnO, receives a small Mn charge and 0.002 equivalent of LiOH, and is not assigned the later stripping treatment. Unknown LiOH concentration and equivalent reference remain explicit.'),
 ('topo','The TOPO alternative remains an incompletely restated cited method. The 1.1% frozen-solution MCD sample is not assigned amine treatment conditions or the 0.20% specimen identity.'),
 ('feed-outcome','The explicit 0.50% feed to 0.20 ± 0.01% ICP product association is distinct from the nominal 0.02% growth series, estimated 0.13% optical sample, reported 1.3% sample and 1.1% MCD specimen.'),
 ('films-abc','A–C coating counts and per-layer 525 °C air annealing are retained. Main masses and SI microgram masses are separately preserved as rounded representations of the named films, not independent replicates.'),
 ('films-def','D–F have SI magnetic outcomes without independently supplied coating counts, exact parent batches or repeated thermal histories. Missing values remain masked.'),
 ('df-conflict','Figure S3b orders D/E/F differently from Table S4. The original plot and exact tabulated values are both present, with no swapped labels or resolved D/F training targets.'),
 ('structure','Figure 3 powder/film XRD, TEM histogram and HRTEM panel associations remain distinct. TEM, Scherrer and optical size estimates are not conflated. No SAED or experimental CIF/coordinates are claimed.'),
 ('powder-state','Rapidly precipitated powder, colloid and film states are separated; shared source material does not imply one physical aliquot across instruments.'),
 ('epr','Experimental X/Q-band spectra are distinguished from fitted and simulated traces. Bulk reference constants, nanocrystal g/A/D fits and D-strain retain their respective provenance.'),
 ('mcd','The original MCD normalization retains its denominator A. Frozen TOPO-capped solution, field-dependent measurement and Brillouin comparison remain distinct from ferromagnetic spin-coated films.'),
 ('optical','Undoped, estimated 0.13% and reported 1.3% samples retain separate spectra and normalization. The absence of Mn ligand-field emission is a measured negative observation; the high-dopant UV scattering qualification remains visible.'),
 ('domain-spin','S > 800 is an author-estimated effective domain-spin bound for the film set, not an atomic spin or a separately assigned film-A value.'),
 ('temperature-bound','Tc > 350 K is a lower bound limited by the instrument window. ZFC behavior over 5–350 K does not establish an exact Curie point or universal impurity-detection threshold.'),
 ('magnetic-model','Colloid Brillouin calculation uses ICP-based N with no fit; the residual-film analysis fits N. These models are not newly measured scalar outcomes.'),
 ('carrier-hypothesis','The g = 2.00 feature has a tentative radical/redox interpretation. Carrier polarity, carrier density and retained nitrogen are not represented as measured.'),
 ('oxidation-controls','Air, anaerobic, added Zn acetate, sodium acetate and nitrate substitution controls remain separate solutions. Their solution stability is not classified as nanocrystal structural evidence.'),
 ('model-tables','All S1–S3 table rows retain cited ligand systems, calculated estimates and experimental-reference columns. They are not attributed as additional measurements of the synthesized Mn:ZnO specimens.'),
 ('statistics','Uniform 6.5 nm and 7.9/79 dopants are source-model assumptions and outputs. The inconsistent printed binomial/Poisson notation is retained rather than silently repaired or executed as validated code.'),
 ('mechanisms','Precursor clusters, acidification, Mn oxidation inhibition, amine coordination, charge transfer and quenching pathways retain author-interpretation status. Scheme 1 and schematic Equation 2 are not experimentally isolated intermediates or balanced synthesis recipes.'),
 ('citations','All 63 main reference groups and five SI references are retained as source citations; substantive notes and the unpublished comparison stay explicitly scoped. External full-text inspection is not claimed.'),
 ('original-crops','All 24 existing figure/table/scheme/equation/method crops were viewed on six labeled audit contact sheets. No graph was redrawn or digitized. The older degree-symbol rendering defect was independently confirmed against the original PDF using PDFium.'),
 ('replacement-pixels','All 40 replacement full pages and crops pass exact pixel comparison against independent fresh same-source PDFium rendering at the original 220 dpi and crop bounds. Renderer changes do not constitute numerical or scientific edits.'),
 ('downstream','The reader remains private. This audit does not approve molecular or apparatus bindings, actual Site rendering, browser interaction, training tasks or publication.')]
bound={**L['bound_files'],**P['bound_files']}
for n in ['reader-link-audit.json','reader-original-pixel-audit.json','reader-render-delta-audit.json','audit_reader_links.py','audit_reader_pdfium.py','audit_reader_render_delta.py','finalize_reader_audit.py','canonical-records-audit.json']:bound[str(B/n)]=sha(B/n)
for n in ['reader-package-manifest.json','reader-prose-correction.json','reader-render-correction.json','reader-original-assets-manifest.json']:bound[str(O/n)]=sha(O/n)
for x in D['unchanged_original_assets']:bound[x['path']]=x['sha256']
for p in (B/'reader-audit-assets').glob('*.png'):bound[str(p)]=sha(p)
assert all(sha(Path(p))==h for p,h in bound.items())
hist=[{'id':'R1','classification':'reader prose','finding':'Original operation cards repeated compressed canonical descriptions and raw implementation context.','resolution':'Author replaced exactly 47 operation text fields with academic sentences; source, canonical quantities and links were unchanged.','status':'resolved','evidence':'public-review-proposal/reader-prose-correction.json'}, {'id':'R2','classification':'original-render fidelity','finding':'Poppler rendered the degree symbol incorrectly in the main page 3 preparation excerpt and Figure 2 caption. The same retained PDF renders correct °C with PDFium.','resolution':'Author supplied a separate uniform set of 40 reader-only PDFium originals. Exact source hashes, 220 dpi and frozen crop bounds were retained. The old extraction asset bytes and canonical package were not modified.','status':'resolved','evidence':['reader-audit-assets/sample-preparation-pdfium.png','reader-original-pixel-audit.json']}]
assets=rd(B/'reader-assets/asset-manifest.json')['assets'];bindings=rd(O/'reader-bindings-proposal.json')['original_assets']
hist[1]['confirmed_glyph_replacements']=[]
for aid,locations in [('sample-preparation','60, 30, 180, 80 and 525 °C in the preparation text'),('figure-2','60 °C in the Figure 2 caption')]:
 old=next(a for a in assets if a['id']==aid);new=next(a for a in bindings if a['source_asset_id']==aid)
 hist[1]['confirmed_glyph_replacements'].append({'source_asset_id':aid,'glyph_locations':locations,'old_render_path':str(B/old['path']),'old_render_sha256':old['sha256'],'replacement_path':new['private_path'],'replacement_sha256':new['sha256'],'source_pdf_page':old['pdf_page'],'source_pdf_sha256':old['source_sha256'],'crop_pixel_bounds':old['crop']['bounds'],'replacement_visually_inspected_at_native_size':True})
out={'schema':'mattersyn-independent-reader-source-audit/1','source_id':'norberg2004','auditor':'/root/peng1998_reader_assets','reader_author':'/root/norberg2004_extract','audited_at':datetime.now(timezone.utc).isoformat(),'status':'passed','scope':'Independent private source-reader prose, canonical quantity/pointer, source coverage, sample association and original-image fidelity audit. The earlier separate complete source/canonical audit is reused only at its unchanged hash boundary. No repeated full extraction or downstream viewer approval is claimed.','reader_sha256':sha(O/'norberg2004.json'),'reader_manifest_sha256':sha(O/'reader-package-manifest.json'),'counts':R['counts'],'programmatic_link_checks':L['check_count'],'original_pixel_checks':P['asset_count'],'manual_scientific_check_count':len(manual),'manual_scientific_checks':[{'id':k,'passed':True,'finding':v}for k,v in manual],'actual_inspection':{'prose_cards_read':288,'updated_operation_cards_read':47,'original_crops_visually_inspected':24,'crop_contact_sheets':[str(B/'reader-audit-assets'/f'contact-{n}.png')for n in range(1,7)],'fresh_pdfium_comparison_source_pages':P['source_pages_rerendered'],'pixel_compared_original_assets':40,'earlier_complete_source_reinspection_boundary':{'canonical_audit_sha256':sha(B/'canonical-records-audit.json'),'source_scope':C['actual_original_source_rechecks']},'scope_note':'All source pages had already been read and visually inspected by this same independent canonical auditor. This reader pass reread all reader prose and source figure/method crops, directly verified original render fidelity and retained the complete existing hash-bound source boundary.'},'finding_history':hist,'open_findings':[],'bound_files':bound,'canonical_record_hashes':C['record_hashes'],'independent':True,'author_files_modified_by_auditor':False,'source_or_canonical_modified':False,'site_modified':False,'ledger_modified':False,'molecular_or_apparatus_bindings_approved':False,'browser_qa_performed':False,'training_eligible':False,'published':False}
p=B/'reader-source-audit.json';p.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
md='# Norberg 2004 independent reader audit\n\nThe private reader passes the completed source/presentation audit. All 288 prose cards, 1,218 exact quantitative or context fields, 201 source facts, 180 mapped units, 47 operations and 40 original assets are covered. The independent link check performed '+str(L['check_count'])+' checks; all 40 replacements match fresh source-PDF pixels.\n\nTwo presentation findings were corrected by the author: 47 operation cards were rewritten as readable prose, and corrupted degree symbols in older Poppler renders were resolved with separate reader-only PDFium assets. The original extraction and canonical files remain unchanged. The precise finding history and file hashes are in the JSON report.\n\nThe D/F film-label conflict, collective S > 800 estimate, missing D–F preparation details, source-model statistical ambiguity and absent experimental coordinates remain explicit. No molecular, apparatus, browser, training or publication approval is granted.\n\nReader SHA256: '+out['reader_sha256']+'\n\nReader manifest SHA256: '+out['reader_manifest_sha256']+'\n'
(B/'reader-source-audit.md').write_text(md,encoding='utf8')
print(json.dumps({'status':'passed','audit_sha256':sha(p),'reader_sha256':out['reader_sha256'],'manual_checks':len(manual),'bound_files':len(bound)},ensure_ascii=False))
