from pathlib import Path
import json,hashlib,math
import pypdfium2 as pdfium
from PIL import Image,ImageDraw,ImageFont
R=Path(__file__).resolve().parent;O=R/'crop-assets';O.mkdir(exist_ok=True);(O/'source-render').mkdir(exist_ok=True)
SOURCE=Path('[local path redacted]');SH='e581449713ddca5e0cb68d05593df476d0e5150b88bc7c6dcbdb269ac70881fb'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
assert sha(SOURCE)==SH
A=[]
def add(id,p,box,title,caption,scope,kind='figure',evidence='experimental',notes=None,panels=None):
 A.append({'id':id,'pdf_page':p,'box':box,'title':title,'caption_paraphrase':caption,'sample_scope':scope,'type':kind,'evidence_type':evidence,'scope_caveats':notes or [],'panels':panels or []})
add('figure-01',2,[612,82,1094,619],'Freshly hydrogen-terminated Si(100) surface','Noncontact AFM image of a freshly etched substrate with monatomic steps.','Etched Si(100) substrate before silver deposition; no Ag nanoparticles assigned.',notes=['Original field 3 µm × 3 µm; reported mean step height 1.3 ± 0.4 Å.','These steps are substrate topography, not silver particle size or a refined atomic structure.'])
add('figure-02',3,[102,82,582,963],'Doping-dependent cyclic voltammetry','Four cyclic-voltammetry panels at 20 mV/s compare silver-free and silver-containing electrolytes and two substrate doping levels.','Panels a/b: n++-Si, c: n-Si; panel d is n-Si in discussion but n++-Si in caption.',panels=['a: silver-free 0.1 M LiClO4/MeCN on n++-Si','b: Ag-containing electrolyte on n++-Si','c: silver-free electrolyte on n-Si','d: Ag-containing electrolyte; doping label conflict'],notes=['Figure caption gives 10.0 mM AgClO4 in b/d; body says 1.0 mM for b. Preserve conflict and do not replace the separate 1 mM plating method.','Axis says Potential, V while tick labels are −800…800 and discussion uses mV; keep original pixels and identify unit inconsistency.','Sequential scans are not separate synthesis recipes.'])
add('scheme-01',4,[102,80,580,663],'Source energy-band interpretation','Six energy diagrams compare degenerate and nondegenerate Si at open, negative and positive polarization.','Authors’ explanatory band model for the two Si doping classes; band edges not experimentally determined here.',kind='scheme',evidence='source_theoretical_schematic',panels=['a–c: n++-Si(100)','d–f: n-Si(100)'],notes=['Shown 1.0 mM Ag+ and approximately 600 meV barrier are model context, not experimentally refined bands.','No measured depletion-layer geometry, atomic interface or particle arrangement is supplied.'])
add('figure-03',4,[612,82,1094,490],'Potential-dependent current transients','Current density versus time for −1000, −800 and −600 mV pulses.','Three n++-Si plating experiments; caption electrolyte 1.5 mM AgClO4 and 0.1 M LiClO4 in MeCN, N2 sparged.',notes=['This 1.5 mM series must remain separate from the general 1 mM plating recipe.','At the more negative potentials the authors discuss coupled silver deposition and hydrogen evolution; total current is not pure silver growth rate.','Axes retain source mA/cm² and milliseconds.'])
add('equation-01',4,[705,1168,1094,1254],'Instantaneous-nucleation current model','Equation 1 gives the rising current dependence I(t) proportional to t^(1/2).','Cited Hills model used to compare nucleation mechanisms, not a measured recipe.',kind='equation',evidence='cited_theoretical_model',notes=['All symbols, exponents and density denominator are retained as original pixels.','Do not use this model to claim instantaneous nucleation; the paper favors progressive nucleation.'])
add('figure-04',5,[102,82,583,1171],'Early current transient and transformed-time comparisons','One −800 mV transient plotted against time, square-root time and time to the three-halves power; inset shows the linear-region fit.','Specific current-transient analysis; exact identity with any Figure5 or Figure7 specimen is not established.',panels=['a: time','b: time^(1/2)','c: time^(3/2), with fit inset'],notes=['Body analyzes approximately 1.6–9.2 ms (transformed range 2–28 ms^(3/2)), not all 25 ms.','Inset slope 0.043315 and R=0.99947 are printed; body rounds R to0.999.','Model-derived N∞=2.32×10^10 cm−2 differs from the later NC-AFM density; do not silently reconcile.'])
add('equation-02',5,[185,1234,580,1317],'Progressive-nucleation current model','Equation 2 gives the t^(3/2) current dependence and model coefficient.','Cited theoretical expression applied to the early transient.',kind='equation',evidence='cited_theoretical_model',notes=['Preserve the printed z N∞ A π numerator and C* notation; do not silently replace symbols or infer missing parameter definitions.','Source note43 separately supplies concentration, diffusion coefficient and silver density used in a calculation.'])
add('figure-05',6,[103,82,1094,1310],'Silver nanoparticle topography at four pulse durations','Four original NC-AFM images and line profiles with Ag deposition at −800 mV.','Panels a/b/c/d correspond to2/7/12/22 ms. Each image spans3 µm ×3 µm.',panels=['a:2 ms, Q=1.6 mC/cm² printed, Γ=0.007','b:7 ms, Q=3.6 mC/cm² printed, Γ=0.016','c:12 ms, Q=8.3 mC/cm² printed, Γ=0.037','d:22 ms, Q=18.7 mC/cm² printed, Γ=0.084'],notes=['Caption and text print mC/cm² here; Figure7/9 use µC/cm². Retain the source inconsistency instead of automatic conversion.','Γ values assume100% silver current efficiency and are upper bounds, not directly measured fractional monolayers.','Line profiles retain Å height units. Lateral image widths are tip-convolved and not reliable particle diameters.'])
add('figure-06',7,[103,82,582,1486],'Original TEM, measured SAED and source ring indexing','TEM of transferred nanoparticles, actual selected-area electron diffraction, and an explanatory indexed-ring drawing.','Particles mechanically removed from Si(100) following −800 mV deposition and transferred to carbon-coated gold TEM grids. Pulse duration, precise batch and Ag concentration of this specimen are unassigned.',evidence='experimental_tem_saed_and_source_schematic',panels=['a: experimental TEM,260 nm ×260 nm region','b: experimental SAED image with original beam stop','c: authors’ drawn FCC silver ring assignment'],notes=['Only b is a measured SAED pattern; c is a source schematic, never substituted for measured diffraction.','Body describes approximately100 particles with diameters10–25 Å in this TEM specimen; do not transfer that range to every NC-AFM formulation.','At least1 h air exposure precedes diffraction; this supports sample-scoped metallic-Ag persistence, not indefinite shelf stability.','No experimentally refined lattice coordinates or sample CIF are supplied.'])
add('figure-06b-saed',7,[124,520,561,952],'Measured selected-area electron diffraction','Standalone original Figure6b SAED panel, with beam stop and unmodified diffraction intensity.','Same transferred specimen as full Figure6; exact pulse duration and batch unassigned.',kind='figure_panel',evidence='experimental_saed',notes=['Parent Figure6 contains caption and panel-to-specimen context; show alongside or link it.','The extracted panel deliberately retains the original beam stop. No spots/rings were added, sharpened, removed or redrawn.','Related Figure6c is an author-drawn indexing diagram; Table1 lists the experimental and reference spacings.'])
add('table-01',7,[612,82,1094,352],'Measured and reference diffraction spacings','Table1 compares four experimental d spacings with the paper’s ICDD FCC silver reference values and relative intensities.','Measured values apply to the transferred nanoparticle diffraction specimen; expected values/intensities are external reference data.',kind='table',evidence='experimental_comparison_with_reference',notes=['hkl111/200/220/311: experimental2.37/2.04/1.42/1.22 Å; expected2.32/2.05/1.44/1.22 Å exactly as printed.','Expected intensities100/90/80/80% are reference values, not measured sample intensities.','The source cites ICDD03-0931; no local verified ICDD CIF is supplied or reconstructed.'])
add('figure-07',8,[102,82,582,655],'Four measured nanoparticle-height distributions','NC-AFM height histograms at increasing charge, with original mean and sigma labels.','Four plotted distributions. Caption lists5/10/15/25 ms from top to bottom at−800 mV.',panels=['top:Q2.8 µC/cm², mean2.2 nm, σ2.4 nm','second:Q7.8 µC/cm², mean7.5 nm, σ4.3 nm','third:Q17.6 µC/cm², mean13.5 nm, σ5.3 nm','bottom:Q38.1 µC/cm², mean17.1 nm, σ6.1 nm'],notes=['Caption says five samples although four histograms and four durations are present. Do not invent the fifth sample.','Body calls the smallest mean2.4 nm and spread2 nm; top histogram labels2.2 and2.4 nm. Preserve both scopes.','Heights are measured from five random3 µm ×3 µm images per sample. Approximate diameter equivalence is a shape-based interpretation, not a lateral AFM measurement.'])
add('figure-08',8,[612,82,1094,524],'Particle density versus pulse duration','Three day-grouped data series show particle areal density as pulse duration increases.','Fifteen depositions at−800 mV grouped into three preparation days; no physical batch IDs supplied.',notes=['Plot ordinate and body say particle density (µm−2); caption incorrectly says mean particle height and height-distribution sigma. Preserve this inconsistency.','Lines guide the eye; do not promote them to a measured continuous recipe-response predictor.','Values from plotted points are not digitized.','Body uses rates per millisecond, whereas Summary prints rates per second.'])
add('figure-09',8,[612,541,1094,1098],'Measured height versus charge and geometric-model curves','Fifteen mean particle heights versus charge, compared with Eq3 curves at three assumed nucleation densities.','Same15 experimental series as Figure8, grouped by preparation day; height error bars and plotted model curves remain distinct.',evidence='experimental_plot_and_geometric_model',notes=['Solid best-fit curve N=4×10^8 cm−2; broken curves N=10^8 and10^9 cm−2. These are model parameters, not three new synthesis batches.','Equation assumes hemispherical particles and instantaneous nucleation; the source uses it for consistency checking despite progressive nucleation.','Charge axis isµC/cm², unlike Figure5 caption mC/cm².','No raw coordinates are digitized and no synthetic curve is generated.'])
add('equation-03',9,[220,82,581,146],'Hemispherical height-versus-charge relationship','Equation3 gives r proportional to Q^(1/3), with nucleation-density and silver-material parameters.','Geometric consistency model; r is particle height/hemisphere radius in this context.',kind='equation',evidence='source_geometric_model',notes=['Strict form assumes instantaneous nucleation and well-defined N; actual source nucleation is progressive.','The following prose refers once to Figure8 but the plotted curves appear in Figure9.','No atomic coordinates, epitaxial interface or measured hemisphere envelope are established.'])
doc=pdfium.PdfDocument(SOURCE);assert len(doc)==9;renders={}
for p in range(1,10):
 im=doc[p-1].render(scale=300/72).to_pil().convert('RGB');im.save(O/'source-render'/f'pdfium-{p:02d}-300dpi.png');renders[p]=im
for a in A:
 norm=[a['box'][i]/(1190 if i%2==0 else 1540) for i in range(4)];im=renders[a['pdf_page']];px=[round(norm[i]*(im.width if i%2==0 else im.height)) for i in range(4)];crop=im.crop(px);p=O/(a['id']+'.png');crop.save(p);w,h=doc[a['pdf_page']-1].get_size()
 a.update(source_id='stiger1999',source_doi='10.1021/la980800b',source_file=SOURCE.name,source_path=str(SOURCE),source_sha256=SH,printed_page=789+a['pdf_page'],relative_asset=p.name,sha256=sha(p),dpi=300,pixel_dimensions=list(crop.size),crop_normalized=norm,bbox_pixels_at_140dpi=a.pop('box'),bbox_pdf_points_top_left=[norm[i]*(w if i%2==0 else h) for i in range(4)],original_source_asset=True,synthetic=False,digitized=False,eligible_training=False,experimental_sample_cif=False,original_caption_preserved=a['type'] in ['figure','table'],visually_reviewed=False,renderer='Original PDF rasterized by PDFium at300 dpi; rectangular crop only')
M={'source_id':'stiger1999','source_doi':'10.1021/la980800b','source_title':'Investigations of Electrochemical Silver Nanocrystal Growth on Hydrogen-Terminated Silicon(100)','source_sha256':SH,'source_file':SOURCE.name,'source_page_count':9,'coverage':{'all_source_pages_text_read':True,'all_source_pages_visually_reviewed':True,'numbered_figures':9,'numbered_tables':1,'numbered_schemes':1,'numbered_equations':3,'additional_original_panel_crops':1,'crop_count':len(A),'individual_crops_visually_reviewed':False},'source_pages':[{'pdf_page':p,'text_read':True,'visual_review':True,'text_sha256':sha(R/f'page-{p}.txt'),'initial_render_sha256':sha(R/f'page-{p}.png')} for p in range(1,10)],'assets':A,'global_limits':['Figure6b is actual SAED; Figure6c is the source schematic ring assignment.','No sample CIF or experimentally refined coordinates exist in the inspected source.','Hydrogen-terminated substrate, silver-free electrochemical controls, CV scans, transient analysis and individual plating-duration specimens remain separate scopes.','The source contains concentration, charge-unit, caption-variable, specimen-count and rate-unit conflicts; original pixels are preserved.','No microscopy enhancement, synthetic diffraction, graph digitization or plot redrawing.']}
save(O/'manifest.json',M)
font=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',22)
for i in range(math.ceil(len(A)/4)):
 sheet=Image.new('RGB',(1800,1800),'#eeeeee');d=ImageDraw.Draw(sheet)
 for n,a in enumerate(A[i*4:i*4+4]):
  x=n%2*900;y=n//2*900;im=Image.open(O/a['relative_asset']).convert('RGB');im.thumbnail((878,850));d.text((x+12,y+8),a['id']+' / PDF p'+str(a['pdf_page']),font=font,fill='black');sheet.paste(im,(x+11,y+40))
 sheet.save(O/f'contact-{i+1:02d}.png')
print(json.dumps({'crops':len(A),'manifest_sha256':sha(O/'manifest.json')}))
