from pathlib import Path
B=Path(__file__).resolve().parent
OUT=B/'reader-assets';OUT.mkdir(exist_ok=True)
s=(B.parent/'la970480g/reader-assets/check_reader_runtime.mjs').read_text(encoding='utf-8')
s=s.replace('yao1998','stiger1999').replace('100 source','144 source')
s=s.replace('cards.length===100&&items.length===100','cards.length===144&&items.length===144')
s=s.replace('Sixteen distinct','Fifteen distinct').replace('filenames.length===16','filenames.length===15')
s=s.replace("input.value='Donnan'","input.value='Schottky'")
s='\n'.join(l for l in s.splitlines() if not any(q in l for q in ["check('No invented XRD plot'","check('Undefined SD unit","check('Local symbol identities"]))
s=s.replace("const body=document", "check('Actual SAED detail and table and scheme accessible',['figure-06b-saed.png','table-01.png','scheme-01.png'].every(f=>filenames.includes(f)));\nconst body=document")
(OUT/'check_reader_runtime.mjs').write_text(s+'\n',encoding='utf-8')

s=(B.parent/'la970480g/reader-assets/audit_canonical_to_reader.py').read_text(encoding='utf-8')
s=s.replace('Yao','Stiger').replace('yao1998','stiger1999').replace('yao-1998-','stiger-1999-')
s=s.replace("routeids={P+'sample-a',P+'sample-b'}","routeids={P+'electrodeposition'}")
s=s.replace("check('11 records, 61 measurements, 47 operations',len(records)==11 and sum(len(r['measurements']) for r in records.values())==61 and sum(len(r['operations']) for r in records.values())==47)","check('8 records, 145 measurements, 36 operations',len(records)==8 and sum(len(r['measurements']) for r in records.values())==145 and sum(len(r['operations']) for r in records.values())==36)")
s=s.replace("check('Two routes, seven procedures and two observations',Counter(r['record_type'] for r in records.values())==Counter(literature_protocol=2,procedure=7,observation=2))","check('One route, four procedures, two controls and one observation',Counter(r['record_type'] for r in records.values())==Counter(literature_protocol=1,procedure=4,protocol_variant=2,observation=1))")
s=s.replace('all 11 records','all 8 records').replace('All 11 records','All 8 records')
s=s.replace("elif rid.endswith('cadmium-loading'):labels=['cadmium-loading'] if m['id']=='loading-fraction' else ['loading-test']\n            elif rid.endswith('other-electrolytes'):labels=['alternative-salts']", "elif rid.endswith('open-circuit-control'):labels=['open-circuit-control']\n            elif rid.endswith('silver-free-pulse-control'):labels=['silver-free-control']")
s=s.replace("expected_sample='a-and-b-context' if isinstance(old['sample_id'],list) else old['sample_id']","expected_sample='shared-'+'-and-'.join(old['sample_id']) if isinstance(old['sample_id'],list) else old['sample_id']")
start=s.index('        if rid in routeids:\n')
end=s.index("    check('53 unique characterization",start)
s=s[:start]+'''        if rid in routeids:
            check(rid+' semiconductor substrate retained',r['schema_version']=='1.2.0' and r['material']['formula']=='Ag/Si' and 'Sb-doped' in r['intended_target']['host']['value'])
            check(rid+' no invented desired size or phase',r['intended_target']['size']['value'] is None and r['intended_target']['phase']['value'] is None)
            for task in wanted:
                v=training_view(r,task)
                check(rid+'/'+task+' requested host retained',v['input'].get('requested_host')==r['intended_target']['host'])
                check(rid+'/'+task+' measurements absent from task input','measurements' not in v['input'] and 'products' not in v['input'])
''' +s[end:]
s=s.replace("check('53 unique characterization rows and 8 other observations',len(records[P+'characterization']['measurements'])==53 and len(joins)==61)","check('143 characterization rows plus two control observations',len(records[P+'characterization']['measurements'])==143 and len(joins)==145)")
s=s.replace("All 54 source characterization facts","All 143 source characterization facts")
s=s.replace("check('100 reader items and 144 source-audit crosswalk units',len(items)==100 and len(coverage['source_audit_unit_map'])==144)","check('144 reader items and 202 source-audit crosswalk units',len(items)==144 and len(coverage['source_audit_unit_map'])==202)")
s=s.replace("u['source_audit_id']","u['source_unit_id']").replace("u['source_audit_pointer']","u['source_audit_json_pointer']").replace("u['public_targets']","u['reader_json_pointers']")
s='\n'.join(l for l in s.splitlines() if "coverage['reader_units']" not in l)
start=s.index('    for key,need in ')
end=s.index("    check('Main-only review scope",start)
s=s[:start]+'''    for key,need in {'source-specific-electrolytes':['1 mM','10 mM','1.5 mM'],'transferred-particles':['10–25 Å','pulse duration is not stated'],'saed-indexing':['actual electron-diffraction','reference relative intensities'],'density-time-series':['cm⁻² ms⁻¹','error-bar meaning'],'summary-scope':['cm⁻² s⁻¹','conflicts'],'early-current-models':['undefined A','starred concentration','no visible F'],'histogram-1':['2.2 nm','2.4 nm','5 ms'],'conflict-14':['four panels','fifth']}.items():check(key+' critical semantic boundaries',all(v in items[key]['text'] for v in need))
    check('All 44 source references and direct note 43',len(ledger['referenced_methods'])==44 and [r['reference_number'] for r in ledger['referenced_methods'] if r['direct_source_note_reviewed']]==[43])
''' + s[end:]
s=s.replace("check('16 originals: 9 figures, 3 equations, 4 context assets',len(assets)==16 and [len(ledger[k]) for k in ['figures','equations','source_notes','tables']]==[9,3,4,0])", "check('15 originals: 9 figures, 3 equations, one SAED detail, table and scheme',len(assets)==15 and [len(ledger[k]) for k in ['figures','equations','source_notes','tables','schemes']]==[9,3,1,1,1])")
s=s.replace("runtime['reader_items']==100 and runtime['unique_original_assets']==16","runtime['reader_items']==144 and runtime['unique_original_assets']==15")
s=s.replace("for formula in ['CdS/polymer','CdS']:","for formula in ['Ag/Si','Ag','Si']:")
s=s.replace("exactly two active-paper routes","exactly one active-paper route")
s=s.replace("(formula=='CdS/polymer')","(formula=='Ag/Si')")
s=s.replace("check(formula+' Cd and S periodic lookup elements retained',{'Cd','S'}<=set(meta.get('elements',hub.get('elements',[]))))", "check(formula+' periodic lookup element identity retained',set(formula.split('/'))<=set(meta.get('elements',hub.get('elements',[]))))")
s='\n'.join(l for l in s.splitlines() if "if formula=='CdS':" not in l)
(OUT/'audit_canonical_to_reader.py').write_text(s+'\n',encoding='utf-8')
