"""Record actual root browser checks; not a substitute for source/code audits."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
N=Path(__file__).resolve().parent;S=N.parents[4]/'recipe-atlas';O=N/'site-integration-proposal'
read=lambda p:json.loads(p.read_text(encoding='utf8'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
records={p.stem:read(p) for p in (O/'v1/records').glob('*.json')}
rows={'monolayer-shell':[9,9,9,6,3,6,3,4],'precursor-preparation':[10,4,8],'precursor-crystallization':[4,4],'decomposition-nmr':[12,5],'decomposition-thf':[8,6],'decomposition-dmso-hot':[7],'excess-precursor-rt':[5,4],'excess-precursor-hot':[6,3],'added-base-comparison':[6],'single-crystal-acquisition':[14]}
for suffix,counts in rows.items():assert len(counts)==len(records['morrison-2017-'+suffix]['operations'])
assert sum(map(len,rows.values()))==24 and sum(sum(v) for v in rows.values())==155
result={'schema':'mattersyn.actual_integrated_browser_validation/1','at':datetime.now(timezone.utc).isoformat(),'reviewer':'/root','status':'passed','mechanism':'Actual existing in-app browser tab via CUA; local preview127.0.0.1:5193; not inferred from static checks.','pages_and_controls':{'ten_procedure_pages':rows,'all24buttons_clicked':True,'operation_svg_and_adjacent_conditions_verified':True,'one_locator_refresh':'One locator became stale during hydration on the room-temperature page. Fresh DOM/visible source-specific SVG and exact stage labels resolved it; all remaining stages tested.','monolayer_scene_screenshot':'66°C,2mL10mMTHFprecursor,3hidealtime,estimated1–1.5monolayermultiplier; apparatus not invented.','molecular_viewer':'THF solvent selected from stock; dialog opened; plus/reset/functional-group toggle and actual mouse drag rotation checked visually.','product_context':'Switched to monolayer optical aliquots; phase remains not reported, separate from route-family phase.','figure_filter':'15of26 related source figures/tables by default;26of26all; restored selected context.','original_figure':'Figure9HRTEM opened, scale bars/panels visually inspected, zoom/reset/close checked.','cdse_hub':'Both excess-precursor and controlled-monolayer method cards present with equal source-card format.','source_reader':'Morrison title,27pagecoverage,19figures,8tables and source scope loaded successfully.','responsive':'390x844 tested; long source-hash provenance initially caused517pxdocumentwidth. Added bounded wrapping CSS; after reload375pxdocumentwidth<=390pxviewport. Normal viewport restored.','runtime_errors':[]},'bound_files':{p.relative_to(S).as_posix():sha(p) for p in [S/'dist/protocol-visuals.mjs',S/'dist/morrison2017-protocol.mjs',S/'dist/illustrated-guide.css',S/'dist/assets/chemical-registry/registry.json',S/'dist/assets/chemical-registry/bindings.json',S/'dist/assets/chemical-registry/product-contexts.json',S/'dist/assets/chemical-registry/solution-components.json',S/'dist/data/paper-reviews/morrison2017.json',S/'dist/data/dataset-manifest.json']},'pending':'Separate integrated code audit and anonymous deployment verification; this report does not assert publication.'}
(O/'browser-validation.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(json.dumps({'status':'passed','stages':24,'condition_rows':155,'browser_sha256':sha(O/'browser-validation.json')}))
