"""Private evidence-linked Dabbousi1997 reader proposal; never writes Site/source/queue."""
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,re
from source_unit_map import build as build_source_map
from finalize_editorial import finalize
OUT=Path(__file__).resolve().parent;B=OUT.parent
SID='dabbousi1997';DOI='10.1021/jp971091y'
KEYS=['zns-overgrowth','cds-overgrowth','cdse-seed-preparation','optical-characterization','wds-preparation','xps-preparation','tem-preparation','saxs-pvb-film','saxs-diblock-film','saxs-solution','waxs-film','air-exposure','core-size-optical-series','coverage-series','air-exposure-observations','solution-saxs-series','cds-optical-comparison']
RECORDS={k:'dabbousi-1997-'+k for k in KEYS}
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def loc(p,s):return f'Main PDF p. {p}, printed p. {9462+p}, {s}'
def ev(p,s):return {'source_id':SID,'document_role':'main','pdf_page':p,'printed_page':9462+p,'locator':loc(p,s)}
def prose(s):
    s=re.sub(r'([,;])(?=[A-Za-z])',r'\1 ',s)
    s=re.sub(r'\b(Figure|Figures|Table|Note|note|reference|Reference|Equation|equation)(?=\d)',r'\1 ',s)
    s=re.sub(r'\b(at|of|is|are|from|to|with|in|uses|gives|has|bare|coated|parameter|ratios|ratio|only|beyond|about|approximately|all|All|sample|time|after|by|than|before)(?=\d)',r'\1 ',s)
    s=re.sub(r'(?<=\d)(?=°C|ML\b|Å\b)', ' ',s)
    s=re.sub(r'(?<=[a-z])(?=\()', ' ',s)
    return s
SECTIONS={k:{'id':k,'title':t,'items':[]} for k,t in [('precursors','Precursors'),('protocol','Synthesis protocol'),('structures','Final structures'),('properties','Properties'),('intuition','Chemical intuition'),('sources','Sources and limitations')]}
COHORTS={
 'seed-family':('cdse-seed-preparation','Reported 23–55 Å seed family; not six independently specified syntheses.'),
 'zns-method':('zns-overgrowth','General ZnS method with note22 core-diameter/temperature pairs; exact precursor quantities vary and are absent.'),
 'cds-method':('cds-overgrowth','CdS branch:33.5–35 Å core diameters in Methods; later comparison-size descriptions conflict.'),
 'core-size-spectra':('core-size-optical-series','Figures1–2 four optical samples:23,42,48,55 Å core diameters; not an assignment to six note22 temperatures.'),
 'photograph-six':('core-size-optical-series','Figure3 six photographed dispersions; peak wavelengths known but exact diameter-to-cuvette assignment absent.'),
 'coverage-main':('coverage-series','Fractions of one nominal~40 Å seed preparation; captions42±10% Å; Table1 bare39±8.2% Å TEM versus42±10% Å SAXS. Five TEM-defined coverages.'),
 'xps-series':('coverage-series','XPS involves approximately 33 and 40 Å cores; Figure6 specifically compares approximately 40 Å bare/1.3ML. Contextual XPS products are separate from Table1 even when nominal coverage matches.'),
 'air-time-series':('air-exposure-observations','The source describes the bare16h/80h results as the same specimen at successive states. Its identity with the general initial XPS baseline is unverified. That baseline repeats the coverage-record XPS context and is not an independent replicate.'),
 'tem-particles':('coverage-series','Fig8 representative particles and Fig9 population histograms; >150 size measurements per sample; aspect ratios use a subset.'),
 'polymer-saxs':('coverage-series','Fig10/Table1 main coverage cohort in polymer films; exact PVB versus diblock assignment for each trace not stated.'),
 'solution-saxs':('solution-saxs-series','Figures11–12 independent hexane-dispersion series explicitly not comparable to Table1; Zn/Cd0.42,0.85,3.1,and5.3/5.6 conflicting.'),
 'waxs-main':('coverage-series','Fig13 main coverage series with ellipsoidal structural fits; model coordinates are not measured atom positions.'),
 'electronic-model':('coverage-series','Figures14–15: finite-barrier model and experimental ZnS optical shifts; Fig14 diameter/radius inconsistency retained.'),
 'cds-comparison':('cds-optical-comparison','Fig16 CdS optical shifts; Methods and results/caption sizes conflict. No same-specimen link imposed.'),
 'pvb-preparation':('saxs-pvb-film','PVB/toluene film method; characterization specimen, not another shell synthesis.'),
 'diblock-preparation':('saxs-diblock-film','Phosphine-functionalized MTD300P20/THF branch, same basic film preparation.'),
 'wds-preparation':('wds-preparation','Carbon-coated pyridine-cast Si(100) film for bulk composition.'),
 'xps-preparation':('xps-preparation','Pyridine-exchanged thin film spin-cast on Si for surface-sensitive measurement.'),
 'tem-preparation':('tem-preparation','Octane drop on carbon-supported copper grid,wick30s,extra carbon protection.'),
 'waxs-preparation':('waxs-film','Pyridine-exchanged glassy particle film on silicon,distinct from polymer-SAXS specimen.')}
def item(sec,key,title,text,page,where,records=(),cohorts=(),kind='reported_source_fact',notes=(),extra=(),facts=()):
    e=[ev(page,where)]+[ev(p,w) for p,w in extra]
    d={'id':key,'title':prose(title),'text':prose(text),'claim_type':kind,'sample_scope':{'cohort_keys':list(cohorts),'state':prose(title),'physical_batch_id':None,'link_limit':'Source-defined cohort only; shared size/formula/technique does not prove identical batch, aliquot or specimen.'},'evidence':e,'source_locators':[x['locator'] for x in e],'canonical_links':[{'record_id':RECORDS[r],'json_pointer':'','relation':'Proposed source-context link pending independent canonical audit.'} for r in records],'notes':list(notes),'facts':list(facts),'training_eligible':False}
    SECTIONS[sec]['items'].append(d);return d
def content():
    item('precursors','received-chemicals','Organometallics and coordinating solvents','TOPO is90% pure from Strem; TOP is95% pure from Fluka. Dimethylcadmium comes from Alfa and diethylzinc from Fluka; each is filtered separately through0.2 µm inside an inert-atmosphere box. Hexamethyldisilathiane,also written bis(trimethylsilyl)sulfide or (TMS)2S,is used as purchased from Aldrich. These supplier/grade statements belong to this paper and are not replaced by those in an earlier recipe.',2,'Materials',records=('zns-overgrowth','cds-overgrowth','cdse-seed-preparation'))
    item('precursors','topse-stock','TOPSe stock solution','Dissolve0.1 mol selenium shot in100 mL TOP; the source calls the resulting stock1 M TOPSe. This is a selenium-in-TOP stock preparation,not free Se added alone to the shell-growth flask. Dissolution temperature,time,endpoint,storage atmosphere and storage duration are not specified.',2,'Materials',records=('cdse-seed-preparation',),cohorts=('seed-family',),facts=({'label':'Se shot','value':0.1,'unit':'mol'},{'label':'TOP solvent','value':100,'unit':'mL'},{'label':'Reported TOPSe stock','value':1,'unit':'M'}))
    item('precursors','solvents-and-standards','Workup solvents and optical standards','HPLC-grade n-hexane,methanol,pyridine and1-butanol are from EM Sciences. Product redispersion also mentions chloroform,toluene and THF; octane is used for TEM preparation. Rhodamine590 or rhodamine640 is the optical-yield standard at matched excitation optical density. Neither a particular dye counterion nor its preparation,reference yield or purity is provided. Avoid assigning solvents or standards to steps where they are not reported.',2,'Materials,workup and characterization',records=('zns-overgrowth','cds-overgrowth','optical-characterization','tem-preparation'))
    item('precursors','zns-charge','ZnS reaction medium and seed loading','The flask contains5 g TOPO,then0.5 mL TOP after cooling to60°C. Approximately0.1–0.4 µmol of CdSe dots in hexane is transferred by syringe; the solvent is pumped off. The amount is particle moles,not a reported amount of CdSe formula units. Seed-dispersion volume and particle number calibration are not supplied.',2,'Synthesis,(CdSe)ZnS',records=('zns-overgrowth',),cohorts=('zns-method',))
    item('precursors','zns-feed-design','Shell-precursor stock and dose calculation','Equimolar diethylzinc and (TMS)2S are dissolved in2–4 mL TOP inside an inert glovebox. The chosen shell dose is calculated from TEM/SAXS core radius,spherical core/shell volumes and bulk lattice parameters; a larger core needs a smaller Zn/Cd ratio for equal shell thickness. Absolute stock molarity and per-sample doses are not printed. Actual growth is generally less than the nominal addition because reaction is incomplete and some material remains on the flask walls.',2,'Synthesis,(CdSe)ZnS',records=('zns-overgrowth',),cohorts=('zns-method',),kind='reported_protocol_and_author_dose_model')
    item('precursors','cds-feed','CdS substitution branch','CdS overgrowth replaces the Zn precursor with dimethylcadmium and retains (TMS)2S. The paper invokes the same basic procedure but specifically reports180°C and approximately1 mL/min delivery. It gives no independent absolute Cd/S loading,total feed volume or duration for this branch; do not replace them with the ZnS5–10 min addition window.',2,'Synthesis,(CdSe)CdS',records=('cds-overgrowth',),cohorts=('cds-method',))
    item('precursors','characterization-materials','Characterization matrices and supports','Poly(vinyl butyral),PVB,and phosphine-functionalized diblock [methyltetracyclododecene]300-[norbornene-CH2O(CH2)5P(oct)2]20,MTD300P20,are separate SAXS matrices. The diblock is cited to reference23; its synthesis is not restated. Other supports are Si(100) for WDS,silicon for XPS/WAXS/polymer films,carbon-coated copper grids for TEM and quartz capillaries for solution SAXS. Nitrogen is the stated shell-growth atmosphere; inert-box gas and purge pressure are unreported.',2,'Materials and characterization specimen preparation',records=('saxs-pvb-film','saxs-diblock-film','wds-preparation','xps-preparation','tem-preparation','saxs-solution','waxs-film'),extra=((3,'SAXS/WAXS continuation'),))
    item('protocol','core-preparation','CdSe seed preparation','The authors cite Murray1993(reference3) for organometallic core synthesis. They report injection of dimethylcadmium/TOPSe into TOPO at340–360°C,then growth of initially23 Å diameter particles at290–300°C to obtain23–55 Å seeds. Methanol size-selective precipitation gives powders,redispersed in hexane. Precursor amounts,injection volume,core-growth time,centrifugation and exact fractionation procedure remain absent here; keep the upstream reference partial.',2,'Synthesis,(CdSe)ZnS',records=('cdse-seed-preparation',),cohorts=('seed-family',))
    item('protocol','medium-degas','TOPO conditioning and seed transfer','Heat5 g TOPO to190°C under vacuum for several hours,then cool to60°C and add0.5 mL TOP. Add the approximately0.1–0.4 µmol CdSe-dot hexane dispersion by syringe and pump off the solvent. The source does not state the vacuum value or confirm a separate temperature/time during solvent removal. Do not inherit190°C into the60°C transfer stage.',2,'Synthesis,(CdSe)ZnS',records=('zns-overgrowth',),cohorts=('zns-method',))
    item('protocol','zns-delivery','Dropwise ZnS precursor addition','Load the glovebox-prepared equimolar Zn/S stock into a syringe,then transfer it to an addition funnel attached to the reaction flask. Heat the TOPO/TOP seed dispersion under N2 to its selected growth temperature. Add the feed dropwise over5–10 min with vigorous stirring. This is an addition funnel description,not an explicitly specified syringe-pump flow rate. Stirring speed,pressure and quantitative delivery profile are absent.',2,'Synthesis,(CdSe)ZnS',records=('zns-overgrowth',),cohorts=('zns-method',))
    item('protocol','size-temperature-pairs','Core-size-specific shell-growth temperatures','Source note22 explicitly pairs seed diameter and addition temperature:23 Å→140°C;30 Å→140°C;35 Å→160°C;40 Å→180°C;48 Å→200°C;55 Å→220°C. These are six reported settings within one general method,not six fully documented batches or an interpolating temperature law. The42 Å optical/table cohort is not explicitly assigned a seventh temperature or silently relabelled40 Å.',13,'Reference and Note22',records=('zns-overgrowth',),cohorts=('zns-method',),extra=((2,'Synthesis,(CdSe)ZnS'),),facts=tuple({'label':f'{d} Å core diameter','value':t,'unit':'°C','status':'reported paired method setting'} for d,t in [(23,140),(30,140),(35,160),(40,180),(48,200),(55,220)]))
    item('protocol','aging-storage','Post-addition stirring and storage','After ZnS addition,cool to90°C and stir for several hours. Add5 mL butanol to prevent TOPO solidifying on cooling to room temperature. Store particles in their growth solution to maintain TOPO surface passivation. Later methanol precipitation recovers powder for redispersion in hexane,chloroform,toluene,THF or pyridine. Storage duration and exact storage temperature are not separately specified; no invented freezer condition is assigned.',2,'Synthesis,(CdSe)ZnS',records=('zns-overgrowth',),cohorts=('zns-method',))
    item('protocol','selective-purification','Final size-selective purification','Slow dilute addition favors growth on CdSe over separate ZnS nucleation but is not claimed to eliminate all small ZnS particles. The authors therefore perform a final size-selective precipitation to favor core/shell particles in the recovered powder. Repeated fractionation can irreversibly flocculate thick-shell particles; no cycle count,centrifuge setting,recovery or quantitative selectivity is supplied.',3,'ResultsIIIA',records=('zns-overgrowth',),cohorts=('zns-method',),extra=((7,'SAXS/polymer aggregation discussion'),),kind='reported_protocol_and_author_rationale')
    item('protocol','cds-addition-storage','CdS overgrowth and storage distinction','For33.5–35 Å diameter CdSe seeds,the Cd/S solution is dripped into the reaction at180°C and approximately1 mL/min. The mixture darkens and its absorption red-shifts during addition. Storage requires equal amounts of hexane and butanol because butanol alone appeared to flocculate these particles. Equal amounts have no explicit mass/volume basis or individual quantity in the source; the ZnS5 mL butanol step is not automatically a CdS volume.',2,'Synthesis,(CdSe)CdS',records=('cds-overgrowth',),cohorts=('cds-method',),notes=('Later Fig16/model size descriptions conflict; keep those experimental/model contexts separate from this method.',))
    item('protocol','coverage-design','Matched-seed coverage series','A large approximately40 Å diameter CdSe preparation is divided into fractions. Varying amounts of Zn/S precursors are added at identical temperatures and addition times,to vary shell coverage while preserving a common seed source. The five comparisons are bare,0.65,1.3,2.6 and5.3 monolayers. Figure captions describe42±10% Å seeds; Table1 distinguishes TEM and SAXS sizes. No exact aliquot masses,doses or per-fraction times are printed.',4,'Optical coverage-series design and Figure4',records=('coverage-series','zns-overgrowth'),cohorts=('coverage-main',))
    item('structures','wds-method','WDS composition measurement','JEOL SEM733 electron microprobe at15 kV measures elemental composition by WDS. Approximately1 µm particle films are cast from concentrated pyridine dispersion on Si(100); solvent evaporates completely before a thin amorphous-carbon coating suppresses charging. The stated elemental-analysis uncertainty is less than±5%. Concentration,cast volume,carbon thickness and calibration details are absent.',2,'Wavelength Dispersive X-ray Spectroscopy',records=('wds-preparation','coverage-series'),cohorts=('wds-preparation','coverage-main'),extra=((5,'WDS results'),))
    item('structures','table1-structure','Table1: measured sizes and model-derived quantities','Table1 compares the five main coverage levels. TEM major-axis sizes are39±8.2%,43±11%,47±10%,55±13% and72±19% Å; mean aspect ratios are1.12,1.16,1.16,1.23 and1.23. Polymer-SAXS fits yield42±10%,46±13%,50±18% Å only for bare,0.65ML and1.3ML. WDS Zn/Cd values are0.46,1.50,3.60,6.80; SAXS-derived ratios0.58,1.32 only at0.65/1.3ML; WAXS-fit ratios0.7,1.4,2.9,6.8. Blank cells stay missing,not zero. Percent spreads are not absolute Å errors.',5,'Table1',records=('coverage-series',),cohorts=('coverage-main','tem-particles','polymer-saxs','waxs-main'),notes=('TEM dimensions,model-fit SAXS sizes and composition measurements have different evidential roles even in one summary table.','A TEM major-axis length is not an isotropic spherical diameter.'))
    item('structures','monolayer-definition','Definition of shell monolayers','The source defines one ZnS monolayer as3.1 Å along the major axis of the prolate particle,using consecutive[002]planes in bulk wurtzite ZnS. It uses TEM dimensions throughout to describe shell thickness in monolayers. This is a geometry-based coverage definition; it does not establish an atomically uniform integer shell or directly measured local interface.',3,'ResultsIIIB,definition of monolayer',records=('coverage-series','zns-overgrowth'),cohorts=('coverage-main',),extra=((7,'TEM interpretation'),))
    item('structures','xps-method','XPS acquisition and specimen scope','Pyridine-exchanged particles are spin-cast on Si as films several monolayers thick. Physical Electronics5200C with dual Mg/Al anode and concentric hemispherical analyzer uses Mg Kα1253.6 eV at300 W(15 keV,20 mA). Survey0–1100 eV uses179 eV pass energy and2 eV resolution; close-ups use71.5 eV pass energy and1 eV resolution. Base pressure is10^-8 Torr. These are measurement settings,not shell-growth pressure.',2,'X-ray Photoelectron Spectroscopy',records=('xps-preparation','coverage-series'),cohorts=('xps-preparation','xps-series'))
    item('structures','xps-composition','Elemental ratios and chemical-state evidence','WDS finds bare-dot Se/Cd approximately0.8–0.9. Corrected XPS gives about0.87,or46%Se/54%Cd. Figure6 compares~40 Å bare and~1.3ML dots; the wider XPS study also includes~33 Å cores. Carbon/oxygen features are attributed mainly to brief air exposure,typically15 min; residual phosphorus after pyridine exchange indicates some TOP/TOPO remains. Sensitivity correction integrates escape attenuation over the nanoscale sphere; it is not simple bulk peak-area counting.',5,'WDS/XPS results and Figure6',records=('coverage-series','xps-preparation'),cohorts=('coverage-main','xps-series'),kind='reported_measurement_and_author_analysis')
    item('structures','auger-parameters','Auger parameters and shell-location inference','Cd Auger parameter466.8±0.2 eV in bare and coated particles is consistent with bulk CdSe. Zn is757.5 eV at1.3/2.6ML,compared with758.0 eV expected for ZnS. A ratio of XPS/Auger Cd intensity ratios between coated and bare samples removes flux/number/cross-section factors in the authors’ model. Calculated ratios1.28 at0.65ML and1.60 at2.6ML support surface growth. These calculations are not local atomic coordinates or a direct shell-thickness measurement.',6,'XPS analysis and equation1',records=('coverage-series',),cohorts=('xps-series',),kind='reported_measurement_and_author_model')
    item('structures','escape-depths','Photoelectron escape-depth reference values','Note26 gives CdSe escape depths15 Å(Cd3d),10 Å(Cd Auger),21 Å(Se3d). In ZnS the values are23.7 Å(Cd3d),13.2 Å(Cd Auger),31.2 Å(Se3d),9.6 Å(Zn2p),26.8 Å(Zn Auger),28.9 Å(S2p). Equation1 weights signal by exp[-z/λ(KE)] alongside flux,atomic population,cross section,emission yield and instrument response. These are analysis constants,not measured dimensions of the product.',13,'Note26',records=('xps-preparation',),kind='source_model_parameter',extra=((6,'Equation1 and depth analysis'),))
    item('structures','xps-intensity-model','Normalized XPS/Auger intensity model','The source defines i = I_XPS(Cd)/I_Auger(Cd),then I = i_overcoated(Cd)/i_bare(Cd). Because Auger electrons have shorter escape depths,a shell attenuates the signals differently and the normalized ratio rises. The result cancels X-ray flux,number of atoms and absorption cross section in the stated model. It is not an elemental Zn/Cd ratio. The paper describes its Auger parameter as a binding-energy difference; retain that source convention and its quoted values.',6,'XPS analysis,equation1 and unnumbered intensity ratio',records=('coverage-series',),cohorts=('xps-series',),kind='author_analysis_model')
    item('structures','xps-finite-size-correction','Finite-size sensitivity correction','The paper corrects elemental sensitivity factors by the attenuation integral ∫_0^d exp(−z/λ) dz and evaluates the geometry over a sphere because electron escape depth is comparable to particle dimensions. This is an analysis assumption,not evidence that every particle is a perfect sphere. Carbon/oxygen energies match standard adsorbate values and are taken to indicate no significant charging. Exact integration implementation and independently validated sensitivity constants are not provided.',5,'XPS analysis',records=('coverage-series','xps-preparation'),cohorts=('xps-series',),kind='author_analysis_model_and_reported_interpretation')
    item('structures','tem-method','HRTEM preparation and acquisition','Topcon EM002B at200 kV images individual particles. An objective aperture selects(100),(002),(101)wurtzite planes. Place one drop of dilute octane dispersion on a copper grid with thin amorphous-carbon support; wick solvent after30 s. Evaporate a second carbon layer to reduce charging/beam damage. The source does not supply grid mesh,drop volume,carbon thickness or dose history.',2,'Transmission Electron Microscopy',records=('tem-preparation','coverage-series'),cohorts=('tem-preparation','tem-particles'))
    item('structures','tem-interface','Resolved fringes and unresolved interface','Figure8 contrasts a bare particle and a2.6ML particle,retaining a50 Å scale bar. Fringes run across the coated particle and suggest epitaxial growth,while a well-defined core/shell interface is not resolved. One pictured bend may indicate strain,but most fringes are straight. High coverage produces some patchy,misshapen particles; separate tethered ZnS nuclei were not observed. More than150 particles per sample underpin major-axis distributions; aspect ratios use a subset.',6,'TEM discussion and Figure8',records=('coverage-series',),cohorts=('tem-particles','coverage-main'),extra=((7,'Figure9'),),kind='reported_images_and_author_interpretation')
    item('structures','tem-histograms','Size and shape distributions','Figure9 shows separate major-axis and aspect-ratio histograms for bare,0.65,1.3,2.6,5.3ML samples. Average length and polydispersity rise with coverage,and aspect-ratio distributions broaden. The measured table means reach1.23 at high coverage; model distributions weighted toward1.3–1.4 are not interchangeable with those measured means. Histogram curves are retained without digitizing individual particle counts.',7,'Figure9 and TEM continuation',records=('coverage-series',),cohorts=('tem-particles','coverage-main'))
    item('structures','polymer-film-preparation','Polymer SAXS specimen preparation','Disperse approximately5 mg nanocrystals in1 mL toluene and combine with0.5 mL of10 wt% PVB in toluene. Concentrate under vacuum to a viscous solution and cast on silicon. MTD300P20 uses the same basic procedure with THF for both polymer and particles. Films are approximately200 µm thick,clear to slightly opaque. This film thickness is a characterization support dimension,not shell thickness or a production yield.',2,'SAXS in polymer films',records=('saxs-pvb-film','saxs-diblock-film'),cohorts=('pvb-preparation','diblock-preparation','polymer-saxs'),extra=((3,'SAXS method continuation'),))
    item('structures','polymer-saxs-acquisition','Polymer SAXS instrument and corrections','Rigaku300 Rotaflex operates in Bragg configuration with Cu Kα,60 kV and300 mA. Scatter/diffraction slits are1/6° and the collection slit0.3 mm. Polymer background is subtracted; low-angle data are corrected for beam width exceeding the generally2 cm specimen. Aggregation makes the region below approximately2.5° unreliable for fits; a shoulder below2° supports this interpretation. The phosphine diblock is only slightly more effective than PVB,and inert casting does not solve the separation problem.',3,'SAXS instrument',records=('saxs-pvb-film','saxs-diblock-film','coverage-series'),cohorts=('polymer-saxs',),extra=((7,'SAXS analysis and aggregation'),(8,'SAXS continuation')),kind='reported_method_and_author_interpretation')
    item('structures','debye-saxs-model','Debye model of particle scattering','Equation2 sums pair distances with angle-dependent scattering factors. Wurtzite atoms are generated inside core and shell ellipsoids; TEM dictates shape distributions,while shell size/spread vary and core size/spread remain fixed. The example20 Å radius aspect-ratio distribution1.1/1.2/1.3/1.4 has24/36/24/16% weights and changes calculated Zn/Cd markedly despite similar scattering shapes. Fits are credible only for bare,0.65ML,1.3ML;2.6/5.3ML patterns lack sufficient structure. Model atom positions are illustrative/calculated,not refined experimental coordinates.',7,'SAXS analysis,equation2',records=('coverage-series',),cohorts=('polymer-saxs',),kind='author_structural_model',extra=((8,'Figure10'),))
    item('structures','solution-saxs-method','Solution SAXS acquisition','A rotating Cu anode operates at40 kV/25 mA with apparent source area~10^-2 mm². A slit forms a3×0.3 mm² beam on a50 mm useful-length PSPE(ELPHYSE)linear detector with200 µm spatial resolution. The paper prints D=370 mm “from the detector,”a self-referential geometry description retained as unresolved. Accessible q is0.006–0.40 Å^-1 with~0.003 Å^-1 resolution. Quartz capillaries have~1 mm optical path and are flame-sealed. Measure reference before sample; analyze Is−Iref.',3,'Small-angle X-ray scattering in dilute solutions',records=('saxs-solution',),cohorts=('solution-saxs',))
    item('structures','solution-saxs-cohort','Independent solution-SAXS cohort','Figures11–12 concern bare and ZnS-coated particles in hexane at comparable particle number concentration. The authors explicitly exclude direct comparison with Table1 because compositions differ. Labels are bare,0.42,0.85,3.1 and5.3 Zn/Cd in Figure11 and p9; p8 instead says5.6 for the highest member. Preserve both source reports without merging this series with0/0.65/1.3/2.6/5.3ML coverage or assigning a synthesized amount from Zn/Cd.',8,'Figure11 and solution-SAXS discussion',records=('solution-saxs-series',),cohorts=('solution-saxs',),extra=((9,'Solution-SAXS continuation and Figure12'),))
    item('structures','solution-saxs-fitting','Guinier,Porod and size-estimation limits','Equation3 gives I(0) proportional to N R^6 under stated contrast assumptions. The paper uses Guinier ln(I) versus q² and Porod q^4I versus q,with Gaussian/log-normal size distributions. Bare-particle fitting yields R0≈19.50 Å,σ≈0.12 in prose; Figure12 reports fitted σ0.11/0.14/0.16/0.25 for a–d. Prose says high-coverage mean size/spread cannot be meaningfully fitted,so it estimates the upper distribution rather than a mean from low-q intensity. Do not publish those high-coverage estimates as ordinary mean particle size.',8,'Solution-SAXS model,equation3',records=('solution-saxs-series',),cohorts=('solution-saxs',),extra=((9,'Figure12 and fit limitations'),),kind='author_analysis_with_source_conflicts')
    item('structures','solution-saxs-density','Electron-density approximation','The solution analysis treats CdSe and thin ZnS shell as one density despite printed values2.92 and2.35 electrons/Å³,respectively. The authors estimate10–15% error in inferred sizes. Radius ratios use the sixth root of relative zero-angle intensities at comparable particle number. Larger-shell estimates concern an upper size bound and are not numbers recovered from the plots. Long-term colloidal stability motivates polydispersity rather than aggregation as the preferred explanation,but does not prove interactions absent.',9,'Solution-SAXS size/contrast discussion',records=('solution-saxs-series',),cohorts=('solution-saxs',),kind='author_model_assumption_and_limit')
    item('structures','waxs-preparation','WAXS film preparation','Precipitate TOP/TOPO-capped dots with methanol and exchange with pyridine. Drop concentrated pyridine dispersion on silicon and evaporate slowly to form glassy films. Wide-angle patterns use the same setup as polymer SAXS. Concentration,drop volume,exchange cycles and evaporation time are not supplied. This specimen is not a PVB or diblock-polymer film.',3,'Wide-Angle X-ray Scattering',records=('waxs-film',),cohorts=('waxs-preparation','waxs-main'))
    item('structures','waxs-observations','WAXS and reference patterns','Figure13 compares measured patterns with simulations and bulk wurtzite CdSe/ZnS reference lines. The initial broad feature combines(100),(002),(101); reduced(102)/(103)intensities are attributed to stacking faults. Shell coverage broadens/shifts the~26° feature,weakens~36°,alters peaks near47° and introduces~56° at high coverage. Figure axis is2θ,while simulation prose prints15°<θ<60°; preserve the axis convention discrepancy. No SAED image or measured CIF is supplied.',9,'Figure13',records=('coverage-series',),cohorts=('waxs-main',),extra=((10,'WAXS analysis'),),kind='reported_patterns_and_author_interpretation')
    item('structures','waxs-model','WAXS simulation and structural limits','The bare-core fit uses~1200 atoms,aspect ratio1.1 and mean1.4 stacking faults per crystallite,kept fixed through later simulations; later prose uses1.15 for core aspect ratio. Heavy-shell fits require bulk aCdSe=4.29 Å and aZnS=3.82 Å; thin-shell patterns scarcely constrain aZnS. Shell shape weights span1.2–1.4 and the highest coverage uses~3 stacking faults. Fitted Zn/Cd0.7/1.4/2.9/6.8 approximates WDS. These are fit parameters,not exact atomic structures.',10,'WAXS simulations',records=('coverage-series',),cohorts=('waxs-main',),kind='author_structural_model')
    item('structures','interface-model-limits','Interface orientation and cross terms','Rotating the shell to align ZnS(100)with CdSe(101)does not substantially improve the high-coverage WAXS fit. Simulations with and without CdSe/ZnS interphase cross terms differ less than changes in composition,aspect ratio or stacking-fault density. TEM lacks resolution to distinguish core/shell fringe spacings,and WAXS is insensitive to shell orientation. A crystalline,locally epitaxial shell is supported; precise interface coordinates or a unique dislocation topology are not.',10,'WAXS interface simulations',records=('coverage-series',),cohorts=('waxs-main','tem-particles'),extra=((12,'Structural interpretation'),),kind='author_model_sensitivity_and_limit')
    item('properties','optical-method','Optical acquisition and quantum yields','HP8452 diode-array absorption and SPEX Fluorolog-2 front-face PL measurements use dilute hexane dispersions in1 cm quartz cuvettes. Room-temperature yield compares integrated dot emission with rhodamine590 or640 solutions of identical optical density at excitation. Excitation wavelength is not specified for every plotted spectrum;450 nm is expressly stated for Figure15PL comparison and365 nm only for the photograph. Do not transfer those settings to every yield measurement.',2,'Optical Characterization',records=('optical-characterization',),extra=((4,'Photograph description'),(11,'Figure15discussion')))
    item('properties','core-size-optics','Size-series absorption and emission','Figures1–2 compare bare and1–2ML coated CdSe cores23,42,48,55 Å. Figure2 gives coated yields40%,50%,35%,30% for a–d. Across the study bare dots give5–15% and coated30–50%,with room-temperature emission across~470–625 nm and FWHM≤40 nm; these aggregate ranges are not per-sample measurements. Absorption/PL red-shift and broaden on overcoating. Figure2 retains a×10 trace annotation,so plotted heights cannot be used directly as absolute yield ratios.',3,'Figures1–2 and ResultsIIIB',records=('core-size-optical-series',),cohorts=('core-size-spectra',),extra=((1,'Abstract/Introduction'),(4,'Optical discussion')),facts=tuple({'label':f'Figure2{lab},{d} Å core','value':qy,'unit':'%','status':'reported coated PL quantum yield'} for lab,d,qy in [('a',23,40),('b',42,50),('c',48,35),('d',55,30)]))
    item('properties','six-dispersion-photograph','Six fluorescent dispersions','Figure3 shows six dilute hexane dispersions in identical quartz cuvettes,excited with365 nm UV. Left-to-right emission maxima are470,480,520,560,594,620 nm. No exact diameter or shell loading is assigned to each cuvette. The article calls it a color photograph,but the supplied PDF reproduction is grayscale; preserve that original and do not synthetically recolor it as source evidence.',4,'Figure3 and photograph description',records=('core-size-optical-series',),cohorts=('photograph-six',))
    item('properties','coverage-absorption','Absorption versus ZnS coverage','Figure4 uses the main five-level coverage series. Spectra keep constant integrated area under the lowest1S3/2–1Se absorption feature,then show increasing red shift and broadening as shells thicken. Ultraviolet absorption rises from the ZnS contribution. These are normalized comparisons with distinct UV/visible axes; neither exact peak positions nor oscillator strengths are digitized here. The authors attribute broadening partly to shell-size distribution.',4,'Figure4 and coverage-series description',records=('coverage-series',),cohorts=('coverage-main',),kind='reported_spectra_and_author_interpretation')
    item('properties','coverage-pl','PL efficiency versus coverage','Figure5 follows the same source-defined coverage series: bare,0.65,1.3,2.6,5.3ML. Prose gives bare15%,maximum approximately50% near1.3ML and approximately30% near5ML. Emission red-shifts and broadens,and the inset’s connecting line is a guide to the eye. No exact yield is transcribed for intermediate0.65/2.6ML points from graph positions. This is a source cohort,not a predictive universal optimum or five independent complete recipes.',5,'Figure5 and PL discussion',records=('coverage-series',),cohorts=('coverage-main',))
    item('properties','air-exposure-method','Air-exposure comparison','Prepared XPS specimens are exposed to air to probe selenium-site protection. Figure7 compares bare,0.65,1.3 and2.6ML~40 Å core samples after extended exposure. The bare sample has explicitly reported16 h and80 h timepoints. Routine~15 min air contact during survey preparation is separate. Air humidity,temperature,lighting and exposure apparatus are not supplied.',5,'XPS handling',records=('air-exposure','air-exposure-observations'),cohorts=('air-time-series','xps-series'),extra=((6,'Figure7 and oxidation discussion'),))
    item('properties','air-exposure-results','Oxidation and passivation evidence','After80 h,SeO2 at59 eV is present for bare and0.65ML particles; no oxide peak is detected at~1.3ML or above. Bare dots after16 h have13%oxide contribution and Se/Cd0.77(43%Se/57%Cd); after80 h,22%oxide and Se/Cd0.37(28%Se/72%Cd). Bare Cd Auger parameter changes466.8→467.5 eV by80 h,while1.3/2.6ML remain unchanged. An estimated34%surface-atom fraction for~40 Å particles underlies the authors’ desorption interpretation. Oxide-peak fraction is not a measured fraction of oxidized whole particles.',6,'XPS oxidation and Figure7',records=('air-exposure-observations',),cohorts=('air-time-series',),kind='reported_results_and_author_interpretation')
    item('properties','zns-energy-shifts','ZnS optical shifts and model comparison','Figure15 compares absorption circles and PL squares against calculated curves for~20 Å radius cores. PL is excited at450 nm. The text reports an approximately36 meV absorption red shift for a16 Å ZnS shell; hypothetical same-material CdSe growth would shift~290 meV. The latter is a comparison calculation,not another synthesis. Broader distributions favor excitation of larger particles and increase PL shifts relative to absorption; no other plotted points are digitized.',11,'Figure15 and discussion',records=('coverage-series',),cohorts=('electronic-model',),extra=((12,'Opening optical-shift comparison'),),kind='reported_result_and_model_comparison')
    item('properties','cds-optical-comparison','CdS optical comparison and size conflict','Figure16 reports experimental CdS-shell shifts with horizontal size-distribution error bars and a model curve. The Methods specify33.5–35 Å core diameters; p11 describes~30 Å radius; Fig16 and p12 instead describe~16 Å radius. A15 Å CdS shell on~16 Å radius cores gives~210 meV red shift; hypothetical CdSe growth gives~390 meV. Retain all locators and avoid binding the entire comparison to an exact method target or converting a model counterfactual into measured synthesis data.',12,'Figure16 and optical-shift comparison',records=('cds-optical-comparison',),cohorts=('cds-comparison',),extra=((2,'CdS synthesis'),(11,'Figure16discussion')),kind='reported_result_with_source_conflict')
    item('intuition','purpose','Why inorganic shell passivation?','The authors seek narrow,bright visible emission from size-controlled CdSe and improved tolerance of subsequent processing. Higher-gap shells are intended to passivate nonradiative surface sites and suppress broad deep-trap emission,especially for smaller cores. Device,ES-OMCVD and cathodoluminescence examples in the Introduction are cited context,not devices or films synthesized and measured in this paper.',1,'Introduction',kind='author_rationale_and_cited_context',extra=((4,'Optical interpretation'),))
    item('intuition','prior-art-boundaries','Earlier systems and proposed applications','The Introduction cites CdS/CdSe and inverse shells,ZnS/CdS,ZnS/CdSe and its inverse,CdS/HgS/CdS quantum wells,ZnSe/CdSe,and Si/SiO2 as prior passivation systems. Hines/Guyot-Sionnest is cited for50% room-temperature yield. Another cited ES-OMCVD study reports ZnS-matrix films with more than two orders of magnitude PL improvement and~10%yield,plus cathodoluminescence. Organic/semiconductor LEDs and alternating-current thin-film electroluminescence are application context. None of these cited systems,film yields or device claims is a new measured outcome of this source’s shell-growth records.',1,'Introduction, references12–21',kind='cited_context_not_current_experiment',extra=((2,'Introduction final line'),))
    item('intuition','temperature-tradeoff','Why a different growth temperature for each core size?','High temperature promotes core Ostwald ripening and broadens its size distribution; low temperature risks incomplete precursor decomposition or poorly crystalline ZnS. The authors select growth temperatures separately by seed size to balance these effects. Note22 lists observed method choices but does not provide a kinetic law,validated optimum search or quantitative temperature-to-size prediction.',3,'ResultsIIIA',kind='author_process_rationale',extra=((13,'Note22'),))
    item('intuition','nucleation-control','Why dilute slow addition and further purification?','Low precursor concentration and slow delivery are intended to favor heterogeneous shell growth on existing CdSe nuclei. The paper acknowledges that homogeneous ZnS formation may persist,so size-selective precipitation is a further enrichment step. Shell dose is estimated from geometry but actual deposited material can be smaller than the feed. This rationale supports careful accounting of nominal feed,measured composition and model shell thickness as three different quantities.',2,'ZnS dose calculation',kind='author_process_rationale',extra=((3,'ResultsIIIA'),))
    item('intuition','ligand-and-solvent-function','Surface ligands and dispersion stability','TOPO/TOP coordinate both bare seeds and the outside of coated particles; “bare” means lacking inorganic shell,not ligand-free. Growth-solution storage maintains TOPO passivation,butanol prevents TOPO solidification,and CdS requires added hexane to avoid butanol-induced flocculation. Thick ZnS shells show irreversible aggregation during purification,which the authors associate with weaker TOPO passivation; polymer-film aggregation is not automatically evidence for aggregation in dilute hexane.',2,'Synthesis and storage',kind='author_rationale_and_reported_function',extra=((3,'Bare-dot terminology'),(7,'Polymer aggregation'),(12,'Thick-shell discussion')))
    item('intuition','electronic-model-assumptions','Effective-mass model and boundary conditions','The simplified model treats noninteracting electron/hole states in a spherical CdSe core with a concentric shell,no interfacial alloying and bulk effective masses. Coulomb attraction enters first-order perturbation. Equations4–5 enforce continuity of radial wavefunction and inverse-mass-weighted radial derivative at the interface. ZnS barriers are0.9 eV for both carriers. Organic-matrix barriers4 eV(electron)and10 eV(hole)are fitting parameters that absorb model deficiencies,not experimentally measured offsets.',10,'DiscussionIVA and equation4',kind='author_electronic_model',extra=((11,'Equation5 and fitting caution'),))
    item('intuition','zns-cds-confinement','Why CdS and ZnS produce different red shifts','The model’s light electron extends more than the heavy hole. ZnS permits some electron leakage but negligible hole leakage; confinement shifts saturate as shell thickens. CdS has a smaller electron barrier0.2 eV and hole barrier0.55 eV,so stronger delocalization predicts larger red shifts. Figure14 compares bare and4 Å ZnS/CdS shells. Its caption says20 Å diameter,while text and model context say20 Å radius; this discrepancy is visible rather than silently fixed.',11,'Figure14 and model discussion',kind='author_electronic_model_with_source_conflict')
    item('intuition','inhomogeneous-pl-model','Size distributions and photoluminescence shifts','Note38 estimates effective size spread by relating absorption linewidths to bare-CdSe size distributions. The model weights the PL peak by effective radius cubed because density of states scales with volume. This preferentially samples larger dots and increases the nonresonant Stokes shift. It is a stated calculation,not an independently observed full distribution or a recipe-controlled output; reference25 supplies earlier context.',13,'Note38',kind='author_optical_model',extra=((11,'Figure15 discussion'),))
    item('intuition','coverage-optimum','Why efficiency peaks near1.3 monolayers in this cohort','The maximum PL yield near1.3ML coincides with the first sample showing no Se oxide after80 h air exposure. The authors interpret this agreement as passivation of most surface vacancies/nonradiative sites. At greater coverage,nonuniform growth,weak ligand coordination and crystal defects can introduce loss pathways. This combines complementary measurements in one source cohort; it does not demonstrate that1.3ML universally optimizes other core sizes or syntheses.',12,'DiscussionIVB',kind='author_mechanistic_interpretation',extra=((13,'Conclusion'),))
    item('intuition','epitaxy-hypotheses','Coherent growth,relaxation and alternative mechanisms','The paper argues against a highly disordered shell because WAXS shows crystalline features. Low-coverage coherent epitaxy remains difficult to prove because Cd/Se dominate scattering. At higher coverage,bulk-like ZnS spacing and continuous TEM fringes motivate locally epitaxial but incoherent growth. Two proposed mechanisms remain:initial coherence followed by strain-induced dislocations/low-angle boundaries,or many coherent islands that coalesce and form grain boundaries. The cited12%CdSe/ZnS mismatch motivates both; they are hypotheses,not resolved atomistic pathways.',12,'DiscussionIVB',kind='author_competing_mechanistic_hypotheses')
    item('intuition','outlook','Open questions and synthesis implications','Source-supported questions include how to retain ligand coordination on thicker shells,avoid uncontrolled core ripening,quantify nominal-versus-deposited dose,and discriminate coherent relaxation from island coalescence. A cited planar CdSe/ZnSe quantum-well analogy has7%mismatch and degradation beyond4 monolayers; it does not set the critical thickness of colloidal CdSe/ZnS. These questions motivate future evidence collection,not a new validated protocol.',12,'DiscussionIVB and reference40',kind='source_grounded_outlook',extra=((13,'Conclusion'),))
    item('sources','source-conflicts','Source conflicts and dimensional conventions','Preserve these distinctions:note22 has40 Å whereas optical captions use42 Å; Table1 bare TEM39 Å differs from fitted SAXS42 Å; solution-SAXS5.6 versus5.3 Zn/Cd and σ0.12 versus0.11; a high-coverage σ fit is printed despite prose calling means unreliable; Fig14 diameter versus radius; CdS33.5–35 Å diameter versus~30/~16 Å radius; WAXS θ prose versus2θ axis; core-model aspect1.1 versus1.15; and the self-referential370 mm detector-distance statement. Figure16 refers to4/10 eV barriers into “CdS matrix,”where surrounding-organic barriers and CdS barriers differ in text. No automatic correction is made.',3,'SAXS geometry',kind='source_conflict_and_scope_assessment',extra=((5,'Table1'),(8,'Solution-SAXS'),(9,'Figure12'),(10,'WAXS/model'),(11,'Figure14/model'),(12,'Figure16'),(13,'Note22')))
    item('sources','reporting-gaps','Missing information and training boundaries','Matching SI is not located or verified. Missing fields include exact core precursor loading/growth time,size-selection conditions,per-sample shell doses/concentrations,seed-number calibration,vacuum levels,stirring rate,centrifugation,isolated yield,storage time,full specimen lineage and many acquisition/calibration details. No raw spectra,refined atomic coordinates,CIF,Raman or SAED pattern are supplied. Spectral curves are preserved as source images without inferred exact point values. Missing information is not zero and does not define a failed synthesis.',2,'Experimental methods',kind='review_gap_assessment',extra=((3,'Method continuation'),(5,'Table1'),(10,'Models'),(13,'Closing matter')))
    item('sources','scope','Supplied-source scope and reference reuse','All13 supplied main pages are read and visually inspected. Two byte-identical local files are one source. The inventory contains16 figures,one numbered table,five numbered equations and40 numbered references/notes. Notes22,26,38 contain direct experimental/model information and are treated accordingly; other references supply citation context only. Prior Murray,Danek and Littau entries may be linked as distinct sources,but their recipes or datasets are not silently imported here. Canonical review,reader verification,training eligibility and publication remain separate gates.',1,'Source identity',kind='review_scope_assessment',extra=((13,'References and Notes'),))

REF_ROLES={1:'Reviews of quantum dots and confinement; four bibliographic subentries',2:'Nanocrystal lattice structure and structural modeling',3:'CdSe precursor/core synthesis,size selection and structural simulation; upstream procedure not fully restated',4:'Monodisperse nanocrystal synthesis precedent',5:'Monodisperse III–V synthesis context',6:'Optical level assignment',7:'Ultrafast/optical spectroscopy background',8:'Optical excited-state context',9:'Quantum-dot spectroscopy background',10:'Fine-structure and exciton-state context',11:'Optical-state size evolution',12:'CdS/CdSe shell precedent',13:'ZnS-on-CdS passivation and simple electronic-model precedent',14:'Core/shell chemistry and XPS/Auger depth comparison',15:'CdS/HgS/CdS quantum-well precedent',16:'Danek1996 ZnSe overgrowth/process-passivation precedent',17:'Littau1993 silicon/oxide surface passivation context',18:'Silicon optical-passivation context',19:'Hines/Guyot-Sionnest CdSe/ZnS synthesis and high-yield precedent',20:'Two device manuscripts in preparation; no independently retrieved experiments',21:'ES-OMCVD composite-film/cathodoluminescence context; not current-paper film synthesis',22:'Direct source note: six paired seed diameters and ZnS-growth temperatures',23:'Phosphine-functionalized diblock matrix; upstream polymer synthesis cited',24:'XPS sensitivity/binding energy/Auger reference handbook',25:'Surface ligands and inhomogeneous/nonresonant Stokes-shift context',26:'Direct source note: photoelectron/Auger escape depths in CdSe and ZnS',27:'Air oxidation and selenium-oxide assignment',28:'Surface location from XPS/Auger intensity comparison',29:'Small-angle scattering methods and form factors',30:'Small-angle scattering methods',31:'Footprint correction and diffraction procedures',32:'Murray thesis:discrete Debye model and prior SAXS specimens',33:'Aggregation signature in disordered particle films',34:'Solution-SAXS sizes/dispersity and interparticle effects',35:'Finite-barrier core/shell electronic model',36:'Core/shell wavefunction modeling',37:'Band-offset reference used in effective-mass model',38:'Direct source note:absorption-derived effective distribution and radius-cubed PL weighting',39:'Stacking-fault formation energy reference',40:'Planar CdSe/ZnSe quantum-well misfit/dislocation analogy,not a colloidal shell threshold'}
def references():
    text=(B/'plain-page-13.txt').read_text(encoding='utf-8').split('References and Notes',1)[1]
    parts=re.split(r'(?m)^\((\d+)\)\s*',text);out=[]
    for j in range(1,len(parts),2):
        n=int(parts[j]);citation=' '.join(parts[j+1].split());citation=citation.split('(CdSe)ZnS Core-Shell Quantum Dots J. Phys.')[0].strip();direct=n in {22,26,38}
        d={'reference_number':n,'citation_as_printed_extracted':citation,'role':REF_ROLES[n],'source_locator':loc(13,f'Reference/Note{n}'),'cited_work_independently_reviewed_in_this_task':False,'import_experimental_evidence':False,'entry_type':'source_experimental_or_model_note' if direct else 'citation_context','direct_source_note_reviewed':direct}
        out.append(d)
        item('sources',f'reference-{n}',f'{"Note" if direct else "Reference"} {n}',REF_ROLES[n]+('. This is information printed in the inspected main article; retain the dedicated evidence item and its stated limits.' if direct else '. This cited work was not independently retrieved or read for this review; its procedures and measurements do not fill missing fields.'),13,f'Reference/Note{n}',kind='source_note_context' if direct else 'citation_only_context',notes=(citation,))
    assert [r['reference_number'] for r in out]==list(range(1,41));return out

ASSET_LINKS={
 'figure-1':(['core-size-optical-series'],['core-size-spectra']),'figure-2':(['core-size-optical-series'],['core-size-spectra']),'figure-3':(['core-size-optical-series'],['photograph-six']),
 'figure-4':(['coverage-series'],['coverage-main']),'figure-5':(['coverage-series'],['coverage-main']),'figure-6':(['coverage-series','xps-preparation'],['xps-series']),
 'figure-7':(['air-exposure-observations','air-exposure'],['air-time-series']),'figure-8':(['coverage-series','tem-preparation'],['tem-particles']),'figure-9':(['coverage-series'],['tem-particles']),
 'figure-10':(['coverage-series','saxs-pvb-film','saxs-diblock-film'],['polymer-saxs']),'figure-11':(['solution-saxs-series','saxs-solution'],['solution-saxs']),'figure-12':(['solution-saxs-series'],['solution-saxs']),
 'figure-13':(['coverage-series','waxs-film'],['waxs-main']),'figure-14':([],['electronic-model']),'figure-15':(['coverage-series'],['electronic-model']),'figure-16':(['cds-optical-comparison'],['cds-comparison']),
 'table-1':(['coverage-series'],['coverage-main']),'equation-1':([],['xps-series']),'equation-2':([],['polymer-saxs','waxs-main']),'equation-3':([],['solution-saxs']),'equation-4':([],['electronic-model']),'equation-5':([],['electronic-model'])}
ASSET_LINKS.update({'formula-guinier-context':([],['solution-saxs']),'formula-radius-context':([],['solution-saxs']),'source-note-22':(['zns-overgrowth'],['zns-method'])})
PAGE_SECTIONS={1:['Title/authors/journal/date,abstract,Introduction,cited prior systems/device motivation'],2:['All materials,TOPSe stock,partial CdSe seed synthesis,ZnS and CdS routes,storage,all specimen/acquisition methods start'],3:['Polymer/solution SAXS,WAXS methods,temperature/addition rationale,monolayer definition,Figures1–2'],4:['Photograph Figure3,main coverage-cohort design,absorption Figure4'],5:['Table1,PL Figure5,WDS composition,XPS Figure6'],6:['Air-exposure Figure7,TEM Figure8,Auger/depth analysis,equation1'],7:['TEM histograms Figure9,polymer SAXS fitting,equation2,aggregation limits'],8:['Figure10 polymer SAXS,independent Figure11 solution series,equation3,Guinier/Porod analysis'],9:['Figure12 solution fits/conflicts,contrast/upper-size limits,Figure13 WAXS'],10:['WAXS fit parameters,sensitivity/interface limits,finite-barrier model,equation4'],11:['Figure14 model/size conflict,equation5,Figure15 measured/model shifts,CdS comparison intro'],12:['Figure16 CdS comparison/conflicts,coverage-yield interpretation,competing epitaxy mechanisms'],13:['Conclusion,acknowledgments,References and Notes1–40 including direct notes22/26/38']}
TABLE_ROWS=[{'coverage_ml':m,'tem_major_axis_A':s,'tem_relative_spread_percent':u,'measured_aspect_ratio':a,'polymer_saxs_fit_size_A':ss,'polymer_saxs_relative_spread_percent':su,'wds_measured_Zn_Cd':w,'polymer_saxs_calculated_Zn_Cd':sr,'waxs_calculated_Zn_Cd':wr} for m,s,u,a,ss,su,w,sr,wr in [(0,39,8.2,1.12,42,10,None,None,None),(.65,43,11,1.16,46,13,.46,.58,.7),(1.3,47,10,1.16,50,18,1.5,1.32,1.4),(2.6,55,13,1.23,None,None,3.6,None,2.9),(5.3,72,19,1.23,None,None,6.8,None,6.8)]]
CONFLICT_TEXT={
'c_core40_42_39':'Approximately 40 Å in the main prose, 42 Å ±10% in optical/SAXS labels, and 39 Å ±8.2% in TEM have distinct measurement definitions. Note 22 explicitly pairs 40 Å with 180 °C; it does not provide a separate 42 Å setting.',
'c_saxs5p3_5p6':'The highest Zn/Cd ratio in the independent solution-SAXS series is 5.3 in Figure 11 and p. 9, but 5.6 in the p. 8 Guinier discussion.',
'c_sigma':'Bare solution-SAXS polydispersity is approximately 0.12 in p. 9 prose and 0.11 in the Figure 12 caption.',
'c_high_saxs_fit':'Figure 12 labels sample d with σ = 0.25 even though the prose considers high-coverage mean size and variance unreliable. The caption fit is not proof of a reliable average.',
'c_F14_core':'Figure 14 calls the core 20 Å in diameter, while its surrounding text says approximately 20 Å in radius. The plotted radial boundary does not authorize silently correcting the caption.',
'c_CdS_core':'CdS Methods specify 33.5–35 Å core diameters; p. 11 says approximately 30 Å radius; Figure 16 and p. 12 say approximately 16 Å radius. The source does not resolve whether different specimens explain this.',
'c_F16_barrier':'Figure 16 describes 4/10 eV barriers into a surrounding CdS matrix. The model prose assigns those barriers to the organic matrix and gives 0.2/0.55 eV for CdS.',
'c_detector_distance':'The SAXS instrument description places the detector at D = 370 mm from the detector. The other endpoint is unresolved.',
'c_theta':'The WAXS simulation range is printed as 15° < θ < 60°, while the Figure 13 axis is 2θ. Approximate feature positions remain associated with the plotted axis.',
'c_model_aspect':'WAXS core-model aspect ratio is initially 1.1 and later 1.15; Table 1 gives a measured TEM mean of 1.12. These are not one exact shared value.',
'c_photo_color':'Figure 3 is described as a color photograph, but the supplied PDF reproduction is grayscale. Its colors have not been reconstructed.',
'c_nominal_actual':'Nominal geometric dose, actual WDS Zn/Cd, TEM-derived coverage and SAXS/WAXS fitted composition are different quantities. Deposited shell can be less than the precursor addition.',
'c_cds_storage_equal':'Equal hexane and butanol amounts for CdS storage lack an explicit mass/volume basis or absolute quantities.',
'c_monolayer_geometry':'The shell-monolayer convention is 3.1 Å along the major axis, whereas precursor-dose design assumes spherical geometry. Thick-shell particles are prolate and nonuniform.',
'c_oxidation_threshold':'Oxide absence is described at approximately 1.3 monolayers or more; unchanged Se/Cd after 80 h is stated for more than 1.3 monolayers. The 1.3/2.6-monolayer Auger parameters remain unchanged.',
'c_model_counterfactual':'Hypothetical 16/15 Å CdSe shells with 290/390 meV shifts are model comparisons, not additional experimentally synthesized products.',
'c_prior_film_devices':'The Introduction’s approximately 10% ES-OMCVD film yield and cathodoluminescence belong to reference 21. LED discussions cite reference 20 manuscripts; these are not new, fully specified experiments in this article.'}

def main():
    content();refs=references();identity=read(B/'source-identity.json');manifest=read(B/'crop-assets/manifest.json')
    assert manifest['source_sha256']==identity['main_sha256']
    assets={'figures':[],'tables':[],'equations':[],'schemes':[],'source_notes':[]};file_sources={}
    for a in manifest['assets']:
        ident=re.sub(r'^(figure|table|equation)-0',r'\1-',a['id']);p=B/'crop-assets'/a['relative_asset'];assert sha(p)==a['sha256'];links,cohorts=ASSET_LINKS[ident]
        assert a['visually_reviewed']
        kind='tables' if ident.startswith('table-') else 'equations' if ident.startswith(('equation-','formula-')) else 'source_notes' if ident.startswith('source-note-') else 'figures'
        v={'id':ident,'label':a['title'],'document_role':'main','page':a['pdf_page'],'printed_page':a['printed_page'],'source_locators':[loc(a['pdf_page'],a['title'])],'caption_paraphrase':a['caption_paraphrase'],'sample_scope':a['sample_scope'],'sample_links':[RECORDS[k] for k in links],'cohort_keys':cohorts,'sample_linkage':'Source-cohort context only; model-only items do not create synthesis outcomes or measured atomic structures.','formulation_labels':cohorts,'evidence_class':a['evidence_type'],'public_asset':'assets/figures/'+SID+'/'+a['relative_asset'],'public_asset_sha256':a['sha256'],'asset_provenance':{'source_file':'10.1021_jp971091y.pdf','source_sha256':identity['main_sha256'],'source_pdf_page':a['pdf_page'],'crop_bbox_pdf_points_top_left':a['bbox_pdf_points_top_left'],'crop_normalized':a['crop_normalized'],'render_dpi':a['dpi'],'pixel_dimensions':a['pixel_dimensions'],'renderer':a['renderer'],'transformation':'Original PDF raster crop; no curve digitization, synthetic coloring or replacement.'},'quantitative_context':a.get('quantitative_context',a.get('scope_caveats',[])),'notes':a.get('scope_caveats',[]),'text_reviewed':True,'visual_reviewed':True,'reviewed':False,'reader_render_verified':False,'training_eligible':False,'source_asset_type':a['type']}
        if a.get('panels'):v['panels']=a['panels']
        if ident=='table-1':v.update(structured_rows=TABLE_ROWS,data_role='Source table:measured TEM/WDS values and fitted SAXS/WAXS values remain separate; blank cells are null.')
        assets[kind].append(v);file_sources[ident]={'private_file':str(p),'sha256':sha(p)}
        if ident=='source-note-22':
            for it in SECTIONS['protocol']['items']:
                if it['id']=='size-temperature-pairs':it['original_assets']=[{'id':ident,'label':'Original source note 22','public_asset':v['public_asset'],'sha256':a['sha256']}]
    drafts={k:read(B/'canonical-drafts'/f'{rid}.json') for k,rid in RECORDS.items() if (B/'canonical-drafts'/f'{rid}.json').exists()}
    products={key:{p['sample_id']:n for n,p in enumerate(r['products'])} for key,r in drafts.items()}
    selection={
      'core-size-spectra':('core-size-optical-series',['size-a','size-b','size-c','size-d']),
      'photograph-six':('core-size-optical-series',[f'photo-{i}' for i in range(1,7)]),
      'coverage-main':('coverage-series',['bare','ml-065','ml-13','ml-26','ml-53']),
      'tem-particles':('coverage-series',['bare','ml-065','ml-13','ml-26','ml-53']),
      'polymer-saxs':('coverage-series',['bare','ml-065','ml-13','ml-26','ml-53']),
      'waxs-main':('coverage-series',['bare','ml-065','ml-13','ml-26','ml-53']),
      'xps-series':('coverage-series',['xps-bare-context','xps-065-context','xps-13-context','xps-26-context','xps-bonding-context']),
      'air-time-series':('air-exposure-observations',['bare-initial','bare-16h','bare-80h','coated-0.65','coated-1.3','coated-2.6']),
      'solution-saxs':('solution-saxs-series',[f'solution-{x}' for x in 'abcde']),
      'cds-comparison':('cds-optical-comparison',['cds-series'])}
    for sec in SECTIONS.values():
        for it in sec['items']:
            samplelinks=[]
            for cohort in it['sample_scope']['cohort_keys']:
                if cohort not in selection:continue
                key,samples=selection[cohort]
                if RECORDS[key] not in [x['record_id'] for x in it['canonical_links']]:continue
                for sample in samples:
                    assert sample in products.get(key,{}),(key,sample)
                    link={'record_id':RECORDS[key],'sample_id':sample,'json_pointer':f'/products/{products[key][sample]}','relation':'Source-defined cohort member; a single statement need not apply to every listed member. Preserve item-specific specimen and treatment qualifiers.'}
                    if link not in samplelinks:samplelinks.append(link)
            if it['id']=='zns-energy-shifts':
                key='coverage-series';sample='coverage-optical-shift';samplelinks=[{'record_id':RECORDS[key],'sample_id':sample,'json_pointer':f'/products/{products[key][sample]}','relation':'Figure15 optical-shift cohort only; calculated comparison shifts are not additional measured samples.'}]
            xps_specific={'xps-composition':['xps-bare-context','xps-13-context','xps-bonding-context'],'auger-parameters':['xps-bonding-context','xps-065-context','xps-13-context','xps-26-context'],'xps-intensity-model':['xps-065-context','xps-26-context'],'xps-finite-size-correction':['xps-bare-context']}
            if it['id'] in xps_specific:
                key='coverage-series'
                samplelinks=[{'record_id':RECORDS[key],'sample_id':sample,'json_pointer':f'/products/{products[key][sample]}','relation':'XPS context only. Exact physical identity with an equal-coverage Table1/TEM/optical specimen is not established.'} for sample in xps_specific[it['id']]]
            if samplelinks:it['sample_scope']['canonical_sample_links']=samplelinks
            if it['id']=='solution-saxs-fitting':it['notes'].append('The printed unnumbered Guinier expression is I(q,N) ≅ I(0,N) exp(−q² R_G²/5), with R_G called the Guinier radius. Preserve this source convention; do not silently replace the denominator or reinterpret the radius symbol.')
            if it['id']=='air-exposure-results':it['notes'].append('The source says oxide absence at approximately 1.3 monolayers or more, but describes unchanged Se/Cd after 80 h for more than 1.3 monolayers. No Cd–O peak is reported after comparable exposure. These statements retain their different scopes.')
            if it['id'] in ['air-exposure-method','air-exposure-results','xps-composition']:
                it['notes'].append('Initial Se/Cd ≈0.87 is general bare-XPS context, repeated in the coverage and air-exposure records without representing an independent replicate. Its exact physical identity with the later exposure film is unresolved. The source identifies the 16 h and 80 h measurements as successive states of the same bare specimen.')
            if it['id']=='waxs-model':it['notes'].append('The first ZnS convolution feature is estimated to have approximately three times less integrated scattering than CdSe, explaining why thin shells are poorly constrained. This is a scattering-model comparison, not a measured material yield.')
            if it['id']=='polymer-film-preparation':it['notes'].append('The approximately 5 mg particle mass is not explicitly separated into inorganic and ligand mass. No final solids ratio is derived from the 10 wt% solution without density/final-volume information.')
    types={k:drafts[k]['record_type'] if k in drafts else ('literature_protocol' if k in KEYS[:2] else 'observation' if k in KEYS[-5:] else 'procedure') for k in KEYS}
    inventory=[{'id':rid,'label':drafts[k]['title'] if k in drafts else k.replace('-',' ').capitalize(),'record_ids':[rid],'record_type':types[k],'status':'proposed_pending_canonical_audit','cohort_keys':[c for c,(r,_) in COHORTS.items() if r==k],'scope':'Supporting/source-cohort record; not an additional independent synthesis.' if types[k]!='literature_protocol' else 'General reported shell-growth method,not independently specified batches for every setting.','gaps':['Matching SI not located or verified.','Canonical sample/operation/measurement joins pending independent audit.']} for k,rid in RECORDS.items()]
    ledger={'schema_version':'1.0','paper_id':SID,'doi':DOI,'title':identity['title'],'paper':{'authors':identity['authors'],'journal':identity['journal'],'year':1997,'volume':101,'issue':46,'pages':'9463–9475'},'source_group':SID,'corpus_paper_id':identity['existing_identity']['papers'][0]['paper_id'],'corpus_document_id':identity['cached_identity_reuse'][0]['document_id'],'review_scope':'supplied_main_only_si_unverified','supporting_information':{'status':'not_located_or_verified','note':'No local matched SI verified; no absence claim.'},'documents':[{'role':'main','filename':'10.1021_jp971091y.pdf','sha256':identity['main_sha256'],'page_count':13,'pages':[{'page':n,'printed_page':9462+n,'text_read':True,'visual_review':True,'sections':PAGE_SECTIONS[n]} for n in range(1,14)]}],'document_identity_verification':{'method':'Visual first/final pages and actual local source hashes matched to corpus identity','full_doi_printed':False},'coverage_status':'All13 supplied main pages read and visually inspected; independent source-audit mapping pending.','independent_audit':'Separate source-audit integration pending; canonical and reader acceptance remain separate.','publication_status':'private_proposal_not_published','source_review_promoted':False,'training_eligible':False,'training_note':'This ledger does not promote canonical or training eligibility. Two routes are distinct from characterization procedures,source observations and theoretical models.','recipe_inventory':inventory,'cohort_inventory':[{'key':c,'record_id':RECORDS[k],'scope':scope} for c,(k,scope) in COHORTS.items()],'characterization_inventory':{'reader_item_ids':[x['id'] for s in ['structures','properties'] for x in SECTIONS[s]['items']]},**assets,'reader_sections':list(SECTIONS.values()),'record_formulation_labels':{rid:[c for c,(k,_) in COHORTS.items() if k==key] for key,rid in RECORDS.items()},'record_formulation_scope_note':'Main coverage and independent solution-SAXS cohorts cannot be joined. Method temperature pairs do not assign every figure sample. Models remain distinct from measurements.','referenced_methods':refs,'chemical_intuition':{'reader_item_ids':[x['id'] for x in SECTIONS['intuition']['items']],'scope':'Author rationale,competing hypotheses,model assumptions and cited analogies distinguished from measurements.'},'reader_contract':{'version':'1.0','section_ids':list(SECTIONS),'item_fields':['id','title','text','claim_type','sample_scope','evidence','source_locators','canonical_links','notes','facts','training_eligible']},'remaining_gaps':['Matching SI not located or verified.','Exact experimental/model conflicts and reporting gaps retained in Sources.','Independent canonical joins,reader visual review and publication remain pending.'],'material_evidence_records':{},'reader_exclusions':[{'source_item_id':'download-watermark','reason':'Not experimental evidence.'},{'source_item_id':'acknowledgments','reason':'Page inventoried; not recipe fields.'}]}
    ledger['record_formulation_labels'][RECORDS['zns-overgrowth']]=['zns-method','core-size-spectra','coverage-main','photograph-six']
    ledger['record_formulation_labels'][RECORDS['cds-overgrowth']]=['cds-method','cds-comparison']
    coverage=[{'source_item_id':v['id'],'source_locators':v['source_locators'],'target':f'/reader_sections/{s}/items/{i}','disposition':'reader_item','claim_type':v['claim_type']} for s,sec in enumerate(ledger['reader_sections']) for i,v in enumerate(sec['items'])]
    for kind in ['figures','tables','equations','source_notes']:
        coverage += [{'source_item_id':v['id'],'source_locators':v['source_locators'],'target':f'/{kind}/{i}','disposition':'original_asset_and_context','claim_type':v['evidence_class']} for i,v in enumerate(ledger[kind])]
    ledger['reader_item_coverage']=coverage
    assert len(set(c['source_item_id'] for c in coverage))==len(coverage)
    assert [len(assets[k]) for k in ['figures','tables','equations','source_notes']]==[16,1,7,1]
    assert all(c in COHORTS for s in SECTIONS.values() for x in s['items'] for c in x['sample_scope']['cohort_keys'])
    auditpath=B/'source-audit.json';audit=read(auditpath) if auditpath.exists() else None
    units=[]
    if audit:
        assert audit['status']=='independent_supplied_main_text_and_visual_review_complete'
        assert audit['source']['sha256']==identity['main_sha256'] and len(audit['page_review'])==13
        for p in audit['page_review']:
            assert p['text_reviewed'] and p['visual_reviewed']
            assert sha(B/p['text_file'])==p['text_sha256'] and sha(B/p['image_file'])==p['image_sha256']
        ledger['coverage_status']='All 13 supplied main pages read and visually inspected; independent source audit complete. Canonical joins, reader acceptance and publication remain separate.'
        ledger['independent_audit']='Independent supplied-main scientific reading and visual audit complete; no matched SI reviewed. Canonical operation/sample/measurement and final reader audits remain separate.'
        ledger['audit_details']={'source_audit_sha256':sha(auditpath),'source_audit_status':audit.get('status'),'scope':'Independent source audit available; explicit source-unit mapping in companion report.'}
        assert set(CONFLICT_TEXT)=={c['id'] for c in audit['conflicts_and_semantic_hazards']}
        ledger['evidence_conflicts']=[{'id':c['id'],'text':CONFLICT_TEXT[c['id']],'claim_type':c['claim_type'],'source_locators':[loc(e['pdf_page'],e['locator']) for e in c['evidence']]} for c in audit['conflicts_and_semantic_hazards']]
        units=build_source_map(audit,ledger,coverage)
    report={'status':'private_proposal_structural_checks_passed','created_utc':datetime.now(timezone.utc).isoformat(),'counts':{'pages':13,'canonical_records_expected':17,'synthesis_routes_expected':2,'procedures_expected':10,'observations_expected':5,'logical_cohorts':len(COHORTS),'figures':16,'tables':1,'numbered_equations':5,'unnumbered_formula_contexts':2,'source_note_crops':1,'numbered_references_and_notes':40,'direct_source_notes':3,'reader_items':sum(len(s['items']) for s in SECTIONS.values()),'reader_asset_units':len(coverage)},'input_sha256':{'source-identity.json':sha(B/'source-identity.json'),'crop-assets/manifest.json':sha(B/'crop-assets/manifest.json'),**{f'plain-page-{n}.txt':sha(B/f'plain-page-{n}.txt') for n in range(1,14)},**{f'main-{n:02}.png':sha(B/f'main-{n:02}.png') for n in range(1,14)}},'source_audit_available':bool(audit),'source_audit_unit_map_complete':False,'asset_file_provenance':file_sources,'promotion':{'training':False,'canonical_source_reviewed':False,'reader_audit_complete':False,'published':False},'pending':['Complete explicit independent source-audit mapping.','Independent canonical joins and source-to-reader audit.','Final cropped-asset and browser review.','Publication.']}
    if audit:
        report['source_audit_unit_map_complete']=True
        report['counts']['scientific_source_audit_units_mapped']=len(units)
        report['input_sha256']['source-audit.json']=sha(auditpath)
        report['pending'].remove('Complete explicit independent source-audit mapping.')
    report['input_sha256'].update({f'canonical-drafts/{RECORDS[k]}.json':sha(B/'canonical-drafts'/f'{RECORDS[k]}.json') for k in drafts})
    report['editorial_coverage_note']='All independent scientific-unit categories and ten missing-information items have explicit public targets. Identity,page checks,OCR cautions and parameter-concept summaries are audit metadata reflected in those units,not additional measurements.'
    report['counts']['unnumbered_relations_in_reader']=4
    canonical_audit=read(B/'canonical-records-audit.json')
    ledger,editorial_changes=finalize(ledger,canonical_audit)
    report['pending']=['Final source-to-reader audit.','Final cropped-asset and browser review.','Publication.']
    report['independent_canonical_audit_sha256']=sha(B/'canonical-records-audit.json')
    for name,v in [('dabbousi1997.json',ledger),('source-item-coverage.json',{'reader_units':coverage,'source_audit_unit_map':units,'scope':'All reader/asset units and explicit independent scientific audit mappings; reader/publication acceptance remain separate.'}),('validation.json',report),('editorial-change-log.json',{'scope':'Whitespace-only changes to allowlisted reader prose; no identifiers, locators, numerical values, hashes or quoted-source files modified. Canonical audit status updated separately using passed independent audit.','changes':editorial_changes})]:
        (OUT/name).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    (OUT/'HANDOFF.md').write_text('# Dabbousi1997 private source ledger\n\nAcademic source content with 17 proposed record links and 20 scoped cohorts. All 13 supplied main pages were read and visually inspected; all 204 independent source-audit units are mapped. Notes 22, 26 and 38 are direct source information; other citations are not imported procedures. Source/canonical/reader/training/publication gates remain separate.\n\n'+json.dumps(report['counts'],indent=2)+'\n\nAll 25 original assets are retained: 16 figures, Table 1, five numbered equations, two unnumbered formula contexts, and source note 22. Four unnumbered relations are explained: Guinier and radius-ratio relations have original context crops; normalized XPS/Auger ratio and finite-size attenuation integral are explicit reader text. The ledger `equations` array therefore has seven asset entries; it does not claim seven numbered equations. Note 22 is in `source_notes`, and `size-temperature-pairs.original_assets` links its original crop with label/public_asset/sha256. Root should extend the source-item original-asset renderer and source-note validation narrowly. No note is mislabeled a figure/equation/experiment.\n\nSource-item product pointers resolve only to source-defined canonical cohorts; the statement-specific qualifiers still control which member a value concerns. Figures 14 and equations have no experimental sample links. Source-to-reader/renderer audit and publication are pending.\n',encoding='utf-8')
    print(json.dumps(report['counts']))
if __name__=='__main__':main()
