"""Root source extraction; private drafts remain ineligible until independently audited."""
from pathlib import Path
from copy import deepcopy
import json,sys,hashlib
B=Path(__file__).resolve().parent; S=B.parents[3]/'recipe-atlas'
sys.path.insert(0,str(S/'scripts'))
from record_helpers import record,source,ev,fact,qty,material,operation,state,product,measurement
from dataset_lib import validate_record,eligibility,build_groups
OUT=B/'canonical-drafts';OUT.mkdir(exist_ok=True)
SID='danek1996'
SRC=source(SID,'10.1021/cm9503137','Synthesis of Luminescent Thin-Film CdSe/ZnSe Quantum Dot Composites Using CdSe Quantum Dots Passivated with an Overlayer of ZnSe','Michal Danek; Klavs F. Jensen; Chris B. Murray; Moungi G. Bawendi',1996)
SRC['main_status']='All eight supplied main pages read and visually inspected; independent canonical audit pending'
def E(p,s):return ev(SID,f'Main PDF p. {p}, printed p. {172+p}, {s}')
MAT=E(2,'Materials');SYN=E(2,'Synthesis of CdSe/ZnSe Nanocrystals');DISP=E(2,'Preparation of the Nanocrystal Dispersions for ES-OMCVD');CVD=E(2,'ES-OMCVD Synthesis');OPT=E(2,'Optical Characterization');COMP=E(2,'Chemical Composition');MIC=E(2,'Electron Microscopy')+E(3,'Electron Microscopy continuation');XRD=E(3,'X-ray Diffraction')
def Q(v=None,u='',e=SYN,**kw):return qty(v,u,e,**kw)
def F(v=None,e=SYN,**kw):return fact(v,e,**kw)
def M(id,n,f,role,stage='synthesis',e=SYN,notes=None,quantities=None):return material(id,n,f,role,stage,e,notes=notes or [],quantities=quantities)
def base(key,title,kind='procedure',method='Supporting procedure',architecture='core_shell'):
 r=record('danek-1996-'+key,'Danek et al. (1996) · '+title,'CdSe/ZnSe','II–VI quantum-dot heterostructures',method,SRC,'Main PDF pp. 1–8, printed pp. 173–180',kind)
 r['collection']='reviewed_literature';r['material'].update(elements=['Cd','Se','Zn'],components=['CdSe','ZnSe'],architecture=architecture)
 r['lineage']['recipe_family']='danek1996-passivation-and-film-composites'
 r['intended_target']['composition']=F('CdSe core with ZnSe overlayer' if architecture=='core_shell' else 'CdSe quantum dots embedded in a ZnSe film',E(1,'Abstract'))
 r['quality'].update(review_status='imported_unreviewed',requested_tasks=[],review_scope='Private extraction from all eight supplied main pages, with complete root text/visual reading. Canonical audit and reader integration pending. SI not located or verified. Source/sample scope does not establish independent physical batches.',missing_fields=['Matching supporting information not located or verified.','No measured atomic coordinates or fully refined core/shell interface structure is supplied.'],conflicts=[])
 r['context_links']=[{'label':'Full source review','url':'../paper-review.html?id=danek1996','relation':'Supplied main only; matching SI not located or verified.'}]
 return r
def link(r,key,label,relation):r['context_links'].append({'label':label,'url':'../records/danek-1996-'+key+'.html','relation':relation})
def add(r,oid,action,label,inputs,out,e=SYN,parameters=None,stage='synthesis',description='',depends=None,environment=None,optional=False,branch='main',retained=False):
 if out:r['material_states'].append(state(out,label+' output',inputs,'product' if stage=='storage' else 'mixture'))
 r['operations'].append(operation(oid,action,label,e,inputs,[out] if out else [],depends=depends,parameters=parameters or {},stage=stage,description=description,environment=F(environment,e),optional=optional,branch=branch,retained_fraction=out if retained else None))
 return oid
def P(r,id,label,formula='CdSe/ZnSe',e=SYN,state_id=None,linkage='general_context',notes=None):
 p=product(id,formula,e,link=linkage,state=state_id,notes=notes or []);p['source_sample_label']=label;r['products'].append(p);return p
def V(r,id,sample,prop,v,tech,e,conditions=''):r['measurements'].append(measurement(id,sample,prop,v,tech,e,conditions))
def stock(id,name,ids,conc,e,scope,quantities=None,ops=None):return {'id':id,'name':name,'components':[{'material_id':i,'quantities':(quantities or {}).get(i,{})} for i in ids],'concentrations':conc,'preparation_operation_ids':ops or [],'scope':scope,'evidence':e}
records=[]

# One general overgrowth recipe, not a separate invented experiment for each figure.
r=base('znse-overgrowth','Solution overgrowth of ZnSe on CdSe','literature_protocol','Seeded ZnSe overgrowth in TOP')
r['materials']=[M('cdse-seeds','Purified, size-selected CdSe nanocrystals','CdSe','seed',notes=['Initial TOP/TOPO preparation is cited to reference10; detailed core synthesis is not repeated here.'],quantities={'mass':Q(100,'mg',approximate=True,basis='Reported purified nanocrystal sample; ligand mass basis not specified')}),M('top','Trioctylphosphine','C24H51P','solvent',notes=['Fluka; used as received (Materials).']),M('topse','Trioctylphosphine selenide','C24H51PSe','chalcogen_precursor',notes=['1.0 M stock prepared by cited reference10. Seed dispersion charge and fed stock amounts are distinct.']),M('dezn','Diethylzinc','C4H10Zn','metal_precursor',notes=['Aldrich; filtered through0.2µm PTFE. Source explicitly identifies high pyrophoricity. Separate OMCVD grade is not this reagent.']),M('nonane','Nonane','C9H20','optional cosolvent',notes=['Anhydrous, Aldrich; used as received. Optional small amount accelerates redispersion; amount unspecified.']),M('methanol','Methanol','CH4O','antisolvent','workup',notes=['Electronic grade, Mallinckrodt; used as received.']),M('butanol','Butanol (isomer unspecified)','C4H10O','quench reagent','workup',notes=['Mallinckrodt; source does not identify isomer. Alcoholyzes residual DEZn.'],quantities={'volume':Q(5,'mL',approximate=True)}),M('hexane','Hexane','C6H14','antisolvent','workup',notes=['HPLC grade, Mallinckrodt; used as received.']),M('pyridine','Pyridine','C5H5N','ligand and solvent','surface_exchange',notes=['Anhydrous, Aldrich; used as received.']),M('ar','Argon','Ar','inert atmosphere'),M('n2','Nitrogen','N2','storage atmosphere','storage')]
r['stocks']=[stock('seed-dispersion','CdSe seeds in TOP/TOPSe',['cdse-seeds','top','topse'],{},SYN,'10mL TOP contains0.5mmol TOPSe. Optional nonane is added only if required; final volume not measured.',{'top':{'volume':Q(10,'mL')},'topse':{'amount':Q(.5,'mmol')}},['redisperse']),stock('growth-feed','Equimolar DEZn/TOPSe in TOP',['dezn','topse','top'],{'dezn_per_topse':Q(1,'',basis='Equimolar DEZn and TOPSe; absolute feed precursor quantities not reported')},SYN,'Separate10mL TOP stock; total dosed volume and absolute precursor amounts are unreported. Do not infer the whole stock was delivered.',{'top':{'volume':Q(10,'mL')},'dezn':{'amount':Q(u='mmol')},'topse':{'amount':Q(u='mmol')}},['prepare-feed'])]
add(r,'precipitate','precipitation','Precipitate purified CdSe seeds',['cdse-seeds','methanol'],'precipitated',stage='workup',description='Methanol precipitation before transfer to the glovebox; solvent volume is not stated.')
add(r,'separate','centrifugation','Collect CdSe nanocrystals',['precipitated'],'seed-pellet',stage='workup',depends=['precipitate'],parameters={'speed':Q(u='rpm'),'duration':Q(u='min')},description='Separate by centrifugation; retain the particles, then transfer into a glovebox.',retained=True)
add(r,'redisperse','redispersion','Prepare the CdSe seed dispersion',['seed-pellet','top','topse'],'seed-slurry',depends=['separate'],stage='precursor_preparation',description='Disperse in10mL TOP containing0.5mmol TOPSe in a glovebox. Optional nonane amount is unspecified.')
add(r,'nonane-option','cosolvent_addition','Optional nonane-assisted redispersion',['seed-slurry','nonane'],'nonane-branch',depends=['redisperse'],stage='precursor_preparation',optional=True,branch='optional_redispersion',description='Optional small amount of anhydrous nonane. The main filtered-dispersion state includes this branch only when used; no volume assumed.')
add(r,'filter-seeds','filtration','Filter the nanocrystal dispersion',['seed-slurry'],'filtered-seeds',depends=['redisperse'],stage='precursor_preparation',parameters={'filter_pore_size':Q(.2,'um')},description='0.2µm PTFE filter; collect the dispersion. Optional nonane-assisted branch is not a mandatory step.',retained=True)
r['operations'][-1]['optional_inputs']=['nonane-branch']
add(r,'heat','heating','Heat the argon-backfilled flask',['filtered-seeds','ar'],'hot-seeds',depends=['filter-seeds'],parameters={'temperature':Q(150,'degC'),'duration':Q(u='min'),'pressure':Q(u='Torr')},environment='Argon, Schlenk line',description='Transfer to an Ar-backfilled flask and heat to150°C. Body discussion gives150–160°C as general overgrowth range; standard procedure is150°C. Pressure and stabilization time unreported.')
add(r,'prepare-feed','stock_preparation','Prepare and filter the shell-growth feed',['dezn','topse','top'],'prepared-feed',stage='precursor_preparation',parameters={'filter_pore_size':Q(.2,'um')},environment='Glovebox; gas not specified',description='Mix equimolar DEZn and TOPSe in a separate10mL TOP portion;0.2µm PTFE syringe filtration. Absolute amounts/concentrations and total delivered fraction are unknown. Independent stock preparation; no timing relative to flask heating is inferred.')
add(r,'dose','continuous_addition','Dose the precursors while stirring',['hot-seeds','growth-feed'],'overgrown',depends=['heat','prepare-feed'],parameters={'temperature':Q(150,'degC'),'feed_flow':Q(.3,'mL/min',approximate=True),'dosed_volume':Q(u='mL'),'duration':Q(u='min'),'pressure':Q(u='Torr')},environment='Argon, Schlenk line',description='Syringe-pump delivery to heated stirred dispersion; follow overgrowth by UV/vis absorption. Stop after the desired amount, not a stated exact time. Slow delivery is intended to suppress separate ZnSe nucleation.')
r['operations'][-1]['endpoint']=F('Desired precursor amount added; overgrowth monitored by UV/vis absorption')
add(r,'cool','cooling','Cool to room temperature',['overgrown'],'cooled',depends=['dose'],description='Room temperature is not a numerically specified setpoint; cooling rate/time unknown.')
add(r,'quench','alcoholysis','Alcoholyze residual diethylzinc',['cooled','butanol'],'quenched',depends=['cool'],stage='workup',parameters={'butanol_volume':Q(5,'mL',approximate=True)},description='Add about5mL butanol to the cooled mixture; no quench duration is given.')
add(r,'isolate','precipitation_centrifugation','Isolate the overcoated particles',['quenched','hexane'],'isolated',depends=['quench'],stage='workup',parameters={'speed':Q(u='rpm'),'duration':Q(u='min')},description='Precipitate with hexane and centrifuge; retain nanocrystals. Hexane volume and centrifuge settings are unreported.',retained=True)
add(r,'exchange','ligand_exchange','Purify and exchange the surface ligand',['isolated','pyridine','hexane'],'pyridine-particles',depends=['isolate'],stage='surface_exchange',parameters={'cycle_count':Q(u='count')},description='Repeated redispersion in pyridine and precipitation with hexane; cycle count, volumes and durations unspecified. Source reports phosphorus below AES detection after purification.',retained=True)
add(r,'store','storage','Store in anhydrous pyridine',['pyridine-particles','pyridine','n2'],'stored',depends=['exchange'],stage='storage',parameters={'temperature':Q(u='degC'),'duration':Q(u='day')},environment='Nitrogen',description='Store dispersed in anhydrous pyridine under nitrogen. Body reports several months of inert-gas stability, not an exact required storage duration.')
p=P(r,'overcoated','General isolated CdSe/ZnSe product',state_id='stored',linkage='explicit',notes=['This general recipe is not a unique quantified run or automatic assignment of every later figure.']);p['surface']=F('Pyridine after exchange');p['morphology']=F('Overcoated nanocrystals; sample-specific size and shape are in the separate characterization record',E(3,'Synthesis'))
r['quality']['experimental_outcome']='reported_product';r['quality']['missing_fields']+=['Exact seed size of the general procedure, shell target, absolute feed precursor amounts, feed concentration, delivered volume and growth time are unstated.','Flask size, stirring rate, inert pressure, ramp/cooling profile, workup volumes/centrifuge settings and cycle count are unstated.','Butanol isomer and optional nonane amount are unspecified.']
link(r,'solution-characterization','Solution and structural evidence','Multiple explicitly separated cohorts; no complete run-to-figure assignment inferred.');link(r,'seed-preparation','Upstream CdSe and TOPSe preparation','Only steps restated by this source; full cited protocol remains its own source.');records.append(r)

r=base('seed-preparation','CdSe seed and precursor preparation','procedure','Cited CdSe core preparation and purification')
r['material'].update(formula='CdSe',elements=['Cd','Se'],components=['CdSe'],architecture='single_material')
r['intended_target']['composition']=F('Size-selected CdSe nanocrystal seeds',SYN)
r['materials']=[M('cdme2','Dimethylcadmium','C2H6Cd','metal_precursor','precursor_preparation',MAT,notes=['Organometallics, Inc.; vacuum transferred. Charge not restated.']),M('selenium','Selenium','Se','upstream chalcogen source','precursor_preparation',MAT,notes=['Electronic grade,Aezar; used as received. No elemental selenium bottle is implied in the shell-growth feed.']),M('top','Trioctylphosphine','C24H51P','coordinating solvent','precursor_preparation',MAT,notes=['Fluka; used as received.']),M('topo','Trioctylphosphine oxide','C24H51OP','coordinating solvent','precursor_preparation',SYN,notes=['Source names TOP/TOPO core-growth medium; TOPO supplier/grade/charge not restated.']),M('topse','Trioctylphosphine selenide','C24H51PSe','stock solute','precursor_preparation',MAT),M('methanol','Methanol','CH4O','antisolvent','workup',MAT,notes=['Electronic grade,Mallinckrodt.']),M('hexane','Hexane','C6H14','dispersant','workup',MAT,notes=['HPLC grade,Mallinckrodt.'])]
r['stocks']=[stock('topse-stock','1.0 M TOPSe stock',['topse','top'],{'concentration':Q(1,'mol/L',MAT)},MAT,'Preparation cited to Murray etal.1993 reference10; exact quantities/preparation not repeated in this article.')]
add(r,'vacuum-transfer','vacuum_transfer','Vacuum transfer dimethylcadmium',['cdme2'],'purified-cdme2',MAT,stage='precursor_preparation',description='Pressure, time and transfer apparatus are not restated.')
add(r,'cited-core','cited_preparation','Prepare and size-select CdSe cores',['purified-cdme2','topo','top'],'raw-core',SYN,stage='precursor_preparation',description='Controlled growth of CdSe nuclei in TOP/TOPO according to reference10. The particular Murray selenium-precursor route is not selected here; the separately listed TOPSe stock is not asserted as an input to this core preparation. No exact Cd charge, injection temperature or growth time supplied here; the citation is not a new fully quantified recipe.')
add(r,'purify','repeated_precipitation','Purify and size-select the CdSe cores',['raw-core','methanol','hexane'],'selected-core',SYN,depends=['cited-core'],stage='fractionation',description='Repeated methanol precipitation/hexane redispersion followed by size-selective precipitation from hexane/methanol; volumes, cycles and selection thresholds not restated.',retained=True)
P(r,'seed','Purified size-selected CdSe seeds','CdSe',state_id='selected-core',linkage='explicit');r['quality']['missing_fields']+=['Full upstream CdSe and TOPSe recipes are cited rather than restated.']
r['context_links'].append({'label':'Murray et al.1993 source contribution','url':'../murray-1993-method-1.html','relation':'Reference10; source-specific historical recipes, not a license to fill unreported Danek quantities.'});records.append(r)

r=base('electrospray-dispersion','Nanocrystal dispersion for electrospray','procedure','Pyridine/acetonitrile dispersion preparation',architecture='composite')
r['material']['architecture']='unresolved'
r['intended_target']['composition']=F('Pyridine/acetonitrile dispersion of either bare CdSe or ZnSe-overcoated CdSe dots; not an embedded film',DISP)
r['materials']=[M('dots','Pyridine-capped CdSe or CdSe/ZnSe nanocrystals',None,'dispersed nanocrystals','precursor_preparation',DISP,notes=['Two alternatives; retain whether bare or overcoated.']),M('hexane','Hexane','C6H14','antisolvent','workup',DISP),M('pyridine','Pyridine','C5H5N','solvent','precursor_preparation',DISP,notes=['Anhydrous']),M('acetonitrile','Acetonitrile','C2H3N','electrospray cosolvent','precursor_preparation',DISP,notes=['Anhydrous,Aldrich; used as received.'])]
add(r,'pellet','precipitation_centrifugation','Collect the pyridine-capped dots',['dots','hexane'],'pellet',DISP,stage='workup',description='Precipitate with hexane, centrifuge and transfer into a glovebox. Settings and volumes unreported.',retained=True)
add(r,'redisperse','redispersion_filtration','Prepare the filtered pyridine dispersion',['pellet','pyridine'],'pyridine-dispersion',DISP,depends=['pellet'],stage='precursor_preparation',parameters={'filter_pore_size':Q(.2,'um',DISP),'cdse_concentration':Q(3,'mg/mL',DISP,approximate=True,basis='CdSe concentration in pyridine before acetonitrile dilution; not total core/shell mass')},description='Redisperse in anhydrous pyridine, filter with0.2µm PTFE and adjust CdSe concentration to about3mg/mL.')
add(r,'dilute','dilution','Dilute with acetonitrile',['pyridine-dispersion','acetonitrile'],'diluted',DISP,depends=['redisperse'],stage='precursor_preparation',parameters={'acetonitrile_excess':Q(2,'fold',DISP,basis='Source says two-fold excess; ratio basis not explicitly stated'),'final_concentration':Q(u='mg/mL',e=DISP)},description='Add two-fold excess of anhydrous acetonitrile for steady electrospray. Do not silently turn this into a measured final1mg/mL concentration.')
add(r,'degas','cyclic_vacuum_degassing','Degas the electrospray feed',['diluted'],'degassed',DISP,depends=['dilute'],stage='precursor_preparation',parameters={'cycles':Q(u='count',e=DISP,raw_text='several'),'pressure':Q(u='Torr',e=DISP)},environment='High-vacuum line',description='Source wording is several thaw–pump–freeze cycles. Exact count, pressure and temperature stages are not specified. Use custom liquid handling attached to ES-OMCVD reactor.')
P(r,'feed','Degassed electrospray feed',e=DISP,state_id='degassed',linkage='explicit');r['quality']['missing_fields']+=['Dispersion volumes, acetonitrile ratio basis, final concentration, exact freeze/pump/thaw cycle count and vacuum pressure are unreported.'];records.append(r)

for coated in [False,True]:
 key='overcoated-dot-film' if coated else 'bare-dot-film';name='ZnSe-overcoated' if coated else 'Bare'
 r=base(key,name+' CdSe dots in a ZnSe composite film','literature_protocol','Electrospray organometallic chemical vapor deposition (ES-OMCVD)',architecture='composite')
 r['materials']=[M('dots',name+' CdSe quantum dots','CdSe/ZnSe' if coated else 'CdSe','seed','synthesis',CVD,notes=['Prepared pyridine/acetonitrile dispersion; exact seed specimen and fraction vary between figure cohorts.']),M('pyridine','Pyridine','C5H5N','feed solvent','synthesis',DISP),M('acetonitrile','Acetonitrile','C2H3N','feed cosolvent','synthesis',DISP),M('h2se','Hydrogen selenide','H2Se','chalcogen_precursor','synthesis',MAT,notes=['Electronic grade,Solkatronic; used as received.']),M('dezn','Diethylzinc','C4H10Zn','metal_precursor','synthesis',MAT,notes=['Electronic grade,Texas Alkyls; used as received. Distinct material treatment from Aldrich solution-growth DEZn.']),M('h2','Hydrogen','H2','carrier gas','synthesis',MAT,notes=['Ultrahigh purity,Matheson; purified through palladium cell.']),M('glass','Degreased glass microscope slide',None,'substrate','precursor_preparation',CVD,notes=['Fisher; glass composition and degreasing reagent/procedure unspecified.']),M('palladium','Palladium','Pd','carrier purifier','precursor_preparation',MAT)]
 r['stocks']=[stock('dot-feed',name+' dot electrospray dispersion',['dots','pyridine','acetonitrile'],{},DISP,'Prepared by linked electrospray-dispersion procedure;3mg/mL CdSe applies before acetonitrile addition, not final feed concentration.')]
 add(r,'purify-h2','gas_purification','Purify hydrogen carrier',['h2','palladium'],'purified-h2',MAT,stage='precursor_preparation',description='Palladium-cell purification; purifier temperature/pressure not specified.')
 add(r,'load-glass','substrate_loading','Load degreased glass slides',['glass'],'loaded-glass',CVD,stage='precursor_preparation',description='Degreased microscope slides; cleaning procedure and slide dimensions unreported.')
 add(r,'base-layer','omcvd_layer','Grow the ZnSe base layer',['loaded-glass','dezn','h2se','purified-h2'],'base-coated',CVD,depends=['purify-h2','load-glass'],parameters={'dezn_flow':Q(1,'umol/min',CVD),'h2se_flow':Q(20,'umol/min',CVD),'pressure':Q(600,'Torr',CVD),'thickness':Q(.1,'um',CVD,approximate=True),'substrate_temperature':Q(u='degC',e=CVD,minimum=150,maximum=270,basis='Study-wide deposition range; specific reported variants are separate choices'),'duration':Q(u='min',e=CVD)},environment='Hydrogen carrier',description='Initial ZnSe matrix film grown by OMCVD. Gas-flow reference quantities are precursor molar flows. No individual layer growth rate/time stated.')
 add(r,'composite','electrospray_omcvd','Deposit the quantum-dot composite',['base-coated','dot-feed','dezn','h2se','purified-h2'],'composite-film',CVD,depends=['base-layer'],parameters={'dezn_flow':Q(1,'umol/min',CVD),'h2se_flow':Q(20,'umol/min',CVD),'electrospray_voltage':Q(4.5,'kV',CVD),'dispersion_flow':Q(17,'uL/min',CVD),'hydrogen_aerosol_flow':Q(1000,'sccm',CVD,basis='Hydrogen carrying aerosol; standard temperature/pressure convention not supplied'),'pressure':Q(600,'Torr',CVD),'thickness':Q(1,'um',CVD,approximate=True),'duration':Q(u='min',e=CVD)},environment='Hydrogen; reactor and electrospray at600Torr',description='Syringe-pump feed to positive capillary electrode; grounded ring counterelectrode.4.5kVdc atomizes dispersion; aerosol enters heated growth zone while ZnSe matrix grows. Substrate temperature follows selected source variant. Reactor geometry/electrode dimensions are cited to reference2a, not restated.')
 add(r,'cap-layer','omcvd_layer','Grow the ZnSe capping layer',['composite-film','dezn','h2se','purified-h2'],'sandwich-film',CVD,depends=['composite'],parameters={'thickness':Q(.1,'um',CVD,approximate=True),'pressure':Q(600,'Torr',CVD),'duration':Q(u='min',e=CVD)},environment='Hydrogen carrier',description='Terminate with a ZnSe cap to bury all quantum dots inside the matrix. Temperature follows deposition variant; final cooling/storage unreported.')
 for t in ([150,200,270] if coated else [150,200,250]):r['condition_options'].append({'id':'comparison-'+str(t),'label':f'Figures7/8 comparison film: {t}°C; '+('overcoated feed [ZnSe/CdSe]=0.4 as printed' if coated else 'bare CdSe feed'),'parameters':{'substrate_temperature':Q(t,'degC',E(6,'Figure7 caption')+E(7,'Figure8 caption'))},'evidence':E(6,'Figure7 caption')+E(7,'Figure8 caption')})
 p=P(r,'film',name+' CdSe dots in ZnSe matrix',e=CVD,state_id='sandwich-film',linkage='explicit',notes=['General film recipe; individual optical cohorts are in the linked characterization record. Three source temperature choices do not specify complete run IDs.']);p['morphology']=F('ZnSe base/composite/ZnSe cap on glass',CVD)
 r['quality']['experimental_outcome']='reported_product';r['quality']['missing_fields']+=['Exact feed specimen, final feed concentration, per-layer duration, cooling and storage conditions are unreported.','Electrode dimensions, reactor geometry and glass degreasing procedure not restated; apparatus reference2a not inspected here.','Depth-dependent5–60min dot thermal exposure is not a stated film deposition duration.','Highest-temperature comparison differs:250°C bare versus270°C overcoated.']
 link(r,'electrospray-dispersion','Feed preparation','Shared preparation for bare or overcoated dots; chemical identities retain separate product states.');link(r,'film-characterization','Composite-film properties','Distinct printed sample ratios and measurement temperatures are preserved.');records.append(r)

# Controls and a partial high-temperature variant do not become fully specified training runs.
for key,title in [('no-seed-control','ZnSe precursor reaction without CdSe nuclei'),('no-dezn-control','Comparative reaction without DEZn dosing'),('high-temperature-overgrowth','Higher-temperature ZnSe overgrowth')]:
 r=base(key,title,'protocol_variant' if key.endswith('control') else 'observation','Comparative solution-growth conditions')
 e=E(3,'Synthesis, comparative experiments')
 ids=[('top','Trioctylphosphine','C24H51P','solvent'),('topse','Trioctylphosphine selenide','C24H51PSe','chalcogen_precursor')]
 if key!='no-dezn-control':ids.append(('dezn','Diethylzinc','C4H10Zn','metal_precursor'))
 if key!='no-seed-control':ids.append(('cdse','CdSe nanocrystals','CdSe','seed'))
 r['materials']=[M(*x,e=e) for x in ids]
 if key=='no-seed-control':
  r['intended_target']['composition']=F('ZnSe-precursor products without CdSe seeds',e);r['material'].update(formula='ZnSe',elements=['Zn','Se'],components=['ZnSe'],architecture='unresolved')
  description='No CdSe nuclei: precursors react slowly to form white hexane-soluble precipitate. Authors propose a ZnSe analogue of small CdS/CdSe clusters; exact identity and size not measured here.'
 elif key=='no-dezn-control':
  r['material'].update(formula='CdSe',elements=['Cd','Se'],components=['CdSe'],architecture='single_material')
  r['intended_target']['composition']=F('CdSe particles without DEZn dosing; no ZnSe shell is assigned',e)
  description='Comparison omits DEZn dosing; used to argue the standard small absorption red shift was not caused by CdSe Ostwald ripening. Exact control time, temperature and concentrations are not independently stated.'
 else:description='At about200°C, initial approximately2nm blue shift is followed by a red shift. Authors interpret this as consistent with interface alloying; no independently quantified higher-temperature recipe or measured alloy structure is supplied.'
 add(r,'comparison','comparative_reaction',title,[m['id'] for m in r['materials']],'comparison-product',e,parameters={'temperature':Q(200,'degC',e,approximate=True) if key=='high-temperature-overgrowth' else Q(u='degC',e=e),'duration':Q(u='min',e=e)},description=description)
 P(r,'comparison','Comparative reaction product','Unassigned ZnSe-precursor product' if key=='no-seed-control' else 'CdSe-based particles',e,'comparison-product',notes=[description])
 if key=='no-seed-control':V(r,'absorption-band','comparison','absorption_band',Q(320,'nm',e),'UV/vis absorption',e,'Sharp band; tentative cluster analogy, not a measured1.5nm ZnSe size.')
 if key=='high-temperature-overgrowth':V(r,'initial-blue-shift','comparison','absorption_blue_shift',Q(2,'nm',e,approximate=True),'UV/vis absorption',e,'Initial stage near200°C; subsequent red shift unquantified.')
 r['quality']['missing_fields']+=['Control-specific amounts, feed profile, duration, full workup and exact specimen identity are not independently specified.'];records.append(r)

r=base('annealing-control','Annealing of a solution-deposited particle film','procedure','Helium annealing control')
e=E(4,'Structural Characterization and Figure4')
r['materials']=[M('dots','CdSe/ZnSe nanocrystals','CdSe/ZnSe','particle film precursor','precursor_preparation',e,notes=['[ZnSe/CdSe]=2.5; film deposited from solution, not an ES-OMCVD matrix composite.']),M('glass','Glass slide',None,'substrate','precursor_preparation',e),M('he','Helium','He','annealing gas','synthesis',e)]
add(r,'deposit','solution_deposition','Deposit the nanocrystal film',['dots','glass'],'as-deposited',e,stage='precursor_preparation',description='Solution-deposited film on glass; exact solution and deposition parameters not restated.')
add(r,'anneal','annealing','Anneal under helium',['as-deposited','he'],'annealed',e,depends=['deposit'],parameters={'duration':Q(30,'min',e,approximate=True),'temperature':Q(u='degC',e=e)},environment='Helium flux; flow and pressure unreported',description='Unresolved source conflict: body~400°C versus Figure4 caption~450°C. Do not turn this into a400–450°C interval or select one value.')
P(r,'before','Figure4a particle film',e=e,state_id='as-deposited');P(r,'after','Figure4b annealed particle film',e=e,state_id='annealed',notes=['Absorption blue shift interpreted by authors as alloying; Zn0.7Cd0.3Se bulk bandgap inFigure4 is calculated reference, not a measured refined structure.'])
for t,label in [(400,'Body text'),(450,'Figure4 caption')]:V(r,f'conflicting-temperature-report-{t}','after','conflicting_source_temperature_report',Q(t,'degC',e,approximate=True,basis=label+' report; conflicts with the other report; operative annealing temperature remains unresolved'),'Source text/caption comparison',e,'Conflicting reports for one annealing control, not alternative experimental recipes.')
r['quality']['conflicts'].append('Body~400°C versus Figure4caption~450°C; unresolved.');r['quality']['missing_fields']+=['Exact annealing temperature is conflicting; flow, pressure, ramp and film preparation parameters absent.'];records.append(r)

r=base('solution-characterization','Colloidal structure, composition and optical cohorts','observation','Source-specific characterization cohorts')
r['intended_target']['composition']=F('Contextual measured CdSe and CdSe/ZnSe cohorts',E(3,'Figures1–6'));r['quality']['missing_fields']+=['Cohort-to-general-recipe mapping is not a fully quantified run assignment.','No raw spectra, assigned absolute core/shell atomic structure or measured uniform shell thickness supplied.']
e=E(3,'Figure1 inset table and Synthesis');
for label,d,spread in [('a',4.0,12),('b',4.4,11),('c',5.0,13),('d',6.8,13)]:
 id='fig1-'+label;P(r,id,'Figure1 '+label+' growth-stage aliquot','CdSe' if label=='a' else 'CdSe/ZnSe',e,notes=['Stages of overgrowth, not four independent experiments. No stage-specific dose or elapsed time provided.'])
 V(r,id+'-size',id,'diameter',Q(d,'nm',e),'HRTEM',e,'Size table insideFigure1; ratio and uncertainty on mean not supplied.')
 V(r,id+'-spread',id,'relative_size_standard_deviation',Q(spread,'%',e,raw_text='s=±'+str(spread)+'%',basis='Printed relative distribution spread; not uncertainty of mean diameter'),'HRTEM',e)
e=E(3,'Synthesis')+E(4,'Figures2/3 and Structural Characterization');p=P(r,'structure-2p5','Figures2/3 overcoated particles, ratio≈2.5',e=e,notes=['Figure3 explicitly~6.8nm and~4.0nm reference; Figure2 is ratio2.5. No individually tracked particle identity inferred.']);p['phase']=F('Lattice fringes with possible peripheral disorder; exact core/shell phase assignment unresolved',e);p['morphology']=F('Slightly irregular particles',e)
V(r,'structure-ratio','structure-2p5','znse_to_cdse_ratio',Q(2.5,'',e,approximate=True,basis='XRF-based overall composition; not precursor dose'),'X-ray fluorescence',e)
V(r,'structure-size','structure-2p5','diameter',Q(6.8,'nm',e,approximate=True),'HRTEM',e)
V(r,'aspect','structure-2p5','aspect_ratio',Q(1.3,'',e,approximate=True),'HRTEM',e,'Reported for~6.8nm particles; not imposed on every growth-stage sample.')
P(r,'bare-xrd','Figure3b bare CdSe comparison','CdSe',E(4,'Figure3'));V(r,'bare-xrd-size','bare-xrd','diameter',Q(4,'nm',E(4,'Figure3'),approximate=True),'Source Figure3 sample designation',E(4,'Figure3'))
e=E(5,'Structural Characterization continuation');P(r,'aes-cohort','Surface/overall composition comparison',e=e,notes=['Specific core≈3.5nm cohort; match to optical4.8 aliquot is not explicitly established.'])
for id,prop,val,u,tech,status,basis in [('core-size','core_diameter',3.5,'nm','Source sample designation','reported','Approximate core size; method for this number not independently identified'),('bulk-ratio','overall_znse_to_cdse_ratio',4.8,'','X-ray fluorescence','reported','Whole-particle composition'),('surface-ratio','aes_znse_to_cdse_ratio',7.0,'','Auger electron spectroscopy','reported','Surface-sensitive apparent composition'),('escape-depth','auger_escape_depth',1,'nm','AES methodological estimate','reported','Approximate escape depth, not measured shell thickness'),('ideal-shell','symmetric_model_shell_thickness',1.3,'nm','Symmetric core/shell calculation','author_derived','Ideal symmetric model; low measured surface ratio suggests nonuniform coverage')]:V(r,id,'aes-cohort',prop,Q(val,u,e,approximate=id in ['core-size','escape-depth','ideal-shell'],status=status,basis=basis),tech,e)
e=E(5,'Optical Characterization, Figures5/6')
for label,ratio,yieldval in [('a',0,.05),('b',3.6,.4),('c',4.3,.4),('d',4.8,.3)]:
 id='optical-'+label;p=P(r,id,'Figures5/6 aliquot '+label,'CdSe' if not ratio else 'CdSe/ZnSe',e,notes=['Isolated at stages of a single preparation; exact aliquot dose/time unreported.']);p['batch_id']='danek1996-solution-optical-series';p['surface']=F('Pyridine',e)
 V(r,id+'-ratio',id,'znse_to_cdse_ratio',Q(ratio,'',e,basis='Sample composition; zero designates bare CdSe'),'Source optical cohort designation',e)
 V(r,id+'-yield',id,'photoluminescence_quantum_yield',Q(yieldval,'%',e,approximate=True),'PL relative to rhodamine590/methanol',e,'Room temperature, pyridine dispersion;480nm excitation. Caption values; body bare-particle range≈0–0.05%. Not TOP/TOPO-capped core yield.')
 V(r,id+'-ple-detection',id,'ple_detection_wavelength',Q(570,'nm',e),'Photoluminescence excitation spectroscopy',e,'Room temperature; spectra normalized to intensity at550nm. Detection setting is not an independently measured peak.')
 V(r,id+'-ple-normalization',id,'ple_normalization_wavelength',Q(550,'nm',e),'Photoluminescence excitation spectroscopy',e)
P(r,'optical-series','Shared solution optical trends',e=e,notes=['Trend-level quantities; no individual aliquot assigned to each shift.'])
for id,prop,v in [('abs-shift','absorption_red_shift',Q(4,'nm',e,approximate=True)),('pl-shift','emission_red_shift',Q(u='nm',e=e,minimum=2,maximum=4,approximate=True)),('stokes','stokes_shift',Q(10,'nm',e,approximate=True))]:V(r,id,'optical-series',prop,v,'Absorption and photoluminescence',e,'Shared optical cohort trend, not a fully enumerated run label.')
r['quality']['conflicts'].append('Initial size spread: Figure1 table±12%, body approximately10%; retain both.');r['quality']['conflicts'].append('Spectral and AES cohorts cannot be joined solely by common4.8 composition ratio.');records.append(r)

r=base('film-characterization','Optical cohorts of quantum-dot composite films','observation','Film photoluminescence and excitation spectroscopy',architecture='composite')
r['intended_target']['composition']=F('Separate CdSe-in-ZnSe composite film cohorts',E(6,'Figures7–11 discussion'));r['quality']['missing_fields']+=['No full per-film run matrix, exact core-size distribution or deposition duration is supplied.','Figures7/8 state shell ratio0.4;Figure10 states4.0. No unsupported correction or sample merge.','No numerical digitization of plotted traces performed.']
for coated in [False,True]:
 for t in ([150,200,270] if coated else [150,200,250]):
  id=('coated-' if coated else 'bare-')+str(t);e=E(6,'Figure7')+E(7,'Figure8');P(r,id,f'Figures7/8 '+('overcoated' if coated else 'bare')+f' feed, {t}°C film',e=e,notes=['Spectra measured at room temperature and10K; RT is not silently assigned a numerical300K setting. Physical specimen pairing acrossfigures not independently resolved.'])
  V(r,id+'-deposition',id,'film_deposition_temperature',Q(t,'degC',e),'Source ES-OMCVD condition',e)
  if coated:V(r,id+'-ratio',id,'feed_znse_to_cdse_ratio',Q(.4,'',e,basis='As printed in Figures7/8 captions; no decimal correction'),'Source caption',e)
  V(r,id+'-excitation',id,'pl_excitation_wavelength',Q(480,'nm',e),'Photoluminescence',e,'Both RT and10K spectra. Intensities/scaling factors are preserved in originalfigures; no fabricated absolute quantum yield.')
e=E(7,'Figure9');P(r,'fig9-bare','Figure9 bare-dot composite at200°C',e=e,notes=['Not definitively the same physical specimen as the200°C panel inFigures7/8.'])
for temp,det in [(300,554),(10,546),(10,710)]:V(r,f'fig9-detect-{det}','fig9-bare','ple_detection_wavelength',Q(det,'nm',e),'Photoluminescence excitation spectroscopy',e,f'{temp}K; film deposited at200°C.710nm selects deep-level emission; other settings select bandedge.')
e=E(7,'Figure10');P(r,'fig10-coated','Figure10 overcoated-dot composite at200°C',e=e,notes=['Distinct≈3.7nm initial cores and4.0 ratio; must not merge with0.4 captions.'])
V(r,'fig10-core','fig10-coated','initial_core_diameter',Q(3.7,'nm',e,approximate=True),'Source sample designation',e)
V(r,'fig10-ratio','fig10-coated','feed_znse_to_cdse_ratio',Q(4,'',e),'Source caption',e)
for temp,det in [(300,576),(10,570)]:V(r,f'fig10-detect-{det}','fig10-coated','ple_detection_wavelength',Q(det,'nm',e),'Photoluminescence excitation spectroscopy',e,f'{temp}K; film deposited at200°C; setting, not independently extracted PL peak.')
e=E(8,'Figure11 and accompanying discussion');P(r,'fig11-series','Figure11 passivation-thickness comparison',e=e,notes=['Two deposition temperatures200/260°C; symmetrical-shell model converts composition and core size to monolayers. No exact point table or run mapping supplied.'])
for t in [200,260]:r['condition_options'].append({'id':'fig11-'+str(t),'label':f'Figure11 film series at{t}°C','parameters':{'deposition_temperature':Q(t,'degC',e)},'evidence':e})
V(r,'fig11-excitation','fig11-series','pl_excitation_wavelength',Q(500,'nm',e),'Photoluminescence',e,'Figure11 uses500nm, not480nm.')
V(r,'thin-model','fig11-series','model_passivation_layer_count',Q(.6,'monolayer',e,approximate=True,status='author_derived',basis='Symmetric-shell geometry; no uniform experimental thickness demonstrated'),'Stoichiometry/core-size model',e,'Associated with greater-than-tenfold bandedge yield enhancement; do not read this as absolute yield.')
V(r,'thin-enhancement','fig11-series','relative_pl_enhancement',Q(10,'fold',e,qualifier='greater_than',basis='Relative to bare-dot composite;~0.6model monolayer'),'Photoluminescence',e)
V(r,'thick-model','fig11-series','model_passivation_layer_count',Q(3,'monolayer',e,approximate=True,status='author_derived',basis='Symmetric-shell geometry'),'Stoichiometry/core-size model',e)
V(r,'thick-enhancement','fig11-series','relative_pl_enhancement',Q(100,'fold',e,approximate=True,basis='Relative to bare-dot composite;~3model monolayers'),'Photoluminescence',e)
P(r,'film-trends','Study-level film trends',e=E(6,'Film synthesis discussion')+E(7,'Optical discussion'),notes=['Trend-level source findings; not exact individual-film run labels.'])
for id,prop,val,cond,e in [('bare-red','emission_red_shift',Q(10,'nm',E(6,'Film synthesis discussion'),approximate=True),'Bare dots, deposition150→200°C',E(6,'Film synthesis discussion')),('bare-return','emission_band_maximum',Q(550,'nm',E(6,'Film synthesis discussion'),approximate=True),'Bare dots, deposition250°C',E(6,'Film synthesis discussion')),('coated-rt-blue','emission_blue_shift',Q(4,'nm',E(6,'Film synthesis discussion'),approximate=True),'Overcoated, increasing deposition temperature; room-temperature PL',E(6,'Film synthesis discussion')),('coated-10k-blue','emission_blue_shift',Q(8,'nm',E(7,'Optical discussion'),approximate=True),'Overcoated, deposition150→270°C;10K PL',E(7,'Optical discussion')),('thermal-exposure','dot_thermal_exposure',Q(u='min',e=E(7,'Optical discussion'),minimum=5,maximum=60,approximate=True,basis='Depth-dependent particle thermal exposure during deposition; not deposition duration'),'Embedded dots experience different time histories',E(7,'Optical discussion'))]:V(r,id,'film-trends',prop,val,'Source optical discussion',e,cond)
r['quality']['conflicts'].append('250°C bare versus270°C coated at highest-temperature comparison; not identical temperatures despite broad text description.');records.append(r)

r=base('characterization','Characterization preparation and acquisition','procedure','Optical, compositional and structural characterization')
r['materials']=[M('sample','CdSe/CdSe-ZnSe particle or film specimen',None,'sample','characterization',OPT,notes=['Sample state differs by method; these are independent aliquots, not a serial preparation.']),M('pyridine','Pyridine','C5H5N','sample solvent','characterization',COMP),M('rhodamine590','Rhodamine590 fluorescence standard',None,'PL standard','characterization',OPT,notes=['Source trade/designation only; do not infer exact salt/CAS without verification.']),M('methanol','Methanol','CH4O','standard solvent','characterization',OPT),M('si-wafer','Silicon wafer','Si','XRF/XRD support','characterization',COMP+XRD,notes=['XRD support explicitly(100); XRF support orientation not given.']),M('cdse-standard','CdSe powder','CdSe','XRF standard','characterization',COMP,notes=['99.99%,Alfa.']),M('znse-standard','OMCVD ZnSe film','ZnSe','XRF standard','characterization',COMP,notes=['Grown in authors laboratory; standard-specific recipe not restated.']),M('nickel','Nickel','Ni','TEM grid','characterization',MIC),M('carbon','Carbon','C','TEM grid/overcoat','characterization',MIC),M('helium','Liquid helium','He','cryostat coolant','characterization',OPT),M('chromium','Chromium','Cr','XRF generator anode','characterization',COMP),M('copper','Copper','Cu','XRD anode/radiation source','characterization',XRD)]
specs=[('abs','uv_vis_spectroscopy','UV/vis absorption',['sample'],OPT,{},'Hewlett-Packard8452 diode-array spectrometer; sample-specific solvent/state retained separately.'),('pl','photoluminescence_spectroscopy','PL and excitation spectra',['sample','rhodamine590','methanol'],OPT,{},'Spex Fluorolog-2, front-face collection. Correct PMT response and excitation spectral flux with experimentally determined factors. Absolute dispersion PL yield estimated against rhodamine590 in methanol; integrated intensities, no extrapolated film absolute yield.'),('cryostat','cryogenic_spectroscopy','Low-temperature film PL',['sample','helium'],OPT,{},'Janis liquid-helium cryostat;10K where specified infigures. Relative film yield from bandedge emission, excitation absorption estimated with transmitted backside light measured by Oriel silicon photodiode.'),('xrf','x_ray_fluorescence','Overall Zn/Cd composition',['sample','pyridine','si-wafer','cdse-standard','znse-standard','chromium'],COMP,{},'Evaporate a few pyridine-dispersion droplets onSi. DianoV generator withCr anode;HNU Si:Li detector. ZnSe film andCdSe powder standards. Not a surface-selective measurement.'),('aes','auger_spectroscopy','Surface-sensitive composition',['sample'],COMP,{'primary_beam_energy':Q(5,'keV',COMP)},'Perkin-Elmer AES microprobe Model660. Escape depth~1nm is methodological estimate; phosphorus below detection after ligand exchange, numeric detection limit absent.'),('tem','transmission_electron_microscopy','High-resolution TEM',['sample','pyridine','nickel','carbon'],MIC,{'accelerating_voltage':Q(200,'kV',MIC)},'Topcon EM002B. Place drop of diluted pyridine dispersion on nickel/carbon grid, short contact then rinse excess with solvent; solvent identity not restated. Carbon overcoat improves electron-beam stability. Contact time, concentration, overcoat thickness unreported.'),('xrd','x_ray_diffraction','Powder X-ray diffraction',['sample','si-wafer','copper'],XRD,{},'Rigaku300 rotating anode, Bragg configuration,Cu Kα. Spread thin precipitated-particle layer on(100)Si. Figure3 bulk wurtzite line references are not a solved core/shell structure.')]
for oid,action,label,inputs,e,parameters,description in specs:add(r,oid,action,label,inputs,None,e,parameters=parameters,stage='characterization',branch='independent_measurement',description=description)
r['quality']['missing_fields']+=['Sample-by-sample microscopy/optical/composition identity links, full instrument scan settings, numeric AES detection limit and calibration raw data are not supplied.'];link(r,'solution-characterization','Colloidal measurements','Cohort-specific outcomes are separated from acquisition.');link(r,'film-characterization','Film measurements','Film states and detection settings remain separate.');records.append(r)

# Detach shared helper evidence lists before adding field-specific locators.
# JSON round-trip deliberately breaks Python object aliases between scientific fields.
records=json.loads(json.dumps(records))
errors=[]
for r in records:
 if r['record_id']=='danek-1996-electrospray-dispersion':
  r['products'][0]['composition']=F('Either bare CdSe or ZnSe-overcoated CdSe in pyridine/acetonitrile; alternative feeds, not a claimed mixture',DISP)
 if r['record_id']=='danek-1996-characterization':
  r['material']['architecture']='unresolved'
  r['intended_target']['composition']=F('Separate bare CdSe, overcoated CdSe/ZnSe and embedded-film specimens; characterization context, not a synthesis target',OPT+COMP+MIC+XRD)
 if r['record_id']=='danek-1996-annealing-control':
  r['material']['architecture']='unresolved'
  r['intended_target']['composition']=F('Annealed film of CdSe/ZnSe particles; final architecture not established after author-interpreted alloying',E(4,'Structural Characterization and Figure4'))
 # Preserve the author's size wording without manufacturing a spherical diameter.
 for m in r['measurements']:
  m['property']={'diameter':'particle_size','core_diameter':'core_size','initial_core_diameter':'initial_core_size'}.get(m['property'],m['property'])
  if m['property']=='photoluminescence_quantum_yield':m['evidence']+=OPT
 if r['record_id']=='danek-1996-znse-overgrowth':
  for m in r['materials']:m['evidence']+=MAT
  for o in r['operations']:
   if o['id'] in ['heat','dose']:o['evidence']+=E(3,'Synthesis')
   if o['id'] in ['exchange','store']:o['evidence']+=E(4,'Purification and storage discussion')
 if r['record_id']=='danek-1996-characterization':
  for o in r['operations']:
   if o['id']=='aes':o['evidence']+=E(4,'Purification discussion')+E(5,'Structural Characterization continuation')
   if o['id']=='cryostat':o['evidence']+=E(7,'Figures8–10')
   if o['id']=='xrd':o['evidence']+=E(4,'Figure3')
 errors+=validate_record(r)
 assert not any(x['eligible'] for x in eligibility(r).values())
 (OUT/(r['record_id']+'.json')).write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert len(set(build_groups(records).values()))==1
manifest=json.loads((B/'source-manifest.json').read_text(encoding='utf-8'))
for page in manifest['pages']:page.update(text_reviewed=True,visual_reviewed=True,render_file=f"main-{page['pdf_page']}.png")
manifest['review_scope']='Root read all eight supplied main pages in text and rendered form. Matching SI not located or verified.'
(B/'source-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
report={'status':'passed' if not errors else 'failed','records':[{'record_id':r['record_id'],'type':r['record_type'],'sha256':hashlib.sha256((OUT/(r['record_id']+'.json')).read_bytes()).hexdigest(),'measurements':len(r['measurements'])} for r in records],'errors':errors,'scope':'Private source-linked canonical drafts; independent scientific audit and all reader integration pending','published':False}
(B/'records-validation.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':report['status'],'records':len(records),'measurements':sum(len(r['measurements']) for r in records),'errors':errors}))
if errors:raise SystemExit(1)
