import json,hashlib,subprocess,concurrent.futures
from pathlib import Path
from PIL import Image
OUT=Path(__file__).parent
BASE=OUT.parents[2]
POP='[local path redacted]'
DOI='10.1021/acsnano.8b05032'
TITLE='Chemistry of Shape-Controlled Iron Oxide Nanocrystal Formation'
def write(name,obj):(OUT/name).write_text(json.dumps(obj,indent=2,ensure_ascii=False),encoding='utf-8')
sections={
'main':[
 ['Title/authors/affiliations','Abstract and graphical abstract','Introduction'],
 ['Figure 1 MALDI isotope assignments and temperature series','Introduction continued','Results: Iron sources and influence on iron oleate'],
 ['Figure 2 proposed redox mechanisms and air-control GC','Iron-source comparisons','Carbonate source formation','MALDI composition and MS/MS'],
 ['Figure 3 morphology and inert XRD','Mixed-valence complex redox discussion','Gas release/consumption controls','Thermal window and proposed network formation'],
 ['Enhanced size and shape control','Figures 4 and 5 TEM/SEM/STEM/tomography','Pristine versus stored/oxidized samples'],
 ['Figure 6 facet analysis and explanatory models','Figure 7 EELS reference/sample spectra and spectrotomography'],
 ['Figure 8 time/temperature morphology trajectory','Facet interpretation','Spatial phase/oxidation analysis','Magnetic discussion'],
 ['Magnetic discussion continued','Growth mechanism and dilution discussion','Conclusion','Materials','General Schlenk/solvent conditioning','Fe(II) carbonate preparation'],
 ['Fe(III) carbonate preparation','CO2 composition assay','Fe(II) and Fe(III) oleate preparations','General nanocrystal synthesis','MALDI methods and purity control','GC','TEM/HRTEM','HAADF-STEM','Electron tomography','EELS tomography','SEM'],
 ['SEM continuation','XRD','VSM','Associated Content','Author details/acknowledgments','References 1–21'],
 ['References 22–51']
],
'si':[
 ['Matching title/authors/affiliations'],['Iron source preparation 1.1 and 1.2','Equations 1 and 2','Figure S1'],['Figure S2','Oleate preparation 2.1','Equation 3'],['Figure S3','Oleate preparation 2.2','Equations 4–6'],['Figure S4','Nanocrystal apparatus Figure S5'],['MALDI spectra Figure S6','MS/MS Figure S7'],['OA purity comparison Figure S8','Isotope-distribution model with LA Figure S9'],['GC oxygen release Figure S10'],['OA-only air control Figure S11','Partial post-synthetic surface oxidation'],['HAADF-STEM/FFT Figure S12'],['SEM Figure S13','Size/shape control text'],['Dilution/time condition matrix Figure S14'],['Star TEM Figure S15','Cubic growth window'],['Cubic TEM Figure S16','Alternative high-ODE Fe:OA series'],['Fe:OA series Figure S17','Time evolution Figure S18','Size/shape control text'],['Control text continuation','Magnetic Figure S19'],['Exchange bias/transition interpretation and thermal-offset warning','Magnetic Figure S20'],['Magnetic Figure S21','Blocking/transition discussion'],['Magnetic discussion continued; vortex speculation','SI references 1–5']
]}
conflicts=[
 {'id':'C01','locators':['Main p.159 FeCO3 source method'],'issue':'16.40 g and 157.7 mmol Na2CO3 disagree for anhydrous sodium carbonate.','resolution':'Retain both reported numbers; no correction or derived concentration.'},
 {'id':'C02','locators':['Main p.160 Fe(II) Oleate'],'issue':'5.69 g and 51.4 mmol FeCO3 disagree for nominal FeCO3.','resolution':'Retain source pair and flag; no silent replacement.'},
 {'id':'C03','locators':['Main p.160 Fe(III) source method','SI p.2 eq2'],'issue':'Main prints Fe2(SO4)3·H2O, SI uses xH2O, and 15.90 g/39.76 mmol corresponds approximately to anhydrous rather than monohydrate.','resolution':'Hydration unresolved; no recalculated pure Fe loading.'},
 {'id':'C04','locators':['Main p.160 CO2 assay','Main p.160 Fe(III) Oleate'],'issue':'Prepared Fe(III) source is estimated 16% Fe2(CO3)3 with remainder probably hydroxide/oxyhydroxide, yet its charge has nominal carbonate mass/mmol.','resolution':'Treat as mixed source; 16% basis unspecified; no pure carbonate assumption.'},
 {'id':'C05','locators':['Main p.156 tomography body','Main p.160 Electron Tomography'],'issue':'Body reports tilt range ±76 degrees; Methods reports −74 to +74 degrees in 2-degree increments.','resolution':'Preserve both under their own locators.'},
 {'id':'C06','locators':['Main p.158 EELS body','Main p.160 EELS Tomography'],'issue':'Body says 15 EELS data cubes; endpoints −65 to +65 with 10-degree increments give 14 nominal positions.','resolution':'Actual angle sequence not recoverable; no inferred extra view.'},
 {'id':'C07','locators':['Main p.159 dilution discussion','SI p.14 Fe:OA series'],'issue':'Main says highest dilution 66 vol% ODE suppresses stars; SI specifies greater than 66 vol% for the stoichiometry series.','resolution':'Keep main threshold discussion separate from the SI alternative series; exact series dilution unknown.'},
 {'id':'C08','locators':['Main p.161 VSM methods','SI p.18 Figure S21'],'issue':'Main states 5–350 K measurements; S21 plot extends to 400 K and text gives cubic blocking temperature about 400 K.','resolution':'Retain figure-specific axis extent and reported estimate, flag scope conflict; no extrapolated numerical curve data.'},
 {'id':'C09','locators':['SI p.6 Figure S7 plot/caption','Main p.154 MS/MS discussion'],'issue':'Plotted neutral spacing annotated 281.69 Da, while caption/main identifies oleate as 281.24 Da.','resolution':'Retain both labels and source locations; use no silently harmonized mass.'},
 {'id':'C10','locators':['SI p.18 Figure S21 caption','SI p.12 Figure S14'],'issue':'S21 calls smaller particles "smaller ODE dilution", whereas S14 shows smaller sizes at higher ODE vol%.','resolution':'Magnetic samples remain unassigned to exact dilution/size.'},
 {'id':'C11','locators':['SI p.18 Figure S21 upper-right/lower-right panels'],'issue':'Upper-right field axis is labeled Oe, lower-right is kOe; apparent unit inconsistency cannot be settled from plot alone.','resolution':'Preserve original axes; do not convert or digitize field values across panels.'},
 {'id':'C12','locators':['SI p.9 section 6'],'issue':'Text cites Figure S11 for the high-resolution image; the actual image and FFT are Figure S12.','resolution':'Use S12, with original cross-reference typo recorded.'},
 {'id':'C13','locators':['Main p.160 general synthesis','SI pp.12–15 growth observations'],'issue':'General method holds 3–5 h; sampled morphology windows end at 40–60 min and Figure8 at56min after nucleation.','resolution':'Different scopes, not necessarily a contradiction; never concatenate full hold after an aliquot.'},
 {'id':'C14','locators':['Main p.155 Figure3a','SI p.12 FigureS14'],'issue':'Figure3a uses34 vol% ODE, while the SI matrix has30 vol%.','resolution':'Distinct conditions; no merging or transferring size labels.'},
 {'id':'C15','locators':['SI p.9 phase discussion'],'issue':'Authors use a common Fd-3m/cubic description and lattice parameters8.33/8.36 Å to discuss magnetite/maghemite indistinguishability. This is a cited comparison, not a refinement of every sample.','resolution':'Do not promote it to sample-resolved space-group or lattice labels; retain FFT ambiguity.'}
]
page_conflicts={'main':{5:['C05'],7:['C06'],8:['C01','C07'],9:['C02','C03','C04','C05','C06','C13'],10:['C08']},'si':{2:['C03'],6:['C09'],9:['C12','C15'],12:['C14'],14:['C07','C13'],18:['C08','C10','C11']}}
docs=json.loads((OUT/'document-inventory.json').read_text())
for d in docs:
    d['identity_verified']=True;d['identity_evidence']='Title and complete author list match; main DOI and Associated Content identify a supporting PDF covering these exact sections.'
    for p in d['pages']:
        n=p['page'];p['text_read']=True;p['visual_review']=True;p['sections']=sections[d['role']][n-1];p['unresolved']=page_conflicts[d['role']].get(n,[])
        p['review_scope']='Full page text and full-page rendering inspected; figures, captions, axes, labels and equations included.'
write('document-inventory.json',docs)

# Coordinates are fractions of the complete source page, top-left origin.
# Crops include entire panels, axes and captions; source content is not redrawn.
figrows=[
 ('graphical-abstract','main',1,[.50,.445,.89,.583],'Conceptual abstract graphic linking iron-oleate complexes, redox/FeO monomers and shape transformation.','author mechanism graphic plus microscopy','No specimen-level recipe assignment.',['10 nm scale bars; mechanistic arrows are explanatory, not a measured trajectory.']),
 ('figure-1','main',2,[.09,.08,.905,.477],'Measured isotope envelopes and calculated complex assignments; relative MALDI peak areas during heating for Fe(II)- and Fe(III)-source oleates.','MALDI-TOF MS + isotope calculations','Separate Fe(II)/Fe(III) analytical reaction series; not final NC products.',['Initial complex formation60 C; S/N>5.','Assigned m/z:955.6,1308.7,1590.0,1871.2,1927.2,2208.4,2561.6,2842.9.','Relative-area curves not digitized; displayed marker temperatures not substituted for a complete timed thermal protocol.']),
 ('figure-2','main',3,[.09,.08,.905,.34],'Proposed reductions through complex oxygen/water oxidation and GC of an air-atmosphere control.','mechanism schemes + GC control','Air-control experiment distinct from nitrogen synthesis.',['Panelc shows N2,O2,CO,CO2 integrated peak areas vs temperature.','Formulas are observed positive ions, described as losing one oleate; not neutral stock formulas.']),
 ('figure-3','main',4,[.09,.08,.905,.279],'Star/cubic TEM examples under different OA/ODE concentrations and inert sealed-capillary XRD from either iron source.','TEM + XRD','3a34vol%ODE stars;3b8vol%ODE cubes;3c separate Fe(II)/Fe(III) pristine XRD aliquots.',['Fe:OA1:7 for both TEM examples.','3a66vol%OA/34vol%ODE;3b92vol%OA/8vol%ODE.','Wustite reference00-006-0615.100nmTEM scale; no sample size stated.']),
 ('figure-4','main',5,[.09,.463,.485,.935],'TEM gallery showing accessible star and cubic nanocrystal morphologies.','TEM gallery','Gallery panels lack a printed per-panel condition or size assignment.',['Eight image groups; do not assign size from scale bars or match visually to other panels as batch identity.']),
 ('figure-5','main',5,[.515,.25,.905,.653],'TEM,70-degree-tilted SEM,STEM and electron-tomography reconstruction identify eight triangular pods.','TEM/SEM/STEM/tomography','Octapod sample; exact recipe branch and run unassigned.',['SEM tilt70 degrees;30nm scale bars.','Eight triangular pods; body tilt±76 vs Methods±74degrees unresolved.']),
 ('figure-6','main',6,[.09,.08,.905,.348],'High-resolution pod projection, its FFT, facet models and an intensity profile support a triangular pod with stepped facets.','HAADF-STEM + FFT + explanatory facet models','Partially air-oxidized octapod; distinct from pristine XRD.',['[110]projection;growth[111];side facets{113},modeled(100)/(111)terraces.','2nm scale; FFT is not SAED; schematic atom positions are not measured coordinates.']),
 ('figure-7','main',6,[.09,.355,.905,.893],'Reference and particle EELS spectra, line profiles, reconstructed slices and3D valence distributions of an oxidized octapod.','EELS/direct spectroscopic tomography','Oxidized octapod; Figure6and7 degree of oxidation may differ.',['Reference Fe2+ from FeTiO3 and Fe3+ from hematite, citedref32.','Fe2+-rich interior/Fe3+-rich exterior;50nm bars.','15 data cubes stated; phase interpretation wustite core/maghemite exterior with possible magnetite/mixed intermediate. No numeric phase fraction.']),
 ('figure-8','main',7,[.09,.08,.905,.49],'Microscopy plus author schematic of post-nucleation star formation and transformation toward cubes.','TEM trajectory + mechanistic schematic','Fe:OA1:7,8vol%ODE trajectory; not four independently synthesized batches.',['0.5min331C;2min331C;8min339C;56min341C (all directly printed).','50nm scale bar. Four phases denote morphological stages, not four crystallographic phases.'])
]
sirows=[
 (1,2,[.11,.323,.91,.75],'Photographs of FeCO3 precipitation, Schlenk filtration and washed wet precursor.','precursor preparation','Fe(II)carbonate route',['Four water washes; no image-derived reactor volume.']),
 (2,3,[.11,.175,.91,.58],'Fe(III)-source precipitation and washing photographs.','precursor preparation','Nominal Fe(III)carbonate mixed with hydroxide/oxyhydroxide',['Schlenk frit;four washes.1L marking is visible on one photographed flask, not a universal reactor specification.']),
 (3,4,[.11,.088,.91,.385],'Fe(II)-source oleate emulsion before and after drying.','precursor preparation','Fe(II)-carbonate-derived oleate mixture',['Drying removes water; no final volume inferred from vessel markings.']),
 (4,5,[.11,.092,.91,.397],'Fe(III)-source oleate emulsion before and after drying.','precursor preparation','Fe(III)-source oleate mixture',['Visual color change; no quantitative speciation from photograph.']),
 (5,5,[.11,.453,.91,.905],'Photograph of the typical nanocrystal synthesis apparatus.','apparatus','Generic NC method',['Three-neck flask,Vigreux/distillation columns,heating mantle visible. Readout and flask markings do not define each run.']),
 (6,6,[.11,.16,.93,.39],'Representative Fe(II)-source oleate MALDI mass spectrum.','MALDI-TOF MS','Analytical Fe(II)-source oleate sample',['Displayed peak955.617;other labeled peaks1027.532,1236.855,1308.772,1590.055,1871.291,1927.207,2208.481,2561.618,2842.961; intensities not digitized.']),
 (7,6,[.11,.47,.93,.735],'MS/MS fragmentation of the955.6ion assigned to FeII2(oleate)3+.','tandem mass spectrometry','Analytical precursor ion, not NC size/phase',['Caption:oleate281.24Da and FeOA337.18Da. Plot annotation281.69Da differs.']),
 (8,7,[.11,.125,.91,.425],'Technical-grade and pure-oleic-acid isotope envelopes compared with simulations.','MALDI purity control','Distinct analytical preparations using technical vs pure OA',['Technical-grade impurities add low-mass peaks; no selected NC grade inferred.']),
 (9,7,[.11,.475,.91,.897],'A10%linoleic-acid component improves the calculated isotope-envelope fit.','calculation/model comparison','Model of impurity in technical OA; not an added reagent recipe',['10%LA is a model fraction consistent with supplier information, not an independently measured composition for every OA bottle.']),
 (10,8,[.11,.128,.91,.73],'Gas chromatogram of Fe(III)-source oleate at60C with oxygen and nitrogen peaks.','GC','Anaerobic preparation analytical headspace with O2release',['O2RT0.76,area4.85%;N2RT0.92,area95.1%. Axis labelmin:sek retained; retention-time unit encoding not normalized.']),
 (11,9,[.11,.09,.91,.517],'Oleic-acid-only air control shows oxygen consumption on heating.','GC control','Pure OA in closed flask under air; no iron',['Consumption increases above140C; curve not digitized.']),
 (12,10,[.11,.087,.91,.54],'High-resolution octapod STEM and FFTs of core and edge after routine purification.','HAADF-STEM + FFT','Partially oxidized octapod; exact recipe unassigned',['Core FFT [100]wustite;edge[100]magnetite and/or maghemite;5nm scale.','These are FFTs, not an acquired SAED pattern.']),
 (13,11,[.11,.131,.91,.58],'Tilted SEM at different magnifications and an untilted overview of octapods.','SEM','Octapod sample associated with Figure5; exact recipe unspecified',['Panel bars20,100,200,100nm; tilt angle70degrees documented for mainFigure5, not individually restated for these panels.']),
 (14,12,[.11,.085,.91,.64],'Condition matrix of ODE dilution and post-nucleation time at Fe:OA1:7.','condition schematic','Four dilution families with overlapping time windows; no physical batch IDs',['ODE0,8,30,56vol%;windows2–6,3–10,5–15,40–60min.','Sizes by row:0%82/75/45/60nm;8%45/38/37/40nm;30%37/32/31/28nm;56%21/22/21/23nm.','Source calls these sizes; geometrical definition, spread and counts absent.']),
 (15,13,[.11,.087,.91,.745],'TEM of stars in the2–6min window, corresponding to the condition matrix.','TEM','Links to FigureS14 by caption and printed sizes',['Upper-left21nm=56%ODE;upper-right37nm=30%;lower-left45nm=8%;lower-right82nm=noODE.','The mapping is via printed size labels and S14; no invented per-particle measurements.']),
 (16,14,[.11,.087,.91,.772],'TEM of cubes in the40–60min window corresponding to the condition matrix.','TEM','Links to FigureS14 by caption and printed sizes',['Upper-left23nm=56%ODE;upper-right28nm=30%;lower-left40nm=8%;lower-right60nm=noODE.']),
 (17,15,[.11,.087,.91,.43],'Cubic morphology and size as Fe:OA ratio varies in high ODE dilution.','TEM/stoichiometry schematic','Alternative series, greater than66vol%ODE; exact amount,T,time and source branch unknown',['Fe:OA1:2.5→7.5nm±10.2%;1:4→8.5nm±9.0%;1:5→13.3nm±4.8%;1:7→21.5nm±6.0%.','Relative spread statistic not defined; not diameter labels.']),
 (18,15,[.11,.483,.91,.83],'TEM aliquot series shows octapod-to-cubic transformation at8vol%ODE and Fe:OA1:7.','TEM time series','Related trajectory; aliquot volumes and same-batch linkage identifiers absent',['Times0.5,2,4,8,13,19,56min.','No numeric sizes assigned; only four temperatures directly available in mainFigure8.']),
 (19,16,[.11,.246,.91,.842],'Magnetization of stars resembling the main Figure3a sample.','VSM','Similar to Figure3a, not explicitly the same physical batch',['20kOefield-cooled isotherms;5,100,150,250,300,350K plotted.','Exchange bias disappears above200K; literature transition lines are not measured exact transition temperatures.']),
 (20,17,[.11,.351,.91,.727],'Magnetization of cubes resembling Figure3b, including50OeZFC warming.','VSM','Similar morphology to Figure3b; exact recipe/size unassigned',['50K and300K hysteresis panels;remanence/coercivity still nonzero at300K.','Temperature offsets attributed to cryostat/sample lag; sweep rate not reported.']),
 (21,18,[.11,.098,.91,.63],'Magnetization of smaller stars(top)and cubes(bottom)under multiple fields.','VSM','No exact dilution,size or batch identifiers; caption dilution wording ambiguous',['ZFC field labels10kOe,7.5kOe,5kOe,3kOe,2kOe,1kOe,750,500,400,300,200,100Oe.','Stars5K/300K isotherms; cubes10K,10K-exchange,300K.','Stars blocking<300K;cubes around400K as reported. Actual plots reach400K despite mainmethod350K ceiling. Upper-right field axis says Oe, lower sayskOe.'])
]
for num,page,box,caption,category,sample,facts in sirows:figrows.append((f'figure-s{num}','si',page,box,caption,category,sample,facts))

figures=[]
for fid,role,page,box,caption,cat,sample,facts in figrows:
    figures.append({'id':fid,'document_role':role,'page':page,'printed_page':151+page if role=='main' else page,'caption_paraphrase':caption,'category':cat,'sample_links':[{'scope':sample,'link_status':'source_context_only_unless_condition_explicit','physical_batch_id':None}],'quantitative_facts':facts,'reviewed':True,'review_scope':'Full figure including axes, all panels, source caption and surrounding discussion.','eligible_training':False,'eligibility_note':'Standalone characterization figures are not independent recipe labels; canonical records preserve only explicitly bounded condition observations.','crop_box_fraction':box,'original_crop_asset':str(OUT/'crops'/f'{fid}.png'),'source_locator':f'{role} PDF p.{page}, '+fid.replace('-',' ')})

equations=[
 {'id':'si-equation-1','page':2,'box':[.12,.198,.89,.229],'expression':'FeSO4·7H2O + Na2CO3 -> FeCO3(s) + Na2SO4 + 7H2O','scope':'Formal Fe(II) precipitation stoichiometry.'},
 {'id':'si-equation-2','page':2,'box':[.12,.855,.89,.901],'expression':'Fe2(SO4)3·xH2O + 3Na2CO3 -> Fe2(CO3)3(s) + 3Na2SO4 + xH2O','scope':'Formal nominal Fe(III) carbonate equation; actual precipitate mixed.'},
 {'id':'si-equation-3','page':3,'box':[.12,.738,.89,.773],'expression':'FeCO3 + 2RCOOH -> [Fe2+(RCOO-)2] + CO2 + H2O','scope':'Formal reaction; not proof of a single stock molecular species.'},
 {'id':'si-equation-4','page':4,'box':[.12,.521,.89,.551],'expression':'Fe2(CO3)3 + 6RCOOH -> 2[Fe3+(RCOO-)3] + 3CO2 + 3H2O','scope':'Formal nominal carbonate route.'},
 {'id':'si-equation-5','page':4,'box':[.12,.56,.89,.589],'expression':'FeO(OH) + RCOOH -> [Fe3+O(RCOO-)] + H2O','scope':'Reaction of oxyhydroxide present in Fe(III) source.'},
 {'id':'si-equation-6','page':4,'box':[.12,.598,.89,.627],'expression':'Fe(OH)3 + 3RCOOH -> [Fe3+(RCOO-)3] + 3H2O','scope':'Reaction of hydroxide present in Fe(III) source.'}
]
for eq in equations:eq.update(reviewed=True,document_role='si',original_crop_asset=str(OUT/'crops'/(eq['id']+'.png')))

# Original crops, without generative editing or plot digitization.
(OUT/'crops').mkdir(exist_ok=True);(OUT/'highres').mkdir(exist_ok=True)
jobs=sorted({(f['document_role'],f['page']) for f in figures}|{('si',e['page']) for e in equations})
def render(job):
    role,page=job;pdf=next(d['source_path'] for d in docs if d['role']==role);target=OUT/'highres'/f'{role}-{page:02}'
    if not target.with_suffix('.png').exists():subprocess.run([POP,'-f',str(page),'-l',str(page),'-singlefile','-r','240','-png',pdf,str(target)],check=True,capture_output=True)
with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:list(pool.map(render,jobs))
manifest=[]
for f in figures+equations:
    role=f['document_role'];page=f['page'];im=Image.open(OUT/'highres'/f'{role}-{page:02}.png');box=f.get('crop_box_fraction',f.get('box'));pixels=[round(v*(im.width if i%2==0 else im.height)) for i,v in enumerate(box)]
    dest=Path(f['original_crop_asset']);im.crop(tuple(pixels)).save(dest)
    doc=next(d for d in docs if d['role']==role)
    manifest.append({'id':f['id'],'source_path':doc['source_path'],'source_sha256':doc['sha256'],'page':page,'render_dpi':240,'coordinate_origin':'top-left','full_render_size_pixels':[im.width,im.height],'crop_box_pixels':pixels,'crop_path':str(dest),'crop_sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'transformation':'Faithful rectangular crop of Poppler page rendering; no resizing/redrawing or intensity adjustment.','rights':'Source article/figure rights remain separate; research review asset, not a claim of open-license reuse.'})
write('crop-manifest.json',manifest)

canonical=json.loads((OUT/'canonical-summary.json').read_text())
rid=lambda s:'feld-2019-'+s
recipe_inventory=[
 {'id':'feii-carbonate','label':'Fe(II) carbonate precipitation','record_ids':[rid('fe2-carbonate-to-oleate-preparation')],'status':'encoded_in_precursor_procedure','source_locators':['Main p.159','SI pp.2–3 eq1/FigS1'],'gaps':['Slow-addition rate, recovered mass/yield, salt-conditioning time; Na2CO3 mass/mmol conflict.']},
 {'id':'feiii-source','label':'Nominal Fe(III) carbonate/hydroxide/oxyhydroxide source','record_ids':[rid('fe3-carbonate-to-oleate-preparation')],'status':'encoded_in_precursor_procedure','source_locators':['Main p.160','SI pp.2–3 eq2/FigS2'],'gaps':['Hydration and nominal molar amount; actual phase proportions except authors nominal16% carbonate estimate.']},
 {'id':'feii-oleate','label':'Fe(II)-source oleate preparation','record_ids':[rid('fe2-carbonate-to-oleate-preparation')],'status':'encoded','source_locators':['Main p.160','SI pp.3–4 eq3/FigS3'],'gaps':['FeCO3 mass/mmol discrepancy; vacuum pressure; stock concentration/yield; scale7 claim not separate batch.']},
 {'id':'feiii-oleate','label':'Fe(III)-source oleate preparation','record_ids':[rid('fe3-carbonate-to-oleate-preparation')],'status':'encoded','source_locators':['Main p.160','SI pp.4–5 eq4–6/FigS4'],'gaps':['Mixture precursor nominal molar loading; vacuum pressure/concentration; scale4 claim not separate batch.']},
 {'id':'generic-thermolysis','label':'Generic Fe(II)- or Fe(III)-source oleate thermolysis','record_ids':[rid('iron-oleate-general-thermolysis')],'status':'partial_protocol_encoded','source_locators':['Main p.160','SI p.5 FigS5'],'gaps':['Charge amount,source choice,dilution-specific setpoint within330–350C,3–5h exact hold,workup.']},
 {'id':'ode0','label':'No ODE,Fe:OA1:7 growth family,including late cubic condition','record_ids':[rid('iron-oxide-undiluted-cubic-condition')],'status':'revision2_audited_and_expanded','source_locators':['SI pp.11–14 FigS14–16'],'gaps':['Individual run/iron-source linkage; exact temperatures;size definition.']},
 {'id':'ode8','label':'8vol%ODE growth family and exact four-point temperature trajectory','record_ids':[rid('iron-oxide-ode8-growth-family')],'status':'partial_family_encoded','source_locators':['Main p.158 Fig8','SI pp.12–15 FigS14–16/S18'],'gaps':['Physical identity linking trajectory to grid; additionalS18 temperatures; reactor quantities.']},
 {'id':'ode30','label':'30vol%ODE growth family','record_ids':[rid('iron-oxide-ode30-growth-family')],'status':'partial_family_encoded','source_locators':['SI pp.12–14 FigS14–16'],'gaps':['No exact per-run temperature/branch/amount; must not substitute34vol%.']},
 {'id':'ode56','label':'56vol%ODE growth family','record_ids':[rid('iron-oxide-ode56-growth-family')],'status':'partial_family_encoded','source_locators':['SI pp.12–14 FigS14–16'],'gaps':['Exact per-run temperature/branch/amount.']},
 {'id':'high-ode-ratio','label':'Greater-than66vol%ODE Fe:OA1:2.5/4/5/7 cubic family','record_ids':[rid('iron-oxide-high-dilution-fe-oa-series')],'status':'partial_family_encoded','source_locators':['SI pp.14–15 FigS17'],'gaps':['Exact ODE%,T,time,amount,iron-source branch; spread definition.']},
 {'id':'ode34','label':'34vol%ODE star example','record_ids':[rid('iron-oxide-ode34-star-condition')],'status':'partial_condition_encoded','source_locators':['Main p.155 Fig3a'],'gaps':['Size,T,time,amount,branch; magnetic S19 is similar,not same batch.']},
 {'id':'oxide-oxidation','label':'Post-synthetic ambient oxidation of microscopy samples','record_ids':[],'status':'characterization_context_only_not_quantified_recipe','source_locators':['Main pp.156–158','SI pp.9–10 FigS12'],'gaps':['Exposure time/humidity,oxygen concentration,workup and conversion fractions absent.']},
 {'id':'other-iron-sources','label':'Qualitative FeO(OH) and Fe(acac)3 comparison; background FeCl3/Fe(CO)5 routes','record_ids':[],'status':'insufficient_recipe_details_no_fabricated_protocol','source_locators':['Main pp.153–155'],'gaps':['Authors mention own hydroxide/acetylacetonate experiments without quantities or run protocols; FeCl3/carbonyl examples cite prior studies.']},
 {'id':'analytical-controls','label':'CO2 assays,Fe-oleate/air GC,OA-only/air GC,OA purity/MALDI controls','record_ids':[],'status':'fully_inventoried_below_as_characterization_not_synthesis_training','source_locators':['Main pp.154–155/160','SI pp.6–9'],'gaps':['Acid amount and assay gas collectionT/P; air headspace volume; individual control charge amounts.']}
]
char=[
 {'id':'maldi','source_locators':['Main pp.154/160','Figures1,S6–S9'],'preparation':'Analytical oleate reactions use pure OA>99%GC,T;technical-grade OA control separately examined. Heat samples collected under nitrogen at roughly60C steps; exact dwell times not reported. Dilute sample1:25withdrytoluene (basis unspecified);9-nitroanthracene12mg/mLdrychloroform matrix;mix matrix/sample and drychloroform on ground steel target in glovebox;Schlenkbag transfer;max1sair contact cannot be excluded.','acquisition':'Bruker ultrafleXtreme/SmartbeamII,positive reflector; m/z350–4500 and2000–20000;FlexControl3.3/flexAnalysis3.3;externalpeptideIIstandard in2,5-dihydroxybenzoic acid;internalcalibration;LIFTMS/MS for iron isotope-pattern peaks.','results':'Eight major assigned complexions;no detectable complexes above3195Da within searched2–20kDarange. OA-linked multinuclearmixedvalencecomplexes are mechanistic precursor species, not single stock identities.','missing':['Laser energy,spot/shot count,calibration residuals,replicate counts/raw spectra.'],'eligible_training':False},
 {'id':'gc','source_locators':['Main pp.154–155/160','Figures2c,S10,S11'],'preparation':'Fe(III)-source oleate headspace at60C;separate air-atmosphere Fe-oleate and pure-OA closed-flask control.','acquisition':'PerkinElmerClarus500TCD;He5.0 99.999%;85mL/min;5A45/60Supelcomolecularsieve;oven230C;TCD200C.','results':'S10O2area4.85%,N2area95.1%;OA-only consumesO2above140C,Fe-oleate consumesbelow100C;CO/CO2startabout150C. Gas supports redox but not a unique elementary mechanism.','missing':['Headspace volume/pressure,sampleloop/injectionvolume,calibration to absolute concentrations,controlbatch amounts.'],'eligible_training':False},
 {'id':'co2-source-assay','source_locators':['Main p.160 Determination of CO2 Content'],'preparation':'Add sulfuric acid to prepared carbonate source,capture foaming evolved gas in measuring cylinder. FeCO3:1.70g14.6mmol;Fe(III)nominalcarbonate:1.90g6.51mmol.','acquisition':'Volumetric gas measurement;acid amount,T/P not supplied.','results':'FeIIgas~300mL vs theoretical320mL,authors6%difference. FeIIIgas~70mL,authors16%Fe2(CO3)3,restprobablyFe(OH)3/FeO(OH);percentbasis unstated.','missing':['Acidvolume/concentrationperassay,gasT/P/watervaporcorrection,basisof16%,replicates.'],'eligible_training':False},
 {'id':'tem','source_locators':['Main p.160','Figures3–8,S12,S14–18'],'preparation':'Diluted colloidal dispersion drop on carbon-coated400meshgrid;remove excess solvent with filterpaper;airdry.','acquisition':'JEOLJEM1011at100kV;JEM2200FSat200kV,twoCEOSCs correctorsCETCOR/CESCOR,Gatan4KUltraScan1000.','results':'Morphology galleries/series;authorreportedcondition-map sizes kept distinct from diameter.','missing':['Per-figure instrument assignment,size statistic/count/definition,aliquotvolume/quench.'],'eligible_training':False},
 {'id':'haadf-fft','source_locators':['Main pp.157–160 Figure6','SI pp.9–10 FigureS12'],'preparation':'Stored ambient/partially oxidized particles.','acquisition':'Aberration-corrected cubedFEITitan300kV,cameralength115mm.','results':'Facet{113},growth[111]from[110]projection;S12corewustite/edgeFe3O4orγFe2O3 FFT. No independently recorded SAED panel found anywhere in main/SI.','missing':['Specific specimen storage duration,oxidationfraction;no measuredatomiccoordinatefile.'],'eligible_training':False},
 {'id':'electron-tomography','source_locators':['Main pp.156/160 Figure5'],'preparation':'Octapod specimen with exact synthesis link unspecified.','acquisition':'FEITecnaiG2 200kV,Fischione2020single-tiltholder;Methods−74..+74degstep2;body±76deg;Inspect3Dcross-correlation/manualaxisadjustment;TVminimizationref51.','results':'Eight triangular pods;3D reconstruction is morphology tomography,not crystallographic coordinates.','missing':['Actual tilt sequence,raw tilt projections,reconstructionparameters/codelocation;externalref50/51details.'],'eligible_training':False},
 {'id':'eels-tomography','source_locators':['Main pp.157–158/160 Figure7'],'preparation':'Oxidized octapod;different oxidation degree possible from Figure6.','acquisition':'CubedFEITitan120kV,Fischione2020;−65..+65degstep10;relaxseveralminutesaftereachtilt;Gorisref32directspectrotomography;15datacubesclaimed.','results':'Fe2+-richcore andFe3+-richexterior,gradualinterface. Authorswustite→maghemiteinterpretationthroughmagnetite/mixedintermediates. ReferenceEELSFeTiO3/hematite are priorreference standards,not synthesis products.','missing':['Actual15angles vs nominal14positions,energyresolution/dispersion,dwell/dose,rawcubes,phasefraction.'],'eligible_training':False},
 {'id':'sem','source_locators':['Main pp.160–161','Figure5b/S13'],'preparation':'Toluene NCdispersion dropped on Siwafer and airdried.','acquisition':'LEO1550at20kV;mainFigure5b70degtilt.','results':'Octapod3Dmorphology;no sample-size-derivedrecipeassignment.','missing':['Recipe/batch IDs,perpaneltilt,coatingdetail.'],'eligible_training':False},
 {'id':'xrd','source_locators':['Main pp.155–156/161 Figure3c'],'preparation':'Purified dispersionfilled andsealed incapillaryunderinertglovebox;prevents post-syntheticoxidation.','acquisition':'PhilipsX\u2019PertPRO,CuKα0.15418nm,40kV110mA,2θ30–110deg;capillarywall0.1mm,diameter0.7mm,length80mm.','results':'Bothinitialsourcebranches producepristinewustite diffraction;reference00-006-0615. No refined lattice/sampleCIF or phase fractions reported.','missing':['Purificationprocedure,step/dwelltime,perbranchrunconditions.'],'eligible_training':False},
 {'id':'vsm','source_locators':['Main pp.158–159/161','SI pp.16–19 FiguresS19–S21'],'preparation':'SamplesdriedunderinertconditionsinQuantumDesignP125Eholders.','acquisition':'QuantumDesignDynacool;Methods5–350K,field≤30kOe;figure-specific field/temperaturesequencesrecorded infigureinventory.','results':'Exchange biasbelow~200K;ferromagnetic hysteresis at300Kforlargerstars/cubes;smallerstarsblocking<300Kandcubes~400Kassourced. Thermaltransitionoffset duewarm-upcryostat/samplelag. Sample massnotreported, magneticmomentnotnormalized tomass.','missing':['PreciseNCsize/dilution/phase,batchlink,sweeprate,samplemass;350vs400Kconflict.'],'eligible_training':False}
]
materials=[
 {'name':'acetone','grade':'99.0%','supplier':'Th.Geyer','role':'Listed;exactproceduraluseunspecified'},
 {'name':'dryacetone','grade':'99.0%,max0.01%H2O','supplier':'AppliChem','role':'Listed;notassignedasNCantisolvent'},
 {'name':'drychloroform','grade':'>=99.0%','supplier':'Sigma-Aldrich','role':'MALDImatrix/targetpreparation'},
 {'name':'helium','grade':'5.0,99.999%','supplier':'Westfalen','role':'GCcarrier'},
 {'name':'hydrochloricacid','grade':'37%','supplier':'VWR','role':'Listed;noquantifiedrecipeuse'},
 {'name':'iron(II)sulfateheptahydrate','grade':'99%','supplier':'Sigma-Aldrich','role':'FeIIsource;N2conditioned'},
 {'name':'iron(III)sulfate','grade':'97%','supplier':'Sigma-Aldrich','role':'FeIIIsource;hydrateambiguous;N2conditioned'},
 {'name':'oleicacidtechnical','grade':'90%','supplier':'Sigma-Aldrich','role':'Ligand/medium;N2conditioned;impuritycontrol'},
 {'name':'oleicacidpure','grade':'99.0%','supplier':'TCI','role':'MALDIanalyticalreactions;exactNCgradeunassigned'},
 {'name':'1-octadecene','grade':'90%','supplier':'Sigma-Aldrich','role':'Diluent'},
 {'name':'sodiumcarbonate','grade':'99.95–100.05%drybasis','supplier':'Sigma-Aldrich','role':'Precipitatingreagent;N2conditioned'},
 {'name':'sulfuricacid','grade':'95.0%','supplier':'Th.Geyer','role':'CO2assay'},
 {'name':'tetrahydrofuran','grade':'99.7%','supplier':'VWR','role':'Listed;exactproceduraluseunspecified'},
 {'name':'drytoluene','grade':'99.85%','supplier':'AcrosOrganics','role':'MALDIsampledilution'},
 {'name':'toluene','grade':'100%','supplier':'VWR','role':'Microscopydispersion'},
 {'name':'9-nitroanthracene','grade':'>=98.5%HPLC','supplier':'Sigma-Aldrich','role':'MALDImatrix;N2conditioned'},
 {'name':'molecularsieve5A45/60mesh','grade':'notstated','supplier':'Supelco','role':'GCcolumnpacking'},
 {'name':'Milli-Qwater','grade':'18.2MOhm/cm asprinted','supplier':'notstated','role':'N2saturated24h;carbonateprep/washing'},
 {'name':'nitrogen','grade':'notstated','supplier':'notstated','role':'Protectivegas;4evacuation/refillcycles'},
 {'name':'peptideIIstandard and2,5-dihydroxybenzoicacid','grade':'notstated','supplier':'BrukerDaltonik','role':'MALDIcalibration'}
]
unresolved_refs=[
 {'reference':'Main32,Goris etal.Ultramicroscopy2016,171,55–62','purpose':'Directspectroscopic tomography reconstruction/referenceEELS','status':'Citationread;externalfullprocedure/rawdata notread orretrieved inthispaperreview.','effect':'Acquisitionreportedherepreserved; algorithmimplementation incomplete.'},
 {'reference':'Main50,Schoenmakers etal.Microsc.Microanal.2005,11,312–313','purpose':'Automatedtomographicacquisition/alignment','status':'Citationread;externalmethodnotread.','effect':'Inspect3Dcross-correlation/manualaxis stated; noextraalgorithm parametersinvented.'},
 {'reference':'Main51,Goris etal.Ultramicroscopy2012,113,120–130','purpose':'TVminimizationtomographicreconstruction','status':'Citationread;externalmethodnotread.','effect':'Noexecutable reconstructionparameters claimed.'},
 {'reference':'SI5,BettoandCoey,J.Appl.Phys.2014,115,17D138','purpose':'Priormicromagneticsimulation motivatingvortex speculation','status':'Citationread;priorstudy fulltextnotread.','effect':'Notanewsimulation orconfirmedmagneticstateofthispaper.'},
 {'reference':'Main13–16 prior FeCl3/Fe(acac)3/FeO(OH)/Fe(CO)5 synthesisexamples','purpose':'Backgroundprecursorcontext','status':'Citationsread;notadoptedasfilled-inmethods.','effect':'Noextrafullyspecifiedrecipecreatedfrompriorwork.'}
]
gaps=['Every suppliedmain/SIpagewasreadandvisuallyreviewed; the remaining gaps below are absent/ambiguous source information, not unreviewed pages.','No acquired SAED image is present; Figure6b andS12c/d are FFTs.','No exact NC reactorcharge, specimen-specific precursorbranch, comprehensiveworkup,quench,isolatedyield orstoragehistory.','No exact geometrical definition of plotted sizes or spread statistic; no raw particlemeasurements/histograms/counts.','No measured CIF/atomiccoordinates, quantified phase fractions, or universal final Fe3O4/γFe2O3 label.','No machine-readable raw spectra/diffraction/magneticcurves or tilt-series files provided in these PDFs; curves are preserved as originalfigures and have not been digitized.','External referenced reconstruction algorithms and prior background recipes were not reviewed as full separate papers; listed explicitly in unresolved_referenced_methods.','Original crop rights remain with source rights holders; this review does not establish public-republication permission.']
coverage={'doi':DOI,'title':TITLE,'journal':'ACS Nano2019,13,152–162','online_date':'2018-12-12','review_date':'2026-09-17','coverage_status':'complete_review_of_supplied_main_and_matching_si_with_explicit_source_gaps','documents':docs,'recipe_inventory':recipe_inventory,'figures':figures,'tables':[],'table_inventory_status':'No numbered/formal tables in either document. FigureS14is a tabulated condition schematic and FigureS17is a ratio/size scheme; both fully inventoried as figures.','schemes_and_equations':equations,'characterization_inventory':char,'materials_inventory':materials,'conditioning':{'source_locator':'Mainp.159','conditions':['AllreactionsSchlenkunderN2;apparatus4evacuation/refillcycles.','WaterN2saturated24h.','OAandODEdegas25C1h0.5mbar,thenN2saturate(durationnotreported).','ReagentsmarkedN2conditionedintheMaterialslistretained;noinventedgasflow.']},'simulations_and_models':[{'id':'isotope-envelopes','source':'MainFig1/SI S8,S9','scope':'Owncalculatedisotopicpatterns and10%LAmixturecomparison;notatomicstructurelabels.'},{'id':'facet-model','source':'MainFig6c,d','scope':'Explanatory(100)/(111)terrace/stepmodel for{113}facet,notrefinedcoordinates.'},{'id':'shape-schemes','source':'MainFig8/SI S14,S17','scope':'Authorschematicgrowth/conditionillustrations,notnewmeasuredparticles.'},{'id':'tomographic-reconstruction','source':'MainFig5d/7f–k','scope':'Measuredprojection-derivedshape/valencedistributionreconstructions;notCIFcrystalcoordinates.'},{'id':'vortex-model','source':'SIp.19ref5','scope':'Priorworksphericalmagnetite simulation cited as speculation;notperformed/confirmedhere.'}],'evidence_conflicts':conflicts,'unresolved_referenced_methods':unresolved_refs,'remaining_gaps':gaps,'canonical_summary':canonical,'coverage_counts':{'main_pages_read':11,'si_pages_read':19,'all_pages_visually_reviewed':30,'numbered_main_figures':8,'unnumbered_graphical_abstracts':1,'si_figures':21,'numbered_si_equations':6,'formal_tables':0,'canonical_records':9,'claimed_independent_experiments':None},'saed_status':{'present':False,'basis':'Allfigures/captions/textin30pagesreviewed;FFTpatternsidentifiedexplicitly asFFT. Electron diffraction mentioned generically inSIp9doesnotconstituteaSAEDdataset.'}}
write('coverage.json',coverage)
print('Wrote complete coverage:',len(figures),'figures,',len(equations),'equations;',len(manifest),'original crops.')
