from pathlib import Path
import json,hashlib,datetime
HERE=Path(__file__).resolve().parent; AUTHOR=HERE.parent/'mixed-batch-02'
def read(p):return json.loads(Path(p).read_bytes())
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
binding=read(HERE/'binding-check.json'); summary=read(AUTHOR/'batch-summary.json'); renders=read(AUTHOR/'private'/'render-manifest.json')
assert sha(AUTHOR/'author-freeze.json')==binding['author_freeze_sha256']
assert sha(AUTHOR/'batch-summary.json')==binding['summary_sha256']
copies=[f for r in summary['receipts'] for f in r['files']]
for f in copies:assert sha(f['path'])==f['sha256']
for r in renders:assert sha(r['image_path'])==r['sha256']
findings={
1:'Synthesis-positive is supported for ligand synthesis and surface modification. Main p2 gives thioctic-acid/PEG chemistry; p5 explicitly exchanges existing QDs with ligands 9–11 (100–300 mg QDs, 1–2 mL ligand, 1 mL methanol, about 60 C overnight under nitrogen). Core/shell growth is cited upstream. Main p6 gel mobility and optical data establish surface/solution behavior, not measured crystal coordinates. SI title and numbered ligand preparations match, although a byline is not present in the inspected SI header.',
2:'Synthesis-positive is supported. Original main p2 shows citric acid 15 g, ethylenediamine 9 g and water 60 mL, 180 C for 5 h, dialysis, then Zr treatment at 80 C for 5 h. Fig1 routes the carbon-dot solution into the second stage while prose omits its dose/addition operation. Main pp3–4 identify TEM/HRTEM and reported 0.34 nm fringe spacing; 1.78–2.06 nm comes from DLS. HPAM formulation is separate. Missing carbon-dot amount remains unresolved.',
3:'Synthesis-positive is supported. Main pp2–3 describe fullerene soot/HNO3 treatment, CoNi-LDH preparation and hydrothermal assembly on Ni foam. FQD, precursor LDH and substrate remain distinct. The final recipe uses 20 mg FQD and 100 mg LDH in 30 mL water, 120 C for 12 h. Five reference electrodes are stated but only four FQD doses are listed; no missing value may be invented. Main p5 gives experimental phase/morphology discussion alongside explicitly calculated DFT context. DOCX title/byline match; only header/contents excerpt inspected.',
4:'Synthesis-positive is supported. Main p7 describes yeast incubation with 5 mM Na2SeO3 for 24 h, collection and resuspension with 1 mM CdCl2, plus purification. Genetically modified strains, media and growth phases are separate. SI p11 FigS12 visually assigns isolated CdSe TEM/HRTEM to PGAL1-GSH1, not all strains. Main p6 optical/yield comparison and SI p15 primer-table context do not establish experimental atom coordinates. Full strain-construction and duration crosswalk remain future work.',
5:'Synthesis-positive is supported by original main p2: 30 nm oxide grown at 950 C, Si dose 8×10^16 cm^-2 at 1 keV, and nitrogen annealing. Sample a is explicitly 1000 C for 20 min and main p3 Fig1 caption assigns its TEM image. XRD size about 3–4 nm is distinct from about 16 nm layer thickness. The five-phase ellipsometry representation is a layer model, not an atomic structure. Main p3 figure text read, image itself not independently viewed.',
6:'Synthesis-positive is supported. Main pp1–2 identify peptide AYSSGAPPMPPF, explicit peptide synthesis, and HEPES/HAuCl4 concentration-series nanocrystal formation; HEPES is the reducing agent and peptide inhibits kinetics. Main p2 states microscopy several days after growth, typically about 10 nm particles and up to about 100 nm aggregates; early nucleation was not imaged. SI p5 citrate controls mostly yield precipitates/aggregates. Reported morphology is retained without claiming image validation.',
7:'Synthesis-positive is supported by original main p2: solid-source MBE at 500 C, As4 pressure 6×10^-6 Torr and In delivery 0.22 ML/s. Uncapped AFM samples are separate from optical samples capped with 48 nm GaAs at 400 C. The authors caution about AFM lateral-size convolution. Punctuated deposition definition is locally present; full interruption-time/deposition series remains unreviewed.',
8:'The bounded theory deferment is supported. Main p2 Numerical Model solves Kohn–Sham/Poisson equations for a modeled device. Layer thicknesses and carrier populations are not measured atomic positions or a local preparation protocol. No complete-source synthesis-negative conclusion was drawn.',
9:'Source-role hold is supported. Main and SI1 have identical SHA256 and are visibly Peer Review Files. Review PDF p3 names the same manuscript as genuine SI2. SI2 pp1–2 contain partial MBE/sample preparation for A–F, isotope/implantation distinctions, and sample E rapid thermal annealing for 30 s at 400 C. This is positive process evidence within a held identity/source-completeness scope, not evidence of no synthesis. The actual article is not present among the three selected files; no global/remote absence claim is made.',
10:'The bounded theory deferment is supported. Main p3 Model and Calculations constructs Si29H36 and assumed oxygen arrangements using prescribed bond lengths/angles. Calculated positions cannot be relabeled as a measured product structure or laboratory oxidation recipe. Uninspected source scope remains unresolved.'}
rows=[]
for r in summary['receipts']:
 pages={}
 for item in r.get('full_pdf_text_pages_read',[]):pages.setdefault(item['source_sha256'],set()).add(item['pdf_page'])
 for item in r.get('original_pdf_pages_visually_inspected',[]):pages.setdefault(item['source_sha256'],set()).add(item['pdf_page'])
 if r['case']==9:pages.setdefault(r['files'][0]['sha256'],set()).add(3)
 rows.append({'case':r['case'],'group_id':r['group_id'],'author_outcome':r['outcome'],'independent_outcome':r['outcome'],'independent_disposition_detail':'source_role_hold_with_partial_synthesis_cues' if r['case']==9 else ('bounded_theory_deferment' if r['case'] in [8,10] else 'synthesis_present'),'source_hashes':r['source_hashes'],'actually_read_targeted_pages':{h:sorted(v) for h,v in pages.items()},'independent_finding':findings[r['case']],'required_screening_correction':None})
save(HERE/'independent-reading-notes.json',rows)
role=next(x for x in rows if x['case']==9)
save(HERE/'source-role-hold.json',{'group_id':role['group_id'],'held':True,'files':next(r['files'] for r in summary['receipts'] if r['case']==9),'actual_roles':{'16aa8f655474738eedba94241b9d5d6d653bb2ef01a7582399016c49ce7eef25':'peer_review_file_two_identical_copies','6c816c20488755ef9ee1f028937169a59b9e2019ff4acd48bcdb6129a443d857':'matching_title_supplement_with_partial_preparation'},'main_role_unresolved':True,'synthesis_absent':False,'sample_recipe_approval':False,'scope':'Read-only exception receipt for the three selected files; no shared overlay or ledger mutation.'})
end=datetime.datetime.now(datetime.timezone.utc);start=datetime.datetime.fromisoformat(binding['started_at']);elapsed=(end-start).total_seconds()
report={'schema':'mattersyn-independent-methods-triage-check/1','auditor':'/root/all_page_coverage','passed':True,'acceptance_scope':'Bounded initial screening classifications, original-source identity and decisive Methods/structure roles only.','author_freeze_sha256':binding['author_freeze_sha256'],'summary_sha256':binding['summary_sha256'],'started_at':start.isoformat(),'ended_at':end.isoformat(),'elapsed_seconds_including_original_replay_reading_and_receipts':elapsed,'elapsed_minutes_per_selected_scope':elapsed/600,'timing_limits':['Purposeful ten-scope batch, not a corpus throughput forecast.','Reuses five prepared original-page views; independently replays selected text from current original bytes.','Does not include complete scientific extraction, full-paper audit or integration.'],'coverage':{'scopes':10,'current_source_copies_rehashed_before_and_after':len(copies),'distinct_source_hashes':len({x['sha256'] for x in copies}),'author_artifact_bindings_verified':len(binding['bindings'])-len(copies),'fresh_original_text_replays':len(binding['fresh_original_text_replays']),'targeted_pdf_pages_read':sum(len(v) for r in rows for v in r['actually_read_targeted_pages'].values()),'original_pdf_pages_visually_inspected':5,'pdf_identity_headers':15,'ooxml_identity_header_and_contents_excerpt':1,'full_ooxml_scientific_read':False,'full_papers_completed':0,'figures_or_atom_tables_completely_validated':False},'outcomes':{'synthesis_present':7,'unresolved':3},'unresolved_breakdown':{'bounded_theory_deferments':2,'source_role_hold_with_positive_partial_SI_process_evidence':1},'required_corrections':[],'retained_qualifications':['Uyeda is local ligand/surface modification, with upstream core/shell growth cited.','Fan carbon-dot solution addition/dose gap remains despite schematic linkage.','Feng five-reference-electrode versus four-listed-masses inconsistency remains.','Li strain/media/timing variants cannot share a single microscopy assignment.','Ding crystallite size and layer thickness remain separate.','Stanley post-growth morphology and early kinetics remain separate.','Mukhametzhanov capped optical versus uncapped AFM specimens and tip-convolution caveat remain.','Kirstein true-main role hold remains; supplementary preparation cues are not discarded.','Matagne and Nishida theory deferments are scoped, not all-source exclusions.'],'new_scientific_records':0,'new_approved_structure_recipe_pairs':0,'training_admissions':0,'source_closures':0,'website_admission':False,'shared_state_mutated':False,'originals_and_author_package_unchanged':True,'bound_evidence':{str(p):sha(p) for p in [HERE/'binding-check.json',HERE/'independent-reading-notes.json',HERE/'source-role-hold.json',HERE/'check_bindings.py',HERE/'finalize_check.py',AUTHOR/'private'/'render-manifest.json']}}
save(HERE/'independent-check.json',report)
(HERE/'independent-check.md').write_text(f'# Mixed batch 02 independent screening check\n\nPassed within bounded Methods-first scope. Seven synthesis-positive classifications are supported; two theory cases remain deferred and one case remains held for source roles. No required correction to the frozen author package.\n\nRehashed 17 copies (16 unique source contents), verified 174 author artifacts, replayed 38 selected original text units, read decisive sections on 25 PDF pages and viewed five prepared original-page images. Fifteen PDF identity headers and one DOCX header/contents excerpt were checked. Full papers, all figures and numerical tables were not audited.\n\nFor Kirstein, both main-labelled and SI1 files are identical Peer Review Files. The matching-title SI2 contains partial preparation for samples A–F, including sample E annealing for 30 s at 400 C. Preserve that process evidence while holding the missing true-main role; this is not a synthesis-negative paper.\n\nImportant quantities and source limitations in the seven positive cases agree with the inspected originals. Fan’s missing carbon-dot addition dose, Feng’s five-versus-four reference count, and specimen/morphology distinctions remain explicit.\n\nElapsed: {elapsed:.1f} seconds ({elapsed/60:.2f} minutes), including tools, reading and receipt writing. This purposive screening check is not a corpus throughput forecast. No scientific records, pairs, training admissions, source closures or website admissions approved. Shared state and source files unchanged.\n',encoding='utf8')
print(json.dumps({'passed':True,'audit_sha256':sha(HERE/'independent-check.json'),'elapsed_seconds':elapsed,'coverage':report['coverage']}))
