"""Paper-wide coverage ledger from full main/SI reading and visual review."""
from pathlib import Path
import json,hashlib,collections
R=Path(__file__).resolve().parent
def write(name,x):(R/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
docs=json.loads((R/'source-manifest.json').read_text());crops=json.loads((R/'crop-manifest.json').read_text())
records=[json.loads(p.read_text(encoding='utf-8')) for p in sorted((R/'canonical').glob('*.json'))]
P='nakonechnyi-2017-';D='10.1021/acs.chemmater.7b00354'
def ids(*s):return [P+x for x in s]
def loc(role,page,part):return {'source_role':role,'pdf_page':page,'printed_page':str(4718+page) if role=='main' else 'S'+str(page),'section_or_item':part}
def f(name,value,unit,scope,qualifier='',status='reported'):
 return {'name':name,'value':value,'unit':unit,'scope':scope,'status':status,'qualifier':qualifier}
def item(id,label,role,page,kind,caption,link,facts=None,gaps=None):
 a=next(x for x in crops if x['id']==id)
 return {'id':id,'label':label,'source_locator':loc(role,page,label),'kind':kind,'caption_paraphrase':caption,'sample_linkage':link,'quantitative_facts':facts or [],'review_status':'full_text_and_original_visual_review','crop_asset':a['relative_path'],'crop_sha256':a['sha256'],'bbox_pdf_points_top_left':a['bbox_pdf_points_top_left'],'unresolved':gaps or [],'digital_curve_data':'not_tabulated_or_extracted' if kind in ['experimental','simulation'] else 'not_applicable'}
conflicts=[
 {'id':'oa-cd-ratio','locators':[loc('main',2,'zb-CdSe/CdS method'),loc('main',3,'Figure1'),loc('si',2,'FigureS1')],'issue':'Method charges5.6mmol OA/0.25mmol CdO, a charged ratio22.4; results/figure nominally20:1.','handling':'Retain listed quantities and reported ratio separately. Do not derive low-OA charge or silently subtract bound ligand.'},
 {'id':'oa-zn-ratio','locators':[loc('main',2,'zb-CdSe/ZnSe method'),loc('main',4,'Figure2 caption')],'issue':'Method charges5.3mmol OA/0.65mmol ZnO (8.1538), while Figure2 says OA/Zn20:1.','handling':'All three seed-loading variants retain method charges; Figure2/Table1 measurements remain context only.'},
 {'id':'dimension-definition','locators':[loc('main',4,'Table1 and TEM discussion'),loc('main',5,'wz TEM discussion')],'issue':'Table1 labels d_shell and defines it as shell thickness. The same8.6±1.5nm is explicitly overall mean diameter in body; wz body describes ~10nm particles, table11.2nm.','handling':'zb8.6nm follows explicit overall-diameter body evidence; wz table dimensions kept under source_d_shell_dimension_unresolved, no exact shell-thickness or diameter training label.'},
 {'id':'seed-size-context','locators':[loc('main',2,'zb core method'),loc('main',4,'Table1'),loc('main',5,'wz core discussion')],'issue':'Generic zb core is about3nm/537nm; table uses3.1nm. Wz discussion says originally3nm, table3.4/3.6nm for distinct shell systems.','handling':'No forced equality or transfer from shell-table seeds into generic wz-core outcome.'},
 {'id':'znse-thermal-transition','locators':[loc('main',2,'zb-CdSe/ZnSe')],'issue':'Zn oleate formation310C; feed injection explicitly260C. Transition timing not described.','handling':'Keep two stages and the missing cooling/recovery transition, do not relabel injection310C.'},
 {'id':'simulation-k1','locators':[loc('main',6,'Kinetic Modeling'),loc('si',6,'TableS1 and preceding paragraph')],'issue':'Main text states3/100s^-1=0.03; SI states0.03333s^-1.','handling':'Keep both original values; simulation not reproduced and neither value becomes an experimental recipe parameter.'},
 {'id':'simulation-cross-references','locators':[loc('main',6,'Figure5 caption'),loc('si',7,'S3.3')],'issue':'Figure5 caption directs parameter settings to SI S1, but parameters are S3/TableS1; SI7 says initial seeds used for main Figures4 and5 although experimental Figure4 precedes simulation Figures5/6.','handling':'Explicitly record source cross-reference mismatch. Use actual figure content and named S3 section.'},
 {'id':'znse-seed-typo','locators':[loc('main',6,'opening continuation')],'issue':'Body says diameter increase relative to ZnSe seeds while method and study identify CdSe seeds.','handling':'Retain as source wording conflict; core identity follows named CdSe protocol, not this isolated sentence.'},
 {'id':'sampling-series-coverage','locators':[loc('main',2,'aliquot schedules'),loc('main',4,'Figure2'),loc('main',5,'Figure4')],'issue':'Plotted series differ from generic methods: Figure2 includes60min beyond method40min; Figure4c yield extends900s beyond listed360s wz-CdS schedule; Figure4d/e plotted subset ends30min while method lists60min.','handling':'Do not equate plot legends to complete method schedule or invent independently charged runs.'}
]
mainsections={1:['Title/authors/abstract','Graphical abstract','Introduction; cited background only'],2:['Introduction continuation','Six core/shell experimental methods','Materials characterization starts'],3:['Materials characterization continuation','Chemical-yield derivation, equations1-8','Experimental results starts','Figure1'],4:['High/low OA CdS outcomes','Table1','Figure2','Figure3','Chemical-yield development starts'],5:['Chemical-yield development continuation','Wurtzite seeded-growth results','Figure4'],6:['Wz-ZnSe results conclusion','Kinetic modeling; equations9-12','Figure5'],7:['Growth-rate equation13','Solubility-dependent simulation/experiment comparison','Figure6'],8:['Model interpretation continuation','Conclusion','SI description','Author information/acknowledgments','References1-17'],9:['References18-33']}
sisections={1:['SI identity/title/authors'],2:['S1 blank seeded-growth controls','FigureS1'],3:['S2 selected-area electron diffraction','FigureS2'],4:['S3.1 model equationsS1-S4'],5:['EquationsS5-S7','S3.2 simulation implementation'],6:['S3.2 parameter rationale','TableS1','S3.3 initial seeded distribution; equationS8'],7:['S3.3 initial distribution values','References1-2']}
for d in docs:
 d['identity_verified_by']='Title and author list match main/SI; main DOI and SI contents correspond to the article cited supporting information.'
 d['pages']=[]
 for n in range(1,d['page_count']+1):
  pg={'page':n,'printed_page':str(4718+n) if d['role']=='main' else 'S'+str(n),'text_read':True,'visual_review':True,'sections':(mainsections if d['role']=='main' else sisections)[n],'unresolved':[c['id'] for c in conflicts if any(l['source_role']==d['role'] and l['pdf_page']==n for l in c['locators'])],'local_text_path':str(R/d['role']/f'page-{n:02d}.txt'),'local_render_path':str(R/d['role']/f'page-{n}.png')}
  d['pages'].append(pg)

figs=[]
figs.append(item('main-graphical-abstract','Graphical abstract (unnumbered)','main',1,'conceptual_and_simulation','Conceptual suppression of homogeneous nucleation and promotion of seeded growth, paired with a simulated concentration map.','Conceptual summary; not an additional experimental sample.',[f('simulation plot time axis',[.01,1000],'s','Graphical-abstract simulation'),f('reference monomer solubility',1,'relative to reference','simulation label')]))
figs.append(item('main-figure-1','Figure1','main',3,'experimental','Absorption, TEM and PL compare high-OA and low-OA zb-CdSe/CdS seeded growth.','High-OA panels a-c versus low-OA panels d-f. TEM b and corresponding e are captioned as2min products; Table1/SAED batch equivalence is not explicitly identified.',[
f('OA/Cd ratio high',20,'mol/mol','panels a-c'),f('OA/Cd ratio low',3,'mol/mol','panels d-f'),f('TEM sampling time',120,'s','panel b; d-f stated same as a-c'),f('TEM scale bar',10,'nm','b,e'),f('spectral aliquot legend high',[10,30,60,90,120,180,240,300],'s','a/c'),f('spectral aliquot legend low',[10,30,60,90,120,180,240,300,360],'s','d/f'),f('overall mean diameter',8.6,'nm','Figure1b body discussion main4'),f('reported diameter spread',1.5,'nm','Figure1b body discussion','± type not specified'),f('initial core diameter',3.1,'nm','Figure1b body discussion'),f('high-OA spectral plateau',120,'s','body main4','about'),f('low-OA CdSe exciton wavelength',570,'nm','body main4'),f('CdS absorption extent',520,'nm','high-OA body main3','approximately'),f('typical high-OA PLQY',[30,35],'%','body main4','typical range, not a single labeled batch')],['oa-cd-ratio','dimension-definition','No exact peak positions digitized beyond explicitly stated570nm.'] ))
figs.append(item('main-figure-2','Figure2','main',4,'experimental','Absorption/PL time series and TEM of irregular zb-CdSe/ZnSe products.','Seed loading is not assigned among25/50/100nmol method alternatives. Phase context in SI S2d; PLQY55% in Table1.',[f('caption OA/Zn',20,'mol/mol','caption'),f('spectral aliquot legend',[1,4,8,12,18,27,40,60],'min','a,b'),f('TEM sampling time',60,'min','c'),f('TEM scale bar',10,'nm','c'),f('additional ZnSe absorption extent',430,'nm','body discussion','approximately')],['oa-zn-ratio','sampling-series-coverage','Irregular shape prevents a reported shell thickness.']))
figs.append(item('main-figure-3','Figure3','main',4,'experimental','Absorbance-derived yield curves compare seeded high/low-OA CdS and unseeded CdS; ZnSe with and without seeds.','These are related time series and controls, not independent points to count as new synthesis batches.',[f('CdS near-completion time',200,'s','body main5','approximately'),f('CdS apparent yield plateau',[60,70],'%','body main5','Author-derived and potentially underestimated/affected by optical constants','author_derived'),f('ZnSe yield at40min',50,'%','body main5','almost','author_derived'),f('ZnSe time at stated yield',40,'min','body main5'),f('unseeded ZnSe detection delay',500,'s','body main5','approximately; first appearance in absorbance')],['Exact point coordinates/error bars not tabulated; no digitization performed.','Yield normalization assumes stoichiometry and uses bulk-derived absorption constants.']))
figs.append(item('main-figure-4','Figure4','main',5,'experimental','Optical spectra, TEM insets and seeded/unseeded yield curves for wz-CdSe/CdS and wz-CdSe/ZnSe.','a-c CdS, d-f ZnSe. Caption says d-f same as a-c, including inset conventions, but exact link to Table1 samples remains unassigned.',[f('TEM inset sampling time',2,'min','caption a; d inherits same-as wording'),f('TEM scale bar',10,'nm','a,d'),f('CdS spectral aliquot legend',[5,30,60,120,180,240,360],'s','a,b'),f('ZnSe spectral aliquot legend',[5,60,150,300,600,1800],'s','d,e'),f('qualitative resulting particle diameter',10,'nm','CdS body','approximately; table number separately unresolved'),f('qualitative original seed diameter',3,'nm','CdS body','approximate contextual value; Table1 says3.4nm'),f('ZnSe absorption visible by',60,'s','body')],['dimension-definition','seed-size-context','sampling-series-coverage','Spectral peak wavelengths remain essentially constant for wz-ZnSe but no exact values reported.']))
figs.append(item('main-figure-5','Figure5','main',6,'simulation','Calculated concentration distributions and mean-radius/concentration trajectories compare precursor-only and seeded growth.','No experimental run; c/d seed distribution imposed numerically.',[f('initial seed radius',1.54,'nm','seeded simulation'),f('initial relative size dispersion',6,'%','seeded simulation'),f('initial seed concentration',10,'µmol/L','seeded simulation'),f('bimodal-seeded concentration increase',7.5,'%','body','about'),f('reaction-to-ripening crossover',100,'s','body','approximately'),f('color reference concentration density',1,'µmol/L/nm','caption')],['simulation-k1','simulation-cross-references','No COMSOL files or numeric trajectory arrays supplied; not independently reproduced.']))
figs.append(item('main-kinetic-scheme','Kinetic scheme, equations9-11 (unnumbered scheme)','main',6,'conceptual','P converts to M; critical monomer aggregation nucleates nanocrystals; monomer attachment grows existing nanocrystals.','Conceptual reaction scheme, not a balanced chemical synthesis or measured species inventory.'))
figs.append(item('main-figure-6','Figure6','main',7,'simulation','Changing assumed monomer solubility shifts simulated growth from secondary nucleation toward growth-only behavior.','Same model seed distribution; not an experimentally quantified acid-to-solubility calibration.',[f('low solubility factor',.25,'relative to reference','a,b'),f('high solubility factor',4,'relative to reference','c,d'),f('low-solubility concentration increase',8,'fold','body','approximately'),f('high-solubility radius increase',2,'fold','body','approximately'),f('experimental acid change discussed',6,'fold','body experiment analogy','approximately; not a calibrated model input mapping')],['No experimental monomer solubility measured; authors explicitly caution simulation values lack experimental quantitative meaning.']))
figs.append(item('si-figure-s1','FigureS1','si',2,'experimental','Normalized unpurified spectra of cores and four precursor-omission controls.','All four controls use50nmol cores. No changes in first-exciton peak or significant concentration changes are reported; no detection limit supplied.',[f('core amount',50,'nmol nanocrystals','all controls'),f('sampling time',300,'s','all controls'),f('Cd:OA ratios',[[1,3],[1,20]],'mol/mol','Cd-containing controls'),f('additional OA absorption below',350,'nm','high-OA unpurified blank','approximately')],['OA/Cd basis and control-specific exact solvent balance unresolved.','A qualitative absence of significant change is not a zero-sized numerical outcome.']))
figs.append(item('si-figure-s2','FigureS2','si',3,'experimental','Actual SAED patterns assign overall wurtzite or zinc-blende phase to the four core/shell material systems.','a wz-CdSe/CdS; b zb-CdSe/CdS; c wz-CdSe/ZnSe; d zb-CdSe/ZnSe. Caption links to TEM samples generally; physical batch IDs absent.',[],['No measured lattice parameter, sample CIF, electron voltage, camera length or indexed-spacing table is provided.']))
figs[-1]['panels']=[{'panel':'a','system':'wz-CdSe/CdS','overall_phase':'wurtzite','annotated_hkl':['010','002','011','012','110','013','112']},{'panel':'b','system':'zb-CdSe/CdS','overall_phase':'zinc blende','annotated_hkl':['111','022','113']},{'panel':'c','system':'wz-CdSe/ZnSe','overall_phase':'wurtzite','annotated_hkl':['010','002','012','110','020']},{'panel':'d','system':'zb-CdSe/ZnSe','overall_phase':'zinc blende','annotated_hkl':['111','022','113']}]

table1=item('main-table-1','Table1','main',4,'experimental_table','Core dimensions, source-labeled shell dimensions and absolute PLQY for four material systems.','Material-system rows; individual physical batch and exact seed-loading association not provided.',[],['dimension-definition','Uncertainty type and TEM particle count not supplied.'])
table1['columns']=[{'name':'d_core','unit':'nm','author_meaning':'core diameter'},{'name':'d_shell','unit':'nm','author_meaning':'shell thickness','interpretation_status':'conflicts with body overall-diameter wording'},{'name':'PLQY','unit':'%','author_meaning':'photoluminescence quantum yield'}]
table1['rows']=[{'system':s,'d_core_nm':c,'d_shell_as_printed_nm':v,'reported_plusminus_nm':p,'plqy_percent':y,'sample_linkage':'context_only'} for s,c,v,p,y in [('zb-CdSe/CdS',3.1,8.6,1.5,35),('zb-CdSe/ZnSe',3.1,None,None,55),('wz-CdSe/CdS',3.4,11.2,2.3,60),('wz-CdSe/ZnSe',3.6,11.2,1.4,80)]]
table1['footnote_paraphrase']='No shell dimension is given for irregular zb-CdSe/ZnSe; d_core denotes core diameter and d_shell is called shell thickness.'
tableS=item('si-table-s1','TableS1','si',6,'simulation_table','Reference parameters used for the kinetic simulations.','Model quantities only, not measured precursor conditions or fitted per-sample physical constants.',[],['simulation-k1','Adsorption-rate expression retained literally rather than evaluated with an assumed concentration-unit convention.'])
tableS['rows']=[{'symbol':s,'description':d,'value':v,'unit':u,'value_status':'author_model_parameter'} for s,d,v,u in [('D','monomer diffusion coefficient',.5e-9,'m^2/s'),('v0','monomer volume',1.33e-29,'m^3'),('[M]0','monomer solubility',2e-8,'mol/m^3'),('T','absolute temperature',553.15,'K'),('gamma','surface tension',.24,'N/m'),('alpha','transfer coefficient',.5,'dimensionless'),('Vm','CdSe molar volume',3.367e-5,'m^3/mol'),('k_g_infinity','monomer adsorption rate constant','5e-7/[M]0','m/s'),('k1','monomer-generation rate constant',.03333,'1/s'),('[P]0','initial precursor concentration',.01667,'mol/L')]]
tables=[table1,tableS]

invent=[]
for r in records:
 locators=[]
 for o in r['operations']:
  for e in o['evidence']:
   if e not in locators:locators.append(e)
 invent.append({'id':r['record_id'],'label':r['title'],'record_ids':[r['record_id']],'status':'source_reviewed_variant_or_control_with_explicit_gaps','source_locators':locators,'gaps':r['quality']['missing_fields'],'experiment_independence':'No author-assigned batch ID; not assumed an independent run.'})
prep=[('zb-metal-myristate','In situ CdO/myristic-acid core precursor',ids('zb-cdse-core'),['s1','s2'],'0.5mmol CdO,1.6mmol myristic acid,10mL ODE; ambient260C until total dissolution.',['Molecular speciation/conversion not measured; time/ramp unreported.']),('zb-se-dispersion','Black-Se dispersion in ODE',ids('zb-cdse-core'),[],'0.24mmol Se dispersed in ODE; swiftly added.',['Carrier volume, preparation temperature, mixing method and storage unreported.']),('wz-core-precursor','CdO/TDPA/oleyl-alcohol/TOPO precursor',ids('wz-cdse-core'),['charge','pretreat','dissolve','top-preinject'],'1.5mmol CdO,6mmol TDPA,24mmol oleyl alcohol,10g TOPO;120C nitrogen1h,350C colorless,2mL TOP then recovery.',['TDPA not expanded in source; molecular speciation not established.']),('supplied-topse','Supplied2M TOP-Se stock',ids('wz-cdse-core','zb-cdse-znse-25nmol','zb-cdse-znse-50nmol','zb-cdse-znse-100nmol'),[],'1.5mL for wz core;0.215mL for each zb-ZnSe loading option.',['Stock recipe, solvent composition, purity and storage not described.']),('supplied-tops','Supplied2M TOP-S stock',ids('zb-cdse-cds-seeded-growth','zb-cdse-cds-low-oa-control','core-stability-top-s-only'),[],'0.38mL stock in1.12mL added ODE for standard zb-CdS route.',['Stock recipe, solvent composition, purity and storage not described.']),('wz-s-top-feed','Sulfur/TOP/wz-core injection feed',ids('wz-cdse-cds-seeded-growth'),['prepare-feed'],'100nmol dried cores+0.5mmol sulfur dissolved in1mL TOP.',['Dissolution temperature/duration, core drying conditions, solution species and storage missing.']),('wz-se-top-feed','Selenium/TOP/wz-core injection feed',ids('wz-cdse-znse-seeded-growth'),['prepare-feed'],'100nmol cores+0.96mmol Se added to1mL TOP.',['Dissolution completion, temperature/duration, speciation and storage missing.']),('shell-metal-oleates','In situ Cd/Zn oleates, distinct source recipes',ids('zb-cdse-cds-seeded-growth','zb-cdse-znse-25nmol','zb-cdse-znse-50nmol','zb-cdse-znse-100nmol','wz-cdse-cds-seeded-growth','wz-cdse-znse-seeded-growth'),['form-cadmium-oleate','form-oleate'],'Separate charged amounts and formation temperatures are retained within each canonical route, never pooled.',['Acid-ratio conflict for zb protocols; conversion/speciation unmeasured.'])]
for id,label,rr,ops,summary,gaps in prep:invent.append({'id':id,'label':label,'record_ids':rr,'operation_ids':ops,'status':'preparation_embedded_in_parent_records' if ops else 'stock_or_dispersion_partially_specified','source_locators':[loc('main',2,'Experimental Section')],'summary':summary,'gaps':gaps,'experiment_independence':'Embedded precursor stage, not an extra synthesis batch.'})
chars=[
 {'technique':'UV-vis absorption','acquisition':'PerkinElmer Lambda950 and Varian Cary500; unpurified shell aliquots diluted into1mL toluene; spectra normalized by aliquot mass. Core concentration averages absorbance at300/320/340nm.','source_locators':[loc('main',2,'Materials Characterization and zb-core subsection'),loc('main',3,'Chemical Yield Calculation')],'items':['Figure1','Figure2','Figure3','Figure4','FigureS1'],'gaps':['Exact instrument per spectrum, path length, dilution factor, slit width, wavelength resolution and raw arrays not supplied.']},
 {'technique':'PL emission','acquisition':'Edinburgh Instruments FLS920 fluorescence spectrometer.','source_locators':[loc('main',2,'Materials Characterization')],'items':['Figure1','Figure2','Figure4'],'gaps':['Excitation wavelength, resolution, concentration and per-sample correction settings unreported.']},
 {'technique':'Absolute PLQY','acquisition':'152mm Spectralon-coated integrating sphere; Princeton Instruments ProEM16002 CCD and ActonSP2358 spectrograph.','source_locators':[loc('main',2,'Materials Characterization'),loc('main',3,'continuation')],'items':['Table1'],'gaps':['Exact excitation and sample collection time/batch unreported.']},
 {'technique':'Bright-field TEM','acquisition':'Cs-corrected JEOL2200FS. Dropcast a solution on carbon-coated copper grid. TEM aliquots ethanol-precipitated and washed3x with1mL hexane/1mL ethanol, global3000g.','source_locators':[loc('main',2,'Methods and Materials Characterization')],'items':['Figure1b/e','Figure2c','Figure4a/d insets'],'gaps':['Accelerating voltage, particle count, sizing algorithm and spread definition unreported.']},
 {'technique':'SAED','acquisition':'Selected-area electron diffraction in TEM;4actual patterns.','source_locators':[loc('si',3,'S2/FigureS2')],'items':['FigureS2a-d'],'gaps':['Camera length, voltage, aperture, measured spacings and exact physical sample IDs not supplied.']},
 {'technique':'Chemical yield from absorption','acquisition':'Equations1-8; first-aliquot subtraction accounts for residual OA/ODE absorption but slightly underestimates formed material; intrinsic coefficient from bulk optical constants; stoichiometric cation:anion assumption1.','source_locators':[loc('main',3,'Chemical Yield Calculation'),loc('main',5,'yield plateau caveat')],'items':['Figure3','Figure4c/f'],'quantitative_facts':[f('zb-CdS intrinsic absorption coefficient',1.56e5,'cm^-1','320nm','bulk-derived','author_derived'),f('zb-ZnSe coefficient',1.15e5,'cm^-1','320nm; also substituted for unavailable wz-ZnSe constants','bulk-derived','author_derived'),f('wz-CdS coefficient',1.73e5,'cm^-1','300nm','bulk-derived','author_derived'),f('assumed cation/anion ratio',1,'mol/mol','all yield calculations','modeling assumption')],'gaps':['No aliquot masses/volumes, measured stoichiometry or pointwise raw data supplied.']},
 {'technique':'Not reported in these documents','acquisition':'No original Raman spectrum, powder-XRD pattern, sample-specific refined CIF, XPS measurement, EDX composition map or FTIR characterization presented.','source_locators':[loc('main',1,'all9pages'),loc('si',1,'all7pages')],'items':[],'gaps':['No absent technique inferred from an external illustration or cited paper.']}
]
sim={'status':'author_simulations_reviewed_not_reproduced','source_locators':[loc('main',6,'Kinetic Modeling'),loc('main',7,'Figure6'),loc('si',4,'S3.1'),loc('si',5,'S3.2'),loc('si',6,'TableS1'),loc('si',7,'S3.3')],'software':'COMSOL Multiphysics; version/project not supplied','model':'Single precursor first-order generation of monomers; classical nucleation; spherical growth with constant size-independent surface tension; one-dimensional radius distribution.','equations':[{'id':'main1-8','role':'absorption/yield inference; experimental data reduction, not precursor inputs'},{'id':'main9-11/S1','role':'P→M⇌QD kinetic scheme'},{'id':'main12/S4','role':'classical nucleation rate'},{'id':'main13/S5','role':'radius-growth rate'},{'id':'S2','role':'size-distribution transport with nucleation source'},{'id':'S3','role':'critical nucleus radius'},{'id':'S6','role':'monomer supersaturation balance'},{'id':'S7','role':'first-order precursor consumption'},{'id':'S8','role':'Gaussian initial seed distribution'}],'implementation':[f('radius domain',[0,8],'nm','simulation'),f('mesh elements',1274,'count','simulation'),f('absorbing region',[0,.2],'nm','simulation'),f('Gaussian nucleation width',.01,'nm','simulation'),f('nucleation center above critical radius',.03,'nm','simulation'),f('target realistic critical radius',.5,'nm','parameter tuning','approximately'),f('main-text k1',.03,'s^-1','main6'),f('SI k1',.03333,'s^-1','SI6'),f('reference monomer solubility asSI prose',2e-11,'mol/L','SI6')],'parameter_rationale':'D chosen from room-temperature cadmium-oleate/toluene measurements; monomer volume based on spherical CdSe unit; solubility and surface-related term adjusted to realistic nucleation radius/final population; adsorption chosen near diffusion-limited regime. Parameters have no asserted measured meaning for these actual shelling conditions.','cases':['No seeds, reference solubility (Figure5a/b)','10µM seeds, reference solubility (Figure5c/d)','Same seeds,0.25×solubility (Figure6a/b)','Same seeds,4×solubility (Figure6c/d)'],'gaps':['No simulation project, solver time tolerances or numeric trajectories provided.','k1 and cross-reference conflicts retained.','No experimental acid-to-solubility calibration or monomer species proof.']}
refs=[{'reference':'21','title':'Fast, High Yield, and High Solid Loading Synthesis of Metal Selenide Nanocrystals','authors':'Flamee et al.','year':2013,'journal_locator':'Chem.Mater.25,2476-2483','role':'Original zb-CdSe preparation','status':'Bibliographic reference read; original method not inspected in this audit','gaps':['Only the brief adapted procedure in Nakonechnyi is curated.']},{'reference':'14','title':'Revisited Wurtzite CdSe Synthesis: a Gateway for the Versatile Flash Synthesis of Multi-Shell Quantum Dots and Rods','authors':'Drijvers et al.','year':2016,'doi':'10.1021/acs.chemmater.6b02666','doi_evidence':'Local bibliographic manifest title match; not used to import experimental values.','role':'Original wz-core and wz-CdS flash preparations','status':'Original source locally indexed; full original method not inspected in this audit','gaps':['Upstream stock recipes and abbreviated TDPA identity remain to verify against original.']},{'reference':'13','title':'Flash Synthesis of CdSe/CdS Core-Shell Quantum Dots','authors':'Cirillo et al.','year':2014,'journal_locator':'Chem.Mater.26,1154-1160','role':'Original zb-CdS flash method','status':'Bibliographic reference read; original method not inspected in this audit','gaps':['Adapted method only; external conditions not inherited without inspection.']},{'reference':'22-25','role':'Optical sizing and absorption-constant/yield calibration','status':'Cited basis identified; calibration sources not fully rederived or independently reviewed','gaps':['3nm core is author-derived, and chemical yields retain the paper stated assumptions.']},{'reference':'29','role':'Wz-core phosphonate/phosphonate-anhydride surface termination','status':'Cited claim reviewed in main5; underlying NMR paper not independently inspected','gaps':['Surface termination is prior-study attribution, not a fresh measurement of each current sample.']},{'reference':'17,32,33; SI1-2','role':'Kinetic model antecedents and solubility interpretation','status':'Citations read; antecedent papers not independently reviewed','gaps':['Current SI model reviewed; no reproduction or transfer of unstated model constants.']}]
gaps=['All16source pages were read and visually reviewed; this is not proof of full laboratory reproducibility.','Unreported stock preparation, acquisition detail and sample identity remain unresolved as enumerated in records.','All8numbered figures and both tables are inventoried; exact continuous spectra and plotted yield/simulation coordinate arrays are not digitized. Only explicitly stated numerical facts and labels are transcribed.','Inherited blank/low-OA conditions are protocol context, not separately quantified control batch records.','Three seed-load variants share the same unassigned ZnSe characterization context; never count repeated contextual observations as three independently measured outcomes.','Original upstream referenced preparations not independently read; no omissions filled from memory.','Source original figures/rights remain separate from factual metadata; full source text and page renders are private review artifacts.']
coverage={'schema_version':'1.0.0','paper':{'doi':D,'title':'Mechanistic Insights in Seeded Growth Synthesis of Colloidal Core/Shell Quantum Dots','authors':['Igor Nakonechnyi','Michael Sluydts','Yolanda Justo','Jacek Jasieniak','Zeger Hens'],'year':2017,'journal':'Chemistry of Materials','volume':29,'pages':'4719-4727'},'review_date':'2026-09-17','documents':docs,'recipe_inventory':invent,'figures':figs,'tables':tables,'characterization_inventory':chars,'simulation_inventory':sim,'evidence_conflicts':conflicts,'unresolved_referenced_methods':refs,'coverage_status':'all_main_and_si_pages_reviewed_all_items_inventoried_remaining_data_and_upstream_gaps_explicit','coverage_dimensions':{'main_pages_read':9,'main_pages_visually_reviewed':9,'si_pages_read':7,'si_pages_visually_reviewed':7,'numbered_figures_inventoried':8,'tables_inventoried':2,'unnumbered_graphical_items':2,'canonical_method_variant_control_records':17,'standalone_verified_physical_batch_ids':0,'exact_curve_arrays_digitized':False,'upstream_reference_methods_complete':False},'remaining_gaps':gaps,'public_export_policy':'Do not publish source_path, full-text files, page renders or private review tree wholesale. Canonical factual records and separately managed attributed figure crops are distinct outputs.'}
coverage['independent_audit']='Independent source audit by experimental_frontier on 2026-09-17: main recipe quantities, WZ/ZB separation, Table 1 and SAED joins checked; relative centrifugal-force units normalized, low-OA copied high-OA notes removed, and SI control addition order retained as partial. See audit.md. Source conflicts and unassigned sample links remain explicit.'
for a in crops:a['visual_review']=True;a['visual_review_note']='Original whole page and crop contact sheet inspected; axes/captions/scale bars preserved.'
write('crop-manifest.json',crops);write('coverage.json',coverage)
write('handoff-manifest.json',{'record_paths':[str(R/'canonical'/(r['record_id']+'.json')) for r in records],'source_review_scope':'All9main+7SI pages;17method/variant/control records, not17independent runs.','files':[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [R/'coverage.json',R/'canonical-validation.json',R/'crop-manifest.json']],'ready_for_independent_review':True})
print(json.dumps(coverage['coverage_dimensions'],indent=2))
