"""Banerjee and Wong 2003: nine-page main and matched one-page SI, private curation."""
from pathlib import Path
from copy import deepcopy
import sys,json,hashlib
B=Path(__file__).resolve().parent;S=B.parents[3]/'recipe-atlas';sys.path.insert(0,str(S/'scripts'))
from record_helpers import record,source,ev,fact,qty,material,operation,state,product,measurement
from dataset_lib import validate_record
SID='banerjee2003';PRE='banerjee-2003-';FORMULA='CdTe/MWNT'
SRC=source(SID,'10.1021/ja035980c','In Situ Quantum Dot Growth on Multiwalled Carbon Nanotubes','Sarbajit Banerjee; Stanislaus S. Wong',2003,si='Matched supplied one-page Supporting Information: infrared spectrum of oxidized MWNTs. Identity supported by embedded metadata naming ja035980c, main-paper SI declaration and matching spectrum subject. Fully read and visually inspected; no added synthesis recipe.')
SRC['main_status']='All nine main pages read as text and original images, including eight figures/captions and references 1–43; matched one-page SI also read and visually inspected. Independent audit pending.'
def E(p,s):return ev(SID,f'Main PDF p. {p}, printed p. {10341+p}, {s}')
def SI(s):return ev(SID,'Matched SI PDF p. 1, '+s)
OX=E(2,'Experimental Section, nanotube processing');SYN=E(2,'Experimental Section, heterostructure synthesis');EM=E(3,'Electron Microscopy');OPT=E(3,'Optical Spectroscopy')+E(4,'Optical Spectroscopy continuation');XP=E(3,'X-ray Photoelectron Spectroscopy');XD=E(3,'X-ray Diffraction');CTRL=E(8,'Oxidation control experiments');MORPH=E(5,'Figure 3')+E(6,'Figure 4 and microscopy interpretation')+E(7,'Morphology discussion')+E(8,'Morphology continuation');XPS=E(7,'Figure 5i')+E(8,'XPS interpretation');XRD=E(7,'Figure 5ii')+E(8,'XRD interpretation');RAM=E(7,'Figure 6')+E(8,'Raman interpretation')+E(9,'Raman continuation');UV=E(8,'Figure 7')+E(9,'Electronic spectroscopy');MECH=E(2,'Coordination and synthesis rationale')+E(7,'Diffusion-limited growth')+E(8,'Figure 8 and morphology discussion')+E(9,'Growth interpretation and conclusion')
def Q(v=None,u='',e=SYN,**kw):return qty(v,u,deepcopy(e),**kw)
def F(v=None,e=SYN,**kw):return fact(v,deepcopy(e),**kw)
CHEM={
 'mwnt-pristine':('Pristine/raw multiwalled carbon nanotubes; MER Corporation','C',OX),
 'mwnt-oxidized':('Aggressively oxidized and purified MWNTs; variable oxygenated surface',None,OX),
 'mwnt-mild':('Mildly oxidized MWNT comparison; preparation unspecified',None,CTRL),
 'potassium-permanganate':('Potassium permanganate','KMnO4',OX),
 'sulfuric-acid':('Sulfuric acid','H2SO4',OX),
 'hydrochloric-acid':('Hydrochloric acid solution, 35%; concentration basis unreported','HCl',OX),
 'hydrofluoric-acid':('Hydrofluoric acid solution, 10%; concentration basis unreported','HF',OX),
 'water':('Distilled water','H2O',OX),
 'cadmium-oxide':('Cadmium oxide','CdO',SYN),
 'tdpa':('Tetradecylphosphonic acid','C14H31O3P',SYN),
 'topo':('Trioctylphosphine oxide','C24H51OP',SYN),
 'top':('Trioctylphosphine','C24H51P',SYN),
 'tellurium-source':('Tellurium source in TOP; starting form and solution speciation unreported',None,SYN),
 'te-top-stock':('Te solution in trioctylphosphine; composition and concentration unspecified',None,SYN),
 'argon':('Argon','Ar',SYN),
 'toluene':('Toluene','C7H8',SYN),
 'methanol':('Methanol','CH4O',SYN),
 'ethanol':('Ethanol for electron microscopy specimens','C2H6O',EM),
 'dimethylformamide':('N,N-Dimethylformamide for composite optical dispersion','C3H7NO',OPT),
 'ptfe-membrane':('PTFE filtration membrane; pore size 0.2 µm',None,SYN),
 'composite-specimen':('CdTe nanocrystal–oxidized MWNT heterostructure',FORMULA,SYN),
 'washings-specimen':('CdTe nanocrystals in toluene washings; population may include detached crystals','CdTe',UV+SYN),
 'no-tube-specimen':('CdTe grown without nanotubes; comparison preparation not fully reproduced','CdTe',E(9,'Electronic spectroscopy comparison'))
}
def C(i,role,stage='synthesis',notes=None,e=None,quantities=None):
 n,f,default=CHEM[i];return material(i,n,f,role,stage,deepcopy(e or default),quantities=quantities,notes=notes or [])
def base(k,title,kind='observation',method='Source-scoped characterization and interpretation'):
 r=record(PRE+k,'Banerjee & Wong (2003) · '+title,FORMULA,'CdTe nanocrystals grown on oxidized multiwalled carbon nanotubes',method,deepcopy(SRC),'Complete nine-page main and matched one-page SI',kind)
 r['schema_version']='1.3.0';r['collection']='reviewed_literature';r['material'].update(elements=['Cd','Te','C','O'],components=['CdTe','MWNT'],architecture='heterostructure')
 r['lineage'].update(source_group=SID,recipe_family='banerjee2003-cdte-mwnt')
 r['intended_target']['composition']=F(FORMULA,E(1,'Abstract'),note='Heterostructure descriptor, not a stoichiometric bulk compound or atomically refined junction.')
 r['intended_target']['host']=F('Oxidized multiwalled carbon nanotubes with oxygenated surface sites',OX,note='Oxygen content and functional-group coverage vary; no exact molecular formula or site pattern is determined.')
 r['quality'].update(review_status='imported_unreviewed',review_scope='Complete supplied main and matched SI read and visually inspected. No cited external full texts or new downloads used. Independent audit and publication pending.',missing_fields=['No chemical masses, Cd:Te ratio, exact TDPA ratio, Te/TOP stock concentration or injection volume, isolated yield or raw spectral arrays are supplied.','No measured atom coordinates, unit-cell refinement, quantitative phase fraction, sample-specific complete particle distribution, electronic transport or photovoltaic device data are supplied.','Main procedures are partial literature descriptions; referenced external protocols do not fill unreported conditions.'],conflicts=[],requested_tasks=['precursor_selection','partial_protocol']if kind=='literature_protocol'else[],experimental_outcome='reported_product'if kind=='literature_protocol'else'not_established')
 r['context_links']=[{'label':'Complete source review','url':'../paper-review.html?id='+SID,'relation':'Original figures, supplied SI, specimen distinctions and source limitations.'}]
 return r
def add(r,i,action,label,inputs,out,e,pars=None,stage='synthesis',desc='',env=None,end=None,kind='reaction_batch',depends=None,retain=False,parents=None):
 if out:r['material_states'].append(state(out,label+' output',inputs if parents is None else parents,kind))
 r['operations'].append(operation(i,action,label,deepcopy(e),inputs,[out]if out else[],depends=depends if depends is not None else([r['operations'][-1]['id']]if r['operations']else[]),parameters=pars or{},stage=stage,description=desc,environment=F(env,e),endpoint=F(end,e),retained_fraction=out if retain else None))
def P(r,i,label,e,formula=FORMULA,st=None,explicit=False,notes=None):
 p=product(i,formula,deepcopy(e),link='explicit'if explicit else'general_context',state=st,notes=notes or[]);p['source_sample_label']=label;r['products'].append(p);return p
def M(r,i,s,prop,v,u,e,tech='Source-reported observation',conditions='',**kw):r['measurements'].append(measurement(i,s,prop,Q(v,u,e,**kw),tech,deepcopy(e),conditions))
def T(r,i,s,prop,v,e,tech='Source-reported observation',conditions='',**kw):r['measurements'].append(measurement(i,s,prop,F(v,e,**kw),tech,deepcopy(e),conditions))
def link(r,k,title,rel):r['context_links'].append({'label':title,'url':'../records/'+PRE+k+'.html','relation':rel})
records=[]
def oxidation(r):
 r['materials']=[C('mwnt-pristine','substrate','precursor_preparation',notes=['MER Corporation; diameter, wall count, length, batch mass and starting impurity concentrations are absent.']),C('potassium-permanganate','oxidant','precursor_preparation'),C('sulfuric-acid','reaction_medium','precursor_preparation'),C('hydrochloric-acid','purification_reagent','precursor_preparation'),C('hydrofluoric-acid','purification_reagent','precursor_preparation'),C('water','solvent','precursor_preparation')]
 for acid,percentage in [('hydrochloric-acid',35),('hydrofluoric-acid',10)]:
  r['stocks'].append({'id':acid+'-solution','name':CHEM[acid][0],'components':[{'material_id':acid,'quantities':{}},{'material_id':'water','quantities':{}}],'concentrations':{'source_percentage':Q(percentage,'%',OX,qualifier='Mass/volume/molar percentage basis is not specified; no conversion is inferred.')},'preparation_operation_ids':[],'scope':'Source processing solution; preparation, dilution volume and stock manufacturer are not reported. Water identifies the solution medium without a reconstructed formulation.','evidence':deepcopy(OX)})
 add(r,'oxidize','oxidative_nanotube_processing','Treat the MWNTs with KMnO4/H2SO4',['mwnt-pristine','potassium-permanganate','sulfuric-acid'],'oxidized-suspension',OX,{'duration':Q(u='h',e=OX),'temperature':Q(u='°C',e=OX)},stage='precursor_preparation',desc='Vigorous/aggressive treatment follows cited Hiura et al. reference 35. Oxidant/acid ratio, concentrations, quantities, temperature, duration, addition order and endpoint are absent; the external full procedure was not supplied.')
 add(r,'acid-hcl','hydrochloric_acid_processing','Process the oxidized material with 35% HCl',['oxidized-suspension','hydrochloric-acid-solution'],'hcl-processed',OX,{'concentration':Q(35,'%',OX,qualifier='Percentage basis unspecified.'),'duration':Q(u='min',e=OX)},stage='precursor_preparation',desc='Successive HCl then HF processing is reported. Acid amount, dwell time, temperature and intermediate separation/washing are unreported.')
 add(r,'acid-hf','hydrofluoric_acid_processing','Process next with 10% HF',['hcl-processed','hydrofluoric-acid-solution'],'hf-processed',OX,{'concentration':Q(10,'%',OX,qualifier='Percentage basis unspecified.'),'duration':Q(u='min',e=OX)},stage='precursor_preparation',desc='No assumption of equal volumes, pH endpoint or identical treatment conditions to HCl.')
 add(r,'wash-tubes','water_washing','Wash the processed MWNTs extensively with distilled water',['hf-processed','water'],'washed-tubes',OX,{'wash_count':Q(u='cycles',e=OX),'water_volume':Q(u='mL',e=OX)},stage='precursor_preparation',retain=True,desc='Extensive washing is stated without a numerical count, volume, separation method or final pH.')
 add(r,'dry-tubes','oven_drying','Dry the purified nanotubes in a 150 °C oven',['washed-tubes'],'oxidized-tubes',OX,{'temperature':Q(150,'°C',OX),'duration':Q(u='h',e=OX)},stage='precursor_preparation',desc='A drying oven is reported; duration, atmosphere, pressure and cooling/storage are not specified.')
r=base('oxidation','Oxidation and purification of the nanotube template','procedure','Oxidative surface functionalization and purification');oxidation(r)
p=P(r,'oxidized','Purified, strongly oxidized MWNT precursor',OX,formula=None,st='oxidized-tubes',explicit=True);p['surface']=F('Expected mixture of carboxylic acids, alcohols and ketones at open ends and defect sites',OX,status='author_derived')
M(r,'oxygen','oxidized','source_oxygen_atomic_fraction',None,'atomic %',CTRL,minimum=5,maximum=6,approximate=True,tech='XPS',conditions='Strongly oxidized MWNT context associated with the presented heterostructure results; no exact aliquot match or uncertainty is supplied.')
T(r,'cleaning','oxidized','purification_observation','Treatment removes almost all metal impurities such as iron and a substantial amount of amorphous carbon. Residual metal was below detection by XPS/EDS; numerical detection limits are not given.',OX+E(5,'Microscopy continuation'))
T(r,'surface-sites','oxidized','oxidized_nanotube_morphology','Most tube ends are opened/derivatized; outer layers at defects and near tips are partly removed, leaving serrated oxygenated edges.',OX+E(4,'Microscopy discussion'))
link(r,'infrared','Original precursor infrared spectrum','Matched SI applies to the oxidized MWNT precursor.');records.append(r)

r=base('growth','In situ CdTe growth on strongly oxidized MWNTs','literature_protocol','Coordination-mediated hot injection on a nanotube template');oxidation(r)
r['lineage']['parent_record_id']=PRE+'oxidation'
r['materials'] += [C('mwnt-oxidized','host_matrix',notes=['Identifies the output of the included oxidation procedure; no second fresh nanotube dose is added.']),C('cadmium-oxide','metal_precursor',quantities={'mass':Q(u='g')}),C('tdpa','ligand',quantities={'mass':Q(u='g'),'tdpa_cd_ratio':Q(qualifier='Substoichiometric TDPA is stated, but the numerical ratio and stoichiometric reference are not defined.')}),C('topo','solvent',quantities={'mass':Q(u='g')}),C('top','solvent',notes=['Solvent/ligand of the Te stock; no independently reported quantity or purification.']),C('tellurium-source','chalcogen_precursor',notes=['The paper specifies a Te solution in TOP; elemental form, upstream synthesis and exact dissolved species are not stated. Do not replace this unknown by a verified TOPTe structure.']),C('te-top-stock','precursor_stock',quantities={'volume':Q(u='mL'),'concentration':Q(u='mol/L')}),C('argon','process_gas'),C('toluene','solvent','workup'),C('methanol','antisolvent','workup'),C('ptfe-membrane','filtration_medium','workup')]
r['stocks'].append({'id':'te-in-top','name':'Te solution in trioctylphosphine','components':[{'material_id':'tellurium-source','quantities':{}},{'material_id':'top','quantities':{}}],'concentrations':{'te_concentration':Q(u='mol/L')},'preparation_operation_ids':[],'scope':'Stock is named but its chemical starting form, dissolution/preparation conditions, purity, amount, concentration and storage are absent. te-top-stock is the same solution identity, not an extra independent reagent.','evidence':deepcopy(SYN)})
for op in r['operations']:
 op['description']='Included upstream template preparation; same source procedure as the linked oxidation record, not another independent batch. '+op['description']
add(r,'mix-cd','precursor_template_mixing','Mix oxidized MWNTs with CdO and TDPA in TOPO',['oxidized-tubes','cadmium-oxide','tdpa','topo'],'cadmium-template-mixture',SYN,desc='No individual masses, nanotube concentration or metal/ligand ratio is given. Substoichiometric TDPA is intended to leave Cd available for coordination to oxygenated nanotube groups; actual coordination fraction is not measured.')
add(r,'heat','precursor_coordination_heating','Heat to 320 °C under argon with vigorous stirring',['cadmium-template-mixture','argon'],'hot-cadmium-template',SYN,{'temperature':Q(320,'°C'),'duration':Q(u='min')},env='Argon',desc='TOPO is the medium. Heating rate, dwell, gas flow, pressure and stirring speed are not supplied.',parents=['cadmium-template-mixture'])
add(r,'adjust','injection_temperature_adjustment','Bring the mixture to the stated 300 °C injection temperature',['hot-cadmium-template'],'injection-ready-mixture',SYN,{'target_temperature':Q(300,'°C')},desc='The text moves from heating at 320 °C to injection at 300 °C; this transition is represented to preserve both conditions. Its timing, cooling method and independently stated atmosphere are absent.')
add(r,'injection','tellurium_stock_injection','Inject the Te solution in TOP at 300 °C',['injection-ready-mixture','te-in-top'],'injected-mixture',SYN,{'temperature':Q(300,'°C'),'injection_volume':Q(u='mL'),'injection_duration':Q(u='s')},desc='No invented elemental-Te powder addition, stock concentration, TOPTe speciation, feed volume or injection speed. Argon is explicit for the preceding 320 °C preparation; continued atmosphere is not independently restated.')
add(r,'grow','nanocrystal_growth','Grow the nanocrystals at 250 °C for 20 min',['injected-mixture'],'grown-mixture',SYN,{'temperature':Q(250,'°C'),'duration':Q(20,'min')},desc='The source does not specify the transition to 250 °C, thermal recovery, aliquots, post-injection atmosphere or stirring rate.')
add(r,'stop','heat_source_removal','Remove the heating source after growth',['grown-mixture'],'unheated-mixture',SYN,desc='Heat-source removal is the stated growth termination action; no chemical quench is reported.')
add(r,'cool','cooling','Cool the reaction mixture to 50 °C',['unheated-mixture'],'cooled-mixture',SYN,{'target_temperature':Q(50,'°C'),'cooling_rate':Q(u='°C/min')},stage='workup',desc='Cooling medium, duration and atmosphere are absent; do not draw an ice or water bath as an observed step.')
add(r,'solvate','toluene_addition','Add 5 mL of toluene at 50 °C',['cooled-mixture','toluene'],'toluene-mixture',SYN,{'temperature':Q(50,'°C'),'toluene_volume':Q(5,'mL')},stage='workup',desc='This explicit 5 mL dose is separate from the later copious toluene washes.')
add(r,'precipitate','methanol_precipitation','Add methanol to precipitate the solid material',['toluene-mixture','methanol'],'precipitated-mixture',SYN,{'methanol_volume':Q(u='mL')},stage='workup',desc='Solid residue contains both functionalized nanotubes and CdTe nanocrystals not attached to tubes. Methanol amount, solvent ratio and precipitation time are unreported.')
add(r,'filter','membrane_filtration','Filter the residue through a 0.2 µm PTFE membrane',['precipitated-mixture','ptfe-membrane'],'retained-solid',SYN,{'membrane_pore_size':Q(.2,'µm')},stage='workup',retain=True,parents=['precipitated-mixture'],desc='The membrane is equipment, not a chemical constituent of the isolated product. No filtration pressure or apparatus is specified.')
add(r,'wash','toluene_washing','Wash away unattached nanocrystals with copious toluene',['retained-solid','toluene'],'washed-heterostructure',SYN,{'toluene_wash_volume':Q(u='mL'),'wash_count':Q(u='cycles')},stage='workup',retain=True,desc='Retain functionalized heterostructures on the membrane. Toluene washings contain removed CdTe and were also used for optical comparison; no fixed wash volume or number is reported.')
r['material_states'].append(state('cdte-washings','Removed CdTe in toluene washings',['retained-solid','toluene'],'fraction'));r['operations'][-1]['outputs'].append('cdte-washings')
add(r,'final-dry','product_drying','Dry the retained heterostructures for characterization',['washed-heterostructure'],'final-composite',SYN,{'temperature':Q(u='°C'),'duration':Q(u='h')},stage='workup',desc='Final drying conditions, product mass, storage and passivation details are not supplied; do not reuse the nanotube precursor drying temperature of 150 °C.')
p=P(r,'composite','Isolated CdTe–MWNT heterostructure',SYN,st='final-composite',explicit=True);p['phase']=F('CdTe predominantly wurtzite; some zinc-blende crystals and/or stacking faults likely; graphitic MWNT host',XRD+MORPH);p['morphology']=F('Irregular/anisotropic CdTe nanocrystals at nanotube tips, etched sidewalls and multi-tube junctions',MORPH)
P(r,'washings','CdTe nanocrystals removed in toluene washings',SYN,formula='CdTe',st='cdte-washings',explicit=True,notes=['Not the retained composite and not necessarily identical to the separate no-nanotube growth comparison.'])
M(r,'long-axis','composite','bound_nanocrystal_long_axis_range',None,'nm',E(8,'Morphology discussion'),minimum=1,maximum=9,tech='Electron microscopy',conditions='Study-wide range for attached nanocrystals, not a mean diameter or per-crystal size/shape pairing.')
M(r,'aspect','composite','bound_nanocrystal_aspect_ratio_range',None,'dimensionless',E(8,'Morphology discussion'),minimum=1,maximum=5,tech='Electron microscopy',conditions='Independent reported range; do not combine extrema to infer short axes.')
T(r,'tdpa-role','composite','author_substoichiometric_tdpa_role','Substoichiometric TDPA allows some Cd to coordinate oxygenated MWNT groups, especially carboxylic acids and alcohols; remaining phosphonic-acid ligands also participate in nanocrystal stabilization.',SYN,status='author_derived')
T(r,'junctions','composite','observed_junction_architecture','Nanocrystals bridge neighboring tubes or bundles and cover tips and sidewalls; geometry and coverage are heterogeneous, without a universal junction separation or connectivity count.',MORPH)
r['quality']['missing_fields']+=['Oxidation reagent amounts/concentrations/times, intermediate handling, TDPA:Cd value, Te solution formulation, injection speed/volume, post-injection gas conditions, solvent wash amounts and final drying are not supplied.']
for k,title in [('oxidation','Nanotube precursor preparation'),('electron-microscopy','TEM/HRTEM evidence'),('xrd','Diffraction and phase evidence'),('xps','Surface chemical evidence'),('raman','Raman properties'),('uv-visible','Optical spectra and washings'),('mechanisms','Chemical intuition')]:link(r,k,title,'Source-specific procedure or interpretation with explicit sample scope.')
records.append(r)

r=base('electron-microscopy','TEM and HRTEM specimen preparation and structural evidence','procedure','Transmission electron microscopy')
r['materials']=[C(i,'specimen','characterization')for i in ['mwnt-pristine','mwnt-oxidized','composite-specimen']]+[C('ethanol','solvent','characterization')]
add(r,'disperse','ethanolic_sample_preparation','Prepare separate ethanolic microscopy specimens',[m['id']for m in r['materials']],'ethanolic-specimens',EM,stage='characterization',kind='sample_set',desc='Sample droplets come from ethanolic solutions. Dispersion concentration, sonication, mixing, dilution and specimen-to-grid quantities are not reported; the separate controls and product are not physically mixed.')
add(r,'deposit','tem_grid_deposition','Dry droplets on lacey-carbon-coated 300-mesh Cu grids',['ethanolic-specimens'],'tem-grids',EM,{'grid_mesh':Q(300,'mesh',EM)},stage='characterization',kind='sample_set',desc='Grid is copper with a lacey carbon film. Drying temperature/time and drop volume are absent; support carbon/Cu are not automatically product constituents.')
add(r,'image-tem','tem_acquisition','Acquire low-resolution TEM images',['tem-grids'],'tem-data',EM,{'accelerating_voltage':Q(120,'kV',EM)},stage='characterization',kind='analysis_data',desc='Philips CM12 with EDAX capabilities. Magnification, dose, exposure and camera settings are not supplied.')
add(r,'image-hrtem','hrtem_acquisition','Acquire high-resolution TEM images',['tem-grids'],'hrtem-data',EM,{'accelerating_voltage':Q(200,'kV',EM)},stage='characterization',kind='analysis_data',depends=['deposit'],desc='JEOL 2010F equipped with Oxford INCA EDS. No electron diffraction/SAED pattern, fitted lattice spacing table or atomic coordinate reconstruction is supplied.')
for i,label,formula,e in [('pristine','Figure 1a pristine MWNT','C',E(3,'Figure 1a')),('oxidized','Figure 1b–d processed MWNT',None,E(3,'Figure 1b–d')),('composite','Figures 2c–e, 3 and 4 composite',FORMULA,MORPH)]:P(r,i,label,e,formula=formula,explicit=True)
for tag,sz,sample,p in [('1a',20,'pristine',3),('1b',125,'oxidized',3),('1c',7,'oxidized',3),('1d',8,'oxidized',3),('2c',180,'composite',4),('2d',75,'composite',4),('2e',112,'composite',4),('3a',5,'composite',5),('3a-inset',5,'composite',5),('3b',20,'composite',5),('3c',5,'composite',5),('3d',10,'composite',5),('4a',20,'composite',6),('4b',10,'composite',6),('4c',10,'composite',6)]:M(r,'scale-'+tag,sample,'micrograph_scale_bar',sz,'nm',E(p,'Figure '+tag+' caption'),tech='Printed image scale',conditions='Scale bar, not a measured particle diameter.')
T(r,'pristine','pristine','pristine_mwnt_structure','Highly crystalline graphitic lattice is visible in the original untreated tube sidewalls; precursor images are distinct from the product images.',E(3,'Figure 1a')+E(5,'Microscopy discussion'))
T(r,'oxidation','oxidized','oxidation_morphology','Open tube tips, serrated edges and partial outer-wall removal are shown; arrows identify etched regions. Chemical group assignments use other evidence and author interpretation, not direct identification of oxygen atoms in the micrograph.',E(3,'Figure 1')+E(4,'Microscopy discussion'))
T(r,'figure2','composite','figure2_tem_motifs','2c: sidewall QD coverage on a bundle; 2d: sidewall crystals including sites near a tip; 2e: arrows mark nanocrystal-mediated junctions.',E(4,'Figure 2c–e'))
T(r,'figure3','composite','figure3_hrtem_motifs','3a: well-defined CdTe lattice fringes and interface; inset is a different composite. 3b: elongated/irregular crystal at an opened tip on a carbon support film. 3c: growth at a defect where acid etched through outer layers. 3d: crystals at exposed serrated edges.',E(5,'Figure 3')+E(6,'Microscopy interpretation'))
T(r,'figure4','composite','figure4_hrtem_motifs','4a: a nanocrystal in a junction between two bundles, arrows identify irregular crystals; inset is EDS. 4b/c: extensive sidewall coverage. The displayed motifs are distinct local regions, not one universal atomistic junction.',E(6,'Figure 4'))
T(r,'phase','composite','hrtem_phase_assignment','Authors describe predominantly wurtzite CdTe, with at least some crystals appearing cubic zinc blende; no phase fractions or exact lattice metrics are tabulated.',E(6,'HRTEM interpretation'),status='author_derived')
T(r,'site-density','composite','relative_attachment_density','Higher particle density near tips is attributed to increased oxygenated-group density and curvature-enhanced reactivity, while aggressive oxidation also enables widespread sidewall growth.',E(5,'Microscopy discussion')+E(6,'Continuation'),status='author_derived')
records.append(r)

r=base('sem','Scanning electron microscopy of CdTe–MWNT junctions','procedure','Field-emission scanning electron microscopy')
r['materials']=[C('composite-specimen','specimen','characterization')]
add(r,'deposit','sem_specimen_mounting','Drop-dry specimens on Cu grids over a Be plate',['composite-specimen'],'sem-mounted',EM,stage='characterization',desc='Cu grids are held over a beryllium plate in a homemade holder. No solvent, coating, droplet quantity or drying conditions specific to SEM are reported; the TEM ethanol preparation is not automatically reused.')
add(r,'image','sem_acquisition','Image on the Leo 1550 field-emission microscope',['sem-mounted'],'sem-data',EM,{'accelerating_voltage':Q(None,'kV',EM,minimum=2,maximum=10),'working_distance':Q(2,'mm',EM)},stage='characterization',kind='analysis_data')
P(r,'composite','Figure 2a–b SEM composite regions',E(4,'Figure 2a–b'),explicit=True)
M(r,'scale-2a','composite','sem_scale_bar',100,'nm',E(4,'Figure 2a caption'),tech='Printed SEM scale')
M(r,'scale-2b','composite','sem_scale_bar',200,'nm',E(4,'Figure 2b caption'),tech='Printed SEM scale')
T(r,'motifs','composite','sem_junction_morphology','Figure 2a shows a crystal near a tube tip; 2b shows a nanocrystal-mediated junction with nanotube bundles. Arrows identify CdTe and Cd/Te EDS signals support the assignment.',E(4,'Figure 2 caption'))
records.append(r)

r=base('eds','Elemental spectroscopy and support-signal limitations','procedure','Energy-dispersive X-ray spectroscopy')
r['materials']=[C('composite-specimen','specimen','characterization'),C('mwnt-oxidized','specimen','characterization')]
add(r,'analyze','eds_acquisition','Analyze separate composite and purified-nanotube specimens',[m['id']for m in r['materials']],'eds-data',EM+E(6,'Figure 4a inset and EDS discussion'),stage='characterization',kind='analysis_data',desc='Philips CM12 EDAX and JEOL 2010F/Oxford INCA capabilities are named, but the paper does not uniquely assign every elemental result to one instrument. Acquisition time, area, quantification/calibration and detection limits are absent; Cu/carbon supports contribute possible signals.')
P(r,'composite','Figure 4a inset composite EDS',E(6,'Figure 4a inset'),explicit=True);P(r,'oxidized','Purified MWNT impurity screening',OX,formula=None)
T(r,'elements','composite','reported_eds_elements','Cd and Te confirm the nanocrystal component. The prose also reports P and attributes it to TDPA as a secondary ligand; phosphorus-source attribution is the authors’ interpretation.',E(6,'EDS discussion'))
T(r,'plotted-elements','composite','figure4_eds_visible_labels','Visible labels include C, O, Cu, Cd and Te. The plotted inset does not establish calibrated stoichiometry, and a Cu signal must not be treated as intentional product doping.',E(6,'Figure 4a EDS inset'))
T(r,'energy-units','composite','eds_axis_unit_conflict','Figure 4 caption calls the energy axis eV, while the inset runs approximately 0–10 with no visible unit label. The Cd/Te/Cu peak placement suggests an inconsistent scale convention; original caption and plot are retained without silently rescaling.',E(6,'Figure 4 caption and inset'))
T(r,'metal-limit','oxidized','residual_metal_detection_statement','Residual catalyst metals were below XPS/EDS detectable limits; numerical limits, tested metal list and quantified removal percentages are not given.',OX+E(5,'Microscopy continuation'))
r['quality']['conflicts']=['EDS caption states eV despite an unlabeled approximately 0–10 inset scale. No calibrated energy rescaling is asserted.'];records.append(r)

r=base('xps','Surface chemistry and precursor oxygen-content evidence','procedure','X-ray photoelectron spectroscopy')
r['materials']=[C(i,'specimen','characterization')for i in ['composite-specimen','mwnt-oxidized','mwnt-mild']]
add(r,'mount','xps_sample_mounting','Mount separate specimens on stainless-steel holders',[m['id']for m in r['materials']],'xps-mounted',XP,stage='characterization',kind='sample_set',desc='Conductive double-sided tape attaches samples to stainless-steel holders in a Kratos DS800. Specimen loading, film thickness, tape composition and calibration standard are not given.')
add(r,'evacuate','xps_vacuum_preparation','Evacuate the XPS analysis chamber',['xps-mounted'],'xps-ready',XP,{'base_pressure':Q(5e-9,'torr',XP,approximate=True)},stage='characterization',kind='sample_set',env='XPS vacuum chamber',desc='This is analytical base pressure, not synthesis or drying pressure. No degassing or sputtering preparation is stated.')
add(r,'survey','xps_survey_acquisition','Acquire the survey spectra with Mg Kα radiation',['xps-ready'],'xps-survey',XP,{'pass_energy':Q(80,'eV',XP),'energy_step':Q(.75,'eV',XP)},stage='characterization',kind='analysis_data',desc='Hemispherical electron energy analyzer. X-ray photon energy, charge correction, acquisition time, takeoff angle and fitting background are not supplied.')
add(r,'high-resolution','xps_high_resolution_acquisition','Acquire high-resolution elemental spectra',['xps-ready'],'xps-high-resolution',XP,{'pass_energy':Q(10,'eV',XP),'energy_step':Q(.1,'eV',XP)},stage='characterization',kind='analysis_data',depends=['evacuate'],desc='Figure 5i shows C 1s, O 1s, Te 3d5/2 and Cd 3d5/2. Figure curves are retained rather than fabricating individual fit components or an atomic-percent table.')
P(r,'composite','Figure 5i CdTe–MWNT heterostructure',XPS,explicit=True);P(r,'strong','Strongly oxidized MWNT precursor',CTRL,formula=None);P(r,'mild','Mildly oxidized MWNT control',CTRL,formula=None)
M(r,'cd-binding','composite','cd_3d5_2_binding_energy',405.22,'eV',E(8,'XPS interpretation'),tech='XPS',conditions='Source fitted CdTe assignment; no fit uncertainty or reference calibration is stated.')
M(r,'strong-oxygen','strong','oxygen_atomic_fraction',None,'atomic %',CTRL,minimum=5,maximum=6,approximate=True,tech='XPS',conditions='Source approximate range for highly oxidized tubes; not composite bulk oxygen stoichiometry.')
M(r,'mild-oxygen','mild','oxygen_atomic_fraction',None,'atomic %',CTRL,minimum=1,maximum=2,approximate=True,tech='XPS',conditions='Separate partially oxidized control; no exact chemical treatment is reproduced.')
T(r,'carbon','composite','author_c1s_surface_assignment','Asymmetric C 1s with a pronounced higher-binding-energy contribution is attributed to carboxylic acids and carboxylate-like surface structures.',XPS,status='author_derived')
T(r,'tellurium','composite','author_te_surface_oxide_assignment','The source assigns Te 3d5/2 oxide features to TeO3, literally. This assignment is retained without substituting TeO2 or treating it as a synthesized, quantitatively identified bulk phase.',XPS,status='author_derived')
T(r,'oxygen-curve','composite','figure5_oxygen_signal_scope','An O 1s high-resolution curve is displayed. The paper provides no exact O peak fit values, component percentages or current-paper quantitative O-species decomposition.',E(7,'Figure 5i'))
T(r,'passivation','composite','author_surface_passivation_limit','Bulky nanotubes cannot occupy every nanocrystal surface site. Authors attribute oxide formation to incomplete passivation and prolonged ambient exposure; the exposure duration and oxide-growth kinetics are not measured.',E(8,'XPS interpretation'),status='author_derived')
T(r,'thermal-decomposition','composite','author_temperature_decomposition_statement','Surface decomposition is expected to accelerate at higher temperatures. No temperature-dependent stability experiment or quantified degradation threshold for this composite is provided.',E(8,'XPS interpretation'),status='author_derived')
M(r,'carboxyl-removal','strong','source_carboxyl_removal_temperature_context',350,'°C',E(8,'Surface stability discussion'),approximate=True,conditions='Authors state heating does not completely remove MWNT carboxyl groups until approximately this temperature. This is contextual discussion, not a prescribed extra anneal or measured stability limit for each sample.')
T(r,'integrity','composite','author_thermal_integrity_expectation','Nanotube and nanocrystal intrinsic structures are expected to remain intact to such temperatures; this expectation is not an independently demonstrated complete thermal-stability series.',E(8,'Surface stability discussion'),status='author_derived')
records.append(r)

r=base('xrd','Diffraction of the CdTe–MWNT heterostructure','procedure','Powder X-ray diffraction')
r['materials']=[C('composite-specimen','specimen','characterization')]
add(r,'acquire','powder_xrd_acquisition','Acquire the composite powder diffraction pattern',['composite-specimen'],'xrd-data',XD,{'radiation_wavelength':Q(1.54,'Å',XD)},stage='characterization',kind='analysis_data',desc='Scintag diffractometer in Bragg configuration with Cu Kα radiation. Scan step/rate, tube voltage/current, specimen holder, standard and refinement are unreported.')
p=P(r,'composite','Figure 5ii CdTe–MWNT powder',XRD,explicit=True);p['phase']=F('Predominantly wurtzite CdTe; possible zinc-blende stacking faults and some zinc-blende crystals; MWNT reflections',XRD)
T(r,'cdte-indices','composite','source_cdte_diffraction_indices','Black labels assign wurtzite CdTe: (100), (002), (101), (110), (103) and (200). The first three overlap in the labeled low-angle group.',E(7,'Figure 5ii indexed pattern'))
T(r,'mwnt-indices','composite','source_mwnt_diffraction_indices','Red labels assign MWNT (002), (101) and (004); the 101/103 label group combines MWNT (red) and CdTe (black) assignments.',E(7,'Figure 5ii indexed pattern'))
T(r,'mixed-phase','composite','source_phase_mixture_limit','Zinc-blende peaks lie close to wurtzite peaks and may overlap; stacking faults and some cubic crystals are likely. No phase-pure assignment or quantitative phase fraction is justified.',XRD)
T(r,'broadening','composite','author_diffraction_broadening_explanation','Peaks broaden relative to bulk because of finite particle size. The paper reports no Scherrer calculation, fitted FWHM list or lattice-constant refinement.',E(8,'Additional Structural Characterization'),status='author_derived')
M(r,'axis-range','composite','figure5ii_displayed_two_theta_range',None,'°',E(7,'Figure 5ii axis'),minimum=20,maximum=70,conditions='Displayed plot range, not a separately stated acquisition scan program.')
records.append(r)

r=base('uv-visible','Electronic spectra of retained composite and removed nanocrystals','procedure','UV–visible spectroscopy')
r['materials']=[C('composite-specimen','specimen','characterization'),C('washings-specimen','specimen','characterization'),C('toluene','solvent','characterization',e=OPT),C('dimethylformamide','solvent','characterization')]
add(r,'dissolve-washings','toluene_optical_specimen','Prepare the CdTe-in-toluene optical specimen',['washings-specimen','toluene'],'toluene-optical-specimen',OPT+UV,stage='characterization',desc='Methods specify CdTe nanocrystals dissolved in toluene and Figure 7 identifies CdTe washings. Exact isolation/redissolution sequence, concentration and blank are not supplied; this does not assert a second independent no-tube synthesis.')
add(r,'disperse-composite','dmf_sonication','Disperse the composite in DMF by sonication',['composite-specimen','dimethylformamide'],'dmf-optical-specimen',OPT,stage='characterization',depends=[],desc='Sonication duration, power, temperature, concentration, solvent volume and sediment handling are not stated.')
add(r,'acquire','uv_visible_acquisition','Measure the two separate electronic spectra',['toluene-optical-specimen','dmf-optical-specimen'],'uv-data',OPT+UV,{'optical_path_length':Q(10,'mm',OPT)},stage='characterization',kind='analysis_data',depends=['dissolve-washings','disperse-composite'],desc='Thermospectronics UV1 at high resolution; quartz cells. Actual spectral resolution, baseline correction, concentration normalization and scattering treatment are absent; samples use different solvents.')
P(r,'composite','Figure 7 upper green curve: composite in DMF',UV,explicit=True);P(r,'washings','Figure 7 lower red curve: CdTe washings in toluene',UV,formula='CdTe',explicit=True)
M(r,'plot-range','composite','figure7_displayed_wavelength_range',None,'nm',E(8,'Figure 7 axis'),minimum=300,maximum=1000,conditions='Printed horizontal tick range; not a fully specified acquisition program.')
T(r,'composite-spectrum','composite','unresolved_exciton_observation','The composite spectrum is featureless and no CdTe exciton can be resolved. This is not evidence of zero CdTe, a measured band gap or an absent absorption cross section.',E(9,'Electronic spectrum discussion'))
T(r,'background','composite','author_exciton_obscuration_explanation','Large nanotube background absorption and variation in attached crystal size/shape are proposed to obscure the exciton.',E(9,'Electronic spectrum discussion'),status='author_derived')
T(r,'washings-heterogeneity','washings','washings_polydispersity_comparison','Optical spectra indicate less monodispersity than approximately 5 nm quasi-spherical crystals grown without nanotubes. The washings are a separate population; no fitted distribution or excitonic peak position is reported.',UV)
T(r,'detachment','washings','author_detached_crystal_hypothesis','Some washed-away crystallites may detach from nanotubes at different growth stages, explaining greater size heterogeneity. This is a proposed origin, not a tracked-particle experiment.',E(9,'Electronic spectrum discussion'),status='author_derived')
T(r,'signal-type','composite','optical_measurement_scope','These are electronic absorption spectra with arbitrary displayed intensity. No photoluminescence, quantum yield, radiative lifetime or carrier-transport measurement is supplied.',UV)
records.append(r)

r=base('infrared','Infrared spectrum of the oxidized MWNT precursor','procedure','Single-reflection ATR infrared spectroscopy')
r['materials']=[C('mwnt-oxidized','specimen','characterization',e=OPT+SI('Spectrum heading'))]
add(r,'acquire','atr_infrared_acquisition','Record the oxidized-nanotube infrared spectrum',['mwnt-oxidized'],'ir-data',OPT+SI('Full spectrum'),stage='characterization',kind='analysis_data',desc='ThermoNicolet Nexus 670 with ZnSe single-reflection ATR accessory. Resolution, scans, background, contact force and specimen preparation are not supplied. Matched SI is an oxidized MWNT spectrum, not a composite/product spectrum.')
P(r,'oxidized','Matched SI: oxidized multiwalled nanotubes',SI('Spectrum heading'),formula=None,explicit=True)
T(r,'axis','oxidized','si_infrared_axis_scope','SI horizontal axis is wavenumber in cm^-1, descending through ticks 2000, 1800, 1600, 1400, 1200, 1000 and 800; vertical intensity is arbitrary with no numeric tick labels.',SI('Spectrum and axis caption'))
T(r,'assignments','oxidized','si_infrared_assignment_limit','The supplied SI gives the curve and axis description without a peak table or specific vibrational assignments. Do not manufacture exact peak positions, carboxyl-band areas or a quantitative functional-group density.',SI('Full page'))
T(r,'identity','oxidized','si_matching_evidence','Main page 9 announces an infrared spectrum of oxidized MWNTs. The supplied SI has that heading and metadata Title naming ja035980csi20030625_041651.doc. It has no standalone title/byline; matching uses metadata and declared contents together.',E(9,'Supporting Information Available')+SI('Heading and document metadata'))
records.append(r)

r=base('raman','Raman response of precursor nanotubes and the composite','procedure','785 nm micro-Raman spectroscopy')
r['materials']=[C('mwnt-oxidized','specimen','characterization'),C('composite-specimen','specimen','characterization')]
add(r,'acquire','micro_raman_acquisition','Acquire separate precursor and composite Raman spectra',[m['id']for m in r['materials']],'raman-data',OPT+RAM,{'excitation_wavelength':Q(785,'nm',OPT),'laser_power':Q(10,'mW',OPT),'confocal_aperture':Q(200,'µm',OPT)},stage='characterization',kind='analysis_data',desc='Jasco Ventuno micro-Raman instrument with diode laser. Power is the stated laser setting, not irradiance; spot size, exposure, spectral resolution, calibration and sample temperature are not provided.')
P(r,'precursor','Figure 6 upper blue: purified oxidized MWNT precursor',RAM,formula=None,explicit=True);P(r,'composite','Figure 6 lower red: CdTe–MWNT product',RAM,explicit=True);P(r,'bulk-reference','Cited bulk CdTe Raman reference',E(8,'Raman discussion and reference 41'),formula='CdTe')
M(r,'lo','composite','cdte_lo_raman_peak',166,'cm^-1',E(8,'Raman interpretation'),tech='Micro-Raman',conditions='Assigned LO-type confined CdTe band, absent in the precursor spectrum.')
M(r,'bulk-lo','bulk-reference','cited_bulk_cdte_lo_peak',170,'cm^-1',E(8,'Raman interpretation and reference 41'),conditions='Cited comparison value, not a separately measured current-paper bulk sample.')
for sample in ['precursor','composite']:
 M(r,'g-'+sample,sample,'nanotube_g_mode',1590,'cm^-1',E(8,'Raman discussion')+E(9,'Continuation'),approximate=True,tech='Micro-Raman')
 M(r,'d-'+sample,sample,'nanotube_disorder_band_range',None,'cm^-1',E(9,'Raman continuation'),minimum=1290,maximum=1320,tech='Micro-Raman',conditions='Source band-position range; not an integrated D/G ratio or spectral width.')
T(r,'lo-absent','precursor','precursor_cdte_band_comparison','The product LO-type band is absent from the precursor MWNT spectrum, supporting formation of the CdTe component.',E(8,'Raman discussion'))
T(r,'confinement','composite','author_raman_confinement_interpretation','Downshift and broadening relative to the cited bulk 170 cm^-1 mode are consistent with confined CdTe clusters, citing earlier studies. No Raman size calibration, phonon-confinement fit or exact FWHM is supplied.',E(8,'Raman discussion'),status='author_derived')
T(r,'plot','composite','figure6_display_scope','Figure 6 uses arbitrary intensities; upper blue precursor and lower red composite curves are vertically separated. No quantitative intensity normalization, D/G ratio or additional overtone assignment is provided.',E(7,'Figure 6'))
records.append(r)

r=base('oxidation-controls','Dependence of attachment on nanotube oxidation')
for i,label,formula in [('strong','Strongly oxidized MWNT growth context',None),('mild','Mildly oxidized MWNT growth control',None),('pristine','Pristine unoxidized MWNT growth control','C'),('raw','Raw-tube control mentioned without separate details','C')]:P(r,i,label,CTRL,formula=formula,notes=['Comparison descriptor, not a newly reconstructed complete recipe or counted independent batch.'])
M(r,'strong-oxygen','strong','precursor_oxygen_atomic_fraction',None,'atomic %',CTRL,minimum=5,maximum=6,approximate=True,tech='XPS')
M(r,'mild-oxygen','mild','precursor_oxygen_atomic_fraction',None,'atomic %',CTRL,minimum=1,maximum=2,approximate=True,tech='XPS')
T(r,'strong-result','strong','nanocrystal_coverage_observation','Aggressive oxidation enables high CdTe surface coverage at ends and numerous sidewall sites; no numerical coverage percentage or site count is supplied.',CTRL)
T(r,'mild-result','mild','nanocrystal_coverage_observation','Very sparse coordinated nanocrystal coverage is reported for mildly oxidized tubes; treatment details and exact growth conditions for each comparison are absent.',CTRL)
T(r,'pristine-result','pristine','nanocrystal_coverage_observation','Few, if any, coordinated crystals were observed on pristine, unoxidized tubes. This qualitative attachment result is not a standardized whole-reaction synthesis failure label.',CTRL)
T(r,'raw-scope','raw','raw_control_scope','Successive growth controls include pristine, raw and mildly oxidized tubes. No distinct raw-tube numerical result or proof of a separate raw-versus-pristine physical batch is given.',CTRL)
T(r,'correlation','strong','author_oxidation_coverage_relationship','Nanocrystal functionalization correlates with degree of oxidation, supporting oxygenated sites as ligands and nucleation sites. No fitted causal coefficient or single-variable quantitative control series is supplied.',CTRL,status='author_derived')
records.append(r)

r=base('free-nanocrystals','Removed nanocrystals and the no-nanotube comparison')
P(r,'washings','CdTe removed during workup in toluene',SYN+UV,formula='CdTe',explicit=True);P(r,'no-tube','CdTe grown without nanotube ligands',E(9,'Electronic spectrum discussion'),formula='CdTe')
M(r,'free-prose-size','washings','free_crystal_prose_size',5,'nm',E(7,'Microscopy discussion')+E(8,'Continuation'),conditions='The earlier discussion calls free washed-away crystals relatively monodisperse and quasi-spherical, 5 nm. No count, width or exact diameter definition is supplied.')
M(r,'no-tube-size','no-tube','no_tube_comparator_prose_size',5,'nm',E(9,'Electronic spectrum discussion'),approximate=True,conditions='Separate comparison crystals grown without nanotubes; complete current-paper preparation is not given.')
T(r,'free-shape','washings','free_crystal_morphology_statement','Earlier prose describes free crystals as quasi-spherical and relatively monodisperse, attributing their origin mainly to cadmium–phosphonic-acid precursor growth.',E(7,'Microscopy discussion')+E(8,'Continuation'))
T(r,'later-comparison','washings','washings_heterogeneity_statement','Later optical discussion describes washings as less monodisperse than no-tube crystals and proposes contributions from crystals detached at different times. These descriptions are preserved without collapsing washings into the no-tube population.',E(9,'Electronic spectrum discussion'))
T(r,'no-tube-recipe','no-tube','no_tube_comparator_recipe_limit','No separate measured precursor charges, heating sequence, workup or sample identifier for this no-nanotube comparison is reproduced here; cited Peng procedures are not treated as fully inspected recipes.',E(9,'Electronic spectrum discussion')+E(2,'References 36–37'))
r['quality']['conflicts']=['Earlier microscopy discussion calls free washings relatively monodisperse/quasi-spherical at 5 nm; later spectroscopy describes greater heterogeneity than a separate approximately 5 nm no-tube comparison. No quantitative distribution or physical-sample reconciliation is supplied.'];records.append(r)

r=base('mechanisms','Coordination, growth anisotropy and junction formation')
P(r,'study','Author interpretation of CdTe–MWNT growth',MECH)
T(r,'coordination','study','author_coordination_mechanism','Oxygenated MWNT groups coordinate Cd precursor and seed in situ CdTe growth after Te solution injection. Nanotubes function as sterically bulky π-conjugated ligands and growth terminators.',MECH,status='author_derived')
T(r,'ligand-competition','study','author_ligand_competition_rationale','Substoichiometric TDPA leaves some Cd available for surface coordination, especially through carboxylic acid/alcohol groups. No ligand-binding constant, available-site density or stoichiometric competition measurement is reported.',SYN,status='author_derived')
T(r,'diffusion','study','author_diffusion_limited_shape_mechanism','A nanotube limits access to one crystal face; incoming monomer preferentially reaches the free end, producing pseudo-one-dimensional or anisotropic growth. This is a steric/diffusion interpretation, not a measured monomer-flux map.',E(7,'Growth-shape discussion'),status='author_derived')
T(r,'site-geometry','study','author_shape_variation_factors','Local group density, site geometry and spatial separation of groups on one tube or adjacent tubes can alter growth and the broad crystal size/shape range.',E(8,'Morphology discussion'),status='author_derived')
T(r,'tip-preference','study','author_tip_growth_rationale','Greater tip coverage is linked to curvature-induced reactivity and abundant oxygenated groups after cap opening/outer-wall etching. Aggressive oxidation also creates active sidewall sites.',E(5,'Microscopy discussion')+E(6,'Continuation'),status='author_derived')
T(r,'junction','study','author_intertube_junction_rationale','Spacing between tubes can allow growing crystals to bridge them, creating fused nanocrystal-mediated networks. Exact atomistic bonding, electronic coupling and carrier transport are not established from the static microscopy alone.',MECH,status='author_derived')
T(r,'scheme','study','figure8_schematic_scope','Figure 8 schematically shows oxidation, Cd coordination/Te injection and in situ CdTe growth with probable multi-tube junction structures. TDPA ligands are omitted for clarity; the schematic is not measured atomic coordinates or a validated crystal model.',E(8,'Figure 8 caption'))
T(r,'passivation','study','author_passivation_tradeoff','Bulky nanotubes cap limited surface regions, leaving incomplete passivation and possible surface oxidation during prolonged air exposure. Source TeO3 wording is retained; exposure kinetics and oxide identity are not independently resolved.',E(8,'XPS interpretation'),status='author_derived')
T(r,'swnt-limit','study','author_swnt_extension_limit','Conventional oxidation of SWNTs has difficulty creating enough groups for dense QD growth without compromising tube structure/electronic integrity. This is qualitative extension context, not a fully specified current SWNT synthesis.',E(9,'Conclusion'))
T(r,'outlook','study','author_future_work','Future directions include charge transport through junctions, crystal growth across aligned nanotubes and thin composite films. Photovoltaic/electronic benefits remain proposed; no device efficiency, mobility or current–voltage measurement appears here.',E(2,'Application rationale')+E(9,'Conclusion'))
records.append(r)

r=base('source-context','Bibliographic scope, cited methods and evidence limits')
P(r,'context','Main article and supplied SI context',E(1,'Article opening')+E(9,'Supporting Information declaration'))
T(r,'documents','context','inspected_source_scope','Nine main pages, eight figures/captions and references 1–43 plus one matched SI page were fully read and visually inspected. No tables, numbered model equation, new reference-paper download, raw curve data or atomic coordinate file were supplied.',E(1,'Article opening')+E(9,'Article ending')+SI('Full page'))
T(r,'external-preparations','context','cited_preparation_access','Reference 35 (Hiura, Ebbesen and Tanigaki, Advanced Materials 1995, 7, 275) supplies prior oxidation context; references 36–37 (Peng and Peng, JACS 2001, 123, 183; 2002, 124, 3343) supply CdO-based CdTe precedent. The current paper modifies these methods but their external full texts are not part of this review.',E(2,'Experimental Section and references 35–37'))
T(r,'prior-attachment','context','prior_attachment_comparison','Earlier CdSe/TiO2 attachments and carbodiimide-mediated amidation yielded less organized isolated junctions. EDC, 11-aminoundecanoic acid and thiol-capped nanocrystals belong to cited prior work, not this paper’s current inventory.',E(2,'Introduction'))
T(r,'other-nanostructures','context','background_material_scope','BN coatings, carbide reactions, Si nanowires, ruthenium-functionalized MWNTs and other metal-complex SWNT systems are cited context. They do not create new synthesized-material entries for this source.',E(1,'Introduction')+E(2,'Introduction continuation'))
T(r,'measurement-limits','context','current_evidence_limits','No SAED pattern, measured CIF/VESTA atomic model, photoluminescence/quantum yield, quantitative electrical transport, photovoltaic device or current-paper bulk CdTe Raman experiment is supplied. Original microscopy and XRD support phase/morphology without exact junction coordinates.',EM+XRD+RAM+UV)
T(r,'matching','context','si_identity_scope','SI page lacks a standalone paper title and byline, but embedded DOI-related filename metadata, main declaration and identical oxidized-MWNT IR subject support the match. SI adds characterization only, not omitted reagent quantities.',E(9,'Supporting Information Available')+SI('Heading and metadata'))
records.append(r)

if __name__=='__main__':
 out=B/'canonical-drafts';out.mkdir(exist_ok=True);errors=[]
 for r in records:
  errors+=validate_record(r);(out/(r['record_id']+'.json')).write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 report={'status':'failed'if errors else'passed','record_count':len(records),'operation_count':sum(len(r['operations'])for r in records),'measurement_count':sum(len(r['measurements'])for r in records),'material_slots':sum(len(r['materials'])for r in records),'source_read_pages':10,'source_visual_pages':10,'main_pages':9,'si_pages':1,'errors':errors}
 (B/'records-validation.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 (B/'canonical-material-identities.json').write_text(json.dumps({'source_id':SID,'source_group':SID,'materials':[{'id':i,'name':n,'formula':f}for i,(n,f,e)in CHEM.items()],'record_material_ids':{r['record_id']:[m['id']for m in r['materials']]for r in records}},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 raw=json.loads((B/'source-manifest.json').read_text(encoding='utf-8-sig'))
 (B/'canonical-record-manifest.json').write_text(json.dumps({'source_id':SID,'source_group':SID,'source_fingerprint':raw.get('fingerprint'),'main_pages_read_and_visually_inspected':9,'si_pages_read_and_visually_inspected':1,'supporting_information':'Supplied one-page SI matched by embedded metadata and main declaration/content; fully inspected.','records':[{'id':r['record_id'],'record_type':r['record_type'],'sha256':hashlib.sha256((out/(r['record_id']+'.json')).read_bytes()).hexdigest(),'operation_ids':[o['id']for o in r['operations']],'sample_ids':[p['sample_id']for p in r['products']],'measurements':len(r['measurements'])}for r in records]},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
 print(json.dumps(report))
 if errors:raise SystemExit(1)
