from pathlib import Path
import json,hashlib,xml.etree.ElementTree as ET
B=Path(__file__).resolve().parent;V=B/'visuals';read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();C=[]
def ck(n,v):C.append({'check':n,'passed':bool(v)})
entries=read(V/'registry-additions.json')['entries'];D={e['id']:e for e in entries};texts={};assets={}
forms={'mwnt-pristine':'C','mwnt-oxidized':None,'mwnt-mild':None,'potassium-permanganate':'KMnO4','hydrofluoric-acid':'HF','tellurium-source':None,'te-top-stock':None,'ptfe-membrane':None,'composite-specimen':'CdTe/MWNT','washings-specimen':'CdTe','no-tube-specimen':'CdTe'}
ck('11 references',set(D)=={'identity-banerjee-'+k for k in forms}and len(D)==11)
for k,f in forms.items():
 e=D['identity-banerjee-'+k];p=V/e['svgPath'];assets[e['svgPath']]=sha(p);xml=ET.fromstring(p.read_text(encoding='utf8'));texts[k]=' '.join(xml.itertext())
 ck(k+'/literal or unknown formula',e['formula']==f);ck(k+'/source DOI',e['provenance']['sourceDoi']=='10.1021/ja035980c');ck(k+'/source hash',e['provenance']['sourceSha256']=='24faaec54cea1293bc7951b7d363587e2ec80edaa68d6e90049b5525bc312837');ck(k+'/no measured coordinates',e['provenance']['measuredCoordinates']is False);ck(k+'/no training geometry',e['provenance']['eligible_training']is False)
 ck(k+'/SVG bound',sha(p)==e['assetHashes']['svgPath']);ck(k+'/no atomic model',e['model2dPath']is None and e['model3dPath']is None);ck(k+'/no invented functional-group model',e['functionalGroups']==[]);ck(k+'/no inferred PubChem lookup',e['pubchemCid']is None)
 if k=='potassium-permanganate':
  ck('KMnO4 counts',e['provenance']['atomCountIllustration']=={'K':1,'Mn':1,'O':4});ck('KMnO4 actual Mn/O glyphs',sum(t.text=='Mn'for t in xml.iter()if t.tag.endswith('text'))==1 and sum(t.text=='O'for t in xml.iter()if t.tag.endswith('text'))==4);ck('K identity shown','K' in texts[k]and'MnO' in texts[k]);ck('No acid speciation inferred','imposed acid-phase speciation' in e['caption'])
 if k=='hydrofluoric-acid':
  ck('HF counts',e['provenance']['atomCountIllustration']=={'H':1,'F':1});ck('HF glyphs',sum(t.text=='H'for t in xml.iter()if t.tag.endswith('text'))==1 and sum(t.text=='F'for t in xml.iter()if t.tag.endswith('text'))==1);ck('HF percent basis unknown','without a percentage basis' in e['caption']);ck('HF not undissociated assumption','not a claim of undissociated HF' in e['caption'])
 for key in ['model2dPath','model3dPath']:ck(k+'/'+key+'/empty',e[key]is None)
for k in ['mwnt-pristine','mwnt-oxidized','mwnt-mild']:ck(k+'/no measured chirality or dimensions','not a measured chirality, wall count, diameter or atomic lattice' in D['identity-banerjee-'+k]['caption'])
for k in ['mwnt-oxidized','mwnt-mild']:ck(k+'/oxygen sites conceptual','not a measured site map' in D['identity-banerjee-'+k]['caption'])
ck('Mild recipe missing','Mild oxidation settings remain unreported' in D['identity-banerjee-mwnt-mild']['caption'])
ck('Tellurium not silently elemental','does not invent a bottle of elemental Te' in D['identity-banerjee-tellurium-source']['caption']);ck('Stock speciation unresolved','does not establish the dissolved tellurium species' in D['identity-banerjee-te-top-stock']['caption']);ck('TOP formula in actual stock drawing','C₂₄H₅₁P' in texts['te-top-stock'])
ck('PTFE equipment','not a measured pore map, polymer-chain model or reaction ingredient' in D['identity-banerjee-ptfe-membrane']['caption']);ck('PTFE actual pore size','0.2' in texts['ptfe-membrane']and'µm'in texts['ptfe-membrane'])
ck('Composite mixed-phase limit','possible zinc blende and stacking faults' in D['identity-banerjee-composite-specimen']['caption']);ck('Composite illustrative interface','not a measured interface or atomic model' in D['identity-banerjee-composite-specimen']['caption'])
for k in ['washings-specimen','no-tube-specimen']:ck(k+'/free populations distinct','does not establish that these are the same sample' in D['identity-banerjee-'+k]['caption'])
for f in read(V/'asset-manifest.json')['files']:ck('Manifest '+f['path'],sha(V/f['path'])==f['sha256'])
manual=['Independently inspected all eleven actual source-specific registry entries, captions, SVG contents and both full contact sheets. Formula/mixture/specimen identities match the source without new atomic models or database lookups.','KMnO4 contains one K, one Mn and four O formula-unit counts. The diagram distinguishes K and MnO4 composition, without claiming its strongly acidic solution speciation. HF has one H and one F as composition symbols; its source10% value has unknown percentage basis and does not specify dissociation or hydrate geometry.','Pristine C-based MWNT and two oxidation contexts remain separate. Red markers are explanatory oxygen sites, not measured density, exact surface formula, chirality or tube dimensions. Identical schematic site counts do not imply equal experimental oxidation; captions and source records state their scope.','Tellurium source and Te/TOP stock retain unresolved chemical identity and preparation; no bottle of elemental Te or specific TOPTe structure is inferred. Stock shows the correct TOP formula C24H51P, with its molecular reference separately audited when reused.','PTFE0.2µm membrane is separation equipment, not reaction precursor or measured pore geometry. The composite architecture visibly includes attached particles and a bridge meeting both tube ends, but supplies no atomic interface, phase fraction, lattice or measured particle number.','Washed-away CdTe and no-tube reference are distinct illustration cards. Source~5nm and monodispersity wording does not become a claimed exact common measured distribution. Wurtzite/zinc-blende limits remain confined to composite source evidence.','No Site mutation or browser validation performed. Existing twelve reference molecules/materials and final record bindings are audited separately.']
fail=[x for x in C if not x['passed']]
out={'status':'passed_source_and_asset_audit_bindings_separate'if not fail else'failed','source_id':'banerjee2003','source_sha256':'24faaec54cea1293bc7951b7d363587e2ec80edaa68d6e90049b5525bc312837','si_sha256':'0746611853616b5531750d1cd4c610d605c551eec0b3317805c0fcc98fce301e','source_audit_sha256':sha(B/'source-audit.json'),'registry_sha256':sha(V/'registry-additions.json'),'asset_manifest_sha256':sha(V/'asset-manifest.json'),'entry_count':11,'asset_hashes':assets,'visual_coverage':[{'path':str(V/'review'/f'molecular-contact-{i}.png'),'sha256':sha(V/'review'/f'molecular-contact-{i}.png'),'actually_viewed':True}for i in [1,2]],'check_count':len(C),'checks':C,'failures':fail,'manual_review':manual,'limits':['Source identity/illustration audit; reused references and bindings separate.','No measured source atomic coordinates or new external lookup.'],'site_mutated':False}
write=lambda n,x:(B/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8');write('molecular-source-audit.json',out)
(B/'molecular-source-audit.md').write_text('# Banerjee2003 molecular identity audit\n\n'+out['status']+f'; {len(C)} supporting checks, {len(fail)} failures.\n\n'+'\n\n'.join(manual)+'\n\nExact registry SHA256 `'+out['registry_sha256']+'`.\n',encoding='utf8');print(json.dumps({'status':out['status'],'registry_sha256':out['registry_sha256'],'checks':len(C),'failures':fail}))

