from pathlib import Path
from datetime import datetime,timezone
import json
B=Path(__file__).resolve().parent;MON=B.parent.parent
def read(p):return json.loads(p.read_text(encoding='utf8'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
fp=read(MON/'ledger.json')['groups']['10.1021_ja035980c']['fingerprint'];assert fp['generation']==2
m=read(B/'source-manifest.json');m['fingerprint']=fp;m['copies']=[{'filename':k,'sha256':h,'role':'si'if '_si_'in k else'main','page_count':1 if '_si_'in k else 9}for k,h in fp['files'].items()];m['si_identity']={'status':'matched','basis':['Main p9 explicitly declares infrared spectrum of oxidized multiwalled nanotubes.','SI heading and single graph match the declared technique and specimen.','SI PDF title metadata contains ja035980csi20030625_041651.doc.','Both local-folder copies match main and SI hashes exactly.'],'limit':'Supplement has no separate full article title or author list; match uses convergent DOI metadata and exact declared content.'};write(B/'source-manifest.json',m)
root={'status':'supplied_main_and_matched_si_read_text_and_visual','at':datetime.now(timezone.utc).isoformat(),'main_pages_text_read':list(range(1,10)),'main_pages_visually_inspected':list(range(1,10)),'si_pages_text_read':[1],'si_pages_visually_inspected':[1],'main_figures':8,'si_figures':1,'tables':0,'references':43,'critical_boundaries':['Aggressive oxidationKMnO4/H2SO4 then35%HCl and10%HF; source lacks doses/basis/time. Water wash and150°Coven dry are upstream only.','CdO+TDPA+oxidizedMWNT inTOPO320°CAr;Te/TOPinjection300°C;250°C20min growth. No source masses/stock concentration and no useofcitedPengpapersto fill gaps.','Cool50°C then5mLtoluene; methanol precipitation;0.2µmPTFEfilterretainscomposite;copioustolueneremovesfreeCdTe;finaldryconditionsunknown.','Pristine/raw/mildlyoxidizedcontrolsnotquantifiedalternatives. Oxygen~5–6versus~1–2at% contextsareXPSobservationsnotexactformulavalues.','Boundnanocrystalslongaxis1–9nm/aspect1–5;~5nmwashingsdiscussionandno-tubereferencecomparisonnotunambiguouslyequalmonodispersity.','Wurtzitepredominantwithpossiblezincblende/stackingfaults; noatomicrefinementorSAED.','Figure4EDScaptioneV versus0–10energyscaleretainedconflict;literalTeO3surfaceassignmentnotreplaced.','785nm10mWRaman166cm-1LOfeaturevs170cm-1bulk;G~1590,D1290–1320. SIIRbelongs tooxidizedMWNTprecursor;noexactpeakassignmentsinvented.','Figure8isauthorschematic;diffusion/surfacegrowthanddevicebenefitsremainhypotheses/outlook.']};write(B/'root-reading.json',root)
stages={'read':{'status':'complete','evidence':[str(B/'root-reading.json'),str(B/'source-manifest.json')],'note':'All nine supplied main pages and the matched one-page IR supplement text-read and visually inspected. Byte-identical incoming/legacy copies reconciled.'},'extract':{'status':'partial','evidence':[str(B/'root-reading.json')],'note':'Source inventory, canonical extraction, complete reader and source-specific assets in preparation.'},'audit':{'status':'pending','evidence':[],'note':'Independent source/canonical/reader/chemical/apparatus gates pending.'},'integrate':{'status':'pending','evidence':[],'note':'Private staging; existing Site unchanged for this paper.'},'publish':{'status':'pending','evidence':[],'note':'Existing MatterSyn version25 remains live.'}}
write(B/'milestones.json',stages);write(B/'checkpoint.json',{'paper':'10.1021/ja035980c','title':'In Situ Quantum Dot Growth on Multiwalled Carbon Nanotubes','source_id':'banerjee2003','source_generation':2,'review_scope':'supplied_main_and_matched_si','main_pages_text_reviewed':list(range(1,10)),'main_pages_visually_reviewed':list(range(1,10)),'si_pages_text_reviewed':[1],'si_pages_visually_reviewed':[1],'si_status':'Matched single-page IR supplement using main declaration, content and DOI-bearing PDF metadata.','website_published':False,'checkpoint_at':datetime.now(timezone.utc).isoformat(),'current_work_items':[{'label':k.capitalize(),'status':v['status'],'scope':v['note']}for k,v in stages.items()],'next_action':'Finish canonical/source inventory and reader; create meaningful chemical/apparatus assets; independently audit, integrate and publish on existing MatterSyn Site.'})
print('Saved full9main+1SI reading checkpoint.')
