"""Original PDFium source crops only; no redraw, digitization or Site edits."""
from pathlib import Path
import json,hashlib,math
import pypdfium2 as pdfium
from PIL import Image,ImageDraw,ImageFont
R=Path(__file__).resolve().parent;O=R/'crop-assets';O.mkdir(exist_ok=True);(O/'source-render').mkdir(exist_ok=True)
SOURCE=Path('[local path redacted]');SH='6a7fb66fb56f6daa4aa677c91ddf0d78aa733b165b7537bbac4c4e1327defb06'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
assert sha(SOURCE)==SH
A=[]
def add(id,p,b,title,caption,scope,kind='figure',evidence='experimental',notes=None,panels=None):
 A.append({'id':id,'pdf_page':p,'box':b,'title':title,'caption_paraphrase':caption,'sample_scope':scope,'type':kind,'evidence_type':evidence,'scope_caveats':notes or [],'panels':panels or []})
add('figure-01',2,[614,83,1090,921],'Single-particle CdS absorption with and without NaCl','Absorption spectra at 30 min and 48 h for CdS in chelate polymer particles of approximately 100 µm diameter.','Sample a: no added NaCl; sample b: nominal source label 0.5 M NaCl. Panels are different reaction-time specimens, not a single spectrum.',panels=['a: 30 min','b: 48 h'],notes=['The nominal 0.5 M label is preserved. The procedure states 10 mL of 0.5 M NaCl followed by 100 mL Na2S solution; postmix concentration basis is unresolved.','Approximately 100 µm is the swollen polymer-particle diameter, not the CdS nanocrystal diameter.','No digitized spectrum or inferred optical onset is created.'])
add('figure-02',3,[102,87,577,458],'Long-time absorbance evolution','Time dependence of CdS absorbance at 450 nm from preparation to approximately 48 h.','Sample a and sample b; aliquot series from source-defined conditions.',notes=['Filled symbols mark 0.5 M in this figure; open symbols mark 0 M. Figure 8 uses the opposite marker assignment. Preserve each original legend.','An absorbance trajectory is not one independent synthesis per plotted point.','Source prose: sample b formation finishes within 2 h, sample a continues gradually to 48 h. No raw coordinates are digitized.'])
add('figure-03',4,[102,83,1090,687],'Sample a radial cross sections at low TEM magnification','Three TEM regions progressing inward from the polymer surface to the edge of the CdS-containing layer.','Sample a, no added NaCl. Distinct radial locations within the polymer particle, not three independently synthesized materials.',evidence='experimental_tem',panels=['a: near surface','b: 4–5 µm inward','c: 8–9 µm inward; near CdS-layer edge'],notes=['The lower side corresponds to the polymer interior. Original 250 nm scale bars preserved.','The layer depth is micrometers; visible CdS objects and aggregates are nanometers. Do not exchange these scales.','Exact aliquot time and microtomy conditions are not in the caption.'])
add('figure-04',4,[102,694,1090,1227],'Sample a nanocrystals and flocculation at higher magnification','High-magnification TEM near the surface and approximately 4–5 µm inward.','Sample a; surface and inner-layer locations.',evidence='experimental_tem',panels=['a: surface region','b: approximately 4–5 µm inward'],notes=['Original 50 nm scale bars retained. This figure supplies TEM morphology, not an electron diffraction pattern.','Small crystallites in flocculated objects are distinct from the larger aggregate dimensions.','Related fitted distributions are in Figure 5; no atomistic coordinates are measured.'])
add('figure-05',5,[102,83,577,808],'Location-specific CdS size distributions for sample a','TEM histograms with log-normal fit near the surface and normal fit in the inner flocculation region.','Sample a: panel a near surface; panel b approximately 4 µm inward.',evidence='experimental_histogram_and_fit',panels=['a: log-normal distribution; mean 2.7 nm; printed standard deviation 0.4','b: normal distribution; mean 4.6 nm; standard deviation 1.8 nm'],notes=['The unit/parameter convention for the log-normal standard deviation 0.4 is not printed; do not automatically label it ±0.4 nm.','Both are regional distributions, not a whole-particle mean or the XRD crystallite diameters 3.8/3.1 nm.','Histogram counts and fit curves remain original; no redrawing or digitization.'])
add('figure-06',5,[614,84,1090,1072],'Optical CdS-layer boundary and source schematic','Original optical micrograph of a sample a hybrid bead and schematic defining the radial CdS layer width L.','Sample a. Panel a is an optical image; panel b is the authors’ interpretive diagram.',evidence='experimental_optical_image_and_source_schematic',panels=['a: optical micrograph with 25 µm bar','b: schematic polymer particle and layer-width L definition'],notes=['Panel b is not a measured concentration map, an atomic model or a crystalline polymer structure.','L measures from the outer polymer surface to the ring boundary; it is not the CdS crystallite diameter.','No nanocrystals were observed in the central region of sample a; exact coordinate map is not provided.'])
add('figure-07',6,[102,86,1090,659],'Sample b cross sections and deeper CdS penetration','Low-magnification TEM at three radial depths in nominal 0.5 M NaCl sample b.','Sample b; distinct radial locations.',evidence='experimental_tem',panels=['a: near polymer surface','b: 9–10 µm inward','c: 15–16 µm inward'],notes=['Original 250 nm scale bars retained.','At the inner region both small isolated nanocrystals and flocculated particles are discussed; no one-size assignment is made to every visible object.','Do not transfer sample a 4–5/8–9 µm location labels to this figure.'])
add('figure-08',6,[102,671,577,1058],'Early-time absorbance versus square root of reaction time','Absorbance at 450 nm plotted against square root of reaction time for the two source conditions.','Sample a: filled circles; sample b: open circles.',evidence='experimental_kinetic_plot_and_fit',notes=['The horizontal axis is square root of time, in seconds to the one-half power; it is not time in seconds.','Source slopes: 4.6×10−3 s−1/2 for a and 8.9×10−3 s−1/2 for b. These are absorbance-versus-root-time slopes, not particle growth rates in nm/s.','Figure 2 marker mapping differs. Early-time points are related aliquots, not independent synthesis recipes.'])
add('figure-09',6,[614,672,1090,1048],'Absorbance and observed CdS layer width','Absorbance at 450 nm versus optically determined layer width L; both NaCl groups fall near the same line.','Sample a filled circles; sample b open circles.',evidence='experimental_correlation_and_fit',notes=['L below approximately 4 µm was difficult to establish precisely from optical ring boundaries.','The line supports a source model to estimate L from absorbance; no digitized calibration function is supplied.','An inferred layer width or diffusion coefficient is not a measured nanocrystal diameter.'])
add('equation-01',7,[191,723,577,857],'Donnan potential from ion partitioning','Displayed equation 1 relates potential difference to counterion and co-ion concentration ratios.','Theoretical model of water and charged-polymer phases, not a measured recipe or atomic structure.',kind='equation',evidence='theoretical_model',notes=['Δφ=φi−φo=−RT/F ln(Bi/Bo)=−RT/F ln(Ao/Ai), preserved as printed.','B denotes cation concentration, A anion concentration; i polymer and o water; R gas constant, T temperature and F Faraday constant.','No experimental potential measurement is implied.'])
add('equation-02',7,[267,1023,577,1109],'Charge neutrality assumptions','Displayed equation 2 defines polymer charge neutrality and external 1:1 electrolyte concentrations.','Model assumptions, not independently measured chemical stoichiometry.',kind='equation',evidence='theoretical_model',notes=['Bi=Ai+X; Bo=Ao≡C. X is fixed charge concentration in the polymer.','The formula describes the model’s ion populations; it is not a complete Cd-chelate coordination formula.'])
add('equation-03',7,[182,1173,577,1243],'Donnan potential as a function of fixed charge and electrolyte','Displayed equation 3 combines concentration and neutrality assumptions.','Model calculation for the source polymer/electrolyte comparison.',kind='equation',evidence='theoretical_model',notes=['Δφ=−RT/F ln[X/(2C)+sqrt(1+(X/(2C))²)], preserved without numerical recomputation.','A literal C=0 is singular; the paper’s finite no-added-NaCl estimate requires a nonzero external ionic concentration not fully specified in that comparison.','Source quotes −390 and −10 mV, and prints −26 meV for a hypothetical reduced-swelling case. Preserve the unit inconsistency instead of silently treating meV as mV.'])
add('polymer-identity-excerpt',2,[102,197,577,332],'Text-established chelate-polymer identity','Original Materials text names Chelex 100, styrene-divinylbenzene copolymer and iminodiacetate side groups.','As-purchased polymer host; not a synthesized polymer in this paper.',kind='text_excerpt',evidence='reported_material_identity',notes=['The source has no drawn polymer structure figure. This is an original text excerpt.','−CH2N(CH2COO−)2 is a local functional motif. Copolymer ratio, crosslink locations, chain length, stereochemistry and Cd coordination geometry are unspecified.'])
add('diffusion-relation-excerpt',5,[614,1091,1090,1216],'Inline diffusion-length relation','Original discussion gives Δ=(2Dt)1/2 and defines diffusion length and diffusivity.','Model interpretation of early-time absorbance kinetics.',kind='equation_excerpt',evidence='theoretical_model_in_text',notes=['This relation is inline and unnumbered. It does not establish exact 3D ion trajectories or measured pore geometry.'])
add('diffusivity-excerpt',6,[102,1073,577,1310],'Source estimates of HS− diffusivity','Original discussion uses L=(2Dt)1/2 and reports effective diffusion coefficients for samples a and b.','Model-derived D: a 2.5×10−10 cm²/s; b 1.1×10−9 cm²/s.',kind='equation_excerpt',evidence='model_derived_quantity',notes=['Layer width is inferred from the absorbance calibration; coefficients are model estimates rather than direct single-ion tracking.','The quoted Chelex/Dowex Na+ diffusivity 1.2×10−7 cm²/s elsewhere is a different ion and cited comparison, not either measured HS− result.'])
add('xrd-assignment-excerpt',3,[102,928,577,1231],'Text-only XRD phase assignment and mean crystallite sizes','Original discussion identifies cubic zinc-blende reflections and Scherrer-based size estimates.','Both samples: broad 26.5° peak and weak approximately 44°/52° features; source mean diameters a 3.8 nm, b 3.1 nm.',kind='text_excerpt',evidence='reported_diffraction_interpretation',notes=['No XRD pattern is printed among the nine figures; this excerpt must not be represented as a pattern image.','Mean crystallite sizes inferred from Gaussian peak fitting and Debye-Scherrer analysis are distinct from regional TEM histograms.','No lattice parameter, refined coordinates or experimentally identified CIF is reported.'])
doc=pdfium.PdfDocument(SOURCE);assert len(doc)==7;renders={}
for p in range(1,8):
 im=doc[p-1].render(scale=300/72).to_pil().convert('RGB');im.save(O/'source-render'/f'pdfium-{p:02d}-300dpi.png');renders[p]=im
for a in A:
 norm=[a['box'][i]/(1190 if i%2==0 else 1540) for i in range(4)];im=renders[a['pdf_page']];px=[round(norm[i]*(im.width if i%2==0 else im.height)) for i in range(4)];crop=im.crop(px);p=O/(a['id']+'.png');crop.save(p);w,h=doc[a['pdf_page']-1].get_size()
 a.update(source_id='yao1998',source_doi='10.1021/la970480g',source_file=SOURCE.name,source_path=str(SOURCE),source_sha256=SH,printed_page=594+a['pdf_page'],relative_asset=p.name,sha256=sha(p),dpi=300,pixel_dimensions=list(crop.size),crop_normalized=norm,bbox_pixels_at_140dpi=a.pop('box'),bbox_pdf_points_top_left=[norm[i]*(w if i%2==0 else h) for i in range(4)],original_source_asset=True,synthetic=False,digitized=False,eligible_training=False,experimental_sample_cif=False,original_caption_preserved=a['type']=='figure',visually_reviewed=False,renderer='Original PDF rasterized by PDFium at 300 dpi; rectangular crop only')
M={'source_id':'yao1998','source_doi':'10.1021/la970480g','source_title':'Electrolyte Effects on CdS Nanocrystal Formation in Chelate Polymer Particles: Optical and Distribution Properties','source_sha256':SH,'source_file':SOURCE.name,'source_page_count':7,'coverage':{'all_source_pages_text_read':True,'all_source_pages_visually_reviewed':True,'numbered_figures':9,'numbered_tables':0,'numbered_equations':3,'unnumbered_equation_excerpts':2,'identity_or_characterization_text_excerpts':2,'crop_count':len(A),'individual_crops_visually_reviewed':False},'source_pages':[{'pdf_page':p,'text_read':True,'visual_review':True,'text_sha256':sha(R/f'page-{p}.txt'),'initial_render_sha256':sha(R/f'page-{p}.png')} for p in range(1,8)],'assets':A,'global_limits':['Figure 1 is absorption spectra, not a polymer structure. No separate polymer structure, table or scheme is printed.','No XRD pattern, SAED pattern, atomistic polymer network or sample CIF is provided.','Source sample labels a and b describe related formulation families; aliquot times and radial regions remain scoped.','NaCl 0.5 M is a source nominal label with unresolved postmix basis.','All original pixels, axes, labels and scale bars preserved; no synthetic microscopy or digitized plot values.']}
save(O/'manifest.json',M)
font=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',22)
for i in range(math.ceil(len(A)/4)):
 sheet=Image.new('RGB',(1800,1600),'#eeeeee');d=ImageDraw.Draw(sheet)
 for n,a in enumerate(A[i*4:i*4+4]):
  x=n%2*900;y=n//2*800;im=Image.open(O/a['relative_asset']).convert('RGB');im.thumbnail((878,752));d.text((x+12,y+8),a['id']+' / PDF p'+str(a['pdf_page']),font=font,fill='black');sheet.paste(im,(x+11,y+40))
 sheet.save(O/f'contact-{i+1:02d}.png')
print(json.dumps({'crops':len(A),'manifest_sha256':sha(O/'manifest.json')}))
