from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text(encoding='utf8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
paths=['crop-assets/manifest.json','crop-assets/validation.json','molecular-assets/registry-additions.json','molecular-assets/bindings-additions.json','molecular-assets/reused-references.json','molecular-assets/asset-manifest.json','molecular-assets/model-provenance.json','molecular-assets/validation.json','molecular-assets/serialized-validation.json','molecular-assets/product-reference-proposal.json','yao-protocol.mjs','apparatus-review/scene-manifest.json','apparatus-review/dispatch-validation.json','apparatus-review/render-validation.json','apparatus-review/correction-validation.json']
d={'source_id':'yao1998','doi':'10.1021/la970480g','source_sha256':'6a7fb66fb56f6daa4aa677c91ddf0d78aa733b165b7537bbac4c4e1327defb06','status':'creator_checked_ready_for_independent_audit','files':[{'path':p,'sha256':sha(R/p)} for p in paths],'original_assets':{'count':16,'figures':9,'numbered_equations':3,'supporting_text_excerpts':4,'resolution_dpi':300,'visual_review':'All seven full pages and all sixteen original crops inspected; panels, captions and scale bars preserved. No graph digitization.'},'chemistry':read(R/'molecular-assets/validation.json')['summary'],'apparatus':{'exports':['buildYaoScene','createYaoArt'],'operations':47,'actions':25,'viewBox':'0 0 600 408','visual_review':'All 47 frames on eight contact sheets inspected; changed wording and diffusion frames re-inspected. Zero out-of-bounds text. Static SVG checks only; root owns browser integration QA.'},'validation':{key:read(R/p) for key,p in [('chemical','molecular-assets/validation.json'),('serialized','molecular-assets/serialized-validation.json'),('dispatch','apparatus-review/dispatch-validation.json')]},'limits':['No verified local cubic CdS CIF exists among the inspected crystal-reference registry/assets; no substitute wurtzite CdSe or invented CdS coordinates are supplied.','Ionic salts use component connectivity and formal charges in 2D only. Polymer and diagnostic-species cards do not invent a complete molecular graph or 3D coordination geometry.','0.5 M NaCl is the pretreatment concentration and source nominal sample label; post-addition concentration is unresolved.','HS− test solution applies only to the separate supernatant aliquot; HS− diffusion in the host is the authors\' interpretation of the Na2S-fed reaction.','Source TEM wording is low/high magnification; high magnification is not evidence of atomic lattice resolution.','Source XRD result is text only; no original XRD trace or SAED image is available in the seven inspected pages.','All new assets are illustrative/reference-only, excluded from measured structure training.','Parent may update source-record hashes on canonical promotion; material-ID joins must remain exact.'],'integration_notes':['Merge entries with copied relative SVG/model assets; reuse existing four registry identities without copying earlier-paper conditions.','Bind all eleven current drafts through recordBindings; observation records may have zero operations.','Import yao-protocol.mjs behind the source-specific scene dispatcher; runtime itself checks both DOI and record prefix.','Use the original crop manifest for public source locators and specimen scopes; no table is printed in this source.','Parent retains exclusive Site writes, integration and publication.']}
write(R/'asset-handoff.json',d)
lines=['# Yao 1998 private asset handoff','','Ready for independent audit and root integration. No Site files were edited.','','- Original source: seven complete pages read and visually reviewed; 16 faithful 300 dpi crops (nine figures, three numbered equations, four supporting text excerpts).','- Chemical registry: 11 new identities (seven ionic 2D depictions and four polymer/speciation cards); four reused identities; 31 exact material bindings across eleven drafts. No new 3D ionic or polymer geometry.','- Apparatus: `yao-protocol.mjs` exports `buildYaoScene` and `createYaoArt`; all 47 operations / 25 actions have source-specific diagrams.','- Validation: '+str(d['validation']['chemical']['passed'])+' chemical checks, '+str(d['validation']['serialized']['passed'])+' serialized connectivity/provenance checks, '+str(d['validation']['dispatch']['passed'])+' dispatch/guard checks pass. All 47 apparatus frames and 11 chemical depictions inspected; zero text overflow. Browser QA remains with root.','','## Scientific boundaries','']+['- '+x for x in d['limits']]+['','## Stable asset hashes','']+['- `'+x['path']+'`: `'+x['sha256']+'`' for x in d['files']]
(R/'asset-handoff.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
print(json.dumps({'module_sha256':sha(R/'yao-protocol.mjs'),'registry_sha256':sha(R/'molecular-assets/registry-additions.json'),'bindings_sha256':sha(R/'molecular-assets/bindings-additions.json'),'chemical_checks':d['validation']['chemical']['passed'],'serialized_checks':d['validation']['serialized']['passed'],'handoff':str(R/'asset-handoff.json')}))
