from pathlib import Path
import json,hashlib,datetime
A=Path(__file__).resolve().parent;B=A.parent
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
package=B/'canonical-proposal/v1/package-manifest.json'
assert sha(package)=='11ff0d309d4b8b785b53a141d4694a6f5a139a81801e7b72f9f0550afbe82c61'
mechanical=load(A/'mechanical-checks-v1.json');schema=load(A/'schema-check-v1.json')
assert mechanical['status']==schema['status']=='passed'
finding={'id':'MCR1','severity':'bounded_semantic_correction','status':'open_pending_author_revision','record_id':'morrison-2017-single-crystal-acquisition','pointer':'/material_states/0/kind','actual':'mixture','required':'analysis_data','reason':'The output precursor-crystal-structure of crystal-mount-measure represents the diffraction/refinement result. It is not a newly prepared chemical mixture. No quantity, input/output ID, specimen, source cell or atomic structure is changed by the requested classification correction.'}
scopes=[
 'Read all 252 reader item prose texts, including 52 uninspected external-reference notices, and the ten conflict descriptions. They preserve the audited main/SI source distinctions.',
 'Read all 18 record inventories, 24 operation descriptions, phase-specific inputs/outputs/retained fractions, branch dependencies and 41 product contexts. The monolayer TEM branch consumes the shell-growth family rather than the final optical dispersion.',
 'Checked separate aqueous precursor preparation, THF vapor crystallization, DMSO-d6 NMR thermolysis, THF powder control, partially specified hot-DMSO control, room-temperature exposure, thick-shell growth and controlled monolayer family.',
 'Preserved 0.512 g as a dispersion aliquot, three initial washes, uncalibrated 2–3-drop aliquots, unknown later repeat counts, 1/2/3/4/16 h time-course points and a separately reported ideal 3 h; no five fabricated synthesis runs.',
 'Verified ambient is not a numerical room temperature or specified gas atmosphere; unknown charges, vessel details and upstream cited-only NH4PTC/CdSe preparations remain explicit.',
 'Verified the approximate mounting dimensions differ from precise Table 1 crystal dimensions and retained the source revision2 corrected approximation flags, within-15-min bound, separate at-least-60% narrative yield, and non-strict thiourea observation time.',
 'Verified the THF-solvated Cd(PTC)2 coordination-polymer tables and chemical formula stay in precursor crystal contexts. Product CdSe/CdS morphology/diffraction observations do not acquire precursor coordinates or a CIF.',
 'Verified all 471 source table cells preserve raw tokens, scaled values, uncertainties, bounds, nulls, column order, prime labels, atom labels and source locators. The raw curated sidecar is exact; published reader context values are scoped, not new training labels.',
 'Verified the 191.37 g CdSe calculation basis and hypothetical intact-ligand sulfur calculation remain model quantities, not synthesis charges. Table S5 analytical columns do not create independently prepared batches.',
 'Verified SI S7 EDS remains THF-scoped, with the conflicting main hot-DMSO prose retained separately; missing channels remain null and literal zero counts remain zero.',
 'Verified monolayer total shell thickness spans both broad faces; no particle diameter or independently measured per-face thickness is fabricated. Cited starting dimensions and quantum yield remain cited context.',
 'Verified Figure 7 explicitly links red absorption and blue PL only; other TEM, XRD, elemental and optical contexts retain unknown physical-batch joins. Figure 3 retains the room-temperature and hot branches.',
 'Verified NMR normalizations, p1/p2 comparison, proposed pathways, cited Raman, high-temperature SILAR failures and c-ALD failures remain qualitative/model/reference contexts without fabricated measured spectra or controlled recipes.',
 'Verified all 30 selected original asset hashes, document roles, page locators and reader mappings against the actual source assets individually viewed in the passed source audit. This pass reuses those unchanged pixel inspections rather than claiming a second full visual reread.',
 'Verified all public candidate asset paths are selected excerpts; no original PDF, full-page attachment, local filesystem path or complete text cache is exposed by the reader. Private full source payloads and author sidecars are not public allowlists.',
 'Verified empty requested_tasks, imported_unreviewed state, zero current eligibility and zero structure_assets on every record. This review does not qualify models, apparatus, a browser, publication or training.'
]
bound=dict(load(package)['bound_files'])
for p in [package,A/'check_v1.py',A/'mechanical-checks-v1.json',A/'schema-check-v1.json',A/'save_v1_audit.py']:bound[str(p)]=sha(p)
audit={'schema':'mattersyn.independent-canonical-reader-audit.v1','reviewer':'/root/peng1998_reader_assets','author':'/root/backlog_eta','status':'findings_pending_bounded_revision','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'package_sha256':sha(package),'source_revision':2,'source_audit_sha256':'5cabf080455991d4aeb36792f37b884afc29595895785b8c7d38e3d3ab00165d','actual_scope':'Independent canonical and reader audit against the already independently reviewed source revision2. Complete source reading and all30 crop visual inspections are inherited only by unchanged hashes from the separate source audit. No new browser, molecule/apparatus or product-model qualification.','counts':{'records':18,'operations':24,'source_facts':72,'source_units':176,'source_fact_quantities':185,'table_cells':471,'measurements':822,'reader_items':252,'reader_fields':1170,'selected_original_assets':30,'references':52},'mechanical_checks':mechanical['check_count'],'schema_records_passed':18,'manual_scopes':scopes,'findings':[finding],'bound_files':bound,'source_files_modified':False,'site_modified':False,'publication_approved':False,'training_approved':False}
(A/'independent-audit-v1.json').write_text(json.dumps(audit,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
(A/'independent-audit-v1.md').write_text('# Morrison canonical/reader v1 independent audit\n\nAll source transport and reader scopes passed, with one bounded semantic classification correction pending: `precursor-crystal-structure` must be analytical data rather than a chemical mixture.\n\nRead all 252 item texts and all 18 record inventories/24 operations. Independently checked 17,830 transport and mapping assertions plus current schema/eligibility for every record. All 471 table cells and 1,170 reader fields remain exact; no scientific numerical correction is requested.\n\nThe supplied main/SI and 30 selected crops were fully read/viewed in the separate source audit; unchanged hashes bind those inspections here. Models, apparatus, integrated browser behavior, publication and training remain separate gates.\n',encoding='utf-8')
print(sha(A/'independent-audit-v1.json'))
