"""Private Friedfeld apparatus authoring; does not write Site or canonical files."""
from pathlib import Path
from copy import deepcopy
import json,hashlib,shutil
A=Path(__file__).resolve().parent; F=A.parents[1]; C=F/'canonical-proposal/draft-v2'; T=F.parent/'la8031286/visuals/apparatus'
def read(p):return json.loads(p.read_bytes())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,v):(A/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert not (A/'package-freeze.json').exists()
assert sha(C/'package-freeze.json')=='ff8767ef6a51f4184825de335dfe9906fab80e53b97e641fa534f6344f25a112'
facts={f['id']:f for f in read(F/'source-extraction-revision-2/source-facts.json')['facts']}
records=[]; paths={}
for row in read(C/'record-manifest.json')['records']:
 p=Path(row['path']); assert sha(p)==row['sha256']; r=read(p)
 if r['operations']: records.append(r); paths[r['record_id']]=p
base={}
def scene(id,title,art,prose,notes,fs):
 base[id]=dict(title=title,art=art,prose=prose,notes=[dict(label=k,value=v)for k,v in notes],source_context_fact_ids=['friedfeld2019-'+f for f in fs])
scene('dry-flask','Dry the four-neck monitoring apparatus','oven','Oven-dry the apparatus overnight at 160 °C and Schlenk-dry before charging chemicals.', [('Apparatus','Four-neck flask with stir bar, Schlenk adapter, thermowell, septum and dip-probe adapter.'),('Unreported','Flask capacity, Schlenk drying time and vacuum pressure. There is no chemical output from this operation.')],['glassware','conversion-charge'])
scene('charge-ode','Charge the pre-injection ODE solution','charge','Charge the dried four-neck flask with the reported 19 mL pre-injection solution, including only the selected additive when applicable.', [('Volume basis','19 mL is the pre-injection solution volume. A stock concentration or a complete stock preparation volume is not inferred.'),('Unreported','Stirring speed and additive-stock concentration. The zero-equivalent comparison uses no additive.')],['conversion-charge','additive-series'])
scene('heat-baseline','Heat under nitrogen and acquire a baseline','baseline','Heat the pre-injection solution under nitrogen to the selected temperature. Calibrate the dip probe in OceanView and collect the background before cluster injection.', [('Reported apparatus','Four-neck flask, thermowell and Ocean Optics TI300 dip probe.'),('Unreported','Heating device, ramp, nitrogen pressure/flow and calibration standard. The heat-wave icon does not assert a bath.')],['conversion-heat','uv-acquisition'])
scene('sonicate-msc','Prepare the cluster injection in ODE','sonicate','Sonicate the cluster precursor in ODE before injection. The representative charge and the varied-concentration branch are distinguished in the adjacent fields.', [('Precursor scope','MSC symbols denote precursor clusters; no quantum-dot particles or measured atomic geometry are asserted at this step.'),('Unreported','Sonicator type, power and duration; the illustrated vial and wave field are generic.')],['conversion-inject','concentration-series'])
scene('inject-msc','Rapidly inject the cluster solution','inject','Rapidly inject the prepared MSC-in-ODE solution into the heated pre-injection solution and homogenize.', [('Time origin','Begin the growth acquisition after homogenization, as reported.'),('Unreported','Injection implement, numerical injection rate and homogenization time. The transfer graphic is explanatory.')],['conversion-inject','conversion-monitor'])
scene('monitor-growth','Monitor absorption during conversion','monitor','Acquire an absorption spectrum every 30 s after homogenization. Keep the acquired data and the physical reaction mixture as separate outputs.', [('Observed formation','Particle symbols denote possible formed material during conversion; they do not assert a pure InP product or a measured size.'),('Unreported','Condition-specific reaction endpoint. The 30 s value is a sampling interval, not a reaction duration.')],['conversion-monitor','phase-result'])
scene('distill-solvent','Distill solvent and retain reaction residue','distill','After the reaction, distill the solvent. Retain the reaction residue for the subsequent glovebox purification and keep the solvent distillate separate.', [('Retained fraction','Distilled reaction residue; the distillate is not the input to purification.'),('Unreported','Distillation temperature, pressure and detailed apparatus. Condenser and receiver geometry are generic.')],['conversion-workup'])
scene('transfer-purify','Transfer to the glovebox and separate products','gpc','Transfer the residue into the glovebox for purification. Preserve the reported GPC-separated InP and In2O3 fractions as distinct product contexts.', [('Fraction boundary','The output is a set of separately reported fractions, not a pooled pure product or a verified batch for every condition.'),('Unreported','GPC packing actually used, eluent, fraction windows, isolated yields and recoveries. The generic column does not assign the purchased medium to this procedure.')],['conversion-workup','phase-result'])
scene('acid-charge','Charge the isotope-labeling reaction','acid-charge','Charge 50 mL of 1.0 M benzylmagnesium chloride in 2-methyltetrahydrofuran and 50 mL THF into a 250 mL three-neck round-bottom flask. Attach the labeled CO2 bulb; its contents enter in the next operation.', [('Reported apparatus','Stir bar, Schlenk adapter, hose adapter and septum; 1.90 L bulb containing 40.9 mmol 13CO2.'),('Source discrepancy','The purchased break-seal vessel is described as 1 L elsewhere; the preparative bulb is printed as 1.90 L. Both descriptions remain scoped.'),('Unreported','Stirring speed; no CO2 delivery is depicted before the following condensation.')],['acid-charge','co2-supply'])
scene('acid-condense','Condense labeled carbon dioxide','condense','Cool the charged three-neck flask in liquid nitrogen, evacuate, place it under static vacuum, and break the attached bulb seal to condense 13CO2.', [('Material boundary','Liquid nitrogen is an external cooling bath. Labeled CO2 enters the reaction; nitrogen coolant does not.'),('Unreported','Numerical liquid-nitrogen temperature, vacuum pressure and condensation duration.')],['acid-condense'])
scene('acid-cold-hold','Hold in the dry-ice/acetone bath','cold','Warm the condensed reaction mixture in a dry-ice/acetone bath at −76 °C and hold for 1 h.', [('Material boundary','Dry ice and acetone belong to the external cooling bath, not the reaction charge.'),('Sequence','This hold follows liquid-nitrogen condensation and precedes the separate room-temperature hold.')],['acid-react'])
scene('acid-ambient-hold','Warm to room temperature','ambient','Warm the mixture to room temperature and hold for 8 h after the cold-bath stage.', [('Unreported','Numerical room temperature and the warming rate.'),('Sequence','The 8 h interval is distinct from the preceding 1 h at −76 °C.')],['acid-react'])
scene('acid-quench','Quench with methanol under ice-water cooling','quench','Cool the reaction mixture in an ice-water bath and add methanol dropwise.', [('Material boundary','Methanol is a reaction input; ice-water is an external cooling bath.'),('Unreported','Methanol volume, numerical addition rate, bath temperature and quench duration.')],['acid-quench'])
scene('acid-acidify','Acidify with aqueous hydrochloric acid','acidify','Add 1 M aqueous HCl to reach pH 2 after methanol quenching.', [('Endpoint','pH 2 is the acidification endpoint; the graphic does not assert an unreported meter or indicator.'),('Unreported','HCl volume, delivery rate and endpoint measurement method.')],['acid-quench'])
scene('acid-extract','Extract and retain the ether fractions','extract','Extract the acidified mixture three times with 20 mL diethyl ether each time. Retain the organic extracts and separate the aqueous raffinate.', [('Retained fraction','Ether extracts, subsequently combined; the aqueous raffinate is not returned to the product workup.'),('Illustration scope','Two fraction containers denote the split without assigning an unreported layer orientation or separatory vessel.')],['acid-extract'])
scene('acid-wash-dry','Wash and dry the combined organic solution','wash-dry','Combine the ether extracts, wash with brine and dry with sodium sulfate.', [('Retained fraction','Dried organic solution; brine and spent drying agent are removed in the workup.'),('Unreported','Brine volume, sodium sulfate amount and drying time.')],['acid-extract'])
scene('acid-filter-evaporate','Filter and remove solvent by rotary evaporation','filter-evaporate','Filter off the drying agent, retain the organic filtrate, then rotary-evaporate the solvent to obtain crude labeled acid.', [('Fraction sequence','Organic filtrate → crude nonvolatile acid. The drying-agent solids and evaporated solvent are separate discarded fractions.'),('Unreported','Filter specification, evaporation pressure, temperature and duration.')],['acid-extract'])
scene('acid-layer','Prepare the layered crystallization solution','layer','Dissolve the crude acid in minimal dichloromethane and layer with pentane.', [('Solvent scope','The solvent layers illustrate the reported layering operation; no exact interface shape or solvent ratio is supplied.'),('Unreported','Numerical solvent volumes and addition rate.')],['acid-crystallize'])
scene('acid-crystallize','Crystallize the labeled acid','crystallize','Allow the layered dichloromethane/pentane solution to stand at 0 °C for 12 h.', [('Product scope','Crystal symbols represent the labeled molecular acid, not InP quantum dots or an atom-resolved crystal model.'),('Unreported','Cooling equipment and the crystallization vessel.')],['acid-crystallize'])
scene('acid-isolate','Collect and dry the acid crystals','isolate','Collect and dry the white labeled-acid crystals, keeping the mother liquor separate.', [('Reported isolated outcome','5.15 g; 92% reported yield. These are outcome measurements, not a feed charge.'),('Unreported','Collection method and drying pressure, temperature and duration.')],['acid-crystallize'])
scene('substitute-labeled-acid','Substitute labeled acid in the cited cluster preparation','cited','Use the synthesized 13C-labeled phenylacetic acid in place of natural-abundance phenylacetic acid in the cited InP cluster preparation.', [('Cited preparation','References 43 and 45 supply the upstream procedure; its complete recipe is not reproduced in the supplied paper and SI.'),('Known inputs versus missing procedure','Labeled acid, indium acetate and P(SiMe3)3 are identified, but complete charges and reaction/workup conditions remain unreported here.'),('Scope','No new executable synthesis or cluster atomic model is inferred from the substitution statement.')],['labeled-msc','prior-cluster','phosphine-gap'])
scene('add-labeled-acid','Prepare separate labeled-acid exchange comparisons','exchange-acid','Add the selected level of labeled phenylacetic acid to natural-abundance phenylacetate-capped MSCs for the separate NMR exchange comparisons.', [('Separate alternatives','1, 10 and 30 equivalents are alternative comparison levels, not cumulative additions in a single recorded batch.'),('Solvent and missingness','Toluene-d8 context; aliquot volumes, exact mixing/holding times and a numerical room temperature are not supplied.')],['acid-exchange','si-exchange'])
scene('add-labeled-indium','Prepare separate labeled-indium exchange comparisons','exchange-indium','Add the selected level of isotopically labeled indium phenylacetate to natural-abundance phenylacetate-capped MSCs.', [('Separate alternatives','1, 5, 10 and 20 equivalents are distinct comparison levels; no cumulative dose is implied.'),('Solvent scope','The SI includes a 20-equivalent CDCl3 comparison. That solvent is not assigned to every other comparison.'),('Unreported','Aliquot volumes, equilibration time and complete preparation of the labeled indium salt.')],['indium-exchange','si-exchange'])
scene('pretreat-msc','Hold the cluster precursor at low temperature','pretreat','Heat the MSC precursor at 130 °C. Retain the separately reported 30 h and 72 h contexts without asserting they identify the same sample.', [('Source conflict','Figure 4A/S13 report 30 h; the main discussion and S14–S16 report 72 h. The cross-panel specimen join remains unresolved.'),('Later conversion','Subsequent 250 °C conversion is linked observation context; it is not silently appended as a fully specified second operation.'),('Unreported','Pretreatment vessel, heating apparatus and condition-specific charge.')],['pretreat','pretreat72','si-pretreat'])
scene('nmr-analyze','Acquire NMR spectra of separate specimens','nmr','Acquire NMR data with the source Bruker Avance instrument, retaining the isotope, exchange and pretreatment specimens separately.', [('Frequency distinction','700 MHz is the general instrument label. The literal Figure 4 caption value of 202 Hz is retained elsewhere as a source inconsistency, not a universal setting.'),('Unreported','Pulse program, delay, scan count and exact cross-technique physical-batch joins.')],['nmr-acquisition','nmr-vt','si-nmr'])
scene('acid-nmr-analyze','Characterize the isolated labeled acid by NMR','acid-nmr','Record the isolated labeled-acid identity data at 23 °C: 1H at 700 MHz and 13C{1H} at 176 MHz in CDCl3.', [('Specimen boundary','The molecular labeled acid is separate from labeled MSCs and their exchange specimens.'),('Source data','The reported shifts, couplings and assignments remain in the source reader; no spectrum is generated here.')],['acid-nmr'])
scene('uvvis-analyze','Measure optical absorption','uvvis','Use the source Cary 5000 UV–vis–NIR instrument or the Ocean Optics TI300 dip probe as specified by the acquisition context.', [('Instrument alternatives','The conventional spectrometer and in situ probe are alternatives; the drawing does not assert they operate in series.'),('Unreported','Cell geometry, optical path length, slit widths and context-specific acquisition details.')],['uv-acquisition','abs-vt'])
scene('tem-analyze','Acquire TEM and local lattice-image evidence','tem','Use the FEI Tecnai G2 F20 with ultrathin carbon on holey carbon grids for the separately assigned microscopy specimens.', [('Evidence scope','Original TEM images and local FFT analyses remain source assets. The local FFT is not relabeled as an SAED acquisition.'),('Unreported','Accelerating voltage, dose and detailed grid preparation; no measured particle size is encoded in the schematic.')],['tem-acquisition','tem-result','si-fft'])
scene('xrd-analyze','Acquire powder X-ray diffraction','xrd','Measure source specimens using the Bruker D8 Discover IμS with a two-dimensional detector.', [('Acquisition gap','Wavelength, radiation-target identity and full scan settings are unreported; no Cu Kα assignment is inserted.'),('Specimen boundary','Separate conversion and pretreatment samples; phase assignments and calculated domain sizes remain source evidence.')],['xrd-acquisition','si-xrd','si-scherrer'])
scene('tga-analyze','Measure thermogravimetric response','tga','Use the TA Instruments Q50 with the reported 10 °C/min ramp for the thermal specimen.', [('Atmosphere','Not reported for this thermal analysis. The nitrogen used during synthesis is not transferred to TGA.'),('Unreported','Sample mass, pan details, gas flow and complete temperature program. Source mass-loss curves remain separate.')],['thermal-acquisition','thermal-result','si-thermal'])
scene('dsc-analyze','Measure calorimetric response','dsc','Use the TA Instruments Q20 with the reported general 10 °C/min ramp; preserve the separate thermal-cycle context.', [('Atmosphere','Unreported; no reaction-nitrogen assignment.'),('Printed program ambiguity','The SI cycle typography includes an ambiguous 1800 °C token; it is not converted into an operational heating rate here.'),('Unreported','Pan specification, sample mass and a resolved full cycle program.')],['thermal-acquisition','si-dsc-cycle'])
scene('optical-analysis-analyze','Process the measured absorption series','optical-processing','Use Igor Pro 6.02A to apply binomial smoothing with factor 1000, subtract the background, and prepare time-dependent absorption plots.', [('Analysis boundary','The factor 1000 is a data-processing parameter, not a physical synthesis condition.'),('Source evidence','No new optical spectrum or re-fit is generated; original source curves and processing assumptions remain traceable.')],['optical-processing'])
scene('kinetic-analysis-analyze','Analyze the source kinetic models','kinetic-analysis','Retain the source kinetic transformations and fits as analysis of the reported measurement series.', [('Model scope','Different orders, regimes and fit coefficients are source models. A fit does not establish a unique growth mechanism or a synthesis success label.'),('Missingness','Raw datasets and complete uncertainty treatment are absent; no new fit is performed.')],['si-logfit','si-orders','si-growth-fits','scheme2-model'])
scene('scherrer-analysis-analyze','Retain the reported Gaussian and Scherrer analyses','scherrer','Keep the printed Gaussian fit boxes and Scherrer domain-size calculations, including the documented fit-box/prose disagreements.', [('Metric distinction','Calculated coherent domain size is not automatically a TEM particle diameter or a source coordinate structure.'),('Source discrepancy','Printed fit values and prose values remain separate; no repaired width, broadening correction or new diffraction trace is created.')],['scherrer-summary','si-scherrer'])
cfg={};bindings=[];labels={};typed=[]
for r in records:
 for j,o in enumerate(r['operations']):
  c=deepcopy(base[o['id']]);c.update(record_id=r['record_id'],operation_id=o['id'],operation_pointer=f'/operations/{j}',option_selections=[])
  for oi,opt in enumerate(r.get('condition_options',[])):
   keys=[]
   for k,q in opt['parameters'].items():
    stage=('heat-baseline' if 'temperature' in k else 'charge-ode' if 'equiv' in k or 'additive' in k else 'sonicate-msc') if r['record_id'].startswith('friedfeld-2019-conversion-') else o['id']
    if stage==o['id']:keys.append(k)
   if keys:c['option_selections'].append(dict(pointer=f'/condition_options/{oi}',keys=keys))
  branch=r['record_id'].replace('friedfeld-2019-','')
  c['branch']=branch
  if branch.startswith('conversion-'):
   c['title']={'conversion-representative':'Representative conversion','conversion-acid-additive':'Acid-additive series','conversion-indium-additive':'Indium-additive series','conversion-concentration':'Concentration series'}[branch]+' · '+c['title']
   c['additive']={'conversion-representative':'No additive assigned','conversion-acid-additive':'Myristic acid option','conversion-indium-additive':'Indium myristate option','conversion-concentration':'No additive assigned'}[branch]
   c['notes'].insert(0,dict(label='Procedure inheritance',value='Representative preparation is the shared procedure; it does not certify that every plotted condition used an identical physical batch or every unreported setting.'))
   if branch=='conversion-concentration' and o['id']=='sonicate-msc':c['notes'].insert(0,dict(label='Varied-concentration branch',value='Condition-specific cluster mass is unreported. The representative 20 mg / 0.00121 mmol charge is not copied into this branch. The 1 mL ODE solvent step is inherited common-procedure context.'))
  ev=list({json.dumps(e,sort_keys=True):e for fid in c['source_context_fact_ids']for e in facts[fid]['evidence']}.values())
  for n in c['notes']:n.update(source_fact_ids=c['source_context_fact_ids'],evidence=ev)
  k=r['record_id']+'--'+o['id'];cfg[k]=c
  b=dict(scene_id=k,record_id=r['record_id'],record_path=str(paths[r['record_id']]),record_sha256=sha(paths[r['record_id']]),operation_id=o['id'],operation_pointer=c['operation_pointer'],inputs=o['inputs'],optional_inputs=o.get('optional_inputs',[]),outputs=o['outputs'],retained_fraction=o['retained_fraction'],source_evidence=o['evidence'],supplemental_source_fact_ids=c['source_context_fact_ids'],supplemental_source_evidence=ev,canonical_description=o['description'],human_prose=c['prose'],art=c['art'],option_selections=c['option_selections'])
  bindings.append(b)
  for pk,q in o['parameters'].items(): labels[pk]=pk.replace('_',' ').capitalize();typed.append(dict(scene_id=k,pointer=c['operation_pointer']+'/parameters/'+pk,quantity=q))
  for sel in c['option_selections']:
   opt=r['condition_options'][int(sel['pointer'].split('/')[-1])]
   for pk in sel['keys']:labels[pk]=pk.replace('_',' ').capitalize();typed.append(dict(scene_id=k,pointer=sel['pointer']+'/parameters/'+pk,quantity=opt['parameters'][pk]))
labels.update({'msc_mass':'MSC precursor mass','msc_amount':'MSC precursor amount','msc_injection_solvent':'ODE in the MSC injection','oven_temperature':'Apparatus oven temperature','drying_duration':'Qualitative oven-drying duration','pre_injection_solution_volume':'Pre-injection solution volume','general_instrument_label':'General NMR instrument label','1h_frequency':'1H frequency','13c_frequency':'13C{1H} frequency','bnmgcl_solution_volume':'BnMgCl stock aliquot in 2-MeTHF','thf_volume':'Additional THF','reaction_co2_bulb_volume':'Attached preparative 13CO2 bulb volume','co2_amount':'Attached 13CO2 amount (condensed next)','flask_volume':'Reported three-neck flask capacity','ether_extraction_repetitions':'Ether extraction repetitions','ether_volume_per_extraction':'Ether volume per extraction'})
assert len(cfg)==58 and len(base)==34
assert len({(b['record_id'],b['operation_id'])for b in bindings})==58
data=dict(source_group='friedfeld2019',configs=cfg,parameter_labels=labels)
save('scene-config.json',data);save('records.json',records);save('typed-field-map.json',typed)
save('canonical-bindings.json',dict(author='/root/norberg2004_extract',status='private_author_proposal_pending_independent_audit',canonical_freeze_sha256=sha(C/'package-freeze.json'),record_manifest_sha256=sha(C/'record-manifest.json'),source_freeze_sha256=sha(F/'source-extraction-revision-2/package-freeze.json'),source_audit_sha256=sha(F/'source-independent-audit/independent-audit-v2.json'),bindings=bindings))
template=(T/'protocol-template.mjs').read_text(encoding='utf-8');template=template[:template.index('function draw(c)')]+(A/'draw-scenes.mjs').read_text(encoding='utf-8')+'\n'+template[template.index('function quantity(q)'):]
template=template.replace('Pati2009','Friedfeld2019').replace('pati2009','friedfeld2019').replace('Pati et al. 2009','Friedfeld et al. 2019').replace('pati-','friedfeld-')
template=template.replace("for(const p of c.option_pointers){const option=r.condition_options?.[Number(p.split('/')[2])];", "for(const selection of c.option_selections){const p=selection.pointer;const option=r.condition_options?.[Number(p.split('/')[2])];")
template=template.replace('Object.entries(option.parameters).map','Object.entries(option.parameters).filter(([k])=>selection.keys.includes(k)).map')
template=template.replace("unit=({degC", "unit=({time_text:'',dimensionless:'',degC")
template=template.replace("rows.push({label:option.label,", "rows.push({label:option.label.replace(/(\\d)C\\b/g,'$1 °C').replace(/(\\d)equiv/g,'$1 equiv').replace('initialMSC','initial MSC = ').replace(/(\\d)mM/g,'$1 mM'),")
template=template.replace("return v===null?(q.raw_text||'Not reported'):", "return v===null?(q.raw_text||'Not reported'):q.unit==='pH'?('pH '+v):")
(A/'protocol-template.mjs').write_text(template,encoding='utf-8');(A/'friedfeld2019-protocol.mjs').write_text(template.replace('__CONFIG__',json.dumps(data,ensure_ascii=False,separators=(',',':'))),encoding='utf-8')
shutil.copyfile(T/'quantity-value.mjs',A/'quantity-value.mjs')
save('helper-provenance.json',dict(templates=[dict(path=str(T/'protocol-template.mjs'),sha256=sha(T/'protocol-template.mjs'),reuse='Source-neutral drawing primitives and condition-grid API only; all source-specific draw cases replaced.'),dict(path=str(T/'quantity-value.mjs'),sha256=sha(T/'quantity-value.mjs'),reuse='Unmodified source-neutral quantity formatter.')],canonical_changes=False))
print(json.dumps(dict(records=len(records),scenes=len(cfg),source_operations=len(base),typed_fields=len(typed),condition_options=sum(len(r.get('condition_options',[]))for r in records))))
