from pathlib import Path
import json,hashlib
V=Path(__file__).resolve().parent;B=V.parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=json.loads((V/'scene-manifest.json').read_text(encoding='utf8'))
for scene in m['scenes']:assert sha(V/scene['file'])==scene['svg_sha256']
contacts=[{'file':str(p.relative_to(V)),'sha256':sha(p),'visually_inspected':True} for p in sorted((V/'review').glob('scenes-*.png'))]
report={'status':'passed_with_illustration_limits','scope':'Review of the root-authored private Gerion module, followed by creator verification of the source-semantic and layout corrections made here. This is not an independent audit of our own final edits; a separate source auditor is reviewing the frozen module.',
'source_id':'gerion2001','module':'gerion2001-protocol.mjs','module_sha256':sha(V/'gerion2001-protocol.mjs'),'operation_count':82,'automated_checks':len(m['checks']),'all_checks_passed':all(c['passed'] for c in m['checks']),'contact_sheets':contacts,'record_hashes':{p.name:sha(p) for p in sorted((B/'canonical-drafts').glob('*.json'))},
'source_semantics_checked':['All82 canonical operations resolve by record and operation IDs; no canonical mutation.','Precipitation starts with a dispersion and ends with wet precipitate; the initial separation hardware is not invented.','MPA collection retains pellet; MPA and silica final clearing retain supernatant.','Membrane concentration retains upper concentrate; dialysis retains internal sample; filtration retains filtrate.','Preparative silica size exclusion retains only fluorescent fraction; analytical HPLC separately collects and inspects the three original peak fractions.','DMAP stock and quench preparations are separate reagent mixtures, not pre-existing nanoparticle dispersions.','TEM/EELS deposition, drying and electron-optical acquisition are distinct; no optical cuvette in electron-microscopy acquisition.','DTNB-treated aliquot and matched blank are separate; salt challenges occur before gel loading.','MWCO, filter pore size and centrifuge force are not conflated; optional0.22mm printing discrepancy remains explicit.','No pressure, bath device, cooling rate, concentration, phase, unit cell, microscopy data or spectra were invented.','4h CW acquisition and0–4000s plotted window remain distinct; canonical approximate>=4h stability claim is preserved.','All source quantities/statuses/ranges/bounds remain in canonical records for the shared adjacent condition panel; SVG apparatus does not duplicate them.'],
'corrections':['Electron microscopy/EELS replaced generic optical instrument artwork.','Correct initial precipitation and MPA redispersion states.','Separate reagent stock preparation from nanocrystal mixture.','Distinct analytical HPLC loading/elution/fraction inspection.','Distinct mica incubation, grid drying, Ellman preparation/incubation and salt incubation.','Moved column/filter collector labels away from notes and moved shell inset away from feed box.','Post-quench shell inset labeled siloxane-coated particle, not continuing growth.','Vacufuge labelled centrifugal evaporation.','Nitrogen inlet now derives from each selected operation environment; unreported atmospheres remain unillustrated, confirmed by 30 additional tests.'],
'limitations':['Apparatus geometry, fluid colors, shell inset and gel extraction marker are explanatory, not measured structures or signals.','No source figure, spectrum or gel pattern is regenerated.','Main article supplied and inspected; declared HRTEM/AFM SI remains unlocated/unverified.','Private module review does not substitute for final integrated desktop/mobile browser verification.']}
(V/'creator-scene-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8')
handoff={'status':'ready_for_root_integration_after_independent_source_audit','module':str(V/'gerion2001-protocol.mjs'),'module_sha256':report['module_sha256'],'exports':['buildGerion2001Scene','createGerion2001Art'],'record_count':28,'operation_count':82,'measurement_count':186,'files':{'canonical_drafts':str(B/'canonical-drafts'),'canonical_manifest':str(B/'canonical-record-manifest.json'),'canonical_validation':str(B/'records-validation.json'),'prose_delta_validation':str(B/'prose-delta-validation.json'),'scene_manifest':str(V/'scene-manifest.json'),'scene_review':str(V/'creator-scene-review.json')},'copy_instructions':'Root copies only the frozen module into the established protocol module location and inserts the Gerion dispatch ahead of generic fallback. Preserve canonical condition rendering beside the SVG. No contacts/render scripts/private audits need to be public assets. Root alone integrates, builds, reviews and publishes.'}
(V/'apparatus-handoff.json').write_text(json.dumps(handoff,ensure_ascii=False,indent=2),encoding='utf8')
(V/'apparatus-handoff.md').write_text(f"# Gerion 2001 apparatus handoff\n\nFrozen module: `gerion2001-protocol.mjs`\n\nSHA-256: `{report['module_sha256']}`\n\nAll 82 operations have source-specific scenes; 380 automated checks passed. All 14 contact sheets were visually inspected; corrected scenes were rerendered and inspected. The private module edits were creator-verified and are awaiting the separate source auditor's final hash-bound check.\n\nCanonical data remain 28 records, 82 operations and 186 measurements. Prose-only spacing cleanup passed exact delta validation; numeric values, units, statuses, IDs, formulas, links and graph structure are unchanged. The final record hashes are in `creator-scene-review.json` and `../canonical-record-manifest.json`.\n\nThe shared runtime must display selected canonical conditions beside each SVG, including approximations, exclusive bounds and source conflicts. The art deliberately does not assign absent temperatures, pressures, stirring rates or microscopic structures. Final integrated browser review remains the root's responsibility.\n\nDeclared HRTEM/AFM SI remains unlocated and unverified; this is a complete supplied-main-paper review with an explicit SI gap.\n",encoding='utf8')
print(json.dumps({'module_sha256':report['module_sha256'],'contact_sheets':len(contacts),'scene_manifest_sha256':sha(V/'scene-manifest.json'),'canonical_manifest_sha256':sha(B/'canonical-record-manifest.json')}))
